### ISSUE TITLE
White screen overlay when minimizing & reopening the app and navigating on Android

### ISSUE THREAD

**Issue by rubina-shakhkyan** [software-mansion/react-native-screens#1010]
## Description

There's a white screen overlay on top of the screens when minimizing and reopening the app several times. 
There are 2 nested navigators. The issue is not always reproduced, but can happen after several trials.

## Steps To Reproduce

1. Close and reopen the app several times and try to navigate to one of the nested screens

## Package versions

- React: `16.x.x`
- React Native: `0.63.x`
- React Native Screens: `2.17.1`

**Comment by WoLewicki** [comment]
On what platform does it happen? Does it happen with the newest version of the package? Could you provide a simple repo with reproduction steps so we can work on it if it still exists?

**Comment by rubina-shakhkyan** [comment]
> On what platform does it happen? Does it happen with the newest version of the package? Could you provide a simple repo with reproduction steps so we can work on it if it still exists?

It happens on Android only. I tried versions `2.17.1`, `3.0.0` and `3.4.0`.

**Comment by WoLewicki** [comment]
OK so could you provide a simple repo with steps needed to reproduce the issue?

**Comment by rubina-shakhkyan** [comment]
> OK so could you provide a simple repo with steps needed to reproduce the issue?

Unfortunately, I cannot provide the repo, but the structure is similar to this one:
https://snack.expo.io/@react-navigation/stacks-in-tabs-v3

And the issue is fixed after flattening two navigators to one.

**Comment by rubina-shakhkyan** [comment]
The issue was caused by wrapping nested navigator in `KeyboardAvoidingView`
