### ISSUE TITLE
React/RCTImageView.h file not found

### ISSUE THREAD

**Issue by abhishekjadhav4** [software-mansion/react-native-screens#1011]
[package.txt](https://github.com/software-mansion/react-native-screens/files/6809722/package.txt)

Please find the attached package file.

I have linked the react-native-screens using react-native link react-native-screens.
Also tried upgrading react-native-screens to latest version.
The code is running for android but causing issue in iOS.

**Comment by WoLewicki** [comment]
I believe it is the same issue as #415, so I will close this one. Feel free to comment if I am wrong.

**Comment by abhishekjadhav4** [comment]
I have tried too many solutions, could you please share the exact solution by looking package.json. I would appreciate your efforts.

**Comment by WoLewicki** [comment]
If this comment does not fix your issue: https://github.com/software-mansion/react-native-screens/issues/415#issuecomment-724239829, it means you have transitioned through one of RN versions in a wrong manner. What `react-native` version are you using?
