### ISSUE TITLE
Memory leak due to HeaderLeft (Right, Center) functions is not removed before screen unmount

### ISSUE THREAD

**Issue by SDSLeon** [software-mansion/react-native-screens#1013]
## Description

Inside screen component CDM, I am using navigation.setOptions with headerRight function, after i go back to prev. screen setOptions object still present in memory with links on screen and all other objects. This object now can't be cleaned from memory, resulted in memory leak.

I can workaround it if I call setOptions({ headerRight: undefined }) before call goBack.

### Screenshots
![image](https://user-images.githubusercontent.com/6071034/125687439-3a2ff074-bc29-4979-887a-f357764b3987.png)
![image](https://user-images.githubusercontent.com/6071034/125687538-1ef1773a-b961-4805-8667-17b57c8684bc.png)
![image](https://user-images.githubusercontent.com/6071034/125688165-f1ee0783-516f-4f86-a319-fb3024189784.png)

## Steps To Reproduce

1. use setOptions inside component CDM with headerRight function
2. goBack to prev screen
3. find setOptions object in memory snapshot

### Expected behavior
setOptions object should be cleared when screen unmounted
### Actual behavior
setOptions object present in memory after screen unmounted
## Snack or minimal code example
https://github.com/SDSLeon/rns-memory-leak-example-1

## Package versions
- React: 17.0.2
- React Native: 0.64.2
- React Native Screens: 3.4.0

**Comment by SDSLeon** [comment]
screenshot from example
<img width="1658" alt="Снимок экрана 2021-07-15 в 15 14 52" src="https://user-images.githubusercontent.com/6071034/125788672-4be3b0f6-af3f-4c9e-b435-9b63929220c3.png">

**Comment by WoLewicki** [comment]
The leak is connected to not cleaning the options for screens after they get unmounted. It is controlled by `react-navigation`, and I am afraid there is nothing we can do in `react-native-screens` about it. Could you submit an issue in `react-navigation` repo concerning this and link this issue there? We will try to work on a solution for that. I will close this issue then, feel free to comment if something is wrong and we can reopen it then.
