### ISSUE TITLE
[Android] Navigating back from a screen embedding a WebView crashes the app (Expo SDK 42)

### ISSUE THREAD

**Issue by jsamr** [software-mansion/react-native-screens#1015]
## Description

Navigating back from a screen embedding a WebView on Android crashes the app. I guess it's a regression of #105.

## Steps To Reproduce

1. Navigate to a stack screen embedding a WebView
2. Navigate back to the home screen

### Expected behavior

No crash.

### Actual behavior

Crash.

## Snack or minimal code example

https://snack.expo.io/@jsamr/rnrh-webview-screens

## Package versions

- React: 16.13.1
- React Native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz
- React Native Screens: 3.4.0
- React Native Community Webview: 11.6.2

**Comment by WoLewicki** [comment]
@jsamr I reproduced the crash in the snack, but after setting `detachInactiveScreens={false}` on the navigator, which makes the navigator not use `react-native-screens` at all, the crash still happens. Can you confirm this? If so, I am afraid it is not an issue of `react-native-screens` and therefore there is nothing we can do about it in this library.

**Comment by jsamr** [comment]
@WoLewicki I can confirm by disabling this options the issue can't be reproduced. I'll repost at react-navigation, thank you!
