### ISSUE TITLE
V3 is laggy on Android

### ISSUE THREAD

**Issue by chungweileong94** [software-mansion/react-native-screens#1017]
## Description

I'm using React Navigation as my app navigation library, which at the time when I installed `react-native-screens` it was v2. So I decided to upgrade to the v3 to test it out and notices that there is a huge lag when navigating between screens, especially for those screens that contain huge listings. I decided to test out all the versions from `2.3.0` to `3.4.0`, and the lag issue only happens on `3.0.0` & above. 

One of the interesting parts I found out is that, during the process of testing, after I build & install the app (with v3) on Android, I decided to downgrade to v2 to prove my findings, and I forgot to stop my metro packager before I do a `yarn install`, surprisingly the lag issue fixed for some reason. This means the android native-side is using v3, while the JS-side of the `react-native-screens` is using v2, so I'm thinking maybe there is some implementation on the JS codebase in `react-native-screens` causing the lag issue. 

## Package versions

- React: 17.0.1
- React Native: 0.64.2
- React Native Screens: 3.4.0

**Comment by chungweileong94** [comment]
After digging into the code changes between `2.18.1` & `3.0.0`, there are not many changes except for the `enabledScreen` is now enabled by default. I manually disabled it in my code and it fixed the lag issue.

I think `react-navigation` should document this.

**Comment by WoLewicki** [comment]
What exactly do you mean by a lag issue? The blinking at the start of transition? If so, it is already documented in #111 and there are solutions provided for this behavior, e.g. https://github.com/software-mansion/react-native-screens/issues/111#issuecomment-757518915. Is there anything more we can help you with concerning this?

**Comment by chungweileong94** [comment]
@WoLewicki Well, blinking is one of the issues. But my problem is mainly the frame drop during the screens transition, it's very obvious since I'm using `TransitionPresets.SlideFromRightIOS`.

All the solutions I found in the [#111](https://github.com/software-mansion/react-native-screens/issues/111) that you mentioned only solve the blinking issue, but the frame drop issue will only get solved if I call `enableScreens(false)`

**Comment by WoLewicki** [comment]
Ok so we would need more information to look into this issue. 
- Can you tell on what devices does the frame drop happen? Is it visible on both platforms? Does it happen only on low-end devices?
- Do frame drops happen both when going forward and back?
- Can you post some video and a repo with the reproduction where it can be clearly seen that when `react-native-screens` are disabled, the performance is better, e.g. without visible frame drops?

**Comment by chungweileong94** [comment]
> Ok so we would need more information to look into this issue.
> 
> * Can you tell on what devices does the frame drop happen? Is it visible on both platforms? Does it happen only on low-end devices?
> * Do frame drops happen both when going forward and back?
> * Can you post some video and a repo with the reproduction where it can be clearly seen that when `react-native-screens` are disabled, the performance is better, e.g. without visible frame drops?

* I tested on both Xiaomi Mi A1 & Xiaomi Mi A2, it's only visible on Android low-end devices
* Yes, frame drops when navigating back & forward
* Not sure if you can see the lag in the video, and here's the repo: https://github.com/chungweileong94/ReactNavigationLagDemo

So while I creating this repo, I do notice that it only happened if I have a `FlatList` (or any `VirtualizedList`) nested in `ScrollView`. I know it's not ideal, but from the time being it's something I did for the actual RN project, where I basically have multiple horizontal `FlatList` & some complex layout nested in `ScrollView`.


https://user-images.githubusercontent.com/15154097/126341885-c02e8137-1345-4784-8b5c-bd78b9554ddd.mp4

**Comment by WoLewicki** [comment]
Thanks for all the information! Could you also post the video of how it behaves without `react-native-screens` switched on to compare the counter of dropped frames when navigating in the same way? The easiest way to do it will be providing [`detachInactiveScreens: false`](https://reactnavigation.org/docs/stack-navigator#detachinactivescreens) in here: https://github.com/chungweileong94/ReactNavigationLagDemo/blob/master/App.tsx#L113

**Comment by chungweileong94** [comment]
> Thanks for all the information! Could you also post the video of how it behaves without `react-native-screens` switched on to compare the counter of dropped frames when navigating in the same way? The easiest way to do it will be providing [`detachInactiveScreens: false`](https://reactnavigation.org/docs/stack-navigator#detachinactivescreens) in here: https://github.com/chungweileong94/ReactNavigationLagDemo/blob/master/App.tsx#L113

Here's the video without `react-native-screens` enabled.

https://user-images.githubusercontent.com/15154097/126345468-2da782ca-5389-4c38-ba7c-3a0b5d035b72.mp4

**Comment by jp928** [comment]
same here

**Comment by WoLewicki** [comment]
One issue I can think of might be searching through all of the children at the beginning of transition due to bug with `WebView`. Could you check if reverting the commit that fixed that issue resolves in acceptable performance? Here is the change: https://github.com/software-mansion/react-native-screens/pull/607/files#

**Comment by chungweileong94** [comment]
> One issue I can think of might be searching through all of the children at the beginning of transition due to bug with `WebView`. Could you check if reverting the commit that fixed that issue resolves in acceptable performance? Here is the change: https://github.com/software-mansion/react-native-screens/pull/607/files#

Tried that, and still the same.

**Comment by Ubax** [comment]
After some digging I think I found the issue. The laggy animation was caused by asynchronous attaching and detaching fragments.
I was able to fix it using #1066 code. 
One thing to note with about this PR is that it is a bit experimental change and some other bugs may occur. I you find any, please let us know.
