### ISSUE TITLE
android header have double the height.

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-screens#1028]
## Description

stack header appear to have double the height on android.

### Screenshots

![Screen Shot 2021-07-23 at 5 31 43 PM](https://user-images.githubusercontent.com/19273413/126805543-51e12d3e-bafb-42a4-8f07-c46fcbd708e1.png)

```tsx
const stack = createNativeStackNavigator();

export function App() {
  return (
    <NavigationContainer>
      <stack.Navigator>
        <stack.Screen
          name="home"
          component={Home}
          options={{
            title: 'Home',
          }}
        />
      </stack.Navigator>
    </NavigationContainer>
  );
}

function Home() {
  return <View />;
}
```

### Expected behavior

to have normal android header height

### Actual behavior

height appears to be doubled.

https://github.com/a-eid/RNSBug

**Comment by WoLewicki** [comment]
Can you check if it is not a duplicate of https://github.com/software-mansion/react-native-screens/issues/553?

**Comment by a-eid** [comment]
@WoLewicki it is `headerTopInsetEnabled` solved the issue, I need to learn more about it 

thank you.
