### ISSUE TITLE
Lottie Animation freezes for around 1 second during navigation

### ISSUE THREAD

**Issue by OscarYuen** [software-mansion/react-native-screens#104]
When I transit to the next screen in navigation, there would be a loading lottie animation component rendered but the animation would freeze for around 1 second and then play as normal again.

After removing useScreen(), the animation during transition of screen doesn't have freezing time

**Comment by WoLewicki** [comment]
Does the issue still exist with the newest version? Or can I close it? @OscarYuen

**Comment by OscarYuen** [comment]
> Does the issue still exist with the newest version? Or can I close it? @OscarYuen

It doesn't exist now. Thanks
