### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager.

### ISSUE THREAD

**Issue by thejadasari** [software-mansion/react-native-screens#1043]
### Screenshots
![image](https://user-images.githubusercontent.com/16138715/128824682-611d3960-ddab-4374-a7f3-c63df0454477.png)

### Expected behavior
Default page should load in App
### Actual behavior
Getting error.

ERROR  Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager.

This error is located at:
    in RNSScreenStackHeaderConfig (at HeaderConfig.tsx:100)
    in HeaderConfig (at NativeStackView.native.tsx:222)
    in RNSScreen (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at src/index.native.tsx:150)
    in Screen (at NativeStackView.native.tsx:175)
    in SceneView (at NativeStackView.native.tsx:276)
    in RNSScreenStack (at NativeStackView.native.tsx:267)
    in NativeStackViewInner (at NativeStackView.native.tsx:321)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:38)
    in SafeAreaProviderCompat (at NativeStackView.native.tsx:320)
    in NativeStackView (at createNativeStackNavigator.tsx:67)

## Package versions

- React: 17
- React Native: 0.64
- React Native Screens: 3.5.0
- React Navigation : 6.0.3

**Comment by WoLewicki** [comment]
Can you provide a simple repo with reproduction of the issue?

**Comment by thejadasari** [comment]
Thank you, I was able to pin point the issue.
In my android **mainApplication.java** file, we were clearing the packages returned by react native and manually linking the packages. In this step, we might have missed adding all auto linked packages.

commenting this code, resolved the issue.

**Comment by ArcherLucky** [comment]
> Thank you, I was able to pin point the issue.
> In my android **mainApplication.java** file, we were clearing the packages returned by react native and manually linking the packages. In this step, we might have missed adding all auto linked packages.
> 
> commenting this code, resolved the issue.

Thank you! I have same problem! I think it can be solved now!

**Comment by SurprisedTao** [comment]
> Thank you, I was able to pin point the issue.
> In my android **mainApplication.java** file, we were clearing the packages returned by react native and manually linking the packages. In this step, we might have missed adding all auto linked packages.
> 
> commenting this code, resolved the issue.

Hello, I am a newbie to RN. Encountered the same problem as you, can you explain in detail how you solved this problem

**Comment by ArcherLucky** [comment]
> Can you provide a simple repo with reproduction of the issue?

resolved, my project rn version is 0.6+, but still need   manually link native pkg, thank u very match!
