### ISSUE TITLE
Android Header not targetable with physical keyboard

### ISSUE THREAD

**Issue by gp3gp3gp3** [software-mansion/react-native-screens#1045]
## Description

When using the header option for any portion of the header (left, center, right), the header component is not targetable by physical keyboards.  This is problematic for apps that need to meet accessibility standards.

My assumption is that the toolbar defined in the [ScreenStackHeaderConfig](https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.java#L73) is the culprit.  Since this is not extending from the react view, I think the accessibility attributes are being skipped over.

I naively tried setting `ViewCompat.setImportantForAccessibility(mToolbar, ViewCompat.IMPORTANT_FOR_ACCESSIBILITY_YES);` in the `ScreenStackHeaderConfig`, but this does not address the issue.

A11Y is critically important for our application, and frequently overlooked in the react native community.  Until this is addressed I need to remove the native stack navigator for the standard one provided via react navigation unfortunately.  I hope this can be looked into so we can use the excellent performance benefits of this library to its full potential.

## Steps To Reproduce

1.  Create screen with header component in stack
2. Connect Android phone to bluetooth keyboard, or through usb port
3.  Navigate around screen using keyboard arrows or tab / shift + tab
4.  Notice header does not target like all touchables do in screen

### Expected behavior

Touchable buttons in header are targetable

### Actual behavior

All keyboard navigation targets end below the header component.

## Package versions

- React: 17.0.1
- React Native: 0.64.1
- React Native Screens: 3.3.0

**Comment by Ubax** [comment]
@gp3gp3gp3 Just to make sure we are thinking about the same behavior. 
Did you try using Meta+Tab to go to header?
The header is a different (navigation cluster)[https://developer.android.com/about/versions/oreo/android-8.0#kbnc] then the rest of the app. 
On my android device I was able to focus a button that was placed in the header.

**Comment by Ubax** [comment]
@gp3gp3gp3 I'm closing it for now. If the issue still occurs with the instructions I provided above, please let us know.

**Comment by peckomingo** [comment]
Could we please reopen this issue? I am experiencing the same problem. Additionally, accessibility is legally important in our country.
