### ISSUE TITLE
[android] modal isn't shown above absolute view (different to ios) 

### ISSUE THREAD

**Issue by hannojg** [software-mansion/react-native-screens#1053]
### Current behavior

We have a custom pervasive header in our app that should be shown on any page. We implemented it in App.tsx like this:

```jsx
<View>
  <NavigationContainer>
  {/* ... */}
  </NavigationContainer>
  <View style={StyleSheet.absoluteFill}>
    <TopBar />
  </View>
</View>
```

When opening a `transparentModal` the behaviour on iOS and android is different:

### Behavior android:

As you can see in the video, the screen that is opened as modal will be behind the custom header view.

https://user-images.githubusercontent.com/16821682/129566322-1f2bee7a-611f-423d-a10f-b152cf5b7201.mp4

_Note:_ We already tried to fix this by playing with zIndex, which didn't help.

### Behavior iOS (correct):

https://user-images.githubusercontent.com/16821682/129566015-84fdd439-b711-4211-bf15-7b1c257edef7.mp4

Here the screen is shown above anything else which is what we are expecting.

### Reproduction

https://snack.expo.dev/@skillnation/react-navigation-v6-modal-reproduction

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.2
| @react-navigation/stack                | 6.0.6
| @react-navigation/native-stack         | 3.4.0
| react-native-screens                   | 3.4.0
| react-native-gesture-handler           | 1.10.2
| react-native-reanimated                | 2.2.0
| react-native                           | 0.64.2
| expo                                   | 42.0.1
| node                                   | v15
| npm or yarn                            | v7

**Comment by WoLewicki** [comment]
Based on your code, if the header is above the `NavigationContainer` and not inside the `Screen` component, the Android's behavior seems more reasonable. The fact that the modal is rendered on top of header on iOS is consequence of how the modality works there, rendering a new view on top of all of the content. You can use `containedTransparentModal` to see the same behavior as on Android. I am not sure if we can help with this since it is rather expected behavior. Can I help you more with this or can this be closed?

**Comment by hannojg** [comment]
Thanks for getting back to me! So the thing is we need the same behaviour on android as it is on iOS.
I can see that with `containedTransparentModal` iOS works like android, but we need it the other way around.

I understand that part of the reason that it is how it is is due to how modality works on android/iOS. It's a bit of a headache when you write code in RN, expecting it to work the same just to find out that there are platform differences.

Do you have any ideas on how this could be circumvented and to achieve the same effect on android? Including the header on each screen isn't an option, because then it would be part of the transition and wouldn't stay persuasive above all content all the time.

**Comment by WoLewicki** [comment]
It would require something analogous to `RNSFullWindowOverlay` (you can read more about it here: https://github.com/software-mansion/react-native-screens/issues/525 and in connected PR) from `iOS`, but on Android. You would need to add the view at the top of all the other content, on `iOS` it is done by adding a view directly to the `window` and maybe it is the same on `Android`.

**Comment by WoLewicki** [comment]
I will close this issue since it's been inactive for quite a while.  Feel free to comment here if there is something to add and we can reopen it then.

**Comment by danieloi** [comment]
Same issue here

**Comment by tolypash** [comment]
+1
