### ISSUE TITLE
"RNSScreenStackHeaderConfig" was not found in the UIManager.

### ISSUE THREAD

**Issue by BartoszKlonowski** [software-mansion/react-native-screens#1060]
## Description

I've implemented very basic RNW app using:
```
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "@react-navigation/stack": "^5.14.5",
    "metro-config": "^0.66.2",
    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-reanimated": "^2.2.0",
    "react-native-safe-area-context": "^3.3.0",
    "react-native-screens": "^3.5.0",
    "react-native-windows": "^0.64.0-0"
  },
```
and I'm facing the following error when having `<Stack.Screen name="Home" component={HomeScreen} />` with an empty `<View></View>` in it.
The error is:
```
Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager.

This error is located at:
    in RNSScreenStackHeaderConfig (at HeaderConfig.tsx:101)
    in HeaderConfig (at NativeStackView.native.tsx:222)
    in RNSScreen (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at src/index.native.tsx:150)
    in Screen (at NativeStackView.native.tsx:175)
    in SceneView (at NativeStackView.native.tsx:276)
    in RNSScreenStack (at NativeStackView.native.tsx:267)
    in NativeStackViewInner (at NativeStackView.native.tsx:321)
    in RCTView (at View.windows.js:52)
    in View (at CompatNativeSafeAreaProvider.tsx:28)
    in CompatNativeSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:46)
    in SafeAreaProviderCompat (at NativeStackView.native.tsx:320)
    in NativeStackView (at createNativeStackNavigator.tsx:67)
    in NativeStackNavigator (at App.js:78)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:429)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at App.js:77)
    in App (at renderApplication.js:47)
    in RCTView (at View.windows.js:52)
    in View (at AppContainer.js:107)
    in RCTView (at View.windows.js:52)
    in View (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40)
```
which is displayed in the app window as a red box with:
`folly::toJson: JSON object value was a NaN or INF`

### Screenshots
![obraz](https://user-images.githubusercontent.com/70535775/129968954-9b4ed14f-e28b-4030-b258-5685c7efa32e.png)
![obraz](https://user-images.githubusercontent.com/70535775/129969022-3a2110b8-9a0c-4788-9332-06bd1a87efeb.png)

## Steps To Reproduce

1. Basically follow the guide of [react-navigation: Getting Started](https://reactnavigation.org/docs/getting-started) or use the minimal code example below.

## Snack or minimal code example

```
import React from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
  Button,
  Linking,
} from 'react-native';

import {Colors} from 'react-native/Libraries/NewAppScreen';

import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';

const Stack = createNativeStackNavigator();

const HomeScreen = ({navigation}) => {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const App = () => {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};
```

## Package versions

- React: 17.0.1
- React Native: 0.64.2
- React Native Screens: 3.5.0

**Comment by WoLewicki** [comment]
Did you follow all the steps required to run the `windows` app? Can you check if the code works if you switch the `native-stack` to e.g. `stack` or `bottom-tabs` navigator? Also cc @tritao since you added the basic `windows` implementation.

**Comment by BartoszKlonowski** [comment]
@WoLewicki Thank you for the response!
I was using the `stack` at the beginning, but when I double checked if I have everything what is needed, I saw the `native-stack` instead of `stack` and I tried to use this  -  that's why it is there, but the error is the same for both.

**Comment by WoLewicki** [comment]
Hmm, but `RNSScreenStackHeaderConfig` is not used in `stack` navigator. I cannot say much more unfortunately, all I can advise is for you to check the README of `windows` folder, especially this: https://github.com/software-mansion/react-native-screens/tree/master/windows#automatic-install-with-autolinking-on-rnw--063.

**Comment by BartoszKlonowski** [comment]
Now that is interesting:
I'm using 0.64.x which means that autolinking should work, but there's no `RNScreens` project added to my solution when I check it in Visual Studio.
So I decided to manually link it, **but:**
when I go to *node_modules/* there's no *windows/* directory at all:
```
PS C:\Dev\ReproProjects\example> cd .\node_modules\react-native-screens\
PS C:\Dev\ReproProjects\example\node_modules\react-native-screens> dir


    Directory: C:\Dev\ReproProjects\example\node_modules\react-native-screens


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        19.08.2021     11:37                android
d-----        19.08.2021     11:37                createNativeStackNavigator
d-----        19.08.2021     11:37                ios
d-----        19.08.2021     11:37                lib
d-----        19.08.2021     11:37                native-stack
d-----        19.08.2021     11:37                node_modules
d-----        19.08.2021     11:37                src
-a----        18.08.2021     21:45           1084 LICENSE
-a----        18.08.2021     21:45           3731 package.json
-a----        18.08.2021     21:45           5990 README.md
-a----        18.08.2021     21:45            880 RNScreens.podspec
```
I've double checked whether I install it correctly and what I do is just: `yarn add react-native-screens` (also tried with `--dev`).

What am I missing?

**Comment by WoLewicki** [comment]
Oh, yeah that might be a problem then. I think that by mistake the `windows` folder was not added to the files published on npm (here is PR adding it: https://github.com/software-mansion/react-native-screens/pull/1050). That would make sense then. I am afraid that till the next version of `react-native-screens`, you have to manually add the `windows` folder to the package 😞  and then probably link it manually too.

**Comment by BartoszKlonowski** [comment]
Unfortunately this workaround ends with hundreds of syntax errors like:
![obraz](https://user-images.githubusercontent.com/70535775/130053518-e8ccc776-246a-41d3-978e-679a6c071ba3.png)

I'm afraid I will just wait for the next release and then I'll try to use this.
But still: Thank you for the support!

**Comment by icaru88** [comment]
same issue here

**Comment by kacperkapusciak** [comment]
Hi @BartoszKlonowski, @icaru88 
This issue should be now resolved by newest version of `react-native-screens` - [v3.6.0](https://github.com/software-mansion/react-native-screens/releases/tag/3.6.0). Please upgrade the dependency to the newest version.

I'll close this issue for now. If you encounter any problems with this don't hesitate to comment here and I'll reopen the issue.
Cheers 🙌

**Comment by McDreamy** [comment]
Hi, I'm having this issue on react native macOS
