### ISSUE TITLE
Okay, now that I'm thinking about it, we could have a channel for disclosing some kind of security issue. I'm having a hard time imagining one, because none of our outputs include running code, but unknown-unknowns, etc. Fine.

### ISSUE THREAD

**Issue by 556677152** [software-mansion/react-native-screens#1069]
Okay, now that I'm thinking about it, we could have a channel for disclosing some kind of security issue. I'm having a hard time imagining one, because none of our outputs include running code, but unknown-unknowns, etc. Fine.

This PR as of today, nearly a month into its life, is still just template content. @Tomtam25 do you intend to fill this in? Is it your intent to get _us_ to fill it in?

_Originally posted by @ben in https://github.com/progit/progit2/pull/1692#issuecomment-901950382_

**Comment by WoLewicki** [comment]
I'm closing this issue due to not following the contributing guidelines for `react-native-screens`.

For more information see [contributing guide](https://github.com/software-mansion/react-native-screens/blob/master/guides/CONTRIBUTING.md).
