### ISSUE TITLE
3.6.0 breaks android build with minSdk = 21

### ISSUE THREAD

**Issue by gersomvg** [software-mansion/react-native-screens#1078]
## Description

When running a `detox build` I encountered this error:

```
> Transform classes.jar (project :react-native-screens) with DexingNoClasspathTransform
D8: Invoke-customs are only supported starting with Android O (--min-api 26)

> Task :react-native-screens:mergeExtDexDebugAndroidTest FAILED
D8: Default interface methods are only supported starting with Android N (--min-api 24): Landroidx/core/internal/view/SupportMenuItem;setTooltipText(Ljava/lang/CharSequence;)Landroid/view/MenuItem;

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:mergeExtDexDebugAndroidTest'.
> Could not resolve all files for configuration ':react-native-screens:debugAndroidTestRuntimeClasspath'.
   > Failed to transform core-1.6.0.aar (androidx.core:core:1.6.0) to match attributes {artifactType=android-dex, dexing-enable-desugaring=false, dexing-incremental-transform=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: /Users/gersom/.gradle/caches/transforms-2/files-2.1/f0a4e8860191b7f240fa7158c7252c34/core-1.6.0-runtime.jar.
         > Error while dexing.
           The dependency contains Java 8 bytecode. Please enable desugaring by adding the following to build.gradle
           android {
               compileOptions {
                   sourceCompatibility 1.8
                   targetCompatibility 1.8
               }
           }
           See https://developer.android.com/studio/write/java8-support.html for details. Alternatively, increase the minSdkVersion to 24 or above.
```

I actually have the suggested compileOptions in my build.gradle. Setting the minSdk option from 21 to 26 fixes it, but we don't want this in our project.

I have the feeling this might have to do with the new Kotlin code in 3.6.0?

## Steps To Reproduce

1. Build android project with minSdk 21 and react-native-screens@3.6.0

### Expected behavior

It builds.

### Actual behavior

It throws the above error.

## Snack or minimal code example

I can set this up later, but first checking if this is needed. :v:

## Package versions

- React: 17.0.1
- React Native: 0.64.2
- React Native Screens: 3.6.0

**Comment by gersomvg** [comment]
@kacperkapusciak I'll find some time this week to try and make a minimal reproduction.

It is probably some interaction with the setup I've done for other dependencies, but downgrading react-native-screens to 3.5.0 instantly fixes it for me.

**Comment by dantenol** [comment]
Having the same issue here, using the latest 3.7.2. I found other packages facing the same error and [this](https://github.com/OneSignal/react-native-onesignal/issues/1235) had the (temporary) solution.

Just adding the lines the own error provides on the package's gradle file solves it. I'm currently using patch-package to edit the file and make Detox build properly.

I don't think only adding these lines is a definitive solution. I expect it to be completely solved on future versions.

**Comment by kacperkapusciak** [comment]
@dantenol there's nothing more permanent than a temporary solution 😅  

This solution is directly stated in the error message but I was completely blinded by the issue stating that it has to do with `minSdkVersion`. Thank you for pointing the solution out!

@gersomvg Could you confirm that #1135 fixes this issue?

Cheers
