### ISSUE TITLE
iOS SearchBar 'cancel' button text change?

### ISSUE THREAD

**Issue by vlkmx** [software-mansion/react-native-screens#1081]
### Discussed in https://github.com/software-mansion/react-native-screens/discussions/1080

<div type='discussions-op-text'>

<sup>Originally posted by **vlkmx** August 25, 2021</sup>

Is there any support for changing the 'cancel' title to any other?

<img width="162" alt="Снимок экрана 2021-08-25 в 16 08 04" src="https://user-images.githubusercontent.com/12006166/130796266-de403a24-c472-4a6f-b242-33143496edfc.png">
</div>

**Comment by WoLewicki** [comment]
@vlkmx can you check if https://github.com/software-mansion/react-native-screens/pull/1108 is what you need?

**Comment by vlkmx** [comment]
@WoLewicki yep, thanks!
