### ISSUE TITLE
3.6.0 update causes `Could not find method ktlint() for arguments [com.pinterest:ktlint:0.40.0]` error

### ISSUE THREAD

**Issue by ElviraBurchik** [software-mansion/react-native-screens#1085]
## Description

When upgrading to 3.6.0 Android build fails with the following error:
```
FAILURE: Build failed with an exception.

* Where:
Build file 'node_modules/react-native-screens/android/build.gradle' line: 61

* What went wrong:
A problem occurred evaluating project ':react-native-screens'.
> Could not find method ktlint() for arguments [com.pinterest:ktlint:0.40.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

## Steps To Reproduce

1. Build Android project with `react-native-screens@3.6.0`

### Expected behavior

It builds successfully 🤞

### Actual behavior

It throws the above error ⬆️

## Package versions

- React: 17.0.1
- React Native: 0.63.3
- React Native Screens: 3.6.0

Our setup is a monorepo, if it's relevant.

**Comment by kacperkapusciak** [comment]
@ElviraBurchik could you check if applying changes from https://github.com/software-mansion/react-native-screens/pull/1093 fixes your issue?

**Comment by ElviraBurchik** [comment]
Hi @kacperkapusciak 

I've been off last week and couldn't respond. I'm going to try the changes again today, but before I switched off it didn't help. I'll check again and reopen the issue if it's still valid, okay?

**Comment by kacperkapusciak** [comment]
@ElviraBurchik
Sure! Sorry for not waiting just a little bit longer with merging this PR. Just let me know and I'll reopen if It didn't help.

**Comment by ElviraBurchik** [comment]
I've tested the fix and it works, thank you @kacperkapusciak 🙌 
Looking forward to the next release.
