### ISSUE TITLE
v3.6.0 - Task: react-native-screens:ktlint FAILED

### ISSUE THREAD

**Issue by brunorafaeI** [software-mansion/react-native-screens#1090]
## Description

When I'm trying to build my project I have this issue : 

```
...
~/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/StackFinishTransitioningEvent.kt:19:1: Unexpected indentation (4) (should be 2)
~/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/StackFinishTransitioningEvent.kt:20:2: Redundant newline (\n) at the end of file

> Task :react-native-screens:ktlint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:ktlint'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

## Steps To Reproduce

1. Build Android project with @react-navigation/native
### Expected behavior
It builds successfully 🤞
### Actual behavior
It throws the above error ⬆️
## Additional Information
I'm using WSL2 (Debian 10 buster) to run my project and running the emulator from windows 10 64 bits, it was worked very well before trying to install @react-navigation/native

## Package versions

- React: 17.0.2
- React Native: 0.65.1
- React Native Screens: 3.6.0

**Comment by brunorafaeI** [comment]
Hi there!

I've changed the version of java to OpenJDK 8 and executed "./gradlew clean", but I have the same error!
Someone can help me pls?

**Comment by kacperkapusciak** [comment]
Hi @brunorafaeI,
It looks like a script or someone by hand changed Android files in the `node_modules/react-native-screens/` directory.
Reinstalling `react-native-screens` should fix your issue.
```
yarn remove react-native-screens
yarn add react-native-screens
```
Or remove the whole `node_modules` directory and reinstall packages with `yarn`.
If it doesn't help, could you provide a full, complete error message?

Cheers

**Comment by brunorafaeI** [comment]
> Hi @brunorafaeI,
> It looks like a script or someone by hand changed Android files in the `node_modules/react-native-screens/` directory.
> Reinstalling `react-native-screens` should fix your issue.
> 
> ```
> yarn remove react-native-screens
> yarn add react-native-screens
> ```
> 
> Or remove the whole `node_modules` directory and reinstall packages with `yarn`.
> If it doesn't help, could you provide a full, complete error message?
> 
> Cheers

Hi @kacperkapusciak,

Thanks for your response! I did what you mentioned, but I still have the same error 👍 

```
t.kt:10:1: Unexpected indentation (4) (should be 2)
/home/brafael/bootcamp/nv03/mobile/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/StackFinishTransitioningEvent.kt:11:1: Unexpected indentation (4) (should be 2)
/home/brafael/bootcamp/nv03/mobile/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/StackFinishTransitioningEvent.kt:13:1: Unexpected indentation (4) (should be 2)
/home/brafael/bootcamp/nv03/mobile/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/StackFinishTransitioningEvent.kt:14:1: Unexpected indentation (8) (should be 4)
/home/brafael/bootcamp/nv03/mobile/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/StackFinishTransitioningEvent.kt:15:1: Unexpected indentation (4) (should be 2)
/home/brafael/bootcamp/nv03/mobile/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/StackFinishTransitioningEvent.kt:17:1: Unexpected indentation (4) (should be 2)
/home/brafael/bootcamp/nv03/mobile/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/StackFinishTransitioningEvent.kt:18:1: Unexpected indentation (8) (should be 4)
/home/brafael/bootcamp/nv03/mobile/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/StackFinishTransitioningEvent.kt:19:1: Unexpected indentation (4) (should be 2)
/home/brafael/bootcamp/nv03/mobile/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/StackFinishTransitioningEvent.kt:20:2: Redundant newline (\n) at the end of file

> Task :react-native-screens:ktlint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:ktlint'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 44s
291 actionable tasks: 291 executed
error Failed to build the app.
Error: Command failed: ./gradlew build -x lint
    at makeError (/home/brafael/bootcamp/nv03/mobile/node_modules/execa/index.js:174:9)
    at Function.module.exports.sync (/home/brafael/bootcamp/nv03/mobile/node_modules/execa/index.js:338:15)
    at buildApk (/home/brafael/bootcamp/nv03/mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:181:22)
    at runOnSpecificDevice (/home/brafael/bootcamp/nv03/mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:162:7)
    at buildAndRun (/home/brafael/bootcamp/nv03/mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:147:12)
    at /home/brafael/bootcamp/nv03/mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:132:12
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Command.handleAction (/home/brafael/bootcamp/nv03/mobile/node_modules/@react-native-community/cli/build/index.js:186:9)
```

**Comment by brunorafaeI** [comment]
Any help?

```
info Fetching system and libraries information...
System:
    OS: Linux 5.10 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 2.43 GB / 12.40 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.4/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by kacperkapusciak** [comment]
@brunorafaeI could you check if applying changes from https://github.com/software-mansion/react-native-screens/pull/1093 fixes your issue?

E.g. you can install package directly from branch with `yarn add git+https://github.com/software-mansion/react-native-screens#@kacperkapusciak/add-spotless` or change files by hand

**Comment by brunorafaeI** [comment]
@kacperkapusciak thanks so much!! its works now very well, ca I know what is the problem? and I'll stay with this version of react-native-screens instead of the official version ??

**Comment by kacperkapusciak** [comment]
@brunorafaeI probably next week we'll release next version of `screens` with this change so till this time you'll have to keep using this fix.

Linters are used to check for code quality and error out when something isn't like it's supposed to be. Previous configuration checked not only when *we* were developing but also on the user's (yours!) computer when using our library. That wouldn't be a problem by itself but somehow your code in `node_modules` differs slightly or uses different formatting than we are. In short - we used linter that worked a bit too well :) 

If I'd have to guess, your IDE automatically reformats code to your preffered style including `node_modules` directory. Normally developers shouldn't change anything in `node_modules` unless they have a specific purpose 🙂 

Cheers

**Comment by brunorafaeI** [comment]
> @brunorafaeI probably next week we'll release next version of `screens` with this change so till this time you'll have to keep using this fix.
> 
> Linters are used to check for code quality and error out when something isn't like it's supposed to be. Previous configuration checked not only when _we_ were developing but also on the user's (yours!) computer when using our library. That wouldn't be a problem by itself but somehow your code in `node_modules` differs slightly or uses different formatting than we are. In short - we used linter that worked a bit too well :)
> 
> If I'd have to guess, your IDE automatically reformats code to your preffered style including `node_modules` directory. Normally developers shouldn't change anything in `node_modules` unless they have a specific purpose 🙂
> 
> Cheers

@kacperkapusciak  I get it, maybe this was the cause of the problem (I replaced the native .editorconfig file for this) :

```
# top-most EditorConfig file
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = false
insert_final_newline = false
```

Could you confirm me if I'm right?

**Comment by brunorafaeI** [comment]
Hey, is this fix not available in the release version yet?

**Comment by kacperkapusciak** [comment]
@brunorafaeI version with this fix went live a few hours after your comment 🙂  You can now upgrade Screens to v3.7.0👍
