### ISSUE TITLE
ScreenContainer is not attached under ReactRootView with react navigation 6

### ISSUE THREAD

**Issue by AmolFC** [software-mansion/react-native-screens#1111]
I am trying to open StackNavigator as modal like following : 
```
<Modal>
<StackNavigator>
</Modal>
```
This is working fine if I am using React Native Screens version 2.18.1 or below.
But if I upgrade to any 3.0.0+ version app is crashing in above case with "ScreenContainer is not attached under ReactRootView " error.
I have also tried "enableScreens(false)" but still getting crash.

- React:17.0.1
- React Native:0.64.2
- React Native Screens:3.6.0
- React Navigation 6

![Screenshot_1631022084](https://user-images.githubusercontent.com/65066755/132354997-45529b7a-58e5-4036-8670-29dd08c88b2a.png)

Please let me know if more details needed. 
Thank you.

**Comment by kacperkapusciak** [comment]
Hi @AmolFC 
We don't support rendering navigators outside of the children of `ReactRootView`. You can use `detachInactiveScreens: false` flag to turn off `react-native-screens` in those cases.

Also, I'm a bit confused about what you are trying to achieve. Isn't maybe using the `presentation: 'modal'` option on StackNavigator something that would help you?

Cheers
