### ISSUE TITLE
[Android] WARNING: API 'variant.getJavaCompile()'

### ISSUE THREAD

**Issue by paolospag** [software-mansion/react-native-screens#112]
I get this error while the app is compiled with `Gradle v5.4.1`:

```
> Configure project :react-native-screens
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
```

**Comment by hamidfzm** [comment]
Same issue...

**Comment by nagad814** [comment]
same here

**Comment by Gazzini** [comment]
same

**Comment by jhoanborges** [comment]
Same issue... i tried to change it to getJavaCompileProvider. But is not working.

**Comment by A-Yatsyk** [comment]
Update your classpath dependency in project level Gradle `android/build.gradle`

`
buildscript {
    // ... repositories, etc. ...

    dependencies {
        // ...other dependencies ...
        classpath 'com.android.tools.build:gradle:3.5.2'
    }
}
`

**Comment by WoLewicki** [comment]
It looks like this issue is outdated, so I am closing it. Feel free to comment if I am wrong.
