### ISSUE TITLE
SearchBar not appearing

### ISSUE THREAD

**Issue by phhoef** [software-mansion/react-native-screens#1124]
## Description
`SearchBar` is not appearing.

## Steps To Reproduce

1. Add SearchBar to a view

## Snack or minimal code example
```
    <View style={ROOT}>
      <View style={HEADER_CONTAINER}>
        <Text preset="header" tx="searchScreen.header" />
      </View>
      <SearchBar placeholder="test" />
      <SectionList
        style={RESULT_LIST}
        sections={sections}
        keyExtractor={(item, index) => item + index}
        renderSectionHeader={renderSectionHeader}
        renderItem={renderItem}
        extraData={{ extraDataForMobX: trucks.length > 0 ? trucks[0].id : "" }}
        onRefresh={fetchData}
        refreshing={refreshing}
        scrollEnabled={true}
      />
    </View>
```

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Screens: 3.4.0
- Expo: 42.0.0

**Comment by Ubax** [comment]
@phhoef to use the search bar you need to pass options to screen. Please take a look at our [example app](https://github.com/software-mansion/react-native-screens/blob/master/Example/src/screens/SearchBar.tsx).

For now I close the issue, since it is not valid.
