### ISSUE TITLE
Going back does not recalculate screen height when parent height is dynamic

### ISSUE THREAD

**Issue by somebody32** [software-mansion/react-native-screens#1140]
## Description

I have a native stack navigator inside a bottom sheet. The bottom sheet's height is dynamic and depends on the currently focused screen. The problem is when going from a taller screen into a smaller one and then back `UIViewControllerWrapperView` and its children (`RNSScreen & RNSScreenView`) stay the size of the previous screen (check flipper screenshot below). Visually it is not changing anything, but taps are not registered anywhere below the old height.

### Screenshots
Here I have the first screen where the whole area is tappable and navigates to the second small screen. When coming back, I can not tap anymore below the top 100px (the height of the second screen).

https://user-images.githubusercontent.com/25742/133996001-1c2a7f48-0220-40af-b4bf-c71c53cde0a7.mov

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/25742/133996127-1e99bdd5-a05f-44cf-9c88-8df4c47105fa.png">

Currently, I'm changing the height via the `useFocusEffect` hook from react-navigation. The problem can go away if I do that on `transitionEnd`, but that would highly delay the animation.

I would be happy to start working on a snack but maybe there is a fast solution that I'm not aware of?

## Package versions
- React: 17.0.2
- React Native: 0.65.1
- React Native Screens: 3.7.2

**Comment by WoLewicki** [comment]
I think the repro is necessary here since it seems like the native screen height passed to the `RNSScreenView` component is wrong for some reason and I see no quick solution to that.

**Comment by somebody32** [comment]
@WoLewicki here you have it, hope it helps https://github.com/somebody32/RNScreensHeightRepro
tried to put in on snack, but the exact bottom sheet lib version doesn't resolve there.

**Comment by WoLewicki** [comment]
I tested the repro you provided and when I swipe to go back, it works correctly. I think the problem comes from the fact that you use `useFocusEffect`, which is not a best option for `native-stack` since it is fired at the beginning of transition when navigating from JS, and at that moment the correct layouts are not set yet. When navigating natively, it is fired only after the transition is done, and it resolves in the proper behavior. Isn't the usage of `transitionEnd` proper from the visual point of view, where you first navigate, and then the bottomSheet gets the correct view? Also, it makes it consistent with navigating natively.

**Comment by somebody32** [comment]
Thank you, @WoLewicki. 

Yes, I understand that switching to `transitionEnd` would fix the issue, but visually it would be a way worse experience: now the sheet expands simultaneously when navigation happens, but with `transitionEnd` navigation starts first, a user sees cut off screen for some time, and then sheet springs to the required height.

Also, some more notes I did while debugging, I hope you could find them useful, all of them are related to `useFocusEffect`
* only swiping back "fixes" the issue, navigating via back button or via `navigation.navigate` suffers
* js stack (`createStackNavigator`) doesn't have this problem
* trying to set the height once more does nothing, ie trying to have `useFocusEffect` and then doing the same on `transitionEnd`. But I suspect memoization somewhere in the bottom sheet lib that does this. So could be fixed by applying random fraction to trigger refresh: `setBottomSheetHeight(400 + random(0.1);`

I agree that for now, this looks more like a userland problem, but there is still inconsistent behavior with js-stack and different navigation methods (swipe back/navigate)

**Comment by WoLewicki** [comment]
> * only swiping back "fixes" the issue, navigating via back button or via `navigation.navigate` suffers
> * js stack (`createStackNavigator`) doesn't have this problem

header back button does not work for me in both navigators, which is weird and I have no idea why.

> * trying to set the height once more does nothing, ie trying to have `useFocusEffect` and then doing the same on `transitionEnd`. But I suspect memoization somewhere in the bottom sheet lib that does this. So could be fixed by applying random fraction to trigger refresh: `setBottomSheetHeight(400 + random(0.1);`

Unfortunately I have no knowledge of the implementation of `bottom-sheet`. Maybe it would be good to submit this issue in its repo too, maybe the authors can say more about it and then we can collaborate how to fix the issues.

**Comment by somebody32** [comment]
@WoLewicki I've just pushed another commit that fixes the back button and removes the bottom sheet lib: I'm using plain reanimated now to imitate it.

So I can confirm that:
1. back button or swipe back fix the issue, but the bottom sheet animation is delayed, because `useFocusEffect` fires later for some reason
2. setting value `onTransitionEnd` together with `useFocusEffect` does nothing and not expanding the view
3. js-version (`createStackNavigator`) does not have this problem, you can swap `createNativeStackNavigator` for `createStackNavigator` to see that

**Comment by WoLewicki** [comment]
1. and 3. are caused by the native navigation, which was said in [previous comment](https://github.com/software-mansion/react-native-screens/issues/1140#issuecomment-925833241).
2. is probably due to the memoization or just how react works.
 
`createStackNavigator` does not use native animation transition options, it is fully controlled from the JS by `Animated` and `react-native-gesture-handler`. I am not sure if we can do much about it unfortunately.

**Comment by somebody32** [comment]
@WoLewicki got it, thanks. So I'll close the issue if nothing can be done here.

For anyone having the same problem, here is a fast hack that minimizes it:

```tsx
let isFocused = useRef(true);
let sheetHeight = 400;

useFocusEffect(
  useCallback(() => {
    setBottomSheetHeight(sheetHeight);
  }, [setBottomSheetHeight, sheetHeight])
);

useEffect(() => {
  return navigation.addListener('focus', () => {
    isFocused.current = true;
  });
}, [navigation]);

useEffect(() => {
  return navigation.addListener('blur', () => {
    isFocused.current = false;
  });
}, [navigation]);

useEffect(() => {
  return navigation.addListener('transitionEnd', () => {
    if (!isFocused.current) {
      return;
    }

    // this is required to allow navigational controller to get new
    // view height, otherwise it would use the cached one from the previous
    // screen. And no, setImmediate is not working,
    // and yes, 0.3 is the minimum value that works
    setBottomSheetHeight(sheetHeight + 0.3);
    setTimeout(() => {
      setBottomSheetHeight(sheetHeight);
    }, 0);
  });
}, [navigation, setBottomSheetHeight, sheetHeight]);
```
