### ISSUE TITLE
Loader doesn't show up if refreshing is true during List initial render

### ISSUE THREAD

**Issue by yangm97** [software-mansion/react-native-screens#1141]
## Steps To Reproduce

1.

## Snack or minimal code example

https://snack.expo.dev/aZqH76ryl

## Package versions

- React:
- React Native:
- React Native Screens:

**Comment by WoLewicki** [comment]
I debugged it a little and it seems like a bug in the logic of setting the frame of `contentOffset` in `RCTScrollView` when adding `refreshControl` and applying `frame` by `RNSScreen`. The workaround for this is to set the `refreshing` to `true` after the transition is over and all layouts are correct. It can be done e.g. like this:
```tsx
  React.useEffect(() => {
    navigation.addListener('transitionEnd', () => {
      setRefreshing(true)
    });
  })
  const [refreshing, setRefreshing] = React.useState(false);

  return (
    <FlatList refreshing={refreshing} ...
```

Can I help you more with this?

**Comment by WoLewicki** [comment]
From your reaction I assume the solution works. I will close this issue then. Feel free to comment if something is wrong.
