### ISSUE TITLE
screenOrientation prop not work

### ISSUE THREAD

**Issue by zwh1666258377** [software-mansion/react-native-screens#1152]
## Description

https://reactnavigation.org/docs/native-stack-navigator/#orientation

when I set this prop,The screen does not rotate after entering the target page.

### Expected behavior

I hope screen rotate after entering the target page.

### Actual behavior
have not rotate 

## Snack or minimal code example

Here are some tips for providing a minimal example: [Snack](https://snack.expo.dev/9LZ5ItpXl )

## Package versions

- React: 16.13.1
- React Native: 0.64
- React Native Screens:~3.4.0

**Comment by kacperkapusciak** [comment]
Hi @zwh1666258377, 
we've investigated the issue and partnered with Expo in order to solve this problem. The issue lays with Expo overriding orientation information and ignoring the value set from `react-native-screens`. We've created this PR (https://github.com/software-mansion/react-native-screens/pull/1155) to allow Expo determine orientation value taken from `react-native-screens`. We plan to release a fix in the near future.

Cheers

**Comment by zwh1666258377** [comment]
thx! but my project is bare workflow, would that still be the case？

**Comment by kacperkapusciak** [comment]
Hi @zwh1666258377,
Yes, it is going to work. You'll have to update (or add the next version of) the `expo-screen-orientation` package to your project if you use bare workflow with dependency to Expo. In bare react-native workflow (without the help of Expo) orientation works just fine.

Cheers

**Comment by zwh1666258377** [comment]
> Hi @zwh1666258377,
> 
> Yes, it is going to work. You'll have to update (or add the next version of) the `expo-screen-orientation` package to your project if you use bare workflow with dependency to Expo. In bare react-native workflow (without the help of Expo) orientation works just fine.
> 
> 
> 
> Cheers

But i use “react-native-orientation”，is this the same？

**Comment by kacperkapusciak** [comment]
@zwh1666258377 your issue and reproduction doesn't state anything about `react-native-orientation`

`react-native-screens` uses the same mechanism to manage orientation that `react-native-orientation` use. One will override the other. You need to choose if you want to manage screen orientation with navigation or with `react-native-orientation` and stick to one approach. They won't work together. 

Thanks to you we've fixed a different issue (with orientation in Expo) even if it's not the problem you are facing. Thank you for that 🙌 

As there's nothing we can do about it further I'll close the issue. If you have any more questions let me know.

Cheers

**Comment by dohooo** [comment]
https://user-images.githubusercontent.com/32405058/136792885-110cb8c9-8349-4409-99f7-9489a5cb7c0d.mp4

**Comment by dohooo** [comment]
I used the same code as [Snack](https://snack.expo.dev/9LZ5ItpXl)

**Comment by dohooo** [comment]
Ok
