### ISSUE TITLE
Back navigation is buggy with `createNativeStackNavigator` on Android

### ISSUE THREAD

**Issue by Miraj98** [software-mansion/react-native-screens#1160]
## Description
I have set up a `createNativeStackNavigator` using the `react-navigation` library. It is set up as follows
```
    <Stack.Navigator>
      <Stack.Screen
        name="MainTabs"
        component={MainTabs}
        options={{headerShown: false}}
      />
      <Stack.Screen name="ChatScreen" component={ChatScreen} />
    </Stack.Navigator>
```

Note: MainTabs is a tab navigator created using the `createMaterialBottomTabNavigator` api from `@react-navigation/material-bottom-tabs`

Whenever I push a screen and then press back either from the header or using the Android back gesture, the top screen is popped for once and then suddenly the popped screen again shows up in a weird way (check the video below to better understand whats happening)

The navigations work perfectly fine on iOS.
The navigations also work  on Android when I use `createStackNavigator` instead of `createNativeStackNavigator`

### Video

https://user-images.githubusercontent.com/20258578/135298803-fc34834e-a4ff-4157-a72d-3d5055635a15.mp4

## Steps To Reproduce

1. Make a Material bottom navigator (using the `createMaterialBottomTabNavigator` api from `@react-navigation/material-bottom-tabs`)
2. Nest it inside `createNativeStackNavigator`
3. Start the app and try to push a screen and then go back

### Expected behavior
After pressing back the popped screen should disappear and not shown again

### Actual behavior
Shows the correct screen for a split second but then shows some parts of the popped screen (Check video from above)

## Package versions

```
{
    "react-native-paper": "^4.9.2",
    "react": "17.0.2",
    "react-native": "0.65.1",
}
```

**Comment by rana944** [comment]
@Miraj98, exactly the issue that I have been facing.
Everything works as expected on iOS device. But the android behaviour is weired.
It does not even leave any stack trace or any sort of error. 

It navigates back to the same screen that has been poped out of the stack and leaving me with a blank screen.
May be downgrading the version could help. If you had a workaround for this issue. Please share.

Thanks

**Comment by mateusz1913** [comment]
It seems that is similar issue to https://github.com/software-mansion/react-native-reanimated/issues/2460

**Comment by ruairioliverwv** [comment]
Same issue for me

**Comment by kacperkapusciak** [comment]
@Miraj98 could you provide a minimal complete reproducible code sample? With this, I mean a small snippet that reproduces your issue in a snack or in an empty repo. Please see [this guide](https://stackoverflow.com/help/minimal-reproducible-example).

Cheers

**Comment by minhchienwikipedia** [comment]
Do you have any solution for it? I getting the same issue!

**Comment by WoLewicki** [comment]
I tested a simple example with `react-native-reanimated`: `2.3.0-beta.1` and I could spot an issue. After upgrading to `2.3.0-beta.4`, I can no longer see the problem. I will close it then. Feel free to comment here if I am wrong and we can reopen it then.
