### ISSUE TITLE
Screens don't compile with Kotlin 1.3.X 

### ISSUE THREAD

**Issue by ds8k** [software-mansion/react-native-screens#1163]
## Description

Building version 3.8.0 fails with the following error:
```
e: /Users/cameronbates/Developer/axios-app/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt: (124, 47): Smart cast to 'ScreenStackFragment' is impossible, because 'mTopScreen' is a mutable property that could have been changed by this time

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:compileDebugKotlin'.
```

### Screenshots

![Screen Shot 2021-09-30 at 2 23 13 PM](https://user-images.githubusercontent.com/4458812/135510173-9b1a0847-7095-4762-bf16-87160cef5bea.png)

## Steps To Reproduce

1. Install 3.8.0 and attempt to build

## Platform

- [ ] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |    65.1     |
| react-native-screens                   |    3.8.0     |
| react-native-safe-area-context         |    3.3.2     |
| react-native-gesture-handler           |    1.10.3     |
| react-native-reanimated                |     1.7.0    |
| react-navigation                |     4.4.3    |
| react-navigation-stack                |     2.10.4    |
| react-navigation-tabs                |     2.10.1    |

**Comment by kacperkapusciak** [comment]
Hi @ds8k,
I can't reproduce this issue on my computer. Could you `cd` into `android/` directory and run `./gradlew -v` (for *nix) or `.\gradlew.bat -v` (for Windows) and copy the output here to provide more information? I'm most interested in Gradle & Kotlin versions and the OS. 

Cheers

**Comment by ilhamsa1** [comment]
Hi, I got this issue when adding kotlin version in `android/build.gradle`

```
buildscript: {
  ext {
      kotlinVersion = "1.3.72"
  }
}
```
I use [watermelonDb ](https://github.com/Nozbe/WatermelonDB) which needs that setting

**Comment by zerbfra** [comment]
Same issue here with this `buildScript`

```
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "20.1.5948944"
        kotlinVersion = "1.3.72"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:4.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}

```

As you can see, I need the kotlin dependency.

**Comment by kacperkapusciak** [comment]
@ilhamsa1 @zerbfra thank you for providing information to reproduce this 🙏 

Could you check if applying changes in https://github.com/software-mansion/react-native-screens/pull/1165 fixes your issue?

cc @ds8k

**Comment by zerbfra** [comment]
> @ilhamsa1 @zerbfra thank you for providing necessary information to reproduce this 🙏
> 
> Could you check if applying changes in #1165 fixes your issue?
> 
> cc @ds8k

Applied the changes and It works like a charm.
You should proceed with merge of #1165 

Thanks 🙏

**Comment by ilhamsa1** [comment]
I just tried PR #1165 and it worked fine ... Thanks...

**Comment by mitjnextt** [comment]
Thanks @kacperkapusciak , It fixed!
