### ISSUE TITLE
detachInactiveScreens={true} cause onScroll of previous tab screen triggered in react navigation v6 bottom tab

### ISSUE THREAD

**Issue by lclrobert2020** [software-mansion/react-native-screens#1183]
## Description

 #10063  of react navigation 
This bug only occurs in IOS, not for android
For example,
when you have a <Tab.Navigator> with two <Tab.Screen>
Let say you are currently on a Screen, say Screen 1, you have a with a onScroll props and a callback inside Screen 1,
When you press the Tab Bar Icon and jump to other Tab Screen, say Screen 2,
When the Screen 2 is shown and rendered,
The onScroll pf Screen 1 is magically called without any reason,
The same applies to onMomentumScrollEnd
if you set detachInactiveScreens={false} in the Tab Navigator
this problem will not occur

But for android,
this problem doesn't exist at all, no matter if detachInactiveScreens is set to true or false
## Steps To Reproduce
1.go to my expo repo
2. press the tab bar to change screen
3. you will see the previous screen onScroll is called when the tab screen is changed
### Expected behavior
Both IOS and Android should not call previous tab screen onScroll
This cause some issue as some of my tab screen has onScroll listener on it
### Actual behavior
In IOS, you will see the previous screen onScroll is called when the tab screen is changed

## Reproduction
https://snack.expo.dev/@robertli93/bug

## Platform

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow
exist both expo or bare react native project
- [ X] Managed workflow
- [ X] Bare workflow

## Package versions

{
  "dependencies": {
    "react-native-screens": "~3.4.0",
    "react-native-tab-view": "^3.0.0",
    "@react-navigation/stack": "6.0.11",
    "react-native-pager-view": "5.0.12",
    "react-native-reanimated": "~2.2.0",
    "@react-navigation/native": "6.0.2",
    "@react-navigation/elements": "1.0.4",
    "react-native-gesture-handler": "~1.10.2",
    "@react-navigation/bottom-tabs": "6.0.9",
    "react-native-safe-area-context": "3.2.0"
  }
}

**Comment by lclrobert2020** [comment]
> The easiest solution is something similar to what I proposed in the previous comment. You can use [`isFocused`](https://reactnavigation.org/docs/use-is-focused/) to detect if you already left the screen and not do anything when the event comes if it returns `false`. Is this enough?
The problem is even if you don't add any scroll listeners, the error will be throw when coming back and forth between tabs 3 times
you can visit my expo https://snack.expo.dev/@robertli93/bugdemo
This example contains no scroll listener but still trigger the error very consistently

**Comment by WoLewicki** [comment]
It is warning from here: https://github.com/facebook/react-native/blob/afe0c1daea0aaf7b40b7ded08d6eb6d45b17099c/Libraries/Lists/VirtualizedList.js#L1614. It is probably triggered because `onScroll` event is sent from native side because of the our fix. You can add logs in these lines and check the exact values, but I think it is caused by these `dt` values being weird due to this flow.

**Comment by ElionItTeam** [comment]
> It is warning from here: https://github.com/facebook/react-native/blob/afe0c1daea0aaf7b40b7ded08d6eb6d45b17099c/Libraries/Lists/VirtualizedList.js#L1614. It is probably triggered because `onScroll` event is sent from native side because of the our fix. You can add logs in these lines and check the exact values, but I think it is caused by these `dt` values being weird due to this flow.

Thanks for ur reply,
I can confirm this is a dt problem,
When I look into it deeper, 
This problem occurs even when only using **1 FlatList**
see my latest demo @ https://snack.expo.dev/@robertli93/flatlist-bug-when-changing-tabs-even-using-single-flatlist
see this latest demo  video https://www.youtube.com/watch?v=vcGAuRvQ1LA&ab_channel=RBL
This is only 1 flatlist in this demo
Thanks to  @WoLewicki 
I have found the reason,
let me explain in detail
the warning is trigger by 
1. dt (calculated by,  const dt = this._scrollMetrics.timestamp? Math.max(1, timestamp - this._scrollMetrics.timestamp) : 1)
2. _scrollMetrics.dt (which seems to be the previous dt of last scroll), contentLength > 5 * visibleLength

**Comment by dhruvpvx** [comment]
it is being called event without detachInactiveScreens={true}
