### ISSUE TITLE
Crash report from iOS: NSInvalidArgumentException: -[UIView gestureEnabled]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by SimpleCreations** [software-mansion/react-native-screens#1194]
## Description

I've received a crash report from an iOS 15 user which seems to originate from react-native-screens.
As with previous crash, I have no reproduction and I'm hoping there is some useful info in the report itself.

The line referenced is:

https://github.com/software-mansion/react-native-screens/blob/225e425063658adb0ef6a2b6510b90bcf15e3057/ios/RNSScreenStack.m#L575

```
NSInvalidArgumentException: -[UIView gestureEnabled]: unrecognized selector sent to instance 0x129230410

0  CoreFoundation   ___exceptionPreprocess
1  libobjc.A.dylib  _objc_exception_throw
2  CoreFoundation   -[NSObject(NSObject) doesNotRecognizeSelector:]
3  UIKitCore        -[UIResponder doesNotRecognizeSelector:]
4  CoreFoundation   ____forwarding___
5  CoreFoundation   ___forwarding_prep_0___
6  [redacted]       -[RNSScreenStackView gestureRecognizerShouldBegin:] (RNSScreenStack.m:575:18)
7  UIKitCore        -[UIGestureRecognizer _shouldBegin]
8  UIKitCore        -[UIGestureRecognizer setState:]
9  UIKitCore        -[UIPanGestureRecognizer touchesMoved:withEvent:]
10 UIKitCore        -[UIGestureRecognizer _componentsChanged:withEvent:]
11 UIKitCore        -[UITouchesEvent _sendEventToGestureRecognizer:]
12 UIKitCore        ___47-[UIGestureEnvironment _updateForEvent:window:]_block_invoke
13 UIKitCore        -[UIGestureEnvironment _updateForEvent:window:]
14 UIKitCore        -[UIWindow sendEvent:]
15 UIKitCore        -[UIApplication sendEvent:]
16 UIKitCore        ___dispatchPreprocessedEventFromEventQueue
17 UIKitCore        ___processEventQueue
18 UIKitCore        ___eventFetcherSourceCallback
19 CoreFoundation   ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
20 CoreFoundation   ___CFRunLoopDoSource0
21 CoreFoundation   ___CFRunLoopDoSources0
22 CoreFoundation   ___CFRunLoopRun
23 CoreFoundation   _CFRunLoopRunSpecific
24 GraphicsServices _GSEventRunModal
25 UIKitCore        -[UIApplication _run]
26 UIKitCore        _UIApplicationMain
27 [redacted]       main (main.m:7:12)
```

## Steps To Reproduce

N/A

### Expected behavior

No crashes

### Actual behavior

Crash

## Reproduction

N/A

## Platform

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |  0.65.1       |
| @react-navigation/native               |   6.0.4      |
| @react-navigation/native-stack         |  6.2.2       |
| react-native-screens                   |  github:software-mansion/react-native-screens#@wolewicki/ios-header-insets       |
| react-native-safe-area-context         |  3.3.2       |
| react-native-gesture-handler           | 1.10.3        |
| react-native-reanimated                |  2.2.3       |
| expo                                   |  N/A |

**Comment by WoLewicki** [comment]
I added the check in #1224, could you check if it fixes the issue? Still, a reproduction would be much appreciated.
