### ISSUE TITLE
[RFC] Allow enabling/disabling screens per subtree instead of globally

### ISSUE THREAD

**Issue by satya164** [software-mansion/react-native-screens#120]
The current way to enable screens is to call `useScreens(true)` at the root level globally in the app.

However, it'll be better to enable/disable screens for part of the app so we could disable it for problematic areas while still keeping it enabled for rest of the code. We can use the context API to achieve it.

One use case is to disable screens for modals in React Navigation where it seems to be problematic.

The API may look like this:

Configuration for a sub-tree:

```js
<ScreensProvider enabled={true}>
  // Content
</ScreensProider>
```

Configuration per-container:

```js
<ScreensContainer enabled={false}>
  // Content
<ScreensContainer>
```

By default `ScreensContainer` will use the parent configuration for enabling/disabling if this prop is not specified. Another approach will be to wrap this container in `ScreensProvider` and pass `enabled` instead of adding a prop on `ScreenContainer` directly.

Then we can do something like `enabled={mode === 'modal' ? false : true}`

cc @kmagiera @osdnk @brentvatne

**Comment by WoLewicki** [comment]
I believe this option was added in #636, so I am closing this issue. Feel free to comment if I am wrong.
