### ISSUE TITLE
back prop is undefined in header option when using a custom navigation bar

### ISSUE THREAD

**Issue by netmas** [software-mansion/react-native-screens#1201]
## Description

Hi! I'm working in a expo managed project. I have a drawer navigator as root navigator, a bottomTabNavigator and a home screen which is a NativeStackNavigator. In navigation index.js I am using the ScreenOptions->Header to use a custom navigation bar.

The navigation is working but back prop in the header of the native stack navigator is undefined. May be because is nested like this: drawer navigator -> bottom tab navigator -> native stack navigator

The problem is that when I send the props to the custom navigation bar the back prop is undefined. And I was checking also routes props is not being updated.

### Screenshots

![Screenshot_1635945958](https://user-images.githubusercontent.com/735107/140075039-f60bc549-94a2-4149-9fa4-e0edea5667c0.png)

![Screenshot_1635945964](https://user-images.githubusercontent.com/735107/140075076-4ea26513-f12a-4d17-9f9f-bd1446f0331c.png)

## Steps To Reproduce

1. Enter DashboardScreen and go to Reflexioines Screen

### Expected behavior
1. The backbutton should be visible, but is not visible because de back prop is undefined

### Actual behavior
1. The backbutton is not visible
## Reproduction

export default function CustomNavigationBar({ myProps, navigation, back }) {

    const { manifest = {} } = Constants;
    console.log("MyProps", myProps )
    return (
      <Appbar.Header>
        { back ? <Appbar.BackAction onPress={navigation.goBack} /> : null}
        <Appbar.Content 
          /*title={
            <View style={{flexDirection: 'row', alignItems: 'baseline'}}>
              <Image
                source={logo} 
                style={{
                  width: 96,
                  height: 44,
                  marginTop: 7,
                }}
              />
              <Caption style={{color: '#FFFFFF', marginLeft: 3 }}>{`${manifest.version}`}</Caption>
          </View>
          } */
          title={`Capellania Empresarial`}
          subtitle={`Version ${manifest.version}`}
        
        />
      </Appbar.Header>
    );
  }

const TabOneStack = createNativeStackNavigator();

function TabOneNavigator() {
	return (
		<TabOneStack.Navigator initialRouteName="DashboardScreen">
            <TabOneStack.Screen
                name="DashboardScreen"
                component={DashboardScreen}
                options={{ 
                headerShown: false,
                headerTitle: 'Dashboard' }}
            />
			<TabOneStack.Screen
				name="ReflexionesScreen"
				component={ReflexionesScreen}
				options={{ 
				headerShown: false,
				headerTitle: 'Reflexiones' }}
			/>
			<TabOneStack.Screen
				name="ReflexionesDetailScreen"
				component={ReflexionesDetailScreen}
				options={{ 
				headerShown: false,
				headerTitle: 'Reflexiones Detail' }}
			/>
		</TabOneStack.Navigator>
	);
}

export default function BottomTabNavigator() {
	//const colorScheme = useColorScheme();

	return (
		<BottomTab.Navigator
		initialRouteName="Dashboard"
		backBehavior='firstRoute'
		barStyle={{ backgroundColor: '#476FB5' }}
		>
		<BottomTab.Screen
			name="Dashboard"
			component={TabOneNavigator}
			options={{
			tabBarIcon: ({ color }) => <TabBarIcon name={
														Platform.OS === 'ios'
														? 'ios-people'
														: 'md-people'
													} color={color} />,
			}}
		/>
		<BottomTab.Screen
			name="Horarios"
			component={TabTwoNavigator}
			options={{
			tabBarIcon: ({ color }) => <TabBarIcon name={'people-circle-outline'} color={color} />,
			}}
		/>
		{/* <BottomTab.Screen
			name="Usuarios"
			component={TabThreeNavigator}
			options={{
			tabBarIcon: ({ color }) => <TabBarIcon name={'person-circle-outline'} color={color} />,
			}}
		/> */}
		</BottomTab.Navigator>
	);
}

const StackHome = createNativeStackNavigator();

function Home() {
	
  return (
    <StackHome.Navigator
		initialRouteName="Root"
		screenOptions =	{{ 
							header: (props) => <CustomNavigationBar myProps = {props} {...props} />,
						}}>
      	<StackHome.Screen name="Root" component={BottomTabNavigator} />
      	<StackHome.Screen name="NotFound" component={NotFoundScreen} options={{ title: 'Oops!' }} />
    </StackHome.Navigator>
  );
}

const Drawer = createDrawerNavigator();

function RootNavigator() {
	return (
		<Drawer.Navigator 
			initialRouteName="Home"
			screenOptions={{
				headerShown: false,
			}}
			drawerStyle={{
							backgroundColor: '#F5F5F6',
						}} >
			<Drawer.Screen name="Home" component={Home} />
			{/* <Drawer.Screen name="Login" component={Login} /> */}
      	</Drawer.Navigator>
	)
}

function Navigation({ themePersonalizado, active_user }) {

	//const isSignedIn = useIsSignedIn();
	const isSignedIn = active_user.isLoggedIn;
	
    return (
      <NavigationContainer theme={ themePersonalizado }>
	  	{
			isSignedIn ? (
			<>
				<RootNavigator />
			</>
			) : (
			<>
				<Login />
			</>
			)
		}
      </NavigationContainer>
    );

}

export navigation

## Platform

- [ ] iOS
- [x ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [x ] Managed workflow
- [ ] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
"react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
"@react-navigation/native": "^6.0.6",
"@react-navigation/native-stack": "^6.2.5",
"react-native-screens": "~3.4.0",
"react-native-safe-area-context": "3.2.0",
"react-native-gesture-handler": "~1.10.2",
"react-native-reanimated": "~2.2.0",
"expo": "~42.0.1",
"react-navigation/drawer": "^6.1.8",
"react-native-paper": "^4.9.2",

**Comment by WoLewicki** [comment]
Sorry for late response, I tried to copy the code you provided and run it, but not all of needed code is provided. Could you fix this, ideally provide it as a single file, e.g. in a form of snack? Otherwise, we cannot elaborate on it correctly.

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
