### ISSUE TITLE
FullWindowOverlay full screen height with native navigation Header

### ISSUE THREAD

**Issue by intergalacticspacehighway** [software-mansion/react-native-screens#1202]
## Description
FullWindowOverlay doesn't take full height if the header is visible in native navigation.

### Screenshots
In the below video, if I turn off the header, it takes the full window height as expected.

https://user-images.githubusercontent.com/23293248/140252258-db98fd75-81a9-45aa-8123-4d547b5f2b82.mov

## Steps To Reproduce

Try out the below code snippet with native navigation
```jsx
<FullWindowOverlay style={StyleSheet.absoluteFill}>
      <Pressable
        style={[{backgroundColor: 'pink'}, StyleSheet.absoluteFill]}
        onPress={() => Alert.alert('hi from pressable')}
      />
</FullWindowOverlay>
```

### Expected behavior
- FullWIndowOverlay to take up the full height.

### Actual behavior
- FullWindowOverlay doesn't take up the full height

## Reproduction
Reproducible issue repo - https://github.com/intergalacticspacehighway/full-window-overlay-native-header-issue
`App.js` contains the code shown in the screen recording.

## Platform

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |     0.66.1   |
| @react-navigation/native               |       6.0.6  |
| @react-navigation/native-stack         |       6.2.5  |
| react-native-screens                   |    3.9.0     |
| react-native-safe-area-context         |      3.3.2   |
| react-native-gesture-handler           |      x   |
| react-native-reanimated                |      x   |
| expo                                   |      x |

## Additional

The below code snippet uses RN's Modal and takes full height regardless of header is visible or not. It would be great if I can achieve similar with `FullWindowOverlay`

```jsx
<Modal visible transparent>
      <Pressable
        style={[
          {flex: 1, backgroundColor: 'pink', justifyContent: 'center'},
          StyleSheet.absoluteFill,
        ]}
        onPress={() => Alert.alert('hi from pressable')}
      />
</Modal>
```

Let me know if I am doing something wrong here. Thanks!

**Comment by nandorojo** [comment]
I'm getting the same issue.

**Comment by WoLewicki** [comment]
Could you check if using `Dimensions` API instead of `StyleSheet.absoluteFill` here: https://github.com/intergalacticspacehighway/full-window-overlay-native-header-issue/blob/main/App.js#L23 fixes the problem?

**Comment by intergalacticspacehighway** [comment]
Yes! this seems to fix the issue. Thank you for the solution @WoLewicki!

<img width="1419" alt="Screenshot 2021-12-01 at 10 48 12 AM" src="https://user-images.githubusercontent.com/23293248/144176460-c8239f13-8192-4108-a804-8a60483f0dae.png">
