### ISSUE TITLE
Refresh control disappears on large header

### ISSUE THREAD

**Issue by trajano** [software-mansion/react-native-screens#1203]
## Description

Refresh control disappears when using large header and pull to refresh.  No issue when header is not large.

## Steps To Reproduce

1. Pull down to refresh and have large headers on.

### Expected behavior

Spinner should remain until processing is done

### Actual behavior

Spinner disappears

## Reproduction

https://snack.expo.dev/@trajano/refresh-control-disappears-when-refreshing

## Platform

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [X] Managed workflow
- [ ] Bare workflow

## Package versions

```
{
  "dependencies": {
    "@expo/vector-icons": "^12.0.0",
    "react-native-paper": "^4.0.1",
    "react-native-screens": "~3.8.0",
    "react-native-tab-view": "^2.15.1",
    "@react-navigation/stack": "^6",
    "react-native-reanimated": "~2.2.0",
    "@react-navigation/drawer": "^6",
    "@react-navigation/native": "^6",
    "react-native-gesture-handler": "~1.10.2",
    "@react-navigation/bottom-tabs": "^6",
    "react-native-safe-area-context": "3.3.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/native-stack": "*"
  }
}
```

**Comment by trajano** [comment]
Would a fix on this one require an upgrade on Expo SDK if we're using managed workflow?

**Comment by kacperkapusciak** [comment]
@trajano could you check if adding `contentInsetAdjustmentBehavior="automatic"` to `<SectionList/>` component AND setting `headerTranslucent: true` on the screen fixes the issue?

**Comment by WoLewicki** [comment]
I believe the solution from @kacperkapusciak should work for all RN components using `UIScrollView` under the hood. I will close this issue then. Feel free to comment if I am wrong and we can reopen it then.

**Comment by yiheinchai** [comment]
Thank you! Encountered the same problem today and `contentInsetAdjustmentBehavior="automatic"` and `headerTranslucent: true` resolved the issue.

**Comment by yiheinchai** [comment]
@WoLewicki I noticed that by using `headerTranslucent: true`, it removes the `ListHeaderComponent` from FlatList which is supposed to be a sticky header. I noted a separate issue regarding this #927 . Is there a solution where I can get BOTH refresh control and sticky headers to work at the same time?

**Comment by WoLewicki** [comment]
I am not sure of the current state of this, but sticky headers were implemented on the JS side, as I mentioned here: https://github.com/software-mansion/react-native-screens/issues/927#issuecomment-883180718, so it is `react-native`'s implementation where it can and should be fixed unfortunately.
