### ISSUE TITLE
Kotlin version needs a bump

### ISSUE THREAD

**Issue by shamilovtim** [software-mansion/react-native-screens#1206]
Most of the react native community is using kotlin 1.4.21 at this point. Suggest bumping up so that there aren't so many versions of kotlin floating around in everyone's projects.

**Comment by Alaa-Ben** [comment]
I see that in the code, there is:
`        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${safeExtGet('kotlinVersion', '1.4.10')}"
`
which means that it uses the project's kotlinVersion, and defaults to 1.4.10 if not declared. Most projects do this, so if you have a kotlinVersion set in your build.gradle, you shouldn't have many versions floating around.

**Comment by kacperkapusciak** [comment]
@shamilovtim You can override the Kotlin version in your app's `build.gradle` with

```
buildscript {
    ext {
        ...
        kotlinVersion = "1.4.21"
    }
}
```

I think "most of the react native community is using kotlin 1.4.21" is a bit of a stretch here

@Alaa-Ben exactly! thanks 🙌
