### ISSUE TITLE
Pressing back fast on iOS may show frozen scene

### ISSUE THREAD

**Issue by grahammendick** [software-mansion/react-native-screens#1207]
Thanks @software-mansion and @kmagiera for your stellar work on `react-freeze`. 

I’ve been knee-deep in `Suspense` this past week and a half [adding freeze support to the Navigation router](https://github.com/grahammendick/navigation/pull/547). I solved a thorny issue along the way that I think your implementation might suffer from so I’m getting in touch to try and help out.

## Showing a Frozen Scene
If you navigate from A to B to C then you end up with a stack A → B → C where scene A is frozen (I’m actually freezing both A and B). On iOS, if you then press back twice very fast you can end up showing A in a frozen state. The navigation happens on the native side immediately and A stays frozen until the JavaScript navigation catches up and unfreezes A. This might be delayed, for example, if the JavaScript thread is busy or A takes some time to render. 

The problem is that when A is frozen, React Native sets its display to 'none'. So you can’t afford to show a frozen scene to the user even for a short amount of time. I fixed this by removing the display property from the list of `validAttributes` for the native Scene component. The list of valid attributes is attached to a component’s ref so you can modify it inside a ref callback. That way, React Native won’t send the display property to native when Suspense tries to set it to 'none'.

```jsx
<NativeScreen
  ref={(ref) => {
    if (ref?.viewConfig?.validAttributes?.style) {
      ref.viewConfig.validAttributes.style = {
        ...ref.viewConfig.validAttributes.style,
        display: false
      };
    }
  }}
>
  {children}
</NativeScreen>
```

**Comment by kacperkapusciak** [comment]
That's brilliant! 🙌 

Thank you @grahammendick so so much for sharing this!
