### ISSUE TITLE
screens swallow NavigationAction in react-navigation

### ISSUE THREAD

**Issue by formatlos** [software-mansion/react-native-screens#121]
I'm using react-native-screens with react-navigation and it seems to swallow sub-action. 
I'm having a Stack-Navigator with a nested Tab-Navigator. I want to navigate back and switch tabs:

```
const navigateAction = NavigationActions.navigate({
  routeName: 'Todos',
  action: NavigationActions.navigate({ routeName: 'Draft' }),
});
navigation.dispatch(navigateAction);
```
with react-native-screens it does only navigate back but not change the tabs. 

Here's a snack demoing that behaviour https://snack.expo.io/@formatlos/screens-swallow-action.

**Comment by WoLewicki** [comment]
When trying the snack, it looks like it is working fine now. Can I close the issue then?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
