### ISSUE TITLE
Issue with suggested fix from Readme for Android crashes on "onCreate"

### ISSUE THREAD

**Issue by spointecker** [software-mansion/react-native-screens#1215]
## Description
I have crashes like many others in crashlytics from `Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.iamstudent/com.iamstudent.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception...`

As suggested in various issues/threads I added/changed the lines from the Readme file in `MainApplication.java`

Unfortunately the app does not compile to a bundle with those changes, these are the errors shown:
```
> Task :app:compileReleaseJavaWithJavac FAILED
/Users/***/Sites/app/android/app/src/main/java/com/*****/MainApplication.java:51: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/***/Sites/app/android/app/src/main/java/com/*****/MainApplication.java:53: error: method onCreate in class Application cannot be applied to given types;
    super.onCreate(null);
         ^
  required: no arguments
  found: <null>
  reason: actual and formal argument lists differ in length
2 errors
```

## Platform

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [X] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |     0.65.2    |
| @react-navigation/native               |    5.9.8     |
| @react-navigation/native-stack         |    -     |
| react-native-screens                   |    3.9.0     |
| react-native-safe-area-context         |  3.3.2       |
| react-native-gesture-handler           |    1.10.3    |
| react-native-reanimated                |    2.2.3    |

**Comment by kirillzyusko** [comment]
@spointecker you should add it to `MainActivity`, not to `MainApplication` 🙂

**Comment by spointecker** [comment]
Ahhh omg how stupid. Have looked at it 100 times and didn't see it. Thank you @kirillzyusko
