### ISSUE TITLE
iOS - Landscape to portrait rotation briefly shows removed screen on pop

### ISSUE THREAD

**Issue by cristianoccazinsp** [software-mansion/react-native-screens#1216]
## Description
If we are in landscape mode, pop a screen, and immediately rotate to portrait, the popped screen will still show for half a second ( I assume while it is being unmounted).

### Screenshots

https://user-images.githubusercontent.com/48869228/142239454-fc6913a9-a973-4335-bfa4-39c61c10fd95.mov

mov file most likely won't play in the browser and needs to be downloaded.

## Steps To Reproduce

1. Switch to landscape
2. Push a screen
3. Pop the screen and immediately rotate to portrait
4. Observe

### Expected behavior
Previous screen should not be visible.

### Actual behavior
Popped screen is visible for half a second.

## Reproduction

This is the animation config I'm using, which may or not be related. I will try to reproduce with the sample app when I get a chance.

```
const animationConfig = {
  animation: 'spring',
  config: {
    stiffness: 1200,
    damping: 200,
    mass: 3,
    overshootClamping: true,
    restDisplacementThreshold: 0.1,
    restSpeedThreshold: 0.1,
    useNativeDriver: true,
  },
};

const {multiply} = Animated;
const animationInterp = ({current, next, inverted, layouts: {screen}}) => {
  const translateFocused = multiply(
    current.progress.interpolate({
      inputRange: [0, 1],
      outputRange: [screen.width, 0],
      extrapolate: 'clamp',
    }),
    inverted,
  );

  const translateUnfocused = next
    ? multiply(
        next.progress.interpolate({
          inputRange: [0, 1],
          outputRange: [0, screen.width * -0.8],
          extrapolate: 'clamp',
        }),
        inverted,
      )
    : 0;

  const overlayOpacity = current.progress.interpolate({
    inputRange: [0, 1],
    outputRange: [0, 0.1],
    extrapolate: 'clamp',
  });

  const shadowOpacity = current.progress.interpolate({
    inputRange: [0, 1],
    outputRange: [0, 0.3],
    extrapolate: 'clamp',
  });

  return {
    cardStyle: {
      transform: [
        // Translation for the animation of the current card
        {translateX: translateFocused},
        // Translation for the animation of the card on top of this
        {translateX: translateUnfocused},
      ],
    },
    overlayStyle: {opacity: overlayOpacity},
    shadowStyle: {shadowOpacity},
  };
};
```

## Platform

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [X] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |  0.65.1        |
| @react-navigation/native               |  5.9.4       |
| @react-navigation/native-stack         |   5.14.9      |
| react-native-screens                   |  3.9.0       |
| react-native-safe-area-context         |  3.3.2       |
| react-native-gesture-handler           |    1.10.3     |
| react-native-reanimated                |  1.13.2       |
| expo                                   |     -    |

**Comment by cristianoccazinsp** [comment]
Repro here: https://github.com/cristianoccazinsp/react-native-screens/tree/repro-1216

Just enter any screen, rotate to landscape, go back and quickly rotate to portrait.

**Comment by WoLewicki** [comment]
This issue exists on `stack` navigator, not `native-stack`? If so, does this issue still happen if you set `detachInactiveScreens: false` on the navigator?

**Comment by cristianoccazinsp** [comment]
@WoLewicki it does not happen with native-stack. However, it happens both with and without `detachInactiveScreens`.

**Comment by WoLewicki** [comment]
Hmm so is there any particular reason why this issue should not be submitted in `react-navigation` repo instead? It seems that it is not connected with `react-native-screens` if it happens with them turned off too.

**Comment by cristianoccazinsp** [comment]
Oddly it started to happen after a screens update since I haven’t changed the navigation one in quite a while.

Note that I tested with detach inactive screens, not disabling screens completely. I will try to do more testing.

**Comment by WoLewicki** [comment]
Setting `detachInactiveScreens: false` on the navigator disables the usage of `react-native-screens` in it, so it would suggest that it is not connected though. Or am I missing something?

**Comment by cristianoccazinsp** [comment]
Doesn’t detachInactiveScreens just forces screens to keep the view in the hierarchy, but the internal screens views and machinery are still used?

I guess the best test would be with useScreens(false).  Either way, I probably won’t be able to report it to react navigation until I upgrade to 6.x, which we can’t right now due to version 6 having some breaking bugs that haven’t been fixed in a while.

**Comment by WoLewicki** [comment]
> Doesn’t detachInactiveScreens just forces screens to keep the view in the hierarchy, but the internal screens views and machinery are still used?

No, the prop for keeping view in hierarchy is `detachPreviousScreen`: https://reactnavigation.org/docs/stack-navigator#detachpreviousscreen. You can set `detachInactiveScreens: false` and see in native view hierarchy that there are no `Screen` components there then.

**Comment by Hirbod** [comment]
@cristianoccazinsp 
> Doesn’t detachInactiveScreens just forces screens to keep the view in the hierarchy, but the internal screens views and machinery are still used?

That is only valid  for react-native-web (it won't apply `display: none`)

**Comment by cristianoccazinsp** [comment]
After further testing, the issue happens even with `enableScreens(false);`, so I guess this is really an issue for react-navigation. Sadly, I don't think react-navigation is getting fixes any time soon as it keeps piling up important bugs in 6.x, so I will report it there once I upgrade to 6.x.

**Comment by Hirbod** [comment]
@cristianoccazinsp fyi: updating from 5 to 6 was a 10min task on my app (and I have a huge navigation)

**Comment by cristianoccazinsp** [comment]
> @cristianoccazinsp fyi: updating from 5 to 6 was a 10min task on my app (and I have a huge navigation)

It's not about the difficulty in upgrading, but the unfixed bugs in 6.x that make it unusable (https://github.com/react-navigation/react-navigation/issues/9918 and alike)

**Comment by Hirbod** [comment]
Unless you need some very special config, I would just upgrade and ditch `createStackNavigator` form @react-navigation/stack to `createNativeStackNavigator` from @react-navigation/native-stack. Once you feel the native performance, you never look back :D

**Comment by cristianoccazinsp** [comment]
We still can't upgrade to the native navigators as we have some very customized headers, and also we use the same transition animations for iOS and Android (the native android one is pretty bad for our app at least). But yes, we would like to go that route eventually.

**Comment by shelzTimesignature** [comment]
things like navigation should've been handled by react native team. its been 3 years now we still facing the same issue

**Comment by shubhamchepe** [comment]
you can try custom navigators , like conditional rendering of components

import React, { useState } from 'react';
import Screen1 from './Screen1';
import Screen2 from './Screen2';

const App = () => {
  const [currentScreen, setCurrentScreen] = useState('screen1');

  const renderScreen = () => {
    if (currentScreen === 'screen1') {
      return <Screen1 navigate={navigate} />;
    } else if (currentScreen === 'screen2') {
      return <Screen2 navigate={navigate} />;
    }
    // Add more screens as needed
  };

  const navigate = (screenName) => {
    setCurrentScreen(screenName);
  };

  return renderScreen();
};

export default App;



NEXT STEP :


import React from 'react';
import { View, Text, Button } from 'react-native';

const Screen1 = ({ navigate }) => {
  const goToScreen2 = () => {
    navigate('screen2');
  };

  return (
    <View>
      <Text>Screen 1</Text>
      <Button title="Go to Screen 2" onPress={goToScreen2} />
    </View>
  );
};

export default Screen1;


FINAL STEP : 

import React from 'react';
import { View, Text, Button } from 'react-native';

const Screen2 = ({ navigate }) => {
  const goToScreen1 = () => {
    navigate('screen1');
  };

  return (
    <View>
      <Text>Screen 2</Text>
      <Button title="Go to Screen 1" onPress={goToScreen1} />
    </View>
  );
};

export default Screen2;

STACK NAVIGATOR/ NATIVE STACK NAVIGATOR LANDSCAPE MODE ISSUE PERSIST AND HENCE I IMPLEMENTED CONDITIONAL RENDERING WHICH WORKS FLAWLESSLY!
