### ISSUE TITLE
Android - Full Screen modal does not cover bottom tab bar

### ISSUE THREAD

**Issue by therunbuddy** [software-mansion/react-native-screens#1219]
## Description

When opening a modal screen in NativeStackNavigator the screen does not cover the bottom tab bar on Andoird. On iOS is covers the tab bar. 

### Screenshots
Android
![image](https://user-images.githubusercontent.com/77796515/142738789-e7256162-b375-4f23-aae5-fac92a65875f.png)

iOS
![image](https://user-images.githubusercontent.com/77796515/142738798-9e228e2f-5ce8-44d3-b85a-8b8d6e29b8e4.png)

### Expected behavior

The modal screen should cover the bottom tab bar

### Actual behavior
The bottom tab bar is still visible

## Reproduction

```
const TrainStack = createNativeStackNavigator()

export default function TrainStackNavigator() {
	return (
		<TrainStack.Navigator
			initialRouteName={ROUTE_TRAIN_PLAN_OVERVIEW}
		>
			<TrainStack.Screen
				name={ROUTE_TRAIN_PLAN_OVERVIEW}
				component={TrainPlanOverviewScreen}
			/>
			<TrainStack.Group screenOptions={{ presentation: 'modal' }}>
				<TrainStack.Screen
					name={ROUTE_TRAIN_PLAN_INTRO}
					component={TrainIntroCoachScreen}
				/>
			</TrainStack.Group>
		</TrainStack.Navigator>
	)
}

export default function SecureNavigator() {
	return (
		<Tab.Navigator
		>
			<Tab.Screen
				name={ROUTE_TRAIN_TAB}
				component={TrainStackNavigator}
			/>
			<Tab.Screen
				name={ROUTE_LEARN_TAB}
				component={LearnScreen}
			/>
			<Tab.Screen
				name={ROUTE_COMMUNITY_TAB}
				component={ComingSoonScreen}
			/>
			<Tab.Screen
				name={ROUTE_SUPPORT_TAB}
				component={SupportScreen}
			/>
		</Tab.Navigator>
	)
}
```

## Platform

- [ ] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |  0.66.3        |
| @react-navigation/native               |    6.0.4     |
| @react-navigation/native-stack         |    6.2.5     |
| react-native-screens                   |     3.9.0    |
| react-native-safe-area-context         |     3.3.2    |
| react-native-gesture-handler           |    1.10.3     |
| react-native-reanimated                |    2.2.4     |

**Comment by Hirbod** [comment]
You should render your modals in the root stack, not nested inside another stack. It works for iOS since iOS always adds modals at the most top screen hierarchy but Android doesn't.

It's a bit annoying, I agree, but actually an easy fix. Modal screens are usally isolated views anyway so it shouldn't matter to place them at root level.

**Comment by WoLewicki** [comment]
It is a difference in how these platforms define `modals`. On `Android`, we achieve "modal" behavior by simply not removing the below screen, whereas on `iOS` it is a platform concept with dedicated native API. I am not sure there is more to be done than what @Hirbod suggested. I will close this then. If you have any ideas how it could be changed or if I am wrong at some point, please comment and we can reopen it.

**Comment by ythomop** [comment]
> It's a bit annoying, I agree, but actually an easy fix. Modal screens are usually isolated views anyway so it shouldn't matter to place them at root level.

Modals are very often used as a screen of filters over a list of items. How is this an "isolated view"?

"Modal" is a widely and vaguely used term, but everyone agrees on the fact that modals render "above" everything else. The implementation of "above" may differ, but the visual result is the same. If react-navigation has a `presentation: "modal"` option (that DOES not state "Only supported on iOS" next to it), then react-navigation should behave as expected and render modals above everything else and not expect the developers to move screens around just for this basic feature to work.

**Comment by hirbod** [comment]
It's been a while, but I've had similar cases where setting the elevation to 0 on the tab bar style was sufficient to make elements overlap the tab bar on Android.

**Comment by ythomop** [comment]
> It's been a while, but I've had similar cases where setting the elevation to 0 on the tab bar style was sufficient to make elements overlap the tab bar on Android.

My point is that workarounds like this are not what react navigation users should rely on.

**Comment by hirbod** [comment]
Fair point, but until resolved (if ever), I think its good to point out some useable solutions

**Comment by ruhajessica** [comment]
use an Active Sheet instead of modal - resolves the issue

**Comment by tlmader** [comment]
> If real Android modals are too expensive to implement at this point, why not mention it in the docs?

I have to agree with this one. I was under the false assumption that Native Stack would place modals above tabs, and I refactored my root stack out only to find out that it only did this on iOS.

**Comment by tlmader** [comment]
> use an Active Sheet instead of modal - resolves the issue

Do you have an example of how to do this?
