### ISSUE TITLE
Zoom animation in Android feels too quick and elastic

### ISSUE THREAD

**Issue by gustavopch** [software-mansion/react-native-screens#1223]
## Description

As the title says, the zoom animation in Android isn't exactly like what I see in native apps (e.g. in Android settings). I'm not sure if it's due to dropped frames or if the animation is just not correctly implemented.

## Steps To Reproduce

1. Perform a screen transition using React Navigation and observe the animation.
2. Perform a screen transition in Android settings and observe the animation.
3. You'll probably see the zoom doesn't happen exactly similarly.

## Platform

- [ ] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |        0.66.3 |
| @react-navigation/native               |        6.0.6 |
| @react-navigation/native-stack         |        6.2.5 |
| react-native-screens                   |        3.9.0 |
| react-native-safe-area-context         |        3.3.2 |
| react-native-gesture-handler           |        1.10.3 |
| react-native-reanimated                |        2.2.4 |
| expo                                   |        - |

**Comment by WoLewicki** [comment]
@gustavopch can you check if applying #1213 introduces better animation?

**Comment by Only-IceSoul** [comment]
I think it only works when they have the same aspect ratio.

**Comment by lightrow** [comment]
why is this closed? It's still happening on 3.18.2, we can't use native stack navigator (react-navigation) on Android because the transition animations are very off, unlike the regular JS stack navigator

**Comment by WoLewicki** [comment]
It was closed since we no longer use system animations and the new animation specs have been taken from `react-navigation` iirc. If you want custom transitions on Android, you can check https://github.com/software-mansion/react-native-screens/issues/489 for more information on how to modify them.
