### ISSUE TITLE
iOS: headerRight component misaligned during first navigation

### ISSUE THREAD

**Issue by honzajerabek** [software-mansion/react-native-screens#1231]
## Description

Hi there, I'm having an interesting problem with components in header. When setting `headerRight` using hook right after navigating from a screen that doesn't have header shown, the component is misaligned out of screen. 

This only happens on first navigation after app start && on iOS && on physical device && using Release build config.

Haven't tested other header components than `headerRight`.

### Screenshots

<img width="1274" alt="Screenshot 2021-12-06 at 15 46 35" src="https://user-images.githubusercontent.com/11437596/144866787-d5b2338a-9ba6-4289-96af-fda2bc6ff2d2.png">

First navigation, back, second navigation:
![RPReplay_Final1638797660](https://user-images.githubusercontent.com/11437596/144866167-55b5b99e-9c61-41b1-a4a5-3929b5ecce86.gif)

## Steps To Reproduce
1. Have a screen with `{ headerShown: false }` option, currently navigated on.
2. Have another screen that has `useEffect` that calls `setOptions` to set `headerRight` to some component (also `headerShown` is not set at all - header is visible). 
3. Run the iOS version, on the physical device, using `Release` build configuration
4. Navigate from the first screen to the second one **<--- the `headerRight` component is misaligned** 
5. Go back and navigate forth again - **the problem disappears**

_Note: Can be reproduced only on physical device, using `Release` build configuration; using simulator with any build configuration or a physical device with `Debug` configuration will not show any problem._

### Expected behavior

`HeaderRight` component is correctly displayed on the first and all subsequent navigations using any build configuration, physical device or simulator, 

### Actual behavior

`HeaderRight` component is misaligned on the first render/navigation when built with `Release` configuration on a physical IOS device

## Reproduction

https://github.com/honzajerabek/friendly-doodle

## Platform

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [X] Bare workflow
haven't tested expo
## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           | 0.66.3|
| @react-navigation/native               | 6.0.6|
| @react-navigation/native-stack         |  6.2.5|
| react-native-screens                   |  3.10.0 |
| react-native-safe-area-context         |  3.3.2 |

**Comment by WoLewicki** [comment]
Does it also happen if it is not set by `setOptions`, but rather in `options` of the `Screen` component? Also, does it still happen if you use `useLayoutEffect` instead of `useEffect`?

**Comment by honzajerabek** [comment]
1. It does not happen when using in Screen's `options`
2. It also does not happen when using with `useLayoutEffect`

Thank you very much, this pretty much solves it for me :)

**Comment by WoLewicki** [comment]
It is already used like this in documentation of `react-navigation`: https://reactnavigation.org/docs/navigation-prop/#setoptions so I think we can close this. Feel free to comment here if something is wrong and we can reopen it then.
