### ISSUE TITLE
Android memory leak?

### ISSUE THREAD

**Issue by cristianoccazinsp** [software-mansion/react-native-screens#1240]
## Description

Android debugger shows that RNScreens is leaking an object. This is mostly a question as perhaps it is not really a problem.

Looks like certain fragments are leaking in the sparse array.

### Screenshots
<img width="1230" alt="Screen Shot 2021-12-14 at 16 26 21" src="https://user-images.githubusercontent.com/48869228/146088060-736dd244-6660-492e-b06a-5be5b25377b8.png">
<img width="1191" alt="Screen Shot 2021-12-14 at 16 26 42" src="https://user-images.githubusercontent.com/48869228/146088072-48ea66cc-e9da-4aa4-a0ec-f5cfc00522bc.png">

## Steps To Reproduce

1. Use `createStackNavigator` (not native), and test pushing and popping some screens
2. Plug in the android native profiler
3. Run a heap dump
4. Open the leaks tab

### Expected behavior
No memory leaks.

### Actual behavior
Memory leak.

## Reproduction
May provide later.

## Platform

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [X] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |  0.66.3        |
| @react-navigation/native               |  5.9.4        |
| @react-navigation/native-stack         |    using /stack only, 5.14.9     |
| react-native-screens                   |    3.10.1     |
| react-native-safe-area-context         |   3.3.2      |
| react-native-gesture-handler           |   1.10.3     |
| react-native-reanimated                |  1.13.2       |
| expo                                   |     none    |

**Comment by WoLewicki** [comment]
I believe your issue is mentioned here: https://github.com/software-mansion/react-native-screens#other-problems and explained here: https://github.com/software-mansion/react-native-screens/issues/843#issuecomment-832034119.

**Comment by cristianoccazinsp** [comment]
Thanks, I should have searched for that first 😁
