### ISSUE TITLE
C++ Exception: St9bad_alloc

### ISSUE THREAD

**Issue by nomi9995** [software-mansion/react-native-screens#1248]
## Description

I am getting this issue in `
react-native-screens@^3.10.1` version. i see this issue on sentry. it is due to reproduce when Ram memory remaining less

![image](https://user-images.githubusercontent.com/36044436/147926920-c4d5cccb-66b5-465e-9746-8d6a5a684801.png)

### Screenshots

![image](https://user-images.githubusercontent.com/36044436/147478484-1d306823-7a64-403b-8f0e-915ca1ee1de0.png)

## Steps To Reproduce

1. dont know

### Expected behavior

it should not be crash in production

## Platform

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [X] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |    ^0.66.4     |
| @react-navigation/native               |    6.0.6     |
| @react-navigation/native-stack         |   6.2.5      |
| react-native-screens                   |   ^3.10.1      |
| react-native-safe-area-context         |   ^3.3.2      |
| react-native-gesture-handler           |    ^2.1.0     |
| react-native-reanimated                |     ^2.3.0    |
| expo                                   |         |

**Comment by WoLewicki** [comment]
Can you provide more information about the flow of your app? Can you navigate forward indefinitely without going back? After going back from a screen, all the memory allocated by it should be freed, so I am not sure if it is a problem of `react-native-screens`, but rather something else is draining the memory and in the end, there is none of it left to allocate memory for the new instance of `RNSScreen`.

**Comment by nomi9995** [comment]
@WoLewicki I tried on my side it is not reproducing but I am getting this issue on sentry, I confirm that it was not present in `react-native-screens@3.9.0` but when I updated `react-native-screens` to `3.10.1` then I am getting this issue on sentry.

**Comment by WoLewicki** [comment]
Are you using `react-freeze`? I cannot think of anything that could introduce such problem between these versions. Could you elaborate more on the flow of the app? Does this exception appear after using app for much time?

**Comment by nomi9995** [comment]
@WoLewicki no I am not using `react-freeze` by using `enableFreeze` method. It is not reproducing on my side. maybe it is due to other packages which are occupying ram. you can close this issue. thanks

here is the complete log of sentry
[cpp_exception.txt](https://github.com/software-mansion/react-native-screens/files/7815365/cpp_exception.txt)

here is other log
![image](https://user-images.githubusercontent.com/36044436/148229141-48a75b47-ee3f-4d2a-be96-59a25500c763.png)

**Comment by WoLewicki** [comment]
Ok I will close this issue then. What you can do is run a memory profiling of your application and see if there is leakage in it, and if there happens to be more instances of `RNSScreen` than there are actual screens, please report it here and we can reopen it then.

**Comment by nomi9995** [comment]
@WoLewicki I tried memory profiling but I did not find any memory leak but this issue is happening in production. I will investigate. thanks
