### ISSUE TITLE
RNScreens components your app's activity need to extend ReactFragmentActivity or ReactCompatActivity

### ISSUE THREAD

**Issue by temharay** [software-mansion/react-native-screens#1249]
## Description

the app crushes on launch with error: RNScreens components your app's activity need to extend ReactFragmentActivity or ReactCompatActivity, which are no more available for import anyway.

It is a brand new application built without expo.

The app does work well if opened from its icon but crushes when it is open from a third party application with this piece of code:

```
import android.app.Activity;
import android.os.Bundle;
import android.view.KeyEvent;
import com.babisoft.ReactNativeLocalization.ReactNativeLocalizationPackage;
import com.facebook.react.common.LifecycleState;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.modules.core.DefaultHardwareBackBtnHandler;
import com.facebook.react.ReactRootView;
import com.facebook.react.shell.MainReactPackage;
import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;
import com.oblador.keychain.KeychainPackage;
import com.reactnativecommunity.asyncstorage.AsyncStoragePackage;
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
import java.util.logging.Logger;
import com.swmansion.reanimated.ReanimatedPackage;
import com.swmansion.rnscreens.RNScreensPackage;
import com.th3rdwave.safeareacontext.SafeAreaContextPackage;


public class DActivity extends Activity implements DefaultHardwareBackBtnHandler {

  private ReactInstanceManager mReactInstanceManager;
  private ReactRootView mReactRootView;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState); //tried null as well
    mReactRootView = new ReactRootView(this);

    Bundle initialProps = new Bundle();
    initialProps.putString("AppCaller", "Denes");

    mReactInstanceManager = ReactInstanceManager.builder()
            .setApplication(getApplication())
            .setCurrentActivity(this)
            .setBundleAssetName("index.android.bundle")
            .setJSMainModulePath("index")
            .addPackage(new MainReactPackage())
            .addPackage(new KeychainPackage())
            .addPackage(new AsyncStoragePackage())
            .addPackage(new ReactNativeConfigPackage())
            .addPackage(new ReactNativeLocalizationPackage())
            .addPackage(new ReanimatedPackage())
            .addPackage(new RNScreensPackage())
            .addPackage(new SafeAreaContextPackage())
            .addPackage(new RNGestureHandlerPackage())
            .setUseDeveloperSupport(BuildConfig.DEBUG)
            .setInitialLifecycleState(LifecycleState.RESUMED)
            .build();
            mReactRootView.startReactApplication(mReactInstanceManager, "app", initialProps);
            setContentView(mReactRootView);
  }


  @Override
  public void onBackPressed() {
    if (mReactInstanceManager != null) {
      mReactInstanceManager.onBackPressed();
    } else {
      super.onBackPressed();
    }
  }

  @Override
  public void invokeDefaultOnBackPressed() {
    super.onBackPressed();
  }

  @Override
  protected void onPause() {
    super.onPause();

    if (mReactInstanceManager != null) {
      mReactInstanceManager.onHostPause(this);
    }
  }

  @Override
  protected void onResume() {
    super.onResume();

    if (mReactInstanceManager != null) {
      mReactInstanceManager.onHostResume(this, this);
    }
  }

  @Override
  public boolean onKeyUp(int keyCode, KeyEvent event) {
    if (keyCode == KeyEvent.KEYCODE_MENU && mReactInstanceManager != null) {
      mReactInstanceManager.showDevOptionsDialog();
      return true;
    }
    return super.onKeyUp(keyCode, event);
  }

  @Override
  protected void onDestroy() {
    super.onDestroy();

    if (mReactInstanceManager != null) {
      mReactInstanceManager.onHostDestroy(this);
    }
    if (mReactRootView != null) {
      mReactRootView.unmountReactApplication();
    }
  }



}
```

## Steps To Reproduce

1.

### Expected behavior

app to launch

### Actual behavior

app crushes on launch.

## Platform

- [ ] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [ ] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           | 0.65.1        |
| @react-navigation/native               |  5.9.4       |
| @react-navigation/native-stack         | 5.14         |
| react-native-screens                   |  3.8.0       |
| react-native-safe-area-context         |3.2.0         |
| react-native-gesture-handler           |1.10.3         |
| react-native-reanimated                |  2.2.2       |

**Comment by WoLewicki** [comment]
If the app you use is a brand new `react-native` app,  then your `Activity` should extend `ReactActivity`, which extends `FragmentActivity` (see the check that throws: https://github.com/software-mansion/react-native-screens/blob/main/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt#L169). Why is it not so?

Also, probably in your main manifest file, you have 2 different activites, and the one with `ReactActivity` is used when you click the app's icon and that's why it works then, but I may be wrong.

**Comment by WoLewicki** [comment]
I am closing it due to no response in 30 days. Also, I made a PR changing the extended class to the proper one: https://github.com/software-mansion/react-native-screens/pull/1303, so thanks for your contribution! Feel free to comment if something is wrong to reopen it.

**Comment by VishnuVk-0104** [comment]
> ## Description
> the app crushes on launch with error: RNScreens components your app's activity need to extend ReactFragmentActivity or ReactCompatActivity, which are no more available for import anyway.
> 
> It is a brand new application built without expo.
> 
> The app does work well if opened from its icon but crushes when it is open from a third party application with this piece of code:
> 
> ```
> import android.app.Activity;
> import android.os.Bundle;
> import android.view.KeyEvent;
> import com.babisoft.ReactNativeLocalization.ReactNativeLocalizationPackage;
> import com.facebook.react.common.LifecycleState;
> import com.facebook.react.ReactInstanceManager;
> import com.facebook.react.modules.core.DefaultHardwareBackBtnHandler;
> import com.facebook.react.ReactRootView;
> import com.facebook.react.shell.MainReactPackage;
> import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;
> import com.oblador.keychain.KeychainPackage;
> import com.reactnativecommunity.asyncstorage.AsyncStoragePackage;
> import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
> import java.util.logging.Logger;
> import com.swmansion.reanimated.ReanimatedPackage;
> import com.swmansion.rnscreens.RNScreensPackage;
> import com.th3rdwave.safeareacontext.SafeAreaContextPackage;
> 
> 
> public class DActivity extends Activity implements DefaultHardwareBackBtnHandler {
> 
>   private ReactInstanceManager mReactInstanceManager;
>   private ReactRootView mReactRootView;
> 
>   @Override
>   protected void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState); //tried null as well
>     mReactRootView = new ReactRootView(this);
> 
>     Bundle initialProps = new Bundle();
>     initialProps.putString("AppCaller", "Denes");
> 
>     mReactInstanceManager = ReactInstanceManager.builder()
>             .setApplication(getApplication())
>             .setCurrentActivity(this)
>             .setBundleAssetName("index.android.bundle")
>             .setJSMainModulePath("index")
>             .addPackage(new MainReactPackage())
>             .addPackage(new KeychainPackage())
>             .addPackage(new AsyncStoragePackage())
>             .addPackage(new ReactNativeConfigPackage())
>             .addPackage(new ReactNativeLocalizationPackage())
>             .addPackage(new ReanimatedPackage())
>             .addPackage(new RNScreensPackage())
>             .addPackage(new SafeAreaContextPackage())
>             .addPackage(new RNGestureHandlerPackage())
>             .setUseDeveloperSupport(BuildConfig.DEBUG)
>             .setInitialLifecycleState(LifecycleState.RESUMED)
>             .build();
>             mReactRootView.startReactApplication(mReactInstanceManager, "app", initialProps);
>             setContentView(mReactRootView);
>   }
> 
> 
>   @Override
>   public void onBackPressed() {
>     if (mReactInstanceManager != null) {
>       mReactInstanceManager.onBackPressed();
>     } else {
>       super.onBackPressed();
>     }
>   }
> 
>   @Override
>   public void invokeDefaultOnBackPressed() {
>     super.onBackPressed();
>   }
> 
>   @Override
>   protected void onPause() {
>     super.onPause();
> 
>     if (mReactInstanceManager != null) {
>       mReactInstanceManager.onHostPause(this);
>     }
>   }
> 
>   @Override
>   protected void onResume() {
>     super.onResume();
> 
>     if (mReactInstanceManager != null) {
>       mReactInstanceManager.onHostResume(this, this);
>     }
>   }
> 
>   @Override
>   public boolean onKeyUp(int keyCode, KeyEvent event) {
>     if (keyCode == KeyEvent.KEYCODE_MENU && mReactInstanceManager != null) {
>       mReactInstanceManager.showDevOptionsDialog();
>       return true;
>     }
>     return super.onKeyUp(keyCode, event);
>   }
> 
>   @Override
>   protected void onDestroy() {
>     super.onDestroy();
> 
>     if (mReactInstanceManager != null) {
>       mReactInstanceManager.onHostDestroy(this);
>     }
>     if (mReactRootView != null) {
>       mReactRootView.unmountReactApplication();
>     }
>   }
> 
> 
> 
> }
> ```
> 
> ### Screenshots
> ## Steps To Reproduce
> 
> ### Expected behavior
> app to launch
> 
> ### Actual behavior
> app crushes on launch.
> 
> ## Reproduction
> ## Platform
> * [ ]  iOS
> * [x]  Android
> * [ ]  Web
> * [ ]  Windows
> * [ ]  tvOS
> 
> ## Workflow
> * [ ]  Managed workflow
> * [ ]  Bare workflow
> 
> ## Package versions
> package	version
> react-native	0.65.1
> @react-navigation/native	5.9.4
> @react-navigation/native-stack	5.14
> react-native-screens	3.8.0
> react-native-safe-area-context	3.2.0
> react-native-gesture-handler	1.10.3
> react-native-reanimated	2.2.2

found any solution for this error?

**Comment by anurag-dadheech** [comment]
Move `DActivity extends Activity` to `DActivity extends AppCompatActivity`
It'll work fine.

**Comment by ko-devHong** [comment]
> Move `DActivity extends Activity` to `DActivity extends AppCompatActivity` It'll work fine.

i'm using Intergration RN.
so it work

**Comment by ko-devHong** [comment]
> I am closing it due to no response in 30 days. Also, I made a PR changing the extended class to the proper one: #1303, so thanks for your contribution! Feel free to comment if something is wrong to reopen it.

@WoLewicki  

`RNScreens` is essential to write `react-navigation`. Your answers are effective only in bare RN apps. They are not effective in integration RN apps. I need a better answer sheet.
