### ISSUE TITLE
Nested NativeStackNavigator Scroll Bug

### ISSUE THREAD

**Issue by jthies73** [software-mansion/react-native-screens#1265]
## Description

It is not possible to create two nested ScrollViews (or ListViews) (react-native-gesture-handler version 2.1.0) with the current version of NativeStackNavigator from '@react-navigation/native-stack'.
If you try to scroll on the nested ScrollView it happens that you always trigger the parent ScrollView only. This was not an issue in previous versions.

I have to admit that I'm not sure whether it is an issue with ReactNavigation or react-native-gesture-handler. However it also happens with the react-native implementation of ScrollView and ListView.

IMPORTANT NOTE: the Bug seems to only appear when nesting two NativeStackNavigators inside of each other and using the nested ScrollViews inside the second StackNavigator. For now I am simply using a DrawerNavigator inside the RootStackNavigator, which solves the problem for now. (see linked repo down below for an example)

### Expected behavior
Each ScrollView can be scrolled independently.

### Actual behavior
When using NativeStackNavigator (inside RootStackNavigator) and dragging a nested ScrollView only the parent ScrollView responds to the gesture.

## Reproduction
bug showcase:
https://github.com/jthies73/NativeStackNavigatorIssue

last working version:
https://github.com/jthies73/NativeStackNavigatorIssue/tree/last_working_version

## Platform
- [ ] iOS
- [X] Android
- [ ] Web 
- [ ] Windows
- [ ] tvOS

## Workflow
- [X] Managed workflow
- [ ] Bare workflow

## Package versions
| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |    0.64.3     |
| @react-navigation/native               |     6.0.6    |
| @react-navigation/native-stack         |    6.2.5     |
| react-native-screens                   |     3.10.1    |
| react-native-safe-area-context         |    3.3.2     |
| react-native-gesture-handler           |    2.1.0     |
| react-native-reanimated                |     2.3.1    |
| expo                                   |     44.0.0    |

**Comment by jthies73** [comment]
> Hey! 👋
> 
> It looks like you've omitted a few important sections from the issue template.
> 
> Please complete **Steps To Reproduce** section.

Hey there! Unfortunately I can not provide an expo snack link since the latest supported expo sdk version is 43.0.0.

**Comment by WoLewicki** [comment]
What was the last version of `expo`/`react-native-screens` where it worked correctly? I checked such old versions as `3.0.0` and it seems to not work there.

**Comment by jthies73** [comment]
Hello @WoLewicki! The Version I used before updating to expo 44.0.4 was react-native-screens 3.8.0.
Unfortunately I can not say to which package or API the Issue is related to. I posted the issue in react-navigation first because I was assuming that it is related to the NativeStackNavigator API. 
-> https://github.com/react-navigation/react-navigation/issues/10248

However I was told to also open this issue here as well.

Best regards,
Jo

**Comment by jthies73** [comment]
I just created a new branch for the last working version.
The only versions I changed are 
expo 44.0.0 -> 43.0.5 and
react-native-gesture-handler 2.1.0 -> 1.10.3

https://github.com/jthies73/NativeStackNavigatorIssue/tree/last_working_version

obviously now you get some warnings for other packages but I hope it helps to isolate the bug a bit more.

**Comment by jthies73** [comment]
solved by https://github.com/software-mansion/react-native-gesture-handler/issues/1823

thanks for your help 😊

**Comment by WoLewicki** [comment]
Great :tada: I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it.
