### ISSUE TITLE
Screen Flashes When App Opens Camera and return back to screen

### ISSUE THREAD

**Issue by MaganAnkur** [software-mansion/react-native-screens#1282]
I am using react-native-image-crop-picker to open camera and capture picture
### Version
- react-native-image-crop-picker v0.37.2
- react-native v0.66.4
- react-native-screens -v3.10.1

### Platform
- iOS
### Expected behaviour
After capturing the image using

Screen should not flicker as shown in attached video

### Actual behaviour

Screen flickers once after closing the camera

### Steps to reproduce

1.ImageCropPicker.openCamera({
      width: 300,
      height: 400,
      cropping: true,
      includeBase64: true,
    });

2. capture image and click use photo once camera closed and it returns back to app screen, screen flickers

### Attachments

https://user-images.githubusercontent.com/42070594/150831876-bec865a6-c981-4f0d-b7a3-713eb3ac922b.mp4

###Code
For Camera Permission I am using react-native-vision-camera

```
const onTakePicture = useCallback(async () => {
    if (onPressPrimaryBtn) {
      onPressPrimaryBtn();
    } else {
      const camPermission = await Camera.getCameraPermissionStatus();
      console.log(camPermission)
      if (camPermission === CAMERA_PERMISSIONS.AUTHORIZED || camPermission === CAMERA_PERMISSIONS.NOT_DETERMINED) {
        const image = await Camera.capturePhoto();
        image &&
          toScreen &&
          navigation?.navigate(toScreen, {imagePath: image?.path});
      } else if (camPermission === CAMERA_PERMISSIONS.DENIED) {
        //To Do Custom Modal
        return Alert.alert('Camera', 'Camera Permission Has To Be Enabled', [
          {
            text: 'Open Settings',
            onPress: openSettings,
          },
        ]);
      }
    }
  }, []);
```

#Camera.capturePhoto

 ```
static capturePhoto = async () => {
    return await ImageCropPicker.openCamera({
      width: 300,
      height: 400,
      cropping: true,
      includeBase64: true,
    });
  };
```

Thanks in advance.

**Comment by jforaker** [comment]
This is an issue in react-native-image-crop-picker that is not related to react-native-screens: https://github.com/ivpusic/react-native-image-crop-picker/issues/1658 

Somebody made a [patch](https://gist.github.com/Milker90/68b2faf3a7d027422761d43326645c51) and you can use at your own risk.

**Comment by MaganAnkur** [comment]
Thanks @jforaker for your quick response, I tried the patch and yes its working.

**Comment by jforaker** [comment]
> Thanks @jforaker for your quick response, I tried the patch and yes its working. I know its react-native-image-crop-picker issue. but just asking if I put that fix by changing the file it will rewrite my changes on fresh pod install isn't it? could you pls suggest how can I use the patch version. sorry for my naive question. Your help is appreciated

@MaganAnkur  - I'm not sure, I don't have experience with that actually -- I was just crossposting because I've seen the issue before. Best of luck.

**Comment by MaganAnkur** [comment]
no worries @jforaker I got this, i used patch-package to use the patch and its working as expected. closing this issue as this is react-native-screens issue .

Thanks @jforaker for all your help
