### ISSUE TITLE
RN 60.x ReactFragmentActivity deprecated

### ISSUE THREAD

**Issue by IntelliJAbhishek** [software-mansion/react-native-screens#129]
As per the RN60.x changelog ReactFragmentActivity is deprecated.

https://github.com/facebook/react-native/commit/8ea8dd6d48bc3db0b8255f320537e662e8fa2a09

**Comment by ChrisEelmaa** [comment]
duplicate of https://github.com/kmagiera/react-native-screens/issues/7

**Comment by jhoanborges** [comment]
Just use ReactActivity. Fragment activity is already included on the react core

**Comment by WoLewicki** [comment]
Looks like this issue is outdated, so I am closing it. Feel free to comment if I am wrong.
