### ISSUE TITLE
When navigate to a new screen in transparentModal screen, the new screen is under transparentModal screen

### ISSUE THREAD

**Issue by heynext** [software-mansion/react-native-screens#1292]
## Description

When navigate to a new screen(DetailsScreen) in transparentModal screen(ModalScreen), the new screen(DetailsScreen) is under transparentModal screen(DetailsScreen).

### Screenshots

![2022-01-31 01-26-31 2022-01-31 01_27_05](https://user-images.githubusercontent.com/13675762/151710303-c17b0ba4-aee4-44a8-9531-910d51993b26.gif)

## Steps To Reproduce

https://snack.expo.dev/@heynext/5b84d0

1. click `Open Modal`
2. click `Details`

### Expected behavior

DetailsScreen on the top

### Actual behavior

DetailsScreen is bellow ModalScreen

## Reproduction

https://snack.expo.dev/@heynext/5b84d0

## Platform

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [ ] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |         |
| @react-navigation/native               |   6.0.2      |
| @react-navigation/native-stack         |     6.0.5    |
| react-native-screens                   |   ~3.8.0      |
| react-native-safe-area-context         |  3.3.2       |
| react-native-gesture-handler           |   ~1.10.2      |
| react-native-reanimated                |         |
| expo                                   |         |

**Comment by WoLewicki** [comment]
This is how the modality works on `iOS`, modal screens are rendered in a different, higher view hierarchy. Can you check if using `containedTransparentModal` fixes your issue?

**Comment by heynext** [comment]
Thanks for your reply. I tried to use `containedTransparentModal`, but it seems doesn't work. The same expo link https://snack.expo.dev/@heynext/5b84d0.
And `Android` is ok using `containedTransparentModal` and `transparentModal`. I removed the `Android` tag.

**Comment by WoLewicki** [comment]
The only solution for this that seems reasonable at the moment is to reset the navigation state in a way that will dismiss the modal, navigate to next screen, and when the previous screen is shown again, push a modal again. I will try to make a PR adding an option of automatically dismissing a modal when there is a new non-modal screen pushed, but the logic may be a bit hard for this.

**Comment by WoLewicki** [comment]
I think I found another option, which is rendering the `containedTransparentModal` as a second screen of a nested stack, and since it is contained, it should navigate away when you push next screen in the non-nested stack. Can you check if this resolves your issue?

**Comment by heynext** [comment]
> I think I found another option, which is rendering the `containedTransparentModal` as a second screen of a nested stack, and since it is contained, it should navigate away when you push next screen in the non-nested stack. Can you check if this resolves your issue?

Like this? It does work. But because the `NestedModal` is nested in `Nested`, the `NestedModal` background is not `HomeScreen`.

![image](https://user-images.githubusercontent.com/13675762/152197078-38c55b9e-643a-4e54-8a51-9d956358d236.png)

![2022-02-03 00-38-48 2022-02-03 00_40_23](https://user-images.githubusercontent.com/13675762/152197401-1fc39afa-936d-47ad-9904-d6047b8ee63a.gif)

This is expected:

![image](https://user-images.githubusercontent.com/13675762/152198391-059972ac-3138-47f2-9696-64ccd2b7fd6a.png)

**Comment by WoLewicki** [comment]
Yeah, the nesting part is necessary since we need another navigator higher in the native hierarchy. I will close this issue then. Feel free to comment if something is wrong.
