### ISSUE TITLE
[iOS]: presentation: 'modal' in native-stack locks navigation after navigating to another modal screen too fast

### ISSUE THREAD

**Issue by vzhovnitsky** [software-mansion/react-native-screens#1299]
## Description

After we close modal screen with gesture and try to open another modal fast enough navigation within the stack locks and does not seem to work.

### Screenshots

https://user-images.githubusercontent.com/32094306/152166412-23a7d584-54cc-4c0a-8021-e118ab318fab.mp4

## Steps To Reproduce

Open screen with presentation: 'modal', then close it with gesture, then try to open another screen with presentation: 'modal'

### Expected behavior

Open new modal as intended

### Actual behavior

Locks navigation within stack

## Reproduction

https://snack.expo.dev/@vzhovnitsky/cranky-apples

## Platform

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [x] Managed workflow
- [ ] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.8 |
| @react-navigation/native-stack         | 6.4.0 |
| react-native                           | 0.66.4 |
| expo                                   | 44.0.0 |

**Comment by andre161292** [comment]
Seems to still happen. At https://snack.expo.dev/swfnLagOD with the updated fix included (Version 3.13.1), this happens even faster.
The proposed workaround from https://github.com/react-navigation/react-navigation/issues/10324#issuecomment-1034176369 also still circumvents the problem, so it seems being the same issue.

**Comment by WoLewicki** [comment]
I tested it on the newest main and it works ok for me @andre161292. Can you show e.g. a video on which it does not work correctly?

**Comment by WoLewicki** [comment]
Are you able to reproduce it without Expo?

**Comment by andre161292** [comment]
Yes i'm able to. I found this thread, because i faced the issue in one of our companies apps. But as it's an unreleased app, i cannot share footage of it - that's why i went with the Expo demo.

**Comment by andre161292** [comment]
@WoLewicki I'm sorry to say, but it's also happening to me on an iPhone (iOS 15.5 as well) - both in Expo and in our app.
