### ISSUE TITLE
[iOS][bug] - RNS 3.11.0 has broken fullScreenGestureEnabled

### ISSUE THREAD

**Issue by hirbod** [software-mansion/react-native-screens#1312]
## Description

I've just upgraded to 3.11.0 and I can't swipe anymore with fullScreenSwipe. It looks like it has a 10x friction and even if I swipe the whole screen, it just move by 5px and snaps back

## Steps To Reproduce

1. Update to 3.11.0 and you won't be able to close any screen with fullScreenGestureEnabled

### Expected behavior

Should be able to swipe to pop

### Actual behavior

Can't swipe to pop anymore

## Reproduction

Just upgrade to 3.11.0 and try to swipe with fullScreen without setting any durations etc.
Video: https://streamable.com/wsdztc

```tsx
      <RouterMainStack.Screen
        name="Blocker"
        component={Blocker}
        options={{
          fullScreenGestureEnabled: true,
        }}
      />
```

## Platform

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [x] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |   0.64.3      |
| @react-navigation/native               | 6.0.8        |
| @react-navigation/native-stack         |   6.5.0      |
| react-native-screens                   | 3.11.0        |
| react-native-safe-area-context         |   3.3.2      |
| react-native-gesture-handler           |   2.1.1      |
| react-native-reanimated                |  2.4.1       |
| expo                                   |  SDK 44 custom dev client       |

**Comment by hirbod** [comment]
Oh, lol. It is actually closing when I swipe from top to bottom, but not from left to right.
Guess this PR is the reason:

https://github.com/software-mansion/react-native-screens/commit/f2ac36b2dd982a320acc5e4ab44700925f313d82

**Comment by hirbod** [comment]
Here is a video, demonstrating the issue: 3.10.2 is working without issues.
https://streamable.com/wsdztc

**Comment by kacperkapusciak** [comment]
Brrr, nasty bug 😓  

Fixed in [3.11.1](https://github.com/software-mansion/react-native-screens/releases/tag/3.11.1) :shipit:

**Comment by hirbod** [comment]
Thank you!

**Comment by hirbod** [comment]
I can confirm it's fixed. Only the new props are missing on react-navigation
