### ISSUE TITLE
crash when dismissing modal via JS

### ISSUE THREAD

**Issue by ericvicenti** [software-mansion/react-native-screens#1329]
```
2022-02-17 12:51:49.510461-0800 expoapp[12511:220743] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally a view controller <UIViewController: 0x13601efa0> that is already being presented by <UIViewController: 0x13ae0c050>.'
```

## Description

When calling goBack from a modal, app crashes after the close animation completes. This crash does not happen when going back via a gesture!

## Steps To Reproduce

one native stack navigator with a screen with `presentation: 'modal'`

1. open modal by tapping on 'settings'
2. close by tapping the close button (close gesture does not cause crash)

### Expected behavior

no crash or redbox

### Actual behavior

native crash:

<img width="1522" alt="Screen Shot 2022-02-17 at 12 52 11 PM" src="https://user-images.githubusercontent.com/1483597/154569814-c2f60895-065f-4126-b41b-a1f402a87057.png">

## Reproduction

[demo repo](https://github.com/zerve-app/zerve)

Run the native iOS app in apps/mobile/ios then run `yarn mobile` from repo root

## Platform

iOS (did not check other platforms)

## Workflow

Expo bare workflow

## Package versions

```
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "expo": "~44.0.6",
    "react-native-reanimated": "^2.4.1",
    "react-native-safe-area-context": "3.4.0",
    "react-native-screens": "~3.12.0",
```

**Comment by ericvicenti** [comment]
An update if you stumble across this: The error was caused by competing versions of RN both firing a redbox.

Scrolling through the Xcode logs reveal the two errors that RN was attempting to display simultaneously.

For anyone who comes across this: be careful in monorepos and use `"peerDependencies": { "react-native": "*" }` in your packages!

Thank you @kacperkapusciak for your time spent identifying this ❤️

**Comment by rcidt** [comment]
@ericvicenti adding `"peerDependencies": { "react-native": "*" }` to your project's package.json fixed the issue?

**Comment by ericvicenti** [comment]
yes, the react native app in my repo uses Expo and hence RN 0.64. Meanwhile the package in the repo specified `"dependencies": { "react-native": "*"` and the most recent version of RN was installed by yarn, alongside 0.64. It seems that both RN versions were throwing a redbox, hence this crash. By changing my package to `"peerDependencies": { "react-native": "*"`, it stopped including the latest version and just 0.64.

**Comment by rcidt** [comment]
@ericvicenti thanks for the explanation
