### ISSUE TITLE
ScreenStack only accepts children of type Screen

### ISSUE THREAD

**Issue by sergey-rudenko-websailors** [software-mansion/react-native-screens#1331]
## Description
I added a router to the project. Immediately after building the application an error appeared

```
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
const Stack = createNativeStackNavigator();

const App = () => {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="HomeScreen" component={Home} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

const Home = () => {
  return (
    <View>
      <Text>Hello!</Text>
    </View>
  );
};

```
### Screenshots
<img width="447" alt="Screenshot 2022-02-18 at 10 07 15" src="https://user-images.githubusercontent.com/97535232/154635378-0e0616aa-41d5-4e6d-b98a-8cb9ad50d8be.png">
<img width="1532" alt="Screenshot 2022-02-18 at 10 24 33" src="https://user-images.githubusercontent.com/97535232/154636917-787c7d7e-bcf8-41d9-a6ae-8e080d25e9a4.png">

## Platform
- [x] iOS

## Workflow
React-Native CLI

## Package versions

"dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "react": "17.0.2",
    "react-native": "0.67.2",
    "react-native-gesture-handler": "^2.2.0",
    "react-native-image-slider-box": "^1.1.17",
    "react-native-safe-area-context": "^3.4.0",
    "react-native-screens": "^2.18.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "react-test-renderer": "17.0.2"
  }

**Comment by kacperkapusciak** [comment]
Hi @sergey-rudenko-websailors :wave:
It looks like you are using Screens in version `2.18.1`. React Navigation v6 requires version `3.0.0` or higher.

Upgrading `react-native-screens` to the latest version resolves the problem.

Cheers
