### ISSUE TITLE
Build failed after upgrade to 3.12.0

### ISSUE THREAD

**Issue by waheedakhtar694** [software-mansion/react-native-screens#1332]
On Android i am getting this error while building 
FYI: I just added `newArchEnabled=true` as mentioned in the docs, in the `gradle.properties`.
Now after cleaning and reinstalling the newer version i am getting this error.

<img width="891" alt="Screenshot 2022-02-18 at 6 09 31 PM" src="https://user-images.githubusercontent.com/45425486/154689135-fea9cb6b-da84-42f7-b668-c420b076c11f.png">

On IOS i enabled fabric inside podfile by adding this flag ` :fabric_enabled => true` and added react-native-codegen in my node modules but now when i try to install pods with this command `RCT_NEW_ARCH_ENABLED=1 pod install` i am getting this error.

<img width="820" alt="Screenshot 2022-02-18 at 6 17 32 PM" src="https://user-images.githubusercontent.com/45425486/154690180-a2b2534d-1819-4eea-bedd-8f2458eb013e.png">

Any solution to fix these will be appreciated, thanks.

**Comment by kacperkapusciak** [comment]
Hi @waheedakhtar694 :wave:
Thanks for your interest in using `react-native-screens` with Fabric! 

First thing - please don't delete the issue template when reporting an issue but fill it out instead 😅

Next, what version of `react-native` are you using? Fabric architecture isn't yet available in any `react-native` release except for release candidates of v0.68.

Also, there aren't any other libraries that use the Fabric architecture so far, so you most probably don't really want to change the architecture of your app from Paper to Fabric at this particular point of time 😄

Cheers

**Comment by waheed25** [comment]
@kacperkapusciak thanks for your quick reply and suggestion to fill the issue template 😁.

I am using `react-native` v0.67.2, so if i move my version to 0.68-rc.1 will it work or anything else is required ? 

I am just curious to test fabric may be i will revert after testing it if some other library makes a problem otherwise i will be keep using fabric.

**Comment by waheedakhtar694** [comment]
@kacperkapusciak thanks so much for this detailed explanation, yes I have other native modules too so I will test this in a separate project, thanks.

**Comment by ZeeshanAhmadKhalil** [comment]
I downgraded the version to `3.10.2` i am getting this error

`Error: Unable to resolve module ./fabric`

**Comment by pierroo** [comment]
> I downgraded the version to `3.10.2` i am getting this error
> 
> `Error: Unable to resolve module ./fabric`

I am on 3.15.0; getting the same error; which is weird since I never got it before.
tried all kind of delete node_modules / clearing cache / restarting the computer etc, without luck.

Did you manage to find a solution? :)
