### ISSUE TITLE
Android problem with 0.68-rc2 using screens 3.12.0 with the new architecture

### ISSUE THREAD

**Issue by TheRogue76** [software-mansion/react-native-screens#1345]
## Description
Version ```3.12.0``` does not work with RN 0.68-rc2. As of that version, ```react-native-gradle-plugin``` has become a dependency of ```react-native``` and is no longer part of it's ```package.json```. When calling ```./gradlew assembleRelease``` or ```./gradlew clean``` the command fails and throws the following error:
```
./gradlew assembleRelease && ..      
Starting a Gradle Daemon, 2 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'RN068RC2'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':classpath'.
      > Could not find com.facebook.react:react-native-gradle-plugin:.
        Required by:
            project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Screenshots
![Screen Shot 1400-12-07 at 02 41 07](https://user-images.githubusercontent.com/40071952/155815235-f62870b4-fd63-4b21-b1e6-13030d18dba3.png)

## Steps To Reproduce

1. ```npx react-native init RN068RC2 --version 0.68.0-rc.2```
2. ```yarn add react-native-screens```
3. ```./gradlew assembleRelease```

### Expected behavior
For the project to build and create a usable apk

### Actual behavior
https://github.com/reactwg/react-native-releases/discussions/13#discussioncomment-2254502

## Reproduction

https://github.com/TheRogue76/failed-rc2-react-native-screens

## Platform

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [X] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |     0.68.0-rc.2    |
| react-native-screens                   |     3.12.0    |

**Comment by Simon-TechForm** [comment]
Can confirm that we are experiencing this as well. Installing `react-native-screens@3.12.0` on `react-native@0.68.0-rc.2` causes the build error mentioned above. We haven't enabled the new architecture either, but aren't planning to do so at this stage. Reverting to `react-native-screens@3.11.1` for now.

**Comment by TheRogue76** [comment]
> Hello! Thanks for reporting.
> 
> From the example you have provided, it looks like you forgot to enable the new architecture ([link](https://github.com/TheRogue76/failed-rc2-react-native-screens/blob/master/android/gradle.properties#L40)). Please change this line to `newArchEnabled=true` in order to enable Fabric and let us know if it works for you.
> 
> However, even with `newArchEnabled=false`, this should still work on Paper (the old React Native renderer). We'll need to take a look on that, thanks again.

Yeah sorry about that. I was working on a project with 0.68 + the new architecture and once I discovered the source of that bug, I created this project separately for this repo and forgot to enable the architecture it here. But as the conversation threads point out, it was indeed a problem. Thanks for releasing 3.13.0 so quickly
