### ISSUE TITLE
fabric: attemps to access this ref will fail 

### ISSUE THREAD

**Issue by matinzd** [software-mansion/react-native-screens#1347]
## Description

```
 ERROR  Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

### Screenshots

![Screenshot 2022-03-01 at 23 56 30](https://user-images.githubusercontent.com/24797481/156262839-23ec5ec8-d3e3-4ce2-923d-9b45ee618ab6.png)

## Steps To Reproduce

1. Setup a bare react native project with 0.68-rc2
2. Enable new architecture on android.
3. Run the sample code.

### Expected behavior
Run without warnings.

### Actual behavior

Run with warnings.

## Reproduction

```
import * as React from 'react';
import {View, Text, Button} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';

function HomeScreen({navigation}) {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Home Screen</Text>
      <Button
        title="Go to Details"
        onPress={() => navigation.navigate('Details')}
      />
    </View>
  );
}

function DetailsScreen() {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Details Screen</Text>
    </View>
  );
}

const Stack = createNativeStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Details" component={DetailsScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;
```

## Platform

- [x] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |    0.68.0-rc2     |
| @react-navigation/native               |     6.0.8    |
| @react-navigation/native-stack         |    6.5.0    |
| react-native-screens                   |    3.13.0   |
| react-native-safe-area-context         |    4.1.2     |
| react-native-gesture-handler           |     N/A    |
| react-native-reanimated                |     N/A    |
| expo                                   |     N/A    |

**Comment by TheRogue76** [comment]
I've been getting the same warning as well with 0.68-rc2

**Comment by kacperkapusciak** [comment]
Hi @matinzd :wave:
Thanks for creating an issue 🎉 
Could you confirm that #1351 fixes the issue?

Cheers

**Comment by matinzd** [comment]
@kacperkapusciak Will try and I will let you know!
