### ISSUE TITLE
Bizarre interaction between StatusBar, Orientation, and NativeStackNavigator

### ISSUE THREAD

**Issue by jakeorbtl** [software-mansion/react-native-screens#1358]
## Description
(android)
The following interaction occurs when using the Native Stack Navigator from `@react-navigation/native-stack` with the `screenOptions` property set as such:
```
screenOptions={{
   orientation: 'portrait-up'
}}
```
If you lock the screen orientation to landscape (using either `expo-screen-orientation` or `react-native-orientation-locker`) and then hide the status bar (using `expo-status-bar`), the screen rotates back to `portrait-up`. Subsequent attempts to lock the screen while the status bar is still hidden will succeed.

I did some testing, and this interaction only happens with this exact set up. The interaction does not happen when using the StatusBar component from `react-native`, nor does it happen if `orientation` from `screenOptions` is not set.

If it would be more appropriate to raise this issue with expo, please let me know.

## Steps To Reproduce

1. Create a new expo project and install the necessary libraries:
```
$ expo init status-bar-test
✔ Choose a template: › blank
$ cd status-bar-test
$ npm install @react-navigation/native @react-navigation/native-stack
$ expo install react-native-screens react-native-safe-area-context expo-screen-orientation
```
2. Replace the contents of `App.js` with the following:
```
import { StatusBar } from 'expo-status-bar';
import Navigator from './Navigator';
import { NavigationContainer } from '@react-navigation/native';

export default function App() {
  
  return (
    <NavigationContainer>
      <StatusBar />
      <Navigator />
    </NavigationContainer>
  );
}
```
3. Create a file called Navigator.js in the root folder and add the following code:
```
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import MainScreen from "./MainScreen";

const Stack = createNativeStackNavigator();

function Navigator() {
    return (
        <Stack.Navigator screenOptions={{
            orientation: 'portrait-up'
        }}>
            <Stack.Screen name="MainScreen" component={MainScreen} />
        </Stack.Navigator>
    );
}

export default Navigator;
```
4. Create a file called MainScreen.js in the root folder and add the following code:
```
import { Text, View, TouchableOpacity} from 'react-native';
import { setStatusBarHidden } from 'expo-status-bar';
import * as ScreenOrientation from 'expo-screen-orientation';

export default () => {
  const lockLeftAndHideStatusBar = () => {
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE_LEFT);
    setStatusBarHidden(true, 'none');
  };

  const unlockAndUnhide = () => {
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT_UP);
    setStatusBarHidden(false, 'none');
  };

    return (
        <View style={{
            flex: 1,
            backgroundColor: '#fff',
            alignItems: 'center'
          }}>
            <TouchableOpacity
                onPress={lockLeftAndHideStatusBar}
                style={{
                    backgroundColor: 'rgba(0,0,100,0.1)',
                    width: '70%',
                    borderRadius: 5,
                    marginTop: 40
                }}>
                <Text style={{
                    fontSize: 24,
                    textAlign: 'center'
                }}>Tap here to lock orinetation to LANDSCAPE_LEFT and hide the status bar.</Text>
            </TouchableOpacity>
            <TouchableOpacity
                onPress={() => ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE_LEFT)}
                style={{
                    backgroundColor: 'rgba(0,100,0,0.1)',
                    width: '70%',
                    borderRadius: 5,
                    marginTop: 40
                }}>
                <Text style={{
                    fontSize: 24,
                    textAlign: 'center'
                }}>Tap here to lock orinetation to LANDSCAPE_LEFT.</Text>
            </TouchableOpacity>
            <TouchableOpacity
                onPress={() => setStatusBarHidden(true)}
                style={{
                    backgroundColor: 'rgba(100,0,0,0.1)',
                    width: '70%',
                    borderRadius: 5,
                    marginTop: 40
                }}>
                <Text style={{
                    fontSize: 24,
                    textAlign: 'center'
                }}>Tap here to hide status bar.</Text>
            </TouchableOpacity>
            <TouchableOpacity
                onPress={unlockAndUnhide}
                style={{
                    backgroundColor: 'rgba(0,0,0,0.1)',
                    width: '70%',
                    borderRadius: 5,
                    marginTop: 40
                }}>
                <Text style={{
                    fontSize: 24,
                    textAlign: 'center'
                }}>Tap here to reset.</Text>
            </TouchableOpacity>
        </View>
    );
};
```
5. Run the app and play around with it to experience the bug:
```
$ expo start
```

## Platform

- [x] Android
As far as I can tell, this doesn't affect iOS, as the status bar appears to be hidden automatically when locking to landscape.

## Workflow

- [x] Managed workflow
- [x] Bare workflow
(This interaction occurs in both workflows)

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |0.64.3|
| @react-navigation/native               |6.0.8|
| @react-navigation/native-stack         |6.5.0|
| react-native-screens                   |3.10.2|
| react-native-safe-area-context         |3.3.2|
| react-native-gesture-handler           |2.1.3|
| expo                                   |44.0.6|

**Comment by kkafar** [comment]
Is there any specific use case to enforce screen orientation with `react-native-screens` and then change it with different library? My point is that you can most likely achieve desired effect only with using single library. 

This seems to me more like some minor integration-between-libraries problem rather than something `react-native-screens` specific.

I'll close this issue due to aforementioned reason, however feel free to tag & notify me if you disagree.

**Comment by jakeorbtl** [comment]
@kkafar My use case is that I'm creating a custom video player that has rotate to fullscreen capability, as well as a fullscreen button that forces the orientation to change. The reason I'm using both `react-native-screens` and another orientation library is that I need my app to be locked to the 'portrait_up' orientation when it starts up, and the only way to ensure that using either `expo-screen-orientation` or `react-native-orientation-locker` is to do something akin to `Orientation.lockToPortrait();` when the app first mounts. This works on iOS, but as you can probably guess, it has no effect on android. What does work on android is setting the stack screen options to `orientation: 'portrait_up'` but of course, that then leads to the status bar interaction. I can't think of a work-around for this issue short of fixing the `lockToPortrait()` bug on the other library.
