### ISSUE TITLE
Crash using FullWindowOverlay

### ISSUE THREAD

**Issue by hukpo** [software-mansion/react-native-screens#1374]
## Description
I'm experiencing a crash using FullWindowOverlay with navigation.goBack()
The problem is here because _container is nil:
https://github.com/software-mansion/react-native-screens/blob/ef0e103ecdc0de867d69b560e453bd63b0d5dbfc/ios/RNSFullWindowOverlay.m#L79

The reason it's nil is because didMoveToWindow was called 2 times
https://github.com/software-mansion/react-native-screens/blob/ef0e103ecdc0de867d69b560e453bd63b0d5dbfc/ios/RNSFullWindowOverlay.m#L75

### Screenshots
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40897161/160256579-2cfe82a6-d006-4398-88de-c9eb7af4c961.png">

## Steps To Reproduce
1. Open screen with FullWindowOverlay
2. Go back using navigation.goBack()

### Expected behavior
No crash

### Actual behavior
Crash

## Reproduction
https://github.com/hukpo/rncrash

## Platform
- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow
- [ ] Managed workflow
- [x] Bare workflow

## Package versions
| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |0.67.4         |
| @react-navigation/native               |^6.0.8         |
| @react-navigation/native-stack         |^6.5.2         |
| react-native-screens                   |^3.13.1         |
| react-native-safe-area-context         |^4.2.2         |

**Comment by WoLewicki** [comment]
Can you check if https://github.com/software-mansion/react-native-screens/pull/1375 fixes your issue and does not introduce any new ones?

**Comment by hukpo** [comment]
@WoLewicki Thanks, it works well now

**Comment by dancixx** [comment]
It is still happening.

```
react-native: 0.67.4
react-native-screens: latest
```

**Comment by WoLewicki** [comment]
@dancixx please provide a repository where it can be easily reproduced so we can work on it.
