### ISSUE TITLE
Deployment target issue

### ISSUE THREAD

**Issue by ScreamZ** [software-mansion/react-native-screens#138]
Hello,

Thanks for this great lib

on IOS build I got this warning : 

`The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'RNScreens')`

Any idea ?

Thanks :)

**Comment by WoLewicki** [comment]
You can read about it here: https://stackoverflow.com/questions/54704207/the-ios-simulator-deployment-targets-is-set-to-7-0-but-the-range-of-supported-d I am closing it. Feel free to comment if something is unclear.
