### ISSUE TITLE
Header in modal is sometimes missing background on iOS 13 & 14

### ISSUE THREAD

**Issue by escwald** [software-mansion/react-native-screens#1391]
## Description
Providing `headerLeft` and `headerRight` with a component for a modal screen can result in an incorrect header background on iOS 13 & 14 (cannot be reproducible on iOS 12 & 15). This does not happen every time (about 50% of the time), but is easily reproducible by re-opening the modal until it appears.

Example
```
<Stack.Navigator
   screenOptions={{
     headerStyle: {
       backgroundColor: 'pink',
     },
  }}
  initialRouteName='Main'
>
  <Stack.Group screenOptions={{ presentation: 'modal' }}>
    <Stack.Screen
      name='Search'
      component={Search}
      options={{
        headerLeft: () => <View />,
      }}
    />
  </Stack.Group>
  <Stack.Screen name='Main' component={Main} />
</Stack.Navigator>
```
The bug occurs even if you do not provide the `backgroundColor`, but providing one makes it more clear when it occurs.

### Screenshots
When it works:
![Screenshot 2022-04-04 at 11 37 15](https://user-images.githubusercontent.com/1682198/161517461-63c91ab9-b993-4d6b-9303-4ef3ef0d813c.png)

Header inspected in Flipper when it works:
![Screenshot 2022-04-04 at 11 30 32](https://user-images.githubusercontent.com/1682198/161515988-daaae362-9c97-4fe4-bca9-4dc26436eac1.png)

When the bug occurs:
![Screenshot 2022-04-04 at 11 37 31](https://user-images.githubusercontent.com/1682198/161517476-444ce404-2419-4a96-ad08-5954fa18ea7f.png)

Header inspected in Flipper when bug occurs:
![Screenshot 2022-04-04 at 11 29 38](https://user-images.githubusercontent.com/1682198/161516009-71e9eb52-3e0b-497f-bc0f-84eab2ce8cca.png)

## Steps To Reproduce

1. Run the app on either iOS 13 or iOS 14
2. Open the modal
3. If bug does not occur, go back and redo previous step.

### Expected behavior
Modal is always opened with correct background color in its header

### Actual behavior
Sometimes opened with a gradient effect background

## Reproduction

Minimial app using bare workflow: [modal-test.zip](https://github.com/software-mansion/react-native-screens/files/8408462/modal-test.zip)

1. Unpack
2. `npm i`
3. `npx pod-install`
4. `npm run ios`

## Platform

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |    0.67.3   |
| @react-navigation/native               |     6.0.10    |
| @react-navigation/native-stack         |    6.6.1     |
| react-native-screens                   |     3.13.1    |
| react-native-safe-area-context         |     4.2.4    |

**Comment by hirbod** [comment]
@escwald does this issue also happen when you apply the color directly on `Group`? Or when you even remove group and apply the presentation as an option to the specific screen? Might be a timing issue traversing the parent or something similar.

**Comment by escwald** [comment]
Yea, I can remove `Group` and put the option inside the screen component and it still happens. Same with `backgroundColor`. You can leave out the `headerStyle` & `backgroundColor` completely and it still happens, it just makes it more clear when the bug occurs.
```
<Stack.Navigator initialRouteName='Main'>
  <Stack.Screen
    name='Search'
    component={Search}
    options={{
      presentation: 'modal',
      headerLeft: () => <View />,
    }}
  />
  <Stack.Screen name='Main' component={Main} />
</Stack.Navigator>
```
[modal-test-wo-group.zip](https://github.com/software-mansion/react-native-screens/files/8409605/modal-test-wo-group.zip)
[modal-test-wo-group-and-header-style.zip](https://github.com/software-mansion/react-native-screens/files/8409645/modal-test-wo-group-and-header-style.zip)


You can change the looks of the bug with `headerTransparent` and `headerBlurEffect`, but the bug will still occur, i.e. that it is inconsistent in how the header looks like.

**Comment by codeion** [comment]
Happens with presentation: 'card' as well.

**Comment by kostiantyn-ccm** [comment]
Still reproduced on ios14 with `presentation: 'modal',`

**Comment by ramiel1999** [comment]
@escwald did you solve it
