### ISSUE TITLE
Tabs Navigator not working with New Architecture

### ISSUE THREAD

**Issue by wwdrew** [software-mansion/react-native-screens#1405]
## Description

I've created a new app using React Native 0.68 and opted into the new architecture for iOS. I've then installed React Navigation, with the bottom-tabs navigator using the example code from the documentation. When building the app, this is the result:

### Screenshots

<img width="502" alt="Screenshot 2022-04-11 at 14 47 22" src="https://user-images.githubusercontent.com/49833875/162775723-3800bec2-2955-4415-a659-f47e90835871.png">

## Steps To Reproduce

1. Install @react-navigation/native, @react-navigation/bottom-tabs with an app using the new architecture.
2. Create a tab stack.

### Expected behavior

Screens and tabs to render correctly, as they do when using the old architecture.

### Actual behavior

An error screen is being displayed behind the tab screen with the message "Unimplemented component: <RNSScreenNavigationComponent>"

## Reproduction

https://github.com/wwdrew/react-navigation-tabs-error

## Platform

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |  0.68.0       |
| @react-navigation/native               |  6.0.10       |
| @react-navigation/bottom-tabs          | 6.3.1 |
| react-native-screens                   |  3.13.1       |
| react-native-safe-area-context         |  4.2.4       |

**Comment by WoLewicki** [comment]
Currently only `native-stack` works with the new architecture. We are in the process of transforming all of the components to new architecture. Can I help you more with this?

**Comment by mbritton** [comment]
I have a potential project a few weeks out that will need RTL layout with TopTabNavigator. Does this timeline sync with your projected release containing components that are compatible with the new architecture?

**Comment by wwdrew** [comment]
@WoLewicki No worries, completely understand that the transition to new architecture won't happen overnight :) Just thought I'd document this error I found while working on a project. As a workaround, I've backed out my new app from using the new architecture until more libraries are compatible with it so I'm not in any rush.

However, if you're able to point me in the right direction to how I could help move this forward though, I'll see if I can find some time to help out.

**Comment by WoLewicki** [comment]
@mbritton all of the other libs you use in the project are already supporting new architecture? IIRC, `TopTabNavigator` doesn't even use `react-native-screens` iirc. 

@wwdrew thanks for offering help ❤️  Migration of `react-native-screens` should end soon and @kkafar is working hard on it 💪  There are many other libraries that need help with transformation so if you have some free time, you can help maintainers port them to new architecture.

**Comment by kkafar** [comment]
Hi @wwdrew!
We've just released version 3.14 with https://github.com/software-mansion/react-native-screens/pull/1458 which should resolve your issue on iOS. Could you try to upgrade and let us know whether it works for you now?

**Comment by wwdrew** [comment]
Hi @kkafar,

I've just tested this out and it's working perfectly now, thank you so much! Looking at that PR I can't imagine how much work must've gone into this, so thank you a million times over for your awesome work!
