### ISSUE TITLE
Back button wrong language

### ISSUE THREAD

**Issue by drthoben** [software-mansion/react-native-screens#1425]
## Description

I'm using `@react-navigation/native-stack` on my German iPhone. When using the stack, the back button title says "Back" instead of "Zurück".

## Steps To Reproduce

1. `git clone https://github.com/drthoben/react-navigation-repro.git`
2. `cd react-navigation-repo`
3. `yarn && yarn start`

### Expected behavior

The back button should say "Zurück".

### Actual behavior

My iPhone language is set to German. The back button title says "Back".

## Reproduction

https://github.com/drthoben/react-navigation-repro

## Platform

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [x] Managed workflow
- [ ] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native | 6.0.10
| @react-navigation/native-stack | 6.6.2
| expo | 44.0.6
| expo-status-bar | 1.2.0
| react | 17.0.1
| react-dom | 17.0.1
| react-native | 0.64.3
| react-native-safe-area-context | 3.3.2
| react-native-screens | 3.13.1
| react-native-web | 0.17.1
| react-native                           | 0.64.3
| expo                                   | 5.0.3
| node                                   | v16.13.1
| yarn                            | v1.22.17

**Comment by hirbod** [comment]
You have to add  the infoPlist key `CFBundleAllowMixedLocalizations: true,`
When you're using expo, this is done via `app.config.ts/js` under expo.iOS.infoPlist

When you're not using expo, just edit your plist in XCode.

Dann klappt das auch ;)

**Comment by hirbod** [comment]
You are indeed using expo.
https://github.com/drthoben/react-navigation-repro/blob/main/app.json

Just add the key "ios": { infoPlist....

**Comment by drthoben** [comment]
> You have to add the infoPlist key `CFBundleAllowMixedLocalizations: true,` When you're using expo, this is done via `app.config.ts/js` under `expo.ios.infoPlist`
> 
> When you're not using expo, just edit your plist in XCode.
> 
> Dann klappt das auch ;)

Thank you very much!

Actually, `CFBundleAllowMixedLocalizations` was the perfect hint for me.

I've tried setting it to `true` but it didn't work. So I consulted the Apple documentation and there it is suggested to set the value of `CFBundleAllowMixedLocalizations` to `"YES"`.

This works perfectly fine.
