### ISSUE TITLE
Search bar on Android incorrectly adjusts other header elements when open

### ISSUE THREAD

**Issue by nrwinner** [software-mansion/react-native-screens#1450]
## Description

On Android, the search bar does not properly adjust header elements.
- Elements placed via `headerRight` are "pushed" out of the way and to the left of the search bar
- If there are any elements placed via `headerLeft`, both the screen title and said elements are not adjusted at all and appear under the search bar

### Screenshots
<img width="412" align="left" alt="Screen Shot 2022-05-17 at 10 33 52 AM" src="https://user-images.githubusercontent.com/7431390/168837599-e91dfe49-d549-45a8-a4c3-9376014653b9.png">

<img width="408" alt="Screen Shot 2022-05-17 at 10 34 05 AM" src="https://user-images.githubusercontent.com/7431390/168837610-1ec6766c-31a0-4771-a2c8-788a485655db.png">

## Steps To Reproduce

1. Add a search bar to the header by specifying `headerSearchBarOptions`
2. Add any element(s) via the `headerLeft` navigation option
3. (Optional) Add any elements to the `headerRight` navigation option
4. Open the search bar on android

### Expected behavior
- The header buttons on both the left side and the right side should no longer be visible. 
- The search bar should appear as the only element in the header.
- The input should be unobstructed.

### Actual behavior
- Any elements placed via `headerRight` seem to get "pushed" out of the way to the left of the search bar
- The screen title as well as any elements placed by `headerLeft` are not adjusted and appear under the search bar

## Reproduction

https://snack.expo.dev/@nrwinner/android-search-bug---react-native-screens-repro

## Platform

- [ ] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [x] Managed workflow
- [ ] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |    0.68.1     |
| @react-navigation/native               |    6.0.2     |
| @react-navigation/native-stack         |    6.1.0     |
| react-native-screens                   |   3.13.1      |
| react-native-safe-area-context         |     4.2.4    |
| expo                                   |     45.0.0    |

**Comment by hirbod** [comment]
I can confirm this issue. Forced me to remove searchHeader completely

**Comment by wem2017** [comment]
I face the same issue, thanks for your feedback
![image](https://user-images.githubusercontent.com/58833808/188894125-f911b1ad-588f-486a-82bc-f3a8488d7238.png)
![image](https://user-images.githubusercontent.com/58833808/188894320-ae76f091-2d81-4e3d-ae97-981a7b162788.png)

**Comment by EliasBarrera** [comment]
could you find a solution ?

**Comment by nrwinner** [comment]
@EliasBarrera I used the `onOpen` and `onClose` callbacks from the search bar to hide the header buttons while the search bar is open. Less than ideal and kinda laggy but it's the best I could do until this gets fixed.

**Comment by EliasBarrera** [comment]
Thank you! :D

**Comment by mazurGit** [comment]
You can try to place component on headerLeft insead of headerRight and add marginLeft to it :

https://user-images.githubusercontent.com/69375560/194675879-283f5e0a-478b-439e-bda7-ea160f3fb689.mp4

**Comment by tboba** [comment]
Hi @nrwinner, thanks for reporting that! Sorry for the really late response 🙏 
I've managed to reproduce this problem and successfully fixed that! I'll create a PR shortly 🥳

**Comment by tboba** [comment]
Hi @nrwinner @garrettg123 @EliasBarrera @wem2017 @hirbod, there's a new version of react-native-screens: 3.26.0 which has this change included. Check it out! If you find something wrong related to the newest version (this change is still buggy or doesn't work for you) let us know 🎉

**Comment by hirbod** [comment]
Great, we actually have a use case for this so I am keen to try it
