### ISSUE TITLE
The type NativeStackNavigationProp has a missing type argument

### ISSUE THREAD

**Issue by Yupeng-li** [software-mansion/react-native-screens#1459]
## Description

The type `NativeStackNavigationProp` has a missing type argument.  [(see the code) ](https://github.com/software-mansion/react-native-screens/blob/90e548739f35b5ded2524a9d6410033fc233f586/src/native-stack/types.tsx#L41)

`NavigationProp` [(see the code)](https://github.com/react-navigation/react-navigation/blob/4e4935ac2584bc1a00209609cc026fa73e12c10a/packages/core/src/types.tsx#L305) expects 6 arguments, but only 5 are given. `NavigatorID` is missing. This caused an issue that `navigation.setOptions` doesn't pickup correct type of screen options. 

### Screenshots
![image](https://user-images.githubusercontent.com/31921080/170520590-f774f050-81ae-4370-bb56-bf22b0b30fe3.png)

## Steps To Reproduce
The details are included in the description section above. 

### Expected behavior
I expect `navigation.setOptions` to use correct type

### Actual behavior
`navigation.setOptions` always shows type error because of the issue.

## Reproduction

I think the error is obvious enough without having a minimal repo.

## Platform

- [x] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |    0.66.3     |
| @react-navigation/native               |    6.0.10     |
| @react-navigation/native-stack         |    6.6.2     |
| react-native-screens                   |    3.13.1     |
| react-native-safe-area-context         |    4.2.5     |
| react-native-gesture-handler           |    2.4.2     |
| react-native-reanimated                |         |
| expo                                   |         |

**Comment by WoLewicki** [comment]
Are you using `@react-navigation/native-stack` or `react-native-screens/native-stack`? You should use the first one if you use `react-navigation` v6 and the second one for v5.

**Comment by Yupeng-li** [comment]
Thank you for pointing this out. I used `react-native-screens/native-stack`. Once I switched to `@react-navigation/native-stack`, it worked like a charm 👍 . I'll close this issue.
