### ISSUE TITLE
Unable to build v3.13.1 with RN 0.69 and Fabric 

### ISSUE THREAD

**Issue by maxperry** [software-mansion/react-native-screens#1474]
## Description

Xcode build is failing with `No template named 'optional' in namespace 'std'; did you mean 'folly::Optional'?`

### Screenshots
<img width="896" alt="Screen Shot 2022-06-09 at 9 54 56 AM" src="https://user-images.githubusercontent.com/6955822/172865028-942660d7-e43c-461e-8bd6-f14ca9152111.png">

## Steps To Reproduce

1.`USE_FABRIC=1 RCT_NEW_ARCH_ENABLED=1 pod install`
2. Build with Xcode.

### Expected behavior
Succeeds to build.
### Actual behavior
Fails to build.
## Platform

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           | 0.69.0-rc.6|
| @react-navigation/native               |6.0.10|
| @react-navigation/native-stack         |6.6.2|
| react-native-screens                   |3.13.1|
| react-native-safe-area-context         |3.3.2|
| react-native-gesture-handler           |2.4.2|
| react-native-reanimated                |3.0.0-rc.0|

**Comment by wem2017** [comment]
I face same issue 0.69.0-rc.6 & "react-native-screens": "3.13.1", No template named 'optional' in namespace 'std'; did you mean 'folly::Optional'?

**Comment by bahmandamia6982** [comment]
Same issue on android
`React Native 0.69.0-rc.6`
I already used `.\gradlew clean`

```
> Task :app:checkDebugAarMetadata FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
11 actionable tasks: 2 executed, 9 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform appcompat-1.4.1.aar (androidx.appcompat:appcompat:1.4.1) to match attributes {artifactType=android-aar-metadata, org.gradle.status=release}.
      > Could not find appcompat-1.4.1.aar (androidx.appcompat:appcompat:1.4.1).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.4.1/appcompat-1.4.1.aar
   > Failed to transform fragment-1.3.6.aar (androidx.fragment:fragment:1.3.6) to match attributes {artifactType=android-aar-metadata, org.gradle.status=release}.
      > Could not find fragment-1.3.6.aar (androidx.fragment:fragment:1.3.6).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.3.6/fragment-1.3.6.aar
   > Failed to transform fragment-1.3.6.aar (androidx.fragment:fragment:1.3.6) to match attributes {artifactType=android-aar-metadata, org.gradle.status=release}.
      > Could not find fragment-1.3.6.aar (androidx.fragment:fragment:1.3.6).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.3.6/fragment-1.3.6.aar
   > Failed to transform lifecycle-runtime-2.4.0.aar (androidx.lifecycle:lifecycle-runtime:2.4.0) to match attributes {artifactType=android-aar-metadata, org.gradle.status=release}.
      > Could not find lifecycle-runtime-2.4.0.aar (androidx.lifecycle:lifecycle-runtime:2.4.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-runtime/2.4.0/lifecycle-runtime-2.4.0.aar
```

**Comment by kyle-ssg** [comment]
Does anyone know a workaround for now? Keen to try out fabric on a project!

**Comment by bahmandamia6982** [comment]
> Same issue on android (without Fabric) `React Native 0.69.0-rc.6` I already used `.\gradlew clean`
> 
> ```
> > Task :app:checkDebugAarMetadata FAILED
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.g-RC-adle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
> 11 actionable tasks: 2 executed, 9 up-to-date
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:checkDebugAarMetadata'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
>    > Failed to transform appcompat-1.4.1.aar (androidx.appcompat:appcompat:1.4.1) to match attributes {artifactType=android-aar-metadata, org.gradle.status=release}.
>       > Could not find appcompat-1.4.1.aar (androidx.appcompat:appcompat:1.4.1).
>         Searched in the following locations:
>             https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.4.1/appcompat-1.4.1.aar
>    > Failed to transform fragment-1.3.6.aar (androidx.fragment:fragment:1.3.6) to match attributes {artifactType=android-aar-metadata, org.gradle.status=release}.
>       > Could not find fragment-1.3.6.aar (androidx.fragment:fragment:1.3.6).
>         Searched in the following locations:
>             https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.3.6/fragment-1.3.6.aar
>    > Failed to transform fragment-1.3.6.aar (androidx.fragment:fragment:1.3.6) to match attributes {artifactType=android-aar-metadata, org.gradle.status=release}.
>       > Could not find fragment-1.3.6.aar (androidx.fragment:fragment:1.3.6).
>         Searched in the following locations:
>             https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.3.6/fragment-1.3.6.aar
>    > Failed to transform lifecycle-runtime-2.4.0.aar (androidx.lifecycle:lifecycle-runtime:2.4.0) to match attributes {artifactType=android-aar-metadata, org.gradle.status=release}.
>       > Could not find lifecycle-runtime-2.4.0.aar (androidx.lifecycle:lifecycle-runtime:2.4.0).
>         Searched in the following locations:
>             https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-runtime/2.4.0/lifecycle-runtime-2.4.0.aar
> ```

Hi Guys and @Software-Mansion great team
I've updated `./node_modules/react-native-screens/android/build.gradle` android dependencies manually and my app worked successfully on RN 0.69.0.RC-6, but, hey, I know its not right way 😊

* i haven't tested ios app yet.

---
Here is changes:
````gradle
implementation 'androidx.appcompat:appcompat:1.6.0-alpha04' // -> Latest Version
implementation 'androidx.fragment:fragment:1.5.0-rc01' //  -> Latest Version
implementation 'androidx.coordinatorlayout:coordinatorlayout:1.1.0' // -> Latest Version
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0'
implementation 'com.google.android.material:material:1.1.0'
implementation "androidx.core:core-ktx:1.5.0"
````
---

Before:
```gradle
implementation 'androidx.appcompat:appcompat:1.1.0'
implementation 'androidx.fragment:fragment:1.2.1'
implementation 'androidx.coordinatorlayout:coordinatorlayout:1.1.0'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0'
implementation 'com.google.android.material:material:1.1.0'
implementation "androidx.core:core-ktx:1.5.0"
```

**Comment by kyle-ssg** [comment]
Awesome, thanks for sharing ❤️! I've tried to get around iOS avoiding the std::optional types but it's followed by a rabbithole of RCTSurface errors so looks like maybe a fair bit of changes required.

**Comment by baveku** [comment]
> ## Description
> Xcode build is failing with `No template named 'optional' in namespace 'std'; did you mean 'folly::Optional'?`
> 
> ### Screenshots
> <img alt="Screen Shot 2022-06-09 at 9 54 56 AM" width="896" src="https://user-images.githubusercontent.com/6955822/172865028-942660d7-e43c-461e-8bd6-f14ca9152111.png">
> 
> ## Steps To Reproduce
> 1.`USE_FABRIC=1 RCT_NEW_ARCH_ENABLED=1 pod install` 2. Build with Xcode.
> 
> ### Expected behavior
> Succeeds to build.
> 
> ### Actual behavior
> Fails to build.
> 
> ## Reproduction
> ## Platform
> * [x]  iOS
> * [ ]  Android
> * [ ]  Web
> * [ ]  Windows
> * [ ]  tvOS
> 
> ## Workflow
> * [ ]  Managed workflow
> * [x]  Bare workflow
> 
> ## Package versions
> package	version
> react-native	0.69.0-rc.6
> @react-navigation/native	6.0.10
> @react-navigation/native-stack	6.6.2
> react-native-screens	3.13.1
> react-native-safe-area-context	3.3.2
> react-native-gesture-handler	2.4.2
> react-native-reanimated	3.0.0-rc.0

Because Fabric uses C++17, and we still use C++11,

**Comment by kkafar** [comment]
Hi @maxperry!
We've just released version 3.14. Could you try to upgrade and let us know whether it works for you now?

**Comment by maxperry** [comment]
That's great @kkafar! I'll try to get back to you tomorrow.

**Comment by kkafar** [comment]
Feel free to reopen if the problem still occurs.
