### ISSUE TITLE
CI issues when I comment in this repo

### ISSUE THREAD

**Issue by hirbod** [software-mansion/react-native-screens#1475]
Hi, 

whenever I comment on something here, I receive an email like this:
<img width="1027" alt="Bildschirmfoto 2022-06-12 um 13 26 25" src="https://user-images.githubusercontent.com/504909/173230908-25b70bd1-646e-4a4b-928d-2798ceefa350.png">

I think some configuration is not correct.

**Comment by kkafar** [comment]
Would you mind sharing your configuration from your github profile: `Settings -> Notifications` 

Below you can find mine: 

![image](https://user-images.githubusercontent.com/50801299/181223537-1b7501e8-61b7-4015-aa0a-0454136defc0.png)


If we can't resolve this issue with profile configuration I'll dive into our bot code.
