### ISSUE TITLE
IOS, Screens under modal screen can swipe back but modal still exist.

### ISSUE THREAD

**Issue by NguyenHoangMinhkkkk** [software-mansion/react-native-screens#1476]
### Description
Screens under modal screen can swipe back but modal still exist.

https://user-images.githubusercontent.com/30792140/167989124-290bfe60-fc29-470e-a86d-577bc92d6972.mov

### Expected behavior
While modal screen exist, screens behide can not wipe back.

### Steps To Reproduce
- clone project in Reproduction section

- yarn && cd ios && pod install && cd ..
- npx react-native run-ios --simulator="iPhone 13 (15.5)"

### Reproduction
https://github.com/NguyenHoangMinhkkkk/navigation-reproduce
This issue also posted at: https://github.com/react-navigation/react-navigation/issues/10584

### Platform
- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.10
| @react-navigation/native-stack         | ^6.5.0
| react-native-safe-area-context         | ^4.2.1
| react-native-screens                   | ^3.13.1
| react-native-gesture-handler           | ^2.3.2
| react-native-reanimated                | ^1.13.4
| react-native                           | 0.68.0

**Comment by NguyenHoangMinhkkkk** [comment]
Hi, thank you so much for your working.
i tried to upgrade these following packages the newer versions

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  ^6.0.10 -> ^6.0.11
| @react-navigation/native-stack         | ^6.5.0 -> ^6.7.0
| react-native-safe-area-context         |  ^4.2.1 -> ^4.3.1
| react-native-screens                   | ^3.13.1 -> ^3.15.0

see last commit: https://github.com/NguyenHoangMinhkkkk/navigation-reproduce

Then the results seeing at this video. things happen but better than previous versions.

https://user-images.githubusercontent.com/30792140/178184556-fcf5f72a-9952-4ae9-add0-38cace727663.mov

**Comment by kkafar** [comment]
Thank you for reporting! Reopening the issue & will look into this

**Comment by kkafar** [comment]
@NguyenHoangMinhkkkk 
I can reproduce this issue only when using `@react-navigation/native-stack`, when working with `react-native-screens/native-stack` everything seems to be working fine. Would love to hear from you if that is also your case.

**Comment by kkafar** [comment]
So I tracked down the issue to these changes introduced in [this commit to `@react-navigation`](https://github.com/react-navigation/react-navigation/pull/10674). When these changes are reverted, the issue does not occur anymore if using `@react-navigation/native-stack`. 

cc @kacperkapusciak, would you mind taking a look at this?

**Comment by NguyenHoangMinhkkkk** [comment]
Hi there, 
Sorry about the mistake. at https://github.com/software-mansion/react-native-screens/issues/1476#issuecomment-1179934951.

The previous video was showing wrong situation of issue. it should be this video below.
https://user-images.githubusercontent.com/30792140/178884385-092ed14a-ac20-4e87-b348-a662f0909bec.mov

i hope it helps.

**Comment by NguyenHoangMinhkkkk** [comment]
> Hi @NguyenHoangMinhkkkk I assure you, that comment was not wrong :D Thanks to your video we found quite a big bug with integration with `@react-navigation`! Thank you for reporting! It should already be fixed with #1524. You can try it out with setting in you `package.json`:
> 
> ```
> "react-native-screens": "software-mansion/react-native-screens#cc5de7ba28e90ecce9bbb3464ef0a625eaae032f"
> ```
> 
> (current main)
> 
> And answering the second part: For the `gestureResponseDistance` prop to work you need to set `fullScreenSwipeEnabled` to `true`, otherwise this prop does not have any effect. You should be able to swipe back with:
> 
> ```
> gestureEnabled: true
> fullScreenSwipeEnabled: false
> ```
> 
> with gesture starting from the very left edge of the screen.

Thats Fixed. Thank you.

**Comment by adampbf** [comment]
@hirbod I have question related to modal presentation with nativeStackNavigator having this combinations of props:

` gestureEnabled: true,
   gestureDirection: 'vertical',
   fullScreenGestureEnabled: true,
   presentation: 'containedTransparentModal'`

and especially `containedTransparentModal` or `transparentModal` vertical swipe gesture is not working on modals - is it supposed to be fixed or it will be like that?

**Comment by NguyenHoangMinhkkkk** [comment]
> 

hi mate.

i did facing same issue. but dont really know is that the issue realate with RNavigation or RNScreen.

for me, both presentation "containedTransparentModal" using for modal and "default" as normal screen can not swipe without "fullScreenGestureEnabled". even docs said that gestureEnabled was true as default.

**Comment by kenzo23312** [comment]
> > @hirbod I have question related to modal presentation with nativeStackNavigator having this combinations of props:
> > ` gestureEnabled: true, gestureDirection: 'vertical', fullScreenGestureEnabled: true, presentation: 'containedTransparentModal'`
> > and especially `containedTransparentModal` or `transparentModal` vertical swipe gesture is not working on modals - is it supposed to be fixed or it will be like that?
> 
> hi mate.
> 
> i did facing same issue. but dont really know is that the issue realate with RNavigation or RNScreen or wrong impletement myself.
> 
> For me, both presentation "containedTransparentModal" using for modal and "default" as normal screen can not swipe without "fullScreenGestureEnabled". even docs said that gestureEnabled was true as default.

maybe @kkafar or @WoLewicki can help us understanding is that our incorrect implementation or missing some props on libraries?

**Comment by kkafar** [comment]
@kenzo23312, @adampbf 
You should be able to hide modal (with `presentation: 'modal'`) with a vertical gesture. Other modal stack presentations require you to create explicit go-back button (you should not be able to swipe neither with vertical nor horizontal gesture). For now this is intended, however we do not rule out the possibility to modify this behaviour in the future.

**Comment by adampbf** [comment]
@kkafar thanks for reply! 
That's pretty bad as having mode `presentation: 'transparent` you can achieve lots of features from bottom sheets to some gesture controlled panels if there is no technical limitation and only `intended` I don't see points why it shouldn't be introduced as it was in previous stack navigators possible and can break many apps which used this approach like one I'm currently working - this pushes me to use other libraries like bottom-sheet which is even worse buggy / limited / need to use portals while having bottom tabs navigation menu.

**Comment by hirbod** [comment]
I would ask for gesture support on transparentModal. I would actually love to have such thing for android as well, because right now, we have 0 gesture support for android unfortunately (and its getting a "thing" more and more)

**Comment by adampbf** [comment]
@hirbod I would push also to have at least for one transparent type gesture enabled very useful thing :)

**Comment by adampbf** [comment]
@hirbod any updates on this gesture prop for transparent modals ?

**Comment by MichaelDanielTom** [comment]
A slightly separate but related issue: does anyone know how to have a transparent card within a `NativeStackNavigator` that will show the screen underneath it? 

I realize that I could use `presentation: 'transparentModal'`, but then if you try pushing screens onto the stack above that modal, it still has the modal showing, and the screen is pushed underneath in the view hierarchy, even though it is on top in the navigation hierarchy. And using `presentation: 'card'` will prevent the route behind from being rendered.

**Comment by hotaryuzaki** [comment]
How to close the modal if the modal is fullscreen??
Is it intended behavior that modal won't close when slide back??
