### ISSUE TITLE
App freezes when opening from background after upgrading from v3.9.0

### ISSUE THREAD

**Issue by Farzin-Firoozi** [software-mansion/react-native-screens#1478]
## Description
When app is opened from background everything gets stuck and nothing works anymore!

But works well with version 3.9.0.

### Video
https://user-images.githubusercontent.com/52259209/173380081-5ecc9a1f-a831-446f-a055-2599c5ee55ce.mp4

## Steps To Reproduce
0. enableFreeze(true)
1. Navigate to some screen.
2. Lock your phone (in order to go to the background).
3. Unlock your phone.
4. You'll see the result.

### Expected behavior
App should continue to work same as before.

### Actual behavior
App gests stuck and nothing works.

## Platform

- [x] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |     0.67.2    |
| @react-navigation/native               |    ^6.0.2     |
| @react-navigation/native-stack         |    ^6.5.2     |
| react-native-screens                   |     3.13.1    |
| react-native-safe-area-context         |    ^3.3.2     |
| react-native-gesture-handler           |     ^1.10.3    |
| react-native-reanimated                |    ^2.4.1     |
| expo                                   |      N/A   |

**Comment by kkafar** [comment]
Hi @Farzin-Firoozi 
I've just tested this on `react-native-screens@3.15` & everything seems to work just fine after locking & unlocking the phone. 

Until there is no reproduction, I'm afraid we can not do much. 

Make sure to follow [installation instructions](https://github.com/software-mansion/react-native-screens#installation).

**Comment by Farzin-Firoozi** [comment]
Issue was with some `BottomSheet` that was invisible but in the rendering tree.
Removed it and got fixed. 
:)
