### ISSUE TITLE
RN 68.1 android not running

### ISSUE THREAD

**Issue by ergauravgupta** [software-mansion/react-native-screens#1483]
[CXX1405] error when building with ndkBuild using node_modules/react-native-screens/android/src/main/jni/Android.mk: Build command failed.
Error while executing process /Users/mono-hyd-mac-9/Library/Android/sdk/ndk/24.0.8215888/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/node_modules/react-native-screens/android/src/main/jni/Android.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDK_DEBUG=1 NDK_OUT=/node_modules/react-native-screens/android/build/intermediates/cxx/Debug/70547186/obj NDK_LIBS_OUT=/node_modules/react-native-screens/android/build/intermediates/cxx/Debug/70547186/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=android/app/build/generated/source PROJECT_BUILD_DIR=/android/app/build REACT_ANDROID_DIR=/android/../node_modules/react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=/android/../node_modules/react-native/ReactAndroid/build APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: ERROR:/node_modules/react-native-screens/android/src/main/jni/Android.mk:fb: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /android/app/build/react-ndk/exported/x86_64/libfb.so exists  or that its path is correct   

fcntl(): Bad file descriptor
/Library/Android/sdk/ndk/24.0.8215888/build/core/prebuilt-library.mk:51: *** Android NDK: Aborting    .  Stop.

**Comment by rado196** [comment]
same here, has anyone solved this issue?

**Comment by kkafar** [comment]
I can not reproduce this issue w/o any reproduction or insights, but I recall coming across this `CXX1405` during development. If I remember right, `Invalidate caches` in Android studio and optionally `rm -fr node_modules && yarn install && rm -fr ~/.gradle` should help. 

If it does not help, please conform to bot's comments so I can have something to begin with.

**Comment by HarshaR1642** [comment]
has anyone solved this issue ??

**Comment by kkafar** [comment]
[This response](https://github.com/software-mansion/react-native-gesture-handler/issues/1976#issuecomment-1092403958) points toward some local misconfiguration. You might want to check it out.

**Comment by kkafar** [comment]
I'm closing this issue, as: 
1. [this](https://github.com/software-mansion/react-native-screens/issues/1483#issuecomment-1202331462) should resolve your problem
2. it is not strictly related to `react-native-screens`

However feel free to re-open / continue the discussion.

**Comment by robinlehrmann** [comment]
Hello :)
unfortunately I get a similar error but instead of missing `libfb.so` for x86_64 it's missing for x86

The complete error is here:
```
* What went wrong:
Execution failed for task ':react-native-safe-area-context:configureNdkBuildDebug[x86]'.
> [CXX1405] error when building with ndkBuild using /Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native-safe-area-context/android/src/main/jni/Android.mk: Build command failed.
  Error while executing process /Users/robin.lehrmann/Library/Android/sdk/ndk/21.4.7075529/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native-safe-area-context/android/src/main/jni/Android.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 NDK_OUT=/Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native-safe-area-context/android/build/intermediates/cxx/Debug/3s2l4j1r/obj NDK_LIBS_OUT=/Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native-safe-area-context/android/build/intermediates/cxx/Debug/3s2l4j1r/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=/Users/robin.lehrmann/projects/rave-now/app/android/app/build/generated/source PROJECT_BUILD_DIR=/Users/robin.lehrmann/projects/rave-now/app/android/app/build REACT_ANDROID_DIR=/Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=/Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native/ReactAndroid/build APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
  Android NDK: ERROR:/Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native-safe-area-context/android/src/main/jni/Android.mk:fb: LOCAL_SRC_FILES points to a missing file
  Android NDK: Check that /Users/robin.lehrmann/projects/rave-now/app/android/app/build/react-ndk/exported/x86/libfb.so exists  or that its path is correct

  fcntl(): Bad file descriptor
  /Users/robin.lehrmann/Library/Android/sdk/ndk/21.4.7075529/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
```

I thought maybe it's because of the the OS. I use MacOS Monterey which only supports 64 bit 🤔 but arm and the others are working... I already followed the hint from https://github.com/software-mansion/react-native-screens/issues/1483#issuecomment-1202331462 but it does not work. :(

**Comment by mechaadi** [comment]
> Hello :) unfortunately I get a similar error but instead of missing `libfb.so` for x86_64 it's missing for x86
> 
> The complete error is here:
> 
> ```
> * What went wrong:
> Execution failed for task ':react-native-safe-area-context:configureNdkBuildDebug[x86]'.
> > [CXX1405] error when building with ndkBuild using /Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native-safe-area-context/android/src/main/jni/Android.mk: Build command failed.
>   Error while executing process /Users/robin.lehrmann/Library/Android/sdk/ndk/21.4.7075529/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native-safe-area-context/android/src/main/jni/Android.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 NDK_OUT=/Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native-safe-area-context/android/build/intermediates/cxx/Debug/3s2l4j1r/obj NDK_LIBS_OUT=/Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native-safe-area-context/android/build/intermediates/cxx/Debug/3s2l4j1r/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=/Users/robin.lehrmann/projects/rave-now/app/android/app/build/generated/source PROJECT_BUILD_DIR=/Users/robin.lehrmann/projects/rave-now/app/android/app/build REACT_ANDROID_DIR=/Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=/Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native/ReactAndroid/build APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
>   Android NDK: ERROR:/Users/robin.lehrmann/projects/rave-now/app/node_modules/react-native-safe-area-context/android/src/main/jni/Android.mk:fb: LOCAL_SRC_FILES points to a missing file
>   Android NDK: Check that /Users/robin.lehrmann/projects/rave-now/app/android/app/build/react-ndk/exported/x86/libfb.so exists  or that its path is correct
> 
>   fcntl(): Bad file descriptor
>   /Users/robin.lehrmann/Library/Android/sdk/ndk/21.4.7075529/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
> ```
> 
> I thought maybe it's because of the the OS. I use MacOS Monterey which only supports 64 bit 🤔 but arm and the others are working... I already followed the hint from [#1483 (comment)](https://github.com/software-mansion/react-native-screens/issues/1483#issuecomment-1202331462) but it does not work. :(


Same problem here, I am on MacOS Monterey as well


```
> Task :ReactAndroid:hermes-engine:configureCMakeMinSizeRel[x86_64]
C/C++: release|x86_64 :CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
C/C++: release|x86_64 :  The OLD behavior for policy CMP0026 will be removed from a future version
C/C++: release|x86_64 :  of CMake.
C/C++: release|x86_64 :  The cmake-policies(7) manual explains that the OLD behaviors of all
C/C++: release|x86_64 :  policies are deprecated and that a policy should be set to OLD only under
C/C++: release|x86_64 :  specific short-term circumstances.  Projects should be ported to the NEW
C/C++: release|x86_64 :  behavior and not rely on setting a policy to OLD.

> Task :react-native-gesture-handler:configureNdkBuildDebug[arm64-v8a] FAILED
C/C++: fcntl(): Bad file descriptor
C/C++: /Users/mechaadi/Library/Android/sdk/ndk/21.4.7075529/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
```

**Comment by kkafar** [comment]
I believe this is due to some misconfiguration of task dependencies in react native gradle plugin (files are required before they re build). Workaround for now: run the Android build twice **from Android studio**. Gradle Sync && first build will fail, but required files will be build so that following builds should succeed.
