### ISSUE TITLE
Modal in iOS goBack() not working

### ISSUE THREAD

**Issue by dhanushm360** [software-mansion/react-native-screens#1487]
## Description
I have an iOS modal using `stackPresentation: "modal"`, and I wanted to implement a cancel button to dismiss the modal. Is there a value prop to dismiss the modal when pressing a button? When I try to use `navigation.goBack()`, it puts me on a different screen.

## Platform

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [x] Managed workflow
- [ ] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |         |
| @react-navigation/native               |         |
| @react-navigation/native-stack         |         |
| react-native-screens                   |         |
| react-native-safe-area-context         |         |
| react-native-gesture-handler           |         |
| react-native-reanimated                |         |
| expo                                   |         |

**Comment by WoLewicki** [comment]
Why would it put you on a different screen? Could you elaborate more on it?

**Comment by hirbod** [comment]
You most likely have some nested navigators and you're not accessing the correct navigator.
goBack and pop just work fine when you're using the right navigator. Check if you're not relying on some kind of navigation ref service which might have a reference to the underlying navigator. You could try to access the current navigator via props or `useNavigation` hook and try to trigger goBack/pop
