### ISSUE TITLE
version@3.14.0 ios build error: RNSScreenViewEvent.h:2:9: 'React/RCTEventDispatcherProtocol.h' file not found

### ISSUE THREAD

**Issue by cengit** [software-mansion/react-native-screens#1501]
## Description

version@3.14.0 ios build error: 

```sh
❌ /Users/runner/work/1/s/node_modules/react-native-screens/ios/RNSScreenViewEvent.h:2:9: 'React/RCTEventDispatcherProtocol.h' file not found

#import <React/RCTEventDispatcherProtocol.h>

^

▸ Compiling RNSScreenStackHeaderSubview.mm

Skipping duplicate build file in Copy Bundle Resources build phase: /Users/runner/work/1/s/node_modules/performance_frontend/src/font/Montserrat-SemiBold.ttf (in target 'eBriefcase' from project 'eBriefcase')

** ARCHIVE FAILED **

The following build commands failed:

CompileC /Users/runner/Library/Developer/Xcode/DerivedData/eBriefcase-fpyythrpiwdiswbagvblncwborcj/Build/Intermediates.noindex/ArchiveIntermediates/eBriefcase/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/RNScreens.build/Objects-normal/arm64/RNSScreenViewEvent.o /Users/runner/work/1/s/node_modules/react-native-screens/ios/RNSScreenViewEvent.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNScreens' from project 'Pods')

(1 failure)
```

I guess this may be library version not matched, but don't know which library. can you please give some advice.

## Steps To Reproduce

1. use react-native-screens version@3.14.0

## Platform

- [x] iOS

## Architecture

- [x] Paper
- [ ] Fabric

## Workflow

- [x] Managed workflow
- [ ] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |  0.63       |
| @react-navigation/native               |    3.8.4     |
| @react-navigation/native-stack         |  5.0.4       |
| react-native-screens                   |   3.14.0      |
| react-native-safe-area-context         |  3.4.1       |
| react-native-gesture-handler           |  1.10.3       |
| react-native-reanimated                |   1.13.4      |

**Comment by kkafar** [comment]
Hi @cengit!
I dived into it and discovered that `React/RCTEventDispatcherProtocol.h` header before `react-native@0.64.x` had different name: `React/RCTEventDispatcher.h`. This causes incompatibility with `react-native-screens@3.14.0`. Will have it fixed soon.

For now your solutions might be:

* bump `react-native` to at least `0.64.x` (if you have trouble updating, take advantage of [react-native upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.64.3)). 

or

* Downgrade version of `react-native-screens` to `3.13.1`. If you don't use newest react-native versions & don't plan to play with new architecture - Fabric, then `3.13.1` is as good for you as `3.14.0`


Let me know if it worked for you!

**Comment by cengit** [comment]
@kkafar Yes, v3.13.1 works fine. thanks for your response, great!

**Comment by SeanDunford** [comment]
> Hi @cengit! I dived into it and discovered that `React/RCTEventDispatcherProtocol.h` header before `react-native@0.64.x` had different name: `React/RCTEventDispatcher.h`. This causes incompatibility with `react-native-screens@3.14.0`. Will have it fixed soon.
> 
> For now your solutions might be:
> 
> * bump `react-native` to at least `0.64.x` (if you have trouble updating, take advantage of [react-native upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.64.3)).
> 
> or
> 
> * Downgrade version of `react-native-screens` to `3.13.1`. If you don't use newest react-native versions & don't plan to play with new architecture - Fabric, then `3.13.1` is as good for you as `3.14.0`
> 
> Let me know if it worked for you!

Hey @[kkafar](https://github.com/kkafar) I just wanted to confirm that based on the pr being closed here https://github.com/software-mansion/react-native-screens/pull/1502#issuecomment-1188653300 that there will be no fix and the two solutions you presented are the only correct ones moving forward.

**Comment by kkafar** [comment]
@SeanDunford 

For this moment, we are not planning to support versions of React Native lower than 0.64 in future `react-native-screens` releases. 

Upgrading React Native to more recent version seems like the best solution for me, as other library vendors (e.g. Expo) have also dropped support for < 0.64.

**Comment by noumantahir** [comment]
> Hi @cengit! I dived into it and discovered that React/RCTEventDispatcherProtocol.h header before react-native@0.64.x had different name: React/RCTEventDispatcher.h. This causes incompatibility with react-native-screens@3.14.0. Will have it fixed soon.
> 
> For now your solutions might be:
> 
> bump react-native to at least 0.64.x (if you have trouble updating, take advantage of [react-native upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.64.3)).
> or
> 
> Downgrade version of react-native-screens to 3.13.1. If you don't use newest react-native versions & don't plan to play with new architecture - Fabric, then 3.13.1 is as good for you as 3.14.0
> Let me know if it worked for you!

Using hardcoded 3.13.1 version worked well for my case as I am using rn 0.63,   

```
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-screens": "3.13.1",
```

**Comment by NgocLe1001** [comment]
[This](https://github.com/software-mansion/react-native-screens/issues/1501#issuecomment-1172170501) helps me a lot. Thanks so much

I add react-native screen version 3.13.1 and it works
my react native version "react-native": "^0.63.4",
