### ISSUE TITLE
File <react/RCTViewManager.h> not found

### ISSUE THREAD

**Issue by Romick2005** [software-mansion/react-native-screens#1505]
## Description
Apple project build error on apple silicon M1 Mac Mini.
Build fails with rect file header not found exception.
Here is the line that cause the issue:
https://github.com/software-mansion/react-native-screens/commit/568e588817538740dff23a3590748614d4c346e3#r77489524

### Screenshots
![image](https://user-images.githubusercontent.com/17779660/176993806-fd20fafc-9a1d-4455-a2fc-f0b419c751a8.jpeg)

## Steps To Reproduce
Start usual xCode project build

### Expected behavior

#import <**R**eact/RCTViewManager.h>

Build success

### Actual behavior
Build failure

## Reproduction
Start iOS build process

## Platform 
- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Architecture
Arm64
- [ ] Paper
- [x] Fabric

## Workflow
- [x] Managed workflow
- [ ] Bare workflow

## Package versions
| react-native-screens                                | 3.14.0 |
| --------------------------------

**Comment by kkafar** [comment]
Hi @Romick2005,
iOS build on Fabric seems to be working well - also on M1 chip. I'll be happy to help, but I need you to provide repo with reproduction of your issue & package versions you're using, so I can see what causes the problems in your case.

**Comment by Romick2005** [comment]
But can you try if replacing

#import <react/RCTViewManager.h>
to
#import <React/RCTViewManager.h>
would work for you also?

I am not able to provide error screenshots now, but on Monday I will.

**Comment by renchap** [comment]
@Romick2005 Are you using case-sensitive filesystem by any chance?

You can test it in the terminal:
```sh
touch test1.txt
touch Test1.txt
ls test1.txt Test1.txt
```

If you have both `test1.txt` and `Test1.txt` created, then you are on a case-sensitive FS (not the default for macOS) and it would explain the issue.

**Comment by Romick2005** [comment]
I can confirm that my file system case-sensitive. 
I knew that even before, that why I was asking for a fix in the code base.
![image](https://user-images.githubusercontent.com/17779660/177263353-6be32096-10cf-4447-a56b-6eed722d5d63.png)

In order to get build I have changed `#import <react/RCTViewManager.h>` to `#import <React/RCTViewManager.h>`.
But that would be really great if that would work out of the box.
Thank you!

PS. I also had the same issue with `#include <openssl/opensslv.h>` in Flipper-Folly. 
So creating a symlinks OpenSSL.framework -> openssl.framework in ios/Podfile with system-case sensitive check 
```
unless File.exist? "pods" [
  system("cd Pods/OpenSSL-Universal/Frameworks/OpenSSL.xcframework/macos-arm64_arm64e_x86_64 && ln -sfh OpenSSL.framework openssl.framework")
end
] 
```
That also resolves OpenSSL issue.

**Comment by hirbod** [comment]
I made a PR for you
https://github.com/software-mansion/react-native-screens/pull/1517

**Comment by Romick2005** [comment]
Thank you @hirbod!
