### ISSUE TITLE
[bug][ios] 3.14+ breaks all ScrollViews/FlatList when inside a stack with fullScreenGestureEnabled

### ISSUE THREAD

**Issue by hirbod** [software-mansion/react-native-screens#1510]
## Description

Hi @WoLewicki, I hold up to my promise to find every bug in RNS :D

After the update to 3.14.1 it is impossible to scroll in a view (ScrollView, FlatList etc) with `fullScreenGestureEnabled`.

The gesture recognizer takes total control and does not allow scrolling anymore. If you set `fullScreenGestureEnabled: false`, it works.

The problem does not occur with 3.13.1. I suspect the regression comes from https://github.com/software-mansion/react-native-screens/pull/1370

### Screenshots

| 3.13.1 (works)                                |  3.14.1 (broken) |
| -------------------------------------- | ------- |
| <video src="https://user-images.githubusercontent.com/504909/177221531-0e25fcc2-d616-40fb-b0f8-2b2f81ab02a0.mp4" />        |   <video src="https://user-images.githubusercontent.com/504909/177221439-e20ac859-95d2-43c6-86bd-043f1f46fa45.mp4" />    |

## Steps To Reproduce

1. Create a Stack Screen with `fullScreenGestureEnabled`.
2. Add ScrollView inside of it and navigate to it
3. Try to scroll - impossible. The horizontal pop gesture kicks in

### Expected behavior

Should not break scrolling. Also messes around with react-native-gesture-handlers `activeOffsetY`. If set to -20, 20, it does also not work anymore, had to change it to -5, 5.

### Actual behavior

Scrolling impossible with `fullScreenGestureEnabled`
Breaks scrolling

## Reproduction

https://snack.expo.dev/@hirbod/scrollview

Just drop the ScrollView inside a Screen with fullScreenGestureEnabled set too true. Since Snack does not Support 3.14.1, it's not a real repro.

## Platform

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Architecture

- [x] Paper
- [ ] Fabric

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |  0.68.2       |
| @react-navigation/native               |    6.0.10     |
| @react-navigation/native-stack         |      6.6.2   |
| react-native-screens                   |     3.14.1    |
| react-native-safe-area-context         |    4.3.1     |
| react-native-gesture-handler           |  2.4.2       |
| react-native-reanimated                |    2.8.0     |
| expo                                   |    SDK 45 (custom dev client)     |

**Comment by kkafar** [comment]
Quite a bug. Looking into this.

**Comment by hirbod** [comment]
I confirm the issue is fixed after pulling in the PR

**Comment by chazzaoui** [comment]
Thank you for resolving this issue so quickly! @kkafar 
Do you have an idea when we can expect a release with this fix?
