### ISSUE TITLE
Android - Appcompat - 1.1.0 stable version

### ISSUE THREAD

**Issue by alexander-w-o-s** [software-mansion/react-native-screens#154]
Android released [stable version of appcompat 1.1.0](https://developer.android.com/jetpack/androidx/releases/appcompat#1.1.0) on September 5.

Is it safe to use this stable version instead of 1.1.0-rc01?

Maybe it makes sense to update version in README.md

**Comment by kmagiera** [comment]
yes, I guess we can use 1.1.0 now that it is out instead of rc, don't see any issues with updating. WIll welcome a PR that changes it

**Comment by mikehardy** [comment]
It is not safe. If you upgrade to appcompat 1.1.0 you will crash any android Activity that uses a WebView (stated differently, you will crash when you use react-native-webview in a component) on all Android 5 and 5.1, and a healthy percentage of Android 6 and 7 devices. https://issuetracker.google.com/issues/141132133

Discovering this was not fun.

https://github.com/ankidroid/Anki-Android/issues/5507#issuecomment-542359551

Tested workaround: https://github.com/react-native-community/react-native-webview/issues/858#issuecomment-543499396 - I'm able to use 1.1.0 in react-native with this, but...

...on my native project there were reports it affected font size as well. So test thoroughly.

**Comment by WoLewicki** [comment]
v. 1.1.0 is used in the library so I am closing this issue. Feel free to comment if I am wrong.
