### ISSUE TITLE
[Android] Tab Screens use fragment transactions instead of ViewPager

### ISSUE THREAD

**Issue by eamon-mallon** [software-mansion/react-native-screens#1548]
## Description
In Android projects, using the Tab Screens navigation causes fragments to be removed and added every time a user navigates. This causes the fragment to be recreated each time it is navigated to. This can be seen in the gif provided below showing that the document view is recreated each time it is navigated to by the user.

After debugging the project I noticed that [ScreenContainer.kt](https://github.com/software-mansion/react-native-screens/blob/main/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt) in react-native-screens uses fragment transactions and removes the fragment each time a [navigation event is called](https://github.com/software-mansion/react-native-screens/blob/main/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt#L303). Is it possible prevent the fragment from being removed every time we navigate or is there a [view pager](https://developer.android.com/reference/androidx/viewpager/widget/ViewPager) implementation with a [bottom bar navigation](https://medium.com/@hasperong/android-bottomnavigationview-with-viewpager-814577cae36) for Tab Screens ?

### Screenshots
<img src="https://user-images.githubusercontent.com/77021678/181390855-f64acd5b-103f-48c7-823e-a465919b60bc.gif" width="200">

## Steps To Reproduce

1. Open an app using tab screens
2. Navigate between fragments
**Result:** fragments are created each time the user navigates

### Expected behavior
Fragments should not be recreated every time they are navigated to, the navigation should preform like a view pager 

### Actual behavior
Fragments are recreated every time the user navigates

## Reproduction

See STR section, this happens on all projects using Tab Screen
```
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={HomeScreen}/>
        <Tab.Screen name="Document" component={DocumentScreen}/>
      </Tab.Navigator>
    </NavigationContainer>
```

## Platform

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |     0.65.2    |
| @react-navigation/native               |    ^6.0.10     |
| react-native-screens                   |  ^3.13.1       |

**Comment by sgong-pdftron** [comment]
Any update on this issue?

**Comment by kkafar** [comment]
@sgong-pdftron Unfortunately not. The whole idea behind `ScreenContainer` is to use fragment transactions as it allows us to easily integrate with other types of native driven navigators such as native-stack. 

Additionally it is important feature of this library, that at given time only singular  tab is attached to the native view hierarchy.

I'm writing from top of my head right now, but are the fragments still recreated? As far as I remember the fragments are retained and just reattached when navigated back to.

I'm currently unaware of such production-ready solution. I might hint, that we plan to create fully native-bottom-tabs, however this won't happen even this year. 

I'll close this issue, as we do not intent to rewrite the implementation in the way suggested by the author.
