### ISSUE TITLE
Android app crash when stay in background

### ISSUE THREAD

**Issue by adembacajdev** [software-mansion/react-native-screens#1554]
### Description

This is the same issue with [#17 ](https://github.com/software-mansion/react-native-screens/issues/17), and Iknow this issue is explained in README, but with the same solution it is not working in our app

React-Native version: 0.68.2 (FABRIC is disabled)
react-native-screens: 3.15.0

Is anyone else who is experiencing the same issue?

Here is the code from MainActivity.java: 

```
package com.mscmobile;
import android.os.Bundle;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "MSCMobile";
  }

  /**
   * Returns the instance of the {@link ReactActivityDelegate}. There the RootView is created and
   * you can specify the rendered you wish to use (Fabric or the older renderer).
   */
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new MainActivityDelegate(this, getMainComponentName());
  }

  public static class MainActivityDelegate extends ReactActivityDelegate {
    public MainActivityDelegate(ReactActivity activity, String mainComponentName) {
      super(activity, mainComponentName);
    }

    @Override
    protected ReactRootView createRootView() {
      ReactRootView reactRootView = new ReactRootView(getContext());
      // If you opted-in for the New Architecture, we enable the Fabric Renderer.
      reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);
      return reactRootView;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
      super.onCreate(null);
    }
  }
}
```

### Steps to reproduce

1. Create React Native app
2. install react-native-screens with react-navigation and use native stack
3. create a release build
4. launch the app, then leave it in background
5. change device language
6. try to launch app again

### Snack or a link to a repository

https://snack.expo.dev/G61b6n-pq

### Screens version

3.15.0

### React Native version

0.68.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Android emulator

### Device model

all android devices

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hi @adembacajdev,
The first thing worth trying is overriding `MainActivity`'s `onCreate` method and not that of `ReactActivityDelegate`. Would you mind to try it out and let me know whether the problem persists.

**Comment by adembacajdev** [comment]
@kkafar thank you man, I didn't figure it out. super.oncreate was there, just changed savedInstance to null. 

Will close this ticket.
