### ISSUE TITLE
Back button subivew is not yet Fabric compatible in react-native-screens

### ISSUE THREAD

**Issue by endlessl8p** [software-mansion/react-native-screens#1563]
### Description

```
<Stack.Screen
   headerLeft: () => (
     <Button
       onPress={() => navigation.navigate(Screen.Settings)}
       title="Info"
     />
     ),
   })}
/>
```

### Steps to reproduce

1. Add `headerLeft` option to any screen and it will trigger an error in the console.

<img width="564" alt="Screenshot 2022-08-18 at 18 07 29" src="https://user-images.githubusercontent.com/104884878/185520622-d9db3843-9f9b-411d-84fd-681f22a07155.png">

### Snack or a link to a repository

--

### Screens version

3.15.0

### React Native version

0.69.4

### Platforms

iOS

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hi @endlessl8p,
I'm aware of this missing feature, it will be added soon and released most likely with 3.17.0. 
Thank you for reporting.

**Comment by myou11** [comment]
Hello @kkafar, I am running into this issue on `react-native-screens` v3.18.0. Is there an update on when this fix will come out? Thanks!

**Comment by kkafar** [comment]
@myou11,
I remember that I encountered some issues with Fabric view-flattening while I was trying to resolve this issue and moved to other stuff. I won't give you any specifics, but I did not forgot about this issue and will be back on it before 3.19.0.

**Comment by myou11** [comment]
gotcha! thanks for the update, looking forward to 3.19!

**Comment by sushant-sahoo** [comment]
facing same issue.. is there any update on this?

**Comment by dppo** [comment]
"react-native": "0.71.3",
"react-native-screens": "^3.20.0",

use new arch There is still this problem
