### ISSUE TITLE
HeaderLargeTitle not collapsing when using Fabric

### ISSUE THREAD

**Issue by diginikkari** [software-mansion/react-native-screens#1607]
### Description

HeaderLargeTitle is not collapsing to small title when scrolling if app is build with fabric support `bundle install && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`

With Fabric build:
<img width="426" alt="Screenshot 2022-10-04 at 15 01 34" src="https://user-images.githubusercontent.com/2279066/193814296-e73971b7-1258-4cf7-b0f3-1b7e5d10e74b.png">

Without Fabric:
<img width="447" alt="Screenshot 2022-10-04 at 15 19 52" src="https://user-images.githubusercontent.com/2279066/193817530-7c343ebd-e378-4a51-8832-689080bbdc23.png">

### Steps to reproduce

```
git clone https://github.com/diginikkari/FabricRNS
cd FabricRNS
yarn
cd ios
bundle install && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install
yarn ios
```

### Snack or a link to a repository

https://github.com/diginikkari/FabricRNS

### Screens version

3.17.0

### React Native version

0.70.1

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Device

iOS simulator

### Device model

iPhone 14

### Acknowledgements

Yes

**Comment by grahammendick** [comment]
See https://github.com/reactwg/react-native-new-architecture/discussions/43. The fix will land in React Native 0.71. I've tested it works in [my Navigation library](https://grahammendick.github.io/navigation/) but can't guarantee it will fix your problem in react native screens

**Comment by diginikkari** [comment]
Good to know. Let's see when 0.71 comes out if this will be fixed also.

**Comment by kkafar** [comment]
This issue should have been resolved with 

* https://github.com/software-mansion/react-native-screens/pull/1825
