### ISSUE TITLE
attempt child is not RNScreen type with React Navigation v6.0

### ISSUE THREAD

**Issue by 1stblood** [software-mansion/react-native-screens#1608]
### Description

Hi, I have install React Navigation v6 with all dependencies including RNScreen 3.18.0.
Enabling hermes and fabric also. But every time I create stack navigator using createNativeStackNavigator, it thrown an error said attempt child is not RNScreen type. How do I solved it? Thanks in advance

stack = createNativeStackNavigator()
const stackApp = () => {
return(
<StackApp.Navigator>
<StackApp.Screen name="Home" component={HomeScreen} />
</StackApp.Navigator>
)
}

### Steps to reproduce

1. Install React Navigation v6.0 and all dependencies
2. Enable hermes and fabric / NEW_ARCH=1 on grade.properties
3. Create stack navigator

### Snack or a link to a repository
https://gitlab.com/denix182/

import {createNativeStackNavigator} from '@react-navigation/stack';

import LoginScreen from '../../screens/Auth/login';
import RegisterScreen from '../../screens/Auth/register';
import ForgotScreen from '../../screens/Auth/forgot';

import MainScreen from '../../screens/Home/main';
import MainNavigation from '../TabNavigation/BottomNavigation';

const AuthStack = createNativeStackNavigator<AuthStackParams>();
const MainStack = createNativeStackNavigator<MainStackParams>();
const RootStack = createNativeStackNavigator();

type AuthStackParams = {
  Login: undefined;
  Register: undefined;
  ForgotPass: undefined;
};

type MainStackParams = {
  Home: undefined;
};
function AuthStacking({route, navigation}: any) {
  return (
    <AuthStack.Navigator>
      <AuthStack.Screen name="Login" component={LoginScreen} />
      <AuthStack.Screen name="Register" component={RegisterScreen} />
      <AuthStack.Screen name="ForgotPass" component={ForgotScreen} />
    </AuthStack.Navigator>
  );
}

function MainStacking({route, navigation}: any) {
  return (
    <MainStack.Navigator>
      <MainStack.Screen name="Home" component={MainScreen} />
    </MainStack.Navigator>
  );
}

const RootStacking = () => {
  return (
    <RootStack.Navigator>
      <RootStack.Screen
        name="Authentication"
        component={AuthStacking}
        options={{headerShown: false}}
      />
      <RootStack.Screen
        name="MainApp"
        component={MainNavigation}
        options={{headerShown: false}}
      />
    </RootStack.Navigator>
  );
};

export {AuthStacking, MainStacking, RootStacking};

### Screens version

3.18.0

### React Native version

0.70.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Android 12

### Acknowledgements

Yes

**Comment by if-fi** [comment]
I get the same error after upgrading from 3.17.0 to 3.18.0

**Comment by furkanbutdev** [comment]
hi, i am getting this error in version 3.18.0 of react-native-screens. Is there any solution?
React native version: 0.70.2

**Comment by skurgansky-sugarcrm** [comment]
same problem

**Comment by kartikmittal1996** [comment]
Hey, I am also getting same issue with latest react native version with new architecture enabled. Please share the solution asap. I have also tried to add react navigation v6.0 in new project of react native but issue still persists. What should I do? 
![Screenshot_1665426859](https://user-images.githubusercontent.com/113685476/194931528-85286d5d-41b9-45c2-94d2-ada0f3fbb40f.png)

**Comment by skurgansky-sugarcrm** [comment]
> I get the same error after upgrading from 3.17.0 to 3.18.0

3.17.0 same issue for me...

**Comment by krystofwoldrich** [comment]
I have the same issue on our new architecture sample app.

Here is a code for repro.

https://github.com/getsentry/sentry-react-native/tree/4c1a32ee4ff92fa53854883765ce9243d3e4dadf/sample-new-architecture

**Comment by kkafar** [comment]
Ok, looks like I know what is going on. 

Autolinking was added with #1585 and it added `react-native.config.js` file with codegen configuration, **but** I did not add this file to npm include list causing its absence in final released package...

Didn't catch it while testing cause I was using library version directly from `main` in test applications.

I'll release new version with the fix soon.

If you need the fix immediately just copy & paste [this file](https://github.com/software-mansion/react-native-screens/blob/main/react-native.config.js) into your `node_modules/react-native-screens/` directory (preferably use some kind of tool like [`patch-package`](https://www.npmjs.com/package/patch-package))

**Comment by krystofwoldrich** [comment]
Awesome! Thank you for the quick solution. @kkafar

**Comment by kkafar** [comment]
3.18.1 is available for download & should resolve the issue. Let me know (tag me) if something is still wrong).

**Comment by furkanbutdev** [comment]
@kkafar Thank you so much for your update! My app ran successfully

**Comment by shivam7366** [comment]
I am still facing the same issue. while using  react-native-screens-3.20.0

App.js

```
import { StyleSheet, Text, View } from "react-native";
import { StatusBar } from "expo-status-bar";

import MealsOverview from "./screens/MealsOverview";
import { NavigationContainer } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";

const Stack = createNativeStackNavigator();

export default function App() {
  return (
    <>
      <StatusBar style="light" />
      <NavigationContainer>
        <Stack.Navigator>
     
          <Stack.Screen name="MealsOverview" component={MealsOverview} />
        </Stack.Navigator>
      </NavigationContainer>
    </>
  );
}

```
MealsOverview.js
``` 
import { View, Text, StyleSheet } from "react-native";
import React from "react";
import { MEALS } from "../data/dummy-data";

export default function MealsOverview() {
  return (
    <View>
      <Text>MealsOverview</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
  },
});
```

and I am facing the error - attempt attach child that is not of type RNscreens

**Comment by ruslan-moiseyenko** [comment]
The same problem. But with most screens it works fine... would be great to understand the core of the problem...

**Comment by kkafar** [comment]
Hey if the issue still exists I would require a [valid reproduction](https://stackoverflow.com/help/minimal-reproducible-example). Unless it is provided I can't do much (as I can not reproduce the issue).
