### ISSUE TITLE
3.18.1 release and tvOS not working ("RNSScreen" was not found in the UIManager.)

### ISSUE THREAD

**Issue by gorbypark** [software-mansion/react-native-screens#1616]
### Description

Upgrading from react-native-screens 3.18.0 to 3.18.1 produces a `requireNativeComponent: "RNSScreen" was not found in the UIManager.` error.  It's quite odd because the diff between 3.18.0 and 3.18.1 is just adding react-native.config.js..

I ran into the issue creating just a demo project to play around with just the very basics added.  After getting the error, I installed 3.13.0 and started working my way up until it stopped working, and it is an issue with 3.18.1 only it seems.  I tried all the clear-cache tricks and restarting metro + the simulator, but I'm fairly confident it's not a cache issue as switching versions between 3.13->3.18 works and the original version I tried was 3.18.1.

Here's the repo showing the issue, https://github.com/gorbypark/rnscreens-3.18.1

dependencies:
```js
  "dependencies": {
    "@react-native-masked-view/masked-view": "^0.2.8",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/stack": "^6.3.2",
    "react": "17.0.2",
    "react-native": "npm:react-native-tvos@0.68.1-1",
    "react-native-gesture-handler": "^2.7.1",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "3.18.1"
  },
  ```

full error: 
```
 ERROR  Invariant Violation: requireNativeComponent: "RNSScreen" was not found in the UIManager.

This error is located at:
    in RNSScreen (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (at src/index.native.tsx:260)
    in Suspender (at src/index.tsx:40)
    in Suspense (at src/index.tsx:39)
    in Freeze (at src/index.native.tsx:163)
    in DelayedFreeze (at src/index.native.tsx:259)
    in InnerScreen (at src/index.native.tsx:422)
    in Screen (at Screens.tsx:38)
    in MaybeScreen (at CardStack.tsx:655)
    in RNSScreenContainer (at src/index.native.tsx:335)
    in ScreenContainer (at Screens.tsx:20)
    in MaybeScreenContainer (at CardStack.tsx:566)
    in RCTView (at View.js:32)
    in View (at Background.tsx:13)
    in Background (at CardStack.tsx:564)
    in CardStack (at StackView.tsx:437)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:87)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:46)
    in SafeAreaProviderCompat (at StackView.tsx:430)
    in RCTView (at View.js:32)
    in View (at GestureHandlerRootView.tsx:17)
    in GestureHandlerRootView (at StackView.tsx:429)
    in StackView (at createStackNavigator.tsx:121)
    in PreventRemoveProvider (at useNavigationBuilder.tsx:697)
    in NavigationContent (at useComponent.tsx:35)
    in Unknown (at createStackNavigator.tsx:120)
    in StackNavigator (at App.tsx:60)
    in App (at goodmorning/index.js:16)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at goodmorning/index.js:15)
    in Entry (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in goodmorning(RootComponent) (at renderApplication.js:60)
```

### Steps to reproduce

1. upgrade to react-native-screens@3.18.1
2. yarn ios --simulator "Apple TV 4K (2nd generation)" --scheme "yourApp-tvOS"
3. see error

### Snack or a link to a repository

https://github.com/gorbypark/rnscreens-3.18.1

### Screens version

3.18.1

### React Native version

react-native-tvos@0.68.1-1

### Platforms

tvOS

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by kkafar** [comment]
See #1614, closing as duplicate.

I still need to do some more testing before 3.18.2 release, but it is coming within hours.

Also please let me know it this: https://github.com/software-mansion/react-native-screens/issues/1614#issuecomment-1276212091 works for you.
