### ISSUE TITLE
Because  of react-native-screen TextInput.onChangeText called with outdated value

### ISSUE THREAD

**Issue by vrozaev** [software-mansion/react-native-screens#162]
Hello. I find a really strange bug.

Switching between screens lead to additional call of TextInput.onChangeText.

Scenario: Se have 2 screens:
1. Open Screen 1 with TextInput.
2. Redirect to Screen 2.
3. Redirect back to Screen 1 and in the same time change value of TextInput.

Expected behavior: input value should be changed.

Actual behavior: input value is not changed.

Repository with reproduce:
https://github.com/vrozaev/react-native-screens-text-input-bug-reproduce

**Comment by compojoom** [comment]
Thanks for talking the time to create a repository that clearly shows the issue. I've just stumbled on the same thing.
@kmagiera - the example is running alpha 22 and rn59, but this happens on 0.61 with alpha 32 as well.

**Comment by gutenye** [comment]
I had the same problem with `react-native 0.59.5` and `react-native-screens alpha 22`.  
`this.setState({ text })` should not invoke `onChangeText` function.

**Comment by kmagiera** [comment]
Thanks for preparing the repro app, it's been very helpful wit tracking this issue down. Managed to fix it in #313 and will publish it in the next release (likely in a couple of days)

**Comment by kmagiera** [comment]
Closing as the fix has been published on npm already. In case you still experience this problem please comment here or start a new issue.
