### ISSUE TITLE
[Android][Fabric] Release builds crash with "RNSScreenStackHeaderConfig" was not found in the UIManager

### ISSUE THREAD

**Issue by Almouro** [software-mansion/react-native-screens#1620]
### Description

Hello!

Since you've been awesome and far ahead of the competition in terms of new arch support ❤️, I wanted to include `react-native-screens` in some performance benchmarks I'm running.

However I'm getting some issues. The app crashes at startup with any basic example with `Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager.` on my lower end Android devices.

Very similar to https://github.com/software-mansion/react-native-screens/issues/1614, however since this one is on the new arch and only for release builds, I created a new issue. Happy to close it and just copy my comment over to that issue if needed.

Here's where it gets really fun:
- only happen on release builds
- only happen on my lower end devices (not sure because of architecture or because of slowness)
  - ❌ crashes on Samsung J3 2017 Android 9.0 with `armeabi-v7a`
  - ❌ crashes on Samsung A10s Android 10.0 with `armeabi-v7a`
  - ✅ no issue on Samsung S10 Android 12.0 with `arm64-v8a`
- seems there's a race condition happening based on this:

Easiest way to reproduce is 

This code crashes ❌
```js
import * as React from 'react';
import {createNativeStackNavigator} from '@react-navigation/native-stack';

createNativeStackNavigator();

const App = () => {
  return null;
};

export default App;
```

However if we force the import of `react-native-screens` to be done on the fly, this succeeds ✅
```js
import * as React from 'react';

const App = () => {
  require('@react-navigation/native-stack').createNativeStackNavigator();
  return null;
};

export default App;
```

### Full logs

Collapsed the logs into external links to help for readability of this issue:
- [App crashing](https://gist.github.com/Almouro/afc66f86a6cce22652f31fe4ade3ab7e#file-crashing-txt)
- [App not crashing](https://gist.github.com/Almouro/afc66f86a6cce22652f31fe4ade3ab7e#file-fixed-txt)

### Steps to reproduce

1. `npx react-native@latest init NavigationBugRepro` ([1st commit](https://github.com/Almouro/NavigationBugRepro/commit/1fe613008f83bd11cf1846fdbeb5748ca303c03f))
2. Follow https://reactnavigation.org/docs/getting-started and https://reactnavigation.org/docs/hello-react-navigation for install ([2nd commit](https://github.com/Almouro/NavigationBugRepro/commit/1fe613008f83bd11cf1846fdbeb5748ca303c03f))
3. Enable the new arch ([3rd commit](https://github.com/Almouro/NavigationBugRepro/commit/1fe613008f83bd11cf1846fdbeb5748ca303c03f))
4. Add basic navigation based on [the docs hello world](https://reactnavigation.org/docs/hello-react-navigation) ([4th commit](https://github.com/Almouro/NavigationBugRepro/commit/f90c46deea2055b54ca781c5107b1b71ca8d25fb)
5. Build release app -> `cd android && ./gradlew assembleRelease`

This crashes the app with logs mentioned previously.

However, if we require navigation on the fly [like in this commit](https://github.com/Almouro/NavigationBugRepro/commit/b119cf1b20fda010badd15d6261a7ec56f7d25e1), we have no issue. 
(I've also attached both APKs if you want to test them out)

### Snack or a link to a repository

https://github.com/Almouro/NavigationBugRepro

### Screens version

3.18.2

### React Native version

0.70.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Samsung J3 2017 Android 9.0

### Acknowledgements

Yes

**Comment by SanjanaTailor** [comment]
@kkafar  - https://github.com/software-mansion/react-native-screens/issues/1614#issuecomment-1276212091 

This will resolve in release build as well or do we have to wait for the patch in mainline branch please suggest ?
@Almouro  - please try this as well it may helpful. 
I was facing similar issues and thank god it worked and added comment for same.

**Comment by kkafar** [comment]
Sorry to come here after such long time still w/o proper solution, but we moved few react-native & react-native-screens versions forward & I'm must ask whether this is still an issue or was it resolved?
