### ISSUE TITLE
Error with UIViewControllerBasedStatusBarAppearance

### ISSUE THREAD

**Issue by iamvucms** [software-mansion/react-native-screens#1625]
### Description

<img width="231" alt="image" src="https://user-images.githubusercontent.com/17398401/198215923-c6c4bd18-b352-4fb5-95fd-e714d8a99a8f.png">

### Steps to reproduce

Generate new project 0.69.3 and install latest react-native-screens.

### Snack or a link to a repository

None

### Screens version

3.18.2

### React Native version

0.69.3

### Platforms

iOS

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hi @iamvucms,

to resolve this issue you should first try out instructions from error message.

You should add 

```xml
<key>UIViewControllerBasedStatusBarAppearance</key>
<true/>
```
to your application `Info.plist` file.

You can see it done [here](https://github.com/software-mansion/react-native-screens/blob/100ed4f9ffd5f27ace4ddbb5c5ffbb80e7a00c64/Example/ios/ScreensExample/Info.plist#L39-L40)

Let me know if it worked!

**Comment by kkafar** [comment]
I'll actually close this issue. Notify me (by tagging) in case the issue was not resolved by my suggestion.

**Comment by vanhai989** [comment]
> I'll actually close this issue. Notify me (by tagging) in case the issue was not resolved by my suggestion.

It still error in react native 0.70.13 when I use 
import { createNativeStackNavigator } from 'react-native-screens/native-stack';
if I don't use this line the error will be gone

**Comment by vanhai989** [comment]
it doesn't occur in react-native-screens v2.18.1, when I update to rn-screens v3.29.0 the error will appeared
