### ISSUE TITLE
Showing refresh icon on the top of the screen having onRefresh in the flatlist while navigating back - Android Only.

### ISSUE THREAD

**Issue by rifad4u** [software-mansion/react-native-screens#1626]
### Description

Showing a white refresh icon on the top of the screen while navigating back from a screen having refresh control or refresh props in the flatlist. This issue is occuring in the android devices only and not occuring in the android OS 8.

This issue won’t come if i refresh the screen at-least once when mounted and issue won’t come if i comment the refresh control or the refresh props.

I'm attaching the snack link below .

### Steps to reproduce

Go to the snack link and run the code with android device and make sure the OS is 10 or above.

### Snack or a link to a repository

https://snack.expo.dev/C8tAWFbdE

### Screens version

3.18.2

### React Native version

0.70.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Acknowledgements

Yes

**Comment by PedroBern** [comment]
[workaround](https://github.com/facebook/react-native/issues/34718#issuecomment-1295919690)

**Comment by itsramiel** [comment]
experiencing this issue

**Comment by devoren** [comment]
same issue

**Comment by rifad4u** [comment]
Why it is still open?

**Comment by alduzy** [comment]
I can confirm that the problem no longer occurs.
<table>
<td>

```
"react-native-screens": "3.18.2"
```

</td>
<td>

```
"react-native-screens": "3.33.0"
```

</td>
</tr>
<tr>
<td>

https://github.com/user-attachments/assets/8a9088f6-cf4a-4de6-8772-75f26d2ae64f

</td>
<td>

https://github.com/user-attachments/assets/747990c0-89c3-47a6-aabe-5c91cc6b0c8a

</td>
</tr>
</table>
