### ISSUE TITLE
iOS modal height jumps when releasing swipe on page sheet

### ISSUE THREAD

**Issue by meyer9** [software-mansion/react-native-screens#1634]
### Description

The iOS page sheet presentation jumps when releasing page sheet. This is reproducible in the `Examples` project in the repo as well.

https://user-images.githubusercontent.com/1247379/201390954-ea41e6a1-4ae0-4520-96fc-f8fa56bb36f5.mp4

(see bottom of screen)

### Steps to reproduce

1. Swipe up on page sheet modal
2. See that the height of the container improperly jumps.

### Snack or a link to a repository

https://snack.expo.dev/@meyer9/native-modal-reproduction-case?platform=ios

### Screens version

3.18.2

### React Native version

0.63.2

### Platforms

iOS

### Acknowledgements

Yes

**Comment by meyer9** [comment]
The react-navigation issue is here, but I think the issue should be filed on this repo.

https://github.com/react-navigation/react-navigation/issues/10900

**Comment by denissdubinin** [comment]
Have the same issue.

**Comment by ferrannp** [comment]
I think this is also fixed by https://github.com/software-mansion/react-native-screens/pull/1767.
