### ISSUE TITLE
White flash on tab change with @react-navigation/bottom-tabs

### ISSUE THREAD

**Issue by gkueny** [software-mansion/react-native-screens#1645]
### Description

When I'm using `@react-navigation/bottom-tabs` with the native stack navigator, I see a white flash on tab transition in **IOS**.

If I replace `@react-navigation/native-stack` by `@react-navigation/stack`, white flash disappear.

I think it can be related to https://github.com/software-mansion/react-native-screens/issues/1276 but I'm not sure we talk about the same issue.

https://user-images.githubusercontent.com/10655690/203101057-2af9f31c-674b-47eb-9dba-dded56bb9753.mp4

### Steps to reproduce

1. Get Minimal reproduction repo https://github.com/gkueny/native-stack-flash-issue-reproduction
2. Install dependencies
3. Run APP
4. Navigate between tab screen

### Snack or a link to a repository

https://github.com/gkueny/native-stack-flash-issue-reproduction

### Screens version

3.20.0 & 3.29.0

### React Native version

0.69.7 & 0.73.6

### Platforms

iOS

### Workflow

React Native (without Expo)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by gkueny** [comment]
Hi @kkafar ,

I can confirm that I reproduce the issue in iOS 15.5 (simulator)

**Comment by kkafar** [comment]
Thank you, I'll look into this

**Comment by techgerm** [comment]
We're experiencing the same issue. Any update?

**Comment by gkueny** [comment]
@techgerm not on my end. I update the minimal reproduction repo with latest version of `@react-navigation/*` & `react-native-screens` but with no luck

**Comment by cam-shaw** [comment]
I get this issue as well. Wonder if it's related to this conversation where "flickering" is discussed? https://github.com/react-navigation/react-navigation/issues/11285

**Comment by Sumit2202** [comment]
Facing this same issue

**Comment by Sumit2202** [comment]
@kkafar has there been any moment on this issue so far?

**Comment by Lakston** [comment]
Curious about this also, same setup, ios, botom navigator and latest version of native screens

**Comment by gkueny** [comment]
I updated minimal reproduction with latest version of each lib & latest version of react-native : https://github.com/gkueny/native-stack-flash-issue-reproduction/commit/46045f1671d122943b78c0fc9badd71e4a69a888

Issue is still present

**Comment by alduzy** [comment]
I can confirm the issue is reproducible on Paper architecture, Fabric works fine.
