### ISSUE TITLE
presentation="modal" not working on android

### ISSUE THREAD

**Issue by Kotpes** [software-mansion/react-native-screens#1650]
### Description

Having set `presentation="modal"` for a screen has no effect on that screen on Android (still opens full screen view)
```js
<Stack.Screen name="ComponentName" component={Component} options={() => ({
        presentation: 'modal'
})} />
```
Works as expected on iOS.

### Steps to reproduce

1. Add `presentation="modal"` to a screen `options`
2. See that it has no effect on android (still opens the full screen view) - see the snack attached 

### Snack or a link to a repository

https://snack.expo.dev/gg56CATOS

### Screens version

6.6.1

### React Native version

0.69.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Acknowledgements

Yes

**Comment by lokeshdangi** [comment]
was facing the same issue. 
seems like native-stack has some issue with "modal" but 'containedTransparentModal'  was working.
"modal" works fine if we switch to a normal stack navigator

**Comment by jaredly** [comment]
Yeah it looks like it's just not implemented? 🤔 weird that the documentation says 
> `modal`, `containedModal`, `fullScreenModal`, `formSheet` will use `Screen.StackPresentation.MODAL`.

when `MODAL` is essentially ignored in the android code.
```
react-native-screens on main ➜ rg MODAL android
android/src/main/java/com/swmansion/rnscreens/Screen.kt
240:        PUSH, MODAL, TRANSPARENT_MODAL

android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt
58:                Screen.StackPresentation.MODAL
60:                Screen.StackPresentation.TRANSPARENT_MODAL

android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt
90:        var visibleBottom: ScreenStackFragment? = null // this is only set if newTop has TRANSPARENT_MODAL presentation mode
328:            fragment.screen.stackPresentation === Screen.StackPresentation.TRANSPARENT_MODAL
```

Given that `Screen`'s are backed by [androidx `Fragment`s](https://github.com/software-mansion/react-native-screens/blob/5682daffff5baaf943cec79ffe1913215653893b/android/src/main/java/com/swmansion/rnscreens/ScreenFragment.kt#L28), I expect the fix will be to have `modal` screens inherit from [DialogFragment](https://developer.android.com/reference/androidx/fragment/app/DialogFragment).

**Comment by muteshi** [comment]
Also facing the same issue. Do we have a work around for this for android?

**Comment by jsvelte** [comment]
I'm facing the same issue. It's not working in android 💯

**Comment by mustafaDabah** [comment]
Is there anyone solved this issue ??

**Comment by PranavRanjithKumar** [comment]
Yes it is not working. Can anyone suggest a workaround?

**Comment by kkafar** [comment]
Hi, sorry for late response!

There is likely no workaround, because as @jaredly reported, indeed Android modal view are effectively not implemented. I recently started looking into it while attempting to implement bottom-sheets for Android -- and unfortunately there are some technical reasons why it is the case and Android modals were left behind. It looks that documentation is indeed misleading, sorry! Once I'll open PR with support for modals & I'll try to remember to link it here so you can track progress.

**Comment by 0xQuokka** [comment]
hey, @kkafar did you find the solution 😛 ?

**Comment by iraybi** [comment]
Any solution yet?

**Comment by titicarabina** [comment]
anything on this?

**Comment by GanongLS** [comment]
let's change to use flutter.

**Comment by atultiwaree** [comment]
I think we should try to use animation API provided by Stack as an alternative to it

**Comment by nitesh-kumar-gupta** [comment]
use
import {createStackNavigator} from "@react-navigation/stack";
instead of 
import {createNativeStackNavigator} from "@react-navigation/native-stack";
working for both Android and IOS

**Comment by rojingharooni** [comment]
after upgrading to react navigation V6 this code worked for me:



```
<Stack.Group screenOptions={{ presentation: 'modal' }}>

    <Stack.Screen name="ComponentName" component={Component} options={() => ({
            presentation: 'modal'
    })} />

</Stack.Group>

```

**Comment by malek0x1** [comment]
> options={() => ({
>             presentation: 'modal'
>     })}

please send the exact version for react navigation. like "6.5.2"

**Comment by izyspania** [comment]
Any update on this?

**Comment by MahbubMorshed** [comment]
working perfectly

**Comment by gaufranc** [comment]
Still not working

**Comment by DarlonHenrique** [comment]
day 28 of september, Expo Router V2 and SDK 49, and still not working on android

**Comment by atultiwaree** [comment]
It's been a so long, Tag "Zuck" now. 😬

**Comment by sergiosrtd** [comment]
still not working

**Comment by Minkeun-Yun** [comment]
add the below in screenOptions
 : animation:"slide_from_bottom"

**Comment by Paulods0** [comment]
I want to make the previous screen appear a little bit in the current screen

**Comment by izyspania** [comment]
> I want to make the previous screen appear a little bit in the current screen

I want the same  but i dont think is intended to work that way on android from what ive seen.

**Comment by JulioMacedo0** [comment]
I'm using ```"expo": "~49.0.13"```, and I'm facing the same issue on Android. The Expo documentation has examples saying it should work, but I can't get it to work."

**Comment by radhey007** [comment]
I have tried tons of things and still its not working on android

**Comment by jsvelte** [comment]
Let's be honest I've been receiving emails through it everytime. This will not gonna fix the issue. Please close it!

**Comment by valdydev** [comment]
<Stack.Group  screenOptions={{ presentation: 'modal',animation:"slide_from_bottom" }}>
            <Stack.Screen name="Shopp" component={Panier} 
                 options={{
                    title: ' Shopp',
                    presentation: 'modal',
              }}
            />
    </Stack.Group>

**Comment by valdydev** [comment]
> Let's be honest I've been receiving emails through it everytime. This will not gonna fix the issue. Please close it!

<Stack.Group screenOptions={{ presentation: 'modal',animation:"slide_from_bottom" }}>
<Stack.Screen name="Shopp" component={Panier}
options={{
title: ' Shopp',
presentation: 'modal',
}}
/>
</Stack.Group>

**Comment by mshaheerz** [comment]
finally this is worked
`import { TransitionPresets } from '@react-navigation/stack';

// ...

<Stack.Screen
  name="Profile"
  component={Profile}
  options={{
    title: 'Profile',
    ...TransitionPresets.ModalSlideFromBottomIOS,
  }}
/>`

### The currently available transitions are:

- SlideFromRightIOS 
- ModalSlideFromBottomIOS 
- ModalPresentationIOS 
- FadeFromBottomAndroid 
- RevealFromBottomAndroid 
- ScaleFromCenterAndroid 
- DefaultTransition 
- ModalTransition


> All of these are the standard transitions provided by iOS and Android

**Comment by matis-dk** [comment]
> finally this is worked
> 
> `import { TransitionPresets } from '@react-navigation/stack';
> 
> <Stack.Screen name="Profile" component={Profile} options={{ title: 'Profile', ...TransitionPresets.ModalSlideFromBottomIOS, }} />;`
> 
> ### The currently available transitions are:
> * SlideFromRightIOS
> * ModalSlideFromBottomIOS
> * ModalPresentationIOS
> * FadeFromBottomAndroid
> * RevealFromBottomAndroid
> * ScaleFromCenterAndroid
> * DefaultTransition
> * ModalTransition
> 
> > All of these are the standard transitions provided by iOS and Android

This is using the javascript look-alike implementation (`@react-navigation/stack`), and not the native implementation from `@react-navigation/native-stack`

**Comment by wolak** [comment]
Still an issue with  "expo": "~49.0.15", "expo-router": "^2.0.0"
First time trying Expo, lots of cool features but been flaky for certain features

**Comment by mubarakshow** [comment]
> I want to make the previous screen appear a little bit in the current screen

Same here.

**Comment by mubarakshow** [comment]
> I want to make the previous screen appear a little bit in the current screen

Use 
```
{
   presentation: "transparentModal"
}
```

**Comment by rafael-mingossi** [comment]
> ModalSlideFromBottomIOS worked but the screen still show in fullscreen, any solution?

Mine is working well not covering full screen. I am using createStackNavigator (non native) and screenOptions={{presentation: 'modal'}} I created a separated group for modal presentations by using <"StackName".Group screenOptions={{presentation: 'modal'}}>, hope that works

**Comment by rafael-mingossi** [comment]
> > Mine is working well not covering full screen. I am using createStackNavigator (non native) and screenOptions={{presentation: 'modal'}} I created a separated group for modal presentations by using <"StackName".Group screenOptions={{presentation: 'modal'}}>, hope that works
> 
> thanks, but I native-stack is better performance, so I dont want to use non-native

Yeah, your are right, but with Native unfortunately it won't work, I hope they fix that.

**Comment by eidan66** [comment]
Any update on this problem? :(
react-navigation/stack didn't work also.

**Comment by wujekbizon** [comment]
so with `"expo": "~50.0.5",` and `"expo-router": "~3.4.6",` it's still not working , shame because docs saying differently

**Comment by ExarchDB** [comment]
Well over a year and still what most would call a key facility is non functional. What, do they all use iphones or what?

**Comment by vikrant699** [comment]
I am having the same issue, my app heavily relies on modal to work correctly. Is there any kind of communication regarding this being in the pipeline to be fixed?

**Comment by ser-emejia** [comment]
My workaround using expo:
```

import Constants from 'expo-constants';

    <View
      style={{
        flex: 1,
        paddingTop: IS_ANDROID ? Constants.statusBarHeight : 0,
      }}>
      
      //...

    </View>
```

**Comment by qaezrun** [comment]
any updates?

**Comment by Khalidzo** [comment]
Please this info should be included in expo docs, since this is causing confusion for many of us.

**Comment by jonanpogi** [comment]
presentation=modal is still not working for bot ios and android

**Comment by suryanshsingh2001** [comment]
> presentation=modal is still not working for bot ios and android

Same

**Comment by eric-everbright** [comment]
looks like a few things could happen here for a way forward:
1. issue gets fixed (looking unlikely)
2. update docs
3. some kind of console warning if used on android

**Comment by suryanshsingh2001** [comment]
> looks like a few things could happen here for a way forward:
> 
> 1. issue gets fixed (looking unlikely on a timeframe suitable for any of us with in-progress projects)
> 2. update docs
> 3. some kind of console warning if used on android
>    ===
>    as for my project, just living with the push navigation for now, unfortunately, and had to figure out a hack to hide the bottom navigation bar, because the purpose of the modal presentation was so that the presented flow was apart from the root navigation

You are absolutely right !. I am thinking using this instead
[react-native-bottom-sheet](https://ui.gorhom.dev/components/bottom-sheet/)

**Comment by ArtyEmsee** [comment]
> > looks like a few things could happen here for a way forward:
> > 
> > 1. issue gets fixed (looking unlikely on a timeframe suitable for any of us with in-progress projects)
> > 2. update docs
> > 3. # some kind of console warning if used on android
> >    as for my project, just living with the push navigation for now, unfortunately, and had to figure out a hack to hide the bottom navigation bar, because the purpose of the modal presentation was so that the presented flow was apart from the root navigation
> 
> You are absolutely right !. I am thinking of using this instead [react-native-bottom-sheet](https://ui.gorhom.dev/components/bottom-sheet/)

With the plan being to host the sheets inside of your routes?

**Comment by suryanshsingh2001** [comment]
> > > looks like a few things could happen here for a way forward:
> > > 
> > > 1. issue gets fixed (looking unlikely on a timeframe suitable for any of us with in-progress projects)
> > > 2. update docs
> > > 3. # some kind of console warning if used on android
> > >    as for my project, just living with the push navigation for now, unfortunately, and had to figure out a hack to hide the bottom navigation bar, because the purpose of the modal presentation was so that the presented flow was apart from the root navigation
> > 
> > 
> > You are absolutely right !. I am thinking of using this instead [react-native-bottom-sheet](https://ui.gorhom.dev/components/bottom-sheet/)
> 
> With the plan being to host the sheets inside of your routes?

No, just using them like a model.

**Comment by suryanshsingh2001** [comment]
Hey, I adjust found a temporary workaround for this for android, if you want modal to be a bit of away from screen like IOS version, just add these screen options and you are good to go.

```js
 <Stack.Group screenOptions={({navigation}) => ({
          ...TransitionPresets.ModalSlideFromBottomIOS,
          gestureEnabled: true,
          presentation: "modal",
          cardStyle: {marginTop: 10, borderTopStartRadius: 20, borderTopEndRadius: 20}

        })}>
```

**Comment by AnkushSarkar10** [comment]
damn

**Comment by m-emre-yalcin** [comment]
i wish the modal screen supported on android

**Comment by haveatalkapp** [comment]
came here with no hope 😞

**Comment by T30-H0** [comment]
they all use iPhones only 😥 .

**Comment by kkafar** [comment]
Hey hey: you can track this PR: https://github.com/software-mansion/react-native-screens/pull/2045 for progress in the matter. It's finally entering review process.

**Comment by atultiwaree** [comment]
> Hey hey: you can track this PR: https://github.com/software-mansion/react-native-screens/pull/2045 for progress in the matter. It's finally entering review process.

Finally 😅

**Comment by suryanshsingh2001** [comment]
> Hey hey: you can track this PR: #2045 for progress in the matter. It's finally entering review process.

Nice.

**Comment by 00ricardo** [comment]
> Hey hey: you can track this PR: https://github.com/software-mansion/react-native-screens/pull/2045 for progress in the matter. It's finally entering review process.

Excelent news, I think that I spoke for everyone when I say that we're looking forward to hear the outcome of this PR. Thanks a lor for your support 💪

**Comment by YosefOberlander** [comment]
This works on android.         
`presentation: 'modal', gestureEnabled: true,
                ...(Platform.OS === 'android' && TransitionPresets.ModalPresentationIOS),`

`
    <ListStackNavigator.Group screenOptions={{ presentation: 'modal', gestureEnabled: true,
                ...(Platform.OS === 'android' && TransitionPresets.ModalPresentationIOS), }}>
                <ListStackNavigator.Screen
                    name="NewList"
                    component={NewList}
                    options={{
                        headerShown: false,
                    }}
                />
            </ListStackNavigator.Group>
`

**Comment by atultiwaree** [comment]
> This works on android.         
> `presentation: 'modal', gestureEnabled: true,
>                 ...(Platform.OS === 'android' && TransitionPresets.ModalPresentationIOS),`
> 
> `
>     <ListStackNavigator.Group screenOptions={{ presentation: 'modal', gestureEnabled: true,
>                 ...(Platform.OS === 'android' && TransitionPresets.ModalPresentationIOS), }}>
>                 <ListStackNavigator.Screen
>                     name="NewList"
>                     component={NewList}
>                     options={{
>                         headerShown: false,
>                     }}
>                 />
>             </ListStackNavigator.Group>
> `
Will it work on iOS??

**Comment by YosefOberlander** [comment]
@atultiwaree Yes.

**Comment by 00ricardo** [comment]
I'll recommend to use `presentation: "transparentModal"` instead. It worked for me.

**Comment by MartinGambit** [comment]
Please fix this issue with presentation: modal on android.
For iOS there are no issues but on android i cannot make it work. Thanks!

**Comment by phoneticallySAARTHaK** [comment]
Reading through the comments, 

**PR: #2045 is in progress**

## Workarounds

### Use Stack Navigator

> use
import {createStackNavigator} from "@react-navigation/stack";
instead of
import {createNativeStackNavigator} from "@react-navigation/native-stack";
working for both Android and IOS

https://github.com/software-mansion/react-native-screens/issues/1650#issuecomment-1622194445

However, it does not use native navigation like NativeStack

### Use Stack TransitionPresets

> import { TransitionPresets } from '@react-navigation/stack';
<Stack.Screen
name="Profile"
component={Profile}
options={{
title: 'Profile',
...TransitionPresets.ModalSlideFromBottomIOS,
}}
/>;

https://github.com/software-mansion/react-native-screens/issues/1650#issuecomment-1822778814

But it also [uses `Stack` implementation](https://github.com/software-mansion/react-native-screens/issues/1650#issuecomment-1835818957), although you can still use native navigation for other screens



Or just the react-native's modal? But it doesn't have an overlay

**Comment by doyunnn** [comment]
I'm using `@react-navigation/native-stack` and below the props are should work. I think...
```
{
presentation: Platform.select({
                                            ios: 'transparentModal',
                                            android: 'containedTransparentModal',
                                        }),
                                        animation: 'slide_from_bottom',
                                        animationDuration: 100,
                                    }
```

**Comment by mapleroyal** [comment]
Still not working on android.

**Comment by karimelsaidy** [comment]
still not working

**Comment by kkafar** [comment]
Hey, I'm limiting conversation cause:

1. "still not working" comments do not bring anything to the discussion,
2. I've already mentioned that you can track progress on #2045 [(comment link)](https://github.com/software-mansion/react-native-screens/issues/1650#issuecomment-2103859957),

**Comment by kkafar** [comment]
And also let me update you on the status of 

* #2045 

It is quite a big PR with tons of new logic introduced to the library, also bringing some breaking changes to the API - I'm actively progressing through the review & patching rough edges, but I wouldn't be surprised if it took even few more weeks to get the necessary approvals.
