### ISSUE TITLE
Unexpected token (207:10)

### ISSUE THREAD

**Issue by Audrew36** [software-mansion/react-native-screens#1657]
### Description

Android Bundling failed 3393ms
SyntaxError: /home/sos/Projects/RN/updated-app/node_modules/react-native-screens/src/index.native.tsx: Unexpected token (207:10)

  206 |   class Screen extends React.Component<ScreenProps> {
  207 |   private ref: React.ElementRef<typeof View> | null = null;
  208 |   private closing = new Animated.Value(0);
  209 |   private progress = new Animated.Value(0);
  210 |   private goingForward = new Animated.Value(0);

### Steps to reproduce

1. Tried different versions.

### Snack or a link to a repository

https://snack.expo.io

### Screens version

3.11.1

### React Native version

expo sdk 45

### Platforms

Android, iOS, Web

### JavaScript runtime

JSC

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by Audrew36** [comment]
Project currently too big to separate reproduction

**Comment by kkafar** [comment]
The only thing I can recommend is using latest `react-native-screens` version. As there is no reproduction I'm afraid I can't do much more. I checked source code at tag `3.11.1` in the place suggested by the stacktrace fragment you provided but there is nothing out of order there. One thing that comes to my mind is that maybe you are using some old typescript version in your project? Could you give me some insight on that?
