### ISSUE TITLE
Can not hide bottom tabs using tabBarStyle

### ISSUE THREAD

**Issue by chukiatt** [software-mansion/react-native-screens#1658]
### Description

Can not hide bottom tabs using tabBarStyle

### Steps to reproduce

open screen 2 times
first time style applied but next time it does not apply

### Snack or a link to a repository

no link

### Screens version

lastest

### React Native version

lastest

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
I'm tagging it with `close-when-stale` label, as there is no reproduction provided.

**Comment by chukiatt** [comment]
tabBarStyle: {display:'none'},

tabbar is hide but the space is still available

**Comment by crieggalder** [comment]
Confirming - I'm seeing this too. tabBarStyle: { display: 'none' } hides the tab bar, but the space the tab bar would have occupied is still reserved and just empty instead.
