### ISSUE TITLE
IOS Memory leak

### ISSUE THREAD

**Issue by Alaa-Ben** [software-mansion/react-native-screens#167]
Hi !
I have 2 tabs (using Native Base for those) in my app. Usually, when navigation from tab A to tab B, memory consumption rises. Then when going back to tab A, tab B gets unmounted and memory goes back to initial state. I noticed that after adding `useScreens()` to my app, going back to tab A from tab B doesn't lower memory consumption, which means memory keeps drastically increasing when navigating between tabs. Any ideas ?
Thanks in advance for your answers !

React Native: 0.61.1
React Navigation: 4.0.9
react-native-screens: 2.0.0-alpha.3

**Comment by Alaa-Ben** [comment]
Up !

**Comment by WoLewicki** [comment]
Does the issue still persist in the newest version? If so, can you provide a repo with minimal configuration needed to reproduce the issue?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
