### ISSUE TITLE
Header height error on devices with dynamic island

### ISSUE THREAD

**Issue by outaTiME** [software-mansion/react-native-screens#1671]
### Description

Hello there,
After upgrading to Expo 47 I started experiencing a visual issue on devices with dynamic island.

In short, if I run my app in the Expo Go on the simulator everything looks fine (as it did with SDK 46), but if I run it from the Expo Go on the device (or if I build a build with EAS) it looks different.

Here below, I leave some screenshots to better understand the incident:

Expo Go (simulator):

![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-16 at 01 14 20](https://user-images.githubusercontent.com/140472/208022286-f2ba198c-912b-400e-bf09-bafd5d15a9dc.jpeg)

Expo Go (device):

![IMG_F54D287D8EA3-1-new](https://user-images.githubusercontent.com/140472/208022297-516c969b-860d-4775-9941-4885ce7fb759.jpeg)

On the other hand, if I compare the versions between the clients, there is a slight difference in their number:

Expo Go version (simulator): 2.26.4.101

Expo Go version (device): 2.26.4.1016582

I don't quite understand what could be the cause of the problem, but this affects the calculation of the header for the native stack of the `react-navigation` (`useHeaderHeight`) and ends up being wrong.

I assume that the version of Expo Go running on the device (2.26.4.1016582) introduces some regression or dependency incompatibility, which is what causes that problem (and this also affects the EAS build).

Any help is appreciated 🙏

Additionally, I leave you the report of this same incident in another repositories, in which I have not received an answer yet:

https://github.com/expo/expo/issues/20498
https://github.com/react-navigation/react-navigation/issues/10989

### Steps to reproduce

1. Download the repository, install dependencies and run `yarn start`
2. Run the project in `Expo Go` on simulator and see that there is no gap between the header and the content
3. Run the project in `Expo Go` on device and observe the gap between the header and the content

### Snack or a link to a repository

https://github.com/outaTiME/dynamic-island-error

### Screens version

3.18.2

### React Native version

0.70.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

iOS simulator

### Device model

iPhone 14 Pro / iPhone 14 Pro Max

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi, @outaTiME! Thanks for your feedback 👍 Sorry for late response 😢 

Looks like this problem occurs only on the devices with new dynamic island (iPhone 14 Pro / Max). I've managed to reproduce it on local environment and find a fix for it. From now the header height will be calculated dynamically, so the problem should probably not occur (we need to confirm that everything is still working correctly after implementing a fix in react-navigation).

**Comment by tboba** [comment]
@outaTiME Hi! For now we will merge pull request created by @dylancom, but in a short time we will introduce a dynamic implementation of calculating header height 👍

**Comment by dylancom** [comment]
@tboba sounds good, but doesn't that have the risk of "layout shifts"? I currently use `useHeaderHeight` to directly calculate the height of a view (and prevent layout shifting while waiting for a dynamic calc of the view's height). See issue: https://github.com/software-mansion/react-native-screens/issues/1779

**Comment by tboba** [comment]
@dylancom It actually should not shift layouts! After every test I've done I haven't spotted any layout shifts. You also won't have to move to the new implementation of the hook (We've decided the new implementation of calculating header height will be moved to completely new `useAnimatedHeaderHeight` hook). 

If you spot any layout shifts or stutters, please let us know! We will also try to investigate #1779 in the future (talking about the original `useHeaderHeight` here).

**Comment by tboba** [comment]
Hi @dylancom @outaTiME, there's a new version of react-native-screens: 3.26.0 which has the new `useAnimatedHeaderHeight` hook included. Check it out! If you find something wrong related to the newest version (this change is still buggy or doesn't work for you) let us know 🎉

**Comment by outaTiME** [comment]
Such good news @tboba, it would be very useful if react navigation would support this new hook, which as far as I can see they haven't done it yet.

**Comment by tboba** [comment]
@outaTiME As for now react navigation's native stack is on the separate repository we'll try our best to make it happen! You should see changes from this release in upcoming days there 🫡

**Comment by outaTiME** [comment]
@tboba that would be awesome, I'll look forward to the updates, thank you for your constant dedication 🫶
