### ISSUE TITLE
requireNativeComponent: RNSScreen was no found in the UIMANAGER

### ISSUE THREAD

**Issue by my-name-is-nheo** [software-mansion/react-native-screens#1674]
### Description

I have the latest versions of 
- @react-navigation/bottoms-tabs
- @react-navigation/drawer
- @react-navigation/elements
- @react-navigation/native
- @react-navigation/stack
- react-native-reanimated
- react-native-safe-area-context
- react-native-screens
installed. 
![image](https://user-images.githubusercontent.com/58013260/210452650-f7830679-da59-443d-9dad-874c15b46d78.png)

![image](https://user-images.githubusercontent.com/58013260/210452618-68f1b275-3494-4fba-90e9-e737faffd2bc.png)

However when I built my app, I ended up getting this error. I recently converted to `pnpm` and read react-native does not support symlinks so I added a configuration to flat out the node_modules without any. (more this [here](https://pnpm.io/npmrc#node-linker)) 

![image](https://user-images.githubusercontent.com/58013260/210453331-0e2dd68b-313d-444f-9fdc-160c3dc19690.png)

After clearing cache, reinstall node_modules, and pods,  I've navigated to my pods directory on XCode and I couldn't locate the RNSScreen pod. 
![image](https://user-images.githubusercontent.com/58013260/210453545-08378c2a-1ca8-47ea-a19e-285439058dac.png)
(Am I supposed to see a RNSScreen pod in the list?)

 I tried manually installing the pod  
`pod 'RNScreens', :path => '../node_modules/react-native-screens/RNScreens.podspec'`

The error goes away, but got a duplicate pod error when trying to deploy to TestFlight. I was able to manually delete the duplicate pod (accessibilityResource) and publish, but I know this is not the way to fix this. 

![image](https://user-images.githubusercontent.com/58013260/210457127-bae88e9c-f7cf-4441-9be8-dbf09f0a9ec4.png)

Any help would be greatly appreciated. 

### Steps to reproduce

1. Installed latest react-navigation packages
2. delete node_modules && pnpm install
3. cd ios/ && pod install
4. watchman watch-del-all
5. pnpm run clean:start (--clear-cache)
6. fastlane command to deploy

### Snack or a link to a repository
This link is just the index.js of my app
https://snack.expo.dev/U41fM6iPM

### Screens version

3.18.2

### React Native version

0.67.5

### Platforms

iOS

### JavaScript runtime

V8

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iphone 13

### Acknowledgements

Yes

**Comment by my-name-is-nheo** [comment]
checking if this [comment](https://github.com/software-mansion/react-native-screens/issues/1614#issuecomment-1276212091) will work

**Comment by kkafar** [comment]
Hi @my-name-is-nheo!

> (Am I supposed to see a RNSScreen pod in the list?)

Yes, the `RNScreens` pod should definitely should be there.

> requireNativeComponent: RNSScreen was no found in the UIManager

This error message is often a sign that the library has not been linked properly. 

It's hard to tell what is wrong with `pnpm` setup right now (I'm not really familiar with this tool), but React Native project is expected to have specific structure and React Native (and `react-native-screens` library) in few places rely on that. 

Would you mind running the following command in your project directory, and provide me with the result?

```
yarn react-native config
```

(Try to use `yarn` or `npm` tools, I've no idea whether `pnpm` has some influence on command result or not)

**Comment by Desintegrator** [comment]
Same issue
I was able ti fix it when added next line in Podfile
`pod 'RNScreens', :path => '../node_modules/react-native-screens'`

**Comment by hank619** [comment]
For those who donesn't work even if react-native-screens is added to package.json, pls try `yarn remove @react-native-community/cli`  in case you hanve already installed an older version of `@react-native-community/cli` so`react-native config` won't analysis the `react-native-screeens` library properly.    
  
No worry, `@react-native-community/cli` is automatically imported by `react-native` so won't cause any error.

Relevant code are [here](https://github.com/react-native-community/cli/blob/6eb95951d9a49114e723d887f7e5223f7fe5f4c9/packages/cli-platform-android/native_modules.gradle#L417)

**Comment by Mary-Grigoryan** [comment]
I have tried all of the above steps and still have the error

**Comment by josedomingos919** [comment]
> Same issue I was able to fix it when added next line in Podfile `pod 'RNScreens', :path => '../node_modules/react-native-screens'`

This solution is working for me, thanks!
