### ISSUE TITLE
Navigation Events not getting fired with createNativeStackNavigator

### ISSUE THREAD

**Issue by swathysubhash** [software-mansion/react-native-screens#168]
Navigation Events stop getting fired from StackViews created with createNativeStackNavigator.
Only WillFocus is getting called.
This happens when stackView is opened from BottomBarNavigator Screen

**Comment by Hirbod** [comment]
willFocus also only gets fired 1 time. Anybody here with a workaround?

**Comment by WoLewicki** [comment]
Does the issue still persist in the newest version? If so, can you provide a repo with minimal configuration needed to reproduce the issue?

**Comment by Hirbod** [comment]
This is fixed in SDK 37

**Comment by WoLewicki** [comment]
Ok, I am closing the issue then.
