### ISSUE TITLE
headerBackTitleStyle breaks on iOS 16 with a dynamic main title

### ISSUE THREAD

**Issue by elisa-rotger** [software-mansion/react-native-screens#1682]
### Description

When dynamically adding or removing a title on a navigation stack screen, the styling set for the back button breaks and it returns to its default state.

As you can see in the example below, there is a screen with a toggable title - when clicked, the style of the back button applied by that prop is removed.

Important: This did NOT happen on iOS 15, only happens on 16 that I've observed. In order to see this behavior, it's necessary to take the example code provided and run it on ios 15.xx and 16.xx to see the difference. Also providing a recording for both cases:

https://user-images.githubusercontent.com/83600907/212047742-64b92b51-e6dc-4f9d-9046-19c110bf375f.mp4

PS: Added this issue on react-navigation github and was directed here (https://github.com/react-navigation/react-navigation/issues/11149)

### Steps to reproduce

In the snack example provided:
  1. Click on side button to navigate to the side screen
  2. Click on toggle title button to remove and add the title to the screen
  3. Notice how the back button styling added by the prop headerBackTitleStyle is removed

### Snack or a link to a repository

https://snack.expo.dev/@elisa.rotger/toggable-title

### Screens version

~3.15.0

### React Native version

0.69.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

Expo bare workflow

### Architecture

None

### Build type

None

### Device

iOS simulator

### Device model

iPhone 14 Pro (iOS 16.2)

### Acknowledgements

Yes

**Comment by lundn** [comment]
Are there any progress on this?
