### ISSUE TITLE
Header theme is set incorrectly

### ISSUE THREAD

**Issue by WhidRubeld** [software-mansion/react-native-screens#1683]
### Description

When setting a theme for the NavigationContainer other than the OS, setting the theme for the Stack navigator works incorrectly (searchBar, header card shadow style).

![IMG_4058](https://user-images.githubusercontent.com/35730139/212303632-cbd4f847-07ed-4c94-beea-7bd3568e5537.png)

### Steps to reproduce
see snack example

### Snack or a link to a repository

https://snack.expo.dev/@appomart/react-native-screens-theme-bug-report

### Screens version

~3.18.0

### React Native version

0.70.5

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Would you mind elaborating, what do you mean when saying "theme is set incorrectly"?

I've just tested your reproduction & it seems to work completely fine

https://user-images.githubusercontent.com/50801299/213862775-ffbd50a5-f6af-4468-99b7-741b29cf2236.mov

In the video above I toggle between `LightTheme` and `DarkTheme`.

What is your expected result?

**Comment by kkafar** [comment]
I've just noticed it now 🤦🏻 The issue is completely valid

**Comment by WhidRubeld** [comment]
Test 1:
- NavigationContainer theme - light
- OS theme - light
- Result - correct
<img width="451" alt="Screenshot 2023-01-27 at 18 20 00" src="https://user-images.githubusercontent.com/35730139/215121850-871e4b81-e95b-446e-a3cd-c29382575758.png">

Test 2:
- NavigationContainer theme - light
- OS theme - dark
- Result - **incorrect**
<img width="451" alt="Screenshot 2023-01-27 at 18 20 39" src="https://user-images.githubusercontent.com/35730139/215122033-f8f4bf50-ac1a-451c-9336-22c740d9c0e9.png">

Test 3:
- NavigationContainer theme - dark
- OS theme - dark
- Result - correct
<img width="451" alt="Screenshot 2023-01-27 at 18 21 27" src="https://user-images.githubusercontent.com/35730139/215122194-30ec95d4-cf22-484c-9e47-1be057d434c0.png">

Test 4:
- NavigationContainer theme - dark
- OS theme - light
- Result - **incorrect**
<img width="451" alt="Screenshot 2023-01-27 at 18 22 04" src="https://user-images.githubusercontent.com/35730139/215122344-cdbc7327-fc15-4191-a321-402f0e6aa379.png">

**Comment by kkafar** [comment]
The fix will be published with next minor version. Thanks for reporting!
