### ISSUE TITLE
When I want to go to the previous page, everything suddenly disappears

### ISSUE THREAD

**Issue by ugurdalkiran** [software-mansion/react-native-screens#1685]
### Description

I'm opening a new page on Android and everything is fine. When I want to come back from that opened page, all Views and Texts disappear from the screen. A white screen appears. Then my back page opens.

At this stage, I want the objects on my screen not to disappear.

In my opinion such a problem occurs when **FABRIC is enabled**. If fabric is not enabled, everything continues as normal. Could it be that the react-navigation package's fabric support is not working properly?

Here is the video.

https://user-images.githubusercontent.com/27302986/191944841-4caf6c35-7395-4329-8203-6ef68ff352a6.mp4

```
"react": "18.2.0",
"react-native": "0.71.0",
---
"@react-navigation/native": "6.1.2",
"@react-navigation/native-stack": "6.9.8",
"react-native-gesture-handler": "2.9.0",
"react-native-safe-area-context": "4.4.1"
"react-native-screens": "3.18.2"

<GestureHandlerRootView style={{ flex: 1 }}>
	<NavigationContainer>
		<Stack.Navigator
		screenOptions={{
			headerMode: "screen"
		}}
		initialRouteName="Home">
		<Stack.Screen name="Home" component={Home} />
		<Stack.Screen
			name="Page"
			component={Page}
			options={{ animation: "slide_from_right" }}
		/>
		</Stack.Navigator>
	</NavigationContainer>
</GestureHandlerRootView>

props.navigation.navigate("Page");
props.navigation.goBack();
```

### Steps to reproduce

1. I go to a page.
2. I click the back button.
3. **Everything disappears. A white page appears instantly** and the previous page opens.

### Snack or a link to a repository

https://stackoverflow.com/help/mcve

### Screens version

3.18.2

### React Native version

0.71.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by ugurdalkiran** [comment]
@kkafar 

I have now installed the updated version **(3.19.0)** and checked again but the problem persists. 😥

Probably the problem is not related to the **react-native-screens** package. Can we say that the problem is caused by the **react-navigation** package?

**Comment by kkafar** [comment]
Hi @ugurdalkiran!

> Probably the problem is not related to the react-native-screens package. Can we say that the problem is caused by the react-navigation package?

No, the problem definitely lies in `react-native-screens`, moreover we are aware that this problem exists. It is caused by change of order in which views are unmounted on new architecture, that is leafs to root (bottom - top) ==> child views are unmounted before the transition begins. On Paper it was not the case, because the order was opposite - root to leafs (top - bottom). 

We still need to find a proper solution to this problem.

**Comment by ugurdalkiran** [comment]
I am glad that you are aware of the problem and that you are looking for a solution.

I hope it will be resolved as soon as possible, thanks for your efforts. ❤️

**Comment by nandorojo** [comment]
Similar problem happening on iOS, **without Fabric enabled**. 

The screen goes blank and just like flies out of place instead of animating out.

## Before

Here is screens version `3.11.1`:


https://user-images.githubusercontent.com/13172299/214119945-0269b941-9a50-402d-bb7f-183abdaac4d7.mov

## After

Here is `3.18.0`. Notice it looks weird when going back. If I swipe back, it works fine. The issue only happens if I call `goBack()`/use the back button.

https://user-images.githubusercontent.com/13172299/214120332-694d185f-4157-4df5-b282-dd2b3b908af6.mov




Any idea which version this started with? Would be useful to downgrade to avoid it happening. Thank you!

**Comment by miladdev85** [comment]
It seems to be the same issue as this: [https://github.com/software-mansion/react-native-screens/issues/1532](url)
Although the one I linked to is Reanimated 2

**Comment by dppo** [comment]
Similar problem happening on android with fabric enabled
`
"@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "react": "18.2.0",
    "react-native": "0.71.7",
    "react-native-safe-area-context": "^4.5.2",
    "react-native-screens": "^3.20.0"
`

**Comment by RyuWoong** [comment]
same issue here +1

platform ios
library version all lastest

enable fabric and using some navigation method  (reset , replace)

any solution?

**Comment by Obhenimen** [comment]
> Hi @ugurdalkiran!
> 
> > Probably the problem is not related to the react-native-screens package. Can we say that the problem is caused by the react-navigation package?
> 
> No, the problem definitely lies in `react-native-screens`, moreover we are aware that this problem exists. It is caused by change of order in which views are unmounted on new architecture, that is leafs to root (bottom - top) ==> child views are unmounted before the transition begins. On Paper it was not the case, because the order was opposite - root to leafs (top - bottom).
> 
> We still need to find a proper solution to this problem.

Please is there a quick fix or any hack to get around this behaviour. Thanks for your reply

**Comment by tboba** [comment]
Hi everyone! I know that this problem is unfortunately still relevant and I want to really say sorry that some of you may experience it. From our side we're still waiting to merge @WoLewicki [PR](https://github.com/facebook/react-native/pull/40738) to official React Native repo about adding listeners for screen mount operations so we could perform proper logic when the screen will unmount on Android. With those listeners it will be possible to fix this issue, but for now we only have to wait 😓

**Comment by kirillzyusko** [comment]
Hey @tboba @WoLewicki @kkafar 

I think `react-native` team hasn't accepted this PR (unfortunately 😔). Are you planning to create any fixes for that (maybe you have some other ideas on how to fix it)?

As I can understand the problem now is that views are getting actually removed from the screen before root `Stack` component receives the same event, right?

**Comment by tboba** [comment]
Hi @kirillzyusko! Yeah, we know this PR has been rejected, sadly 😢 AFAIK, currently @kkafar is working on possible fix for that bug, do you know Kacper what's the current state of it?
About the second thing - yes, that's exactly why all of the elements are gone on going backwards.

**Comment by kirillzyusko** [comment]
@tboba Cool, glad to hear that progress is moving 😎 

I just thought to suggest that potentially we can pospone unmounting a component in JS (I guess it's managed by react-navigation). Just potentially instead of excluding a component from JS tree we can assign a new prop (like `removing=true/false`) and actually remove a component only when transition has completed.

But I'll be glad to hear how you managed to overcome this problem 💪 👀

**Comment by WoLewicki** [comment]
Hey all, could you check https://github.com/software-mansion/react-native-screens/pull/2134 fixes this problem and does not introduce any new ones?

**Comment by kirillzyusko** [comment]
@WoLewicki I can check only next week (currently on a short vacation and don't have an access to my laptop) 👀

**Comment by alduzy** [comment]
I believe https://github.com/software-mansion/react-native-screens/pull/2134 fixes the issue.
Let me know in case you are still encountering the problem, I will re-open it.

**Comment by r0b0t3d** [comment]
@alduzy I can confirm that your PR fixed the issue on 4.0.0-beta.14. But looks like @maciekstosio is working on a separate PR, so for now I will patch the changes to use it temporarily

**Comment by Odyrac** [comment]
got same issue with 4.1.0 since migrating to expo sdk 52 newArch

**Comment by 2Senn** [comment]
Still facing this issue. I am on 4.4.0. Happens with a screen that has modal presentation on IOS. when navigation.goBack() is called. screen turns blank before dismissing. Any update on this?
Thanks!

**Comment by kkafar** [comment]
@2Senn I can't confirm that the issue occurs anymore. Could you provide me with more details:

1. library versions you're using,
2. test screen you're using,
3. recording of the bug?

**Comment by 2Senn** [comment]
@kkafar Hey sure thing! 

react-native-screens 4.4.0
expo 52.0.23
"@react-navigation/bottom-tabs": "^7.2.0",
"@react-navigation/native": "^7.0.13",
"@react-navigation/native-stack": "^7.2.0",
"react-native": "0.76.5",

```
    <Stack.Navigator
      screenOptions={{
        animation: "fade_from_bottom",
        headerShown: false,
        contentStyle: { backgroundColor: "white" },
      }}
      initialRouteName={redirectToCart ? "Cart" : "MerchantMain"}
    >
      <Stack.Screen name="MerchantMain" component={MerchantScreen} />
      <Stack.Screen
        name="Modifier"
        component={Modifiers}
        options={{
          headerShown: false,
          presentation: "modal",
        }}
      />
      <Stack.Screen
        name="Menu"
        component={MenuSheet}
        options={{
          headerShown: false,
          sheetGrabberVisible: true,
          presentation: "formSheet",
          sheetAllowedDetents: [0.5, 0.7],
          sheetLargestUndimmedDetentIndex: "none",
          sheetCornerRadius: 24,
        }}
      />
      <Stack.Screen
        name="Cart"
        component={CartScreen}
        options={{
          header: () => <CartHeader title="Cart" />,
          headerShown: true,
        }}
      />
    </Stack.Navigator>
```
Here is the modal screen: 

```
export const Modifiers = () => {
  const { activeItem, clearActiveItem } = useActiveItemStore();
  const { clearSelections } = useModifierStore();
  const { bottom } = useSafeAreaInsets();
  const scrollRef = useRef<FlashList<Modifier>>(null);

  useFocusEffect(
    useCallback(() => {
      return () => {
        // clean up active item and form
        clearActiveItem();
        clearSelections();
      };
    }, [])
  );

  if (!activeItem) return null;

  return (
    <View className="flex-grow min-h-screen">
      <View className="w-full flex-row flex-grow">
        <FlashList
          ref={scrollRef}
          data={activeItem.modifiers}
          bounces={false}
          ListHeaderComponent={ListHeader}
          contentContainerStyle={{ paddingBottom: BOTTOM_HEIGHT + bottom + 16 }}
          estimatedItemSize={200}
          showsVerticalScrollIndicator={false}
          keyExtractor={(item) => item.id}
          ItemSeparatorComponent={() => <Divider />}
          ListFooterComponent={ListFooter}
          renderItem={({ item }) => <ItemModifier item={item} />}
        />
      </View>
      {/* Add to cart UI */}
      <AddToCart scrollRef={scrollRef} />
    </View>
  );
};
```

I thought it might have something to do with calling useFocusEffect (which on unmount removes the conents of the screen essentially). However, it happens with and without it. 

Here is a video: 

https://github.com/user-attachments/assets/9fc65df1-6f65-4ea7-bccb-ce54221cbf0e

**Comment by 2Senn** [comment]
It seems that it is closely related to Lists specifically. Commenting out my flashlist or my flatlist from the footer causes it to work correctly. Will try to find a more exact cause.

**Comment by 2Senn** [comment]
Sorry I deleted the post with the versions and recording since I managed to find exactly what is happening. 

One of the child components is an Animated.View (with reanimated 3) and when using "entering" / "exiting" animations, the bug occurs. 

commenting those out solves the issue. Although I am not too sure why a small components exiting animation causes the entire component to unmount when navigating back.

**Comment by kkafar** [comment]
@2Senn I've seen something similar reported here: 

* https://github.com/software-mansion/react-native-screens/issues/2545

& I've forwarded this to reanimated team

**Comment by Hydralerne** [comment]
any solutions ? issue still exist in android

**Comment by thomasflensted** [comment]
This is also happening to me on iOS. Lots of weird behavior when using modal presentation for routes.

**Comment by kkafar** [comment]
If you believe this is still a valid issue - please provide a reproduction & preferably a recording of the bug happening. Otherwise I consider it fixed.

**Comment by jjr02** [comment]
> Se você acredita que este ainda é um problema válido - por favor, forneça uma reprodução e, de preferência, uma gravação do bug acontecendo. Caso contrário, considero-o fixo.

I'm currently having this problem

https://github.com/user-attachments/assets/5e20a912-e387-4ebb-8174-2dc745d09368

**Comment by jjr02** [comment]
> Se você acredita que este ainda é um problema válido - por favor, forneça uma reprodução e, de preferência, uma gravação do bug acontecendo. Caso contrário, considero-o fixo.

I'm currently having this problem

https://github.com/user-attachments/assets/61c25821-95f6-480d-aa67-abb12060ae29

**Comment by jjr02** [comment]
> If you believe this is still a valid issue - please provide a reproduction & preferably a recording of the bug happening. Otherwise I consider it fixed.

I'm currently having this problem

https://github.com/user-attachments/assets/c5f3ea48-ce2c-455a-941b-fd650a33c9c0

**Comment by kkafar** [comment]
@jjr02 thanks! I can see that you clearly experience the issue and that's something. 
On my end, however, I can't reproduce and therefore debug the problem. Would you consider spending some time to prepare a reproduction? I would also need your dependency list (at least react-native, react-native-screens versions)

**Comment by Hydralerne** [comment]
It's exist in latest version of rn screens on android when screens are enabled, just give the unmont a delay till the animation finish

**Comment by kkafar** [comment]
Okay @Hydralerne, please provide a reproduction.

**Comment by jjr02** [comment]
> [@jjr02](https://github.com/jjr02) thanks! I can see that you clearly experience the issue and that's something. On my end, however, I can't reproduce and therefore debug the problem. Would you consider spending some time to prepare a reproduction? I would also need your dependency list (at least react-native, react-native-screens versions)


Hello, the dependency versions are

"react-native": "0.76.7",
"react-native-screens": "~4.4.0".

The error occurs when the application is run on Android devices.

Below is the link to a basic example with the error via the snack expo dev platform.

https://snack.expo.dev/eVy0kZFeAtnzhu9Sn-IZt?platform=android

video in ios emulator working normally

https://github.com/user-attachments/assets/e12c5528-d4e2-4b8e-9c2c-0430e9c676c8

video on the android emulator with the error

https://github.com/user-attachments/assets/568d9b58-ecf9-424c-b2b2-8eb1ebcb2787

In this example, when we return to the previous screen, the content with a red background disappears and in a fraction of a second, the standard screen without content is displayed, followed by the main screen.

**Comment by jjr02** [comment]
> [@jjr02](https://github.com/jjr02) thanks! I can see that you clearly experience the issue and that's something. On my end, however, I can't reproduce and therefore debug the problem. Would you consider spending some time to prepare a reproduction? I would also need your dependency list (at least react-native, react-native-screens versions)

@kkafar 

Hello, the dependency versions are

"react-native": "0.76.7",
"react-native-screens": "~4.4.0".

The error occurs when the application is run on Android devices.

Below is the link to a basic example with the error via the snack expo dev platform.

https://snack.expo.dev/eVy0kZFeAtnzhu9Sn-IZt?platform=android

video in ios emulator working normally

https://github.com/user-attachments/assets/e12c5528-d4e2-4b8e-9c2c-0430e9c676c8

video on the android emulator with the error

https://github.com/user-attachments/assets/568d9b58-ecf9-424c-b2b2-8eb1ebcb2787

In this example, when we return to the previous screen, the content with a red background disappears and in a fraction of a second, the standard screen without content is displayed, followed by the main screen.

**Comment by Beki78** [comment]
@jjr02  Did you find any solution for this

**Comment by MichalKrakow** [comment]
Bump, expo 52 with react navigation, on expo go and dev build, same issue. How come this persist since 2023 my god.

**Comment by kkafar** [comment]
@MichalKrakow if you experience the issue, please provide a reliable reproduction (preferably w/o expo). Atm I can't reproduce it & I'm using the library daily.

**Comment by MichalKrakow** [comment]
sure no problem:
```
npx create-expo-app@latest --template react-navigation/template
```
run on adnroid device with expo go.
There you have it.

**Comment by E-Emmy** [comment]
This issue still persists, especially when adding animation: slide_from_right

**Comment by E-Emmy** [comment]
This issue still persists, especially when adding animation: slide_from_righthttps://github.com/user-attachments/assets/38580bd9-9a72-4f95-b9db-e03be0a88c7b

**Comment by kkafar** [comment]
I can only reiterate: I do not reproduce the issue. Valid reproduction w/o expo is needed here.

**Comment by Jgtech1** [comment]
Changes made:
enableScreens() added: This helps improve the performance of react-native-screens and prevents screen flickering, especially when transitioning between screens.

This method ensures the screens are managed better by React Native under the new architecture.

detachInactiveScreens={false}: This prevents screens from being detached when not active, which resolves the issue of views disappearing when going back.

Removed invalid headerMode: "screen": This was not required for @react-navigation/native-stack (it’s for @react-navigation/stack). Instead, you can use options directly like title or headerShown to control the header.

Basic Screen Components (Home and Page): I added basic UI components for Home and Page to give context and ensure the app works out of the box.

Explanation:
GestureHandlerRootView: This is the wrapper component required when using react-native-gesture-handler, ensuring gestures are handled properly within the app.

NavigationContainer: This is the root navigator component that wraps the entire app and enables navigation functionality.

Stack.Navigator: The Stack.Navigator now uses the detachInactiveScreens={false} setting to ensure inactive screens are not unmounted. This prevents the disappearing views when navigating back.

options={{ animation: 'slide_from_right' }}: This ensures the page transition is smooth and animated.

Next Steps:
Test the app: After applying the code, make sure to test the navigation between the "Home" and "Page" screens to confirm that the views no longer disappear when going back.

Additional Debugging: If the issue persists, it might be related to Expo's new architecture. In that case, try disabling Fabric temporarily in app.json as I mentioned earlier.

But try this code let see 

import React from 'react';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { enableScreens } from 'react-native-screens'; // Enable screens for better performance

// Enable screens
enableScreens();

// Screen components
function Home() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Home Screen</Text>
    </View>
  );
}

function Page() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Page Screen</Text>
    </View>
  );
}

const Stack = createNativeStackNavigator();

export default function App() {
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <NavigationContainer>
        <Stack.Navigator
          initialRouteName="Home"
          detachInactiveScreens={false} // Ensuring inactive screens are not detached
        >
          <Stack.Screen
            name="Home"
            component={Home}
            options={{
              title: 'Home',
            }}
          />
          <Stack.Screen
            name="Page"
            component={Page}
            options={{
              animation: 'slide_from_right', // Slide animation for Page screen
            }}
          />
        </Stack.Navigator>
      </NavigationContainer>
    </GestureHandlerRootView>
  );
}

**Comment by Odyrac** [comment]
still same issue with slide_from_right and minimal example since expo 53 (expo 51 was ok)

**Comment by Odyrac** [comment]
@kkafar can we reopen this issue? I managed to reproduce it on expo53 with the minimal code example on React Navigation AND Expo Router. I know this issue has existed since the migration from expo51 to expo52. I did some research on the internet, and many issues on Reddit and other platforms mention similar problems.

To get your minimal example, just run `npx create-expo-app@latest --template tabs`

**Comment by Odyrac** [comment]
https://github.com/user-attachments/assets/8baf17d2-a20e-496c-b00f-efd44559f7e6

Here is an example with Expo Router using the minimal example. The bug is even more noticeable with React Navigation using a slide_from_right animation because it further highlights the previous screen, which seems to unmount.

**Comment by simonasbuj** [comment]
It's still the same in 2026... People on other tickets and stackoverflow are saying to use  `SystemUI.setBackgroundColorAsync` but it doesnt help at all for me.


https://github.com/expo/expo/issues/32425
https://stackoverflow.com/a/76286959

**Comment by Odyrac** [comment]
Hey, are you using Expo Go? This issue still exists but only on Expo Go for
me. Using development builds fix the issue and I don't have any issue in
prod build. I am also using the system ui fix, yes!

**Comment by simonasbuj** [comment]
> Hey, are you using Expo Go? This issue still exists but only on Expo Go for
> me. Using development builds fix the issue and I don't have any issue in
> prod build. I am also using the system ui fix, yes!
> 
> Le sam. 10 janv. 2026, 21:51, Simas ***@***.***> a écrit :
> […](#)

Hey,  yes the bug is in expo go. Could you share where and how do you set  SystemUI.setBackgroundColorAsync?

Cause i tried setting it in root _layout.tsx to "#ffffff" but the bug still persists.

And I didnt try the build yet, but good to know that it fixes the bug.

**Comment by arpeiks** [comment]
Replacing expo-router stack seems to resolve the issue
`bun add @react-navigation/stack react-native-gesture-handler`


```
import { withLayoutContext } from "expo-router";
import { createStackNavigator } from "@react-navigation/stack";

const { Navigator } = createStackNavigator();
export const Stack = withLayoutContext(Navigator);

export default function RootLayout() {
  return <Stack screenOptions={{ headerShown: false, animation: "slide_from_right" }} />;
}
```

**Comment by najwer23** [comment]
slide_from_right, "expo": "~56.0.12", still persist

**Comment by JS-GitRepo** [comment]
I've been experiencing the same issue on Expo 57 and can confirm- _it's an Expo Go issue._

Creating a dev build and running it on device (Android, Pixel 9 Pro) resolves the issue with no other tweaks.
