### ISSUE TITLE
formSheet presentation only opening half-way in 3.19.0

### ISSUE THREAD

**Issue by gorbypark** [software-mansion/react-native-screens#1686]
### Description

formSheet presentation screens are only opening half-way in 3.19.0.  I reverted to 3.18.2 and everything works as normal.  Looking through the change logs I'm not seeing anything obvious to the cause of this.  Originally I had thought the new formSheet detent PR had merged/released, but it hasn't yet https://github.com/software-mansion/react-native-screens/pull/1649#issuecomment-1396638960.  I have only tried on the "old architecture".  The two screenshots below show 3.19.0 and 3.18.2, respectively, with no other changes made besides the version.

3.19.0
<img width="415" alt="Screen Shot 3.19.0" src="https://user-images.githubusercontent.com/19569469/213394219-b7f5d6df-c729-4913-8590-031444b1f5b8.png">

3.18.2
<img width="415" alt="Screen Shot 3.18.2" src="https://user-images.githubusercontent.com/19569469/213412411-38d70b97-3d6f-4385-8729-7bd4c9f13299.png">

### Steps to reproduce

1. Upgrade to react-native-screens 3.19.0
2. set `'presentation: 'formSheet'` on a screen

### Snack or a link to a repository

.

### Screens version

3.19.0

### React Native version

0.71.0

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by gorbypark** [comment]
After further investigation, it appears that the medium detent PR was accidentally merged in 3.19.0?  https://github.com/software-mansion/react-native-screens/compare/3.18.2...3.19.0 the changelog is showing it as included in 3.19.0

**Comment by kkafar** [comment]
Yeah, this might be a my mistake, as I've left some part of native implementation intact... But while testing I didn't notice the change of default behaviour. I'll check this & let you know

**Comment by kkafar** [comment]
Yep, everything works fine on main, I've made mistake when removing public API and wrong default value is passed in `3.19.0` 🤦🏻‍♂️ 

It will be fixed with next minor version (won't give you details, but it should not be long from now).

**Comment by SMJ93** [comment]
Hey @kkafar, when you you plan on releasing `3.19.1`?

**Comment by hirbod** [comment]
@kkafar this issue has not been resolved yet as we're still on 3.19 and Expo SDK 48 is about to ship with 3.19.0. Could we get a 3.19.1 to be shipped with Expo? Thanks!

**Comment by kkafar** [comment]
Should be fixed with: https://github.com/software-mansion/react-native-screens/releases/tag/3.20.0

**Comment by adamivancza** [comment]
@kkafar the issue was fixed in 3.20.0 but was re-introduced again in later versions.

**Comment by kkafar** [comment]
Hey @adamivancza, I've just tested it on main -- seems to me that sheet presentation works just fine. 
Here's my test case:

<details>

```tsx


import * as React from 'react';
import {Button, StyleSheet, View, Text, ScrollView} from 'react-native';
import {NavigationContainer, ParamListBase} from '@react-navigation/native';
import {
  createNativeStackNavigator,
  NativeStackNavigationProp,
} from 'react-native-screens/native-stack';
import {SheetDetentTypes} from 'react-native-screens';

const Stack = createNativeStackNavigator();

export default function App(): JSX.Element {
  return (
    <NavigationContainer>
      <Stack.Navigator
        screenOptions={{
          // headerRight: () => <View style={styles.headerView} />,
          headerTitleStyle: {
            color: 'cyan',
          },
          headerShown: true,
          headerHideBackButton: false,
        }}>
        <Stack.Screen name="First" component={First} />
        <Stack.Screen
          name="SheetScreen"
          component={SheetScreen}
          options={{
            stackPresentation: 'formSheet',
          }}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

function First({
  navigation,
}: {
  navigation: NativeStackNavigationProp<ParamListBase>;
}) {
  return (
    <Button
      title="Tap me for the second screen"
      onPress={() => navigation.navigate('SheetScreen')}
    />
  );
}

function SheetScreen({
  navigation,
}: {
  navigation: NativeStackNavigationProp<ParamListBase>;
}) {
  return (
    <View style={styles.centeredView}>
      <Button
        title="Tap me for the first screen"
        onPress={() => navigation.navigate('First')}
      />
      <Button
        title="Tap me for the second screen"
        onPress={() => navigation.navigate('Second')}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  headerView: {
    height: 20,
    width: 20,
    backgroundColor: 'red',
  },
  centeredView: {
    justifyContent: 'center',
    alignItems: 'center',
  },
});

```
</details>


The sheet opens by default to full height. 

Provide me with repro / give more detail please.

**Comment by adamivancza** [comment]
hey @kkafar! Maybe you're using something outdated in your repro as `stackPresentation` was renamed to `presentation`? 
https://reactnavigation.org/docs/native-stack-navigator/#presentation
https://reactnavigation.org/docs/upgrading-from-5.x/#options-of-native-stack

**Comment by kkafar** [comment]
@adamivancza, I see now.
Difference in prop naming comes from the fact that I'm using only `react-native-screens`.
Please note that I'm importing native stack directly from `react-native-screens` not from `@react-navigation/native-stack` (which uses `react-native-screens` components under the hood).
I'll check out whether it works with `@react-navigation` & let you know whether the issue should be moved to their repo.

**Comment by adamivancza** [comment]
<img width="526" alt="Screenshot 2023-07-06 at 12 32 58" src="https://github.com/software-mansion/react-native-screens/assets/19835917/c8b1d7da-e8db-4133-8860-cfb741d31942">

will attach a full repro project shortly

**Comment by adamivancza** [comment]
full repro project:
[formsheet-repro.zip](https://github.com/software-mansion/react-native-screens/files/11967271/formsheet-repro.zip)

**Comment by kkafar** [comment]
@adamivancza, 
could you try out `react-native-screens` from this branch #1811 ?

You can put the following in your `package.json`:

```json
"react-native-screens": "software-mansion/react-native-screens#@kkafar/check-sheet-presentation-on-ios"
```

Let me know whether the fix works.

**Comment by adamivancza** [comment]
yeah, I can confirm that works fine @kkafar! thx for the quick fix ;)
can you release this fix as a patch?


<img width="502" alt="Screenshot 2023-07-06 at 14 09 04" src="https://github.com/software-mansion/react-native-screens/assets/19835917/fd10db24-cc21-4616-8988-84be66e579e0">

**Comment by kkafar** [comment]
@adamivancza It's already released

**Comment by IgorVanian** [comment]
Sorry to dig this up but it seems that on some older iOS versions this issue is still present. We have a case on iPhone7 iOS 15.8.8 (Released May 11, 2026). @kkafar 

Edit: actually found out custom detents values were only introduced in iOS 16+ https://developer.apple.com/documentation/uikit/uisheetpresentationcontrollerdetent/resolvedvalueincontext:?language=objc
