### ISSUE TITLE
Android crash: "Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment

### ISSUE THREAD

**Issue by swiggyrahulgupta5** [software-mansion/react-native-screens#1697]
### Description

I am react-native-screens in my application.
My app is a tab bar with 5 fragments one of which is a react native module and 1 tab is an activity with a react native module as well.
When i open the fragment with the react native code, 
then open the activty and navigate back and forth between these two, i get this crash:

AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app/com.app.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception

Fragment A (React Native) has Activity A as a parent
Activity B(React Native)
So there are two different things here (mind my english) but then how is this causing this ScreenFragment issue?
Is ScreenFragment singleton?
Please advice how can i keep separate instances of react native navigation if i have 2 different react native components one is loaded in a fragment and one in an activity in the same app

### Steps to reproduce

Create a Fragment with react native screens
Create an activity with react native screens
Navigate back and forth between these two will cause this crash

### Snack or a link to a repository

https://stackoverflow.com/help/mcve

### Screens version

3.8.0

### React Native version

0.69.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

Android emulator

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @swiggyrahulgupta5,
first thing to try is testing out more recent `react-native-screens` version.
Besides that providing a repo with reproduction would be of massive value to help resolve this issue.

**Comment by adnansudozai** [comment]
@swiggyrahulgupta5 can you solve this issue i have face this issue to on Samsung devices

**Comment by gkasireddy202** [comment]
Facing same issue on react-native:0.73.7

**Comment by mostafahpater** [comment]
Add this to your MainActivity.java if you are using java in your react native 
`
import android.os.Bundle;

@Override
    protected void onCreate(Bundle savedInstanceState) {
       super.onCreate(null);
   }
`
or add this to your MainActivity.kt if you are using Kotlin in your react native 
`
import android.os.Bundle
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(null)
}

`

**Comment by mostafahpater** [comment]
Add this to your MainActivity.java if you are using java in your react native

import android.os.Bundle;
@Override
protected void onCreate(Bundle savedInstanceState) {
super.onCreate(null);
}

or add this to your MainActivity.kt if you are using Kotlin in your react native

import android.os.Bundle
override fun onCreate(savedInstanceState: Bundle?) {
super.onCreate(null)
}

**Comment by gkasireddy202** [comment]
@mostafahpater - Thanks for your reply.
Can I add the code in the below file path right?
import android.os.Bundle
override fun onCreate(savedInstanceState: Bundle?) {
super.onCreate(null)
}

Appname>android>app>src>main>java>com>MyApp>MainActvity.kt

**Comment by mostafahpater** [comment]
@gkasireddy202 
yes this is path of file and add import up of page and add fun inside (class MainActivity )

**Comment by FaithChinonso** [comment]
> @mostafahpater - Thanks for your reply. Can I add the code in the below file path right? import android.os.Bundle override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(null) }
> 
> Appname>android>app>src>main>java>com>MyApp>MainActvity.kt

did this work for you?

**Comment by gkasireddy202** [comment]
I tested this fix on Pixel 8 and did not face this issue on Pixel 8.

**Comment by Andreibv** [comment]
> Add this to your MainActivity.java if you are using java in your react native
> 
> import android.os.Bundle; @ Override protected void onCreate(Bundle savedInstanceState) { super.onCreate(null); }
> 
> or add this to your MainActivity.kt if you are using Kotlin in your react native
> 
> import android.os.Bundle override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(null) }

Let me try with this solution.

**Comment by babarbahadur** [comment]
This fixed the app crash but when user opens the app by clicking the push notification then redirection does not works. This is probably because we initialised it with null. Any suggestions on how to fix it?

**Comment by siddhantkazam** [comment]
> This fixed the app crash but when user opens the app by clicking the push notification then redirection does not works. This is probably because we initialised it with null. Any suggestions on how to fix it?

did you find the fix for the issue?

**Comment by babarbahadur** [comment]
> > This fixed the app crash but when user opens the app by clicking the push notification then redirection does not works. This is probably because we initialised it with null. Any suggestions on how to fix it?
> 
> did you find the fix for the issue?

unfortunately no :/

**Comment by Titmdeveloper** [comment]
> > > This fixed the app crash but when user opens the app by clicking the push notification then redirection does not works. This is probably because we initialised it with null. Any suggestions on how to fix it?
> > 
> > 
> > did you find the fix for the issue?
> 
> unfortunately no :/

Couldn’t you solve this with another solution?

**Comment by kkafar** [comment]
Guys, we've updated installation steps of the library, please check them out - they should help to resolve the issue: https://github.com/software-mansion/react-native-screens?tab=readme-ov-file#android

**Comment by siddhantkazam** [comment]
Can anyone confirm if this solved this issue, for both app crash and navigation from push notifications?

> Guys, we've updated installation steps of the library, please check them out - they should help to resolve the issue: https://github.com/software-mansion/react-native-screens?tab=readme-ov-file#android
