### ISSUE TITLE
[ANDROID TV] Focus gets lost between page transitions

### ISSUE THREAD

**Issue by yusufyildirim** [software-mansion/react-native-screens#1706]
### Description

Focus management is very important for TV applications and there's this big problem that has been hurting `react-native-tvos` community [for a long time](https://github.com/react-native-tvos/react-native-tvos/issues/237).

TV app users typically navigate around the UI items using their remote's d-pad. On every d-pad action, the currently focused element changes on the screen. It's crucial to restore the focus when user navigates to a different screen and then comes back to the previous one. Users should always continue their journey where they left off.

I'm assuming due to  working principles `react-native-screens`, Android loses the track of last focused element and hence can not recover the focus natively. As a result, a new focus search begins on every page transition and focus gets lost. Here's how it looks:

https://user-images.githubusercontent.com/22980987/215900717-12ae4e2e-5ab6-4d5b-95a3-ec5883209a23.mov

As can be seen on the screen recording, I navigate to a screen by triggering `onPress` action of the `(4) Text input example` -- I'll call it Button 4 -- button. Later, I come back to the previous screen using the back button. Since `Button 4` was the last element that had the focus on the previous screen, it should regain the focus when we navigate back.

Here's the expected behavior:

https://user-images.githubusercontent.com/22980987/215901324-91542862-c8d0-43e5-a56f-cb8a0c77c701.mov

### Steps to reproduce

1. Clone https://github.com/yusufyildirim/TVInputDemo/tree/focus-bug-repro repo
2. Run the app using `yarn android` command
3. Focus one of the elements on the screen and press enter to navigate to another screen
4. Come back to previous screen
5. See the focus is lost

### Snack or a link to a repository

https://github.com/yusufyildirim/TVInputDemo/tree/focus-bug-repro repo

### Screens version

3.18.2

### React Native version

0.69.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

Android emulator

### Acknowledgements

Yes

**Comment by yusufyildirim** [comment]
Here I have a potential solution: https://github.com/douglowder/TVInputDemo/pull/1

Only check the [patch file](https://github.com/douglowder/TVInputDemo/pull/1/files#diff-770b24a528477af8fa115e7fcf129f1f0dc3a39c96a67eb29e7b989e0b64ad64), the rest is unrelated to `react-native-screens` 😄

**Comment by kkafar** [comment]
@yusufyildirim, 
Android TV is not one of our directly supported platforms, but unless your patch causes some issues on Android, I think we can try to integrate it. I'll be back with more info after I play around with this patch.

**Comment by matias-sandell** [comment]
Would love to see this fix in react-native-screens! Have you had time to check it yet @kkafar?

**Comment by ROG3R-DEV** [comment]
I am also waiting for this problem to be fixed.

**Comment by josefnorlin** [comment]
We're patching this in and have for a couple of months now. Works great!

Is there any way we can get this approved?

**Comment by tboba** [comment]
Hi @yusufyildirim, thank you for this PR! Sorry for late feedback 😅 

I've just tested your patch file and it looks awesome! However, while I was testing those changes on Android it seems that there is also a `focused` state on mobile devices 🤔

https://github.com/software-mansion/react-native-screens/assets/23281839/579d947b-3bac-4c1f-9ac8-84b72273206f

I achieved changing this state with buttons on keyboard - I'm still not sure how can I switch between focused elements by touching. I'll block selecting last focused child in non-TV devices for now, but It's worth discussing if the focused state should be also saved on the phones. I'll open PR with this patch shortly ✌️

**Comment by yusufyildirim** [comment]
@tboba Thank you very much! I was thinking this could be a problem for TalkBack mode (even though I'm not sure how it works, though) but I forgot keyboards, controllers etc is a thing on mobile devices, so is `focus`. Thanks for the update 😄

**Comment by tboba** [comment]
Hey @yusufyildirim @matias-sandell @ROG3R-DEV @josefnorlin, just a quick announcement - the PR with this change has been merged to main and will land in the newest version of react-native-screens! Stay tuned 🎉

**Comment by tboba** [comment]
Hi @yusufyildirim @matias-sandell @ROG3R-DEV @josefnorlin, there's a new version of react-native-screens: 3.26.0 which has this change included. Check it out! If you find something wrong related to the newest version (this change is still buggy or doesn't work for you) let us know 🎉

**Comment by matias-sandell** [comment]
Awesome, will take it for a spin! Great work @yusufyildirim and @tboba! 🥇

**Comment by micheleb** [comment]
Hey there 👋🏻 
It looks like there's been a regression since this PR was merged.
The fix is a tiny diff:

<details>
<summary>react-native-screens+4.4.0.patch</summary>

```diff
diff --git a/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt b/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
index b11a19f..dfcac58 100644
--- a/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
+++ b/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt
@@ -478,6 +478,11 @@ class ScreenStackFragment :
         screen.background = shape
     }
 
+    override fun onStart() {
+        lastFocusedChild?.requestFocus()
+        super.onStart()
+    }
+
     override fun onStop() {
         if (DeviceUtils.isPlatformAndroidTV(context)) {
             lastFocusedChild = findLastFocusedChild()
```
</details>

Would that require a fully-fledged PR with repro repo as well? If it does, I can create one in the next few weeks. If it's ok to skip the repro and just link this PR, I have [a fork](https://github.com/micheleb/react-native-screens) ready.

Thanks!

**Comment by kkafar** [comment]
@micheleb thanks for taking your time to fix this. Just open the PR & link this issue. T
