### ISSUE TITLE
Task :react-native-screens:compileReleaseKotlin FAILED

### ISSUE THREAD

**Issue by Gabotron-ES** [software-mansion/react-native-screens#1716]
### Description

When doing a gradlew clean assembleRelease to get .aab file of my react-native appI get the following:

```
> Task :react-native-screens:compileReleaseKotlin FAILED
e: org.jetbrains.kotlin.util.KotlinFrontEndException: Exception while analyzing expression in (15,47) in C:/xampp/htdocs/WOO!/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/SearchViewFormatter.kt

Attachments:
causeThrowable
java.io.FileNotFoundException: C:\xampp\htdocs\WOO!\node_modules\react-native-screens\android\build\intermediates\compile_r_class_jar\release\R.jar!/node_modules/react-native-screens/android/build/intermediates/compile_r_class_jar/release/R.jar!/com/swmansion/rnscreens/R.class
```

And:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
```

It seems .jar file seems missing, this started happening after I changed my app package name (I think...)

I tried upgrading kotlin version to 1.8.0 inside build.gradle but still getting the same error.
```
kotlinVersion = "1.8.0" //added this inside ext
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0" //added this inside dependencies
```

My package.json file
```
"react-native": "0.68.5",
"react-native-screens": "^3.19.0"
```

I have been stuck with this for a while, I can't uninstall react-native-screens library since react-narive-navigation has a dependency on it (it seems)

### Steps to reproduce

1. Changed package name of my app from com.appname tp com.enterprisename.packagename
2. did a gradlew clean assembleRelease to get .aab file
3. App fails to build when it gets to react-native-screens (error seems to be related to kotlin)

### Snack or a link to a repository

https://stackoverflow.com/questions/75404806/react-native-cant-get-release-bundle-because-react-native-screens-kotlin-error

### Screens version

3.19.0

### React Native version

0.68.5

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hi, @Gabotron-ES, 
would you mind checking out 
```
kotlinVersion = "1.6.21"
``` 
(same version for Kotlin Gradle Plugin)

This is the version we use inside the library and test with. 

Moreover you should definitely try out standard approach - reinstall the dependencies: `rm -fr node_modules yarn.lock && yarn install` and then try to build.

I've tried to build `react-native-screens` with `react-native@0.68.5` and it seems to be working fine. This indicates that this is likely some misconfiguration on your side.

To be able to help you in more concrete wat I would need a repository with a reproduction.

**Comment by Gabotron-ES** [comment]
Tried it but getting the same error:

```
e: org.jetbrains.kotlin.util.KotlinFrontEndException: Exception while analyzing expression at (15,47) in C:/xampp/htdocs/WOOO!/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/SearchViewFormatter.kt

Attachments:
expression.kt
R.id.search_src_text
        at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.logOrThrowException(ExpressionTypingVisitorDispatcher.java:253)
        at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.lambda$getTypeInfo$0(ExpressionTypingVisitorDispatcher.java:224)
```

It happens after I change package name of app, followed this tutorial:

https://classnstudy.com/how-to-rename-app-and-change-package-name-in-react-native-for-android/

**Comment by kkafar** [comment]
@Gabotron-ES, do you think it is possible for you to provide a reproduction of this issue? It is rather hard to guess what is unusual about your setup, especially that I have not encountered this issue earlier.

**Comment by wdospinal** [comment]
I had a similar screens:compileReleaseKotlin failure with:

react-native-screens@3.22.0
react-native@0.71.7
ext.kotlinVersion = '1.8.21'
Bumping to Kotlin to 1.8.21 resolved this for me.I had a similar screens:compileReleaseKotlin failure with:

**Comment by Abdelazeem777** [comment]
Any Solutions?

**Comment by Sameer-Ijaz** [comment]
I had same issue when compiling android, I solved it by this method https://www.youtube.com/watch?v=7Fhp_1ZxQeg&ab_channel=SgtSam

**Comment by ahmed-raza12** [comment]
if it happened after name change go to mainactivity,kt mainapplication.kt and at top change your old package name with new one. it should resolve the problem. also update react-native rename global pkg so you dont face this problem again

**Comment by sampriti026** [comment]
Hey I solved this issue by upgrading the react-native-screens, i think it was the conflict in the kotlin version mentioned in the build.gradle under node moduls -> react-native-screens-> android and the one i was using in the build.gradle of the root project. (that is android -> build.gradle).

**Comment by RobertSavage** [comment]
After days and days of trying everything. I just decided to do this and it fixed the problem.

**Steps to fix:**
I deleted my android folder.
Created a new temp react native project
copied the new android folder over

**Ran these commands to rename everything:**
sudo npm install -g react-native-rename
react-native-rename "{project name}"        
react-native-rename "{project name}" -b com.{project name}.{project name}

**Comment by jerome-Dh** [comment]
> rm -fr node_modules

Thank you
Doing this worked for me

`rm -fr node_modules package-lock.json && npm install`

**Comment by jerome-Dh** [comment]
> Hey! 👋
> 
> This is the version we use inside the library and test with.
> 
> Moreover you should definitely try out standard approach - reinstall the dependencies: `rm -fr node_modules yarn.lock && yarn install` and then try to build.
> 

**Thank you**
Doing this worked for me

rm -fr node_modules package-lock.json && npm install

**Comment by Namnp1521** [comment]
> > Hey! 👋
> > This is the version we use inside the library and test with.
> > Moreover you should definitely try out standard approach - reinstall the dependencies: `rm -fr node_modules yarn.lock && yarn install` and then try to build.
> 
> **Thank you** Doing this worked for me
> 
> `rm -fr node_modules package-lock.json && npm install`

it work!

**Comment by albertonsc** [comment]
Estava atuando em um projeto expo 48, que estava gerando build com android 33, precisava alterar o android para 34 e estava obtendo esse erro ao buildar. Com a alteração do kotlinVersion de 1.8.10 obtive sucesso. Tanto a alteração do kotlinVersion  para 1.0.21 quanto para 1.6.21 foram bem sucedidas.

"react-native": "0.71.14";
"Expo":  "~48.0.21";
"react-native-screens": "^3.34.0";

**Comment by ReddyyZ** [comment]
> if it happened after name change, go to mainactivity,kt mainapplication.kt files and at top change your old package name with new one. it should resolve the problem. also update react-native rename global pkg so you dont face this problem again

While I was updating my Expo SDK from 49 to 50 I had to change from java to kotlin and I forgot to change my package name, this solved my issue.

Thanks!

**Comment by tiagopazhs** [comment]
> Estava atuando em um projeto expo 48, que estava gerando build com android 33, precisava alterar o android para 34 e estava obtendo esse erro ao buildar. Com a alteração do kotlinVersion de 1.8.10 obtive sucesso. Tanto a alteração do kotlinVersion para 1.0.21 quanto para 1.6.21 foram bem sucedidas.
> 
> "react-native": "0.71.14"; "Expo": "~48.0.21"; "react-native-screens": "^3.34.0";

None of these Kootin versions worked in my case:

    "expo": "~46.0.19",
    "react-native": "0.69.6",
 "react-native-screens": "~3.15.0",

**Comment by Samama-Zargham** [comment]
This version helped for me to resolve this isuue after 8 hours 🤍❤️

    "react-native-screens": "3.27.0",

**Comment by Buddhaa97** [comment]
> 3.27.0

This worked, thanks

**Comment by thearvindgehlod** [comment]
Run this command in your terminal

cd android
// to check if there are any deamon running.

./gradlew --status or .\gradlew --status
./gradlew --stop
./gradlew clean
cd ..
// then restart the server

**Comment by rajivchaulagain** [comment]
This problem is related to the mismatch version of kotlin during release of your app like during compilation of your app the kotlin version for package react-native-screen is not matched with your build configuration kotlin verify that first.
also most the solution might be one of this,
1. Mismatch kotlinVersion in buildscript, 
2. React native screen package is not using the kotlinVersion which we added in our buildscript
3. @react-native/gradle-plugin package also might not have mismatch version for kotlinVersion
