### ISSUE TITLE
 warning: 'RCTEventEmitter' is deprecated. Deprecated in Java import com.facebook.react.uimanager.events.RCTEventEmitter

### ISSUE THREAD

**Issue by CurpraCode** [software-mansion/react-native-screens#1759]
### Description

 warning: 'RCTEventEmitter' is deprecated. Deprecated in Java
import com.facebook.react.uimanager.events.RCTEventEmitter
I added this code to improve the UI screen navigation
  if (Platform.OS === 'android') {
    if (UIManager.setLayoutAnimationEnabledExperimental) {
      UIManager.setLayoutAnimationEnabledExperimental(true);
    }
  }

### Steps to reproduce

1. I am currently using react-native 0.71, "react-native-screens": "^3.20.0",  "@react-navigation/native": "^6.1.5",
    "@react-navigation/native-stack": "^6.9.11",
 

### Snack or a link to a repository

https://github.com/Peak-Pay/peakpay-reactnative-app

### Screens version

3.20.0

### React Native version

0.71.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Redmi Note 11 pro

### Acknowledgements

Yes

**Comment by latobibor** [comment]
**Link to GitHub repository:**
https://github.com/latobibor/react-native-gesture-handler-build-warnings-repro

**Minimal reproduction:**
1. Run to get the latest virgin `react-native`: `npx react-native init GestureHandlerDeprecatedWarnings`
2. Run `yarn add react-native-screens`
3. Run `npm run android`

It results in a _huge_ amount of warnings during build.

Reproducible with version `0.69.9` as well.

**Comment by CurpraCode** [comment]
Hello, please who is looking into this

**Comment by hassanharoon321** [comment]
does anyone solve this issue
