### ISSUE TITLE
Shared element transition stops working when you push a screen on top of tabs screen

### ISSUE THREAD

**Issue by hamdij0maa** [software-mansion/react-native-screens#1763]
### Description

Shared element transition stops working when you push a screen on top of tabs screen

### Steps to reproduce

Shared element transition stops working when you push a screen on top of tabs screen

### Snack or a link to a repository

https://gist.github.com/hamdij0maa/e594c15f071692f890f72df8a7f5d6e0

### Screens version

3.20

### React Native version

0.71.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 Pro

### Acknowledgements

Yes

**Comment by hamdij0maa** [comment]
I have a native stack on top of a tabs navigator, 
once the native stack is rendered, the shared transition won't work again.

**Comment by kkafar** [comment]
Hey, the repro you provided is not really prepared to be run by and what's more important it seems to me that this issue should be brought to attention of `reanimated` team as it is `reanimated` who is responsible for SET behaviour (if there any changes required in `screens` side I'm sure the reanimated team will let me know internally).

However most important thing is a valid reproduction.
