### ISSUE TITLE
NullPointerException - LifecycleRegistry.removeObserver

### ISSUE THREAD

**Issue by sregg** [software-mansion/react-native-screens#1776]
### Description

We're getting a few NPE in our app in prod.

```
NullPointerException
Parameter specified as non-null is null: method androidx.lifecycle.LifecycleRegistry.removeObserver, parameter observer
```

<img width="899" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/1479283/2a721e30-1b62-4250-ae68-602bd9102782">

Searching for `removeObserver` in our entire project returns only this line in `react-native-screens`:
https://github.com/software-mansion/react-native-screens/blob/6272e448afce5a112d1ddffc3cc146a453738be5/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.kt#L46

### Steps to reproduce

We can't seem to reproduce.
It seems to be happening only on Android. Maybe on app start (we don't see any breadcrumbs in Sentry).

### Snack or a link to a repository

Couldn't repro in snack.

### Screens version

3.18.2

### React Native version

0.71.8

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Redmi Note 9 Pro Max - Android 11

### Acknowledgements

Yes

**Comment by AZIMAT** [comment]
@sregg do you find any solutions?

**Comment by sregg** [comment]
I'm gonna do a patch using patch-package today and see if that fixes it.
I'll submit a PR if that helps.

**Comment by AZIMAT** [comment]
> I'm gonna do a patch using patch-package today and see if that fixes it. I'll submit a PR if that helps.

`
fun <T> unregister(view: T) where T : View, T : LifecycleObserver? {
        if(view != null) {
            mViewToLifecycleMap[view]?.removeObserver(view)
        }
    }
`
I'm going to check this line of code.

**Comment by AZIMAT** [comment]
> I'm gonna do a patch using patch-package today and see if that fixes it. I'll submit a PR if that helps.

May I have your patch?

**Comment by sregg** [comment]
> > I'm gonna do a patch using patch-package today and see if that fixes it. I'll submit a PR if that helps.
> 
> `
> fun <T> unregister(view: T) where T : View, T : LifecycleObserver? {
>         if(view != null) {
>             mViewToLifecycleMap[view]?.removeObserver(view)
>         }
>     }
> `
> I'm going to check this line of code.
> 

That was my plan for the patch

**Comment by AZIMAT** [comment]
> > > I'm gonna do a patch using patch-package today and see if that fixes it. I'll submit a PR if that helps.
> > 
> > 
> > `fun <T> unregister(view: T) where T : View, T : LifecycleObserver? { if(view != null) { mViewToLifecycleMap[view]?.removeObserver(view) } }`
> > I'm going to check this line of code.
> 
> That was my plan for the patch

Please share your patch result.

**Comment by sregg** [comment]
Here's the patch:

```diff
diff --git a/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.kt b/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.kt
index 41bfc80..5925472 100644
--- a/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.kt
+++ b/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.kt
@@ -43,6 +43,9 @@ class LifecycleHelper {
     }
 
     fun <T> unregister(view: T) where T : View, T : LifecycleObserver? {
+        if (view == null) {
+            return
+        }
         mViewToLifecycleMap[view]?.removeObserver(view)
     }
```

**Comment by AZIMAT** [comment]
@sregg I have this issue in sentry again.

**Comment by sregg** [comment]
Even after that patch?

**Comment by AZIMAT** [comment]
> Even after that patch?

Yeap.

**Comment by matous94** [comment]
I have the same problem, but my react-native-screen version (3.20.0) doesn't contain the file you patched anymore or any other removeObserver call. There are removeObserver calls in other dependencies though. Mostly expo libraries in my case. I tried to patch one suspicious file but it didn't work.

**Comment by AZIMAT** [comment]
@matous94 Can you reproduce this issue on a real device?

**Comment by matous94** [comment]
It actually happens only on real device, in preview/production build, which makes testing quite tedious, since it's not happening in Expo dev-client.

Also I just noticed the "Steps to reproduce" for this issue are different from mine. For me it happens when I call Updates.reloadAsync. I use it to reload app at logout, expired session token etc.

**Comment by AZIMAT** [comment]
@sregg RNScreen 3.2 doesn't contain the file that we patched yesterday. :|

**Comment by sregg** [comment]
Does that mean it's fixed?
I'll try it out

**Comment by AZIMAT** [comment]
> LifecycleObserver

Nope, I published with new version already and i have same issues in sentry.

**Comment by AZIMAT** [comment]
> Does that mean it's fixed? I'll try it out

Nope, I published on production with version 3.2.0 and i have same issues in sentry.

**Comment by matous94** [comment]
I just got the following, more detailed error message in dev in terminal after hot-reloading. I will look into it later, but it seems the error might be coming from sentry package? Possibly the same issue

`java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.lifecycle.LifecycleRegistry.removeObserver, parameter observer
  androidx.lifecycle.LifecycleRegistry.removeObserver(Unknown Source:3)
  io.sentry.android.core.AppLifecycleIntegration.removeObserver(AppLifecycleIntegration.java:112)
  io.sentry.android.core.AppLifecycleIntegration.lambda$close$1$io-sentry-android-core-AppLifecycleIntegration(AppLifecycleIntegration.java:123)
  io.sentry.android.core.AppLifecycleIntegration$$ExternalSyntheticLambda0.run(Unknown Source:2)
  android.os.Handler.handleCallback(Handler.java:942)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loopOnce(Looper.java:201)
  android.os.Looper.loop(Looper.java:288)
  android.app.ActivityThread.main(ActivityThread.java:7898)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)`

**Comment by sregg** [comment]
Thanks @matous94 
Looks promising: https://github.com/getsentry/sentry-java/issues/2675.
Closing ticket.

**Comment by DiorAbjalilov** [comment]
> I have this issue too, We can't reproduce it. but some users were affected after updating compile SDK to 33.

I also have sdk 33. how can I solve this problem
