### ISSUE TITLE
[0.72.0-rc.5] Event: you must return a valid, non-value from `getEventData`

### ISSUE THREAD

**Issue by tomekzaw** [software-mansion/react-native-screens#1778]
### Description

The following error appears when using react-native-screens@3.20.0 with react-native@0.72.0-rc.5 with Fabric enabled:

<img width="479" alt="Zrzut ekranu 2023-06-1 o 20 16 30" src="https://github.com/software-mansion/react-native-screens/assets/20516055/d9733fbe-812f-4c46-98a5-7826c1953939">

The root cause is that react-native-screens sends an event with name `onAttached` with `null` payload which apparently is no longer supported.

### Steps to reproduce

1. Run FabricExample app.

### Snack or a link to a repository

https://github.com/software-mansion/react-native-reanimated/tree/%40tomekzaw/72rc5

### Screens version

3.20.0

### React Native version

0.72.0-rc.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by cortinico** [comment]
yeah that's most likely the cause

**Comment by kmagiera** [comment]
ccing @WoLewicki – will you have some time to look into this one?

**Comment by WoLewicki** [comment]
Could you take a look if https://github.com/software-mansion/react-native-screens/pull/1783 fixes the issue?

**Comment by tomekzaw** [comment]
@WoLewicki Works like a charm. 👏 

Closing this issue as it was fixed in #1783 and released in 3.21.0.
