### ISSUE TITLE
createNativeStackNavigator crashing with 'reset' action.

### ISSUE THREAD

**Issue by KestasVenslauskas** [software-mansion/react-native-screens#178]
I have 2 screens: Home & Settings.
When I am at settings screen I'm trying to go back using StackActions.reset
This crashes app on Android.

`java.lang.IllegalStateException: ScreenContainer is not attached under ReactRootView
        at com.swmansion.rnscreens.ScreenContainer.findRootFragmentActivity(ScreenContainer.java:93)`

**Comment by uqmessias** [comment]
@KestasVenslauskas, did you get any progress on this issue?
I'm having a similar problem with my StackNavigator and don't have idea of how to solve it.

My Navigator is something like the following:

```jsx
import 'react-native-gesture-handler';
import { useScreens } from 'react-native-screens';
import createAnimatedSwitchNavigator from 'react-navigation-animated-switch';

import Login from './routes/Login';
import Splash from './routes/SplashScreen';

import transition from './transition';

useScreens();

const HomeNavigator = createStackNavigator(
  {
    'Page1': Page1,
    'Page2': Page2,
  },
  {
    headerMode: 'none',
    initialRouteName: 'Page1',
  },
);


const AppNavigator = createAnimatedSwitchNavigator(
  {
    'SplashScreen': Splash,
    'Login': Login,
    'Home': HomeNavigator,
  },
  {
    initialRouteName: 'SplashScreen',
  },
);

export default AppNavigator;
```

Inside `SplashScreen`, there is a validation whether the user is logged in or not and the user goes to `Home` if he's logged in. From that, the user can log out (`navigation.navigate('Login')`), but it crashes the app.

Do you, or anyone else, have a way to solve that issue without disabling the `react-native-screens`?

**Comment by WoLewicki** [comment]
Does the issue still persist in the newest version? If so, can you provide a repo with minimal configuration needed to reproduce the issue?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
