### ISSUE TITLE
RN 0.72.1 use_frameworks fix for pod spec

### ISSUE THREAD

**Issue by billnbell** [software-mansion/react-native-screens#1826]
### Description

`react-native-screens+3.22.1.patch` fix for new arch and 0.72.1 

Test with `cd ios && NO_FLIPPER=1 USE_FRAMEWORKS=static RCT_NEW_ARCH_ENABLED=1 pod install --repo-update && cd .. && yarn ios`

```
diff --git a/node_modules/react-native-screens/RNScreens.podspec b/node_modules/react-native-screens/RNScreens.podspec
index 60b368e..b61f26c 100644
--- a/node_modules/react-native-screens/RNScreens.podspec
+++ b/node_modules/react-native-screens/RNScreens.podspec
@@ -4,8 +4,6 @@ package = JSON.parse(File.read(File.join(__dir__, "package.json")))
 
 fabric_enabled = ENV['RCT_NEW_ARCH_ENABLED'] == '1'
 
-folly_compiler_flags = '-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -Wno-comma -Wno-shorten-64-to-32'
-
 Pod::Spec.new do |s|
   s.name         = "RNScreens"
   s.version      = package["version"]
@@ -20,34 +18,14 @@ Pod::Spec.new do |s|
   s.platforms    = { :ios => "9.0", :tvos => "11.0" }
   s.source       = { :git => "https://github.com/software-mansion/react-native-screens.git", :tag => "#{s.version}" }
 
+  s.source_files    = "ios/**/*.{h,m,mm,swift}"
+  s.requires_arc    = true
+  install_modules_dependencies(s)
   if fabric_enabled
-    s.pod_target_xcconfig = {
-      'HEADER_SEARCH_PATHS' => '"$(PODS_ROOT)/boost" "$(PODS_ROOT)/boost-for-react-native"  "$(PODS_ROOT)/RCT-Folly"',
-      "CLANG_CXX_LANGUAGE_STANDARD" => "c++17",
-    }
-    s.platforms       = { ios: '11.0', tvos: '11.0' }
-    s.compiler_flags  = folly_compiler_flags + ' ' + '-DRCT_NEW_ARCH_ENABLED'
-    s.source_files    = 'ios/**/*.{h,m,mm,cpp}'
-    s.requires_arc    = true
-  
-    s.dependency "React"
-    s.dependency "React-RCTFabric"
-    s.dependency "React-Codegen"
-    s.dependency "RCT-Folly"
-    s.dependency "RCTRequired"
-    s.dependency "RCTTypeSafety"
-    s.dependency "ReactCommon/turbomodule/core"
-  
     s.subspec "common" do |ss|
       ss.source_files         = "common/cpp/**/*.{cpp,h}"
       ss.header_dir           = "rnscreens"
       ss.pod_target_xcconfig  = { "HEADER_SEARCH_PATHS" => "\"$(PODS_TARGET_SRCROOT)/common/cpp\"" }
     end
-  else 
-    s.source_files = "ios/**/*.{h,m,mm}"
-    s.requires_arc = true
-  
-    s.dependency "React-Core"
-    s.dependency "React-RCTImage"
   end
 end
```

### Steps to reproduce

See above

### Snack or a link to a repository

none

### Screens version

3.22.1

### React Native version

0.72.1

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hi @billnbell, would you mind describing what the issue is?

**Comment by tboba** [comment]
Hi @billnbell, as we didn't received any response for the past two weeks, we cannot provide any help for your issue.
If you think the problem should still be considered, please fill in appropriate steps to reproduce with [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

Thank you 👍

**Comment by Srpalkn** [comment]
@tboba hi I've faced with ‘react/debug/react_native_expect.h' file not found issue after upgrading React Native to 0.72.3 and installing pods with USE_FRAMEWORKS=static RCT_NEW_ARCH_ENABLED=1. This patch seems to fix that issue. My react-native-screens version is 3.22.1. I can give you more info about my configs if you wish. 
Also you can check this discussion, seems like there will be a patch soon [https://github.com/facebook/react-native/issues/38188#issue-1788624311](url)

**Comment by billnbell** [comment]
Yeah it literally fixed the issues!!! :)

**Comment by tboba** [comment]
That's interesting 🤔 @billnbell if you think this issue occurs also in react-native-screens, would you mind creating a pull request with this patch? Have you also tested if this change is compatible with older versions of React Native and if it impacts old architecture?

**Comment by billnbell** [comment]
It does impact older RN. You need to only apply 
```
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))
 
fabric_enabled = ENV['RCT_NEW_ARCH_ENABLED'] == '1'
 
Pod::Spec.new do |s|
  s.name         = "RNScreens"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.description  = <<-DESC
                  RNScreens - first incomplete navigation solution for your React Native app
                   DESC
  s.homepage     = "https://github.com/software-mansion/react-native-screens"
  s.license      = "MIT"
  # s.license    = { :type => "MIT", :file => "FILE_LICENSE" }
  s.author       = { "author" => "author@domain.cn" }
  s.platforms    = { :ios => "9.0", :tvos => "11.0" }
  s.source       = { :git => "https://github.com/software-mansion/react-native-screens.git", :tag => "#{s.version}" }

  s.source_files    = "ios/**/*.{h,m,mm,swift}"
  s.requires_arc    = true

if fabric_enabled
  install_modules_dependencies(s)
else
  s.source_files = "ios/**/*.{h,m,mm}"
  s.dependency "React-Core"
  s.dependency "React-RCTImage"
end
```

**Comment by tboba** [comment]
After looking on it further I can say this change looks promising. However, as we discussed it with @kkafar we won't introduce that for now, as we want to keep control on the dependencies that are being injected.

However, we will consider replacing those lines in the future. Thanks for suggesting that! 🙏

**Comment by choijiho0021** [comment]
Of the 40 libraries I'm using, only this one specified the version in RCT-Folly, creating an error when installing New Arch
