### ISSUE TITLE
When using nested, native-stack navigators, a modal screen in the inner navigator cannot push a modal screen in the outer navigator

### ISSUE THREAD

**Issue by tpcstld** [software-mansion/react-native-screens#1829]
### Description

https://github.com/software-mansion/react-native-screens/assets/5456182/f8b58a06-4cbd-458d-9e46-387a10b54b0b

I admit that this wording is a little confusing but let me try to explain what's going on. This seems to affect iOS only.

In the demo snack, I expect to be able to launch the "outer modal" -- the screen with name `modal` -- in the outer navigator from any other screen in this app. For example:

* I can navigate to `modal` from the starting screen `home`.
* I can navigate to `modal` from the inner navigator base screen, `base`.

However, I am unable to navigate to `modal` from `inner-modal`.

This is unexpected because if I were to remove the `presentation: modal` from `inner-modal`, then `modal` would pop-up normally. In addition, if `inner-modal` were in the same navigator as `modal`, then it would work, as evidenced by `modal` being able to navigate to `modal-2.

In addition, after this occurs, nothing is able to launch `modal` anymore, including the buttons which worked before!

### Steps to reproduce

1. Open the snack; iOS simulator
2. Open the Inner Navigator
3. Open the Inner Modal
4. Try to open the Outer Modal from the Inner Modal
5. Observe that it does not work.

### Snack or a link to a repository

https://snack.expo.dev/fnbHe-IiWz

### Screens version

3.18.0

### React Native version

0.70.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

Paper

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @tpcstld, thanks for reporting this bug! I believe this issue could be related to #1813. Have you spotted similar behavior with freezing nested modals, or you cannot just perform actions there?

**Comment by tpcstld** [comment]
When I do nest modals (on the same navigator), the nested modals do seem to be working!
