### ISSUE TITLE
Animated.View issue with native-stack

### ISSUE THREAD

**Issue by DauMoe** [software-mansion/react-native-screens#1850]
### Description

I have a Nested list `Animated.View` (Have to use because of using animation in React Native) and I want to show overlap children.
Everything works fine without `native-stack`. You can see the repo for more detail. How can I do the expectation with `native-stack` wrapping? It's a bug or I miss something here
## Expected:
![expected](https://raw.githubusercontent.com/DauMoe/native_stack_issue/main/media/expected.png)
## Reality:
![un_expected](https://raw.githubusercontent.com/DauMoe/native_stack_issue/main/media/with_navigation.png)

### Update:
I changed to use `stack` instead `native-stack`. It works fine. Any idea about it, guys?

### Steps to reproduce

Starting application following React Native document
- Step 1: Setting the environment variable ORG_GRADLE_PROJECT_newArchEnabled=true
- Step 2: `yarn install` or `npm install`
- Step 3: `yarn android` or `npm run android`
- Step 4: change **withNavigator** value to see the different when using **react-navigation** and not

### Snack or a link to a repository

https://github.com/DauMoe/native_stack_issue

### Screens version

3.23.0

### React Native version

0.72.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Android 9 Pie TV 720p Emulator

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @DauMoe, we are here! 😃 
As I can see, you're testing this change on Android TV, which isn't currently supported by us, but if this issue also impacts standard Android we can try to fix it. Do you know if this issue also occurs there?

**Comment by DauMoe** [comment]
I just try to testing on Pixel 3 API 28 device and it's the same result. You can check images below
## With navigation:  
![with_navigation](https://raw.githubusercontent.com/DauMoe/native_stack_issue/main/media/stand_android_with_navigation.png)
## Without navigation:
![without_navigaiton](https://raw.githubusercontent.com/DauMoe/native_stack_issue/main/media/stand_android_without_navigation.png)

**Comment by tboba** [comment]
I'm also able to fix it by updating `@react-navigation/native` and `@react-navigation/native-stack` version to `6.9.14`. Because of that I'll close the issue for now, but if the problem still happens in your case don't hesitate to reopen this issue. Thanks! ❤️
