### ISSUE TITLE
Build error in macOS Catalyst. (Solution provided!) Cannot initialize a parameter of type 'BOOL' (aka 'signed char'

### ISSUE THREAD

**Issue by exotexot** [software-mansion/react-native-screens#1853]
### Description

I cannot build out of the box for catalyst using the latest version of rn-screens.

ERORR:

`Cannot initialize a parameter of type 'BOOL' (aka 'signed char') with an lvalue of type 'BOOL *const' (aka 'signed char *const')`

Using react-native 0.71.12.

The error is in RNSSearchBar.mm (Line 426):

`RCT_EXPORT_METHOD(toggleCancelButton : (NSNumber *_Nonnull)reactTag flag : (BOOL *)flag)
`
CHANGE INTO:

`RCT_EXPORT_METHOD(toggleCancelButton : (NSNumber *_Nonnull)reactTag flag : (BOOL)flag)`

### Steps to reproduce

build for macOS catalyst.

### Snack or a link to a repository

-

### Screens version

3.23.0

### React Native version

0.71.12

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Thanks for reporting. Once CI passes I'll merge the fix.
