### ISSUE TITLE
White screen when navigate screen with blurview - @react-native-community/blur

### ISSUE THREAD

**Issue by davidgvf** [software-mansion/react-native-screens#1882]
### Description

When navigate to screen use blurview, all screen is white

### Steps to reproduce
[Uploading screen-capture.webm…]()

Navigate to screen 
These screen have this code:
 return (
            <BlurView style={{ borderRadius: 16 }} blurAmount={18} overlayColor={'transparent'}>
                {props.children}
            </BlurView>
        );

In android 

### Snack or a link to a repository

a

### Screens version

3.24.0

### React Native version

0.72.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

None

### Device

Android emulator

### Device model

Pixel 7

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @davidgvf, out github bot makes some valid points. Marking it as stale and will close it shortly, unless proper reproduction is provided.

**Comment by davidgvf** [comment]
Hi @kkafar i updated with a video that reproduce de error

**Comment by kkafar** [comment]
Hey, 

1. The link does point to this exact issue not to any video resource
2. It would be much simpler if you provided us with snack / github repo with code on which I can reproduce the issue.

**Comment by segun-flexible** [comment]
if you check this link, you will see where they said it might misbehave when working with navigation
https://docs.expo.dev/versions/latest/sdk/blur-view/#known-issues

so my advice is not to use this package until they fix the issue of it not allowing us to navigate to other screen

**Comment by alduzy** [comment]
Related issue: https://github.com/software-mansion/react-native-screens/issues/1661

**Comment by vivek154** [comment]
Its because of transition animation while navigating.
You can use
screenOptions={{ animation:'none'}}
this config on stack navigator like below.

<RootStack.Navigator screenOptions={{ headerShown: false ,animation:'none'}}>
            <RootStack.Screen name={HOME_SCREEN} options={{ headerShown: false }} component={TabScreen} />
            <RootStack.Screen name={MY_PROFILE} options={{ headerShown: false }} component={ProfileScreen} />
 </RootStack.Navigator >
