### ISSUE TITLE
View config getter callback for component `RNSScreen` must be a function (received `undefined`).

### ISSUE THREAD

**Issue by AliYar-Khan** [software-mansion/react-native-screens#1901]
### Description

I am experiencing issue with version 3.22.0 

`View config getter callback for component `RNSScreen` must be a function (received `undefined`).`

### Steps to reproduce

1. add react navigation along with react native screen version 3.22.0 
2. gives the error

### Snack or a link to a repository

https://snack.expo.dev/@aliyark145/glopilot-aliyar-khan?platform=web

### Screens version

3.22.0

### React Native version

0.71.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @AliYar-Khan,
The issue is irreproducible on latest `react-native-screens` version (3.25.0). 
Please provide me with reproducible example (preferably github repo with application setup) & tag me -> I'll reopen the issue. 

Also please test this on latest `react-native-screens` version.

**Comment by AliYar-Khan** [comment]
Problem is expo sdk doesn't support that and it gives error on that version

**Comment by kkafar** [comment]
Oh, this gives me instant nudge that this might be Expo issue, but I'll look deeper into this then.

**Comment by AliYar-Khan** [comment]
thanks @kkafar

**Comment by AliYar-Khan** [comment]
@kkafar did you manage to get insight on this ?

**Comment by ludovic-noirault** [comment]
I reproduce the same behaviour on the up to date version (3.25.0) on TVos

```
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 47.08 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: 2023.09.18.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10811636
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 20.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.71.13-1
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by AliYar-Khan** [comment]
@nisam360 which version of React Native Screens you are using ?

**Comment by J-4-K-3** [comment]
I also got the same issue, it because of incorrect versions in the dependencies

{
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "react-native-paper": "4.9.2",
    "react-native-screens": "~3.20.0",
    "@react-navigation/native": "6.0.0",
    "@react-navigation/bottom-tabs": "^6.0.0",
    "react-native-safe-area-context": "4.5.0"
  }
}

Refer to those versions, and see if they help. Currently am using expo version 48.0.0 rather 49 because that version was causing a bit of frustration

**Comment by vivaan187** [comment]
@J-4-K-3 Thanks mate, I had the same issue but your solution helped me resolve it.

**Comment by Stefan13579** [comment]
Same Problem here. Before I had v47.0.0 it worked well and I saved a lot of data in my app. Know I get the error with v49.0.0. If I switch back to v47.0.0 no data are stored in the flat list. I get an empty app. This worries me a lot because there was a lot in it. 
Would be great if you could also help me. Here my dependencies.

{
  "dependencies": {
    "axios": "*",
    "expo-constants": "~14.4.2",
    "@expo/vector-icons": "^13.0.0",
    "react-native-paper": "4.9.2",
    "react-native-screens": "~3.22.0",
    "@react-navigation/stack": "*",
    "@react-navigation/native": "6.0.0",
    "react-native-toast-message": "2.1.6",
    "@react-native-picker/picker": "2.4.10",
    "react-native-dropdown-picker": "*",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-safe-area-context": "4.6.3",
    "@react-native-community/checkbox": "*",
    "@react-native-async-storage/async-storage": "1.18.2"
  }
}

**Comment by Stefan13579** [comment]
In the app v49.0.0 is shown no matter which version I safed in snack.expo.

**Comment by kkafar** [comment]
I've been trying to reproduce this issue right now & failed. Ping me if you still have this issue and are able to provide a reproduction.
