### ISSUE TITLE
Native Stack Navigator header sticks to bottom of screen when using headerBackground option

### ISSUE THREAD

**Issue by NikolaB131** [software-mansion/react-native-screens#1911]
### Description

Version of ```@react-navigation/native-stack``` is ```6.9.14```
When adding headerBackground option to Stack.Navigator or Stack.Screen header sticks to bottom.
Bug is on IOS and Android, Web version does not have bug.
There is no bug when switching to older version (```6.9.13```).
Appears with or without expo

### Steps to reproduce

1. Add headerBackground option to Stack.Navigator or Stack.Screen with any JSX Element (even <></>)
2. Header sticks to bottom of screen

### Snack or a link to a repository

https://snack.expo.dev/@nikolab131/header-sticks-to-bottom-of-screen

### Screens version

3.25.0

### React Native version

0.72.5

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung Galaxy A50 (Android 12)

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @NikolaB131, thanks for reporting this issue! Are you certain that this issue is reproducible on the non-expo environment? I've just tested your repro on the expo environment and non-expo environment and I can only reproduce it on the expo env 🤔

**Comment by NikolaB131** [comment]
Just tried reproduce issue on new bare React Native project. And issue reproduced. And again when i switched version of `@react-navigation/native-stack` to `6.9.13`, issue disappeared. Unfortunately i dont have mac, so i only can reproduce it on android.

![bug](https://github.com/software-mansion/react-native-screens/assets/69255437/3633c0cb-58d9-4b03-a89f-54a867f6b9b2)

**Comment by tboba** [comment]
@NikolaB131 thanks for the update! First thing that comes to my mind is that it could be the problem related directly to the `@react-navigation/native-stack`. Let me look on that - I'll keep you updated.

**Comment by ArnoldoJr** [comment]
Issue resolved for me on  `"@react-navigation/native-stack": "6.9.17",`

**Comment by NikolaB131** [comment]
> Issue resolved for me on `"@react-navigation/native-stack": "6.9.17",`

Yep, I just checked, issue gone on "6.9.17"

**Comment by tboba** [comment]
@ArnoldoJr @NikolaB131 Glad to hear that, thanks for confirming!
Cheers!
