### ISSUE TITLE
RefreshControl disappears when navigating from a screen with a custom header to a screen using headerLargeTitle.

### ISSUE THREAD

**Issue by Canciller** [software-mansion/react-native-screens#1914]
### Description

RefreshControl disappears when navigating from a screen with a custom header to a screen using headerLargeTitle.

https://github.com/software-mansion/react-native-screens/assets/39095957/77cc77c4-7baa-458c-be88-bb0d08317f75

### Steps to reproduce

1. Pull to refresh and RefreshControl is visible.
2. Navigate to a screen using headerLargeTitle.
3. Go back.
4. Pull to refresh and RefreshControl disappears.

### Snack or a link to a repository

https://github.com/Canciller/RefreshControlDisappearsBug

### Screens version

^3.25.0

### React Native version

0.72.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 Pro

### Acknowledgements

Yes

**Comment by deepanshushukla** [comment]
@Canciller How did  you resolve this?
