### ISSUE TITLE
RNSHeaderHeightChangeEvent: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by joseluismurillorios** [software-mansion/react-native-screens#1932]
### Description

With new architecture using stack navigator causes a crash, even the hello-react-navigation example is not working for me, if I let the Stack.Navigator component without any screens or a Stack.Screen outside a navigator I get errors but the app doesn't crash

[RNSHeaderHeightChangeEvent canCoalesce]: unrecognized selector sent to instance

![image](https://github.com/software-mansion/react-native-screens/assets/11035303/1bc8e2fb-44a1-4488-89ff-81dcd2f275fc)

System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 83.50 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: ~/.nvm/versions/node/v18.17.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.17.1/bin/yarn
  npm:
    version: 9.6.7
    path: ~/.nvm/versions/node/v18.17.1/bin/npm
  Watchman:
    version: 2023.10.09.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/username/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - iOS 17.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/username/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Steps to reproduce

1. `NO_FLIPPER=1 USE_FRAMEWORKS=static RCT_NEW_ARCH_ENABLED=1 pod install`
2. `react-native start --reset-cache`
3. Build and run the app

### Snack or a link to a repository

https://snack.expo.dev/@joseluismurillorios/vigorous-blue-yogurt

### Screens version

3.26.0

### React Native version

0.72.1

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by isinuyk** [comment]
+1
IOS only, new arch enabled
react-native 0.72.6
react-native-screens 3.26.0

On Android with the new arch, it works without crashing.

Downgrading to 3.25.0 fixes the problem for me.

**Comment by tboba** [comment]
Hey @joseluismurillorios, thanks for reporting this issue!
I think I've just found where's the problem - `RNSHeaderHeightChangeEvent` should have `canCoalesce` method. Strangely, I haven't met this error yet 🤔 

Will submit a PR with the change shortly 👍

**Comment by tboba** [comment]
@joseluismurillorios @isinuyk could you check if changes made in branch `@tboba/fix-cancoalesce-method` fixed your problem?

You can get the version with those changes with:
`yarn add software-mansion/react-native-screens#0466a9454b1b0ec5e86f312c428beaece07e6b8f`

**Comment by joseluismurillorios** [comment]
@tboba  Yes, those changes fixed the problem!

**Comment by tboba** [comment]
@joseluismurillorios thanks for the update! I think we will release the patch that includes that fix. Stay tuned 🙏

**Comment by tboba** [comment]
Hey @joseluismurillorios @isinuyk! Just wanna announce that we're released react-native-screens **3.27.0** which includes that fix! 🎉 
If you're still facing any problems in the newest version, don't hesitate to open a new issue 🙏 

Cheers!
