### ISSUE TITLE
Android bundle increase with almost 1mb after upgrade

### ISSUE THREAD

**Issue by tux2nicolae** [software-mansion/react-native-screens#1952]
### Description

After upgrading from 3.25.0 to 3.26.0 (same for 3.27.0) we noticed a big increase in our bundle size of almost 1mb

### Steps to reproduce

1. Install 3.25.0 check the bundle size
2. Install 3.26.0 (or 3.27.0) check the bundle size

### Snack or a link to a repository

https://github.com/software-mansion/react-native-screens/

### Screens version

3.26.0

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

None

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @tux2nicolae, thank you for creating this issue!

Between the `3.25.0` and `3.27.0` versions we've updated couple of libraries, which may indeed increase the bundle size, but they should not increase the size that much 🤔
I've just checked the differences between both versions and unfortunately in my case higher version does not differ from the `3.25` one. I can only observe 0.1mb increase in node_modules directory:

<img width="261" alt="Screenshot 2023-10-30 at 11 56 23" src="https://github.com/software-mansion/react-native-screens/assets/23281839/19475125-267d-4bc7-804d-83eb103a65f1">
<img width="260" alt="Screenshot 2023-10-30 at 11 57 01" src="https://github.com/software-mansion/react-native-screens/assets/23281839/e5f6c21a-fe20-40b3-88a4-8219fa5fe38f">

and for the final bundle size, import cost of `react-native-screens` is still relatively cheap.

![image](https://github.com/software-mansion/react-native-screens/assets/23281839/e6dc62b3-c803-4f99-bfa3-21338f35174c)

Can you show your measurements of how the bundle size looks like after updating the rn-screens version to the higher version?

**Comment by tux2nicolae** [comment]
Thank you for your response @tboba ,

Our application is an instant app on android which is limited to 15 MB in size, we monitor each library upgrade and it's size increase, that's how we notice it, below I've attached more information's regarding the size increase:

## Only making this change in package-lock.json results in size increase
![image](https://github.com/software-mansion/react-native-screens/assets/39991250/f5576123-1529-4f8d-8eb5-4dc9f7b39d48)

# With 3.25.0

### node_modules
![image](https://github.com/software-mansion/react-native-screens/assets/39991250/733413e3-c8d2-4eca-9610-24e7966525f0)

### react-native-screens (after building with `.\gradlew bundleRelease`)
![image](https://github.com/software-mansion/react-native-screens/assets/39991250/a9d4fcef-12df-4824-8687-c376c66dafca)

### bundle size
![image](https://github.com/software-mansion/react-native-screens/assets/39991250/228ed85e-c674-4200-b994-c3e33303318a)

# With 3.27.0

### node_modules
![image](https://github.com/software-mansion/react-native-screens/assets/39991250/dfca1da4-7201-4f17-9d68-8c4ff52fcb5c)

### react-native-screens after building with `.\gradlew bundleRelease`
![image](https://github.com/software-mansion/react-native-screens/assets/39991250/84976ec4-257c-46c5-bbf7-b5656cb87b15)

### bundle size
![image](https://github.com/software-mansion/react-native-screens/assets/39991250/41f40b31-fdfb-406e-ae9b-24eed82b7396)

-----------------------------------------------------------

This increase of bundle size also affects the application size in play console.

If I can help with more info, or anything else please let me know.

Thank you again!

**Comment by tboba** [comment]
@tux2nicolae thanks for the helpful screenshots! My first assumption is that the size increase may come from the changes adapted in #1891. As you can see, we've bumped a few libraries there, but also upgraded Kotlin version - that brings me to the question, do you have variable `kotlinVersion` declared in your build.gradle file? If so, what's the kotlin version you're declaring in your app?

**Comment by tux2nicolae** [comment]
@tboba thank you for your quick response, no I do not have a `kotlinVersion` declared, but thanks for the hint, I'll make a few tests and get back with my findings

**Comment by tux2nicolae** [comment]
Just found that `implementation 'com.google.android.material:material:1.9.0'` is the culprit, when using `1.1.0` version the size comes to normal. 

Is it safe for me to revert to `1.1.0` for now, or does `react-native-screens` has a hard dependency on the `1.9.0` version?

Thank you again for sorting this out!

p.s Changing the `kotlinVersion` doesn't seem to noticeable affect the size.

**Comment by tboba** [comment]
Yeah, so everything became brighter now 😄 
I believe this library (which adds a support for Material Design for Android) became heavier, as from version `1.5.0` it adds a support for Material 3. Between `1.5.0` and `1.9.0` there might be some changes, but at the time when we've bumped it, it was just the newest version. As long as you're not using Material 3 (which you may not, as React Native supports Material 2 by default) I think you're good to go with downgrading the version!

**Comment by tux2nicolae** [comment]
Thank you for confirming it,

Yes I understand the push regarding material 3, we actually have some extra free space up to 15mb limit, but just for now we can't justify it until we are forced to do so. Maybe in the future we'll try another solution to this, but until then we are ok with downgrading to `1.1.0`.

I'll also attach the patch here, if someone finds himself in the same situation.
 
[react-native-screens+3.27.0.patch](https://github.com/software-mansion/react-native-screens/files/13209254/react-native-screens%2B3.27.0.patch)

Thank you again for your time, and help!
