### ISSUE TITLE
Unknown Kotlin JVM target: 20

### ISSUE THREAD

**Issue by renishdeveloper** [software-mansion/react-native-screens#1953]
### Description

I'm using the package with react native project having react native version 0.72.6, I"m getting the error that is there in the below screenshot.
![image](https://github.com/software-mansion/react-native-screens/assets/40269099/d2d003ff-f8f7-48c9-a846-37758d7806d8)

### Steps to reproduce

1. Create react native project and install this package and run the project using npx react-native run-android.

### Snack or a link to a repository

not possible to share the repo

### Screens version

3.27.0

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @renishdeveloper, thanks for submitting this issue!

Unfortunately, this issue is not reproducible for me. I've created new project via `create-react-native-app`, I've added `react-native-screens` and tried `npx react-native run-android` - no issues there, the app is being built correctly.
My first assumptions is the wrong version of Java installed locally - in my case I'm using openjdk 11.0.20 from Zulu.
Also, do you have `jvmTarget` specified in your gradle files? If so, what is the version you're using in the project?

Cheers!

**Comment by indiademo** [comment]
Hi @tboba i am facing this issue in 2 application when i install react-native-screens

> Task :react-native-screens:compileReleaseKotlin FAILED

> Task :react-native-safe-area-context:compileReleaseKotlin
'compileReleaseJavaWithJavac' task (current target is 11) and 'compileReleaseKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
w: /Users/abhishekpathak/project/ui/RedRose/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaView.kt: (58, 23): 'getter for uiImplementation: UIImplementation!' is deprecated. Deprecated in Java

**Comment by mrtomhoward** [comment]
I struck this today after doing something completely unrelated to `react-native-screens`.  I installed `react-native-vision-camera` and `react-native-fs`, then started getting this error each time I tried to build even after I removed those libs (and yes, trashed `yarn.lock` and `node_modules/*`, reinstalled everything and ran `npx jetify` each time).

The thing that fixed it for me was commenting out `export JAVA_HOME=$HOME/OpenJDK/jdk-20.0.2.jdk/Contents/Home/` in my `.zshrc` file.

After that, for `java --version` I get `java 11.0.18`, and the builds work again.

Its' wierd that this suddenly came up, as I've had that OpenJDK version installed/used for a while and it was building fine as recently as yesterday.

**Comment by indiademo** [comment]
Hi @mrtomhoward ,

      Thanks for your response, i also yesterday downgrade my java version 20 to 11 and working fine for me also.

This is issue with latest java version.

**Comment by kkafar** [comment]
RN uses Java 11 on versions before 73 (or 72, I do not recall exactly), and 17 for later versions. We do not test for compatibility with Java 20.

**Comment by phgn0** [comment]
^ `brew uninstall java --ignore-dependencies && brew install java17` fixed this issue for me.
