### ISSUE TITLE
Not working with React Native 0.73 RC

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [software-mansion/react-native-screens#1961]
### Description

I am migrating the application to React Native 0.73.0-rc.4, while building the app I am getting C++ related issues for react-native-screens library.

### Steps to reproduce

Integrate react-native-screens with react native 0.73.0-rc.4

### Snack or a link to a repository

https://snack.expo.io/

### Screens version

3.27.0

### React Native version

0.73.0-rc.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @ravindraguptacapgemini, thanks for submitting this issue!
We're aware that react-native-screens might not work correctly (or even completely) on React Native 0.73 and we're doing our best to fix that! @kkafar is working on supporting this version in PR #1956. 

For now I'll close this issue, but don't hesitate to ask any questions there.
Cheers!

**Comment by krishnapythonprogrammer** [comment]
Hi @tboba  
See my application is breaking due to react-native -screen or updating to targetVersion set to 35 in old mobile app is working fine in new device itss building open and crash immediately
