### ISSUE TITLE
enableScreens(false) doesn't appear to work 

### ISSUE THREAD

**Issue by edsztukowski** [software-mansion/react-native-screens#1962]
### Description

I have experienced a bug noted here where hiding a bottom tab navigator with styles wouldn't work unless I set `enableScreens` to false. The bug is detailed here:
https://github.com/software-mansion/react-native-screens/issues/1366

Recently we updated from React Native 0.70.1 to 0.72.2 and I notice that setting `enableScreen(false)` no longer seems to fix the bug. I suspect it's possible that screens are no longer being disabled, because when I went and manually updated from native-screens stack to navigation stack, I was no longer seeing the issue.

### Steps to reproduce

The original ticket had a great snack demonstrating the issue, but it's only possible to see when running on a real device instead of expo: https://snack.expo.dev/@tarikfp/hide-bottom-bar-fails-on-ios?platform=ios

1. Create a Tab navigator with a set of native screens inside the tab. 
2. Dynamically hide the tab navigator for a specific screen. 
3. A gray space will still show
4. Set `enableScreens(false)` and ensure native screens are not being used. 

### Snack or a link to a repository

https://snack.expo.dev/@tarikfp/hide-bottom-bar-fails-on-ios?platform=ios

### Screens version

3.27.0

### React Native version

0.72.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Old arch

### Build type

Release mode

### Device

Real device

### Device model

iPhone 12 OS 17

### Acknowledgements

Yes

**Comment by edsztukowski** [comment]
Closing because I am incorrect, enableScreens false is working correctly, but it doesnt appear to fix the issue with hiding the bottom navigation anymore

**Comment by dogankablan** [comment]
@edsztukowski Did you solve your problem? How did you solve it? I have the same problem.

**Comment by edsztukowski** [comment]
Never solved it @dogankablan. We're still on an older rn version at the moment that doesn't have the issue. I hope they address it soon though because we're getting prepped to upgrade

**Comment by dogankablan** [comment]
@edsztukowski 
We've upgraded the software to the latest version and currently, we're dedicating all our time to resolving this issue. If we manage to fix the error, I'll inform you as well.
