### ISSUE TITLE
I am experiencing the same problem in iOS 17, both in the simulator and on the real device. Can you help to solve the problem?

### ISSUE THREAD

**Issue by Entireno** [software-mansion/react-native-screens#1965]
I am experiencing the same problem in iOS 17, both in the simulator and on the real device. Can you help to solve the problem?

_Originally posted by @Entireno in https://github.com/software-mansion/react-native-screens/issues/1570#issuecomment-1805623248_

**Comment by tboba** [comment]
Hey @Entireno, thank you for creating this issue. As library developers we value each issue, but unfortunately we cannot do much without appropriate steps to reproduction (including minimal repro). If you're experiencing the same issue as mentioned in the description, please create a new issue and fill the fields with appropriate description.

Thank you!
