### ISSUE TITLE
Taps often lost on Android real device + Fabric with header enabled

### ISSUE THREAD

**Issue by franksmule** [software-mansion/react-native-screens#1975]
### Description

On a real android device, with fabric enabled, taps are often lost when Header is shown on Native Stack.

On an Android emulator, iOS and even using a tool such as scrcpy taps are always registered, using real device and manually tapping is very inconsistent. Have seen across multiple phones.

### Steps to reproduce

1. Checkout `react-native-screens` repo
2. go to FabricExample folder
3. Change App.js to code in linked snack repo.
4. Run adb logcat | grep ReactNative
5. Use on **real** android device - notice how logs do not print '1111' with every tap (inconsistent) 
6. Change headerShown to `false` logs WILL print with every tap

### Snack or a link to a repository

https://snack.expo.dev/X06saJ53E

### Screens version

main

### React Native version

0.72.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Nokia TA-1234

### Acknowledgements

Yes

**Comment by franksmule** [comment]
To add some further findings:

TextInput has the same issue - taps are _sometimes_ ignored, the input does not get focus and no keyboard.

If I use `react-native-gesture-handler` RectButton, TextInput they **always** work. The `react-native` imports have the intermittent issues.

**Comment by dviluk** [comment]
Same for me, you need to tap on the top half of the pressable component to trigger the event. I switched to `@react-navigation/stack` for now.

**Comment by dviluk** [comment]
Does some know what is causing this?

**Comment by grgmo** [comment]
similar issue we're seeing with native stack on react native `0.73.2` only on Fabric Android real device where tap seems to get lost and no `onPress` callback on header component.

**Comment by yosukapro** [comment]
Any solution found for this?
