### ISSUE TITLE
hitSlop does not work inside in stack header

### ISSUE THREAD

**Issue by alexandernanberg** [software-mansion/react-native-screens#1981]
### Description

`hitSlop` does not work as expected in a Stack header

https://github.com/software-mansion/react-native-screens/assets/8997319/2c6fb0d0-c4c9-413d-8f13-dfa42c06674a

### Steps to reproduce

1. Add a `<Pressable>` to either `headerLeft` or `headerRight`
2. Set a `hitSlop`
3. Try to press on the hitSlop area and see the `onPress` cb isn't called

### Snack or a link to a repository

https://github.com/alexandernanberg/react-native-screens-repro

### Screens version

3.22.1

### React Native version

0.72.6

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Yeah, I can confirm the issue, thanks for reporting

**Comment by thomasttvo** [comment]
seeing this as well on `native-stack` navigation, @kkafar any idea how we can patch the library for a fix?

**Comment by kkafar** [comment]
@thomasttvo, checkout this PR: https://github.com/software-mansion/react-native-screens/pull/1995

**Comment by hirbod** [comment]
I can confirm that hitSlop indeed doesn't work in v4.4.0

**Comment by thomasttvo** [comment]
This works for our team on `3.32.0`. Perhaps the fix needs to be merged into v4.

**Comment by kkafar** [comment]
Pressables on Fabric were a subject of different issue. #2466 is supposed to fix that => this should longer be no problem since 4.6.0-beta.0 release (just released). Let me know in case you still encounter this issue.

**Comment by Jpoliachik** [comment]
Upgraded to v4.6.0 and it looks like Pressables do behave more consistently now in headerLeft, but it still doesn't look like `hitSlop` is working all of the time. In my case sporadic - hitSlop area works sometimes but not all of the time. Pretty strange actually, curious if others are seeing it too.

**Comment by hirbod** [comment]
![Image](https://github.com/user-attachments/assets/59907732-2084-46cb-83fa-07a1488b75f3)

It's not only inconsistent, @kkafar @Jpoliachik - it also re-introduces old bugs, like this cut off button (even on 4.7.0-beta.4 with Fabric).

We're going full circle with these bugs :(

**Comment by kkafar** [comment]
@hirbod what do you do to trigger this behaviour? Please share a snippet - I do not observe this buggy behaviour on my end. 

https://github.com/user-attachments/assets/a6af49af-8840-421c-b803-bea63b3b025b

**Comment by hirbod** [comment]
I had this Zeego snippet @kkafar

```tsx
<DropdownMenu.Root>
  <DropdownMenu.Trigger asChild>
    <View className="h-6 w-6">
      <Ionicons name="settings-outline" size={22} color="white" />
    </View>
  </DropdownMenu.Trigger>
  <DropdownMenu.Content>
    <DropdownMenu.Item key="b_sign_out" onSelect={signOut} destructive>
      <DropdownMenu.ItemTitle style={Platform.select({ web: { color: '#dc2626' } })}>
        Sign out
      </DropdownMenu.ItemTitle>
    </DropdownMenu.Item>
  </DropdownMenu.Content>
</DropdownMenu.Root>
```

I had to wrap my Ionicons with a View and add `h-6` and `w-6`.

We’ve been using the exact same component for a year, so either a recent change caused this (RE: it happens 1/3 of the time but is “fixed” with h-6 and w-6), or our switch to Fabric did.

**Comment by ryanlntn** [comment]
We're still seeing this as well. Perhaps this should be re-opened?

**Comment by liixing** [comment]
Still have the issue when use icon with pressable

**Comment by sgandon** [comment]
same me, issue still there. Any work around ?

**Comment by kkafar** [comment]
Any reproduction?

**Comment by thomasttvo** [comment]
I'm on `4.17.1` and confirmed this issue is now back. We should reopen this issue.

**Comment by thomasttvo** [comment]
Upon closer inspection, it looks like if it's on `headerLeft`, the `hitSlop` is off centered. If it's `headerRight` then the `hitSlop` doesn't work at all

**Comment by kkafar** [comment]
I'll reopen in case somebody provides a valid reproduction.

**Comment by kligarski** [comment]
Hi, `hitStop` on iOS should be fixed by this PR: https://github.com/software-mansion/react-native-screens/pull/3446.
