### ISSUE TITLE
Not working with React Native 0.73

### ISSUE THREAD

**Issue by BooYeu** [software-mansion/react-native-screens#1984]
### Description

react-native 0.73 is released, but something wrong when build android

### Steps to reproduce

react-native 0.73 is released, but something wrong when build android

### Snack or a link to a repository

none

### Screens version

3.17.0

### React Native version

0.73.0

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @BooYeu, thanks for reporting that!
Yup, I agree with @AlirezaHadjar. Let's close this issue, as #1985 is more detailed.
