### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager.

### ISSUE THREAD

**Issue by madhuvenkat123** [software-mansion/react-native-screens#1986]
### Description

Hello, first of all thank you for creating and maintaining this amazing library.  Currently when i am trying to run this project its crashing right away with error Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager. This error is located at:
    in RNSScreenStackHeaderConfig
    in Unknown
    in RNSScreen
    in N
    in Unknown
    in o
    in Suspense
    in Unknown
    in q
    in l
    in s
    in f
    in o
    in Suspense
    in Unknown
    in q
    in RNSScreenStack
    in ScreenStack
    in y
    in RNCSafeAreaProvider
    in Unknown
    in p
    in Unknown
    in Unknown
    in u
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in s
    in $
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in y.  

I have tried this steps mentioned in this comment https://github.com/software-mansion/react-native-screens/issues/1614#issuecomment-1276212091 but still facing the same issue. I have tried every possible solution not sure whats i am doing wrong. Please suggest if anyone has any idea about it how can i resolve this.

### Steps to reproduce

 Install react native project with version 0.68.4 and install react native screen with latest version. Then create stack navigator.

### Snack or a link to a repository

Na

### Screens version

^3.29.0

### React Native version

0.68.2

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

Simulator IOS 15

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @madhuvenkat123,

most likely reinstalling deps should resolve the issue:

```bash
rm -fr node_modules yarn.lock
yarn install
cd ios
rm -fr Pods build Podfile.lock
pod install
```

Lemme know if this helped.

**Comment by kkafar** [comment]
I think we can proceed with closing this issue. Let us know whether in case the problem persisted.
