### ISSUE TITLE
Weird flash when use Actions.pop()

### ISSUE THREAD

**Issue by catmans1** [software-mansion/react-native-screens#199]
I follow with example project. When i implement `react-native-router-flux` using Actions.pop() to come back previous screen, and it occur weird flash.
My code in App.js
```
import { useScreens } from 'react-native-screens';
useScreens();
```
Library i am using
```
react-native-cli: 2.0.1
react-native: 0.61.2
```
```
"react-native-router-flux": "^4.0.6",
"react-native-screens": "^2.0.0-alpha.4",
```

**Comment by DanielLe232** [comment]
Do anyone occur the same issue?

**Comment by atlkuk** [comment]
I have the same issue here! is there a way to avoid this flash?

**Comment by WoLewicki** [comment]
Does the issue still exist in the newest version @catmans1 @atlkuk ?

**Comment by catmans1** [comment]
@WoLewicki It no longer happen.

**Comment by atlkuk** [comment]
@WoLewicki I installed the latest version and it happen again

**Comment by WoLewicki** [comment]
@atlkuk are you using bare RN project or Expo?

**Comment by atlkuk** [comment]
@WoLewicki I'm using RN 0.61.5 + router-flux obviously.

**Comment by WoLewicki** [comment]
I mean do you use Expo Client?

**Comment by atlkuk** [comment]
Ah no sorry

**Comment by WoLewicki** [comment]
Can you provide a repo with minimal configuration needed to reproduce the issue?
