### ISSUE TITLE
can't change header height

### ISSUE THREAD

**Issue by haipv01** [software-mansion/react-native-screens#1991]
### Description

I tried to change header height in headerStyle but it didn't work for me

import { createNativeStackNavigator } from 'react-native-screens/native-stack';
const Stack = createNativeStackNavigator();

  const appStack = (
        <Stack.Navigator
        headerMode='screen'
        screenOptions={{ 
            headerShown: true, 
            cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS,
            direction: I18nManager.isRTL ? 'rtl' : 'ltr',
            headerHideShadow: false,
            headerStyle: {
                backgroundColor: '#f5f6f8',
                height: 50
            },
            headerLeft: (props) => {
                return  <CustomizeLeftHeader navigationProps={props}  />
            },
            headerRight: (props) => {
                return  <CustomizeRightHeader navigationProps={props}  />
            },
            
            }}>

### Screens version

2.18.1

### React Native version

0.60.5

### Platforms

iOS

**Comment by tboba** [comment]
Hi @haipv01, thanks for creating this issue!
Unfortunately, currently react-native-screens doesn't support changing its header height. The only (natively) supported values for `headerStyle` setting are `blurEffect` and `backgroundColor`. However, I see that you're probably using react-navigation API, which changes header behavior a bit. Have you tried to replace the import with the `@react-navigation` one?

```tsx
import { createNativeStackNavigator } from '@react-navigation/native-stack';
```

Hope that it helps.
Cheers!

**Comment by haipv01** [comment]
thank you for quick support @tboba 
I'd like to use react-native-screens/native-stack because the navigation animation smoothly and fast than @react-navigation/native-stack, my project version is 0.60.5 very old, upgrading that is very time consuming
is there any way to custom header height, ex  trick, tip, custom library code

**Comment by tboba** [comment]
@haipv01 I understand. Unfortunately blur effects and background color are the only parts of header you can customize in react-native-screens. There may be more settings you can choose from for modifying header (every prop that starts with `header` changes its behavior) but I believe that for now it's impossible to change its height 😕 
You can try to use React Navigation - it should be really easy to setup (since I see that you're already using its properties - for example `cardStyleInterpolator`). React Navigation still supports React Native 0.60, so I think it should work in your case.

I also convince you to at least try to update your project to the newest React Native. I know that it's painful, but there are tools that helps you find yourself in that mess (take a look at [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.60.5&to=0.73.1) or the [rnx-kit](https://microsoft.github.io/rnx-kit/docs/guides/dependency-management) that helps you maintain your RN version.
There's also [Flame AI](https://github.com/infinitered/flame) that upgrades your app for **you**, but I see that it requires having ChatGPT 4 subscription. With those tools, upgrading React Native version becomes really easy! 🙏 

Hope that it helps.
Cheers!

**Comment by haipv01** [comment]
@tboba thank you. I will try it at the end
I seen the getDefaultHeaderHeight.tsx file in newer react-native-screens so can I change the header height in that
![Screenshot 2023-12-21 at 10 24 55](https://github.com/software-mansion/react-native-screens/assets/131338302/646d06f5-ffaf-462e-82a0-72491c1396b7)

**Comment by tboba** [comment]
@haipv01 sadly this method only calculates height of the header, so it does not change it. However I remember that there's an option `headerTopInsetEnabled` that allows you to change the inset of a header, but it works only on Android and lets you to enlarge the header only by 24px - it's the status bar height.

**Comment by tboba** [comment]
@haipv01 sadly this method only calculates header height and it does not change it. However I remember that there's an option for the screen called `headerTopInsetEnabled` which allows you to enlarge the header, but it's only for Android and it allows you to enlarge the header by 24px (status bar height), in case if you'd like to use `statusBarTranslucent` prop with it.

**Comment by haipv01** [comment]
@tboba thank you for your help

**Comment by tboba** [comment]
@haipv01 You're welcome 🤗 For now I'll close this issue, but in case if you still have any question, don't hesitate to ask it here!

**Comment by haipv01** [comment]
> Hi @haipv01, thanks for creating this issue! Unfortunately, currently react-native-screens doesn't support changing its header height. The only (natively) supported values for `headerStyle` setting are `blurEffect` and `backgroundColor`. However, I see that you're probably using react-navigation API, which changes header behavior a bit. Have you tried to replace the import with the `@react-navigation` one?
> 
> ```tsx
> import { createNativeStackNavigator } from '@react-navigation/native-stack';
> ```
> 
> Hope that it helps. Cheers!

I'am trying this solution but I realize @react-navigation/native-stack base on react-native-screens, and I still can't modify header height.

by the way I also tried to custom '@react-navigation/stack CardStyleInterpolators but the animation couldn't be the same with native stack animation

   const customAnimation = {
        gestureDirection: 'horizontal',
        transitionSpec: {
          open: TransitionSpecs.TransitionIOSSpec,
          close: TransitionSpecs.TransitionIOSSpec,
        },
        cardStyleInterpolator: ({ current, layouts }) => {
          return {
            cardStyle: {
              transform: [
                {
                  translateX: current.progress.interpolate({
                    inputRange: [0, 1],
                    outputRange: [layouts.screen.width, 0],
                  }),
                },
              ],
            },
          };
        },
      };

**Comment by tboba** [comment]
@haipv01 Oh, okay 🤔 
I've got some ideas how the header height could be changed (at least on Android, on iOS I'm not sure if we can change it) but for now it's still idea. I'll leave it on our agenda though 👍

**Comment by tboba** [comment]
Also, please keep in mind that react-native-screens only supports React Native 0.64 (and higher) since version 3.14.0. This means that you should upgrade your project to the higher React Native version for supporting this feature (or you'll need to patch the package manually).

**Comment by haipv01** [comment]
> @haipv01 Oh, okay 🤔 I've got some ideas how the header height could be changed (at least on Android, on iOS I'm not sure if we can change it) but for now it's still idea. I'll leave it on our agenda though 👍

hi, have you tried this one or any feature updated
