### ISSUE TITLE
iOS header not respecting notch anymore

### ISSUE THREAD

**Issue by tobiaslins** [software-mansion/react-native-screens#200]
I just upgraded from 2.0.0-alpha.4 to alpha.5 and the navbar was not working correctly anymore on iOS (with notch)

![image](https://user-images.githubusercontent.com/2978876/67559291-f1d42a00-f718-11e9-9fbc-654add8a6b14.png)

I digged into the code and found out that following changes are the reason:
https://github.com/kmagiera/react-native-screens/pull/184/files#r338960815

Reverting back those line it's working again! 

I'm not too familiar with iOS so not sure what this change should change/fix

Thanks!

**Comment by kmagiera** [comment]
can you share some code that reproduces the issue? this works ok on my Example apps and also on two other apps I'm testing native navigator with

**Comment by tobiaslins** [comment]
@kmagiera the stacknavigator is nested in a TabNav
I try to create a minimum sample when I get back home!

**Comment by Alenius** [comment]
This problem happens to me too. I just installed react-native-screens. The <SafeAreaView> is not working as intended.

**Comment by satya164** [comment]
This doesn't seem to happen with latest alpha anymore. But now screen content appears below the header.

**Comment by immortalx** [comment]
Latest alpha 2.0.0-alpha.7 shows fine in android but in iOS any content appears behind the header.

**Comment by WoLewicki** [comment]
Does the issue exist in the newest version @tobiaslins ?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
