### ISSUE TITLE
Screen UI clipped when changing orientation from portrait to landscape

### ISSUE THREAD

**Issue by iamsaadMehmood** [software-mansion/react-native-screens#2000]
### Description

When the user changes the orientation from portrait to landscape or landscape to portrait the UI clipped but after reloading the application the UI works perfectly

I have tried the following patch in RNSScreenStack.mm but it didn't work
```
- (void)navigationController:(UINavigationController *)navigationController
       didShowViewController:(UIViewController *)viewController
                    animated:(BOOL)animated
{
  [self emitOnFinishTransitioningEvent];
  [RNSScreenWindowTraits updateWindowTraits];
  [_controller.view setNeedsLayout]; <------- This line
}
```

The Following is the UI that I am getting after changing the orientation

![Simulator Screenshot - iPad (10th generation) - 2023-12-28 at 12 55 29](https://github.com/software-mansion/react-native-screens/assets/101876738/8806193f-efb3-440f-8419-6a2b7135b8fe)

Following is the UI which should be after changing the orientation

![Simulator Screenshot - iPad (10th generation) - 2023-12-28 at 13 28 09](https://github.com/software-mansion/react-native-screens/assets/101876738/1fc6985c-ebaa-4f80-a190-37331bc48889)

Tested on iPad (10th generation)
 iOS 17.2.

### Steps to reproduce

1. Create Some UI that is different for landscape and portrait.
2. Change the Device orientation from portrait to landscape or Landscape to portrait the UI will be clipped.

### Snack or a link to a repository

can't share

### Screens version

^3.29.0

### React Native version

0.71.3

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPad (10th Generation)

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @iamsaadMehmood, thanks for submitting this issue!
Do you know if this issue is related to the #1738? Is it the same problem?

**Comment by iamsaadMehmood** [comment]
> Hi @iamsaadMehmood, thanks for submitting this issue! Do you know if this issue is related to the #1738? Is it the same problem?

Yes That's the same problem
