### ISSUE TITLE
[ios] Screen freezes for a couple of seconds when navigating back from a screen containing video

### ISSUE THREAD

**Issue by mohamedmagdy7** [software-mansion/react-native-screens#2009]
### Description

on ios devices
- "react-native-screens": version 3.29.0
- "react-native": version 0.71.7
When opening a screen with video and navigate back quickly without letting the video loads, the screen freezes on the back animation for a couple of seconds.

https://github.com/software-mansion/react-native-screens/assets/98698005/da4d5689-111a-4c30-9af3-3c5deb4e0f98

### Steps to reproduce

- Open screen with video from ios device
- Navigate back quickly without letting the video loads
- Notice the screen freeze

### Snack or a link to a repository

- A video describing the issue attached

### Screens version

3.29.0

### React Native version

0.71.7

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Release mode

### Device

Real device

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hey @mohamedmagdy7, thanks for creating this issue!
Our Github bot has marked some valid points there 👆, could you please create a reproducer for that issue?
