### ISSUE TITLE
Android Lint warning: Using internal inset dimension resource

### ISSUE THREAD

**Issue by jitendragupta24** [software-mansion/react-native-screens#2020]
### Description

We have been running Android Lint tool on the latest code and came across an error about 'Using internal inset dimension resource' in a file. Here is the summary of this warning and places where this needs to be fixed.

![image](https://github.com/software-mansion/react-native-screens/assets/102529696/410b325f-230c-455a-8a43-4d67d8907b8b)

### Steps to reproduce

Run lint command using gradle as specified in this documentation:
https://developer.android.com/studio/write/lint#commandline

### Snack or a link to a repository

NA

### Screens version

3.29.0

### React Native version

0.71.13

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @jitendragupta24, I can confirm this behavior is reproducible for me, but I believe this issue may be related to #2018 (which describes warnings about using depreacted methods, but the scope to fix is to resolve all warnings). Hence, let me redirect you to #2018. You can write a comment there about this warning 🙏 
Nonetheless, thanks for creating this issue!

Cheers!
