### ISSUE TITLE
Error on reload: ERROR Invariant Violation: Failed to call into JavaScript module method RCTEventEmitter.receiveEvent

### ISSUE THREAD

**Issue by sbin1211** [software-mansion/react-native-screens#2027]
### Description

some users report this issue, and i think it's caused by the React-Native-screens.  
https://github.com/facebook/react-native/issues/42640#issue-2098722178

### Steps to reproduce

you can reproduce this issue with below repro.
(when you trigger the "reload" inside app, the error happen, but NOT from terminal

https://github.com/sbin1211/RNInvariantViolation.git

### Snack or a link to a repository

 https://github.com/sbin1211/RNInvariantViolation.git

### Screens version

3.29

### React Native version

0.73

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @sbin1211, thanks for creating this issue!
Unfortunately I cannot reproduce the error with given steps to repro 😕 Could you give us more details about the device you're using where this error happens?

https://github.com/software-mansion/react-native-screens/assets/23281839/e9fc8b3f-b9d8-4ded-b17a-400680603559

**Comment by sbin1211** [comment]
> Hi @sbin1211, thanks for creating this issue! Unfortunately I cannot reproduce the error with given steps to repro 😕 Could you give us more details about the device you're using where this error happens?
> 
>  8mb.video-riQ-fSVsSIX3.mp4

https://github.com/software-mansion/react-native-screens/assets/22540308/77f22c09-e974-4c9f-8890-f4fd3eff213e



@tboba see the screencast, it happens when fabirc turn on 

"AwesomeProject" with {"rootTag":1,"initialProps":{"concurrentRoot":true},"fabric":true}

**Comment by tboba** [comment]
Hi @sbin1211, sorry for the delay 🙏 
I still can't reproduce the bug, even if I just enabled fabric. Have you tried to reset cache of yarn/npm before running your app? Are you listening for some events?

<img width="1069" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/23281839/c33203d2-3516-43ee-ae0c-851dd90d64a3">

**Comment by mittalkamal29** [comment]
Are you able to find any solution for the same? As I am facing that issue after updating the RN version.

**Comment by mohitGraffers** [comment]
<img width="355" height="785" alt="Image" src="https://github.com/user-attachments/assets/def8a302-0a0e-4ecf-8599-c19fdc039502" />


I am facing same isue , it is still not resolve 

React-Native Version - 0.77.0
React-Native Screens - 4.13.1

**Comment by Phong-TH** [comment]
I have the same issue after updating to RN 0.81.1, "react-native-screens": "^4.15.4",

**Comment by rousseau634** [comment]
in my case, it solved when I replaced AppDelegate with swift

**Comment by rousseau634** [comment]
> I have the same issue after updating to RN 0.81.1, "react-native-screens": "^4.15.4",

In my case, it solved when I replaced AppDelegate with swift

**Comment by Vishal-D4** [comment]
<img width="300" height="566" alt="Image" src="https://github.com/user-attachments/assets/33c3fa6e-f920-4e57-b845-14b125e5ce21" />

I recently upgrade from react-native v0.76.6 to 0.81.4 and getting the same error as mentioned by others.
React-Native-Screens-: 4.15.4

i also tried replacing AppDelgate.mm to AppDelegate.swift, but then ran into other errors.
Provide any workaround as i have to publish my app soon

**Comment by kkafar** [comment]
@Vishal-D4 when upgrading you should follow https://react-native-community.github.io/upgrade-helper/ **strictly**.

**Comment by NikhilCodeblaze** [comment]
@Vishal-D4 I also faced same issue how you fixed it . i did same upgraded to 0.81.4

**Comment by Vishal-D4** [comment]
@NikhilCodeblaze for me the error got solved once i upgraded correctly. Check if u upgraded correctly or not

**Comment by NikhilCodeblaze** [comment]
i fixed it following RN 0.77.0 blogpost to add #import <ReactAppDependencyProvider/RCTAppDependencyProvider.h> in appdelegate.mm file @Vishal-D4

**Comment by Vishal-D4** [comment]
@NikhilCodeblaze so is it working now?
Actually there were too many changes after uprading to latest stable version of RN, so i couln't exactly found out what is the reason for this issue

**Comment by NikhilCodeblaze** [comment]
Yes its working fine @Vishal-D4

**Comment by cchandra-ABS** [comment]
is anyone who fixed this issue

**Comment by Phong-TH** [comment]
@cchandra-ABS we keep using ObjC for RN 0.81.1 to avoid this issue. Hope this help!

**Comment by Lavanjan** [comment]
Please add the following two lines to your AppDelegate.mm file.

#import <ReactAppDependencyProvider/RCTAppDependencyProvider.h>
  self.dependencyProvider = [RCTAppDependencyProvider new];


```
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <ReactAppDependencyProvider/RCTAppDependencyProvider.h>


@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"<Your app Name>";
  self.dependencyProvider = [RCTAppDependencyProvider new];
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

// remaining of the AppDelegate
```
