### ISSUE TITLE
androidx.fragment.app.Fragment.instantiate Fragment.java, line 613

### ISSUE THREAD

**Issue by Mushthak007** [software-mansion/react-native-screens#2037]
### Description

androidx.fragment.app.Fragment.instantiate
Fragment.java, line 613

### Steps to reproduce

androidx.fragment.app.Fragment.instantiate
Fragment.java, line 613

### Snack or a link to a repository

androidx.fragment.app.Fragment.instantiate Fragment.java, line 613

### Screens version

3.16.0

### React Native version

0.69.0

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Mushthak007** [comment]
com.swmansion.rnscreens.ScreenFragment.<init> ScreenFragment.kt:57
com.swmansion.rnscreens.ScreenStackFragment.<init> ScreenStackFragment.kt:38
java.lang.reflect.Constructor.newInstance0 Constructor.java
java.lang.reflect.Constructor.newInstance Constructor.java:343
androidx.fragment.app.Fragment.instantiate Fragment.java:613
androidx.fragment.app.FragmentContainer.instantiate FragmentContainer.java:57
androidx.fragment.app.FragmentManager$3.instantiate FragmentManager.java:483
androidx.fragment.app.FragmentStateManager.<init> FragmentStateManager.java:85
androidx.fragment.app.FragmentManager.restoreSaveState FragmentManager.java:2728
androidx.fragment.app.FragmentController.restoreSaveState FragmentController.java:198
androidx.fragment.app.FragmentActivity$2.onContextAvailable FragmentActivity.java:149
androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable ContextAwareHelper.java:99
androidx.activity.ComponentActivity.onCreate ComponentActivity.java:352
androidx.fragment.app.FragmentActivity.onCreate FragmentActivity.java:273
com.facebook.react.ReactActivity.onCreate ReactActivity.java:45
android.app.Activity.performCreate Activity.java:8683
android.app.Activity.performCreate Activity.java:8662
android.app.Instrumentation.callActivityOnCreate Instrumentation.java:1417
android.app.ActivityThread.performLaunchActivity ActivityThread.java:4165
android.app.ActivityThread.handleLaunchActivity ActivityThread.java:4340
android.app.servertransaction.LaunchActivityItem.execute LaunchActivityItem.java:101
android.app.servertransaction.TransactionExecutor.executeCallbacks TransactionExecutor.java:135
android.app.servertransaction.TransactionExecutor.execute TransactionExecutor.java:95
android.app.ActivityThread$H.handleMessage ActivityThread.java:2584
android.os.Handler.dispatchMessage Handler.java:106
android.os.Looper.loopOnce Looper.java:226
android.os.Looper.loop Looper.java:313
android.app.ActivityThread.main ActivityThread.java:8810
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:604
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1067

**Comment by tboba** [comment]
Hey @Mushthak007 👋 
This description doesn't say too much about the issue that happens for you. Could you write correct description for the issue, including the steps to reproduce?
Could you also check if this error happens on the newest version of Screens?
Have you tried the solution mentioned here: https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067?
