### ISSUE TITLE
Hardware/software back button press ignored by ScreenStack and onDismiss

### ISSUE THREAD

**Issue by MarcusMorter** [software-mansion/react-native-screens#204]
I'm trying to make some simple navigation components, but when I tried making a stack, it ignores the back press and shuts down the app instead of poping the screen.

```
<ScreenStack
                style={{
                    flex: 1
                }}
            >
                <Screen
                    style={StyleSheet.absoluteFill}
                    onDismissed={() => {console.log("------------ dismissed")}}
                >
                    <Screen1/>
                </Screen>
                <Screen
                    style={StyleSheet.absoluteFill}
                    onDismissed={() => {console.log("------------ dismissed")}}
                >
                    <Screen2/>
                </Screen>
            </ScreenStack>
```
Also the parameter is different for the example and documentation (docs say onDismiss, example has onDismissed. tried both and neither work)

I'd like to know if this is a bug or if I'm doing something wrong.

**Comment by ajsmth** [comment]
have you tried capturing the back event with a BackButton handler instead of just console.log?

**Comment by WoLewicki** [comment]
Can you repro the issue in the newest version @MarcusMorter?

**Comment by MarcusMorter** [comment]
@WoLewicki I'll try (just don't have a pc now, gonna be durring the weekend)

**Comment by WoLewicki** [comment]
@MarcusMorter did you manage to do that?

**Comment by MarcusMorter** [comment]
@WoLewicki yup, it works now
