### ISSUE TITLE
iOS: `Screen` with `{ presentation: "modal" }` navigated to from within another react-native's `Modal` doesn't open

### ISSUE THREAD

**Issue by bbarthec** [software-mansion/react-native-screens#2048]
### Description

https://github.com/software-mansion/react-native-screens/releases/tag/3.29.0 and https://github.com/software-mansion/react-native-screens/pull/1912 are causing breaking change in behaviour of `'@react-navigation/native-stack'`'s `Screen` that is mounted with `{ presentation: "modal" }`.

Hiding the `react-native`'s `Modal` that is the most top component in the view hierarchy prevents `Screen` with `{ presentation: "modal" }` from showing.
My scenario:
1. show a `BottomSheet` that is based on `react-native`'s `Modal` with an action button
2. clicking the button should hide the `BottomSheet` and navigate to `{ presentation: "modal" }` individual Screen

| Before `3.29.0` (`3.28.0` here) - desired behaviour | `3.29.0` - breaking change | `3.29.0` - without `BottomSheet` autohide |
|-|-|-|
| <video src=https://github.com/software-mansion/react-native-screens/assets/16623003/b3cf2994-e438-4f86-8bf4-f53f2970dd2d height=480 /> | <video src=https://github.com/software-mansion/react-native-screens/assets/16623003/18bbcf97-0c5e-4d87-b504-3bb1c53ce69a height=480 /> | <video src=https://github.com/software-mansion/react-native-screens/assets/16623003/91f38632-b3ed-4cea-84b2-aab61ac91e58 height=480 /> |

### Steps to reproduce

1. Open https://snack.expo.dev/@bbarthec/react-native-screens-modal-in-modal-issues
2. Open the snack in Expo GO (SDK 50 comes with version `3.29.0`) on either physical iPhone or Simulator
3. Open `BottomSheet` modal & open `Screen` modal - see `Screen` is not visible. It's probably mounted using dismissed `BottomSheet` modal as an anchor component.
4. Commend out `setVisible(false)` from line 51 and repeat the process. See the modal `Screen` properly mounts.

### Snack or a link to a repository

https://snack.expo.dev/@bbarthec/react-native-screens-modal-in-modal-issues

### Screens version

3.29.0

### React Native version

0.73

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
yeah, I see why that's happening, thanks for reporting! We will include a fix in incoming release

**Comment by kLesieur** [comment]
@kkafar Any news on an incoming fix ? I have a similar issue that I think could be related to this one :)

**Comment by kimlesieur** [comment]
@kkafar  Any news on an incoming fix ? I have a similar issue that I think could be related to this one :)

**Comment by hollanderbart** [comment]
@kkafar Can you please let us know when a possible fix is planned? Thanks!

**Comment by kkafar** [comment]
Excuse me for late response, @hollanderbart, #2113 should resolve the issue. 
If you have capacity, I would like to get feedback & confirmation that the patch works also in your case.

You can test out the patch by installing `react-native-screens` directly from GitHub, by putting following in your package.json:

```json
"react-native-screens": "software-mansion/react-native-screens#@kkafar/fix-presenting-from-react-native-modal"
```

(watch for typos, as I'm writing from memory 😅)

**Comment by hollanderbart** [comment]
Thanks @kkafar I will test it out and come back to you on this.

**Comment by hollanderbart** [comment]
I've tested it and your fix works! 🎉 

Thanks again @kkafar
I suppose you can merge this fix.

**Comment by kkafar** [comment]
Great, thanks for checking it out!
