### ISSUE TITLE
Newer version of RN comes with Kotlin. How to override `onCreate`?

### ISSUE THREAD

**Issue by alex-mironov** [software-mansion/react-native-screens#2049]
### Description

The newer version of RN uses Kotlin for Android.
<img width="1524" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/2544767/c4f939f7-9bc6-45f2-befa-012d0fd45ebb">
Can somebody suggest how to rewrite this into Kotlin?
```java
    //react-native-screens override
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(null);
    }
```

### Steps to reproduce

1. Install the recent version of React Native - 0.73.4 as of writing
2. Navigate to `MainActivity.kt` and paste the code from documentation
```java
    //react-native-screens override
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(null);
    }
```

### Snack or a link to a repository

https://react-native-community.github.io/upgrade-helper/?from=0.72.0&to=0.73.4

### Screens version

3.29.0

### React Native version

0.73.4

**Comment by tboba** [comment]
Hi @alex-mironov, transfering this `onCreate` from Java to Kotlin is pretty simple, you just need to add this snippet into your `MainActivity.kt` file:

```kt
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(null)
    }
```

Please let me know if you have any other questions! For now I'll close this issue.
Cheers

**Comment by FreTimmerman** [comment]
be sure `import android.os.Bundle` is present at the top in `MainActivity.kt`
