### ISSUE TITLE
Missing React-RCTImage dependency

### ISSUE THREAD

**Issue by stianjensen** [software-mansion/react-native-screens#2054]
### Description

When upgrading to react-native 0.73, I needed to upgrade react-native-screen to the latest version in order to make it build properly on Android.
Then I ran into an issue on iOS where `React-RCTImage` disappeared from the list of dependencies of RNScreens in Podfile.lock.

It looks like it stems from this commit, which first shipped with v3.26.0:
https://github.com/software-mansion/react-native-screens/commit/c3d1ae81fdd1214b572ac9c063a50deedf7db316

React-RCTImage is only added to the list of dependencies if you're running in a react-native environment without `install_modules_dependencies`.

The error I was getting was:
```
ld: Undefined symbols:
  _OBJC_CLASS_$_RCTImageLoader, referenced from:
       in RNSScreenStackHeaderConfig.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Patching the podspec locally to add back React-RCTImage (at least when running with `new_arch_enabled == false`, the only config I've tested so far), resolves the issue for me. Has it gotten lost in this case accidentally?

I can see from the PRs to the example repo here as well that the dep got lost when updating the version of react-native-screens used in the example repositories:
https://github.com/software-mansion/react-native-screens/pull/1979

For context, I am running with `use_frameworks!` in my Podfile, but have seen no issues with that and react-native-screens until now.

Would it be possible to keep the dependency and thereby continue supporting this workflow?

### Steps to reproduce

Install with use_frameworks! in your podfile, and then try to run on iOS.

### Snack or a link to a repository

https://github.com/stianjensen/react-native-screens-test/tree/main

### Screens version

3.29.0

### React Native version

0.73.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by babzcraig** [comment]
> Yeah, this is rather unintended. Thanks for letting us know.
> 
> Most likely we will bring back react-image to our dependency list, as we directly consume it.

Hi @kkafar any update on this? Thank you

**Comment by WoLewicki** [comment]
@stianjensen can you check if applying https://github.com/software-mansion/react-native-screens/pull/2089 fixes the issue?

**Comment by tboba** [comment]
@stianjensen That's great, thanks for confirming this resolves your issue!
The PR with fix has been already merged (commit: https://github.com/software-mansion/react-native-screens/commit/02154a9e94916018814e1b8cda5ed0f9963dc1e8) and will land in the next release of Screens 🎉 

Also, if the error with undefined symbol still happens to you, could you create separate issue with it? 🙏

**Comment by itlijunjie** [comment]
@stianjensen 

Try adding the following code to the podspec file in v3.27.0.

```ruby
if ENV["USE_HERMES"] == nil || ENV["USE_HERMES"] == "1"
    s.dependency "hermes-engine"
end
```
