### ISSUE TITLE
Can't finish installation on react-native 0.59.9

### ISSUE THREAD

**Issue by W1nstar** [software-mansion/react-native-screens#206]
If I add the two lines on the build.gradle file, I get an error wich I don't really understand. I'm using react-navigation 3.11.

This is how my dependencies look like:

> dependencies {
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-screens')
    implementation project(':react-native-keyevent')
    implementation project(':react-native-gesture-handler')
    implementation project(':@react-native-community_async-storage')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
	implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
	implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
}

And this is the error I'm getting:

> Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.1.0-rc01] AndroidManifest.xml:24:18-86
        is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.

I tried: 
1. Adding just the swiperefresh implementation.
2. Adding just the swiprefresh implementation and removing the comment on the appcompat-v7
3. Adding just the appcompat:1.1.0

If I don't add anything to the build.gradle, the app compiles normally, but I'm guessing screens won't have effect without the dependencies?

I don't really think the solution should be to tinker with the manifest, no?

**Comment by WoLewicki** [comment]
It is no longer needed to add those lines, so I am closing this issue. Feel free to comment if I am wrong.
