### ISSUE TITLE
New architecture with static conditional router showing blank on iOS

### ISSUE THREAD

**Issue by b0iq** [software-mansion/react-native-screens#2063]
### Description

as I opened this issue https://github.com/react-navigation/react-navigation/issues/11884, there's an issue with conditional routing. it works fine on Android

### Steps to reproduce

1. copy this reproduction snack: [example from the docs](https://snack.expo.dev/?name=Signing+in+and+signing+out+with+AuthContext&code=import+*+as+React+from+%27react%27%3B%0Aimport+*+as+SecureStore+from+%27expo-secure-store%27%3B%0A%0Aimport+%7B+Button%2C+Text%2C+TextInput%2C+View+%7D+from+%27react-native%27%3B%0Aimport+%7B+createStaticNavigation+%7D+from+%27%40react-navigation%2Fnative%27%3B%0Aimport+%7B+createNativeStackNavigator+%7D+from+%27%40react-navigation%2Fnative-stack%27%3B%0A%0Aconst+AuthContext+%3D+React.createContext%28%29%3B%0A%0Aconst+SignInContext+%3D+React.createContext%28%29%3B%0A%0Afunction+useIsSignedIn%28%29+%7B%0A++const+isSignedIn+%3D+React.useContext%28SignInContext%29%3B%0A++return+isSignedIn%3B%0A%7D%0A%0Afunction+useIsSignedOut%28%29+%7B%0A++const+isSignedIn+%3D+React.useContext%28SignInContext%29%3B%0A++return+%21isSignedIn%3B%0A%7D%0A%0Afunction+SplashScreen%28%29+%7B%0A++return+%28%0A++++%3CView%3E%0A++++++%3CText%3ELoading...%3C%2FText%3E%0A++++%3C%2FView%3E%0A++%29%3B%0A%7D%0A%0Afunction+HomeScreen%28%29+%7B%0A++const+%7B+signOut+%7D+%3D+React.useContext%28AuthContext%29%3B%0A%0A++return+%28%0A++++%3CView%3E%0A++++++%3CText%3ESigned+in%21%3C%2FText%3E%0A++++++%3CButton+title%3D%22Sign+out%22+onPress%3D%7BsignOut%7D+%2F%3E%0A++++%3C%2FView%3E%0A++%29%3B%0A%7D%0A%0Afunction+SignInScreen%28%29+%7B%0A++const+%5Busername%2C+setUsername%5D+%3D+React.useState%28%27%27%29%3B%0A++const+%5Bpassword%2C+setPassword%5D+%3D+React.useState%28%27%27%29%3B%0A%0A++const+%7B+signIn+%7D+%3D+React.useContext%28AuthContext%29%3B%0A%0A++return+%28%0A++++%3CView%3E%0A++++++%3CTextInput%0A++++++++placeholder%3D%22Username%22%0A++++++++value%3D%7Busername%7D%0A++++++++onChangeText%3D%7BsetUsername%7D%0A++++++%2F%3E%0A++++++%3CTextInput%0A++++++++placeholder%3D%22Password%22%0A++++++++value%3D%7Bpassword%7D%0A++++++++onChangeText%3D%7BsetPassword%7D%0A++++++++secureTextEntry%0A++++++%2F%3E%0A++++++%3CButton+title%3D%22Sign+in%22+onPress%3D%7B%28%29+%3D%3E+signIn%28%7B+username%2C+password+%7D%29%7D+%2F%3E%0A++++%3C%2FView%3E%0A++%29%3B%0A%7D%0A%0Aexport+default+function+App%28%29+%7B%0A++const+%5Bstate%2C+dispatch%5D+%3D+React.useReducer%28%0A++++%28prevState%2C+action%29+%3D%3E+%7B%0A++++++switch+%28action.type%29+%7B%0A++++++++case+%27RESTORE_TOKEN%27%3A%0A++++++++++return+%7B%0A++++++++++++...prevState%2C%0A++++++++++++userToken%3A+action.token%2C%0A++++++++++++isLoading%3A+false%2C%0A++++++++++%7D%3B%0A++++++++case+%27SIGN_IN%27%3A%0A++++++++++return+%7B%0A++++++++++++...prevState%2C%0A++++++++++++isSignout%3A+false%2C%0A++++++++++++userToken%3A+action.token%2C%0A++++++++++%7D%3B%0A++++++++case+%27SIGN_OUT%27%3A%0A++++++++++return+%7B%0A++++++++++++...prevState%2C%0A++++++++++++isSignout%3A+true%2C%0A++++++++++++userToken%3A+null%2C%0A++++++++++%7D%3B%0A++++++%7D%0A++++%7D%2C%0A++++%7B%0A++++++isLoading%3A+true%2C%0A++++++isSignout%3A+false%2C%0A++++++userToken%3A+null%2C%0A++++%7D%0A++%29%3B%0A%0A++React.useEffect%28%28%29+%3D%3E+%7B%0A++++%2F%2F+Fetch+the+token+from+storage+then+navigate+to+our+appropriate+place%0A++++const+bootstrapAsync+%3D+async+%28%29+%3D%3E+%7B%0A++++++let+userToken%3B%0A%0A++++++try+%7B%0A++++++++%2F%2F+Restore+token+stored+in+%60SecureStore%60+or+any+other+encrypted+storage%0A++++++++userToken+%3D+await+SecureStore.getItemAsync%28%27userToken%27%29%3B%0A++++++%7D+catch+%28e%29+%7B%0A++++++++%2F%2F+Restoring+token+failed%0A++++++%7D%0A%0A++++++%2F%2F+After+restoring+token%2C+we+may+need+to+validate+it+in+production+apps%0A%0A++++++%2F%2F+This+will+switch+to+the+App+screen+or+Auth+screen+and+this+loading%0A++++++%2F%2F+screen+will+be+unmounted+and+thrown+away.%0A++++++dispatch%28%7B+type%3A+%27RESTORE_TOKEN%27%2C+token%3A+userToken+%7D%29%3B%0A++++%7D%3B%0A%0A++++bootstrapAsync%28%29%3B%0A++%7D%2C+%5B%5D%29%3B%0A%0A++const+authContext+%3D+React.useMemo%28%0A++++%28%29+%3D%3E+%28%7B%0A++++++signIn%3A+async+%28data%29+%3D%3E+%7B%0A++++++++%2F%2F+In+a+production+app%2C+we+need+to+send+some+data+%28usually+username%2C+password%29+to+server+and+get+a+token%0A++++++++%2F%2F+We+will+also+need+to+handle+errors+if+sign+in+failed%0A++++++++%2F%2F+After+getting+token%2C+we+need+to+persist+the+token+using+%60SecureStore%60+or+any+other+encrypted+storage%0A++++++++%2F%2F+In+the+example%2C+we%27ll+use+a+dummy+token%0A%0A++++++++dispatch%28%7B+type%3A+%27SIGN_IN%27%2C+token%3A+%27dummy-auth-token%27+%7D%29%3B%0A++++++%7D%2C%0A++++++signOut%3A+%28%29+%3D%3E+dispatch%28%7B+type%3A+%27SIGN_OUT%27+%7D%29%2C%0A++++++signUp%3A+async+%28data%29+%3D%3E+%7B%0A++++++++%2F%2F+In+a+production+app%2C+we+need+to+send+user+data+to+server+and+get+a+token%0A++++++++%2F%2F+We+will+also+need+to+handle+errors+if+sign+up+failed%0A++++++++%2F%2F+After+getting+token%2C+we+need+to+persist+the+token+using+%60SecureStore%60+or+any+other+encrypted+storage%0A++++++++%2F%2F+In+the+example%2C+we%27ll+use+a+dummy+token%0A%0A++++++++dispatch%28%7B+type%3A+%27SIGN_IN%27%2C+token%3A+%27dummy-auth-token%27+%7D%29%3B%0A++++++%7D%2C%0A++++%7D%29%2C%0A++++%5B%5D%0A++%29%3B%0A%0A++if+%28state.isLoading%29+%7B%0A++++%2F%2F+We+haven%27t+finished+checking+for+the+token+yet%0A++++return+%3CSplashScreen+%2F%3E%3B%0A++%7D%0A%0A++if+%28state.isLoading%29+%7B%0A++++return+%3CSplashScreen+%2F%3E%3B%0A++%7D%0A%0A++const+isSignedIn+%3D+state.userToken+%21%3D+null%3B%0A%0A++return+%28%0A++++%3CAuthContext.Provider+value%3D%7BauthContext%7D%3E%0A++++++%3CSignInContext.Provider+value%3D%7BisSignedIn%7D%3E%0A++++++++%3CNavigation+%2F%3E%0A++++++%3C%2FSignInContext.Provider%3E%0A++++%3C%2FAuthContext.Provider%3E%0A++%29%3B%0A%7D%0A%0Aconst+RootStack+%3D+createNativeStackNavigator%28%7B%0A++screens%3A+%7B%0A++++Home%3A+%7B%0A++++++if%3A+useIsSignedIn%2C%0A++++++screen%3A+HomeScreen%2C%0A++++%7D%2C%0A++++SignIn%3A+%7B%0A++++++screen%3A+SignInScreen%2C%0A++++++options%3A+%7B%0A++++++++title%3A+%27Sign+in%27%2C%0A++++++%7D%2C%0A++++++if%3A+useIsSignedOut%2C%0A++++%7D%2C%0A++%7D%2C%0A%7D%29%3B%0A%0Aconst+Navigation+%3D+createStaticNavigation%28RootStack%29%3B%0A&dependencies=expo-secure-store%40*%2C%40react-navigation%2Fnative%407.0.0-alpha.14%2C%40react-navigation%2Fnative-stack%407.0.0-alpha.15%2Creact-native-safe-area-context%40*%2Creact-native-screens%40*&platform=web&supportedPlatforms=ios%2Candroid%2Cweb&preview=true&hideQueryParams=true) 
2. enable new architecture 
3. sign in to switch screen

### Snack or a link to a repository
[example from the docs](https://snack.expo.dev/?name=Signing+in+and+signing+out+with+AuthContext&code=import+*+as+React+from+%27react%27%3B%0Aimport+*+as+SecureStore+from+%27expo-secure-store%27%3B%0A%0Aimport+%7B+Button%2C+Text%2C+TextInput%2C+View+%7D+from+%27react-native%27%3B%0Aimport+%7B+createStaticNavigation+%7D+from+%27%40react-navigation%2Fnative%27%3B%0Aimport+%7B+createNativeStackNavigator+%7D+from+%27%40react-navigation%2Fnative-stack%27%3B%0A%0Aconst+AuthContext+%3D+React.createContext%28%29%3B%0A%0Aconst+SignInContext+%3D+React.createContext%28%29%3B%0A%0Afunction+useIsSignedIn%28%29+%7B%0A++const+isSignedIn+%3D+React.useContext%28SignInContext%29%3B%0A++return+isSignedIn%3B%0A%7D%0A%0Afunction+useIsSignedOut%28%29+%7B%0A++const+isSignedIn+%3D+React.useContext%28SignInContext%29%3B%0A++return+%21isSignedIn%3B%0A%7D%0A%0Afunction+SplashScreen%28%29+%7B%0A++return+%28%0A++++%3CView%3E%0A++++++%3CText%3ELoading...%3C%2FText%3E%0A++++%3C%2FView%3E%0A++%29%3B%0A%7D%0A%0Afunction+HomeScreen%28%29+%7B%0A++const+%7B+signOut+%7D+%3D+React.useContext%28AuthContext%29%3B%0A%0A++return+%28%0A++++%3CView%3E%0A++++++%3CText%3ESigned+in%21%3C%2FText%3E%0A++++++%3CButton+title%3D%22Sign+out%22+onPress%3D%7BsignOut%7D+%2F%3E%0A++++%3C%2FView%3E%0A++%29%3B%0A%7D%0A%0Afunction+SignInScreen%28%29+%7B%0A++const+%5Busername%2C+setUsername%5D+%3D+React.useState%28%27%27%29%3B%0A++const+%5Bpassword%2C+setPassword%5D+%3D+React.useState%28%27%27%29%3B%0A%0A++const+%7B+signIn+%7D+%3D+React.useContext%28AuthContext%29%3B%0A%0A++return+%28%0A++++%3CView%3E%0A++++++%3CTextInput%0A++++++++placeholder%3D%22Username%22%0A++++++++value%3D%7Busername%7D%0A++++++++onChangeText%3D%7BsetUsername%7D%0A++++++%2F%3E%0A++++++%3CTextInput%0A++++++++placeholder%3D%22Password%22%0A++++++++value%3D%7Bpassword%7D%0A++++++++onChangeText%3D%7BsetPassword%7D%0A++++++++secureTextEntry%0A++++++%2F%3E%0A++++++%3CButton+title%3D%22Sign+in%22+onPress%3D%7B%28%29+%3D%3E+signIn%28%7B+username%2C+password+%7D%29%7D+%2F%3E%0A++++%3C%2FView%3E%0A++%29%3B%0A%7D%0A%0Aexport+default+function+App%28%29+%7B%0A++const+%5Bstate%2C+dispatch%5D+%3D+React.useReducer%28%0A++++%28prevState%2C+action%29+%3D%3E+%7B%0A++++++switch+%28action.type%29+%7B%0A++++++++case+%27RESTORE_TOKEN%27%3A%0A++++++++++return+%7B%0A++++++++++++...prevState%2C%0A++++++++++++userToken%3A+action.token%2C%0A++++++++++++isLoading%3A+false%2C%0A++++++++++%7D%3B%0A++++++++case+%27SIGN_IN%27%3A%0A++++++++++return+%7B%0A++++++++++++...prevState%2C%0A++++++++++++isSignout%3A+false%2C%0A++++++++++++userToken%3A+action.token%2C%0A++++++++++%7D%3B%0A++++++++case+%27SIGN_OUT%27%3A%0A++++++++++return+%7B%0A++++++++++++...prevState%2C%0A++++++++++++isSignout%3A+true%2C%0A++++++++++++userToken%3A+null%2C%0A++++++++++%7D%3B%0A++++++%7D%0A++++%7D%2C%0A++++%7B%0A++++++isLoading%3A+true%2C%0A++++++isSignout%3A+false%2C%0A++++++userToken%3A+null%2C%0A++++%7D%0A++%29%3B%0A%0A++React.useEffect%28%28%29+%3D%3E+%7B%0A++++%2F%2F+Fetch+the+token+from+storage+then+navigate+to+our+appropriate+place%0A++++const+bootstrapAsync+%3D+async+%28%29+%3D%3E+%7B%0A++++++let+userToken%3B%0A%0A++++++try+%7B%0A++++++++%2F%2F+Restore+token+stored+in+%60SecureStore%60+or+any+other+encrypted+storage%0A++++++++userToken+%3D+await+SecureStore.getItemAsync%28%27userToken%27%29%3B%0A++++++%7D+catch+%28e%29+%7B%0A++++++++%2F%2F+Restoring+token+failed%0A++++++%7D%0A%0A++++++%2F%2F+After+restoring+token%2C+we+may+need+to+validate+it+in+production+apps%0A%0A++++++%2F%2F+This+will+switch+to+the+App+screen+or+Auth+screen+and+this+loading%0A++++++%2F%2F+screen+will+be+unmounted+and+thrown+away.%0A++++++dispatch%28%7B+type%3A+%27RESTORE_TOKEN%27%2C+token%3A+userToken+%7D%29%3B%0A++++%7D%3B%0A%0A++++bootstrapAsync%28%29%3B%0A++%7D%2C+%5B%5D%29%3B%0A%0A++const+authContext+%3D+React.useMemo%28%0A++++%28%29+%3D%3E+%28%7B%0A++++++signIn%3A+async+%28data%29+%3D%3E+%7B%0A++++++++%2F%2F+In+a+production+app%2C+we+need+to+send+some+data+%28usually+username%2C+password%29+to+server+and+get+a+token%0A++++++++%2F%2F+We+will+also+need+to+handle+errors+if+sign+in+failed%0A++++++++%2F%2F+After+getting+token%2C+we+need+to+persist+the+token+using+%60SecureStore%60+or+any+other+encrypted+storage%0A++++++++%2F%2F+In+the+example%2C+we%27ll+use+a+dummy+token%0A%0A++++++++dispatch%28%7B+type%3A+%27SIGN_IN%27%2C+token%3A+%27dummy-auth-token%27+%7D%29%3B%0A++++++%7D%2C%0A++++++signOut%3A+%28%29+%3D%3E+dispatch%28%7B+type%3A+%27SIGN_OUT%27+%7D%29%2C%0A++++++signUp%3A+async+%28data%29+%3D%3E+%7B%0A++++++++%2F%2F+In+a+production+app%2C+we+need+to+send+user+data+to+server+and+get+a+token%0A++++++++%2F%2F+We+will+also+need+to+handle+errors+if+sign+up+failed%0A++++++++%2F%2F+After+getting+token%2C+we+need+to+persist+the+token+using+%60SecureStore%60+or+any+other+encrypted+storage%0A++++++++%2F%2F+In+the+example%2C+we%27ll+use+a+dummy+token%0A%0A++++++++dispatch%28%7B+type%3A+%27SIGN_IN%27%2C+token%3A+%27dummy-auth-token%27+%7D%29%3B%0A++++++%7D%2C%0A++++%7D%29%2C%0A++++%5B%5D%0A++%29%3B%0A%0A++if+%28state.isLoading%29+%7B%0A++++%2F%2F+We+haven%27t+finished+checking+for+the+token+yet%0A++++return+%3CSplashScreen+%2F%3E%3B%0A++%7D%0A%0A++if+%28state.isLoading%29+%7B%0A++++return+%3CSplashScreen+%2F%3E%3B%0A++%7D%0A%0A++const+isSignedIn+%3D+state.userToken+%21%3D+null%3B%0A%0A++return+%28%0A++++%3CAuthContext.Provider+value%3D%7BauthContext%7D%3E%0A++++++%3CSignInContext.Provider+value%3D%7BisSignedIn%7D%3E%0A++++++++%3CNavigation+%2F%3E%0A++++++%3C%2FSignInContext.Provider%3E%0A++++%3C%2FAuthContext.Provider%3E%0A++%29%3B%0A%7D%0A%0Aconst+RootStack+%3D+createNativeStackNavigator%28%7B%0A++screens%3A+%7B%0A++++Home%3A+%7B%0A++++++if%3A+useIsSignedIn%2C%0A++++++screen%3A+HomeScreen%2C%0A++++%7D%2C%0A++++SignIn%3A+%7B%0A++++++screen%3A+SignInScreen%2C%0A++++++options%3A+%7B%0A++++++++title%3A+%27Sign+in%27%2C%0A++++++%7D%2C%0A++++++if%3A+useIsSignedOut%2C%0A++++%7D%2C%0A++%7D%2C%0A%7D%29%3B%0A%0Aconst+Navigation+%3D+createStaticNavigation%28RootStack%29%3B%0A&dependencies=expo-secure-store%40*%2C%40react-navigation%2Fnative%407.0.0-alpha.14%2C%40react-navigation%2Fnative-stack%407.0.0-alpha.15%2Creact-native-safe-area-context%40*%2Creact-native-screens%40*&platform=web&supportedPlatforms=ios%2Candroid%2Cweb&preview=true&hideQueryParams=true) 
### Screens version

3.29.0

### React Native version

0.73.6

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

iOS simulator

### Device model

iPhone 15 iOS 17.4

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi, @b0iq, since the [original issue](https://github.com/react-navigation/react-navigation/issues/11884#issuecomment-2110460811) has been closed in the react-navigation repo, I'll close it also here.
As I wrote there, if you think this issue should be still considered again, we'll re-open it for sure.

Cheers 👋
