### ISSUE TITLE
Execution failed for task ':react-native-screens:compileDebugKotlin'.

### ISSUE THREAD

**Issue by sirusbaladi** [software-mansion/react-native-screens#2064]
### Description

When running eas build for android specifically I'm getting a build error in the gradlew. 

I'm using managed expo. 
I tried changing kotlin version to 1.6.21 and 1.8.0 but no success so far. here are my settings:
 compileSdkVersion: 34,
          targetSdkVersion: 34,
          buildToolsVersion: "34.0.0",
          kotlinVersikon: "1.6.21",

Detected multiple Kotlin daemon sessions at build/kotlin/sessions
* What went wrong:
Execution failed for task ':react-native-screens:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

### Steps to reproduce

run eas build for android 

### Snack or a link to a repository

N/A

### Screens version

"~3.20.0"

### React Native version

0.71.14

### Platforms

Android

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @yantl0, would you mind posting whole stack trace so that we can see what exactly causes the error to happen?

**Comment by sirusbaladi** [comment]
> same error, fixed by add import at MainActivity.kt file
> 
> `import android.os.Bundle`

not relevant as the issue is using a manged expo environment

**Comment by sirusbaladi** [comment]
the issue is specifically for the version of react native and react-native-screens mentioned above.

**Comment by victor-axelsson** [comment]
I think this might be due to some issue with using an old version of cmake. 

```
cmake_minimum_required(VERSION 3.13)
```

When I install the latest version of cmake via Android studio I can see in the Android Studio SDK manager that it installed an older version, 1.18.1. 

<img width="652" alt="Screenshot 2024-04-03 at 09 50 14" src="https://github.com/software-mansion/react-native-screens/assets/5947764/2fa9cb5f-1e83-472b-abca-c08008e00cff">

Now, even if I uninstall the older version and set the `cmake_minimum_required(VERSION 3.13)`cmake_minimum_required(VERSION 3.6.4111459)` I cannot get it to work. It still installs the old version and I cannot get it to compile with the later version resulting in the compile issues. 

Maybe I'm missing something with caching when I build or something? I have been stuck on this for way too long :)

**Comment by kkafar** [comment]
To provide you with any help I would require you to provide me with any information about the error. All I know up to today is that you have some problems building application, no actual reproduction, no stacktrace, no insights.

**Comment by Nikitashalimov** [comment]
Today I also faced this problem. What I didn't do, nothing helped. 
It turned out that the previous developer added to the project, but did not use it, so I just deleted this package, and everything worked right away

**Comment by kkafar** [comment]
I'm closing this ticket due to lacks [described above](https://github.com/software-mansion/react-native-screens/issues/2064#issuecomment-2051889227).

Ping me if the situation changes.

**Comment by ARSSHEIKH** [comment]
this not work for me

> same error, fixed by add import at MainActivity.kt file
> 
> `import android.os.Bundle`

any update for this issue?

**Comment by SaraChicaD** [comment]
> same error, fixed by add import at MainActivity.kt file
> 
> `import android.os.Bundle`

doing this ^^ plus implementing this last bit of native code in the instructions (my bad!) fixed it for me: https://github.com/software-mansion/react-native-screens?tab=readme-ov-file#android

**Comment by Monir-Shembesh** [comment]
@sirusbaladi did you find a solution to this issue when using expo managed workflow? issue persists in `react-native 0.75.0` and `react-native-screens 3.31.1`

**Comment by panshak** [comment]
@mateus-cazuza have you been able to resolve it?

**Comment by SourabhKanase** [comment]
> Today I also faced this problem. What I didn't do, nothing helped. It turned out that the previous developer added to the project, but did not use it, so I just deleted this package, and everything worked right 








how did youu solve the issue i am facing same issue

**Comment by Samama-Zargham** [comment]
This version worked for me to resolve this issue

    "react-native-screens": "3.27.0",

**Comment by SourabhKanase** [comment]
What version of react native you are using

**Comment by Samama-Zargham** [comment]
> What version of react native you are using
> […](#)

i faced this for 2 projects  on 0.73.1 &  0.72.3 now both are resolve

**Comment by Sleiman2** [comment]
@sirusbaladi  go to your (SDK tools) and check that your are using the correct ( NDK ) it worked for me when I corrected the NDK  version

**Comment by abdullahSolace** [comment]
> This version worked for me to resolve this issue 😻😻😻😻
> 
> ```
> "react-native-screens": "3.27.0",
> ```

this really worked for me. <3

**Comment by Shahzaib114** [comment]
Hi, i resolved these two errors by following the given solution...

> Execution failed for task ':react-native-screens:compileDebugKotlin'.

> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction


This issue might be due to a version mismatch between **react-native-screens** and your **React Native setup**. Certain versions of this library may conflict with specific React Native versions. Please refer to the official documentation for compatibility details.

[https://www.npmjs.com/package/react-native-screens](https://www.npmjs.com/package/react-native-screens)

![Image](https://github.com/user-attachments/assets/c5e2dd30-b1b0-423f-ac79-192aca5268ca)

**Comment by Sheraz008** [comment]
@Samama-Zargham  its working Thanks .....❤️

**Comment by Pattygeek** [comment]
> Update `react-native-screens` for 3.27.0 work for me.
> 
> ```
> npm install react-native-screens@3.27.0
> ```
> 
> I had that update the `android/build.gradle` too:
> 
> ```
> compileSdkVersion = 34
> targetSdkVersion = 34
> kotlinVersion = '1.8.22'
> 
> dependencies {
>         ...rest
>         classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
> }
> ```
> 
> But this throw a new error when run android build:
> 
> ```
> * What went wrong:
> Execution failed for task ':app:checkDebugDuplicateClasses'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
>    > Duplicate class androidx.lifecycle.ViewModelLazy found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.5.0-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.0)
>      Duplicate class androidx.lifecycle.ViewTreeViewModelKt found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.5.0-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.0)
>      
>      Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
> ```
> 
> I'll bring you news as soon as it's resolved

this really worked, thanks
