### ISSUE TITLE
iOS react-navigation not fullScreen

### ISSUE THREAD

**Issue by Byeong-soo** [software-mansion/react-native-screens#2073]
### Description

I use React navigation and Screens 'absoluteFill' doesn't work properly in iOS environment. There is some margin at the bottom. Android is fine, but bug only occur in IOS. 

I think absoluteFill is not working properly on the screen in 'NativeStackView.native.tsx'.

### Steps to reproduce

just use react navigation Stack.screen in iOS

### Snack or a link to a repository

https://github.com/react-navigation/react-navigation

### Screens version

3.22.1

### React Native version

0.73.1

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey, I fail to spot the issue in my test application. Please provide us with proper reproduction & screenshots.
