### ISSUE TITLE
Error upon running npm install on 3.30.0

### ISSUE THREAD

**Issue by Lump01** [software-mansion/react-native-screens#2079]
### Description

I get this after running `npm install` with version 3.30.0
```
npm ERR! code 1
npm ERR! path /Users/username/digapps/passare/passare-mobile/node_modules/react-native-screens
npm ERR! command failed
npm ERR! command sh -c git submodule update --init --recursive && (cd react-navigation && yarn)
npm ERR! sh: line 0: cd: react-navigation: No such file or directory

npm ERR! A complete log of this run can be found in: /Users/username/.npm/_logs/2024-03-25T16_15_30_292Z-debug-0.log
```
The following postinstall script is what is breaking this I believe:
```
"postinstall": "git submodule update --init --recursive && (cd react-navigation && yarn)",
```
It seems there was an issue with the publishing of the react-navigation [branch](https://github.com/react-navigation/react-navigation/tree/523fa4f3afb7c428a8370bfd83933c0163224e66) the latest version of react-native-screens is trying to pull in.

### Steps to reproduce

Run `npm install` with `"react-native-screens": "^3.30.0"`

### Snack or a link to a repository

https://snack.expo.dev/FNyvGqV3DmVi3cXhmElYS

### Screens version

3.30.0

### React Native version

0.72.3

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

None

### Device

None

### Device model

N/A

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @Lump01, thanks for submitting this PR. Are you certain this issue happens on `3.29.0` version? We've added the change with submodules in the 3.30.0 version.

**Comment by akeva001** [comment]
I am also unable to install any version of the package due to this issue.

**Comment by Lump01** [comment]
Apologies, it was 3.30.0. I had the version as "^3.29.0" with the caret in front of it so it was downloading 3.30.0 in the background.
