### ISSUE TITLE
Issue on installation of latest version

### ISSUE THREAD

**Issue by mohd-ramzan-1** [software-mansion/react-native-screens#2080]
### Description

npm ERR! command sh -c git submodule update --init --recursive && (cd react-navigation && yarn)

### Steps to reproduce

npm ERR! command sh -c git submodule update --init --recursive && (cd react-navigation && yarn)

### Snack or a link to a repository

no link

### Screens version

3.30.0

### React Native version

0.72.12

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

simulator 

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @mohd-ramzan-1, thank you for creating this PR. This issue is already known, please refer to the pinned issue [here](https://github.com/software-mansion/react-native-screens/issues/2078).
Thanks you for your patience 🙏
