### ISSUE TITLE
Android Build Error - Execution failed for task ':react-native-screens:configureCMakeRelWithDebInfo'

### ISSUE THREAD

**Issue by FraserKemp** [software-mansion/react-native-screens#2082]
### Description

When assembling a dev release build on android I get a build error. 

Error shown is :

* What went wrong:

Execution failed for task ':react-native-screens:configureCMakeRelWithDebInfo'.
> [CXX1405] error when building with cmake using /Users/vagrant/git/node_modules/react-native-screens/android/CMakeLists.txt: Build command failed.
  Error while executing java process with main class com.google.prefab.cli.AppKt with arguments {--build-system cmake --platform android --abi armeabi-v7a --os-version 24 --stl c++_shared --ndk-version 24 --output /Users/vagrant/git/node_modules/react-native-screens/android/.cxx/RelWithDebInfo/513j6x30/prefab/armeabi-v7a/prefab}
  
  Usage: prefab [OPTIONS] [PACKAGE_PATH]...
  
  Error: Missing argument "PACKAGE_PATH".

### Steps to reproduce

- Create a new project "npx react-native@0.68.7 init RNScreenTest --version 0.68.7"
- run yarn install
- Run project via release variant in android studio or via command line
- See error

ERROR : > Task :react-native-screens:configureCMakeRelWithDebInfo FAILED
C/C++: prefabUsage: prefab [OPTIONS] [PACKAGE_PATH]...
C/C++: prefabError: Missing argument "PACKAGE_PATH".

### Snack or a link to a repository

https://github.com/FraserKemp/test-react-native-screens

### Screens version

3.30.1

### React Native version

0.68.7

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

None

### Acknowledgements

Yes

**Comment by hau1412** [comment]
You too, i need fix version

**Comment by hau1412** [comment]
I downgrade version [3.29.0], it work

**Comment by FraserKemp** [comment]
I also downgraded for now 👍

**Comment by tboba** [comment]
Hi @FraserKemp, thanks for submitting this issue! Let me investigate it 🔎

**Comment by kumarGautamAramark** [comment]
I am also having same issue - 
React native - 0.70.6
react-native-screens - "^3.15.0"

**Comment by tboba** [comment]
@kumarGautamAramark This seems to be issue with React Native, rather than error from Screens. I found that there were some issues with prefab already in 0.70 - https://github.com/facebook/react-native/issues/34871

**Comment by kumarGautamAramark** [comment]
@wieckowskimateusz yeah, setting "3.29.0" did resolve the issue. Thank you.

**Comment by tboba** [comment]
I can confirm this exists on my side 👍 We'll try find a solution for that. Thanks!

**Comment by ardneved** [comment]
Confirming downgrading to "3.29.0" instead of "^3.29.0" did resolve the issue.

**Comment by frankfuu** [comment]
Yep 3.29 works for me. Adding it to my lock file

```
react-native-screens@^3.8.0:
  version "3.29.0"
  resolved "https://registry.yarnpkg.com/react-native-screens/-/react-native-screens-3.29.0.tgz#1dee0326defbc1d4ef4e68287abb32a8e6b76b29"
  integrity sha512-yB1GoAMamFAcYf4ku94uBPn0/ani9QG7NdI98beJ5cet2YFESYYzuEIuU+kt+CNRcO8qqKeugxlfgAa3HyTqlg==
  dependencies:
    react-freeze "^1.0.0"
    warn-once "^0.1.0"
```

**Comment by usamaabutt** [comment]
Hi @tboba I am also getting this issue here's the detail of my project.

"react-native": "0.69.12"
"react-native-screens": "^3.29.0",

And I had a patch previously for version `3.29.0` and it was working fine 3 days before the last version release came out `3.30.1`.

**Patch:**
<img width="1250" alt="Screenshot 2024-03-28 at 1 18 13 PM" src="https://github.com/software-mansion/react-native-screens/assets/44516486/b32b2183-4bb6-41fd-a60b-07b867ce6837">

**build issue:**
<img width="1242" alt="Screenshot 2024-03-28 at 1 16 08 PM" src="https://github.com/software-mansion/react-native-screens/assets/44516486/2dcf4080-1827-4115-8fce-3bafad98d9d1">


Please provide a solution for this.

**Comment by usamaabutt** [comment]
> > I am also having same issue - React native - 0.70.6 react-native-screens - "^3.15.0"
> 
> instead of "^3.15.0" set "3.29.0" (without ^)

This fixed my issue, Thanks @wieckowskimateusz  for saving my day!

**Comment by tboba** [comment]
Hi everyone, thanks for confirming that on your scenario this error also happens! I can observe, that error with `PACKAGE_PATH` happens only on projects with the React Native 0.68. However, the error with `ReactAndroidConfig.cmake` happens only on projects with the React Native 0.69 - 0.70. I've already discussed this issue with @piaskowyk and we're taking a look what went wrong 👀

**Comment by pradeep-tomer** [comment]
> I am also having same issue - React native - 0.70.6 react-native-screens - "^3.15.0"
You have getting same issue in react-native-screen with react-native 0.70.10 then I have update react-native-screen with 3.18.0 then my issue has been resolved

**Comment by tboba** [comment]
Hi all! This fix has been included in the newest release of React Native Screens: **3.31.0-rc.0**! 🎉 
Please note that this is a release candidate for upcoming version of Screens: 3.31.0. If you encounter any issues or inconveniences, please reach out to use by submitting an issue! Thanks 💙 

cc @FraserKemp @hau1412 @kumarGautamAramark @wieckowskimateusz @ardneved @frankfuu @usamaabutt @pradeep-tomer

**Comment by FraserKemp** [comment]
@tboba Awesome thanks for the speedy fix, I will test this is working again next week and let you know if I have issues!!

**Comment by zanotta** [comment]
Using version 3.29.0 works for me.

RN 0.68.2

**Comment by kmaschke85** [comment]
Same here with 3.31.1. Downgrade to 3.29.0 seems to work for now.

**Comment by Gowtham1802** [comment]
<img width="960" alt="Screenshot 2024-06-10 164358" src="https://github.com/software-mansion/react-native-screens/assets/128211353/1cee96fe-1c8f-47ac-be8d-07a0331f7f18">


i faced this type of error in android studio, please give me correct solution

**Comment by zhuweiyou** [comment]
> I downgrade version [3.29.0], it work

 Thank you. It works for me.

**Comment by tboba** [comment]
@driiftkiing Are you using old architecture, or the new one? Please keep in mind that according to [the table of supported versions of react-native](https://github.com/software-mansion/react-native-screens/blob/main/README.md#supported-react-native-version), for react-native-screens 3.33.0+ you should use React Native 0.75 or higher.

**Comment by DarshanPuli** [comment]
im still getting a build fail 
react native version : 0.76.0
react native screens version : 3.35.0

**Comment by aurangs7** [comment]
Getting: 
`> Task :react-native-screens:generateCodegenSchemaFromJavaScript FAILED
`

with:
```
"react-native-screens": "^3.34.0"
 "react-native": "0.76.1"
```

**Comment by MaratSHU** [comment]
> Getting: `> Task :react-native-screens:generateCodegenSchemaFromJavaScript FAILED `
> 
> with:
> 
> ```
> "react-native-screens": "^3.34.0"
>  "react-native": "0.76.1"
> ```

same error for: 
```
"react-native": "0.76.1",
"react-native-screens": "^4.0.0"
```

**Comment by aurangs7** [comment]
The react native version upgrade from 0.75.4 to 0.76.1 works fine with iOS, but the build is failing on Android. I spent two days finding the solution, but finally, I left it at 0.75.4 for now. 

Let me know if you find any solution to it @MaratSHU 

Thanks

**Comment by LinhLM23496** [comment]
+1

**Comment by mateus-bernart** [comment]
Also 0.76.1 React native version error on react native screens version 3.30, 3.31
