### ISSUE TITLE
Not able to navigate to a nested modal navigator

### ISSUE THREAD

**Issue by hollanderbart** [software-mansion/react-native-screens#2085]
### Description

When trying to open a nested modal, the screen isn't opening. After some research this is due to the `__block` keyword.
This seems to be wrongly fixed in this PR: https://github.com/software-mansion/react-native-screens/commit/471127e26aa23eed4d14388a9646bf83de5e8699

Changing the following line will fix the issue:

```
  __block UIViewController *changeRootController = _controller;
```

into 

```
UIViewController *changeRootController = _controller;
```

### Steps to reproduce

1. Use Test1829 and open a nested modal

### Snack or a link to a repository

not-needed

### Screens version

3.30.1

### React Native version

0.72.x

### Platforms

iOS

### Acknowledgements

Yes

**Comment by hollanderbart** [comment]
@[kkafar](https://github.com/software-mansion/react-native-screens/commits?author=kkafar)

Do you know why you added the `__block` statement here? https://github.com/software-mansion/react-native-screens/blob/471127e26aa23eed4d14388a9646bf83de5e8699/ios/RNSScreenStack.mm#L390

**Comment by hollanderbart** [comment]
@kkafar When do you plan to create a new release?

**Comment by kkafar** [comment]
Only thing holding me back is to allocate a time for library testing before releasing a version (and actually we have slight problem on main rn, but it should be fixed today).

I would say you can expect one early next week, but this is a rough estimate.

**Comment by hollanderbart** [comment]
@kkafar how are you doing? I don't want to ask you again but please don't forget ;-)
