### ISSUE TITLE
Types on FullWindowOverlay does not allow to set style props (even if used in examples

### ISSUE THREAD

**Issue by wcastand** [software-mansion/react-native-screens#2099]
### Description

Typescript types for FullWindowOverlay doesn't accept a style props to be passed for android case.

One of your example pass a style to the component: https://github.com/software-mansion/react-native-screens/blob/a8bb418a8428befbb264ef958a5d7f7ea743048a/FabricTestExample/src/Test1096.tsx#L37

Here is the error i get :
![Screenshot 2024-04-10 at 10 59 30](https://github.com/software-mansion/react-native-screens/assets/2178244/7ff54ec8-f2e8-430d-908c-b579cbd076e3)

### Steps to reproduce

Create a typescript project and add a style props to FullWindowOverlay

### Snack or a link to a repository

https://snack.expo.dev/@wcastand/spontaneous-green-crackers

### Screens version

~3.29.0

### React Native version

0.73.6

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by alduzy** [comment]
You should not be using FullWindowOverlay in an android app, there is a warning for that.
Please have a look at how the component is currently implemented: https://github.com/software-mansion/react-native-screens/blob/main/src/components/FullWindowOverlay.tsx
I recommend you use [platform specific code](https://reactnative.dev/docs/platform-specific-code) if you want to use this component in your iOS app and just use View element on android.
We're planning to add android support in the near future, however the style prop is not going to be added as it may conflict with component's functionality.
