### ISSUE TITLE
Strange flicker when you scroll up a modal with NativeStack in iOS

### ISSUE THREAD

**Issue by nicolascavallin** [software-mansion/react-native-screens#2112]
### Description

I originally published the issue in `react-navigation`: https://github.com/react-navigation/react-navigation/issues/11929

### Current behavior

When you open a `presentation: 'modal'`, in Native Stack on iOS, and you try to "swipe up", seems a strange black flicker at the bottom of the screen.

https://github.com/react-navigation/react-navigation/assets/22961489/bb11dc52-96ac-459a-bc8e-9f32942fc296

### Expected behaviour

In native iOS applications this does not occur, so it shouldn't happen.

### Build type and Device

This is happening in both, `debug` and `release` builds, and `simulator` and `real device`.

### Steps to reproduce

1. In iOS, using `@react-navigation/native-stack`, navigate to screen with `presentation: modal`
2. Then, try to "slide up" when the screen is opened as modal

### Snack or a link to a repository

https://snack.expo.dev/@nicolascavallin/grounded-indigo-cashew

### Screens version

^3.30.1

### React Native version

0.73.6

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey, thanks for reporting!

I am aware this issue & it should be handled with #2045. This is the same issue as #1722.

I won't close this issue yet, but don't mind if I do as replicate.

**Comment by visibly** [comment]
@nicolascavallin were you able to solve it?

**Comment by nicolascavallin** [comment]
> @nicolascavallin were you able to solve it?

Nope, and I didn't work on it, sorry.

**Comment by lukastragan** [comment]
@kkafar Hello, I believe this issue still persists, will you reopen this issue, or should I create a new one?

**Versions:**
react-native-screens: 4.6.0
react-native: 0.77.0

This occurs on both architectures, in both debug and release builds, and also on simulator and real device.

Here is a link to a reproduction: [GitHub Repo](https://github.com/lukastragan/react-native-screen-modals)

And here is a video demonstrating the issue:

https://github.com/user-attachments/assets/b33a7e2c-5fd7-4764-b627-e75dd0e36736

**Comment by kkafar** [comment]
Hey, I'm aware of this problem. 

It looks right now that I won't be able to solve this until we get API for synchronous layout on UI thread (synchronous state updates?) in `react-native`. AFAIK its work in progress

There is a workaround that I've applied to `formSheet` presentation, but it leads to different issues (especially regarding scrollview in sheet).

**Comment by nicolascavallin** [comment]
`formSheet` presentation is working without this bug, but the UI implementation is quite different, so is not as easy as change `presentation: "modal"` into `presentation: "formSheet"`
