### ISSUE TITLE
issue related to react-native-screen

### ISSUE THREAD

**Issue by iCode-Stack** [software-mansion/react-native-screens#2114]
### Description

A problem occurred configuring project ':react-native-screens'.
> [CXX1101] NDK at C:\Users\Coding Expert\AppData\Local\Android\Sdk\ndk\26.1.10909125 did not have a source.properties file

### Steps to reproduce

when i add the library giving the error mentioned in description.

### Snack or a link to a repository

nill

### Screens version

3.31.1

### React Native version

0.74

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

A20 Samsungh

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @iCode-Stack, this looks rather like issue with your development environment configuration. Have you tried actually removing / installing NDK again (silly but sometimes effective) 😅 

If you're new to development you can easily google resources with instructions on how to install Android NDK via Android Studio.

I'll close the ticket as I do not consider it to be a `react-native-screens` issue, will reopen if that changes.

**Comment by metacop** [comment]
![image](https://github.com/software-mansion/react-native-screens/assets/56640826/ecc25ce1-14ce-44e5-8ef6-1914eb5a2502)

I have exactly the same problem. with react native 0.74. any solution?

**Comment by metacop** [comment]
> Hey @iCode-Stack, this looks rather like issue with your development environment configuration. Have you tried actually removing / installing NDK again (silly but sometimes effective) 😅
> 
> If you're new to development you can easily google resources with instructions on how to install Android NDK via Android Studio.
> 
> I'll close the ticket as I do not consider it to be a `react-native-screens` issue, will reopen if that changes.

why do you close it? If not, is there any solution?

**Comment by metacop** [comment]
> ### Description
> A problem occurred configuring project ':react-native-screens'.
> 
> > [CXX1101] NDK at C:\Users\Coding Expert\AppData\Local\Android\Sdk\ndk\26.1.10909125 did not have a source.properties file
> 
> ### Steps to reproduce
> when i add the library giving the error mentioned in description.
> 
> ### Snack or a link to a repository
> nill
> 
> ### Screens version
> 3.31.1
> 
> ### React Native version
> 0.74
> 
> ### Platforms
> Android
> 
> ### JavaScript runtime
> Hermes
> 
> ### Workflow
> React Native (without Expo)
> 
> ### Architecture
> Fabric (New Architecture)
> 
> ### Build type
> Debug mode
> 
> ### Device
> Real device
> 
> ### Device model
> A20 Samsungh
> 
> ### Acknowledgements
> Yes

![image](https://github.com/software-mansion/react-native-screens/assets/56640826/fc2a2e22-d3d9-4228-8cff-e7d0e1dd5b97)
I found the solution. was what the friend above said. now works with react native 0.74

**Comment by 0xpranv** [comment]
> > ### Description
> > A problem occurred configuring project ':react-native-screens'.
> > > [CXX1101] NDK at C:\Users\Coding Expert\AppData\Local\Android\Sdk\ndk\26.1.10909125 did not have a source.properties file
> > 
> > 
> > ### Steps to reproduce
> > when i add the library giving the error mentioned in description.
> > ### Snack or a link to a repository
> > nill
> > ### Screens version
> > 3.31.1
> > ### React Native version
> > 0.74
> > ### Platforms
> > Android
> > ### JavaScript runtime
> > Hermes
> > ### Workflow
> > React Native (without Expo)
> > ### Architecture
> > Fabric (New Architecture)
> > ### Build type
> > Debug mode
> > ### Device
> > Real device
> > ### Device model
> > A20 Samsungh
> > ### Acknowledgements
> > Yes
> 
> ![image](https://private-user-images.githubusercontent.com/56640826/327051874-fc2a2e22-d3d9-4228-8cff-e7d0e1dd5b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MzM0MDUsIm5iZiI6MTcyMDYzMzEwNSwicGF0aCI6Ii81NjY0MDgyNi8zMjcwNTE4NzQtZmMyYTJlMjItZDNkOS00MjI4LThjZmYtZTdkMGUxZGQ1Yjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE3MzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0OGY2MGQ1ZWM4ZDdjNzU3MThiNjk5ODE2OTRhNTg0OGFkMDgzYjdiMjE1M2IwOGUzMWIyZGI3NWYyMWY1YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aJgXqtQip-hWz2O-cbJdnkNQTJr5oskJc417y-ECh9E) I found the solution. was what the friend above said. now works with react native 0.74

Hey, thank you so much. This fixed the issue i was trying to resolve

**Comment by jorgedelrio-bax** [comment]
It seems that in my environment the folder "/home/user/Android/Sdk/ndk/26.1.10909125" exists, but it was empty. The way to reproduce the error is to create an empty directory with the same version specified in the build.gradle (ndkVersion = "26.1.10909125") for the NDK and try to build the app. I believe that some other tool created the directory but didn't install the NDK, fooling the other tools into thinking that the NDK was installed when, in reality, it was not.

**Comment by hamzadevlpr** [comment]
finally, I found the error solved

**Comment by KirtirajM** [comment]
I solved this same error by changing ndkVersion  in build.gradle file 
from  ndkVersion = "26.1.10909125"   to--->  ndkVersion = "28.0.12433566"

**Comment by czheisenberg** [comment]
> I solved this same error by changing ndkVersion in build.gradle file from ndkVersion = "26.1.10909125" to---> ndkVersion = "25.1.8937393"

Thank you!!!

**Comment by zubyrbutt** [comment]
this solution worked for me. https://github.com/software-mansion/react-native-reanimated/issues/4712#issuecomment-1852734366
