### ISSUE TITLE
> Could not create task ':react-native-screens:compileReleaseKotlin'.    > KOTLIN_1_9 

### ISSUE THREAD

**Issue by dellta1291** [software-mansion/react-native-screens#2145]
### Description
How to fix this error : 
help me please

Could not determine the dependencies of task ':react-native-screens:extractReleaseAnnotations'.
> Could not create task ':react-native-screens:compileReleaseKotlin'.
   > KOTLIN_1_9  

### Steps to reproduce

when build apk      

### Snack or a link to a repository

https://github.com/software-mansion/react-native-screens  

### Screens version

3.27.0  

### React Native version

0.72.14

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

samsung a9

### Acknowledgements

Yes

**Comment by onetrace-abdullah** [comment]
We're also getting the same error in Bitrise, we recently upgraded to React Native 0.74.1, which involved converting the java files into kotlin files.

Strangely enough the Android build works fine locally (MacOS Sonoma 14.4.1).

I saw another issue referencing the same error: https://github.com/software-mansion/react-native-reanimated/issues/5498, where some people were able to solve the issue by using a MacOS environment instead of a Linux machine, however the same error was still happening even after moving to a MacOS builder in Bitrise.

Here's the error we're getting:

> \> Task :app:mergeExtDexRelease
> \> Task :app:mergeReleaseJavaResource
> \> Task :react-native-screens:configureCMakeRelWithDebInfo[arm64-v8a] FAILED
>
> FAILURE: Build failed with an exception.
>
> \* What went wrong:
> Execution failed for task ':react-native-screens:configureCMakeRelWithDebInfo[arm64-v8a]'.
> \> [CXX1210] /Users/vagrant/git/node_modules/react-native-screens/android/CMakeLists.txt [REDACTED]|arm64-v8a : No compatible library found
>
> \* Try:
> \> Run with --stacktrace option to get the stack trace.
> \> Run with --info or --debug option to get more log output.
> \> Run with --scan to get full insights.
> \> Get more help at https://help.gradle.org/.
> BUILD FAILED in 4m 49s
> 525 actionable tasks: 525 executed
> Run: build task failed: exit status 1

**Comment by tboba** [comment]
Hi, @dellta1291! Thanks for filling this issue.
Have you checked if the same error happens on the newest version of react-native-screens? Could you tell us which version of kotlin are you using in your project? Also, please send the output from `npx react-native info` command and your `build.gradle` file from your app, if it's possible.

**Comment by tboba** [comment]
@onetrace-abdullah this looks like a different error, not related to this issue. Which Android NDK do you have installed? You can check such thing by going to Android Studio -> Settings/Preferences -> Languages & Frameworks -> Android SDK -> SDK Tools (tab) -> scroll down to NDK).

**Comment by onetrace-abdullah** [comment]
@tboba Sorry I just noticed the error is not actually the same, my bad. The NDK version on Bitrise is `26.1.10909125`, which is the same as what I see in Android Studio locally, however I also have `23.1.7779620` installed so not sure which one Android Studio is actually using.

In Bitrise we use their Ubuntu 22.04 docker image, and all the tooling versions they include are listed in https://stacks.bitrise.io/announcements/ubuntu-22/

Should I perhaps open a separate ticket?

**Comment by kkafar** [comment]
We definitely need a reproduction here, otherwise providing you with any help is difficult & constricted.

**Comment by kkafar** [comment]
Also I'm gonna redirect you & whole conversation to

* https://github.com/software-mansion/react-native-screens/issues/2067

as we have multiple instances of this issue already.
