### ISSUE TITLE
bug(iOS): transitionStart is not triggered for anything but default navigation

### ISSUE THREAD

**Issue by hirbod** [software-mansion/react-native-screens#2178]
### Description

`transitionStart` is never reported for `presentation` modes other than the **default**. When switching to `modal` or `transparentModal`, it only reports `transitionEnd`. When closing the modal, it reports both `transitionStart` and `transitionEnd`.

If the target is pushed normally, it works correctly. This bug occurs only on iOS, not on Android. Open the snack with iOS and check the logs. I have added two buttons, both pushing to the same screen. Only the default one triggers both start and end, while the modal one only emits the end.

### Steps to reproduce

Open my Snack and watch the console while testing both buttons.

transitionStart and transitionEnd should work for every presentation mode.
Here is a video showcasing everything:

https://github.com/software-mansion/react-native-screens/assets/504909/6f05d06e-89a9-4ace-838a-ee69206d3d09

### Snack or a link to a repository

https://snack.expo.dev/@hirbod/react-navigation-transition-event-bug?platform=ios

### Screens version

3.21.0

### React Native version

0.74.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

Real device

### Device model

All iOS devices

### Acknowledgements

Yes

**Comment by hirbod** [comment]
Same issue applies to useTransitionProgress and useReanimatedTransitionProgress by the way.

**Comment by maksg** [comment]
Hey, @hirbod! Thanks for reporting the issue.
It should be fixed in `react-navigation` `6.10.0` by this PR https://github.com/react-navigation/react-navigation/pull/11803.
If you're still having problems with this, please open a separate issue with reproduction steps.

**Comment by hirbod** [comment]
@maksg did you test my issue with the current update before blindly closing it?

**Comment by maksg** [comment]
@hirbod Yes, we did test that with your example, it wasn't blindly closed. It was reproducible with the project you provided and the issue disappeared when we upgraded `react-navigation` to `6.10.0` in your sample.

**Comment by hirbod** [comment]
Thank you very much. I think I misunderstood your reply, thank you very much!

**Comment by hirbod** [comment]
@maksg I've just confirmed that it's working!
