### ISSUE TITLE
ReactNativeScreen enableScreens is not  a function

### ISSUE THREAD

**Issue by tarunkonda2016** [software-mansion/react-native-screens#219]
![image](https://user-images.githubusercontent.com/31408692/68462121-e5c88c00-0231-11ea-934e-c08433ab636c.png)

 "react-native-screens": "^2.0.0-alpha.8",

index.js file 
import {enableScreens,} from 'react-native-screens';
enableScreens();

**Comment by manny2011** [comment]
i got the same one.

**Comment by jstheoriginal** [comment]
It used to be called `useScreens` in earlier betas so likely beta 8 it was called that. So either use the old name or update to latest.

**Comment by danjersoft** [comment]
i had the same issue after upgrading. clearing the RN cache solved it for me:
```
node node_modules/react-native/local-cli/cli.js start --reset-cache
```

**Comment by tudousdk** [comment]
you are right

**Comment by Albert0405** [comment]
I have the same problem, any fix to this?

**Comment by WoLewicki** [comment]
@tarunkonda2016 is your issue solved? Can I close it?

**Comment by WoLewicki** [comment]
I am closing it. Feel free to comment if something is not ok.
