### ISSUE TITLE
there is an additional blank space at the bottom of the screen

### ISSUE THREAD

**Issue by one-god** [software-mansion/react-native-screens#2201]
### Description

When I'm using the @react-navigation/native-stack navigation library in a mixed native and React Native (RN) development environment, if I navigate from a native (non-React Native) screen to a React Native screen, there is an additional blank space or padding at the bottom of the React Native screen. However, this blank space or padding disappears when I navigate to another React Native screen and then return to the previous React Native screen.

### Steps to reproduce

https://github.com/software-mansion/react-native-screens/assets/25094341/6acae914-8fb8-4728-84fd-7853e7f9d879

### Snack or a link to a repository

Platforms  IOS

### Screens version

3.31.1

### React Native version

0.72.14

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @one-god, please provide us with a reproduction (create a repo with the example you show on recording & share the link), otherwise it will be hard to help you here.

**Comment by one-god** [comment]
@kkafar Please help me, thank you.
`//testStack
import {createNativeStackNavigator as createStackNavigator } from '@react-navigation/native-stack'
import TextScreen from '@/screens/Text/TextScreen'
import TextTwoScreen from '@/screens/Text/TextTwoScreen'
const Stack = createStackNavigator()
 function TestStack(props: any) {
 <Stack.Navigator
      initialRouteName={"TextScreen"}
      screenOptions={{
        title: 'test',
        headerBackTitleVisible: false,
        headerTitleAlign: 'center',
        headerShadowVisible: false,
        headerTitleStyle: {
          color: '#333',
          fontSize: 16,
        },
      }}
    >
      {/*  测试首页*/}
      <Stack.Screen
          name="TextScreen"
          component={TextScreen}
          initialParams={params}
          options={{
            title: 'test',
        }}
      />
      {/*  测试two*/}
      <Stack.Screen
          name="TextTwoScreen"
          component={TextTwoScreen}
          initialParams={params}
          options={{
            title: 'test',
          }}
      />
  </Stack.Navigator>
}
          //RootStack
 export default function RootStack({
     <NavigationContainer
            ref={navigationRef}
            linking={linking}
            fallback={<Fallback />}
            onReady={() => {}}
        >
      <Stack.Navigator
          initialRouteName={initialRoute}
          screenOptions={{
            gestureEnabled: false,  
            headerBackTitleVisible: false,
            headerStyle: {
              backgroundColor: 'transparent',
            },
            headerShown: false,
          }}
      >
            <Stack.Screen
              name="TestStack"
              component={TestStack}
              initialParams={params}
            />
      </Stack.Navigator>
</NavigationContainer>

//APP.tsx
import { RootSiblingParent } from 'react-native-root-siblings'
import { SafeAreaProvider } from 'react-native-safe-area-context'
import { GestureHandlerRootView } from 'react-native-gesture-handler'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import Toast from 'react-native-toast-message'
const App = (props) => {
  return (
   <RootSiblingParent>
      <SafeAreaProvider>
        <GestureHandlerRootView style={{ flex: 1 }}>
              <RootStack
                {...props}
                initialRoute={initialRoute}
                params={params}
              />
        </GestureHandlerRootView>
        <Toast config={toastConfig} />
      </SafeAreaProvider>
    </RootSiblingParent>
  )
}
//---TextScreen 
import { useNavigation } from '@react-navigation/native'
import React from 'react'
import { View,Text,TouchableOpacity } from 'react-native'
const TextScreen = () => {
  const navigation = useNavigation() as any
  return (
    <View style={{ flex: 1, backgroundColor: '#333',justifyContent: 'center',alignItems: 'center' }}>
      <Text style={{ color: '#fff', justifyContent: 'center', alignItems: 'center', textAlign: 'center' }}>TextScreen body</Text>
          <TouchableOpacity onPress={() => navigation.navigate('TextTwoScreen')} style={{paddingVertical:20,paddingHorizontal:20,borderRadius:10,backgroundColor:'red'}}><Text>push</Text></TouchableOpacity>
    </View>
  )
} 
///TextTwoScreen
import { useNavigation } from '@react-navigation/native'
import React from 'react'
import { View,Text } from 'react-native'
const TextScreen = () => {
  return (
    <View style={{ flex: 1, backgroundColor: '#333',justifyContent: 'center',alignItems: 'center' }}>
      <Text style={{ color: '#fff',justifyContent: 'center',alignItems: 'center',textAlign: 'center' }}>inside TextScreen body</Text>
    </View>
  )
} 
`

**Comment by kkafar** [comment]
Hey @one-god, I allowed myself to format the code you pasted in your response.

1. I mean, it would be best if you provided a ready-to-go repository, as I've asked, because that snippet does not work.
2. You provided me only with JS part of the code - how does that relate to the problem description, namely that the issue happens when navigating between purely native and React Native screen?
