### ISSUE TITLE
bug(android): Direct event name for 'RNSScreen' doesn't correspond to the naming convention

### ISSUE THREAD

**Issue by Gregoirevda** [software-mansion/react-native-screens#2215]
### Description

Bug in android when the app is bootstrapped
`Direct event name for 'RNSScreen' doesn't correspond to the naming convention, expected 'topEventName'->'onEventName', got 'topHeaderBackButtonClickedEvent'->'onHeaderBackButtonClicked'`

### Steps to reproduce

Build app and open Logcat in AndroidStudio

### Snack or a link to a repository

https://snack.expo.dev/

### Screens version

3.29.0

### React Native version

0.73.8

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Is this a crash or only a warning?

**Comment by kkafar** [comment]
I just noticed that you're reporting screens 3.29.0. This should not happen on most recent version of the library. Ping me it this is not the case & I'll reopen.
