### ISSUE TITLE
Elevation shadow in header appears on android after navigating forward and back (v3.32.0)

### ISSUE THREAD

**Issue by outaTiME** [software-mansion/react-native-screens#2220]
### Description

Hi there, 
after upgrading to version 3.32, on android when the header shadow is disabled, and you navigate forward and then back, the elevation shadow appears in the header, in the previous version (3.31.1) this does not happen, can it be that the new version has brought a regression ?

### Screens version

3.32.0

### React Native version

0.74.2

### Platforms

Android

**Comment by alduzy** [comment]
Hi @outaTiME, thanks for reporting. Although I can't see any repro or screenshots I think it's the same problem as here:
https://github.com/software-mansion/react-native-screens/issues/2212
I am closing this issue as completed since the fix is waiting to be released.

**Comment by outaTiME** [comment]
Exactly, seems to be the same error, thanks 🙏
