### ISSUE TITLE
When enabled fullScreenGestureEnabled, the animation changed from Native one to React Navigation animation once goes back triggered

### ISSUE THREAD

**Issue by xiaomei7** [software-mansion/react-native-screens#2227]
### Description

Basically the title.
In my project, I enabled `fullScreenGestureEnabled` for stack options. I went on using the app with no problem but once I go back then go into it again or any other screens, the animation changes from Native behaviour to React Navigation one.

### Steps to reproduce

1. set fullScreenGestureEnabled to true.
2. App must have more than one stack screen.
3. Navigate to one, then swipe back.
4. Navigate again, the animation looks different.

### Snack or a link to a repository

https://github.com/xiaomei7/ReactScreenBugExample

### Screens version

3.27.0

### React Native version

0.73.8

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
@xiaomei7 I was just about to ask you for recording, cause I'm trying to reproduce & I can't spot the issue. 

Please note that you video did not upload.

**Comment by kkafar** [comment]
Oh, I can see it 😱 






| Initial | After swipeback |
|--------|--------|
| <video width="320" height="240" controls src="https://github.com/software-mansion/react-native-screens/assets/50801299/68dd565b-d6bf-45e0-9b74-617f3e1b7e13"></video> | <video width="320" height="240" controls src="https://github.com/software-mansion/react-native-screens/assets/50801299/c68f1d47-a40a-4cdb-85f5-14e5385378e9"></video> |

**Comment by xiaomei7** [comment]
Yes, sorry for the video, didn't see it haven't upload, but the animation is very subtle yeah😵

**Comment by kkafar** [comment]
I'm not sure whether this is a bug or iOS feature yet. Will look into it sometime this / next week and update you here.

**Comment by xiaomei7** [comment]
many thanks
