### ISSUE TITLE
Wrong layout when updating headerLeft and headerRight on new arch

### ISSUE THREAD

**Issue by janicduplessis** [software-mansion/react-native-screens#2231]
### Description

When the headerLeft is removed and headerRight has updated layout at the same time in native-stack, it results in the headerRight having incorrect layout.

Workaround:

If I update them in separate ticks (using setTimeout) layout is correct.

### Steps to reproduce

Using [this code](https://gist.github.com/janicduplessis/9e3e056aa2fb2744936615ce81dc72be) in FabricExample app HeaderOptions.tsx

- Go to "Header Options" example
- Click the "Header large item" button
- See that the header right item green square is off screen
- Comment out [line 59](https://gist.github.com/janicduplessis/9e3e056aa2fb2744936615ce81dc72be#file-headeroptions-tsx-L59) where we set `headerLeft`
- Click the "Header large item" button
- See that the header right item green square has now correct layout

Updating both headerLeft and headerRight (bug):

<img width="374" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/2677334/de4fca62-ed62-450a-9608-31811161516a">

<img width="370" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/2677334/9842f7a4-1949-4e97-8b85-09085c19c853">

Updating only headerRight (correct)

<img width="371" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/2677334/49f0f515-13aa-4663-aef4-179df51b0761">

<img width="371" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/2677334/12f57b33-27fc-4492-9d8e-dda97ac740d8">

### Snack or a link to a repository

https://github.com/janicduplessis/react-native-screens/tree/%40janic/header-bug-1

### Screens version

main@e5a6220

### React Native version

0.74

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by alduzy** [comment]
Hi! Thanks for reporting. I'm going to take a look at it.
Wrapping the right item in a `useCallback` hook should do the trick until the problem's solved.
