### ISSUE TITLE
Screen not available for interaction for a while when navigate back 

### ISSUE THREAD

**Issue by Adil7767** [software-mansion/react-native-screens#2238]
### Description

Current Behavior
When i go back any screen with physical back button or navigation back button. Previous screen can not interacting for a while (about 500ms)

Expected Behavior
When i navigate back. I should be able to interact immediately this screen.

here is my pkgs version
```
    "react": "18.2.0",
    "react-native": "0.74.2",
    "@react-navigation/drawer": "^6.6.15",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "react-native-responsive-sizes": "^2.0.4",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "^3.26.0",
```
same issues was rose in 2020 but still open and now its here again 

[https://github.com/react-navigation/react-navigation/issues/9124](https://github.com/react-navigation/react-navigation/issues/9124)

### Steps to reproduce

a

### Snack or a link to a repository

https://github.com/react-navigation/react-navigation/issues/9124

### Screens version

3.26.0"

### React Native version

0.74.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

Real device

### Device model

ios 13

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @Adil7767, thanks for creating this issue. Have you checked if this issue also occurs on the newest version of react-native-screens? Also, could you send us a correct reproducer to reproduce this issue?

**Comment by tboba** [comment]
Hi @Adil7767, unfortunately I cannot spot any issues, related to delays between old and new architecture. I've tested example application from react-native-screens and both Paper and Fabric have interaction disabled during the transition which is completely fine.
If you still think this is a problem, please let us know in this PR with appropriate reproducer.
Thanks!
