### ISSUE TITLE
Tab non-interactive after remount on new arch

### ISSUE THREAD

**Issue by janicduplessis** [software-mansion/react-native-screens#2252]
### Description

When changing from tab navigation to stack navigation then back to tab navigation again the tab will be frozen. This seems to happen only in the very specific scenario provided in the repro example.

Some things I noticed:

- If there is no `SafeAreaProvider` it works fine
- If there is no `headerShown: false` on the stack navigators it works fine

### Steps to reproduce

Using the Fabric example [with these changes](https://github.com/janicduplessis/react-native-screens/commit/cbe041b28606acf4d3ed9e29440700483babddea):

1. Click on "Test", see the alert opens
2. Click on "Toggle"
3. Click on "Toggle" again
4. Click on "Test", see the button does not work anymore

### Snack or a link to a repository

https://github.com/janicduplessis/react-native-screens/tree/%40janic/tab-freeze

### Screens version

main@8013dc87c18c0367b2fb5a2ce99b5f1e84dff0bb

### React Native version

0.73

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Thank you @janicduplessis for all the reports, you're doing huge job!
