### ISSUE TITLE
On Android devices, when you go to the previous screen with the stackNavigator back operation, a shadow appears in the navigation header, even though shadowing is turned off.

### ISSUE THREAD

**Issue by Ozgur-Kupeli** [software-mansion/react-native-screens#2255]
### Description

On Android devices, when you go to the previous screen with the stackNavigator back operation, a shadow appears in the navigation header, even though shadowing is turned off.

The problem is caused by version 3.32.0 of the react-native-screens library. A workaround was made by fixing the problem to version "react-native-screens": "3.31.1".

Working in harmony between the react-native-screens and @react-navigation/native libraries, which are dependent on each other, will prevent users from wasting unnecessary time. The source of the problem must be found and resolved.

### Steps to reproduce

.

### Snack or a link to a repository

private

### Screens version

3.32.0

### React Native version

0.71.13

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by alduzy** [comment]
Hi @Ozgur-Kupeli , thanks for reporting. Although I can't see any repro or screenshots I think it's the same problem as here:
https://github.com/software-mansion/react-native-screens/issues/2212
I am closing this issue as completed since the fix is waiting to be released.
