### ISSUE TITLE
Crashing when updating android to api target 35

### ISSUE THREAD

**Issue by corbella83** [software-mansion/react-native-screens#2257]
### Description

All versions of "react-native-screens" are crashing when targeting android app to api level 35 due to NoSuchMethodError:

java.lang.NoSuchMethodError: No interface method removeLast()Ljava/lang/Object; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /apex/com.android.art/javalib/core-oj.jar)
                                      	at com.swmansion.rnscreens.ScreenStack.obtainDrawingOp(ScreenStack.kt:319)
                                      	at com.swmansion.rnscreens.ScreenStack.drawChild(ScreenStack.kt:303)
                                      	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)

Is this line:
`if (drawingOpPool.isEmpty()) DrawingOp() else drawingOpPool.**removeLast**()`

And means that removeLast is not available anymore. Replacing it to this works well:

`if (drawingOpPool.isEmpty()) DrawingOp() else drawingOpPool.removeAt(drawingOpPool.size - 1)`

This is a known issue from android: [official android documentation](https://developer.android.com/about/versions/15/behavior-changes-15?hl=en#:~:text=The%20new%20SequencedCollection,has%20been%20disabled.)

### Steps to reproduce

1. Create a react-native project CLI, using 0.74.3 and add dependency of react-native-screens 3.32.0
2. Configure compileSdkVersion and targetSdkVersion of the android project to use api level 34
3. Execute android app and ensure everything is working
4. Change compileSdkVersion and targetSdkVersion to use api level 35
5. Execute android app and it will crash

### Screens version

3.32.0

### React Native version

0.74.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

Real device

### Device model

Samsung Galaxy S22

### Acknowledgements

Yes

**Comment by corbella83** [comment]
> Hey! 👋
> 
> The issue doesn't seem to contain a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).
> 
> Could you provide a [snack](https://snack.expo.dev/) or a link to a GitHub repository under your username that reproduces the problem?

I'm not going to create a new project, configure it, and upload to github for a change this small change that android. Every project you have installed will behave the same if you use android api level35

**Comment by avizuber** [comment]
I'm facing this issue on a Samsung Galaxy Tab A9 running Android 14.

Everything is find on a phone running Android 14, but the tablet has this crashing issue. I'm using react-native-screens 4.16.0, 3.30.0, 3.32.0 and all had the same issue.

I ended up creating a patch that modifies ScreenStack.kt

```
    private fun obtainDrawingOp(): DrawingOp =
        if (drawingOpPool.isEmpty()) DrawingOp() else drawingOpPool.removeAt(drawingOpPool.size - 1)
```

But obviously a patch isn't ideal. Any insight on this?

**Comment by kkafar** [comment]
@avizuber are you able to provide me with reproduction of the crash?

**Comment by kelvingraddick** [comment]
I was facing this issue on a **moto g pure** running **Android 12**. Using `react-native-screens` `v3.32.0`.
Upgrading to at least `v3.37.0` seems to fix it.
Sentry link: https://wave-link.sentry.io/share/issue/185399e9f33c431d8ee9f04185d9c588/

**Comment by Elson0509** [comment]
In \node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\safearea\SafeAreaView.kt, I changed in line 109 from this:
`if (newSystemInsets != currentSystemInsets) {`

To this:
`if (!newSystemInsets.equals(currentSystemInsets)) {`

Then 
```
yarn patch-package react-native-screens 
cd android
./gradlew clean
```

And worked
