### ISSUE TITLE
HeaderSearchBar Android hides on navigation

### ISSUE THREAD

**Issue by iliapnmrv** [software-mansion/react-native-screens#2271]
### Description

Search bar hides on navigation. I use bottom sheet as navigation screen

https://github.com/iliapnmrv/rn-navigation-SearchBar-android-bug

https://github.com/user-attachments/assets/8258fbe3-4ef2-4a44-8655-58bdf341b937

I've also created an issue in rn-navigation repository https://github.com/react-navigation/react-navigation/issues/12075

### Steps to reproduce

1. create basic screen with react-navigation search bar
2. create bottom sheet as screen
3. navigate back and forth

### Snack or a link to a repository

https://snack.expo.dev/@iliapnmrv/rnnavigationandroidsearchiconbug

### Screens version

3.32.0

### React Native version

0.74.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by alduzy** [comment]
Hi @iliapnmrv thanks for reporting the issue. It turned out to be a problem with `transparentModal` being pushed in front of the screen with searchbar. I prepared a PR that fixes it.
