### ISSUE TITLE
Incorrect childCount in removeViewAt

### ISSUE THREAD

**Issue by BenIrving** [software-mansion/react-native-screens#2282]
### Description

There is a bug in react-native-screens on Android when newArchEnabled=true and we have FlatLists in our screens

We attempt to remove an incorrect number of children when calling removeViewAt in SurfaceMountingManager

This seems related to the changes introduced by @WoLewicki in [2134](https://github.com/software-mansion/react-native-screens/pull/2134) as we patched these changes into a previous version of rns and this bug became immediately apparent. This was tested on rn73 & rn74 as well

![Screenshot_1722864873](https://github.com/user-attachments/assets/1af31f62-0b79-4bbb-8e92-bba9fdff9ddb)

### Steps to reproduce

1. Press listitem1
2. Press listitem2
3. Observe crash

### Snack or a link to a repository

https://github.com/BenIrving/rnsrepro

### Screens version

3.34.0

### React Native version

0.75.0-rc.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

None

### Acknowledgements

Yes

**Comment by alduzy** [comment]
@BenIrving Thanks for reporting the issue, I am working on a possible fix.
As a workaround you can try setting the [removeClippedSubviews](https://reactnative.dev/docs/flatlist#removeclippedsubviews) option in the `FlatList` to false.

**Comment by ben-irving** [comment]
Thanks @alduzy - can confirm this resolved the issue in our production app

**Comment by janicduplessis** [comment]
I have also encountered this issue, for now I reverted #2134 since it would cause screens to go completely blank when navigating back to it.

**Comment by BenIrving** [comment]
@alduzy  I can confirm the workaround fixes the issue. Is there any progress on a proper fix here?

**Comment by alduzy** [comment]
@BenIrving There is a fix, but not the prettiest one. I'll prepare a PR

**Comment by Akash95B** [comment]
I am still facing the issue when i am using sectionlist and flatlist. And I am getting the error while navigating back. 
@WoLewicki 
<img width="377" alt="Screenshot 2024-09-19 at 2 19 51 PM" src="https://github.com/user-attachments/assets/140ca169-ef7f-418e-baef-cb3707cb5fad">


Below is the sectionlist component 

`import React, { useState } from 'react';
import { View, SectionList, FlatList, Image, TouchableOpacity } from 'react-native';
import UpArrow from '../../../../../assets/svg/UpArrow.svg';
import DownArrow from '../../../../../assets/svg/DownArrow.svg';
import styles from '../components/SectionStyle';
import { useTheme } from '@react-navigation/native';
import GilroyText from '../../../../../common/components/Text';

const SectionListItem = ({ sections = [] }) => {
  const { colors } = useTheme();
  const themedStyles = styles(colors);
  const [expandedSection, setExpandedSection] = useState(sections.length > 0 ? sections[0].title : null);

  const toggleSection = (title: any) => {
    setExpandedSection(expandedSection === title ? null : title);
  };

  const renderSlotCard = ({ item }) => (
    <View style={themedStyles.card}>
      <GilroyText textType='semi-bold' style={themedStyles.CardHeader}>{'AF2'}</GilroyText>
      <GilroyText textType='regular' style={themedStyles.time}>{item.time}</GilroyText>
      <GilroyText textType='regular' style={themedStyles.slots}>{item.slots} slots</GilroyText>
      <Image source={{ uri: 'https://randomuser.me/api/portraits/men/32.jpg' }} style={themedStyles.coachImage} />
      <GilroyText textType='regular' style={themedStyles.coachName}>{item.coach}</GilroyText>
    </View>
  );

  const renderDayHeader = (day: string | number | boolean | React.ReactElement<any, string | React.JSXElementConstructor<any>> | Iterable<React.ReactNode> | React.ReactPortal | null | undefined) => (
    <GilroyText textType='bold' style={themedStyles.dayHeader}>{day}</GilroyText>
  );

  const renderHorizontalList = ({ data }) => (
    <FlatList
      data={data || []}
      renderItem={renderSlotCard}
      keyExtractor={(item) => item.id}
      horizontal
      showsHorizontalScrollIndicator={false}
      contentContainerStyle={themedStyles.horizontalListContent}
      removeClippedSubviews={false}
    />
  );

  const renderSectionHeader = ({ section: { title } }) => {
    const isExpanded = expandedSection === title;

    return (
      <TouchableOpacity
        style={[
          themedStyles.sectionHeader,
          isExpanded && themedStyles.expandedSectionHeader,
        ]}
        onPress={() => toggleSection(title)}
      >
        <GilroyText style={themedStyles.sectionTitle}>{title}</GilroyText>
        {isExpanded ? <UpArrow /> : <DownArrow />}
      </TouchableOpacity>
    );
  };


  const renderSectionFooter = ({ section }) => {
    const isExpanded = expandedSection === section.title;

    if (!isExpanded) return null;

    return (
      <View style={themedStyles.expandedSection}>
        {section.days.map((dayItem) => (
          <View key={dayItem.day}>
            {renderDayHeader(dayItem.day)}
            {renderHorizontalList({ data: dayItem.data })}
          </View>
        ))}
        <View style={themedStyles.expandedSectionBottomBorder} />
      </View>
    );
  };


  return (
    <View style={{ flex: 1, marginLeft: 20 }}>
      <SectionList
        sections={sections.map(section => ({
          ...section,
          data: section.data || [],
        }))}
        renderItem={() => null}
        renderSectionHeader={renderSectionHeader}
        renderSectionFooter={renderSectionFooter}
        keyExtractor={(item) => item.id}
        contentContainerStyle={themedStyles.sectionListContent}
        removeClippedSubviews={false}
      />
    </View>
  );
};

export default SectionListItem;
`

**Comment by WoLewicki** [comment]
@Akash95B is https://github.com/software-mansion/react-native-screens/pull/2330 included in your build?

**Comment by maxymczech** [comment]
Has this been fixed? I am on `react-native@0.76.3`, tried updating `@react-navigation` packages and ran into this issue. I was updating from

```
    "@react-navigation/drawer": "^7.0.19",
    "@react-navigation/native": "^7.0.13",
    "@react-navigation/native-stack": "^7.1.14",
```

to 

```
    "@react-navigation/drawer": "^7.1.1",
    "@react-navigation/native": "^7.0.14",
    "@react-navigation/native-stack": "^7.2.0",
```

**Comment by AmirNexter** [comment]
Can confirm that it still happens in:
"react-native-screens": "^4.8.0"
"react-native": "^0.76.5",
any update?

**Comment by kkafar** [comment]
Yep, [4.8.0 requires react-native 0.78](https://github.com/software-mansion/react-native-screens?tab=readme-ov-file#support-for-fabric)
