### ISSUE TITLE
non-virtual member function marked 'override' hides virtual member function react native 0.74

### ISSUE THREAD

**Issue by Kabeer-Haseja** [software-mansion/react-native-screens#2284]
### Description

  /Users/kabeerhaseja/Desktop/EMPG/jarvis-app/node_modules/react-native-screens/android/src/main/jni/../../../../common/cpp/react/renderer/components/rnscreens/RNSModalScreenShadowNode.h:23:61: error: non-virtual member function marked 'override' hides virtual member function
    Point getContentOriginOffset(bool includeTransform) const override;
                                                              ^
  /Users/kabeerhaseja/.gradle/caches/transforms-4/4776b9590c2c29c10151d4763bf3e35c/transformed/jetified-react-android-0.74.5-debug/prefab/modules/react_nativemodule_core/include/react/renderer/core/LayoutableShadowNode.h:126:17: note: hidden overloaded virtual function 'facebook::react::LayoutableShadowNode::getContentOriginOffset' declared here: different number of parameters (0 vs 1)
    virtual Point getContentOriginOffset() const;
                  ^
  2 errors generated.

### Steps to reproduce

after install pods and run app through xCode
or i run android 

### Snack or a link to a repository

..

### Screens version

3.32.0

### React Native version

0.74.5

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by WoLewicki** [comment]
Please try using the newest version of the library and check if it solves your problem.

**Comment by WoLewicki** [comment]
In the comment description, you provided that you are not using the newest one: 
<img width="226" alt="image" src="https://github.com/user-attachments/assets/a6313fd5-b51d-4ca6-8fce-6f958b65e654">

If you want to use the `react-native-screens` version `3.33.0` or `3.34.0` on new architecture, you need to use `react-native` version `0.75.x` (see https://github.com/software-mansion/react-native-screens#support-for-fabric).

If you really need to use the newest version of  `react-native-screens` with `react-native` version `0.74.x`, you can revert the changes to `.cpp` and `.h` files from this PR: https://github.com/software-mansion/react-native-screens/pull/2218/files#diff-ca8e8243717509db3426d12140ad9c98ba7b07bf18155362b738f5f5d514cded and it should work.

Does it answer your question?

**Comment by kkafar** [comment]
Hey, I'll close the issue as this looks just like mismatched version of `react-native-screens` & `react-native`, as @WoLewicki kindly explained. 

@Kabeer-Haseja let us know if the problem persists after upgrading your app to support required RN version or downgrading screens to match with `react-native` version you use currently.

**Comment by Kabeer-Haseja** [comment]
@kkafar it works ❤️

**Comment by alexandreerick** [comment]
i'm having this problem with react-native 0.81.5 and rn-screens 4.20.0. Android works fine, ios is the problem.

**Comment by kkafar** [comment]
@alexandreerick, as explained above it is likely that your dependencies are out of sync. I'd recommend verifying in your lock file what versions exactly are installed & if there are version conflicts (dependencies request various versions of the same package) it might make sense to set "resolution" rules in your package.json.
