### ISSUE TITLE
Typescript error after update to latest 

### ISSUE THREAD

**Issue by Cancercookie** [software-mansion/react-native-screens#2294]
### Description

I am receiving the following errors with tsc after upgrading to the latest version of screen and all the @react-navigation packages.

```bash

node_modules/react-native-screens/src/native-stack/types.tsx:63:3 - error TS2344: Type 'StackNavigationState<ParamList>' does not satisfy the constraint 'string | undefined'.

63   StackNavigationState<ParamList>,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-screens/src/native-stack/types.tsx:488:3 - error TS2314: Generic type 'DefaultNavigatorOptions' requires 4 type argument(s).

488   DefaultNavigatorOptions<NativeStackNavigationOptions> &
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-screens/src/native-stack/types.tsx:492:37 - error TS2314: Generic type 'Descriptor' requires 3 type argument(s).

492 export type NativeStackDescriptor = Descriptor<
                                        ~~~~~~~~~~~
493   ParamListBase,
    ~~~~~~~~~~~~~~~~
... 
496   NativeStackNavigationOptions
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
497 >;
    ~
```

my packages that could be related to this issue: 

```json
"@react-navigation/drawer": "^6.7.0",
"@react-navigation/native": "^6.1.0",
"@react-navigation/native-stack": "^6.11.0",
"@react-navigation/stack": "^6.4.0",
"react-native-screens": "3.34.0",
"typescript": "~5.0.0"
"react-native": "0.73.6"
```

If I stop responding I may be on vacation, I'll resume my activities in 2 weeks.

### Steps to reproduce

Upgrade to latest with said dependencies

### Snack or a link to a repository

my repo is private sorry

### Screens version

3.34.0

### React Native version

0.73.6

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by alduzy** [comment]
@Cancercookie That's unusual, have you tried removing the `node_modules` and installing the dependencies again or restarting the TS server?

Btw. the `3.34.0` version should be used with react-native 0.75.x (see https://github.com/software-mansion/react-native-screens#support-for-fabric). Let me know if the problem still persists

**Comment by Cancercookie** [comment]
I've tried `node_modules` and restart. But I guess the main issue is using this version with 0.73.x, when I saw compatibility with 0.75+ in the changelog I also assumed retrocompatibility, I didn't check the table in README. I'll revert to a previous version and report back. Thanks.

**Comment by alduzy** [comment]
@Cancercookie You're right the compatibility rules apply to fabric and not necessarily to paper. Anyway, let me know if downgrading helped.

**Comment by Cancercookie** [comment]
Sorry for being this late, I tried downgrading from 3.34.0 to 3.30.0 decrementally but nothing.
If I revert back to 3.29.0 the error goes away.

**Comment by alduzy** [comment]
@Cancercookie Can you add a minimal reproduction?

**Comment by Cancercookie** [comment]
https://github.com/Cancercookie/screen-repro

**Comment by alduzy** [comment]
Hi @Cancercookie thanks for submitting the repro, what steps do I have to perform in order to get the error? I tried `yarn tsc` but could not reproduce it.
You can also check if using `yarn tsc --skipLibCheck` helps in your case. Make sure you restart the ts server.

**Comment by Cancercookie** [comment]
https://github.com/Cancercookie/screen-repro I updated the repro. 

I failed to notice that because I was not referencing a `react-native-screens` type directly in my project the error was not showing in `tsc`

**Comment by alduzy** [comment]
@Cancercookie Good to hear that you were able to resolve the issue!
