### ISSUE TITLE
freezeEnabled is not a function 

### ISSUE THREAD

**Issue by Randall71** [software-mansion/react-native-screens#2302]
### Description

My application works normally but when I add the React compiler I get this error and I can no longer launch my application in development mode.

After adjusting the configuration like this and my application works as before with the compiler, so I put this here in case there is something to review, otherwise feel free to close it
```
diff --git a/node_modules/react-native-screens/src/components/ScreenStack.tsx b/node_modules/react-native-screens/src/components/ScreenStack.tsx
index 46043b6..8a661fa 100644
--- a/node_modules/react-native-screens/src/components/ScreenStack.tsx
+++ b/node_modules/react-native-screens/src/components/ScreenStack.tsx
@@ -21,7 +21,7 @@ function ScreenStack(props: ScreenStackProps) {
     const { props, key } = child;
     const descriptor = props?.descriptor ?? props?.descriptors?.[key];
     const isFreezeEnabled =
-      descriptor?.options?.freezeOnBlur ?? freezeEnabled();
+      descriptor?.options?.freezeOnBlur ;
 
     // On Fabric, when screen is frozen, animated and reanimated values are not updated
     // due to component being unmounted. To avoid this, we don't freeze the previous screen there
```

### Steps to reproduce

--

### Snack or a link to a repository

--

### Screens version

3.34.0

### React Native version

0.74.5

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung Galaxy Tab A7 (Android 12)

### Acknowledgements

Yes

**Comment by parsadotsh** [comment]
I run into the same issue (I have react-compiler on) when I update certain dependencies:
![image](https://github.com/user-attachments/assets/9f75571e-aabd-4ba1-b861-86d962b95f75)

**Comment by avoc-ado** [comment]
2 workarounds:
1: add freezeOnBlur to every screen.
```
<Stack.Screen
  name="(tabs)"
  options={{
    freezeOnBlur: false,
  }}
/>
```
2: make a yarn patch to replace the freezeEnabled() call with true/false

**Comment by somangoi** [comment]
In my case, this error happened when I updated "react-native-screens" from ~3.29.0 to 3.31.1. When I downgraded to ~3.29.0, it got back normal.

**Comment by jeroenptrs** [comment]
Patching freezeEnabled still causes issues when I switch tabs with expo-router, getting `Error: Rendered fewer hooks than expected.` when I do.

Anyone else experiencing this?

**Comment by alduzy** [comment]
I believe https://github.com/software-mansion/react-native-screens/pull/2410 fixes the issue unintentionally 😄 
Try applying the following patch:

```
diff --git a/node_modules/react-native-screens/src/components/ScreenStack.tsx b/node_modules/react-native-screens/src/components/ScreenStack.tsx
index 1783dcf..e08dbff 100644
--- a/node_modules/react-native-screens/src/components/ScreenStack.tsx
+++ b/node_modules/react-native-screens/src/components/ScreenStack.tsx
@@ -1,5 +1,6 @@
 import React from 'react';
-import { ScreenStackProps, freezeEnabled } from 'react-native-screens';
+import { ScreenStackProps } from '../types';
+import { freezeEnabled } from '../core';
 import DelayedFreeze from './helpers/DelayedFreeze';
 
 // Native components

```

**Comment by sgup** [comment]
I'm seeing this error after enabling react compiler with Expo

**Comment by alduzy** [comment]
@sgup Thank you for letting me know. I'll make sure to implement the fix in v3.
