### ISSUE TITLE
Navigating to a full screen modal with custom header props causes crash

### ISSUE THREAD

**Issue by ha3** [software-mansion/react-native-screens#2317]
### Description

On iOS, if a full-screen modal screen has a custom `headerLeft`, `headerRight`, or `headerTitle` prop, then navigating to it causes a crash after several times.

This is the error message:
> Exception thrown while executing UI block: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

I am positive that this regression was introduced somewhere after 3.32.0.

### Steps to reproduce

1. Have two screens, one being a full-screen modal
2. Add either custom `headerLeft`, `headerRight`, or `headerTitle` function.
3. Navigate to the modal and go back several times
4. Observe the crash

### Snack or a link to a repository

https://github.com/ha3/rns-fullscreen-repro

### Screens version

3.34.0

### React Native version

0.75.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 13 (iOS 15.5)

### Acknowledgements

Yes

**Comment by louis-openspace** [comment]
I can confirm this worked in 3.32.0 and broken when I used 3.34.0

**Comment by jakecurreri** [comment]
+1

Patch from @maksg's [PR](https://github.com/software-mansion/react-native-screens/pull/2336) until bundled into a release?


[ios/RNSScreenStackHeaderConfig.mm](https://github.com/software-mansion/react-native-screens/pull/2336/files#diff-e5ef5b6e29f17bca80b51bc0c5faef1a44bac24e00952b30ac822520213dc6a5)
```
// When modal is shown the underlying RNSScreen isn't attached to any navigation controller.
// During the modal dismissal transition this update method is called on this RNSScreen resulting in nil navctr.
// After the transition is completed it will be called again and will configure the navigation controller correctly.
// Also see: https://github.com/software-mansion/react-native-screens/pull/2336
if (navctr == nil) {
  return;
}
```
