### ISSUE TITLE
[native-stack] Modals are not dismissed when unmounting a navigator

### ISSUE THREAD

**Issue by janicduplessis** [software-mansion/react-native-screens#233]
When using the react-navigation bindings and changing the mounted navigator the modals are not dismissed. For example in my app the logout button is inside a screen presented modally. The content underneath the modal will change to the login screen but the modal is not dismissed and becomes unresponsive.

Navigator setup looks like:

```ts
<NavigationContainer
  // to remount on log state change
  key={showApp ? 'a' : 'b'}
>
  <RootModalStack.Navigator initialRouteName="app">
    <RootModalStack.Screen
      name="app"
      component={showApp ? RootStackNavigator : LoginStackNavigator}
    />
    {rootModalStackElements}
  </RootModalStack.Navigator>
</NavigationContainer>
```

I guess this is due to modals not being part of the screen view on iOS and are pushed on the root vc.

A workaround is to call `popToTop` and then changing state un a timeout.

**Comment by WoLewicki** [comment]
Does the issue still exist in the newest version of the library? And if so, can you provide a repo/snack that shows this bug?

**Comment by janicduplessis** [comment]
Looks like it doesn't, I removed the hack I was using and it works now!
