### ISSUE TITLE
Android - "cannot remove child at index X" error on new architecture

### ISSUE THREAD

**Issue by cjpete** [software-mansion/react-native-screens#2339]
### Description

When navigating back from a stack screen which contains a FlatList, the app throws a soft error:

```
Cannot remove child at index 9 from parent ViewGroup [106], only 10 children in parent. Warning: childCount may be incorrect!

null
```

<img width="536" alt="image" src="https://github.com/user-attachments/assets/4a612c94-a0c1-45d8-8881-ab917b9757e8">

https://github.com/user-attachments/assets/db7e7eae-7840-4a58-a84b-25534e67f2ef

### Steps to reproduce

1. Open the repro app 
2. Navigate to the flatlist screen 
3. Press header back button
4. Observe error

### Snack or a link to a repository

https://github.com/72days/TestNavFlatListIssues

### Screens version

3.34.0

### React Native version

0.75.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Samsung S9 and Pixel 1

### Acknowledgements

Yes

**Comment by cjpete** [comment]
> Hey! 👋
> 
> The issue doesn't seem to contain a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).
> 
> Could you provide a [snack](https://snack.expo.dev/) or a link to a GitHub repository under your username that reproduces the problem?

There is a reproduction example in the issue: https://github.com/72days/TestNavFlatListIssues

**Comment by arnabJ** [comment]
Temporarily add this to FlatList to fix the issue:
```JavaScript
<FlatList
    data={images}
    numColumns={3}
    contentContainerStyle={[{paddingHorizontal: 10}, containerStyle]}
    renderItem={renderItem}
    removeClippedSubviews={false} // <- Add This
/>
```

Got this workaround from: https://github.com/software-mansion/react-native-screens/issues/2282

**Comment by alduzy** [comment]
I believe it's the same issue: https://github.com/software-mansion/react-native-screens/issues/2282
The problem has been recently revisited by: https://github.com/software-mansion/react-native-screens/pull/2383

**Comment by WKampel** [comment]
Still happens in latest beta version (4.0.0-beta.9)

**Comment by alduzy** [comment]
@WKampel Can you attach a reproduction?

**Comment by abhayagrawal-fareye** [comment]
Facing this issue with RN 0.75.4 and react-native-screens - 3.34.0

**Comment by Aamir0890** [comment]
facing this issue with  "react-native-screens": "^3.35.0", and   "react-native": "0.76.0",

**Comment by delphinebugner** [comment]
Had the issue with `3.34.0`, just upgraded to `3.35.0` and it did fix it, thanks @alduzy  🙂

**Comment by jaemushim** [comment]
Facing this issue with react native 0.76.1, react native screens 3.35.0

**Comment by pj-prize** [comment]
Same, seeing this issue in RN 0.76.1 and RN Screens 3.35.0

**Comment by marcio-b** [comment]
Same issue in RN 0.76.1 and RNScreens 3.35.0. I also tried updating RNScreens to 4.1.0 and had the same result.

**Comment by alduzy** [comment]
Related issue: https://github.com/software-mansion/react-native-screens/issues/2491

**Comment by marcio-b** [comment]
I just wanted to confirm that issue is resolved in v4.2.0.

**Comment by pj-prize** [comment]
Confirmed that this is fixed for me with RN 0.76.2 and RN Screens 4.2.0

**Comment by Yousuf223** [comment]
cannot remove child at index 7 from parent ViewGroup [416], only 8 childern in parent. warning: childCount may be Incorrect!

**Comment by tree1891** [comment]
same issue
RN 0.76.5
RN Screens 4.3.0

**Comment by saimarshadsaim31** [comment]
I was also facing this issue, not for flatlist but in some other part of the app. was using v4.0.0, upgraded to 4.2.0 and it got fixed!

**Comment by hasangonen91** [comment]
"react-native-screens": "3.34.0", to "3.35.0",  working for me

**Comment by KhuongVo2105** [comment]
![image](https://github.com/user-attachments/assets/42ee5d1e-566b-4c01-a64f-a0d0881fb200)
this also happens in RN 0.76.5 and RN screens 4.4.0. I went into _android/gradle.properties_ and changed to **newArchEnabled=false**
![image](https://github.com/user-attachments/assets/39175d35-205f-47a3-9202-ae0b676b59d6)

**Comment by ShubhamNative** [comment]
I'm also facing the same issue in RN Screen : '^4.3.0' Is there any solution for this?

**Comment by dev-shahbazshaikh** [comment]
I'm using  "react-native-screens": "4.5.0", 
I'd issue on "react-native-screens":"^4.0.0" which installed latest 4.6.0 initially, which was causing the issue. I manually downgraded to previous working 4.5.0 version from my package-lock.json. It started working.

**Comment by KhuongVo2105** [comment]
> I'm also facing the same issue in RN Screen : '^4.3.0' Is there any solution for this?Tôi cũng đang gặp phải vấn đề tương tự trong Màn hình RN: '^ 4.3.0' Có giải pháp nào cho điều này không?

I recommend choosing the appropriate RN Screens version published at the library's github repository. Refer [here](https://github.com/software-mansion/react-native-screens?tab=readme-ov-file#support-for-paper)

![Image](https://github.com/user-attachments/assets/3690a01e-0150-4b14-8915-b4bd2f7e464f)

**Comment by TalhaAbbas55** [comment]
> I'm also facing the same issue in RN Screen : '^4.6.0' ,RN 0.76.6

same here, react native just being react native

**Comment by ShubhamNative** [comment]
I have found some temporary solution just get the latest or any stable version of RN Screens Currently I'm using 4.5.0 and it is working fine for me. Happy Coding : )

**Comment by projodesign** [comment]
I've also experienced this issue using 4.6.0. Downgrading to 4.5.0 does solve it for me.

I actually had the issue with a production build, even though it was fine in Expo Go. (Expo does complain that I should be using 4.4.0, but had to upgrade due the ongoing pressable onPress issue). So I was just getting a white screen, and had to use adb debug to determine the error.

As others have mentioned, the issue occurs when navigation back from a screen that has a Flatlist on. The issue occurred on 6 out of the 7 screens that contain a flatlist in my app.

**Comment by Aravindhan-Senthilkumar** [comment]
> > I have found some temporary solution just get the latest or any stable version of RN Screens Currently I'm using 4.5.0 and it is working fine for me. Happy Coding : )
> 
> i changed its version to 4.5.0 and also 4.4.0 it didn't work. How can i fix that someone know ?

You can use RN - 0.77.0 , React & React-dom - 18.2.0 and RN Screen - 4.2.0 to resolve this issue. They fixed this in latest update i think so.

**Comment by Aravindhan-Senthilkumar** [comment]
They resolved this issue in the latest RN release . I am using these versions RN - 0.77.0 , React & React-dom - 18.2.0 and RN Screen - 4.2.0. If you are facing the issue again, i recommend using Flashlist by shopify for this purpose and tell me how is it ?

**Comment by SurendraSp** [comment]
Anyone who also face this issue and using older react native versions downgrade to `react-native-screens 4.4.0` 
make sure you remove ^ from version.

`"react-native-screens": "4.4.0"`

**Comment by ethanneff** [comment]
react-native 0.76.5 and react-native-screens **4.2.0** is what worked for me. 4.3.0, 4.4.0, 4.5.0, 4.6.0 are all broken.

**Comment by mathieupost** [comment]
Issue still persists on 4.7.0-beta.4

**Comment by lukaqll** [comment]
same issue. I tried installing 4.2.0, 4.4.0, 4.5.0 and 4.6.0. RN 0.76. Occurs when I have a list and call goBack from the navigation

**Comment by Dosbodoke** [comment]
> Issue still persists on 4.7.0-beta.4
> 
> 4.5.0 works for me though.

Can you update your comment with which version of react are you using? 

For new readers, here's what I found...

rn v0.76 with new arch had an issue with neste lists that was crashing the applications, so the rn-screen made a series of PR's to mitigate it

1. https://github.com/software-mansion/react-native-screens/pull/2307
2. https://github.com/software-mansion/react-native-screens/pull/2383
3. https://github.com/software-mansion/react-native-screens/pull/2495
4. https://github.com/software-mansion/react-native-screens/pull/2531

These commits should be avaiable on react-native-screens v4.4.0

But then rn v0.77 came out and introduced a fix for it so the team removed those changes that were a workound (see https://github.com/software-mansion/react-native-screens/commit/2aa278c8c5c39d697f636fa8c3781fc96f1a2e1b)

So, on rn-screen v4.6.0 it should be fixed but it's necessary to use rn 0.77

**Comment by Farids87** [comment]
Same issue
RN: 0.76.5
React-native-screen: ^4.4.0
![Screenshot_20250225_204703_Venus.jpg](https://github.com/user-attachments/assets/8da4be2e-2d4f-4357-8ae2-39eb38e85342)

**Comment by aliyanlatif** [comment]
Same issue
RN: 0.76.3
React-native-screen: ^4.3.0

upgrading RN to 0.77.0 fixed the issue for me

**Comment by mukul-sharma085** [comment]
> Same issue RN: 0.76.5 React-native-screen: ^4.4.0 ![Screenshot_20250225_204703_Venus.jpg](https://github.com/user-attachments/assets/8da4be2e-2d4f-4357-8ae2-39eb38e85342)

did you found any fix?

**Comment by Farids87** [comment]
> > Same issue RN: 0.76.5 React-native-screen: ^4.4.0 ![Screenshot_20250225_204703_Venus.jpg](https://github.com/user-attachments/assets/8da4be2e-2d4f-4357-8ae2-39eb38e85342)
> 
> did you found any fix?

Not sure but I have set newArchEnabled=false on AndroidManifest and then it worked...

**Comment by Umar-Farooq-Shafi** [comment]
> react-native 0.76.5 and react-native-screens **4.2.0** is what worked for me. 4.3.0, 4.4.0, 4.5.0, 4.6.0 are all broken.

worked for me

**Comment by yossularko** [comment]
> > react-native 0.76.5 and react-native-screens **4.2.0** is what worked for me. 4.3.0, 4.4.0, 4.5.0, 4.6.0 are all broken.
> 
> worked for me

it's worked!

**Comment by Muzamil63** [comment]
> > > react-native 0.76.5 and react-native-screens **4.2.0** is what worked for me. 4.3.0, 4.4.0, 4.5.0, 4.6.0 are all broken.
> > 
> > 
> > worked for me
> 
> it's worked!

what is your react native version

**Comment by alidjanoff** [comment]
> > Issue still persists on 4.7.0-beta.4
> > 4.5.0 works for me though.
> 
> Can you update your comment with which version of react are you using?
> 
> For new readers, here's what I found...
> 
> rn v0.76 with new arch had an issue with nested lists that was crashing the applications, so the rn-screen team made a series of PR's to mitigate it
> 
> 1. [fix(Android): incorrect childCount in removeViewAt when using flatlist on fabric #2307](https://github.com/software-mansion/react-native-screens/pull/2307)
> 2. [fix(Android): going back on fabric with nested list #2383](https://github.com/software-mansion/react-native-screens/pull/2383)
> 3. [fix(Android): going back on fabric with removeClippedSubviews #2495](https://github.com/software-mansion/react-native-screens/pull/2495)
> 4. [fix(Android): prevent crash when we can not insert any subviews into child #2531](https://github.com/software-mansion/react-native-screens/pull/2531)
> 
> These commits are avaiable on react-native-screens v4.3.0 that added [#2531](https://github.com/software-mansion/react-native-screens/pull/2531) . You should be able to use v4.4.0 as also
> 
> But then rn v0.77 came out, the team rn-screens add support to it on `v4.5.0` [#2581](https://github.com/software-mansion/react-native-screens/pull/2581) . At some time rn 0.77 introduced a fix for this problem and the rn-screens team removed those changes that were a workound [2aa278c](https://github.com/software-mansion/react-native-screens/commit/2aa278c8c5c39d697f636fa8c3781fc96f1a2e1b) on `v4.6.0`
> 
> So, a quick summary should be:
> 
> If you are on new arch and using `v0.76` use rn-screen `v4.4.0` If you are on new arch and using `v0.77` use `v4.6.0` Do not use `v4.5.0`
> 
> Feel free to suggest any editions.

This id worked thanks

**Comment by ZAKARIA-MOSBAHI** [comment]
thank you

**Comment by duongbao0803** [comment]
I use RN 0.76.6 and react-native-screen: 4.6.0 and get error

**Comment by Dosbodoke** [comment]
> I use RN 0.76.6 and react-native-screen: 4.6.0 and get error

Bro, read the thread. I did a super detailed explanation some comments earlier that will fix your problem.

Good luck

**Comment by dasharadhashivaprasad** [comment]
im  not useing  flatlist using scrollview getting same how can i  fix it

**Comment by mishalbutt7** [comment]
> **4.2.0**

It Worked

**Comment by dasharadhashivaprasad** [comment]
for faltlist its working but without flatlist i mean if i use scrollview in that page if i go back manually getting that error only for scrollview which attribute i need to use can u explain briefly

**Comment by Sowmiya13G** [comment]
Facing Same issue ,I am using 0.76.2 RN version. can you suggest the RN Screen version

**Comment by nemorize** [comment]
@Sowmiya13G Use 4.4

**Comment by alidjanoff** [comment]
If you are on new arch and using v0.76 use rn-screen v4.4.0 If you are on new arch and using v0.77 use v4.6.0 Do not use v4.5.0

**Comment by Dosbodoke** [comment]
> > If you are on new arch and using v0.76 use rn-screen v4.4.0 If you are on new arch and using v0.77 use v4.6.0 Do not use v4.5.0
> 
> I used exactly that, RN 0.76 and rn-screen v4.4.0 and still facing that issue, any suggestions? 

Is the screen that you are moving back using FlatList/FlashList? I read something on this thread about setting 'disableVirtualization=false'

**Comment by ziaakhan7872** [comment]
I was facing the same issue in react-native-gifted-chat, and I was able to resolve it by passing the removeClippedSubviews: false prop inside listViewProps. Here’s how I applied it:

<GiftedChat
  {...otherProps}
  listViewProps={{
    removeClippedSubviews: false,
  }}
/>

**Comment by cristiano-linvix** [comment]
> > Issue still persists on 4.7.0-beta.4
> > 4.5.0 works for me though.
> 
> Can you update your comment with which version of react are you using?
> 
> For new readers, here's what I found...
> 
> rn v0.76 with new arch had an issue with nested lists that was crashing the applications, so the rn-screen team made a series of PR's to mitigate it
> 
> 1. [fix(Android): incorrect childCount in removeViewAt when using flatlist on fabric #2307](https://github.com/software-mansion/react-native-screens/pull/2307)
> 2. [fix(Android): going back on fabric with nested list #2383](https://github.com/software-mansion/react-native-screens/pull/2383)
> 3. [fix(Android): going back on fabric with removeClippedSubviews #2495](https://github.com/software-mansion/react-native-screens/pull/2495)
> 4. [fix(Android): prevent crash when we can not insert any subviews into child #2531](https://github.com/software-mansion/react-native-screens/pull/2531)
> 
> These commits are avaiable on react-native-screens v4.3.0 that added [#2531](https://github.com/software-mansion/react-native-screens/pull/2531) . You should be able to use v4.4.0 as also
> 
> But then rn v0.77 came out, the team rn-screens add support to it on `v4.5.0` [#2581](https://github.com/software-mansion/react-native-screens/pull/2581) . At some time rn 0.77 introduced a fix for this problem and the rn-screens team removed those changes that were a workound [2aa278c](https://github.com/software-mansion/react-native-screens/commit/2aa278c8c5c39d697f636fa8c3781fc96f1a2e1b) on `v4.6.0`
> 
> So, a quick summary should be:
> 
> If you are on new arch and using `v0.76` use rn-screen `v4.4.0` If you are on new arch and using `v0.77` use `v4.6.0` Do not use `v4.5.0`
> 
> Feel free to suggest any editions.

I'm using the following architecture:
react-native 0.76.9 and react-native-screens 4.4.0

It works perfectly for android 8+
however, I have devices using android 7.1.1 and on them the problem still persists.

I had to use removeClippedSubviews, but I wonder if this brings any harm to performance perhaps?

**Comment by Dosbodoke** [comment]
@cristiano-linvix IDK if it can cause any perfomance issue. Maybe I can try to benchmark it. But yes, you do need to set removeClipedSubviews

Do you know any strategies to do this benchmark?

**Comment by cristiano-linvix** [comment]
From what I've read about what this property does, it basically removes views that are not visible from memory.

Thinking about large lists, with hundreds of records, depending on the UI load of the component, this will certainly affect performance.

The use of removeClippedSubviews={false} only became mandatory for me because of Android 7 (POS payment machines).

Is there any way to not use this prop in Android 7?

I'm using RN 0.76.9 because from 0.77, some things changed, and whenever an error is triggered, the application crashes, I haven't found out why, do you know?

**Comment by nemorize** [comment]
@cristiano-linvix If you want to use removeClippedSubviews prop because you are worried about the performance caused by ui load on millions of records, you will actually suffer from performance degradation in other ways even if you use it.

The removeClippedSubviews-ed items have been released from memory, and if you want to scroll up or down again to view the item, the views should be rendered anew.

Depending on the scroll status, it will cause frequent heavy ui loads, and that will soon lead to performance degradation.

Rather than creating a list where heavy ui loads are expected, why not provide another ux? You can cut them into 20 units to provide pagination.

**Comment by cristiano-linvix** [comment]
> [@cristiano-linvix](https://github.com/cristiano-linvix) If you want to use removeClippedSubviews prop because you are worried about the performance caused by ui load on millions of records, you will actually suffer from performance degradation in other ways even if you use it.
> 
> The removeClippedSubviews-ed items have been released from memory, and if you want to scroll up or down again to view the item, the views should be rendered anew.
> 
> Depending on the scroll status, it will cause frequent heavy ui loads, and that will soon lead to performance degradation.
> 
> Rather than creating a list where heavy ui loads are expected, why not provide another ux? You can cut them into 20 units to provide pagination.

Hello!

In most listings I do pagination of 40 at a time.

However, on the sale screen, on Android 7 where there are limited resources, when I reach 100 records, usability starts to slow down a bit.

But, this only happens on devices with limited resources and Android 7.

I would still like to find out why React Native 0.77 crashes on some when some exceptions are thrown. Very strange.

**Comment by rohit-xcode** [comment]
> Temporarily add this to FlatList to fix the issue:
> 
> <FlatList
>     data={images}
>     numColumns={3}
>     contentContainerStyle={[{paddingHorizontal: 10}, containerStyle]}
>     renderItem={renderItem}
>     removeClippedSubviews={false} // <- Add This
> />
> Got this workaround from: [#2282](https://github.com/software-mansion/react-native-screens/issues/2282)

it worked!!! thanks man.

**Comment by vladik-Didyk** [comment]
last month
Temporarily add this to FlatList to fix the issue:

<FlatList
data={images}
numColumns={3}
contentContainerStyle={[{paddingHorizontal: 10}, containerStyle]}
renderItem={renderItem}
removeClippedSubviews={false} // <- Add This
/>
Got this workaround from: https://github.com/software-mansion/react-native-screens/issues/2282
it worked!!! thanks man.

**Comment by asxxb** [comment]
just add a removeClippedSubviews={false}  to the flatlist component solved the issue ,removeClippedSubviews={false} basically tells React Native “don’t aggressively detach off-screen child views”, so the native ViewGroup child count stays consistent with what JS thinks it has.

The trade-off is slightly higher memory usage because those off-screen items stay mounted instead of being recycled, but it’s a perfectly fine fix if the list isn’t huge.

**Comment by codewithyasirarafath** [comment]
> > > If you are on new arch and using v0.76 use rn-screen v4.4.0 If you are on new arch and using v0.77 use v4.6.0 Do not use v4.5.0
> > 
> > 
> > I used exactly that, RN 0.76 and rn-screen v4.4.0 and still facing that issue, any suggestions?
> 
> Is the screen that you are moving back using FlatList/FlashList? I read something on this thread about setting 'removeClippedSubviews={false}'

Yes i am facing the same issue , can you please give me a solution here Quickly

**Comment by ConnorZ97** [comment]
For anyone who still encounters a similar error:
```
Exception thrown when executing UIFrameGuarded
Cannot remove child at index x from parent ViewGroup [xx], only x children in parent. Warning: childCount may be incorrect!
The spcified child already has a parent. You must call removeView() on the child's parent first.
```
I fixed it by changing "headerTitleAlign" from "center" to "left" in my stack screen options. But I reckon it's still an issue.

**Comment by shubhamdeol** [comment]
I am also still facing the issue. I am on `~4.16.0` version of react native screens and react native `0.81.4`. 
When we call replace or pop(2) we get this error. 
After this replace call device starts firing low memory events as per sentry reports and then app crashed. We do not get crash on all devices. It's not easy to reproduce but I feel it might be coming from low memory devices. 

I am not sure why does main activity stops resumes and pauses here.  

<img width="726" height="671" alt="Image" src="https://github.com/user-attachments/assets/dabe203b-7488-42cb-b47d-57dff24b3771" />

After this we get
`IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.`

**Comment by shubhamdeol** [comment]
@cristiano-linvix 

> some time rn 0.77 introduced a fix for this problem and the rn-screens team removed those changes that were a workound. 

I feel this has re introduced this error on version above `4.6.0`

**Comment by shubhamdeol** [comment]
it seems my gut feeling was correct. I revered changes done here which they made in 4.6.0. I no longer face this issue. 
https://github.com/software-mansion/react-native-screens/commit/2aa278c8c5c39d697f636fa8c3781fc96f1a2e1b

I had to apply patch. 

Here is patch file content

```
diff --git a/android/src/main/java/com/swmansion/rnscreens/Screen.kt b/android/src/main/java/com/swmansion/rnscreens/Screen.kt
index eb3e7182a946e07774738bb38357fe17c23a86d5..972cbe2d589dd852e57db2525578e290c11f6d86 100644
--- a/android/src/main/java/com/swmansion/rnscreens/Screen.kt
+++ b/android/src/main/java/com/swmansion/rnscreens/Screen.kt
@@ -18,10 +18,13 @@ import androidx.swiperefreshlayout.widget.SwipeRefreshLayout
 import com.facebook.react.bridge.GuardedRunnable
 import com.facebook.react.bridge.ReactContext
 import com.facebook.react.uimanager.PixelUtil
+import com.facebook.react.uimanager.ReactClippingViewGroup
 import com.facebook.react.uimanager.ThemedReactContext
 import com.facebook.react.uimanager.UIManagerHelper
 import com.facebook.react.uimanager.UIManagerModule
 import com.facebook.react.uimanager.events.EventDispatcher
+import com.facebook.react.views.scroll.ReactHorizontalScrollView
+import com.facebook.react.views.scroll.ReactScrollView
 import com.google.android.material.bottomsheet.BottomSheetBehavior
 import com.google.android.material.shape.CornerFamily
 import com.google.android.material.shape.MaterialShapeDrawable
@@ -420,6 +423,31 @@ class Screen(
             for (i in 0 until it.childCount) {
                 val child = it.getChildAt(i)
 
+                // The children are miscounted when there's removeClippedSubviews prop
+                // set to true (which is the default for FlatLists).
+                // Unless the child is a ScrollView it's safe to assume that it's true
+                // and add a simple view for each possibly clipped item to make it work as expected.
+                // Core has fixed this but the issue still exists. It might have missed some edge cases
+                // so we are adding the workaround back.
+                // See https://github.com/software-mansion/react-native-screens/pull/2495
+
+                if (child is ReactClippingViewGroup &&
+                    child.removeClippedSubviews &&
+                    child !is ReactScrollView &&
+                    child !is ReactHorizontalScrollView &&
+                    child is ViewGroup
+                ) {
+                    // We need to workaround the issue to handle edge cases.
+                    // Some views do not accept any children or have set amount and they throw
+                    // when we want to brute-forcefully manipulate that.
+                    try {
+                        for (j in 0 until child.childCount) {
+                            child.addView(View(context))
+                        }
+                    } catch (_: Exception) {
+                    }
+                }
+
                 if (parent is SwipeRefreshLayout && child is ImageView) {
                     // SwipeRefreshLayout class which has CircleImageView as a child,
                     // does not handle `startViewTransition` properly.

```

**Comment by leoimelzer** [comment]
> For anyone who still encounters a similar error:
> 
> ```
> Exception thrown when executing UIFrameGuarded
> Cannot remove child at index x from parent ViewGroup [xx], only x children in parent. Warning: childCount may be incorrect!
> The spcified child already has a parent. You must call removeView() on the child's parent first.
> ```
> 
> I fixed it by changing "headerTitleAlign" from "center" to "left" in my stack screen options. But I reckon it's still an issue.

Facing very same issue here and only with your suggestion I could make it work.

I have following versions applied on project:

```
{
    "@react-navigation/bottom-tabs": "7.7.3",
    "@react-navigation/native": "7.1.19",
    "@react-navigation/native-stack": "7.6.2",
    "react-native-screens": "~4.11.1",
    "react-native": "0.79.6",
    "react-native-reanimated": "~3.17.4"
}
```

did you find any other solution rather than changing the title alignment?
