### ISSUE TITLE
No view found for id 0x20 (unknown) for fragment ScreenFragment Android in React-Native 0.75

### ISSUE THREAD

**Issue by abrah4mr** [software-mansion/react-native-screens#2345]
### Description

If you change repeatedly between tabs you get the following error:

https://github.com/user-attachments/assets/6437a2af-cb27-4715-8bad-6c1ed4238e1f

Note: I have to use the 3.35.0-rc.1 version, because of this issue: https://github.com/software-mansion/react-native-screens/issues/2324#issue-2493613911

Seems to work if you add the `detachInactiveScreens={false}` prop to the Tab.Navigator

Dependencies:

```
{
    "@react-navigation/bottom-tabs": "6.6.1",
    "@react-navigation/native": "6.1.18",
    "@react-navigation/native-stack": "6.11.0",
    "@react-navigation/stack": "6.4.1",
    "react": "18.3.1",
    "react-native-gesture-handler": "2.19.0",
    "react-native-safe-area-context": "4.11.0",
    "react-native-screens": "3.35.0-rc.1",
}
```

### Steps to reproduce

1. Create a TabNavigator with React-Navigation
2. Change between the tabs until get the error

### Snack or a link to a repository

nel

### Screens version

3.35.0-rc.1

### React Native version

0.75.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Thanks for reporting this @abrah4mr. #2351 should fix this. We plan on releasing library version early next week

**Comment by abrah4mr** [comment]
@kkafar Thanks!
