### ISSUE TITLE
Android, Breaks ScrollView/FlatList when inside a stack with goBackGesture

### ISSUE THREAD

**Issue by Aletagro** [software-mansion/react-native-screens#2362]
### Description

If you add ScrollView/FlatList to the stack with goBackGesture enabled (for example: verticalSwipe). goBackGesture works fine, but lists cannot be scrolled

### Steps to reproduce

1. Create a Stack Screen with goBackGesture
2. Add ScrollView/FlatList inside of it and navigate to it
3. Try to scroll - impossible

### Snack or a link to a repository

https://github.com/Aletagro

### Screens version

3.31.1-4.0.0-beta.0

### React Native version

0.74.5

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @Aletagro, could you provide at least a snack with a code that we can reproduce the issue on?

**Comment by WKampel** [comment]
Same issue

**Comment by WKampel** [comment]
Same issue

**Comment by kkafar** [comment]
I believe this PR should solve the issue: https://github.com/software-mansion/react-native-screens/pull/2383
