### ISSUE TITLE
ReactNative v0.75.4 with new architecture android app is crashing

### ISSUE THREAD

**Issue by sankar-gp** [software-mansion/react-native-screens#2390]
### Description

ReactNative v0.75.4 with new architecture android app is crashing when I click back. But it's working in iOS and when I disable new arch it's working fine. Issue is only with newArchEnabled=true

Error Log:
Cannot remove child at index 1 from parent ViewGroup[1332], only 2 children in parent. Warning: childCount may be incorrect! null

App should not crash when newArchEnabled=true

### Steps to reproduce

use react native v0.75.4, app is crashing 

### Snack or a link to a repository

norepo

### Screens version

3.34.0

### React Native version

0.75.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @sankar-gp, thanks for reporting. I believe you're talking about this issue: https://github.com/software-mansion/react-native-screens/issues/2341
we're aware of it. See the conversation, there are some temporary workaround suggested there.
