### ISSUE TITLE
Require cycles break Metro import support

### ISSUE THREAD

**Issue by EvanBacon** [software-mansion/react-native-screens#2408]
### Description

The require cycles in files like https://github.com/software-mansion/react-native-screens/blob/3ca34864e9d4e67bedef94079516b9d1e5a5b97a/src/components/ScreenContainer.tsx#L5C39-L5C59 where a module imported by `react-native-screens` imports `react-native-screens` leads to a require cycle. 

This is generally not great, but it leads to a break in Metro when using built-in import support:
```js
config.transformer.getTransformOptions = () => ({
  transform: {
    experimentalImportSupport: true
    inlineRequires: false,
  },
});
```

This should be fixed upstream in Metro (cc @robhogan) but figure it'd be good to also resolve it in `react-native-screens`.

### Steps to reproduce

1. Expo Router project on iOS, or Android
2. Configure Metro to use experimentalImportSupport (`npx expo customize metro.config.js`):
```js
config.transformer.getTransformOptions = () => ({
  transform: {
    experimentalImportSupport: true
    inlineRequires: false,
  },
});
```
3. Open project, it should crash with something like `Warning: TypeError: freezeEnabled is not a function (it is undefined)`

### Snack or a link to a repository

https://snack.expo.io

### Screens version

react-native-screens@4.0.0-beta.9

### React Native version

react-native@0.76.0-rc.4

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
I see @EvanBacon, thanks for noticing this. We'll sort this out with next beta.
