### ISSUE TITLE
Typescript definitions for createNativeStackNavigator

### ISSUE THREAD

**Issue by bartzy** [software-mansion/react-native-screens#242]
Are there any type definitions for `createNativeStackNavigator`?

**Comment by WoLewicki** [comment]
They are available https://github.com/software-mansion/react-native-screens/blob/master/src/screens.d.ts and https://github.com/software-mansion/react-native-screens/blob/master/native-stack/types.tsx. If you have any questions, feel free to comment here.

**Comment by Raffpy** [comment]
What happened with the links?

> They are available https://github.com/software-mansion/react-native-screens/blob/master/src/screens.d.ts and https://github.com/software-mansion/react-native-screens/blob/master/native-stack/types.tsx. If you have any questions, feel free to comment here.

**Comment by WoLewicki** [comment]
@Raffpy the whole repo is written in typescript now so `.d.ts` files are not used. You can look for types directly in the files with the code or in `lib` folder in `react-native-screens` in your `node_modules`
