### ISSUE TITLE
React Native 0.76 (new arch, bridgeless) support

### ISSUE THREAD

**Issue by craiganderson-iotv** [software-mansion/react-native-screens#2441]
### Description

Using React Native 0.76 with the new architecture in bridgeless mode results in two pathways for errors on Android:

1. Using `react-native-screens@3.34.1` will build correctly, but encounteres the same issue as #2324 
1. Using `react-native-screens@3.35.0-rc.1`, which fixes the above, will not build for 0.76

I managed to patch `3.34.1` according to #2289, which allows the error to be bypassed, but then only shows a white screen. Everything works after closing / opening the app again

### Steps to reproduce

1. Use React Native 0.76.0 and `react-native-screens@3.34.1`
2. Encounter an error whilst running in dev mode
3. Hot-reload

### Snack or a link to a repository

-

### Screens version

3.34.1

### React Native version

0.76.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by Hao-yiwen** [comment]
Same question.

**Comment by kkafar** [comment]
Hey @craiganderson-iotv thanks for reporting. We've just released [3.35.0](https://github.com/software-mansion/react-native-screens/releases/tag/3.35.0) which should resolve the situation.

Let me know if that is not the case.

**Comment by tohel17** [comment]
@kkafar faced this same issue on 0.75.4 updated react-native-screens to 3.35.0
getting this error
![image](https://github.com/user-attachments/assets/f2ac0d2f-a371-44c5-b433-8d558a514f74)

**Comment by kkafar** [comment]
Hey @tohel17, the issue you encounter is not related to react-native-screens. It is related to `react-native-safe-area-context` and possibly [this breaking change](https://github.com/facebook/react-native/commit/55671c00e5567845ffe467e50a4b9dfa562e48db) introduced with 0.76.0 version of react-native.

**Comment by tohel17** [comment]
@kkafar My bad updating safe area library fixed it.

**Comment by kkafar** [comment]
@tohel17 I'm glad to hear that!
