### ISSUE TITLE
headerBlurEffect does not work in the new architecture

### ISSUE THREAD

**Issue by matinzd** [software-mansion/react-native-screens#2445]
### Description

Native `headerBlurEffect` does not work in the new architecture.

![image](https://github.com/user-attachments/assets/1645635f-70f9-47b9-a2fa-cf440bdcd2c9)

### Steps to reproduce

1. Enable new arch in RN 76
2. Set `headerBlurEffect` to `light` and set `headerTransparent` to true

### Snack or a link to a repository

https://github.com/matinzd/RN76RNScreensBug

### Screens version

3.41.1

### React Native version

0.76.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 16

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hi, thanks for reporting!

It does! Use latest 3.35.0 (released few minutes ago) [(link)](https://github.com/software-mansion/react-native-screens/releases/tag/3.35.0) or latest beta version of screens.

**Comment by matinzd** [comment]
Very nice! Thanks for the release :)

**Comment by pedrio-gh** [comment]
Thanks a lot for the fix guys!
