### ISSUE TITLE
i am getting error no view found for id 

### ISSUE THREAD

**Issue by medigini** [software-mansion/react-native-screens#2453]
### Description

my app is getting crash without any log 
![WhatsApp Image 2024-10-26 at 3 15 25 AM](https://github.com/user-attachments/assets/c0ce244a-b24a-44d5-a4c8-7d41a1f5af66)

### Steps to reproduce

![WhatsApp Image 2024-10-26 at 3 15 25 AM](https://github.com/user-attachments/assets/c3eee7e5-0c43-4837-970c-fbeb833b26c4)

### Snack or a link to a repository

not available

### Screens version

3.35.0

### React Native version

0.76

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

Real device

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @medigini thanks for reporting!

@alduzy didn't we fix something similar? Do you remember the issue? Maybe I just haven't cherry-picked some PR for the 3.35.0 version? Would you have some context.

**Comment by kkafar** [comment]
@medigini I guess this is error from production? Or are you able to observe of what interaction this crash happens? W/o proper reproduction it might be hard to come up with any solution.
