### ISSUE TITLE
When I Installing dependencies into a bare React Native project,The program cannot start

### ISSUE THREAD

**Issue by Amoslzh** [software-mansion/react-native-screens#2458]
### demo
https://github.com/Amoslzh/errro-demo

### Description

"@react-navigation/native": "^6.1.18",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-safe-area-context": "^4.12.0",
    "react-native-screens": "^3.35.0"

When I Installing dependencies into a bare React Native project,The program cannot start。
The error is as follows

C/C++: fatal error: too many errors emitted, stopping now [-ferror-limit=]
C/C++: 15 warnings and 20 errors generated.
C/C++: C:\Users\zhihao.liang\AppData\Local\Android\Sdk\ndk\25.1.8937393\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android21 --sysroot=C:/Users/zhihao.liang/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DFOLLY_NO_CONFIG=1 -Drnscreens_EXPORTS -IC:/project/RNproject/newProject/node_modules/react-native-screens/android/../cpp -isystem C:/Users/zhihao.liang/.gradle/caches/transforms-3/e1231b5b187cb579b629117f9511a862/transformed/jetified-react-android-0.73.6-debug/prefab/modules/jsi/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -std=c++20 -MD -MT CMakeFiles/rnscreens.dir/src/main/cpp/jni-adapter.cpp.o -MF CMakeFiles\rnscreens.dir\src\main\cpp\jni-adapter.cpp.o.d -o CMakeFiles/rnscreens.dir/src/main/cpp/jni-adapter.cpp.o -c C:/project/RNproject/newProject/node_modules/react-native-screens/android/src/main/cpp/jni-adapter.cpp        
C/C++: C:/project/RNproject/newProject/node_modules/react-native-screens/android/src/main/cpp/jni-adapter.cpp:1:10: fatal error: 'jni.h' file not found
C/C++: #include <jni.h>
C/C++:          ^~~~~~~
C/C++: 1 error generated.

> Task :react-native-safe-area-context:compileDebugKotlin
w: file:///C:/project/RNproject/newProject/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextModule.kt:6:46 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/project/RNproject/newProject/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextModule.kt:8:2 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/project/RNproject/newProject/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt:6:46 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/project/RNproject/newProject/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt:25:51 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/project/RNproject/newProject/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt:27:11 'constructor ReactModuleInfo(String!, String!, Boolean, Boolean, Boolean, Boolean, Boolean)' is deprecated. Deprecated in Java
w: file:///C:/project/RNproject/newProject/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt:33:27 'hasConstants: Boolean' is deprecated. Deprecated in Java
w: file:///C:/project/RNproject/newProject/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaProviderManager.kt:4:46 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/project/RNproject/newProject/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaProviderManager.kt:11:2 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/project/RNproject/newProject/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaView.kt:59:23 'getter for uiImplementation: UIImplementation!' is deprecated. Deprecated in Java
w: file:///C:/project/RNproject/newProject/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaViewManager.kt:4:46 'ReactModule' is deprecated. Deprecated in Java   
w: file:///C:/project/RNproject/newProject/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaViewManager.kt:14:2 'ReactModule' is deprecated. Deprecated in Java   

> Task :react-native-screens:compileDebugKotlin FAILED
57 actionable tasks: 5 executed, 52 up-to-date

 fatal error: too many errors emitted, stopping now [-ferror-limit=]
  15 warnings and 20 errors generated.
  [2/3] Building CXX object CMakeFiles/rnscreens.dir/src/main/cpp/jni-adapter.cpp.o
  FAILED: CMakeFiles/rnscreens.dir/src/main/cpp/jni-adapter.cpp.o
  C:\Users\zhihao.liang\AppData\Local\Android\Sdk\ndk\25.1.8937393\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android21 --sysroot=C:/Users/zhihao.liang/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DFOLLY_NO_CONFIG=1 -Drnscreens_EXPORTS -IC:/project/RNproject/newProject/node_modules/react-native-screens/android/../cpp -isystem C:/Users/zhihao.liang/.gradle/caches/transforms-3/e1231b5b187cb579b629117f9511a862/transformed/jetified-react-android-0.73.6-debug/prefab/modules/jsi/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -std=c++20 -MD -MT CMakeFiles/rnscreens.dir/src/main/cpp/jni-adapter.cpp.o -MF CMakeFiles\rnscreens.dir\src\main\cpp\jni-adapter.cpp.o.d -o CMakeFiles/rnscreens.dir/src/main/cpp/jni-adapter.cpp.o -c C:/project/RNproject/newProject/node_modules/react-native-screens/android/src/main/cpp/jni-adapter.cpp
  C:/project/RNproject/newProject/node_modules/react-native-screens/android/src/main/cpp/jni-adapter.cpp:1:10: fatal error: 'jni.h' file not found
  #include <jni.h>
           ^~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\zhihao.liang\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "C:\\project\\RNproject\\newProject\\node_modules\\react-native-screens\\android\\.cxx\\Debug\\5b31282w\\arm64-v8a" ^
        rnscreens
    from C:\project\RNproject\newProject\node_modules\react-native-screens\android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-screens:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

BUILD FAILED in 13s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

### Steps to reproduce

1.yarn add @react-navigation/native
2.yarn android  (success)
3.npx expo install react-native-screens react-native-safe-area-context
4.yarn android (fail)
5.yarn remove react-native-safe-area-context   yarn android (fail)

### Snack or a link to a repository

no

### Screens version

3.35.0

### React Native version

0.73.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by GenGraphic** [comment]
Same here!
