### ISSUE TITLE
Stack navigation unmounts previous screen too early with new arch

### ISSUE THREAD

**Issue by Veeksi** [software-mansion/react-native-screens#2459]
### Description

When updating from 3.31.1 to 4.0.0-beta.14 and updating expo sdk from 51 to 52 next defined problem occurs.

The animation is basic 'slide_from_right' animation. The problem is that once we navigate to second screen, the second screen unmounts during animation. However when using older version, the second screen unmounts after animation which is wanted behaviour.

Basically the code looks like this:
```typescript
import { NavigationContainer, useNavigation } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { Button, Text, View } from 'react-native';

const RNStack = createNativeStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <RNStack.Navigator>
        <RNStack.Screen name='First' component={First} />
        <RNStack.Screen
          name='Second'
          component={Second}
          options={{ animation: 'slide_from_right' }}
        />
      </RNStack.Navigator>
    </NavigationContainer>
  );
}

const First = (): JSX.Element => {
  const navigation = useNavigation();
  return (
    <View
      style={{
        flex: 1,
        backgroundColor: 'red',
        justifyContent: 'center',
        alignItems: 'center',
      }}
    >
      <Text>first</Text>
      <Button
        title='Go to second XD'
        onPress={() => navigation.navigate({ name: 'Second' })}
      />
    </View>
  );
};

const Second = () => {
  return (
    <View style={{ flex: 1, backgroundColor: 'blue' }}>
      <Text>second</Text>
    </View>
  );
};
```

Animation works on older version:

https://github.com/user-attachments/assets/58992cf8-6611-49c6-928d-f0b88eaabcb9

Animation doesn't work on newer version:

https://github.com/user-attachments/assets/5ff03ceb-b8bf-45c9-8819-e156ac3e954d

You can test working animation that uses sdk51 on 'main' branch here: https://github.com/Veeksi/rn-navigation-problem/tree/main
Broken animation can be found on 'sdk52' branch here: https://github.com/Veeksi/rn-navigation-problem/tree/sdk52

### Steps to reproduce

1. Click "Go to second" button
2. Notice that view animates from left to right
3. Swipe back
4. Notice that view animates from right to left but during the animation, previous screen unmounts when it should stay mounted until animation completes

### Snack or a link to a repository

You can test working animation that uses sdk51 on 'main' branch here: https://github.com/Veeksi/rn-navigation-problem/tree/main 

Broken animation can be found on 'sdk52' branch here: https://github.com/Veeksi/rn-navigation-problem/tree/sdk52

### Screens version

Works on 3.31.1 and doesn't work on 4.0.0-beta.14

### React Native version

0.74.5 was used with sdk51. 
0.76.0 was used with sdk52.
 
### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Oneplus Nord 2

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @Veeksi, what react native version have you used in sdk 51? (there were two available - 74 & 75)?

**Comment by Veeksi** [comment]
> Hey @Veeksi, what react native version have you used in sdk 51? (there were two available - 74 & 75)?

Hey, I used 0.74.5

**Comment by Veeksi** [comment]
I have created issue in expo's github too. See it here: https://github.com/expo/expo/issues/32425

**Comment by alduzy** [comment]
@Veeksi Thanks for reporting! I believe it's a copy of https://github.com/software-mansion/react-native-screens/issues/1685. Let's move the conversation there.
