### ISSUE TITLE
Navigating back from modal has animation glitch in old architecture with RNS 4.0.0 (React Navigation v7)

### ISSUE THREAD

**Issue by roshangm1** [software-mansion/react-native-screens#2488]
### Description

When navigating back from a presentation modal screen manually, there is no slide down animation. This makes the app look glitchy. 

Reproduction link uses expo router in the example but also happens when not using it. 

![Simulator Screen Recording - iPhone 14 Pro - 2024-11-10 at 20 11 45](https://github.com/user-attachments/assets/b5413021-3bbc-4bd3-b51d-9d5c5a0a1f6a)

### Steps to reproduce

1. Create a new app old architecture 
2. Two screens in a stack navigator, one with "presentation": "modal"
3. Navigate to the modal
4. Navigate back using `navigation.goBack` or `router.back`

### Snack or a link to a repository

https://github.com/roshangm1/rns-modal-navigation-animation-glitch

### Screens version

4.0.0

### React Native version

0.76.0

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
I confirm the issue is reproducible, thanks for reporting
