### ISSUE TITLE
`java.lang.String` cannot be cast to `com.facebook.react.bridge.ReadableArray`

### ISSUE THREAD

**Issue by craiganderson-iotv** [software-mansion/react-native-screens#2489]
### Description

Using latest of all libraries, upon launch the app displays the following error:
![image](https://github.com/user-attachments/assets/2c493f84-5892-4fdf-8764-8d0fc6ab2712)
Reloading the app causes the error to disappear, however because it errored during startup, React Native Screens will not work and merely displays a blank white screen

Relaunching the app works correctly thereafter, so it's more of an annoyance than a real issue

### Steps to reproduce

1. Use the latest React Native and React Native Screens
2. Run app on Android
3. Observe error

### Snack or a link to a repository

N/A

### Screens version

4.0.0

### React Native version

0.76.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by Vercixxx** [comment]
Are you using expo/eas? If so check expo doctor. I encountered same problem, im my case changing versions of 3 dependecies
- @react-native-picker/picker@2.7.5,  
- expo@~51.0.39, 
- react-native-screens@3.31.1
 and buiding app again resolved problem. Good luck!

**Comment by kkafar** [comment]
@craiganderson-iotv hey, thanks for reporting. The issue is irreproducible with the reproduction steps you provided. I do remember having similar problem in development some time ago - it was due to mismatch between react-navigation version and react-native-screens version.

My hypothesis is that you're using `react-native-screens` 4.0.0 with `react-navigation` 6.x.x - this won't work. 4.0.0 requires 7.x.x line of `react-navigation`.

**Comment by craiganderson-iotv** [comment]
@kkafar Thanks for getting back to me, I think I have resolved the issue - or at least cannot reproduce it myself anymore.

I had some overrides from the React Native `0.76` new architecture migration that seemed to have caused the issues:

```text
"overrides": {
    "@react-navigation/drawer": {
      "react-native-screens": "$react-native-screens"
    },
    "@react-navigation/native-stack": {
      "react-native-screens": "$react-native-screens"
    },
    "@react-navigation/stack": {
      "react-native-screens": "$react-native-screens"
    }
```

My apologies for the unnecessary issue

**Comment by kkafar** [comment]
Glad to hear you got it working
