### ISSUE TITLE
Minimal Expo 52 app crashes when using form sheet modals when using RNTP

### ISSUE THREAD

**Issue by doughsay** [software-mansion/react-native-screens#2507]
### Description

When using react-native-track-player, which uses a Headless JS Task, form sheet modals crash when being opened after the app has been closed once. I haven't been able to reproduce this without using react-native-track-player, but the maintainers there seem to think it's not related to their package.  I'm having a hard time knowing where to look for help, and what else to try.

Video showing the crash:

[rntp-crash.webm](https://github.com/user-attachments/assets/e2204046-7550-419e-8270-00ad677d6e17)

### Steps to reproduce

1. open the app
2. see that the form sheet modal opens
3. close the app (not just background)
4. open the app again
5. try and open the modal and see that it crashes instead

### Snack or a link to a repository

https://github.com/doughsay/expo-test-app

### Screens version

4.0.0

### React Native version

0.76.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 9 Pro XL API 35

### Acknowledgements

Yes

**Comment by doughsay** [comment]
Updated to react-native 0.76.2, it didn't help

**Comment by doughsay** [comment]
Updated to react-native-screen 4.1.0, no change, still crashes.  If anyone here thinks this isn't related to anything in react-native-screens, please let me know so I can maybe file an issue somewhere else.  It's a bit over my head, and I really need help figuring it out.

**Comment by radko93** [comment]
Are you using new architecture? headless is broken with new arch https://github.com/facebook/react-native/issues/47570

**Comment by doughsay** [comment]
> Are you using new architecture? headless is broken with new arch https://github.com/facebook/react-native/issues/47570

No, old architecture, although I've tried both. But you can see in my repo I have it currently disabled.

**Comment by mikehardy** [comment]
:wave: I'm looking into upstream facebook/react-native/issues/47570 and having trouble reproducing

Right now there is *definitely* a problem with old-architecture and headlessJS - I have a clean reproducer up and it is tracking in facebook/react-native/issues/47592

I am unable to reproduce failures yet with new architecture and 0.76.1 or .2 but I understand from comments you do reproduce here. I'll see what I can do about converging the two reproducers to something truly minimal (no react-native-track-player needed if possible...) and post it up on 47570

**Comment by mikehardy** [comment]
I don't believe this is related to headlessJS crashes. I think this is something different now.

**Comment by kkafar** [comment]
Could someone confirm whether applying this patch resolves the issue for you?

https://github.com/software-mansion/react-native-screens/pull/2526.patch

You can either apply this patch or try to install react-native-screens directly from branch:

`"react-native-screens": "software-mansion/react-native-screens#@kkafar/fix-crash-with-proxy-already-registered"`

**Comment by kkafar** [comment]
Thanks for confirmation. I'll release it later today
