### ISSUE TITLE
Crash when switching tabs after updating to Expo 52 (old arch)

### ISSUE THREAD

**Issue by wongk** [software-mansion/react-native-screens#2512]
### Description

I have a Tamagui app that uses Expo and React Native for our native apps. Today I updated to the latest Expo 52, and updated all of our dependencies. The app runs, but any time I switch tabs (on both iOS and Android), the app crashes. The stack trace points to the crash coming from react-native-screens. We are using the old architecture.

```
 ERROR  Warning: TypeError: Cannot read property 'regular' of undefined

This error is located at:
    in SceneView (created by NativeStackView)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in Unknown (created by ScreenStack)
    in ScreenStack (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator
    in Unknown (created by Layout)
    in Layout
    in Unknown (created by Route(profile))
    in Suspense (created by Route(profile))
    in Route (created by Route(profile))
    in Route(profile) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by Navigator)
    in NavigatorSlot (created by Slot)
    in Slot (created by AppNavigation)
    in Navigator (created by AppNavigation)
    in RCTView (created by TabsContent)
    in TabsContent
    in Unknown (created by Themed(Anonymous))
    in Theme (created by Themed(Anonymous))
    in Themed(Anonymous) (created by TabsContents)
    in TabsContents (created by BottomTabBar)...
```

### Steps to reproduce

I don't have specific steps. Please see the stack trace in the description.

### Snack or a link to a repository

I am not able to provide a reproduction

### Screens version

4.1.0

### React Native version

0.76.2

### Platforms

Android, iOS, Web

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by Odyrac** [comment]
same here

**Comment by wongk** [comment]
I was able to track this down and it is not a react-native-screens issue. I only assumed so due to the call stack. For anyone else experiencing this issue, `ThemeProvider` from react-navigation now requires the `fonts` property. I solved this as follows:

```
    <ThemeProvider
      value={{
        ...DefaultTheme,
        dark: scheme === "dark",
        colors: {
             ...
        },
      }}
    >
      {children}
    </ThemeProvider>
```

**Comment by kkafar** [comment]
Glad to hear you managed to resolve this!

**Comment by kkafar** [comment]
@Odyrac was your case the same?
