### ISSUE TITLE
RNScreens Attempt to register InsestsObserverProxy on DecorView a while it has been already registered on DecorView b EXPO SDK 52

### ISSUE THREAD

**Issue by Odyrac** [software-mansion/react-native-screens#2519]
### Description

After migrating to Expo SDK52 my project is starting with an error. The first time it's working and on the first reload the error RNScreens Attempt to register InsestsObserverProxy on DecorView a while it has been already registered on DecorView b is shown on Expo Go (not in the console).

### Steps to reproduce

Use React Native Screens with Expo SDK 52.

### Snack or a link to a repository

/

### Screens version

4.2.0 and 4.1.0

### React Native version

0.76.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by Odyrac** [comment]
Hi, when i delete all the data of my Expo Go it's working once, then error comes back. So many issues since upgrading to sdk 52 lmao

**Comment by outaTiME** [comment]
> Hi, when i delete all the data of my Expo Go it's working once, then error comes back. So many issues since upgrading to sdk 52 lmao

Hi @Odyrac,  
(As I mentioned earlier) I don't think this is specific to Expo 52. I'm experiencing the same issue with the previous version of Expo.

**Comment by Odyrac** [comment]
> > Hi, when i delete all the data of my Expo Go it's working once, then error comes back. So many issues since upgrading to sdk 52 lmao
> 
> Hi @Odyrac, (As I mentioned earlier) I don't think this is specific to Expo 52. I'm experiencing the same issue with the previous version of Expo.

What was the trigger for you? I didn't have this error before upgrading

**Comment by outaTiME** [comment]
> > > Hi, when i delete all the data of my Expo Go it's working once, then error comes back. So many issues since upgrading to sdk 52 lmao
> > 
> > 
> > Hi @Odyrac, (As I mentioned earlier) I don't think this is specific to Expo 52. I'm experiencing the same issue with the previous version of Expo.
> 
> What was the trigger for you? I didn't have this error before upgrading

In your case, this error is probably happening because you updated to react-native-screens version 4.x when switching to Expo 52. This issue didn’t occur with version 3.35.0.

**Comment by Odyrac** [comment]
Yes but I tried to use version 3.35.0 and I had other errors due to incompatibilty with Expo probably, so I still don't have solution with sdk52

**Comment by outaTiME** [comment]
Just in case, 
here’s a video of the issue (using Expo 51 with react-native ~0.75.4 and react-native-screens ^4.2.0): 

https://github.com/user-attachments/assets/4386e05b-2d72-4e3b-aa5d-e27295a77a1d

**Comment by kkafar** [comment]
I want to confirm that I've managed to reproduce the issue.

**Comment by kkafar** [comment]
@outaTiME Idk your setup, but Expo 51 used react-navigation v6, which is incompatible with `react-native-screens@4`. Second thing is that the error messsage you got suggests that you need to rebundle the app. I guess fresh install would be the best to ensure there are no invalidated caches there: `rm -fr node_modules android/build android/app/build && yarn install && yarn start --reset-cache`.

Note that AFAIK if you're running your app with Expo Go you can not just hotswap library version, as the native code won't be rebuilt. AFAIK you need the development build.

**Comment by outaTiME** [comment]
> > @outaTiME Idk your setup, but Expo 51 used react-navigation v6, which is incompatible with `react-native-screens@4`. Second thing is that the error messsage you got suggests that you need to rebundle the app. I guess fresh install would be the best to ensure there are no invalidated caches there: `rm -fr node_modules android/build android/app/build && yarn install && yarn start --reset-cache`.
> > Note that AFAIK if you're running your app with Expo Go you can not just hotswap library version, as the native code won't be rebuilt. AFAIK you need the development build.
> 
> Got it, I didn’t know that react-native-screens@4 wasn’t compatible with Expo 51 and React Navigation 6.
> 
> On another note, I updated the react-native-screens dependency to point to your branch and created a fresh development build using `expo run:android --variant debug --device`. Before that, I deleted the Android folder to avoid conflicts, but I didn’t clear the `node_modules` or Yarn cache.

Maybe my issue is related to how Yarn 4.x downloads dependencies from a branch. When I check the downloaded code, the `android` folder seems incomplete:

![CleanShot 2024-11-20 at 11 01 22@2x](https://github.com/user-attachments/assets/22ac0f55-f8cb-4f04-9b03-25ea7fabe71d)

**Comment by kkafar** [comment]
Yeah, this definitely looks like some kind of problem with our package. We've had this behaviour reported before (when installing the library from branch source files aren't downloaded), but I've no idea why this happens. It is especially baffling that when I'm installing from branch it works...

**Comment by Odyrac** [comment]
> Could someone confirm whether applying this patch resolves the issue for you?
> 
> https://github.com/software-mansion/react-native-screens/pull/2526.patch
> 
> You can either apply this patch or try to install react-native-screens directly from branch:
> 
> `"react-native-screens": "software-mansion/react-native-screens#@kkafar/fix-crash-with-proxy-already-registered"`

Is this patch compatible with Expo environment ?
git apply 2526.patch
error: android/src/main/java/com/swmansion/rnscreens/InsetsObserverProxy.kt: No such file or directory
error: android/src/main/java/com/swmansion/rnscreens/RNScreensPackage.kt: No such file or directory

I don't have android folder in my project

**Comment by Odyrac** [comment]
Okay so I apply the patch directly in the module react-native-screens (this actually seems more logical) but still get same error message with the second reload. I started with --clear my expo go to be sure of no conflict

**Comment by Odyrac** [comment]
I don't understand why the issue was closed because it's still a problem.

I tried to update RNScreens, I'm now in "react-native-screens": "^4.2.0", but still the same error when app is starting :(

**Comment by kkafar** [comment]
The issue is closed because the PR with fix has been merged. The release will be in few hours, I had a minor hickup when testing

**Comment by kkafar** [comment]
I've released the 4.3.0 which hopes to resolve the issue. Let me know in case the issue persists.

**Comment by Odyrac** [comment]
@kkafar I tried but still same error. Did you investigate into statusBarTranslucent ? If I remove it, error disappear

**Comment by OlivierSte** [comment]
> @kkafar I tried but still same error. Did you investigate into statusBarTranslucent ? If I remove it, error disappear

@Odyrac  Did you manage to fix it? I'm experiencing the exact same issue. If I remove the statusBarTranslucent it disappears. 
I have the 4.40 version of react-native-screens
