### ISSUE TITLE
`sheetAllowedDetents: "fitToContents"` doesn't seem to work?

### ISSUE THREAD

**Issue by johankasperi** [software-mansion/react-native-screens#2521]
### Description

Thanks for an awesome library! 

When setting `sheetAllowedDetents: "fitToContents"` or `sheetAllowedDetents: [-1]` it seems to have no effect? I've tried adding this config to the "FormSheet" screen in the `StackPresentation` example in the example project. I've also removed everything inside the `FormScreen` but still the sheet detents is not equal to the content height. I thought we could expect the formsheet to act similar to when setting `size={["auto]}` in https://github.com/lodev09/react-native-true-sheet Is that not the case?

### Steps to reproduce

1. Run Example app in this repo.
2. Add `sheetAllowedDetents: "fitToContents"` in the options here: https://github.com/software-mansion/react-native-screens/blob/5fa039effe7b37c49ab26386ee87def0bb35ab11/apps/src/screens/StackPresentation.tsx#L180

### Snack or a link to a repository

https://github.com/software-mansion/react-native-screens/blob/main/apps/src/screens/StackPresentation.tsx#L180

### Screens version

4.2.0

### React Native version

0.76.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 16 Pro iOS 18.1

### Acknowledgements

Yes

**Comment by kkafar** [comment]
@johankasperi you're right. I've used `Test1649` for all my development testing and I haven't updated the example app. Done it in  #2528.

You can test the Example app after the #2528 is merged. 

> [!note]
What was wrong there is usage of flex: 1 on top level container in the sheet. See release notes for explanation on current limitations of this presentation style: https://github.com/software-mansion/react-native-screens/releases/tag/4.0.0
