### ISSUE TITLE
ScreenFooter missing an export in web version

### ISSUE THREAD

**Issue by chrisnojima** [software-mansion/react-native-screens#2534]
### Description

This commit (https://github.com/software-mansion/react-native-screens/pull/2504/files#diff-96fd20779df1dada3660b5dbaaeb48a45528b25c038ae5b621e19f2e2671fcc3R16) introduces a new export `FooterComponent` in `ScreenFooter` but the web variant (https://github.com/software-mansion/react-native-screens/blob/main/src/components/ScreenFooter.web.tsx) does not have this, so if you mix react-navigation with screens on web you'll have an import error

cc: @kkafar 

### Steps to reproduce

Try and build a web app using navigation/screens and you'll see it complain there is no component exported by that name

### Snack or a link to a repository

sorry

### Screens version

4.3.0

### React Native version

0.75.4

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Thanks! I need to setup CI for web...

**Comment by Delindel** [comment]
Hello! We were debugging the conflict and got to this fix, however its not installed by Yarn, seems to install the contents of @4.2.0 so we downgraded to @4.1.0 and it worked.

Do you know why yarn would not be downloading the correct contents of this fix along with @4.3.0?

Tried cleaning cache, nuking node_modules, changing terminals, nothing.

If we missed something super obvious please enlighten us!
