### ISSUE TITLE
Android model w/ slide_from_bottom is transparent while closing

### ISSUE THREAD

**Issue by marklawlor** [software-mansion/react-native-screens#2571]
### Description

Expo Router issue: https://github.com/expo/expo/issues/33517
React Navigation: https://github.com/react-navigation/react-navigation/issues/12333

React Navigation reproduction provided below. Please note that the video below is from originally reported Expo Router repro

Original Report: 

When dismissing a modal the modal body is transparent. This is a very basic modal following the guide [here](https://docs.expo.dev/router/advanced/modals/). The modal body is fine when the modal is opening.

https://github.com/user-attachments/assets/8e7470fc-08bc-4c4f-9ce7-2481aafcced4

### Steps to reproduce

1. Run repro on android
2. Press "Go to settings"
3. Press "close"

### Snack or a link to a repository

https://github.com/marklawlor/react-navigation-33517

### Screens version

4.1.0

### React Native version

0.76.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Thanks for reporting!

**Comment by kkafar** [comment]
@marklawlor The reproduction you provided works absolutely fine when expo is taken out of the equation. Try to run `FabricExample` on #2576 (I've pasted the reproduction there). I've tried few different / screen / navigator combinations but haven't been able to reproduce. Right now it looks like this is some downstream issue. 

https://github.com/user-attachments/assets/06a9970a-6d1b-4551-9374-394d43b8fc8d

**Comment by marklawlor** [comment]
Confirmed that the issue is now resolved in new Expo projects with latest dependencies. The issue is only reproducible in Expo Go and users should migrate to a development build. Expo Go will be updated around the `react-native-screens@4.4.0` release
