### ISSUE TITLE
App crashes on Android: [RNScreens] Attempt to register InsetsObserverProxy

### ISSUE THREAD

**Issue by Tobbe** [software-mansion/react-native-screens#2582]
### Description

My app crashes as soon as I start it when using Expo Go.

![image](https://github.com/user-attachments/assets/42a2527a-4fef-4f7e-93e1-65be4b199989)

If I switch to a development build it works fine

![image](https://github.com/user-attachments/assets/14883533-df15-47d6-89c5-81d26cc29318)

It seems that setting the statusbar to be translucent might be the cuprit

Broken:
```tsx
export default function RootLayout() {
  return <Stack screenOptions={{ statusBarTranslucent: true }} />;
}
```

Works:
```tsx
export default function RootLayout() {
  return <Stack />;
}
```

### Steps to reproduce

Clone and run the linked repo. Open the app using Expo Go on an Android Emulator. It should immediately crash, showing the screen in the screenshot above

### Snack or a link to a repository

https://github.com/Tobbe/expo-status-bar

### Screens version

4.1.0

### React Native version

0.76.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

API 35

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @Tobbe, thanks for reporting. The issue you describe was fixed with #2526 and is already released with version 4.3.0 of the library. As for Expo Go I can't say what is the library upgrade strategy there. Developement build is surely way to go.
