### ISSUE TITLE
Not compatiable wtih RN 0.77.0-rc.4

### ISSUE THREAD

**Issue by kprabath** [software-mansion/react-native-screens#2588]
### Description

I installed react-native-screens for my React Native 77+ project, which supports the Android 15 page size memory. However, when I tried to compile the project, it threw the following compilation error. It seems the React Native team has made changes to some core libraries, and adjustments might be needed in your libraries to accommodate these changes.

I understand that RN version 77.rc.4 is still in beta, but I would like to seek help with this since this version supports compatibility with the Android 15 page size memory

node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainerViewManager.kt:20:71 Type argument is not within its bounds: should be subtype of 'BaseViewManagerInterface!'
node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContentWrapperManager.kt:14:110 Type mismatch: inferred type is ScreenContentWrapperManager! but BaseViewManagerInterface! was expected
node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenFooterManager.kt:14:94 Type mismatch: inferred type is ScreenFooterManager! but BaseViewManagerInterface! was expected
node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfigViewManager.kt:29:87 Type argument is not within its bounds: should be subtype of 'BaseViewManagerInterface!'
node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSubviewManager.kt:19:89 Type argument is not within its bounds: should be subtype of 'BaseViewManagerInterface!'
node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackViewManager.kt:21:63 Type argument is not within its bounds: should be subtype of 'BaseViewManagerInterface!'
node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt:34:53 Type argument is not within its bounds: should be subtype of 'BaseViewManagerInterface!'
node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarManager.kt:27:63 Type argument is not within its bounds: should be subtype of 'BaseViewManagerInterface!'

### Steps to reproduce

Setup a project with 0.77.0-rc.4
install react navigation and react native screens 
try to run the project

### Snack or a link to a repository

no link

### Screens version

4.4.0

### React Native version

0.77.0-rc.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hi @kprabath support for 0.77 will come with this PR: https://github.com/software-mansion/react-native-screens/pulls early January. You can run the lib directly from the branch: "@kkafar/support-0.77" for now on. I'll close the ticket as it is not really an issue.
