### ISSUE TITLE
Task :react-native-screens:buildCMakeDebug[arm64-v8a] FAILED

### ISSUE THREAD

**Issue by fynally** [software-mansion/react-native-screens#2592]
### Description

`Task :react-native-screens:buildCMakeDebug[arm64-v8a] FAILED`

Am always getting this error no matter the version of react-native-screen

### Steps to reproduce

**### Initialize a new project**
npx @react-native-community/cli@latest init myApp

**### Install react-native-screens**
npm install react-native-screens

**yarn android**

info Installing the app...

WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34

This Android Gradle plugin (7.4.2) was tested up to compileSdk = 33

This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=34
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 34

WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34

This Android Gradle plugin (7.4.2) was tested up to compileSdk = 33

This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=34
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 34

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build.
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions,
 even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl

The Kotlin plugin was loaded in the following projects: ':alexzunik_react-native-money-input', ':react-native-screens'

> Task :alexzunik_react-native-money-input:processDebugManifest
package="com.alexzunik.reactnativemoneyinput" found in source AndroidManifest.xml: C:\Users\xxx\n
ode_modules\@alexzunik\react-native-money-input\android\src\main\AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com
/studio/build/configure-app-module#set-namespace
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/ag
p-upgrade-assistant for more information.

> Task :alexzunik_react-native-money-input:compileDebugKotlintimeClasspathf :alexzunik_react-native-money-input:debugCompileClasspath
'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 11) jvm target compatibility
should be set to the same Java version.
Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

> Task :react-native-screens:processDebugManifest
package="com.swmansion.rnscreens" found in source AndroidManifest.xml: C:\Users\xxx\node_modules\
react-native-screens\android\src\main\AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com
/studio/build/configure-app-module#set-namespace
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/ag
p-upgrade-assistant for more information.

> Task :react-native-splash-screen:processDebugManifest
package="org.devio.rn.splashscreen" found in source AndroidManifest.xml: C:\Users\xxx\node_module
s\react-native-splash-screen\android\src\main\AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com
/studio/build/configure-app-module#set-namespace
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/ag
p-upgrade-assistant for more information.

> Task :react-native-async-storage_async-storage:processDebugManifest
package="com.reactnativecommunity.asyncstorage" found in source AndroidManifest.xml: C:\Users\xxx
\node_modules\@react-native-async-storage\async-storage\android\src\main\AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com
/studio/build/configure-app-module#set-namespace
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/ag
p-upgrade-assistant for more information.

> Task :react-native-async-storage_async-storage:compileDebugJavaWithJavac

> Task :react-native-screens:buildCMakeDebug[arm64-v8a] FAILED

> Task :react-native-screens:compileDebugKotlin
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/Screen.kt:45:77 Unchecked cast: CoordinatorLayout.Behavior<(raw) View!>? to BottomSheetBehavior<Screen>
w: file:///C:/Users/xxx/zonic_social/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenFooter.kt:252:9 Parameter 'changed' is never used
w: file:///C:/Users/Mayor/Desktop/zonics/initial/zonic_social/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenFooter.kt:253:9 Parameter 'left' is never used
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenFooter.kt:254:9 Parameter 'top' is never used
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenFooter.kt:255:9 Parameter 'right' is never used
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenFooter.kt:256:9 Parameter 'bottom' is never used
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenStackFragment.kt:257:31 'setter for targetElevation: Float' is deprecated. Deprecated in Java
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenStackFragment.kt:260:13 'setHasOptionsMenu(Boolean): Unit' is deprecated. Deprecated in Java
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenStackFragment.kt:496:22 'onPrepareOptionsMenu(Menu): Unit' is deprecated. Deprecated in Java
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenStackFragment.kt:504:22 'onCreateOptionsMenu(Menu, MenuInflater): Unit' is deprecated. Deprecated in Java
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenStackHeaderConfig.kt:100:38 'getter for systemWindowInsetTop: Int' is deprecated. Deprecated in Java
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenWindowTraits.kt:55:42 'replaceSystemWindowInsets(Int, Int, Int, Int): WindowInsetsCompat' is deprecated. Deprecated in Jav
a
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenWindowTraits.kt:56:39 'getter for systemWindowInsetLeft: Int' is deprecated. Deprecated in Java
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenWindowTraits.kt:58:39 'getter for systemWindowInsetRight: Int' is deprecated. Deprecated in Java
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/ScreenWindowTraits.kt:59:39 'getter for systemWindowInsetBottom: Int' is deprecated. Deprecated in Java
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/SearchBarManager.kt:138:66 Elvis operator (?:) always returns the left operand of non-nullable type Boolean
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/main/java/com/swmansion/rns
creens/SearchBarView.kt:153:43 Parameter 'flag' is never used
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rn
screens/FabricEnabledHeaderConfigViewGroup.kt:17:25 Parameter 'wrapper' is never used
w: file:///C:/Usersxxx/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rn
screens/FabricEnabledViewGroup.kt:10:25 Parameter 'wrapper' is never used
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rn
screens/FabricEnabledViewGroup.kt:13:9 Parameter 'width' is never used
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rn
screens/FabricEnabledViewGroup.kt:14:9 Parameter 'height' is never used
w: file:///C:/Usersxxx/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rn
screens/FabricEnabledViewGroup.kt:15:9 Parameter 'headerHeight' is never used
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rn
screens/NativeProxy.kt:7:36 Parameter 'fabricUIManager' is never used
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rn
screens/NativeProxy.kt:11:13 Parameter 'tag' is never used
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rn
screens/NativeProxy.kt:12:13 Parameter 'view' is never used
w: file:///C:/Users/xxx/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rn
screens/NativeProxy.kt:15:33 Parameter 'tag' is never used
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions
91 actionable tasks: 86 executed, 5 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about
doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This
can happen if you use versions of Android Studio and the command-line tools that were released at different times.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\xxx\node_modules\@react-native-async-storage\async-storage\android\src\javaPackage
\java\com\reactnativecommunity\asyncstorage\AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:buildCMakeDebug[arm64-v8a]'.
> Unable to delete file 'C:\Users\xxx\node_modules\react-native-screens\android\build\intermediat
es\cxx\Debug\316m3j1w\obj\arm64-v8a'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11m 25s
error Failed to install the app.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Snack or a link to a repository

no link

### Screens version

^4.4.0

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

None

### Device

Real device

### Device model

itel p40

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hello @fynally, thanks for the report.

I've read the build logs you provided and there are issues I've noticed:

1. You're using react native 0.72, which has been released ~2 years ago and we no longer test against it. Please see our readme for [information on what versions of `react-native` are supported](https://github.com/software-mansion/react-native-screens?tab=readme-ov-file#supported-react-native-version). Most likely the best way forward is to upgrade the RN version.
2. You get series of warnings regarding Android & Kotlin Gradle plugins - might be worth a shot to fix the compat / multiple installation issues in the project of yours.

I'll close the ticket, as nothing indicates to me that this is an issue with the library & the issue does not contain working reproduction. However, please tag me in case you have some more information that might be helpful (reproduction would be something to work with) & I'll open the ticket then (in case this is library issue) / I will be happy to provide you with some guidance, if possible.

**Comment by Anuragsingh013** [comment]
brother why u close this issue i,m stuck in same issue from last 5 days i,m using 
"Thanks for sharing the details. You're using:

React Native: 0.78.2

React Native CLI: 15.0.1

NDK Version: 27.1.12297006" 


here is complete error message 
'> Task \:react-native-screens\:buildCMakeDebug FAILED

\[Incubating] Problems report is available at: file:///C:/MyNewApp/android/build/reports/problems/problems-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to [https://docs.gradle.org/8.12/userguide/command\_line\_interface.html#sec\:command\_line\_warnings](https://docs.gradle.org/8.12/userguide/command_line_interface.html#sec:command_line_warnings) in the Gradle documentation.
104 actionable tasks: 94 executed, 10 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: [https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor](https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor)

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint\:deprecation for details.
Note: C:\MyNewApp\node\_modules\react-native-safe-area-context\android\src\paper\java\com\th3rdwave\safeareacontext\NativeSafeAreaContextSpec.java uses or overrides a deprecated API.
Note: Recompile with -Xlint\:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
  Execution failed for task '\:react-native-screens\:buildCMakeDebug'.

> com.android.ide.common.process.ProcessException: ninja: Entering directory \`C:\MyNewApp\node\_modules\react-native-screens\android.cxx\Debug\6y2pj6f2\arm64-v8a'
> \[1/3] Building CXX object CMakeFiles/rnscreens.dir/C\_/MyNewApp/node\_modules/react-native-screens/cpp/RNScreensTurboModule.cpp.o
> \[2/3] Building CXX object CMakeFiles/rnscreens.dir/src/main/cpp/jni-adapter.cpp.o
> \[3/3] Linking CXX shared library ........\build\intermediates\cxx\Debug\6y2pj6f2\obj\arm64-v8a\librnscreens.so
> FAILED: ../../../../build/intermediates/cxx/Debug/6y2pj6f2/obj/arm64-v8a/librnscreens.so
> cmd.exe /C "cd . && C:\Users\ANURAG~~1\AppData\Local\Android\Sdk\ndk\271~~1.122\TOOLCH~~1\llvm\prebuilt\WINDOW~~1\bin\CLANG\_\~1.EXE --target=aarch64-none-linux-android24 --sysroot="C:/Users/ANURAG SINGH/AppData/Local/Android/Sdk/ndk/27.1.12297006/toolchains/llvm/prebuilt/windows-x86\_64/sysroot" -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D\_\_BIONIC\_NO\_PAGE\_SIZE\_MACRO -D\_FORTIFY\_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -Wl,-z,max-page-size=16384 -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,librnscreens.so -o ........\build\intermediates\cxx\Debug\6y2pj6f2\obj\arm64-v8a\librnscreens.so CMakeFiles/rnscreens.dir/C\_/MyNewApp/node\_modules/react-native-screens/cpp/RNScreensTurboModule.cpp.o CMakeFiles/rnscreens.dir/src/main/cpp/jni-adapter.cpp.o  "C:/Users/ANURAG SINGH/.gradle/caches/8.12/transforms/f0cbb2cbf3730d81e18c2b2ed9b3eee6/transformed/react-android-0.78.2-debug/prefab/modules/jsi/libs/android.arm64-v8a/libjsi.so"  -landroid  -latomic -lm && cd ."
> ld.lld: error: undefined symbol: std::\_\_ndk1::\_\_shared\_weak\_count::\_\_release\_weak()
>
> > > referenced by shared\_ptr.h:184 (C:/Users/ANURAG SINGH/AppData/Local/Android/Sdk/ndk/27.1.12297006/toolchains/llvm/prebuilt/windows-x86\_64/sysroot/usr/include/c++/v1/\_\_memory/shared\_ptr.h:184) ?
" ?

**Comment by joy-mollick** [comment]
Someone will find it helpful .

When upgrading my project to React Native 0.79.2 with react-native-screens 4.10.0, I hit CMake build errors during assembleDebug / assembleRelease. This happened because react-native-screens includes Fabric (new architecture) C++ sources, but my project had newArchEnabled=false.  

🔧 The Fix

I patched the CMakeLists.txt inside
node_modules/react-native-screens/android

cmake_minimum_required(VERSION 3.9.0)

project(rnscreens)

set(RNS_NEW_ARCH_ENABLED false)

# ----------------------------
# Source files (legacy)
# ----------------------------
set(RNSCREENS_SOURCES
    ../cpp/RNScreensTurboModule.cpp
    ./src/main/cpp/jni-adapter.cpp
)

# ----------------------------
# Add shared library
# ----------------------------
add_library(rnscreens SHARED ${RNSCREENS_SOURCES})

# ----------------------------
# Include directories
# ----------------------------
include_directories(
    ../cpp
)

# ----------------------------
# Compiler options
# ----------------------------
set_target_properties(rnscreens PROPERTIES
    CXX_STANDARD 20
    CXX_STANDARD_REQUIRED ON
    CXX_EXTENSIONS OFF
    POSITION_INDEPENDENT_CODE ON
)

# ----------------------------
# Compiler definitions
# ----------------------------
target_compile_definitions(
    rnscreens
    PRIVATE
    -DFOLLY_NO_CONFIG=1
)

# ----------------------------
# Find ReactAndroid
# ----------------------------
find_package(ReactAndroid REQUIRED CONFIG)

# ----------------------------
# Link libraries
# ----------------------------
target_link_libraries(rnscreens
    ReactAndroid::jsi
    android
    c++_shared
)

My app compiled successfully with RN 0.79.2 + react-native-screens 4.10.0.
assembleRelease and bundleRelease now work fine.
The key was disabling Fabric sources when new architecture is off.

This is not ideal solution , but it will work .
