### ISSUE TITLE
Option to remove 1pt bottom border on Navbar for iOS

### ISSUE THREAD

**Issue by bartzy** [software-mansion/react-native-screens#265]
I'm looking for a way to remove the (seemingly native) 1pt border on the bottom of the Navbar on iOS:
![image](https://user-images.githubusercontent.com/167339/71769205-b75fe800-2f26-11ea-8db0-f091d42929f2.png)

Is it possible to do with the current options?

**Comment by richeterre** [comment]
@bartzy Did you ever find a solution?

I used to hide that border by passing a `headerStyle` containing `borderBottomWidth: 0`, but since upgrading to React Navigation v4 (which apparently requires react-native-screens… or does it?), that approach no longer works 😕

**Comment by WoLewicki** [comment]
https://github.com/software-mansion/react-native-screens#hideshadow should allow this now. If I am not right, feel free to comment.

**Comment by KingAmo** [comment]
this does not work for me, any help please?
