### ISSUE TITLE
Using gradient in background color?

### ISSUE THREAD

**Issue by kopax** [software-mansion/react-native-screens#267]
Hello, and sorry in advance if that's not the right place to ask.

I am discovering this library and it look promising, however, I need to have a gradient background, is that still possible using that library?

The type is not specified in the documentation https://github.com/kmagiera/react-native-screens#backgroundcolor

Thanks and best!

**Comment by WoLewicki** [comment]
If I am not wrong, now the `backgroundColor` is now explicitly a string and there is no option for a gradient there. I am closing it then. Feel free to comment if something is not clear.

**Comment by kopax** [comment]
Thanks. Yes you can close it is welcomed.  Keep doing such a good work. Dimitri
