### ISSUE TITLE
Can't use rn element inspector on modal

### ISSUE THREAD

**Issue by Hirbod** [software-mansion/react-native-screens#268]
When opening rn element inspector while a modal is open, the element inspector gets attached to the window behind. So it's not possible to inspect the modal screen.

No issues with the performance monitor though. 

![Simulator Screen Shot - iPhone 11 - 2020-01-06 at 20 45 38](https://user-images.githubusercontent.com/504909/71844175-e52f6300-30c5-11ea-9bd6-6861a90ca3eb.png)

**Comment by Hirbod** [comment]
Also, packages like https://github.com/testshallpass/react-native-dropdownalert can't display any alerts inside modals. Looks like "nothing is higher in order" then a modal. We need a fix for this :/ 

@kmagiera any thoughts?

**Comment by WoLewicki** [comment]
Does the issue still exist after #481?

**Comment by Hirbod** [comment]
No @WoLewicki, it is just partially fixed. The developer menu finally mounts on top of the modal, but the element inspector is still behind it.

**Comment by WoLewicki** [comment]
@Hirbod can you check if #614 fixes this issue and does not create any new problems?

**Comment by Hirbod** [comment]
@WoLewicki since I am using an Expo App currently, I am pretty limited in testing PRs.

**Comment by juergengunz** [comment]
@WoLewicki #614 did not fix it for me, inspector is still behind...

**Comment by WoLewicki** [comment]
@juergengunz can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by Margaridaa** [comment]
I was able to work around this type of issue by opening up the modal and only then toggle the inspector.

**Comment by RuanPissinati** [comment]
Consegui contornar o problema deixando o status do modal visible true para poder inspecionar.
