### ISSUE TITLE
iOS left slide back has obvious caton

### ISSUE THREAD

**Issue by ParryGao** [software-mansion/react-native-screens#269]
"react-native": "0.60.4",
"react-navigation": "3.5.0",
"react-native-screens": "^2.0.0-alpha.22",

Device: iPhone 8
Device Version: 12.4

**Comment by WoLewicki** [comment]
@ParryGao does the issue still exist in v. 2.4.0? If so, can you clarify what is the issue exactly?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
