### ISSUE TITLE
Custom transition with react-navigation and createNativeStackNavigator for some of the screens

### ISSUE THREAD

**Issue by bartzy** [software-mansion/react-native-screens#273]
Is it possible to create custom transitions for some of the screens while still using this library?
If not, is it possible to use createNativeStackNavigator for most of the app, but then use react-navigation without for screens that require custom transitions?

Thanks!

**Comment by r0b0t3d** [comment]
I am using `createNativeStackNavigator` and `createStackNavigator` of `react-navigation-stack` together

**Comment by bartzy** [comment]
@r0b0t3d How are you doing that for example, with 2 screens in createNativeStackNavigator, then the 3rd one should transition from the 2nd with createStackNavigator custom transition?

**Comment by r0b0t3d** [comment]
@bartzy  Here is my code.
Create stack navigator from `createSharedElementStackNavigator` and `createStackNavigator` from `react-navigation-stack`
```
import { createSharedElementStackNavigator } from 'react-navigation-shared-element';
import { createStackNavigator } from 'react-navigation-stack';

function springyFadeIn() {
  const transitionSpec = {
    timing: Animated.spring,
    tension: 15,
    useNativeDriver: true,
  };

  return {
    transitionSpec,
    screenInterpolator: ({ position, scene }) => {
      const { index } = scene;

      const opacity = position.interpolate({
        inputRange: [index - 1, index],
        outputRange: [0, 1],
      });

      return { opacity };
    },
  };
}

const ActivitySummaryNavigator = createSharedElementStackNavigator(
  createStackNavigator,
  {
    ActivitySummary: { screen: ActivitySummary },
    ImageViewer: { screen: ImageViewer },
  },
  {
    initialRouteName: 'ActivitySummary',
    headerMode: 'none',
    transitionConfig: () => springyFadeIn(),
  },
);

export default ActivitySummaryNavigator;
```
Then attach it to `createNativeStackNavigator `
```
const MainNavigator = createNativeStackNavigator(
{
    Home: {
      screen: HomeNavigator,
    },
    ActivitySummary: {
      screen: ActivitySummaryNavigator,
    },
});

export default MainNavigator;
```

**Comment by WoLewicki** [comment]
@bartzy Does it solve your issue? Can I close it then?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Comment by zilurrane** [comment]
Searching for the solution to this. 
We want to add slide from right transition to our app.

**Comment by WoLewicki** [comment]
@zilurrane currently, on Android there is no such option. You can follow #489 for more info. If you want to use custom JS-based transitions, you can use a normal `stack-navigator` along with `native-stack` ones.

**Comment by darias08** [comment]
Hello, so I am trying to use both the `createNativeStackNavigator` and `createSharedElementStackNavigator` into one function. 

If I were to use the createNativeStackNavigator that will give me the ability to have the `slide_from_right` animation which are some components I need in my app. 

Next, I want to use the `createSharedElementStackNavigator` which gives me some cool animation transitions within my app. Almost like a pop-in, pop-out type of animations. 

I just want to knowhow can use these two and essentially combine them into one function in my Stack.Navigator.

Here's a sample of what my code : 

```
function UserIsSignedIn() {
  
  const navigation = useNavigation();

  return (
<Stack.Navigator
        initialRouteName="Home"
        screenOptions={{
        headerTintColor: "white",
        headerTransparent: true,
        title: '',
        headerStyle: {backgroundColor: 'transparent'},
        }}
      >

      {/* Profile Screen */}
      <Stack.Screen 
      name="Profile" 
      component={ProfileScreen}
      options={{
      animation: 'slide_from_right',
      headerTintColor: "white",
      headerTransparent: true,
      title: '',
      headerStyle: {backgroundColor: 'transparent'},
      headerLeft: () => (
      <TouchableOpacity
        style={styles.headerBtnContainer}
        onPress={() => navigation.goBack()}>
        <Ionicons name="chevron-back" size={25} color="white" style={{paddingRight:30, paddingLeft: 30}}/>
      </TouchableOpacity>  
      ),
      }}/>

{/* Game Preview */}
      <Stack.Screen 
      name="GamePreview" 
      component={GamePreviewScreen}
      sharedElements= {(route, otherRoute, showing) => {
            const { item } = route.params;
            return [
        {
        id: `item.${item.id}.game`,
        animation: 'fade',
        resize: 'clip',
          
          },
        ];
      }}
      options={{
      headerLeft: () => (
      <TouchableOpacity
        style={styles.headerBtnContainer}
        onPress={() => navigation.goBack()}>
        <Ionicons name="chevron-back" size={25} color="white" style={{paddingRight:30, paddingLeft: 30}}/>
      </TouchableOpacity>  
      ),
      }}/>

</Stack.Navigator>
  
  )
}

export default UserIsSignedIn;

```
