### ISSUE TITLE
going back to Tab crashes the app

### ISSUE THREAD

**Issue by SmirnovM91** [software-mansion/react-native-screens#274]
After changing tabs 
![image](https://user-images.githubusercontent.com/32675072/72094454-aeb14c80-3340-11ea-88a3-3c3d25eb3793.png)

i have header =  null
![image](https://user-images.githubusercontent.com/32675072/72094537-d86a7380-3340-11ea-8696-caade77eb8b9.png)

**Comment by WoLewicki** [comment]
@SmirnovM91 does the issue still exist in v. 2.4.0?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
