### ISSUE TITLE
[Android]Can't access developer menu on physical device

### ISSUE THREAD

**Issue by afishhhhh** [software-mansion/react-native-screens#276]
Using `enableScreens` and `createNativeStackNavigator` in `App.js`:
```
import { enableScreens } from 'react-native-screens'
import createNativeStackNavigator from 'react-native-screens/createNativeStackNavigator'

enableScreens()
const AppNavigator = createNativeStackNavigator({
  Login
})
```
I can't access developer menu. But when I replace `createNativeStackNavigator` with `createStackNavigator`, I can access developer menu.

`react-native-screens` version: 2.0.0-alpha.22

**Comment by winkelsdorf** [comment]
Same here with `2.0.0-alpha.29` on Android emulator (Pixel 3, API 29). RN is `0.61.5`.

**Comment by WoLewicki** [comment]
Does the issue still exist in v 2.4.0 @winkelsdorf @afishhhhh ?

**Comment by afishhhhh** [comment]
I didn't notice. Now I can press "d" on the Terminal to access developer menu. @WoLewicki 
`react-native` v 0.61.5
`react-native-screens` v 2.3.0
`react-navigation` v 5.x

**Comment by winkelsdorf** [comment]
@WoLewicki Yes, still exists with v2.4.0. RN still on v0.61.5 and react-navigation still on v4.3.6. I'm encountering other issues as well, `createNativeStackNavigator()` does not respect `headerTitleStyle`.

I'm going to re-investigate as soon as customer decides to upgrade to newer react-navigation branch.

**Comment by WoLewicki** [comment]
Ok, it would be great if you could provide a reproduction with a minimal needed configuration for easier debugging. Could you do it?

**Comment by winkelsdorf** [comment]
@WoLewicki Tbh, sadly this is out of the time scope for me :/ I'm a native iOS Developer and the side project using this has currently no budget at all, not even for RN 0.62 or `react-navigation` migration :( When I try to use this component with `enableScreens()` I start having disappearing views on Android, debugging this and creating a minimal reproducing demo would mean some 3-5 unpaid hours and (what matters most) time which I must take from a paid project. So best ignore my report, as I am unable to give feedback shortly.

Probably @afishhhhh can jump in?

**Comment by WoLewicki** [comment]
Can you check if #602 resolves your issue?
