### ISSUE TITLE
Memory increases when I navigate between screens

### ISSUE THREAD

**Issue by billypap1** [software-mansion/react-native-screens#295]
I use React-Navigation v4 (Stack Navigator) with react-native-screens v2.0.0-alpha.6 and I have noticed a memory increase when I navigate between screens.

For example, if I populate a list with Items and navigate to an Item Page memory adds up 5mb. Even If I go back, memory is not released. Is this a bug? Can I remove same screen names from stack?

Memory Results Here -> [Memory Results](https://i.stack.imgur.com/nHTSS.png)

**Comment by WoLewicki** [comment]
@billypap1 is it still the case with the newest version?

**Comment by WoLewicki** [comment]
Closing due to no reply for more than 30 days. Feel free to comment here to reopen.
