### ISSUE TITLE
App crash when updating from alpha.29 to alpha.31

### ISSUE THREAD

**Issue by diego-better-half** [software-mansion/react-native-screens#301]
The app has started crashing with the error `Can't find variable gestureEnabled` after updating to alpha 31.

```
    react: ^16.11.0 => 16.12.0 
    react-native: ^0.62.0-rc.1 => 0.62.0-rc.1
```

![Simulator Screen Shot - iPhone 11 - 2020-01-27 at 20 32 01](https://user-images.githubusercontent.com/55058765/73211449-2c989480-4144-11ea-9e35-bdc82636bc63.png)

Might be related to this change
https://github.com/kmagiera/react-native-screens/commit/d32463ee83a098267315b7451defb6b4f95a8741

**Comment by WoLewicki** [comment]
It was related to the breaking change in Android, as you mentioned correctly. I am closing this then. Feel free to comment if you have any more questions.
