### ISSUE TITLE
Upgrade from 2.0.0-beta.1 to 2.0.0-beta.2 break web application

### ISSUE THREAD

**Issue by kopax** [software-mansion/react-native-screens#311]
I have tried to upgrade `react-native-screens` in my app with:
```diff
-    "react-native-screens": "2.0.0-beta-1",
+    "react-native-screens": "2.0.0-beta.2",
```

Looking at my console: `Uncaught SyntaxError: Invalid left-hand side in assignment`

It work fine on native apps.

**Comment by WoLewicki** [comment]
Does the issue persist in the newest version or can I close it @kopax ?

**Comment by kopax** [comment]
We can close it. Thanks so much for asking prior closing it, this is really really really the good way to deal with issue and it is much appreciated, you got all the kudos on hearth for that.
