### ISSUE TITLE
Using custom font in navigation header?

### ISSUE THREAD

**Issue by beaur** [software-mansion/react-native-screens#319]
I'm using expo and have loaded a custom font using the expo-font package https://docs.expo.io/versions/v36.0.0/sdk/font/.  I am also using the new react-navigation 5 library and the Native Stack Navigator which uses react-native-screens.

I want to use this custom font in my navigation header however is seems setting `titleFontFamily` to this custom loaded font is not working.  I can set the font family successfully to any of the UIFont font families (https://github.com/lionhylra/iOS-UIFont-Names) but not my custom loaded font.  Is this a known limitation or should this be working?

**Comment by WoLewicki** [comment]
It seems like a duplicate of #371 . I am closing it then, please inform me if it is not the same issue.

**Comment by beaur** [comment]
Yes this seems to have been since duplicated.  I will continue monitoring #371 .
