### ISSUE TITLE
`headerBackTitleStyle` only applies when `headerBackTitle` is set

### ISSUE THREAD

**Issue by iDuuck** [software-mansion/react-native-screens#321]
I am not able to style the `headerBackTitle` without setting it explicitly (i.e. inherited from the parent screen).

The problem lies in this method/line: https://github.com/kmagiera/react-native-screens/blob/f78c26441970f942f8c57a391c1ec5eb25a70cdc/ios/RNSScreenStackHeaderConfig.m#L280

**Comment by WoLewicki** [comment]
@iDuuck can you check if applying #458 solves your issue?

**Comment by iDuuck** [comment]
Will check once back on this project. Currently only working on projects with a bare workflow, where it is working flawlessly as usual.
