### ISSUE TITLE
ScreenStackHeaderConfig sometimes renders subviews incorrectly on iPad

### ISSUE THREAD

**Issue by matt-oakes** [software-mansion/react-native-screens#322]
`ScreenStackHeaderConfig` will sometimes render it's subviews in the wrong position on iPad.

From the "Native stack example" in the `Examples` project, this is the correct rendering:

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-02-11 at 10 50 03](https://user-images.githubusercontent.com/97068/74230474-5a411a00-4cbc-11ea-93d5-d9275fdc8161.png)

This is the rendering with the bug:

![Simulator Screen Shot - iPad Pro (11-inch) - 2020-02-11 at 10 47 58](https://user-images.githubusercontent.com/97068/74230486-60cf9180-4cbc-11ea-8092-bb797aba2f83.png)

## Steps to reproduce

1. Open the example app in this repo in Xcode and enable "iPad" support in the project settings.
2. Run the app on the iPad and open the "Native stack example".
3. The bug only seems to happen ~25% of the time, so rerun the example until you see it.

## Causes

I have traced it through and the bug happens when the [`+ (void)updateViewController:(UIViewController *)vc withConfig:(RNSScreenStackHeaderConfig *)config`](https://github.com/kmagiera/react-native-screens/blob/ed997ef4ecd4cc99383386cb016bc8d79bf70279/ios/RNSScreenStackHeaderConfig.m#L249) method is called twice.

When it is only called once these are the methods which are called:

1. [`- (void)navigationController:(UINavigationController *)navigationController willShowViewController:(UIViewController *)viewController animated:(BOOL)animated`](https://github.com/kmagiera/react-native-screens/blob/ed997ef4ecd4cc99383386cb016bc8d79bf70279/ios/RNSScreenStack.m#L51)
2. [`+ (void)willShowViewController:(UIViewController *)vc withConfig:(RNSScreenStackHeaderConfig *)config`](https://github.com/kmagiera/react-native-screens/blob/ed997ef4ecd4cc99383386cb016bc8d79bf70279/ios/RNSScreenStackHeaderConfig.m#L244)
3. [`+ (void)updateViewController:(UIViewController *)vc withConfig:(RNSScreenStackHeaderConfig *)config`](https://github.com/kmagiera/react-native-screens/blob/ed997ef4ecd4cc99383386cb016bc8d79bf70279/ios/RNSScreenStackHeaderConfig.m#L249)

When it is called twice, and the bug appears, these are the methods which are called:

* First call
  1. [`- (void)didUpdateReactSubviews`](https://github.com/kmagiera/react-native-screens/blob/ed997ef4ecd4cc99383386cb016bc8d79bf70279/ios/RNSScreenStackHeaderConfig.m#L110).
  2. [`- (void)updateViewControllerIfNeeded`](https://github.com/kmagiera/react-native-screens/blob/ed997ef4ecd4cc99383386cb016bc8d79bf70279/ios/RNSScreenStackHeaderConfig.m#L86)
  3. [`+ (void)updateViewController:(UIViewController *)vc withConfig:(RNSScreenStackHeaderConfig *)config`](https://github.com/kmagiera/react-native-screens/blob/ed997ef4ecd4cc99383386cb016bc8d79bf70279/ios/RNSScreenStackHeaderConfig.m#L249)
* Second call
  1. [`- (void)navigationController:(UINavigationController *)navigationController willShowViewController:(UIViewController *)viewController animated:(BOOL)animated`](https://github.com/kmagiera/react-native-screens/blob/ed997ef4ecd4cc99383386cb016bc8d79bf70279/ios/RNSScreenStack.m#L51)
  2. [`+ (void)willShowViewController:(UIViewController *)vc withConfig:(RNSScreenStackHeaderConfig *)config`](https://github.com/kmagiera/react-native-screens/blob/ed997ef4ecd4cc99383386cb016bc8d79bf70279/ios/RNSScreenStackHeaderConfig.m#L244)
  3. [`+ (void)updateViewController:(UIViewController *)vc withConfig:(RNSScreenStackHeaderConfig *)config`](https://github.com/kmagiera/react-native-screens/blob/ed997ef4ecd4cc99383386cb016bc8d79bf70279/ios/RNSScreenStackHeaderConfig.m#L249)

Commenting out [this line](https://github.com/kmagiera/react-native-screens/blob/ed997ef4ecd4cc99383386cb016bc8d79bf70279/ios/RNSScreenStackHeaderConfig.m#L100) fixes the issues, but don't really solve it.

## Proposed solution

We should be able to fix this by keeping track of the config which has been applied to the navigation item and only setting it again if something has changed. This would fix it, but wouldn't actually solve the root cause of this bug. It could be that we need to "reset" some other state to make everything work as expected.

**Comment by matt-oakes** [comment]
This seems to be related to this iOS 13 issue:

https://forums.developer.apple.com/thread/121861

I have tried implementing the workaround, but it doesn't seem to fix it.

I have had success with re-setting the `screenView` of the `RNSScreenStackHeaderConfig` view a short delay after the `viewWillAppear` method is called on `RNScreen, however, this falls deeply into the "dirty hack" category:

```objectivec
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    
    double delayInSeconds = 0.1;
    dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, (int64_t)(delayInSeconds * NSEC_PER_SEC));
    dispatch_after(popTime, dispatch_get_main_queue(), ^(void){
        [self.view.reactSubviews enumerateObjectsUsingBlock:^(UIView * _Nonnull view, NSUInteger idx, BOOL * _Nonnull stop) {
            if ([view isKindOfClass:[RNSScreenStackHeaderConfig class]]) {
                ((RNSScreenStackHeaderConfig*) view).screenView = ((RNSScreenView *)self.view)    ;
            }
        }];
    });
}
```

Note, that this workaround require you to add this method to `RNSScreenStackHeaderConfig` so we recall the setup method when the `screenView` is set. In my opinion, this should be happening anyway as the config depends on the `screenView` and currently there could be timing bugs if the `screenView` is set after the view controller will appear method is called:

```objectivec
- (void)setScreenView:(RNSScreenView *)screenView
{
  _screenView = screenView;
  [self updateViewControllerIfNeeded];
}
```

I don't feel happy enough that this is a good solution to submit a PR, but hopefully the workaround is useful for people who have the issue right now.

**Comment by WoLewicki** [comment]
@osdnk

**Comment by immortalx** [comment]
@matt-oakes which files do i need to modify to implement this workaround?

**Comment by immortalx** [comment]
@matt-oakes I don't know where in RNSScreenStackHeaderConfig i should apply this workaround. Can you share the whole file or tell me where to add those lines? 
Thank you

**Comment by 509dave16** [comment]
@immortalx The RNSScreenStackHeaderConfig is a `UIViewController` I think. Considering that the `viewWillAppear` is an instance method of it: https://developer.apple.com/documentation/uikit/uiviewcontroller/1621510-viewwillappear

Currently in RNSScreenStackHeaderConfig, `viewWillAppear` has not been defined. So there isn't an existing declaration of it to be modified. I just needs to be added. I don't believe there's a particular ordering that has to be followed for declared instance methods. So as long as `viewWillAppear` declared with all the rest of the instance methods you should be good I think.

**Comment by FrankFundel** [comment]
Anywhere in RNSScreenStackHeaderConfig.m I want to palce the workaround code an error gets thrown. How can this still be an Issue?

**Comment by WoLewicki** [comment]
I will close it to keep the discussion about the issue in one place. Please see #432 for more information.
