### ISSUE TITLE
stackAnimation set to fade or none ignores navigation bar

### ISSUE THREAD

**Issue by dmarkow** [software-mansion/react-native-screens#326]
Normally when pushing a screen, the view respects the navigation bar. However, when you set a screen to use `stackAnimation: "fade"` (or "none"), the pushed view gets partially hidden behind the header.

Using the Example app's "Native Stack Bindings for RNN", I set the pushed screen to use a fade animation:

```
# nativeNavigation.js

...

Push: {
      screen: PushScreen,
      navigationOptions: {
        title: 'Pushed',
        stackAnimation: "fade",

...
```

The animation does fade now instead of sliding in, however, the pushed screen's upper left red square is completely hidden behind the navigation, and stays hidden as you "push more". However, when you tap "go back" the view correctly shows the red square:

![screencast 2020-02-12 10-43-22](https://user-images.githubusercontent.com/8009/74356820-9a6bcf80-4d84-11ea-99d6-90b618d8f28f.gif)

Here it is working correctly with the default animation:

![screencast 2020-02-12 10-41-18](https://user-images.githubusercontent.com/8009/74356861-a9528200-4d84-11ea-86b8-5627968bc0f0.gif)

**Comment by WoLewicki** [comment]
@dmarkow can you check if #527 fixes your issue?

**Comment by dmarkow** [comment]
@WoLewicki Yes, it does!
