### ISSUE TITLE
iOS - React/RCTImageLoader.h file not found on RN 0.61.5

### ISSUE THREAD

**Issue by allthetime** [software-mansion/react-native-screens#328]
error from xcode:

```
....../node_modules/react-native-screens/ios/RNSScreenStackHeaderConfig.m:8:9: 

'React/RCTImageLoader.h' file not found
```

I just upgraded RN and now I am getting this error.

Reverting to 0.60.0 fixes the issue.

**Comment by morteify** [comment]
Duplicate of #281

**Comment by kmagiera** [comment]
Thanks for linking @morteify – I'm going to close this one as there are some resolution suggestions in #281 alrleady.
