### ISSUE TITLE
App crashes while navigating after adding react-native-screens on API 22 Android

### ISSUE THREAD

**Issue by pdSatyam** [software-mansion/react-native-screens#329]
Package Info:
```
{
  "name": "Papyrus_60",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/google-signin": "^3.0.4",
    "@react-native-community/slider": "^2.0.8",
    "@react-native-firebase/app": "^6.0.1",
    "@react-native-firebase/auth": "^6.0.1",
    "@react-native-firebase/firestore": "^6.0.1",
    "faker": "^4.1.0",
    "formik": "^1.5.8",
    "hex-to-rgba": "^1.0.2",
    "moment": "^2.24.0",
    "native-base": "^2.10.0",
    "react": "^16.9",
    "react-moment": "^0.9.6",
    "react-native": "^0.61.5",
    "react-native-circular-progress": "^1.3.3",
    "react-native-fbsdk": "^1.0.4",
    "react-native-fontawesome": "^5.7.0",
    "react-native-gesture-handler": "^1.4.0",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-modal": "^7.0.2",
    "react-native-modalbox": "^1.6.0",
    "react-native-parallax-header": "^1.1.3",
    "react-native-react-native-recorder": "file:react-native-react-native-recorder",
    "react-native-reanimated": "^1.3.0",
    "react-native-screens": "^2.0.0-beta.1",
    "react-native-simple-toast": "^0.1.1",
    "react-native-slider": "^0.11.0",
    "react-native-svg": "^9.13.2",
    "react-native-tag-select": "^2.0.0",
    "react-native-track-player": "^2.0.0-rc13",
    "react-native-vector-icons": "^6.0.2",
    "react-native-video": "^5.0.2",
    "react-navigation": "^4.0.0",
    "react-navigation-backhandler": "^1.4.0",
    "react-navigation-drawer": "^2.3.3",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.2",
    "react-redux": "^7.1.0",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "yup": "^0.27.0"
  },
  "devDependencies": {
    "@babel/core": "7.5.5",
    "@babel/runtime": "7.5.5",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.8.0",
    "eslint": "6.1.0",
    "jest": "24.8.0",
    "jetifier": "^1.6.4",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

1. App is working fine on API 28, crashing when it starts navigating on API 22.
This started because I was using react-navigation: ^4.0.0 and 'react-native-screens' became a dependency of react-navigation.
2. No error in packager.
3. Error in device logs. 

<img width="1396" alt="Screenshot 2020-02-14 at 11 26 57 AM" src="https://user-images.githubusercontent.com/13198518/74505362-f49f9880-4f1c-11ea-8e74-1650aeb7cca9.png">

Changelogs:

https://github.com/react-navigation/react-navigation/blob/v4.0.0/yarn.lock (react-native-screens : 
 react-native-screens "^1.0.0 || ^1.0.0-alpha") 
https://github.com/react-navigation/react-navigation/blob/%40react-navigation/stack%405.0.3/yarn.lock .  (react-native-screens-2.0.0-beta.2)

React-native Info:

System:
    OS: macOS Mojave 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 35.30 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 25.0.0, 27.0.0, 27.0.3, 28.0.0, 28.0.3, 29.0.1
      System Images: android-22 | ARM EABI v7a, android-22 | Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.0.4 => 3.0.4 
    react: ^16.9 => 16.12.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by jimkhan** [comment]
i aslo same problem. Did you solve it? or get any solution?? @pdSatyam

**Comment by WoLewicki** [comment]
Does the issue still exist? And if so, can you provide a repo with minimal configuration where this happens?

**Comment by jimkhan** [comment]
for me it was Graphics Card problem. @WoLewicki

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
