### ISSUE TITLE
[Android] Header does not have left and right padding on Android

### ISSUE THREAD

**Issue by sallar** [software-mansion/react-native-screens#332]
Hi. 

I'm using `@react-navigation/native-stack` in my app, and I have an issue with Header on Android. When the header doesn't show back button, the title is stuck to the left side of the screen without any padding. 

The header right can be solved with CSS, but I couldn't find a way to do the same with title on Android.

![2020-02-15 17 25 57](https://user-images.githubusercontent.com/768052/74590576-51cc4480-5018-11ea-8686-fd568661a0db.jpg)

Thank you

**Comment by kmagiera** [comment]
Hey, unfortunately native toolbar on Android does not apply a padding automatically in a way iOS navbar does. I haven't yet decided how do we want to go about handling this to provide better consistency. Thanks for reporting, I'll keep this open for now and check back soon when we have more time to address consistency issues.

Before that happens you should be able to add an empty view as left item to the navbar and offset the title this way.

**Comment by sallar** [comment]
@kmagiera thank you. I couldn’t find a way to add an empty view to the left sidebar though. I’m using React navigation in my project and I went through all the options. Maybe I have missed something?

**Comment by kddc** [comment]
@sallar Yes, pretty sure it's related to this PR - https://github.com/software-mansion/react-native-screens/pull/289/files

**Comment by sallar** [comment]
yes @kddc good find. that's it.

**Comment by kddc** [comment]
Hey @NekoMobileStudio, awesome that you tackled that issue - if i may make a suggestion, i would suggest to maybe make it more like a boolean parameter, which toggles if you want to use the default inset behaviour (which was used before the commit i linked) and the one with the inset 0. 
But i have no idea about, why this was changed in the first place, and im sure there are good reasons for it.

**Comment by sallar** [comment]
@kmagiera any chance we could have a review on this PR?

**Comment by kmagiera** [comment]
Ended up coming with an alternative approach for this. I'd like to avoid adding too many settings to header (like it was done in #350). My approach is not as flexible but brings consistency between Android and iOS. In the future we can give option to remove default paddings (on both Android and iOS) and this way allow the user to specify margin in JS starting from the edge of the navigation bar.

**Comment by kmagiera** [comment]
@sallar I'm not going to merge #396 just yet, do you mind checking if it provides a solution to your usecase?

**Comment by sallar** [comment]
Thanks @kmagiera I’m going to test this as soon as possible. Is it out in a beta?

**Comment by taismassaro** [comment]
hi @kmagiera 
I've read the release commit list for version `2.2.0` and it says this fix should already be there, but that's the version I'm using and I'm still having this inconsistency between Android and iOS.

I'm using `react-native-screens/native-stack` for the Stack and `@react-navigation/native` hooks to show the header on screens I want `skip` or `back` buttons:

```js
if (backButton || skipAction) {
      navigation.setOptions({
        title: '',
        headerShown: true,
        headerHideBackButton: !backButton,
        headerHideShadow: true,
        headerBackTitleVisible: false,
        headerRight: showSkipButton,
        contentStyle: [t.bgWhite],
        headerStyle: { backgroundColor: t.textWhite.color },
        headerTintColor: t.textBlack.color,
      });
    }
```

![Screenshot_1583399773](https://user-images.githubusercontent.com/16339834/75967307-e7e2e480-5ecb-11ea-8072-83d817c38b9e.png)
---
![Simulator Screen Shot - iPhone 11 - 2020-03-05 at 10 26 22](https://user-images.githubusercontent.com/16339834/75967313-e9141180-5ecb-11ea-9c8c-341b18f9ed4a.png)


maybe my approach isn't correct? can you give me some insight on this? 😬 

thanks!
