### ISSUE TITLE
Why is `containedModal` not exported?

### ISSUE THREAD

**Issue by pvinis** [software-mansion/react-native-screens#334]
Why is that `stackPresentation` not exported/exposed? The `index.d.ts` doesn't  have it, yet when I use it in a project it works great.

**Comment by kmagiera** [comment]
I think this is just an oversight as we only check TS definition file every once in a while. Happy to accept a PR for the definition file that'd add that.

**Comment by pvinis** [comment]
Started it on https://github.com/software-mansion/react-native-screens/pull/355

**Comment by Hirbod** [comment]
@pvinis you need help on this?

**Comment by pvinis** [comment]
I don't have time to continue this unfortunately :(. Feel free to take over that PR.

**Comment by WoLewicki** [comment]
I see that no one has currently time to update the PR and make it compatible with the newest changes to the structure, so I made it: #551. 
Thanks for your contribution @pvinis!
