### ISSUE TITLE
[Android] com.bumptech.glide.manager.SupportRequestManagerFragment cannot be cast to com.swmansion.rnscreens.ScreenFragment

### ISSUE THREAD

**Issue by ctopher7** [software-mansion/react-native-screens#339]
version 2.0.0 beta 6

**Comment by dynbit** [comment]
In ours use this exception comes from https://github.com/DylanVann/react-native-fast-image,
as it is using view-less fragments. 

> A view-less Fragment used to safely store an RequestManager that can be used to start, stop and manage Glide requests started for targets within the fragment or activity this fragment is a child of.
Ref: https://bumptech.github.io/glide/javadocs/380/com/bumptech/glide/manager/SupportRequestManagerFragment.html

**Comment by msantang78** [comment]
Yeah, we have the same error and we are using react-native-fast-image
I even tried with version 8.0.0 (not available on NPM not sure why) but the error persists.

**Comment by alimek** [comment]
I guess could be closed via #344

**Comment by kmagiera** [comment]
closing this as we already have a fix in and 2.0.0-beta.8 has been published that includes the fix.

**Comment by ctopher7** [comment]
@kmagiera thank you!
