### ISSUE TITLE
Method `useScreens` is deprecated, please use `enableScreens`

### ISSUE THREAD

**Issue by R4meau** [software-mansion/react-native-screens#346]
I'm on Expo and when I use `useScreens`, I get the above error.

Although, the `README` on here is saying to use `useScreens` when using Expo and `enableScreens` when not.

I went ahead and used `enableScreens` and it's all working fine. This is just to make sure that the README is simply outdated.

**Comment by kmagiera** [comment]
`enableScreens` is just an alias for `useScreens`. They do the same thing, but we encourage to use `enabledScreens` as `useScreens` is detected as being a react hook (which is not) by some react tooling. Do you mind updating the docs, I'd be happy to merge such change to clarify that.
