### ISSUE TITLE
[native-stack] If present native alert for iOS that time not navigate new screen in react-navigation 5 using createNativeStackNavigator

### ISSUE THREAD

**Issue by satya164** [software-mansion/react-native-screens#357]
_Moved from [react-navigation/react-navigation#6852](https://github.com/react-navigation/react-navigation/issues/6852). Originally opened by @singheshadev_
___

**Current Behavior**

- Not redirect new screen.

**Expected Behavior**

- Navigate new screen

**How to reproduce**

- Open A screen
- Present native alert view 
- Execute to navigate second screen code (Using createNativeStackNavigator)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                |
| @react-navigation/native       |
| react-native                   |

**Comment by WoLewicki** [comment]
@singheshadev can you provide a repro with a minimal configuration that shows the bug? Because I cannot understand what you mean by the native alert view.

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
