### ISSUE TITLE
[native-stack] Can't toggle element inspector on modal window

### ISSUE THREAD

**Issue by satya164** [software-mansion/react-native-screens#367]
_Moved from [react-navigation/react-navigation#6766](https://github.com/react-navigation/react-navigation/issues/6766). Originally opened by @Hirbod_
___

When opening rn element inspector while a modal is open, the element inspector gets attached to the window behind. So it's not possible to inspect the modal screen.

No issues with the performance monitor though. This might be even an upstream issue with react-native itself. Or do you think it can be handled by react-native-screens? Not sure where this belongs to.

![Simulator Screen Shot - iPhone 11 - 2020-01-06 at 20 45 38](https://user-images.githubusercontent.com/504909/71844175-e52f6300-30c5-11ea-9bd6-6861a90ca3eb.png)

**Comment by WoLewicki** [comment]
Looks like it is the same issue you already opened in this library #268, so I am closing it here. Feel free to comment here if I am not right.
