### ISSUE TITLE
[native-stack] headerLargeTitle exposes white background on navigation

### ISSUE THREAD

**Issue by satya164** [software-mansion/react-native-screens#370]
_Moved from [react-navigation/react-navigation#6751](https://github.com/react-navigation/react-navigation/issues/6751). Originally opened by @evanheckert_
___

**Current Behavior**

![demo-gif](https://user-images.githubusercontent.com/5625859/73494562-55a26a80-437a-11ea-904d-38376df88771.gif)

Gif was recorded with slow animations enabled in the iOS simulator (ios 13.3). Symptoms are the same when running on iPhone 11 Pro Max through expo client.

**Expected Behavior**
I would expect either the headerStyle or contentStyle backgroundColor to be the background color throughout the transition.  

**How to reproduce**
Repro: https://github.com/evanheckert/header-example

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 13.3 and 13.3.1
| @react-navigation/native       | 5.0.0-alpha.29
| @react-navigation/native-stack | 5.0.0-alpha.29
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | latest expo fork, sdk-36.0.1
| expo                           | 36.0.2
| node                           | 10.17.0
| npm or yarn                    | yarn v1.21.1

**Comment by WoLewicki** [comment]
Looks like the issue has been resolved in the previous thread. Feel free to comment it would be needed to be reopened.
