### ISSUE TITLE
[native-stack] `headerLargeTitleStyle` isn't accepting any Expo fonts

### ISSUE THREAD

**Issue by satya164** [software-mansion/react-native-screens#371]
_Moved from [react-navigation/react-navigation#6750](https://github.com/react-navigation/react-navigation/issues/6750). Originally opened by @iDuuck_
___

**Current Behavior**

When I am trying to include a custom font into Expo, I am not able to use it using the native stack navigators `fontFamily` attributes. It keeps the SF Font.

**Expected Behavior**

I want the font to be the right one actually.

**How to reproduce**

Implement a custom font into an Expo project and try to use the font for any of the title styles.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | next
| @react-navigation/native-stack | ^5.0.0-alpha.29
| react-native-screens           | ^5.0.0-alpha.29
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz
| expo                           | 36
| node                           | v12.8.0
| npm or yarn                    | 1.19.2

**Comment by Derewith** [comment]
No news?

**Comment by iDuuck** [comment]
It super sad. Because `react-navigation` was one of my go to projects for React-Native.

**Comment by Hirbod** [comment]
@iDuuck but this is a native stack issue, not related directly to react navigation

**Comment by iDuuck** [comment]
Native-stack belonged to react-navigation before this issue was moved. Now it seems a little abandoned. No documentation and no Changelog or so.

**Comment by artyfy-tech-kjetil** [comment]
Any news on this?

**Comment by WoLewicki** [comment]
I made a PR: #442. Can you check if it resolves the issue?

**Comment by WoLewicki** [comment]
I am closing this issue. Feel free to comment if the issue still persist after #442.
