### ISSUE TITLE
QUESTION: How can I benefit from this library?

### ISSUE THREAD

**Issue by OmarBasem** [software-mansion/react-native-screens#375]
I use react-navigation for handling navigation. How can I benefit from this library? What can this library do that I cannot do with react-navigation alone?
Thanks!

**Comment by punisher97** [comment]
Native view controllers increase UX and smooth animations, your can check this in JS and UI fps with perf monitor

**Comment by OmarBasem** [comment]
@punisher97 so react-navigation does not have native view controllers?
Thanks for your reply!

**Comment by punisher97** [comment]
> @punisher97 so react-navigation does not have native view controllers?
> Thanks for your reply!

Not, it this is objective of react-native-screens
more info:
https://reactnavigation.org/docs/react-native-screens/

**Comment by OmarBasem** [comment]
@punisher97 Thank you so much!
