### ISSUE TITLE
White flash when using DarkTheme

### ISSUE THREAD

**Issue by dogukny** [software-mansion/react-native-screens#380]
When DarkTheme is activated white flash appears while moving to the other page. Its not appear in DefaultTheme.

```
<Button
          title={'route'}
          onPress={() => {
            this.props.navigation.navigate('Add');
          }}
        />
```

```
    <NavigationContainer theme={DarkTheme}>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Add" component={Add} />
      </Stack.Navigator>
    </NavigationContainer>
```

<img src="https://user-images.githubusercontent.com/35095902/75197735-0597a780-5770-11ea-85c0-816c053bcd79.gif" width="270" height="480">

**Comment by enheit** [comment]
I have the same issue on Android (v9)

**Comment by punisher97** [comment]
I was think same your, but the white flash must be the root view container, in my case always was white, because, simply check color schema and change your backgroundColor root wrapper.

```jsx
const colorScheme = useColorScheme();

return  <View style={[styles.container, { backgroundColor: colorScheme === 'dark' ? 'black' : '#F5FCFF' }]}>
      {children}
      {bootSplashIsVisible && (
        <Animated.View style={[StyleSheet.absoluteFill, styles.bootsplash, { opacity: opacity.current }]}>
          <Animated.View style={{ transform: [{ translateY: translateY.current }] }}>
            <FastImage
              source={images.logo}
              onLoadEnd={() => {
                console.log('[AppLoading] hide boot splash');
                BootSplash.hide();
                !initialized && setBootSplashLogoIsLoaded(true);
              }}
              style={styles.logo}
            />
            <ActivityIndicator size="large" color={Colors.blueGrey800} />
          </Animated.View>
        </Animated.View>
      )}
    </View>

```

**Comment by WoLewicki** [comment]
@dogukny @enheit does @punisher97 's solution fix your issue?

**Comment by enheit** [comment]
@WoLewicki  I have not checked yet... I will try ASAP

**Comment by kmagiera** [comment]
I believe the white flash comes from some container view having a white (or default background). Possibly the app container you render need to be styled properly

**Comment by punisher97** [comment]
@kmagiera it's correct i use react-navigation and setting backgroundColor(#000) in previous viewContainer, in my case  a stack 

```typescript
const Stack = createStackNavigator();

const RootNavigator = () => {
  const theme = useTheme();
  const isAuthenticated = useSelector(isAuthenticatedSelector);
  const navigationTheme = theme.dark ? DarkTheme : DefaultTheme;
  const screenOptions: StackNavigationOptions = {
    headerTintColor: '#fff',
    cardStyle: { backgroundColor: '#000' },
    headerShown: false,
  };

  return (
    <NavigationContainer theme={navigationTheme}>
      <Stack.Navigator screenOptions={screenOptions}>
        {!isAuthenticated ? (
          <Stack.Screen
            name="Auth"
            component={AuthNavigator}
            options={{ headerShown: false, animationTypeForReplace: isAuthenticated ? 'push' : 'pop' }}
          />
        ) : (
          <Stack.Screen name="Home" component={HomeScreen} options={{}} />
        )}
      </Stack.Navigator>
    </NavigationContainer>
  );
};
```

**Comment by dogukny** [comment]
> @dogukny @enheit does @punisher97 's solution fix your issue?

Still appears. I changed root view's background to black already and tried with useTheme but not didn't fix.

```

function HomeScreen(props) {
  const {colors} = useTheme();

  return (
    <View
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.background, // or #000000
      }}>

**Comment by punisher97** [comment]
@dogukny an screen its not a root view container, must be in the top, the first View or Navigator

**Comment by WoLewicki** [comment]
Did you manage to fix the issue with these solutions @dogukny?

**Comment by codecog** [comment]
The `contentStyle` of `<Stack.Screen>`, `backgroundColour` of `<NavigationContainer />` `theme` prop, `rootView.backgroundColour` in `AppDelegate.m` for iOS & `windowBackground` in `styles.xml` for Android all need to be set.

**Comment by dogukny** [comment]
> Did you manage to fix the issue with these solutions @dogukny?

I did punisher97's solution for first view but didn't change. It's not about just black color or darktheme, other colors effect too.

**Comment by WoLewicki** [comment]
I believe it is the same issue as #111, so I will close this issue to keep the discussion about it in 1 place only. Feel free to comment if I am wrong.

**Comment by ubaidmoin** [comment]
> The `contentStyle` of `<Stack.Screen>`, `backgroundColour` of `<NavigationContainer />` `theme` prop, `rootView.backgroundColour` in `AppDelegate.m` for iOS & `windowBackground` in `styles.xml` for Android all need to be set.

I resolved the issue by following @dogukny instructions.
In NavigationContainer add:
`theme={ colors: { background: '#000' }}`
It stopped the white flickering as i set it to black.

**Comment by frknnay** [comment]
`detachInactiveScreens={false}` also  fixed the issue for me.
example:
`<MainStack.Navigator
      detachInactiveScreens={false}
    >
     ...
 </MainStack.Navigator>`

**Comment by iqqmuT** [comment]
@frknnay For me it was `screenOptions={{ animationEnabled: false }}` (which you also have) that fixed the issue.

**Comment by luizwhite** [comment]
It is a good practice to defined all props like [this](https://reactnavigation.org/docs/themes#basic-usage).
So, to resolve my issue i did
```jsx
...
import { NavigationContainer, DefaultTheme } from '@react-navigation/native';
...

const App: React.FC = () => (
  <NavigationContainer
    theme={{
      dark: true,
      colors: {
        ...DefaultTheme.colors,
        background: '#mycolor',
        card: '#mycolor',
      },
    }}
  >
  ...
...
```

**Comment by a-Marino** [comment]
> `detachInactiveScreens={false}` also fixed the issue for me.
> example:
> `<MainStack.Navigator detachInactiveScreens={false} screenOptions={{ animationEnabled: false }} > ... </MainStack.Navigator>`

Thank you. This worked for me. 😁👍👍

**Comment by radoncreep** [comment]
> 
> 
> `detachInactiveScreens={false}` also fixed the issue for me.
> example:
> `<MainStack.Navigator detachInactiveScreens={false} screenOptions={{ animationEnabled: false }} > ... </MainStack.Navigator>`

this worked for me, but stops animation when switching screens

**Comment by VityaSchel** [comment]
I tried

- Wrapping `<NavigationContainer>` with `<View style={{ flex: 1, backgroundColor: '#000' }}>`
- `cardStyleInterpolator: () => ({})` in screenOptions
- `animationEnabled: false` in screenOptions
- `detachInactiveScreens={false}` prop on `<Stack.Navigator>`
- `contentStyle={{ backgroundColor: '#000' }}` on `<Stack.Screen>`
- `theme={DarkTheme}` prop on `<NavigationContainer>` with object imported from '@react-navigation/native'
- setting DarkTheme following properties:
```javascript
combinedDarkTheme.dark = true
combinedDarkTheme.colors.background = '#000'
combinedDarkTheme.backgroundColor = '#000'
```

And I still getting white flashes when navigating between screens, even after restarting server with `yarn start -c` (clears cache). Samsung A50, android 10, expo go. Is there any other tips?

**Comment by shelzTimesignature** [comment]
its 2022, two years after the first issue was reported but still nothing only workarounds which doesn't work

**Comment by afkcodes** [comment]
```
screenOptions={{
          headerShown: false,
          animation: 'fade_from_bottom'
   }}
```

I solved it with this, try this

**Comment by shelzTimesignature** [comment]
Thanks man

**Comment by afkcodes** [comment]
welcome, i hope it fixed the issue

**Comment by dngconsulting** [comment]
Nothing from all previous answers work, here's why :
1) setting animationEnable to false is not possible, it prevents user to go back by swiping the screen with a gesture
2) playing with background colors is not acceptable if you have a header and a main screen, you can't limit your background to portions of your screens. And when background is dynamic you won't play with theme background color compensation, I don't understand how it's possible to propose such a hack 
Sorry but such a flash with whatever color is not acceptable ...

**Comment by gorip1** [comment]
Adding a simple black view (or of the color of your background) to wrap the rootNavigator also do the trick 

``` jsx
  return (
    <NavigationContainer linking={linking} theme={themeColors}>
      <View style={styles.backgroundTransition}>
        <RootNavigator />
      </View>
    </NavigationContainer>
  );
};

const themedStyles = StyleService.create({
  backgroundTransition: {
    flex: 1,
    backgroundColor: 'black',
  },
});
```

**Comment by koaladlt** [comment]
> ```
>  <Stack.Navigator
>         screenOptions={{
>           headerShown: false,
>           animation: 'fade_from_bottom'
>         }}
>       >
>         <Stack.Screen name="Main" component={MainTabNavigator} />
>         <Stack.Screen name="Favorites" component={Favorites} />
> </Stack.Navigator>
> ```
> 
> I solved it with this, try this

This is the best solution for me now, thanks a lot!

**Comment by risav-sarkar** [comment]
> 

Thank You! This worked!

**Comment by risav-sarkar** [comment]
> ```
>  <Stack.Navigator
>         screenOptions={{
>           headerShown: false,
>           animation: 'fade_from_bottom'
>         }}
>       >
>         <Stack.Screen name="Main" component={MainTabNavigator} />
>         <Stack.Screen name="Favorites" component={Favorites} />
> </Stack.Navigator>
> ```
> 
> I solved it with this, try this

Thank You! This worked!

**Comment by minhajul-islam** [comment]
> <item name="android:windowBackground">#000000</item>

thanks a lot

**Comment by HenZzz-999** [comment]
Hello, how are you :), I also had this problem, there are several ways to solve it, the best of which is to use the '@react-navigation/native' documentation, this solution is correct and effective:

- https://reactnavigation.org/docs/themes/#basic-usage

This would be an example code:
```
const MyTheme = {
         ...DefaultTheme,
         colors: {
             ...DefaultTheme.colors,
             background: '#000000', // Here you set the background color
         },
     };
```

Within MyTheme you can add many more changes apart from the background color, there you can change default colors of the **'@react-navigation/native'** dependency, to see it just enter the imported file **'DefaultTheme'** from:

- import { NavigationContainer, DefaultTheme } from '@react-navigation/native'

I hope I have helped or contributed greetings! :)

**Comment by ThukuWakogi** [comment]
Replacing `createNativeStackNavigator` with `createStackNavigator` worked for me.

https://stackoverflow.com/a/72720779/5895888

**Comment by laspi94** [comment]
import { DarkTheme, NavigationContainer, DefaultTheme } from '@react-navigation/native';

return (
        <NavigationContainer onStateChange={handleStateChange} theme={isDarkActive() ? DarkTheme : DefaultTheme}  >
            <StackNavigator />
        </NavigationContainer >
    );
    
    hidden something more

**Comment by brianwkinyua** [comment]
> Replacing [`createNativeStackNavigator`](https://reactnavigation.org/docs/native-stack-navigator) with [`createStackNavigator`](https://reactnavigation.org/docs/stack-navigator/) worked for me.
> 
> You can make this change together with most of the fixes given above
> 
> https://stackoverflow.com/a/72720779/5895888

Using 

<SafeAreaProvider style={{ backgroundColor: <your app's theme color> }}>
    <OtherComponents/>
</SafeAreaProvider>

worked for me after all other attempts failed. Thanks for sharing this [ThukuWakogi](https://github.com/ThukuWakogi).
