### ISSUE TITLE
Back gesture broken

### ISSUE THREAD

**Issue by BrendonSled** [software-mansion/react-native-screens#385]
The back gesture in iOS no longer works in the latest release

Platform: iOS
Version: 2.0.0-beta.13

With some testing it looks like this issue started at beta.11

**Comment by janicduplessis** [comment]
I can confirm this, looking into it.

**Comment by Hirbod** [comment]
Bummer... v2 just got released and merged into expo sdk 37. I can confirm this too

**Comment by janicduplessis** [comment]
@Hirbod can you confirm that #389 fixes the issue?

I will make sure this gets included in expo release

**Comment by ShotSkydiver** [comment]
Yep.... seems to have been introduced somewhere in between beta.10 and beta.13 - at least, that's when I first noticed it

**Comment by Hirbod** [comment]
Gimme couple if minutes, gonna implement the fix

**Comment by Hirbod** [comment]
@janicduplessis 👍 #389 fixed the issue, gesture is working again.

**Comment by janicduplessis** [comment]
👍 Thanks!

**Comment by Hirbod** [comment]
@janicduplessis u have contacts to get this into sdk 37?

**Comment by janicduplessis** [comment]
Yes, I mentioned this to people at Expo to make sure it gets included.

**Comment by Hirbod** [comment]
@janicduplessis I don't know what happened or what I've done, I also made a clean local demo but the back gesture is still broken, I am 100% on react-native-screens 2.2.0

**Comment by Hirbod** [comment]
@janicduplessis false alarm.. its the simulator, which wan't we do drag over the edge to recognize my swipe.. everything is working
