### ISSUE TITLE
[native-stack] [iOS]: headerTranslucent doesn't work and causes issues with layout

### ISSUE THREAD

**Issue by sallar** [software-mansion/react-native-screens#387]
Hi, 

When adding `headerTranslucent: true` on iOS, the header does NOT get translucent, but instead, some new issues are caused by it.

Without `headerTranslucent`:

![image](https://user-images.githubusercontent.com/768052/75338344-3b837b80-5897-11ea-9909-e72fb02c9798.png)

With `headerTranslucent`:

![image](https://user-images.githubusercontent.com/768052/75338380-49d19780-5897-11ea-95de-4f91b9a9d0d8.png)

Note that the spacing from top is wrong and the content are now under the header (the week strip is not shown). And also the header does not turn translucent. 

I'm using `react-native-screens@2.0.0-beta.13` and `@react-navigation/native-stack@5.0.3`

**Comment by sallar** [comment]
This is still the case in `2.2.0`

**Comment by zcmgyu** [comment]
This still remains on 2.3.0

<img width="538" alt="Screen Shot 2020-03-20 at 7 33 23 PM" src="https://user-images.githubusercontent.com/13638569/77156419-ae70c280-6ae2-11ea-91a0-711088079e3e.png">

**Comment by AzzouDuGhetto** [comment]
Ran into the same issue

**Comment by WoLewicki** [comment]
What behavior do you want to achieve? setting `headerTranslucent: true` on iOS 13 makes the content not respect the header's height and appears under it. If you want to see the content below the header, use semi-transparent header backgroundColor, e.g. 
```js
headerTranslucent: true,
headerStyle: {backgroundColor: 'rgba(255,255,255,.8)'},
```

**Comment by sallar** [comment]
@WoLewicki that makes sense. Two questions:

1- Isn't `headerTranslucent` supposed to make the header look blurred? Will setting a translucent background colour achieve this?
2- How do I find out what body padding to use so the content appears at the right spot?

**Comment by WoLewicki** [comment]
1. In the current implementation, setting `headerTranslucent` to `true` will resolve to `configureWithDefaultBackground` of appearance (https://github.com/software-mansion/react-native-screens/blob/master/ios/RNSScreenStackHeaderConfig.m#L271). It makes the content appear under the header, which gives the opportunity to see the content when applying backgroundColor with alpha < 1 to the header.
2. `react-native-screens` don't provide a method which will give you the current height of header + status bar, for now, so you have to implement the padding by yourself.

**Comment by sallar** [comment]
@WoLewicki I see. thanks. So there's no way currently to also make it blurred like native iOS apps?
Seems like background effect needs to be applied. https://developer.apple.com/documentation/uikit/uibarappearance/3197994-backgroundeffect?language=objc

**Comment by WoLewicki** [comment]
Hmm I can add `backgroundEffect` as a prop to RNScreens.

**Comment by WoLewicki** [comment]
I added PR for it #512. Can you check if it is what you would like to have @sallar?

**Comment by sallar** [comment]
@WoLewicki thanks! I’ll check in a minute.

**Comment by sallar** [comment]
@WoLewicki that's it :) works nicely. 

```
      navigationOptions: () => ({
        title: 'Start',
        headerStyle: {
          blurEffect: 'prominent',
        },
        translucent: true,
        largeTitle: true,
      }),
```

I added this in `nativeNavigation.js` in RNScreens Example and works perfectly.

<img width="346" alt="image" src="https://user-images.githubusercontent.com/768052/81990509-f8d87080-9647-11ea-998f-ee3a9030b6f3.png">

The thing is, when I don't add `blurEffect`, it still works (of course with a normal blur this time):

<img width="320" alt="image" src="https://user-images.githubusercontent.com/768052/81990545-0ee63100-9648-11ea-89c9-dbf8cc9d53d6.png">

Thanks a lot.

**Comment by sallar** [comment]
However I think something's wrong with the master version "in my project only". this is what happens in mine but not in Example@master:
```
      <Stack.Screen
        name={HOME_SCREEN}
        component={HomeScreen}
        options={{
          headerLargeTitle: true,
          headerTranslucent: true,
          headerStyle: {
            backgroundColor: 'rgba(255, 0, 0, 0.1)',
          },
        }}
      />
```

Results in an "opaque" background:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/768052/81991083-2245cc00-9649-11ea-8e3a-419885d0348c.png">

So the navigation is not actually translucent.

**Comment by WoLewicki** [comment]
Blur effect can be only applied with connection to backgroundColor and with that color having alpha < 1. Then it can change the default blur applied. It works with `backgroundColor: 'transparent'` too. In your case, there might be a problem with aligning the content after the refresh. Try switching the translucency and refreshing the app with cmd+R. After disabling translucency, the content should appear below the header section.

**Comment by arjndr** [comment]
@sallar setting `contentInsetAdjustmentBehavior="automatic"` on ScrollView seems to fix the layout issue

**Comment by WoLewicki** [comment]
@arjndr setting `contentInsetAdjustmentBehavior="automatic"` with translucent header makes the `ScrollView` acquire a `contentOffset` equal to the height of the header, but the ScrollView can still scroll under the header.
headerTranslucent: true
![image](https://user-images.githubusercontent.com/32481228/84784324-764a2480-afea-11ea-9dda-841597588f66.png)
headerTranslucent: false
![image](https://user-images.githubusercontent.com/32481228/84784454-9ed21e80-afea-11ea-97e0-772e2563a2df.png)
You can see the difference in the size of `RNScreen`.

**Comment by WoLewicki** [comment]
Can I help you any more with this issue or can I close it?

**Comment by LRNZ09** [comment]
I still have this issue with version `2.10.1`

**Comment by WoLewicki** [comment]
@LRNZ09 but what is your issue?

**Comment by LRNZ09** [comment]
@WoLewicki sorry for not being so explicit, I resolved with the layout issue using @arjndr’s solution, but I still can't enable the translucent header

**Comment by WoLewicki** [comment]
What do you mean by not being able to enable it? You can check this medium post to see how it works from iOS 11: https://medium.com/@wailord/the-particulars-of-the-safe-area-and-contentinsetadjustmentbehavior-in-ios-11-9b842018eeaa. `react-native-screens` sets `edgesForExtendedLayout` to `UIRectEdgeAll` when setting the `translucent` to `true.

**Comment by LRNZ09** [comment]
@WoLewicki I’ve just set `headerTranslucent`to `true` in the `screenOptions` prop of `NativeStack.Navigator`

**Comment by WoLewicki** [comment]
And it didn't change anything? Can you provide a snack/repo that shows the problem?

**Comment by sallar** [comment]
`NativeStack.Navigator` sounds like react-navigation and not react-native-navigation 🤔

**Comment by LRNZ09** [comment]
I'm working on this repo https://github.com/LRNZ09/match-app I've added a red box on the welcome page to test the translucency

**Comment by WoLewicki** [comment]
Could you provide a minimal repo needed to reproduce the issue so everybody can easily work on it? It would be best if it would have only the needed libraries.

**Comment by LRNZ09** [comment]
@WoLewicki Sure, here's a snack https://snack.expo.io/@lrnz09/header-translucent-bug

**Comment by WoLewicki** [comment]
@LRNZ09 you are using `contentInsetAdjustmentBehavior="automatic"` on `ScrollView`, which adds inset equal to header's height, so the first element of this `ScrollView` appears below it. You can see my comment: https://github.com/software-mansion/react-native-screens/issues/387#issuecomment-644786421. To check that the header is translucent, you can apply something like
```
headerStyle: {
    backgroundColor: 'rgba(100,100,100,0.1)',
    blurEffect: 'prominent',
  },
```
and see the difference with `headerTranslucent`: `true/false`.

**Comment by LRNZ09** [comment]
@WoLewicki ok so, the problem here is that you have to add a transparent background color to see the translucent effect. But I remember in an old version of the native stack it wasn't mandatory and just `headerTranslucent` was enough

**Comment by WoLewicki** [comment]
It may have been like that. Can I help you any more with this or can I close this issue?

**Comment by LRNZ09** [comment]
Yeah I guess this can be closed now

**Comment by timothyerwin** [comment]
> `contentInsetAdjustmentBehavior="automatic"`

this works with a scrollview but for some reason it doesn't work with a flatlist
