### ISSUE TITLE
Add animationTypeForReplace

### ISSUE THREAD

**Issue by enheit** [software-mansion/react-native-screens#394]
I would like to have `animationTypeForReplace` option for `Stack.Screen`.

> **animationTypeForReplace**
>
>The type of animation to use when this screen replaces another screen. It takes the following values:
>
>`push` - The animation of a new screen being pushed will be used
>`pop` - The animation of a screen being popped will be used
>Defaults to `push`.
>
>When `pop` is used, the `pop` animation is applied to the screen being replaced

See: https://reactnavigation.org/docs/stack-navigator#animationtypeforreplace

**Comment by caiobiodere** [comment]
@WoLewicki is there any workaround to get this working?

**Comment by WoLewicki** [comment]
@caiobiodere @enheit can you check if #486 is what you need and works right?

**Comment by caiobiodere** [comment]
@WoLewicki Hey mate thanks for doing this, that's exactly what we need but there is still a problem when you use it as a push replacement the navigation bar is changing its height I think probably because of the animation sequence of how you are changing the controllers maybe this works:

```
NSMutableArray *newControllers = [NSMutableArray arrayWithArray:controllers];
[_controller setViewControllers:newControllers animated:NO];
[_controller pushViewController:top animated:shouldAnimate];
```

**Comment by WoLewicki** [comment]
I am not sure what do you mean by the change of the bar height. Can you be more specific? Also, I cannot make it this way because your configuration adds one more controller. `newControllers` is the new array of controllers that should be set. You add an excessive element in that configuration.

**Comment by enheit** [comment]
@WoLewicki I currently not able to check this functionality. If something will not be working as expected I will create another issue. 

Thank you (:

**Comment by caiobiodere** [comment]
@WoLewicki what happens is while the navigation is pushed from using replace animation the bar height is almost collapsed to the top and when the animation is done the bar height is pushed to the right size

**Comment by WoLewicki** [comment]
@caiobiodere could you post here a gif that shows the behavior you are talking about?

**Comment by caiobiodere** [comment]
@WoLewicki hey mate I was actually using it wrong, my navigator stack was being built all wrong fixed it following react navigation guides, thank you for being awesome and I think you should include this feat in the future
