### ISSUE TITLE
RTL SUPPORT

### ISSUE THREAD

**Issue by baraa95** [software-mansion/react-native-screens#403]
hi , i'm trying to use the native stack for iOS and android ,

the issue that when the app is rtl ... the animations and the headers still from left to right ,

this issue was in the react native navigation library and they added their support here 

![Screen Shot 2020-03-02 at 10 18 12 AM](https://user-images.githubusercontent.com/16765528/75657565-29c31f00-5c6f-11ea-81e2-ebf80ec968e7.png)

https://wix.github.io/react-native-navigation/#/docs/styling?id=options-object-format

kindly add this support so the library will be full and have all the same features like them

**Comment by EhsanSarshar** [comment]
+1

**Comment by EhsanSarshar** [comment]
@WoLewicki is there any plan to support RTL

**Comment by WoLewicki** [comment]
Can you check if #580 works the way it should?

**Comment by baraa95** [comment]
@WoLewicki Thanks a lot its working now but only when headerShown is true... if you set the headerShown to false the issue still exist

**Comment by WoLewicki** [comment]
@baraa95 can you check if #722 fixes both those issues? I can spot the large title jumping from the left side to the right one when there is large title in the first screen of the app, but I don't know if there is a way to fix this unfortunately.

**Comment by kashmiry** [comment]
@baraa95 Did you find a solution to this? when`headerShown: false` I still get the behavior switched.
