### ISSUE TITLE
createNativeStackNavigator documentation missing 

### ISSUE THREAD

**Issue by desis123** [software-mansion/react-native-screens#404]
I used createNativeStackNavigator while it was with @react-navigation, today I just found it moved with  react-native-screens. But the document I used from react-navigation website, it's not in there  anymore. . I found it from google cache. It would be very helpful for us if elaborated  documentation is present here. 

One more thing to say, if you look for performance, there is no choice but to use  createNativeStackNavigator . so I hope the library would be maintained in future. I really liked it's performance.

**Comment by derwo** [comment]
Seems like documentation should arrive soon. This is from the README:

> 
> ## Using native stack navigator
> 
> In order to take advantage of the native stack navigator primitive introduced in version 2.0 you need to use navigator creator function exported by react-native-screens package:
> 
> ```js
> import createNativeStackNavigator from 'react-native-screens/createNativeStackNavigator';
> ```
> 
> Then replace places when you use `createStackNavigator` with `createNativeStackNavigator`. Note that not all the screen customization options are supported. There are some technical limitations for implementing some of the stack header options. Documenting the supported parameters is on an immediate roadmap and will be available soon.
>

**Comment by diego-better-half** [comment]
I believe that should be changed to `import { createNativeStackNavigator } from 'react-native-screens/native-stack';`

**Comment by Hirbod** [comment]
It’s there, just look closer ;)

https://github.com/software-mansion/react-native-screens/blob/master/native-stack/README.md

**Comment by WoLewicki** [comment]
@Hirbod is right, it is the available documentation of `native-stack`
