### ISSUE TITLE
[native-stack] Custom image background on the whole screen

### ISSUE THREAD

**Issue by leshniak** [software-mansion/react-native-screens#405]
**Platform:** Android

**Problem:** I'd like to set a custom image background on the whole app screen, including the header bar. On react-navigation and non-native stack I can do it with https://reactnavigation.org/docs/stack-navigator/#headertransparent.

Is this possible on native-stack? Or will it be possible in the future?

**Comment by WoLewicki** [comment]
So you basically need a transparent header?

**Comment by leshniak** [comment]
Yes, I want to achieve an effect like this:
![IMG_1737](https://user-images.githubusercontent.com/752917/82296527-d5435c00-99a0-11ea-8931-ef0e218d08b2.PNG)

**Comment by WoLewicki** [comment]
On iOS it is already an option with:
```js
 headerStyle: 
{
  backgroundColor: 'transparent'
}
```
On Android it is not available currently.

**Comment by WoLewicki** [comment]
Please follow #575 for any updates on this.
