### ISSUE TITLE
How to use with React Native Router Flux?

### ISSUE THREAD

**Issue by jeanlucdu55** [software-mansion/react-native-screens#407]
Hi, 

Our app is done with RNRF and we'd like to have the iOS 13 modals but we don't understand how to add react-native-screens to our project,

Does anyone has successfully used Screens with RNRF? 

Thanks, 

Théo

**Comment by WoLewicki** [comment]
Do you mean that you would like to use native-stack in your project?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
