### ISSUE TITLE
How to use native stack navigator ?

### ISSUE THREAD

**Issue by muhammadwafa** [software-mansion/react-native-screens#411]
`@react-navigation/native-stack' to 'react-native-screens/native-stack`, how can I use `native stack `from `react-native-screens`. 

If I need only `native-stack`, then do I need to install` react-navigation` too ???

**Comment by Hirbod** [comment]
Yes you will, if you actually want a navigation library. 

https://github.com/software-mansion/react-native-screens/blob/master/native-stack/README.md

**Comment by muhammadwafa** [comment]
Thank you Is `native-stack` faster than `@react-navigation/stack`

**Comment by Hirbod** [comment]
Yes, it’s smoother since it’s a native primitive but less customizable

**Comment by desis123** [comment]
@muhammadwafa I highly recommand to use native stack ... I have tested both of them on production.  native-stack is way to smoother than react-navigation stack.

**Comment by muhammadwafa** [comment]
thank you so much

**Comment by WoLewicki** [comment]
I'm closing since it's resolved.

**Comment by Jalson1982** [comment]
@desis123 @Hirbod  how you use it? I tried native stack on IOS perfect fine performance great but on android, I do not have any touchable event.
