### ISSUE TITLE
While swipe back view - Automatically call on click event. 

### ISSUE THREAD

**Issue by singheshadev** [software-mansion/react-native-screens#416]
Issue only when crate sub stack.navigator crate

- Create one stack.navigation and create another stack.navigation and use second navigation in first navigation

```
export const TeamSettings =() => {
    return (
        <Stack.Navigator
            initialRouteName="changeTeam"
            screenOptions={{
                headerShown: false
            }}
        >
            <Stack.Screen name="TeamSettings" component={TeamSettings}/>
        </Stack.Navigator>
    );
};

export const TeamSettings =() => {
    return (
        <Stack.Navigator
            initialRouteName="changeTeam"
            screenOptions={{
                headerShown: false
            }}
        >
            <Stack.Screen name="changeTeam" component={changeTeam}/>
            <Stack.Screen name="changeTeam2" component={changeTeam}/>
        </Stack.Navigator>
    );
};
```

When swipe to back in **changeTeam2** screen then swipe back successfully but call click event in list in view changeTeam2.

**Comment by WoLewicki** [comment]
Are you using `native-stack` or just `stack` navigator?

**Comment by rinpatva14** [comment]
I am using native-stack.

**Comment by singheshadev** [comment]
I am using native-stack.

**Comment by WoLewicki** [comment]
Can you provide a repo with the minimal needed configuration to recreate the issue?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
