### ISSUE TITLE
[iOS] Navigate from tabs causes error

### ISSUE THREAD

**Issue by AlexSmirnov9107** [software-mansion/react-native-screens#418]
Navigate from tabs to stack causes error. 

![image](https://user-images.githubusercontent.com/32673518/76624929-6db3ff00-6560-11ea-82e1-243f9ab59c40.png)

![image](https://user-images.githubusercontent.com/32673518/76624998-8b816400-6560-11ea-9106-4e3716feae18.png)

`

-  "react-navigation": "^4.2.2",
- "react-native-screens": "^2.3.0",

`

**Comment by mikedizon** [comment]
Seeing this as well

**Comment by mikedizon** [comment]
In my case, the problem appears to go away when I switch from `createAnimatedSwitchNavigator` to `createSwitchNavigator`

**Comment by mikedizon** [comment]
@AlexSmirnov9107 were you able to resolve?

**Comment by WoLewicki** [comment]
Can you provide a minimal repo where the bug can be seen?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
