### ISSUE TITLE
Question: Could orientation locking be a part of this library?

### ISSUE THREAD

**Issue by bjartebore** [software-mansion/react-native-screens#42]
One of the things I have been missing from react-navigation is the possibility to lock the orientation of the screen for an incoming view. Since this must be implemented on a UIViewController and not a UIView on iOS this was before impossible to accomplish. With react-native-screens introducing the use of UIViewController I see a possibility for this. Could this be a possible future feature for react-native-screens?

**Comment by kmagiera** [comment]
Definitely make sense. Note however that screens does not require you to render full screen elements. Good example is when you want to have split view on wider screens (tablets) and want to have a side pane that is visible with the changes being made in the main area. But I can still see this fit into this library scope so if you are willing to submit a PR I'd be more than happy to review and merge it in
