### ISSUE TITLE
Navigator rendering twice and resetting screenOptions to defaults.

### ISSUE THREAD

**Issue by GollyJer** [software-mansion/react-native-screens#424]
Hi. I'm using v2.3.0.

I have a simple stack and am trying to turn off gestures.
```javascript
<Native.Navigator
  initialRouteName={initialRouteName}
  screenOptions={{ headerShown: false, gestureEnabled: false }}
>
  <Native.Screen name="account-setup" component={screens.AccountSetupScreen} />
  <Native.Screen name="user-type-selector" component={screens.UserTypeSelectionScreen} />
</Native.Navigator>
```

**However, gestures remain enabled.** 

I walked through the source and landed here. 
https://github.com/software-mansion/react-native-screens/blob/89658d9361d32865bf5955549e94f85be155da89/src/screens.native.js#L109

When I `console.log({...this.props})` they get printed twice.
The first output show correct values.
```javascript
{
  "children":  [children are in here ]
  "gestureEnabled": false,  //  <=====  👍
  "onAppear": [Function onAppear],
  "onDismissed": [Function onDismissed],
  "onFinishTransitioning": [Function onFinishTransitioning],
  "stackAnimation": undefined,
  "stackPresentation": "push",
  "style": Object {
    "bottom": 0,
    "left": 0,
    "position": "absolute",
    "right": 0,
    "top": 0,
  },
}
```
**But the second resets them to default**

```javascript
{
  "children":  [children are in here ]
  "gestureEnabled": undefined,  //   <===== 👎
  "onAppear": [Function onAppear],
  "onDismissed": [Function onDismissed],
  "onFinishTransitioning": [Function onFinishTransitioning],
  "stackAnimation": undefined,
  "stackPresentation": "push",
  "style": Object {
    "bottom": 0,
    "left": 0,
    "position": "absolute",
    "right": 0,
    "top": 0,
  },
}
```

This happens with any screenOptions passed into `Native.Navigator`

I'm not sure if I've discovered a bug but stepping around the code it isn't obvious to me why this is happening.

Thanks.

**Comment by WoLewicki** [comment]
Does the bug occur after upgrading to the latest version of RNScreens? If so, can you provide a repo with a minimal repro with the options passed to the navigator that is not working correctly?

**Comment by GollyJer** [comment]
@WoLewicki Just tried with `2.4.0`. Still the same.

Is it working in your tests? If it's on my end I don't want to bother you.

**Comment by WoLewicki** [comment]
I think it might be some error on your side since I haven't noticed such behavior. Maybe if you provided minimal configuration where the error occurs, it would be easier to spot the problem.

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
