### ISSUE TITLE
In the case of Stack Presentation is modal, after dismissing modal, could not push to any screen.

### ISSUE THREAD

**Issue by zcmgyu** [software-mansion/react-native-screens#425]
In the case of Stack Presentation is `modal`, after dismissing modal, could not push to any screen.

I try adding an event to trigger dismiss but it hasn't any event callback.

 Stack Presentation is `push` works fine.

### Code:

`stackPresentation: 'modal'`

```
useEffect(() => {
    const unsubscribe = navigation.addListener('appear', e => {
      alert('alert');
    });

    return unsubscribe;
  }, [navigation]);

useEffect(() => {
    const unsubscribe = navigation.addListener('dismiss', e => {
      alert('dismiss'); // THIS DOES NOT SHOW
    });

    return unsubscribe;
  }, [navigation]);
```

### Evidence:

**Modal:**

![Mar-20-2020 20-20-20](https://user-images.githubusercontent.com/13638569/77159214-458c4900-6ae8-11ea-96f7-564a127fe8fc.gif)

**Push:**

![Mar-20-2020 20-17-37](https://user-images.githubusercontent.com/13638569/77159097-08c05200-6ae8-11ea-835c-6dcd90e5a8eb.gif)

### Version:

> react-native-screens 2.3.0
> @react-navigation/native: 5.1.1

**Comment by wibb36** [comment]
It doesn't push to other screens in the same navigator. when modal presentation.

It works fine without #260 @kitten changes. The only thing that doesn't work is the missing headers. Try  it without the patches.

**Comment by zcmgyu** [comment]
@wibb36 Thanks. This is a patch's issue.
