### ISSUE TITLE
[native-stack] Add headerLargeTitleStyle to Native Stack Navigator

### ISSUE THREAD

**Issue by GabrielRegis** [software-mansion/react-native-screens#437]
I'm trying to change the Large Header Font Family when using Native Stack Navigator and it's not working as it should. It would be nice if we could configure font properties for the Large Title component.

**Comment by WoLewicki** [comment]
Can you be more specific of what is not working how it should? `headerLargeTitleStyle` is exposing `fontFamily` property.
