### ISSUE TITLE
Include back button in ScreenStackHeaderLeftView

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-screens#445]
Firstly, this lib is awesome.

When defining a custom ScreenStackHeaderLeftView, I feel that a lot of the times I'd want to still have the native back button where applicable. If I wish to be able to both go back and have a custom view next to it.

Also perhaps a side question on this, would I be able to detect if the stack can go back?

Edit: figured the last point out already - thanks

**Comment by WoLewicki** [comment]
@kyle-ssg can you check if using `backButtonInCustomView` from #457 set to `true` gives you what you want?

**Comment by WoLewicki** [comment]
Ok so I am closing this issue. Feel free to comment if there is something wrong.
