### ISSUE TITLE
headerLargeTitleHideShadow prop is not working for me

### ISSUE THREAD

**Issue by artmerlop** [software-mansion/react-native-screens#447]
This is my code:

`<Stack.Navigator screenOptions={{headerBackTitle: 'Atrás'}}>
      <Stack.Screen name="Test" component={Test} options={{headerLargeTitle: true, headerLargeTitleHideShadow: true, headerLargeStyle: {backgroundColor: 'transparent'}, headerTitle: "Test"}} />
    </Stack.Navigator>`

**Comment by WoLewicki** [comment]
The option's name is `headerHideShadow`, that is probably why it is not working for you. Does it solve your issue?

**Comment by artmerlop** [comment]
Hi @WoLewicki I'm trying to use the recently added props: largeTitleHideShadow and headerLargeStyle, none of them work.

**Comment by WoLewicki** [comment]
Oh ok, so it is a question to @janicduplessis then.

**Comment by artmerlop** [comment]
@WoLewicki he is not home, haha

**Comment by WoLewicki** [comment]
@artmerlop are you using it in iOS 13?

**Comment by milesper** [comment]
This is still an issue for me in the 2.5.0 release, is there any solution or planned fix?

**Comment by artmerlop** [comment]
> @artmerlop are you using it in iOS 13?

Yes! @WoLewicki

**Comment by WoLewicki** [comment]
What exactly does not work? 
With headerLargeTitleHideShadow: true:
![image](https://user-images.githubusercontent.com/32481228/80369920-58d0c800-888f-11ea-8152-6992709fb4dc.png)
With headerLargeTitleHideShadow: false:
![image](https://user-images.githubusercontent.com/32481228/80370001-7c940e00-888f-11ea-8ec3-646138064594.png)
Maybe it is an Expo project and the native code, which you are using does not have this prop yet?

**Comment by lucasmotta** [comment]
I don't see this option available on the `2.7.0` - if I use `headerHideShadow: true` it does remove the shadow.

**Comment by WoLewicki** [comment]
@lucasmotta you are right, `headerHideShadow` works both on the large and normal header and `headerLargeTitleHideShadow` will work only for the large title.

**Comment by WoLewicki** [comment]
Is this issue still relevant? As far as I can repro, these props are working fine. Can someone provide a repo with something not working, and, if not, can I close this issue?

**Comment by artmerlop** [comment]
The property is now working for me in latest version (2.7.0) I think is now safe to close this issue.
