### ISSUE TITLE
Android leak

### ISSUE THREAD

**Issue by everfire130** [software-mansion/react-native-screens#448]
```
main dependencies:
 "react": "16.11.0",
 "react-native": "0.62.0",
 "react-navigation": "4.3.5",
 "react-navigation-hooks": "1.1.0",
 "react-navigation-stack": "2.3.9",
 "react-navigation-tabs": "2.8.9",
 "react-native-screens": "2.4.0",
```
and after I have added this code to app.js.
```
import {enableScreens} from 'react-native-screens';
enableScreens();
```
and use `push` 、 `navigate` to route in some pages
  I got the leak warnings
![WechatIMG1188](https://user-images.githubusercontent.com/11308837/78004907-60bf4a00-736d-11ea-9cde-d1fe0b150736.jpeg)
![WechatIMG1189](https://user-images.githubusercontent.com/11308837/78004917-66b52b00-736d-11ea-8cc2-44aa592e1b7a.jpeg)

**Comment by InvictusGar** [comment]
same problem

**Comment by WoLewicki** [comment]
Can you provide a repo with minimal configuration needed to reproduce the issue?

**Comment by tanjiaweiGitHub** [comment]
webview 开启硬件加速，安卓9 10 可以百分百重现 @WoLewicki

**Comment by WoLewicki** [comment]
@tanjiaweiGitHub could you write in English? I'm sorry but I don't understand what is written there.

**Comment by InvictusGar** [comment]
he means to set webview hardwareAccelerated=true, and then this leak would appear @WoLewicki

**Comment by tanjiaweiGitHub** [comment]
enableScreens() and hardwareAccelerated=true

**Comment by tanjiaweiGitHub** [comment]
enableScreens() and hardwareAccelerated=true

Open any webpage through webView, then exit webview, click on any @WoLewicki

**Comment by tanjiaweiGitHub** [comment]
By adding the style opacity: 0.99 you can avoid the crash problem, but I think this is not a long-term plan @WoLewicki

**Comment by tanjiaweiGitHub** [comment]
And I encountered the problem of flickering after page loading when switching pages, which was temporarily solved by setting opacity: 0.99

**Comment by WoLewicki** [comment]
There seem to be some problems with the react-native-webview and react-native-screens integration, but I am not sure that it should be solved anyhow on our side. If you have any ideas, I would love to check PR with such changes.

**Comment by WoLewicki** [comment]
I am closing this issue to keep the discussion about `react-native-webview` in one place. Please see #105 for more information.
