### ISSUE TITLE
Native Stack does not compile when isolatedModules flag is provided

### ISSUE THREAD

**Issue by niksudan** [software-mansion/react-native-screens#449]
Attempting to compile `react-native-screens/native-stack` with the `isolatedModules` flag enabled throws the following error:

```
Cannot re-export a type when the '--isolatedModules' flag is provided.
```

This is caused by [this line of code](https://github.com/software-mansion/react-native-screens/blob/master/native-stack/index.tsx#L16):

```tsx
export {
  NativeStackNavigationOptions,
  NativeStackNavigationProp,
} from './types';
```

A solution for this is to [upgrade to TypeScript 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#-type-only-imports-and-export) and then adding the `type` keyword:

```tsx
export type { ... } from './types';
```

Naturally, this isn't great for backwards compatibility. There are some good workarounds provided in [this StackOverflow thread](https://stackoverflow.com/questions/53728230/cannot-re-export-a-type-when-using-the-isolatedmodules-with-ts-3-2-2).

In the meantime I've turned off the option as it's not really necessary for my project, but it's the only dependency that throws this error.

**Comment by WoLewicki** [comment]
@niksudan can you provide a repo with minimal configuration needed to repro the issue so I can work on it?
