### ISSUE TITLE
On going back, or navigating to a screen that exists, a blank page is displayed. 5.x

### ISSUE THREAD

**Issue by paul-apacio** [software-mansion/react-native-screens#451]
This one drove me insane for a while.
Setting up basic stack navigator on Android as described in the docs resulted in the following:

Navigating "forward" works fine, as long as the page does not yet exist in the stack.
Navigating to a preexisting screen in the stack, or using goBack resulted in a blank screen. 

Initially I thought the issue was my screens, but it simply seems to be the animation breaking and not transitioning away. The page is there but behind a white square.

Going back works fine if you use any gesture, or the native back button or gesture, or the back button in the react-navigation header.

Turning off the animation in screenOptions has temporarily fixed this for me: 

`<Stack.Navigator headerMode='none' screenOptions={{gestureEnabled: true, lazy: false, swipeEnabled: true, animationEnabled: false}}>`

Obviously I guess this is not by design.

**Comment by WoLewicki** [comment]
Can you provide a snack or repo with a minimal configuration that shows the issue?
