### ISSUE TITLE
The stack is invalid

### ISSUE THREAD

**Issue by JonsonHI** [software-mansion/react-native-screens#462]
```
"react": "16.11.0",
"react-native": "0.61.5",
"react-navigation": "^4.3.7",
"react-navigation-stack": "^2.3.11",
"react-native-screens": "2.4.0",
```
index.js
```
import { useScreens,enableScreens } from 'react-native-screens';
enableScreens()
```

0.59.8  0.61.5 Integration success  but use was ineffective

![image](https://user-images.githubusercontent.com/18373125/79089334-5f801b00-7d78-11ea-880e-319522555213.png)

**Comment by WoLewicki** [comment]
Can you be more specific on what the issue is?

**Comment by JonsonHI** [comment]
Under react-native-screens, there should be only one page on the page, and mine shows multiple

When I call the enclosing props. Navigation. Navigate () there is no change

**Comment by JonsonHI** [comment]
When I use the react-native screen the ios stack should be just one page on the Controller,
When I call the enclosing props. Navigation. Navigate (" page ") to jump to a new page.
The current controller should also be a page, instead of pushing on the current page in the form of a view or overwriting a view
The react-native screen worked well on the project I created on my own, but my current project is not

Every time you push a new page, you don't walk the native code of iOS
And tabs walk through the native code of iOS every time you click

**Comment by WoLewicki** [comment]
I think what you are getting is the result of https://github.com/react-navigation/react-navigation/blob/master/packages/stack/src/views/Stack/CardStack.tsx#L418 RNScreens are currently disabled on iOS in stack navigator, but they are enabled in Tab navigator so this is why you get it, so this issue is not strictly the issue of react-native-screens. Is this what you meant?

**Comment by JonsonHI** [comment]
![image](https://user-images.githubusercontent.com/18373125/79521510-f1936680-808b-11ea-8835-a055877bba36.png)
screen A->B->C 的ios stack
this is new project

But as I mentioned above it's a View that push a page

**Comment by WoLewicki** [comment]
Sorry but I don't understand what is the issue exactly. Can you provide a repo with a suitable commentary of what is wrong?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
