### ISSUE TITLE
gesturesEnabled not supported for createNativeStackNavigator()

### ISSUE THREAD

**Issue by luatnd** [software-mansion/react-native-screens#467]
Hi, I changed `createStackNavigator` to `createNativeStackNavigator` and my swipe to back feature is not work anymore on android.
```js
import {  createBottomTabNavigator, createStackNavigator } from 'react-navigation';
import createNativeStackNavigator from 'react-native-screens/createNativeStackNavigator';
```
Is createNativeStackNavigator already support the `gesturesEnabled` prop from 'react-navigation'?

**Comment by WoLewicki** [comment]
If you mean going back with swipe gesture, there is no such thing in native Android navigation and so it is not available here. The `gestureEnabled` prop resolves to disabling `goBack()` behavior of hardware back button. Does it solve your issue?

**Comment by luatnd** [comment]
Thanks, 
it's mean my app will lack of swipe-to-back if I switch to `createNativeStackNavigator`?
So my final decision is going back to `createStackNavigator`.

**Comment by WoLewicki** [comment]
> it's mean my app will lack of swipe-to-back if I switch to `createNativeStackNavigator`?

Yes since it is not native behavior.

Ok, so I am closing it. Feel free to comment if anything is wrong.

**Comment by mikehuebner** [comment]
There might actually be a bug with this, while testing `gesturesEnabled` on iOS I cannot seem to disable them.

```
// Generate screens
const AppNavigator = createNativeStackNavigator(AppNavRoutes, AppNavConfig);

// ... Routes Config
const ROUTES = {
  // ...
 Billing: {
    path: `/:productType/${PARAM_BILLING}`,
    screen: Screens.Billing,
    // @TODO Make this dynamical for React Navigation v5
    navigationOptions: {
      gesturesEnabled: false
    }
  },
// ...
};
```

Yet I am still able to swipe back on iOS. Is there something I'm missing or is this not supported yet?

**Comment by WoLewicki** [comment]
Prop's name is `gestureEnabled`, maybe this is the problem @mikehuebner?
