### ISSUE TITLE
Jest - TypeError: Unable to require `.d.ts` file.

### ISSUE THREAD

**Issue by Collin3** [software-mansion/react-native-screens#469]
As soon as I add `import {createNativeStackNavigator} from 'react-native-screens/native-stack';` into my production code, my jest test file fails to run with the error below.

```
  ● Test suite failed to run

    TypeError: Unable to require `.d.ts` file.
    This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or another executable extension available alongside `index.tsx`.
```
I have found that if I rename the `native-stack/types.tsx` file to `native-stack/index.d.ts` then the error goes away. I'm curious if anyone else is seeing this as well. I wonder if there's a problem with how the types are being shipped or if something just isn't configured correctly on my end 🤔

**Comment by Collin3** [comment]
I take that back, that workaround did not actually work. If I clear my jest cache before I run tests for a file that imports `createNativeStackNavigator` it always fails with that error. However, if I run the tests five times in a row, it will fail every time until the 5th time. The first four times it will give me the same error as above and complain about `index.tsx`, `createNativeStackNavigator.tsx`, `HeaderConfig.tsx` and then `NativeStackView.tsx`. As soon as it passes on that fifth run, it will pass every time until I clear my jest cache (or run my tests in a CI pipeline..)

**Comment by WoLewicki** [comment]
Can you check if is not related to https://github.com/kulshekhar/ts-jest/issues/1336? It doesn't seem like the bug in `react-native-screens`.

**Comment by Collin3** [comment]
🤦‍♂️  Bumped up to the latest of jest and ts-jest and that seems to have fixed it.
