### ISSUE TITLE
Confirm installation is correct

### ISSUE THREAD

**Issue by Paduado** [software-mansion/react-native-screens#474]
Hi, I'm following the steps described [here](https://reactnavigation.org/docs/react-native-screens), for a RN App without expo, however I don't see any notable difference in my App's performance, is there a way to confirm `react-native-screens` is properly working?

**Comment by WoLewicki** [comment]
`react-native-screens` are currently disabled on iOS in StackNavigator due to some bugs, so there will be no performance boost there. `react-native-screens` has also `screensEnabled` method, with which you can check if they are enabled for sure. Does it solve your issue?

**Comment by Neck1T** [comment]
> `react-native-screens` are currently disabled on iOS in StackNavigator due to some bugs, so there will be no performance boost there. `react-native-screens` has also `screensEnabled` method, with which you can check if they are enabled for sure. Does it solve your issue?

I used enableScreens
on android I use android studio layout inspector - and I saw the different. But on ios 
I do not see changes 
like here 
https://twitter.com/janicduplessis/status/1039979591815897088/photo/2

**Comment by Paduado** [comment]
> `react-native-screens` are currently disabled on iOS in StackNavigator due to some bugs, so there will be no performance boost there. `react-native-screens` has also `screensEnabled` method, with which you can check if they are enabled for sure. Does it solve your issue?

Yes 🙌, but I was still looking to see a different kind of component being rendered or something like that.

> I used enableScreens
on android I use android studio layout inspector - and I saw the different. But on ios
I do not see changes
like here
https://twitter.com/janicduplessis/status/1039979591815897088/photo/2

I'll try that, thanks!

**Comment by WoLewicki** [comment]
Ok, so I am closing this issue. Feel free to comment if there is something more you would like to know.
