### ISSUE TITLE
Hide Bottom Tab Navigation while still be able to animate the header on push/navigate

### ISSUE THREAD

**Issue by Hirbod** [software-mansion/react-native-screens#476]
Hi,

I am using EXPO SDK 37 (RNS v2.2.0), native-stack and createMaterialBottomTabNavigator.
Using the default bottomTabNavigator isn't an option, as it's missing features (like the badge) which I need. bottomTabNavigator has a "tabBarVisible" prop, which is broken and unusable anyway (and the docs say you should not use it)

I know there have been several tickets about this, but none of them help to get rid of the root problem. If I want to cover the Tabbar on a specific screen, I have to place that screen outside of the TabNavigator (eg RootNavigator), which is perfectly fine and is working for me. 

The real Issue I have with this workaround is iOS' largeHeader, which does a sweet animation for me when I am navigating to another screen, which also has a native header. (largeHeader -> smallHeader, also largeHeader -> largeHeader and small -> to small)
So the largeHeader transitions and shrinks and all elements on the next screen arrange each other smoothly.

When I place the screen outside of the stack in order to open it above the tab bar, I lose all of this nice transitions and animations since this screens have no relationship to eachother.

So: is there any option, to open a "Chat List", which opens the "Chat" and animates the header + sits on top of the nav bar? I mean how does every native app achieve this so easy and we all struggle to hide a TabBar while having sweet header animations.

I did some crazy stuff with EventEmitters and I am able now to push my screen without the TabBar, but I am only setting TabBars barStyle height to 0 and back to undefined when I'm returning back to the first tab screen. It works and looks "Ok", but it is not what I really would love to achieve, as the TabBar is hiding/appearing hard)

Is it possible to have a Stack, which opens a Screen of another Stack but still animates the header between each other? Even If I have to pass some kind of "reference", which is totally fine. But we need to connect different screens with each other, even if they are not part of the same stack.

I mean a "modal" also opens above everything, so there is a mechanism that can open from the current stack and hide the TabBar. But I don't want a modal at this stage, I need that default push screen.

**Comment by WoLewicki** [comment]
One way I can think of is putting a stack navigator above the tabs navigator and navigating to another screen of this stack navigator. This way you keep the header animation and make the `tabBar` disappear on the other screens. I know it may not be the thing you are looking for though. 
>Is it possible to have a Stack, which opens a Screen of another Stack but still animates the header between each other? Even If I have to pass some kind of "reference", which is totally fine. But we need to connect different screens with each other, even if they are not part of the same stack.

Can you provide an example where it could be animated? There is no animation when  
e.g. switching tabs.

**Comment by Hirbod** [comment]
> One way I can think of is putting a stack navigator above the tabs navigator and navigating to another screen of this stack navigator. This way you keep the header animation and make the tabBar disappear on the other screens. I know it may not be the thing you are looking for though.

Can you explain this to me please @WoLewicki ?

I have 3 Tabs, each Tab has a Stack.Navigator.

AppRootNavigator
   TabBar
       Tab1 -> Stack
       Tab2 -> Stack
       Tab 3 -> Stack
RootScreen
...
RootScreen

If I open a Rootscreen, it overlaps the TabBar but no HeaderAnimation
If I open a Screen of a Stack, it has a nice HeaderAnimation but the TabBar stays visible, but I dont want this, because I am opening a Chat and I need the space.

**Comment by WoLewicki** [comment]
> Can you explain this to me please @WoLewicki ?

```js
function Tabs() {
  const Tab = createMaterialBottomTabNavigator();
  return (
    <Tab.Navigator>
      <Tab.Screen name="HomeTab" component={HomeScreen} />
      <Tab.Screen name="EditTab" component={SecondScreen} />
    </Tab.Navigator>
  );
}

function RootStack() {
  const Root = createNativeStackNavigator();
  return (
    <Root.Navigator
      screenOptions={{
        headerLargeTitle: true,
      }}>
      <Root.Screen name="Tabs" component={TabStack} />
      <Root.Screen name="Edit" component={FirstTabStackScreen2} />
      <Root.Screen name="Details" component={FirstTabStackScreen3} />
      <Root.Screen name="Profile" component={FirstTabStackScreen4} />
      <Root.Screen name="Edit1" component={SecondTabStackScreen2} />
      <Root.Screen name="Details1" component={SecondTabStackScreen3} />
      <Root.Screen name="Profile1" component={SecondTabStackScreen4} />
    </Root.Navigator>
  );
}
```

Something like this conceptually. You start in `TabStack`, so the user sees the tabs. Then each navigating goes to the screens of the `Root` stack navigator. It causes the tabs to disappear and keeps the header transitions since it is in the same navigator. You would have to play a bit with the header titles etc, and, as I say, there might be cases where this configuration is unusable. Do you understand the concept?

**Comment by Hirbod** [comment]
Hi, thanks for the ideas. I will play around and see if this fits my needs (since sometimes I want to keep the tabs and some tabs need their own navigator).

Not sure if I get what I need with this approach.

Beside of this workarounds, is there any way „native“ could help to connect different navigators? Is my request even possible?

**Comment by WoLewicki** [comment]
>Beside of this workarounds, is there any way „native“ could help to connect different navigators? Is my request even possible?

It may be possible with custom interpolators but `react-native-screens` don't support it now and I think it won't come in the near future.

> Hi, thanks for the ideas. I will play around and see if this fits my needs (since sometimes I want to keep the tabs and some tabs need their own navigator).

You can e.g. provide the same routes for different navigators. There are ways to enforce the needed behavior most of the time, but they may be not too straightforward.

**Comment by WoLewicki** [comment]
Is there anything else I can help you with here or can I close it?

**Comment by Hirbod** [comment]
Thanks, Im good for now
