### ISSUE TITLE
[TypeScript] Minor issue: cannot re-export type.

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/react-native-screens#478]
```sh
ERROR in node_modules/react-native-screens/native-stack/index.tsx(17,3):
Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
    15 |  */
    16 | export {
  > 17 |   NativeStackNavigationOptions,
       |   ^
    18 |   NativeStackNavigationProp,
    19 | } from './types';
    20 | 

```
It seems like, if the `isolatedModules` flag is set to `true` in `tsconfig.json`, then this line needs to be changed to:

```typescript
export type {
  NativeStackNavigationOptions,
  NativeStackNavigationProp,
} from './types';
```

I tried setting `isolatedModules` to `false`, but Next.js requires it to be `true` to build.

Could I submit a PR to change this line?

https://github.com/software-mansion/react-native-screens/blob/dd115b8be0b4ce99be15c0d6f352283f4959c872/native-stack/index.tsx#L16

**Comment by WoLewicki** [comment]
It should be resolved now so I am closing it. Feel free to comment if I am wrong.

**Comment by nandorojo** [comment]
Thank you!
