### ISSUE TITLE
enableScreens(true) with react navigation make component flash

### ISSUE THREAD

**Issue by AnOptimistSeePessimist** [software-mansion/react-native-screens#480]
## Current Behavior

**enableScreens(true)**

![11](https://user-images.githubusercontent.com/27407218/80302376-421d6900-87dc-11ea-8092-db0a2fe3e8c2.gif)

**enableScreens(false)**
![12](https://user-images.githubusercontent.com/27407218/80302456-c07a0b00-87dc-11ea-8002-49516beb3a8e.gif)

## How to reproduce
https://github.com/AnOptimistSeePessimist/example

**Comment by sa8ab** [comment]
+1 same issue

**Comment by WoLewicki** [comment]
Can you provide a repo with minimal configuration needed to reproduce the issue?

**Comment by AnOptimistSeePessimist** [comment]
tested in android real device(ios is ok): https://snack.expo.io/@chengxiaodong1/reactnativescreens

**Comment by osdnk** [comment]
@AnOptimistSeePessimist 
Would you mind moving this issue to the react-navigation repo? Screens are working fine but appear to be improperly handled by navigation stack. 

Thanks for your watchfulness!

**Comment by AnOptimistSeePessimist** [comment]
ok

**Comment by siarheipashkevich** [comment]
@AnOptimistSeePessimist did you solve this issue?

**Comment by joebernard** [comment]
In my case navigating back (tapping the < in the upper left of a stack) will pop the top screen then quickly flash that top (popped) screen for a split second. It is very reproducible on all my stacks. If I disable `react-native-screens` the problem goes away.

```javascript
enableScreens(false);
```

Relevant packages:
```
"react-native": "0.64.1",
"react-native-screens": "3.3.0",
"react-navigation": "4.4.4",
"react-navigation-props-mapper": "1.0.4",
"react-navigation-stack": "2.10.4",
"react-navigation-tabs": "2.11.1",
```

@AnOptimistSeePessimist Can you please re-open this issue so we can get some attention on it?

**Comment by kangfenmao** [comment]
Same issue!!
