### ISSUE TITLE
No touchable events on Android with Native Stack

### ISSUE THREAD

**Issue by Jalson1982** [software-mansion/react-native-screens#483]
Hello. I am playing around and want to use native stack because of performances but have an issue.
 `   
<NavigationContainer><Stack.Navigator screenOptions={{headerShown: false}}>
          {!isAuthenticated && <Stack.Screen name="Auth" component={Auth} />}
          {isAuthenticated && (
            <Stack.Screen
              name="Wizard"
              component={WizardStack}
            />
          )}
        </Stack.Navigator>
      </NavigationContainer>`

And Auth is another Stack.Navigator same as Wizard. On Android, I do not have any touchable event. On press does not react at all. Any help, please?

**Comment by Jalson1982** [comment]
I have them enabled!
`import React from 'react';
import {SafeAreaProvider} from 'react-native-safe-area-context';
import {NavigationContainer} from '@react-navigation/native';
import FlashMessage from 'react-native-flash-message';
import {useSelector} from 'react-redux';
import {createNativeStackNavigator} from 'react-native-screens/native-stack';
import {Auth, WizardStack} from './src/navigation/Navigation';
import {enableScreens} from 'react-native-screens';
import setAuthorizationHeader from './src/interceptors/setAuthorizationHeader';

enableScreens();
const Stack = createNativeStackNavigator();`

**Comment by Jalson1982** [comment]
Complete App.js file:

`import React from 'react';
import {SafeAreaProvider} from 'react-native-safe-area-context';
import {NavigationContainer} from '@react-navigation/native';
import FlashMessage from 'react-native-flash-message';
import {useSelector} from 'react-redux';
import {createNativeStackNavigator} from 'react-native-screens/native-stack';
import {Auth, WizardStack} from './src/navigation/Navigation';
import {enableScreens} from 'react-native-screens';
import setAuthorizationHeader from './src/interceptors/setAuthorizationHeader';

enableScreens();
const Stack = createNativeStackNavigator();

const App = () => {
  const accessData = useSelector((state) => state.userReducer.accessData);
  const isAuthenticated = useSelector(
    (state) => state.userReducer.isAuthenticated,
  );
  if (accessData) {
    setAuthorizationHeader(accessData.token);
  }

  return (
    <SafeAreaProvider>
      <NavigationContainer>
        <Stack.Navigator screenOptions={{headerShown: false}}>
          {!isAuthenticated && <Stack.Screen name="Auth" component={Auth} />}
          {isAuthenticated && (
            <Stack.Screen name="Wizard" component={WizardStack} />
          )}
        </Stack.Navigator>
      </NavigationContainer>
      <FlashMessage
        position="top"
        titleStyle={{marginTop: 10}}
        duration={4000}
      />
    </SafeAreaProvider>
  );
};

export default App;
`

**Comment by Jalson1982** [comment]
Here is a gist for the complete App.js file. If I replace native stack with a stack from react-navigation it works!
https://gist.github.com/Jalson1982/0bbcc73d628397da9b803c8fced6b5e1

**Comment by Hirbod** [comment]
iirc I've heard people had some problems with touch events and could fix them (its also in the react-navigation docs) that you should include 

```tsx
import "react-native-gesture-handler";
```

at the first import at top your App.js (before you even import React. Try that and lets see if its working. For me its working anyways, with or without that import.

**Comment by Jalson1982** [comment]
I have that too. In index.js file I have it :


import {AppRegistry} from 'react-native';
import React from 'react';
import {PersistGate} from 'redux-persist/integration/react';
import 'react-native-gesture-handler';
import {Provider} from 'react-redux';
import App from './App';
import {name as appName} from './app.json';
import {store, persistor} from './src/state/store';

**Comment by Hirbod** [comment]
Is there any render in your index.js? If so, enableScreens might be called to lately. Also check if your nested Auth-Sack and Wizard-Stack uses nativeStack.

**Comment by Hirbod** [comment]
The last thing I see which differs from my setup is, that I don't use ```SafeAreaProvider```  - maybe thats messing up.

**Comment by Jalson1982** [comment]
Auth stack and wizard stack use native stack. Here is full index.js can it be that this create issue?

`
import {AppRegistry} from 'react-native';
import React from 'react';
import {PersistGate} from 'redux-persist/integration/react';
import 'react-native-gesture-handler';
import {Provider} from 'react-redux';
import App from './App';
import {name as appName} from './app.json';
import {store, persistor} from './src/state/store';

console.disableYellowBox = true;



function renderApp() {
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <App />
      </PersistGate>
    </Provider>
  );
}
AppRegistry.registerComponent(appName, () => renderApp);
`

**Comment by Jalson1982** [comment]
Here is index.js. Can it be issue with it? 

https://gist.github.com/Jalson1982/752b3b6a8aca1aed987e1d22a72ff180

I will try enable screens in index.js now and inform.

**Comment by Hirbod** [comment]
Few hints that might help, even if all of them might be trial and error

1) move ```import 'react-native-gesture-handler';```to first position
2) Import and call enableScreens() in your index.js, not your App.js
3) Remove SafeAreaProvider and try again
4) If you really need SafeAreaProvider (i don't even need it), you need to make sure that your ```SafeAreaView``` has flex: 1

**Comment by Jalson1982** [comment]
Really crazy. I am using Buttons from react-native-gesture-handler and that is the reason why it does not work! If I add normal TouchableOpacity it works.

**Comment by Hirbod** [comment]
I also had a lot of issues with those buttons and I don't use them anymore from react-native-gesture-handler. They only worked for me when handling with absolute positioning on android.

**Comment by Jalson1982** [comment]
Thanks mate. Last one, do you maybe know how to remove shadow under header on android? On ios headerHideShadow works on android when i go back it returns shadow

**Comment by Hirbod** [comment]
Sounds like a bug, might be worth an own ticket. Maybe that react-native-gesture-handler bug is also worth an own issue. This should be closed :)

**Comment by WoLewicki** [comment]
If your first issue is resolved, please close it and open another one with the correct topic if you have any.
