### ISSUE TITLE
Header hide shadow on android do not work

### ISSUE THREAD

**Issue by Jalson1982** [software-mansion/react-native-screens#484]
Hello. I have set on Stack.Navigator property headerHideShadow: true and it works on IOS but on android on goBack it returns shadow or randomly adds it. Look into gif:

![giphy](https://user-images.githubusercontent.com/35011526/80591304-c579cd00-8a1d-11ea-9c30-0b44a1518f08.gif)

**Comment by Jalson1982** [comment]
For now I hide header and made my custom header component but this is issue.

**Comment by SRandazzo** [comment]
Thanks just came searching for this issue as I am seeing the same. Will see if I can poke around at the code

**Comment by Jalson1982** [comment]
Well, I will also try to invest some time but this is an easily reproducible bug home @WoLewicki will have time to take a look.

**Comment by WoLewicki** [comment]
Did this start happening recently or was it always like this? Can someone tell? @SRandazzo @Jalson1982

**Comment by Jalson1982** [comment]
Hello @WoLewicki. To be honest I use react-navigation 5 and wanted because of performances to give a shot to native stack and I use it just for a few days so I can not say how it was in the past. So if I set prop headerHideShadow, on IOS it works as you expect on android you can see this flash showing shadow on transition and then on goBack show it like there is no prop. Hope that this can help though.

**Comment by WoLewicki** [comment]
Ok, thanks.

**Comment by WoLewicki** [comment]
Can you check if #488 resolves the issue?

**Comment by Jalson1982** [comment]
@WoLewicki  thx I will try it during the day and inform! Thanks!

**Comment by agarant** [comment]
@WoLewicki I confirm that #488 resolves the issue.

**Comment by Jalson1982** [comment]
I can confirm the same. It works with #488

**Comment by WoLewicki** [comment]
After some consultation, we changed the behavior to #516 which does not dive into android's implementation but does not give you an opportunity to switch the shadow visibility while being on screen. It shouldn't be a case though. I am closing this issue then. Feel free to comment if the change does not work correctly or if you have any questions.

**Comment by SrBrahma** [comment]
Hmmm... This is happening in the current version but with the default react-navigation createStackNavigator props. Like, the shadow is weak during the transition but gets "fully shadowed" when the transition finishes. It's like the OP .gif, but with the shadow enabled.

**Comment by WoLewicki** [comment]
You should submit an issue in `react-navigation` then. It is almost certainly not the same issue since we use native behaviors in `native-stack`.
