### ISSUE TITLE
Navbar window fitting android

### ISSUE THREAD

**Issue by tankers746** [software-mansion/react-native-screens#485]
I was wondering why the following was reverted: 
https://github.com/software-mansion/react-native-screens/commit/4f8efd2873516dd2d3c30661dffce99b5fa76f57

The current navbar on android doesn't take into account for using a translucent status bar:

`MainActivity.onCreate`

`getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);`

![image](https://user-images.githubusercontent.com/19326459/80616511-93935580-8a73-11ea-8e22-4372cfc845a2.png)

**Comment by janicduplessis** [comment]
I'm using this patch as a workaround for now, we tried making it work properly before but ended up very difficult.

In ScreenStackHeaderConfig.java
```
@@ -153,6 +156,13 @@ public class ScreenStackHeaderConfig extends ViewGroup {
       getScreenFragment().setToolbar(mToolbar);
     }
 
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
+      mToolbar.setPadding(0, getRootWindowInsets().getSystemWindowInsetTop(), 0, 0);
+    } else {
+      // Hacky fallback for old android.
+      mToolbar.setPadding(0, (int)(25 * getResources().getDisplayMetrics().density), 0, 0);
+    }
+
     activity.setSupportActionBar(mToolbar);
     ActionBar actionBar = activity.getSupportActionBar();
 ```

Maybe we could make it a prop so try to find some heuristic to figure out if we're drawing under the statusbar.

**Comment by Hirbod** [comment]
Well.. we both got the same error on the same day ;)
Was about to release my app right now. So we need to set translucent to false again and go with black for now... 
So Expo -> translucent just dont work.

<img width="400" alt="Bildschirmfoto 2020-04-29 um 19 50 09" src="https://user-images.githubusercontent.com/504909/80629130-afd2ca80-8a52-11ea-90de-df14cd4ea2ca.png">

**Comment by mrousavy** [comment]
@janicduplessis Your patch doesn't work for me, it's saying "package Build does not exist". Where did you import the `Build` class from?

**Comment by mrousavy** [comment]
Nevermind, found it! If anyone's interested, [I've created a patch for this](https://gist.github.com/mrousavy/8ab7f59df622cdc94eb7f0ff83500bb1). Use [patch-package](https://www.npmjs.com/package/patch-package) and rebuild to include the patch.

**Comment by WoLewicki** [comment]
Can you check if #518 fixes your issue? It should apply proper insets for translucent/non translucent status bar.

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Also, #545 changed the behavior and should have fixed the issue. Feel free to comment to reopen it.

**Comment by Hirbod** [comment]
I can confirm that it was fixed in the latest release
