### ISSUE TITLE
Feat: Support gestureEnable for iOS page sheet modal

### ISSUE THREAD

**Issue by Hirbod** [software-mansion/react-native-screens#487]
Currently, there is no way to disable the pull down to close gesture. I know that this is a system ux but sometimes it should be configurable, trough stack options or through setOptions()

There are different approaches. One of the approaches will leave the modal still pullable but won’t dismiss it. I don’t see any benefits from this. The other approach is to actually disable. (The most important thing here should be via setOptions(). I see that apples App Store also does this on certain screens while loading for example)

https://stackoverflow.com/questions/56718552/disable-gesture-to-pull-down-form-page-sheet-modal-presentation

**Comment by lucasmotta** [comment]
Hey @Hirbod, sorry if I missed something, but you can disable the pull down gesture by passing `gestureEnabled: false` to your screen.

**Comment by Hirbod** [comment]
Nope, https://github.com/software-mansion/react-native-screens/blob/master/native-stack/README.md#gestureenabled

Also tested this, it’s not working. It’s always dismissible by gesture

**Comment by lucasmotta** [comment]
Oh sorry I should have been more specific - it does not disable the gesture entirely, but for me at least it does not allow it to be dismissed - see the gif below:

![Kapture 2020-04-30 at 18 13 33](https://user-images.githubusercontent.com/76673/80739505-7bbcdf80-8b0e-11ea-8f57-14fd0d48bcd2.gif)

**Comment by Hirbod** [comment]
Where did you put that prop? On the modal itself or on the stack?

If this really works (I’m on expo, so stuck at version 2.4.0, maybe that’s the reason I haven’t seen this behavior) But I would also like to have a full disable. There a plenty of use cases why it should be possible.

**Comment by lucasmotta** [comment]
I'm not really sure on what version Expo is using, but this behaviour was working for me from version 2.5.0 and still works on 2.7.0.

The config is set  on the screen itself on my case:
![image](https://user-images.githubusercontent.com/76673/80743558-102a4080-8b15-11ea-8dd9-8a255ae9fc4f.png)

And if you want to completely block the gesture from happening, I would suggest wrapping your screen with the `PanGestureHandler` - I did a quick test on iOS here (simulator) and the screen does not move at all:

```jsx
export function ModalScreen() {
  return (
    <PanGestureHandler>
      <Animated.View style={{ flex: 1 }}>
        <Text>My screen</Text>
      </Animated.View>
    </PanGestureHandler>
  )
}
```

Let me know if that works for you.

**Comment by Hirbod** [comment]
Thanks. I will test that. It might break my Scrollview inside of it I think.

**Comment by Hirbod** [comment]
It works, but I had to add some activeOffset and failOffsets in order to make the swipe back gesture work but disable the pull down + I had to change my component so that only iOS wraps the gesture handler and not Android because Android wasn’t playing well. But since I achieved what I need I will close this.
