### ISSUE TITLE
Android strange behaviour on hardware back press

### ISSUE THREAD

**Issue by Jalson1982** [software-mansion/react-native-screens#490]
Hello. I have noticed strange behaviour when press android back hardware button, my icons are invisible and then we return back. Look gif bellow:

![giphy2](https://user-images.githubusercontent.com/35011526/80914419-a647ac00-8d4b-11ea-977e-1bb84f7c1443.gif)

And here is the behaviour when I press the icon and go back it does not remove icons on the previous screen and no strange behaviour.

![giphy1](https://user-images.githubusercontent.com/35011526/80914433-c24b4d80-8d4b-11ea-9d70-3f6dee312a3d.gif)

**Comment by Hirbod** [comment]
I can confirm that this also happens when I use icons on headerRight(). The moment I goBack() or pop() I can see that the icon disappears. Its just a visual thing, not breaking anything, since I am leaving the screen anyway.

**Comment by Jalson1982** [comment]
Yes it does not break but it looks strange and bad from UX perspective!

**Comment by WoLewicki** [comment]
Does this issue still exist with Expo SDK 38?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
