### ISSUE TITLE
Unexpected token error while using react-native-web

### ISSUE THREAD

**Issue by Mukhammadali** [software-mansion/react-native-screens#492]
I am facing this problem while integrating react-native-web. Is there any solution for this?

<img width="730" alt="Screen Shot 2020-05-05 at 11 21 47 AM" src="https://user-images.githubusercontent.com/22298895/81040005-dc0fa080-8ec3-11ea-8613-c209aa434eea.png">

**Comment by WoLewicki** [comment]
Can you check if applying #510 fixes the problem?

**Comment by quangvinh2080** [comment]
@WoLewicki I'm still having this problem when using it with react-native-web

```
./node_modules/react-native-screens/src/screens.web.js
SyntaxError: ./node_modules/react-native-screens/src/screens.web.js: Unexpected token (19:6)

  17 | 
  18 |     return (
> 19 |       <View
     |       ^
  20 |         style={[style, ENABLE_SCREENS && !active ? { display: 'none' } : null]}
  21 |         {...rest}
  22 |       />
```

**Comment by WoLewicki** [comment]
It should work ok after #517 is merged.
