### ISSUE TITLE
UX feat: Make gesture back distance adjustable

### ISSUE THREAD

**Issue by Hirbod** [software-mansion/react-native-screens#503]
There is currently no way to increase the distance where a user can swipe to go back. It has to be super close on the left side in order to work. It would be nice if we could set a much higher distance for this, so people with single hand usage on big screens can swipe too. 

If you take instagram as example, it works on the full screen.

**Comment by wong2** [comment]
We are in desperate need of this!

**Comment by Hirbod** [comment]
And additionally: support swipe to pop also on Android, since gestures getting common on Android too

**Comment by WoLewicki** [comment]
Isn't it a duplicate of #251?

**Comment by Hirbod** [comment]
True.
