### ISSUE TITLE
[Android] When there are multiple Stack navigators in a Tab navigator, only one Stack navigator is rendered

### ISSUE THREAD

**Issue by jtomaszewski** [software-mansion/react-native-screens#507]
We use both `@react-navigation/material-top-tabs` and `@react-navigation/stack` in such a way that:

- the app at root uses `@react-navigation/material-top-tabs` navigator created with `createMaterialTopTabNavigator()`
- then, each tab may consist of its own' `Stack.Navigator` created with `createStackNavigator()`

Problem is, that after adding `enableScreens()`, the following bug appears **only on Android**:

- only one of the stack navigators in the tabs is rendered
- all the other tabs render blank white content

If `enableScreens()` is removed, then everything works on Android flawlessly.

What's annoying, that I can't find any errors in the react/expo console. So I don't really know how to start with fixing this issue.

However, I managed to set up a repro example: https://snack.expo.io/@jack-ailo/react-navigation-material-stack-android-bug-repro .

**Comment by WoLewicki** [comment]
Do you have the newest version of `RNScreens`? I copied the snack and it works just ok on Android.

**Comment by jtomaszewski** [comment]
Yeah. 2.7.0 , just as the snack references in package.json . Here's the video from my Android (Xiaomi Mi 9 SE):

https://www.dropbox.com/s/z7lp93mds43w8zy/WhatsApp%20Video%202020-05-14%20at%2009.35.17.mp4?dl=0

**Comment by WoLewicki** [comment]
Oh, you are using Expo Client. It has the native code of RNScreens of v. 2.2.0 compiled inside it, iirc. So the bug still exists there. Using v. 2.7.0 can only change JS code of the library. So you either have to wait for the SDK38 of Expo, which should be here in about a month, or use bare workflow. Does it fix your issue?

**Comment by jtomaszewski** [comment]
Oh, that explains a lot. We like using Expo client a lot, so I guess we'll just disable this plugin for now, and wait for SDK 38.

Maybe it could have been noted in README (that there's such an issue for android on SDK 37), but I guess our usage of navigators is a rare case... and now that I've created this issue, hopefully other people which encounter this bug will find this GH issue with a quick google search.

So I guess we can close it for now, yeah.
