### ISSUE TITLE
ERROR: Failed to resolve: androidx.cardview:cardview:1.1.0

### ISSUE THREAD

**Issue by Bageerapm** [software-mansion/react-native-screens#509]
Error

ERROR: Failed to resolve: androidx.cardview:cardview:1.1.0
Show in Project Structure dialog
Affected Modules: app

**Comment by WoLewicki** [comment]
Did you try this solution? https://github.com/software-mansion/react-native-screens/issues/452#issuecomment-610512829

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
