### ISSUE TITLE
Faild to run android after npm install react-native-screens

### ISSUE THREAD

**Issue by AnasAlsaadi** [software-mansion/react-native-screens#514]
`* What went wrong:
Execution failed for task ':react-native-screens:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-screens:debugRuntimeClasspath'.
   > Could not find material-1.1.0.aar (com.google.android.material:material:1.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/google/android/material/material/1.1.0/material-1.1.0.aar
   > Could not find viewpager2-1.0.0.aar (androidx.viewpager2:viewpager2:1.0.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/viewpager2/viewpager2/1.0.0/viewpager2-1.0.0.aar
   > Could not find fragment-1.2.1.aar (androidx.fragment:fragment:1.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.2.1/fragment-1.2.1.aar
   > Could not find fragment-1.2.1.aar (androidx.fragment:fragment:1.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.2.1/fragment-1.2.1.aar
   > Could not find fragment-1.2.1.aar (androidx.fragment:fragment:1.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.2.1/fragment-1.2.1.aar
   > Could not find fragment-1.2.1.aar (androidx.fragment:fragment:1.2.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.2.1/fragment-1.2.1.aar
   > Could not find coordinatorlayout-1.1.0.aar (androidx.coordinatorlayout:coordinatorlayout:1.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/coordinatorlayout/coordinatorlayout/1.1.0/coordinatorlayout-1.1.0.aar
   > Could not find coordinatorlayout-1.1.0.aar (androidx.coordinatorlayout:coordinatorlayout:1.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/coordinatorlayout/coordinatorlayout/1.1.0/coordinatorlayout-1.1.0.aar
   > Could not find activity-1.1.0.aar (androidx.activity:activity:1.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/activity/activity/1.1.0/activity-1.1.0.aar
   > Could not find transition-1.2.0.aar (androidx.transition:transition:1.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/transition/transition/1.2.0/transition-1.2.0.aar
   > Could not find lifecycle-viewmodel-savedstate-2.2.0.aar (androidx.lifecycle:lifecycle-viewmodel-savedstate:2.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-viewmodel-savedstate/2.2.0/lifecycle-viewmodel-savedstate-2.2.0.aar
   > Could not find lifecycle-viewmodel-savedstate-2.2.0.aar (androidx.lifecycle:lifecycle-viewmodel-savedstate:2.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-viewmodel-savedstate/2.2.0/lifecycle-viewmodel-savedstate-2.2.0.aar
   > Could not find lifecycle-viewmodel-2.2.0.aar (androidx.lifecycle:lifecycle-viewmodel:2.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-viewmodel/2.2.0/lifecycle-viewmodel-2.2.0.aar
   > Could not find lifecycle-viewmodel-2.2.0.aar (androidx.lifecycle:lifecycle-viewmodel:2.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-viewmodel/2.2.0/lifecycle-viewmodel-2.2.0.aar
   > Could not find lifecycle-viewmodel-2.2.0.aar (androidx.lifecycle:lifecycle-viewmodel:2.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-viewmodel/2.2.0/lifecycle-viewmodel-2.2.0.aar
   > Could not find lifecycle-viewmodel-2.2.0.aar (androidx.lifecycle:lifecycle-viewmodel:2.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-viewmodel/2.2.0/lifecycle-viewmodel-2.2.0.aar
   > Could not find lifecycle-runtime-2.2.0.aar (androidx.lifecycle:lifecycle-runtime:2.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-runtime/2.2.0/lifecycle-runtime-2.2.0.aar
   > Could not find lifecycle-runtime-2.2.0.aar (androidx.lifecycle:lifecycle-runtime:2.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-runtime/2.2.0/lifecycle-runtime-2.2.0.aar
   > Could not find lifecycle-runtime-2.2.0.aar (androidx.lifecycle:lifecycle-runtime:2.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-runtime/2.2.0/lifecycle-runtime-2.2.0.aar
   > Could not find lifecycle-livedata-core-2.2.0.aar (androidx.lifecycle:lifecycle-livedata-core:2.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-livedata-core/2.2.0/lifecycle-livedata-core-2.2.0.aar
   > Could not find lifecycle-livedata-core-2.2.0.aar (androidx.lifecycle:lifecycle-livedata-core:2.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-livedata-core/2.2.0/lifecycle-livedata-core-2.2.0.aar
   > Could not find lifecycle-livedata-core-2.2.0.aar (androidx.lifecycle:lifecycle-livedata-core:2.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-livedata-core/2.2.0/lifecycle-livedata-core-2.2.0.aar
   > Could not find core-runtime-2.1.0.aar (androidx.arch.core:core-runtime:2.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/arch/core/core-runtime/2.1.0/core-runtime-2.1.0.aar
   > Could not find core-runtime-2.1.0.aar (androidx.arch.core:core-runtime:2.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/arch/core/core-runtime/2.1.0/core-runtime-2.1.0.aar

`

I have error when try this:
1- npm install react-native-screens
2- react-native link react-native-screens
3- react-native run-android

PLEASE ANY HELP !!

**Comment by WoLewicki** [comment]
What version of `react-native` are you using?

**Comment by AnasAlsaadi** [comment]
@WoLewicki  0.62

**Comment by WoLewicki** [comment]
So it is not needed to use `react-native link`. It should be enough to add the library via npm/yarn and then just build the project. Can you check?

**Comment by AnasAlsaadi** [comment]
@WoLewicki 

it is working now after try another solution and spent alot of time

girdle version should be ; 

**classpath 'com.android.tools.build:gradle:3.4.2'**

in waraper :

**distributionUrl=https\://services.gradle.org/distributions/gradle-5.5-all.zip**

react-native-screen/android/build.gridle

**implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-beta01'**


after all changes working fine !

**Comment by WoLewicki** [comment]
Ok so I am closing it then. Feel free to comment if you have any questions.

**Comment by MursiDirect** [comment]
still have the same issue, any help please ? 
what i get while trying to run the andoid app "react-native run-android"


`Execution failed for task ':react-native-screens:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-screens:debugCompileClasspath'.
   > Failed to transform appcompat-1.1.0.aar (androidx.appcompat:appcompat:1.1.0) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for ExtractAarTransform: C:\Users\Mohammed\.gradle\caches\modules-2\files-2.1\androidx.appcompat\appcompat\1.1.0\351d3409fe51f3d862bd2b1bcc0f3b6ded29460e\appcompat-1.1.0.aar.
         > Cannot parse result path string:
   > Failed to transform appcompat-1.1.0.aar (androidx.appcompat:appcompat:1.1.0) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.status=release}.
      > Execution failed for ExtractAarTransform: C:\Users\Mohammed\.gradle\caches\modules-2\files-2.1\androidx.appcompat\appcompat\1.1.0\351d3409fe51f3d862bd2b1bcc0f3b6ded29460e\appcompat-1.1.0.aar.
         > Cannot parse result path string:
   > Failed to transform viewpager2-1.0.0.aar (androidx.viewpager2:viewpager2:1.0.0) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.status=release}.
      > Execution failed for LibrarySymbolTableTransform: C:\Users\Mohammed\.gradle\caches\transforms-2\files-2.1\7890bc1915851051324e46f63878a44f\jetified-viewpager2-1.0.0.
         > Cannot parse result path string:
`
