### ISSUE TITLE
Large Header with Custom Component Getting Cut Off

### ISSUE THREAD

**Issue by cmrigney** [software-mansion/react-native-screens#532]
I'm using `createNativeStackNavigator()` and providing my own `headerCenter` component that is taller than the default iOS header height. I'm trying to use `headerLargeTitle` so it fits. The problem is, my component won't render any taller than the non-large height. It appears that the large header title is cutting it off, even though I'm making the title transparent. However, when I navigate, it shows the component correctly very briefly. It might be worth noting that in the non-native `createStackNavigator()` this works fine.

I am using the following options to get this effect:
```
{
  title: 'Feed',
  headerLargeTitle: true,
  headerTitleStyle: {
    color: 'transparent',
  },
  headerCenter: () => (
    <CallHeader
      displayName="Bob"
      trulyNumber="+13305551234"
    />
  ),
}
```

**Comment by cmrigney** [comment]
Here is an example of what I'm referring to.

![357CE0E0-110A-4FB0-8FAE-55F315DE924E-91494-0003A9249358E86F](https://user-images.githubusercontent.com/3259448/83884926-9d177980-a713-11ea-8070-13f395bda1b9.gif)

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue? I cannot repro the cutting in the view.

**Comment by cmrigney** [comment]
To repro

1) Use `create-react-native-app` to create an app
2) Add `@react-navigation/native` and `react-native-screens` to `package.json`
3) Replace App.js with the following code

```
import * as React from "react";
import { Platform, StyleSheet, Text, View, Button } from "react-native";
import { enableScreens } from "react-native-screens";
import { NavigationContainer, useNavigation } from "@react-navigation/native";

enableScreens();

const instructions = Platform.select({
  ios: `Press Cmd+R to reload,\nCmd+D or shake for dev menu`,
  android: `Double tap R on your keyboard to reload,\nShake or press menu button for dev menu`,
});

import { createNativeStackNavigator } from "react-native-screens/native-stack";

const Stack = createNativeStackNavigator();

export default function Root() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Test" component={App} options={{
          headerCenter: () => <Circle />,
          headerLargeTitle: true,
          headerTitleStyle: {
            color: 'transparent'
          }
        }} />
        <Stack.Screen name="Test2" component={App2} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

function App() {
  const navigation = useNavigation()
  return (
    <View style={styles.container}>
      <Button title="Test" onPress={() => navigation.navigate('Test2')} />
      <Text style={styles.welcome}>Welcome to React Native!</Text>
      <Text style={styles.instructions}>To get started, edit App.js</Text>
      <Text style={styles.instructions}>{instructions}</Text>
    </View>
  );
}

function App2() {
  const navigation = useNavigation()
  return (
    <View style={styles.container}>
      <Button title="Test2" onPress={() => navigation.navigate('Test')} />
      <Text style={styles.welcome}>Welcome to React Native!</Text>
      <Text style={styles.instructions}>To get started, edit App.js</Text>
      <Text style={styles.instructions}>{instructions}</Text>
    </View>
  );
}

function Circle() {
  return <View style={styles.circle} />
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF",
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10,
  },
  instructions: {
    textAlign: "center",
    color: "#333333",
    marginBottom: 5,
  },
  circle: {
    backgroundColor: '#ff0000',
    borderRadius: 32,
    height: 64,
    width: 64,
  }
});

```

**Comment by eyecandydotdev** [comment]
Seems to me that you are mixing the two libraries in an unexpected way. There's https://reactnavigation.org/ and there's this one here https://github.com/software-mansion/react-native-screens

**Comment by WoLewicki** [comment]
I checked on a native iOS project and the `titleView` that is used when the `headerCenter` is set automatically to clip to bounds so I think it is desired behavior which Apple HIG suggests. 
![image](https://user-images.githubusercontent.com/32481228/85054038-bd2b4c00-b19b-11ea-9c6a-f77ae4cde2cb.png) 
(You can see even though height is 200, it is still truncated)
The first time it is outside of the view probably because of this: https://stackoverflow.com/questions/47121427/make-navigationbars-titleview-larger-than-itself

**Comment by WoLewicki** [comment]
Can I somehow help you more with it or can I close this issue?

**Comment by cmrigney** [comment]
@WoLewicki Thanks for investigating this. We decided to use the non-native stack navigator to get the features we need. This can be closed.
