### ISSUE TITLE
'React/RCTImageView.h' file not found | iOS Build Failed

### ISSUE THREAD

**Issue by z937010871** [software-mansion/react-native-screens#533]
"react-native-screens": "^2.7.0",
    "react-native": "0.59.5",

**Comment by z937010871** [comment]
> ```
> "react-native-screens": "^2.7.0",
> "react-native": "0.59.5",
> ```

help~

**Comment by WoLewicki** [comment]
I believe it is the same issue as #415, so I will close this one. Feel free to comment if I am wrong.
