### ISSUE TITLE
[BUG] Cannot set stack animation to none.

### ISSUE THREAD

**Issue by 378978764** [software-mansion/react-native-screens#534]
When setting `stackAnimation` to `none`, it still uses `fade`.
Android version: MIUI 11 based on Android X.

BTW, how can I use the same transition animation across different platforms? For example, use `slide from right` in Android?

**Comment by WoLewicki** [comment]
Can you provide a repo with minimal configuration needed to reproduce the fade animation when set to none?
The second issue is discussed in #489.

**Comment by 378978764** [comment]
> Can you provide a repo with minimal configuration needed to reproduce the fade animation when set to none?
> The second issue is discussed in #489.

Just `ignite new myApp`, and then choose `bowser`.

**Comment by WoLewicki** [comment]
It works just fine in my example. Please provide a repo/snack where it is not working.

**Comment by 378978764** [comment]
> It works just fine in my example. Please provide a repo/snack where it is not working.

Ok, I posted one [here](https://github.com/378978764/TestAnimationNone).

**Comment by WoLewicki** [comment]
The example is too big to quickly debug why the animation is like that. It is probably some custom animation and setting the `stackAnimation` doesn't change anything. Can you provide a repro without all the boilerplate?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Comment by Administaror** [comment]
Me,too

**Comment by WoLewicki** [comment]
@Administaror please submit a repo with a minimal configuration that shows the issue so I can confirm there is a bug.

**Comment by Administaror** [comment]
Im Buged!!
