### ISSUE TITLE
transparentModal covers up Toasts, warning messages, etc

### ISSUE THREAD

**Issue by Aryk** [software-mansion/react-native-screens#535]
I use the transparentModal quite often in my app because I like the screen to come up from the bottom in certain places. I don't like to use "modal" because I like it to come all the way to the top and not stop 85% of the way.

After months of development I constantly hit problems with rendering Toast in a transparentModal, even if I put <Root> inside the Stack Navigator. It also hides warning messages. I've tried Toast with native-base and toast with react-native-tiny-toast, can't get either to work inside transparentModal.

Maybe someone can point me in the right direction. How can I get navigators natively to come up from the bottom (all the way to the top) *without* the headaches I get with transparentModal?

I ultimately just want native, simple screen transitions, nothing fancy, but I find myself spending a lot of time trying to hack my way around transparentModal's all-or-nothing behavior where it simply covers literally everything...

Maybe there is a different way to achieve screens transitioning in from the bottom?

I'm using Expo 37 with react-native-screens 2.8.0.

**Comment by Hirbod** [comment]
When you use Expo you use v2.2.0 and not 2.8.0

**Comment by Hirbod** [comment]
It does not solve the issue, I just wanted to make sure you understand that installing 2.8.0 on expo won’t give you 2.8.0 but only 2.2.0 since expo bundles native codes with SDK releases and you are stuck to the delivered version till a new SDK comes out

**Comment by Hirbod** [comment]
No, I have the same issue and it’s already reported couple of times.

**Comment by Aryk** [comment]
I did a few searches and nothing came up. What's the official thread on this so I can follow it?

**Comment by WoLewicki** [comment]
@Aryk I believe it is #525. Can I close this issue to keep the discussion in one place then?

**Comment by WoLewicki** [comment]
Closing this in order to keep the discussion in one place (#525).
