### ISSUE TITLE
react-native-screens  react-native-webview

### ISSUE THREAD

**Issue by tanjiaweiGitHub** [software-mansion/react-native-screens#546]

**Comment by tanjiaweiGitHub** [comment]
复现环境：  reactnative0.61.5

**Comment by tanjiaweiGitHub** [comment]
## 复现环境
1.  "react-native-screens": "^2.8.0",
2. "react-navigation": "^4.1.0",
3.  "react-native-webview": "^9.3.0"
4.  "react-native": "0.61.5",
5. 安卓9/安卓10

**Comment by WoLewicki** [comment]
Please write in English otherwise I won't be able to understand you.

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
