### ISSUE TITLE
2.9.0 breaks importing from "react-native-screens/native-stack/xxx"

### ISSUE THREAD

**Issue by stackia** [software-mansion/react-native-screens#547]
Before 2.9.0, I can use `import HeaderConfig from "react-native-screens/native-stack/views/HeaderConfig"` but now this should be `import HeaderConfig from "react-native-screens/lib/module/native-stack/views/HeaderConfig"`. TypeScript can no longer resolve the corresponding .d.ts in such cases.

FYI our scenario is to rewrite some of native-stack's logic to bring `react-native-modalize` to react-navigation. After upgrading to 2.9.0, it's not that easy to reuse the existing code of `native-stack` in TypeScript files.

**Comment by satya164** [comment]
These files are internal and not supposed to be used by external code. So there's no guarantee that what you're doing will continue to work in a patch version. So `.d.ts` not getting resolved is least of the problems, we could entirely remove this file in a patch version and your code will break.

If you want to customize such code, you should copy these files into your project and change them as you need.
