### ISSUE TITLE
react-native-photoeditorsdk and react-native-screens

### ISSUE THREAD

**Issue by ZaikinaEvgeniya-2** [software-mansion/react-native-screens#548]
If use this library `react-native-photoeditorsdk`, demo https://github.com/imgly/pesdk-react-native-demo
and add `react-native-screens` to this project, then get error
![Screenshot_2020-06-23-16-45-09](https://user-images.githubusercontent.com/62234691/85919354-174ea000-b873-11ea-8c7b-b73d9d4d4b00.png)

run on real android 5.1

may be I missed some steps for install `react-native-screens`,
I just yarn add `react-native-screens`

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by ZaikinaEvgeniya-2** [comment]
sorry for not responding for a long time, 
project: https://github.com/ZaikinaEvgeniya-2/pesdk-react-native-demo
when start it click on `Click here to edit a sample image` - and get this error

may be i missed some steps when install react-native-screens
my steps:
1) `https://github.com/imgly/pesdk-react-native-demo` start it, click on `Click here to edit a sample image` - everything work fine,
2)  I fork this demo and `yarn add react-native-screens` - start it, click on `Click here to edit a sample image` and get this error

**Comment by ZaikinaEvgeniya-2** [comment]
I can not repeate this issue with android with higer version, so I think it is because android 5 invoke this error.
