### ISSUE TITLE
White flicker when navigating back

### ISSUE THREAD

**Issue by sa8ab** [software-mansion/react-native-screens#549]
First of all thank you for the great lib.
the problem is that when I am navigating to or back in the stack navigator I see a white flicker in the edges, I also had the issue when using @react-navigation/stack with `enableScreens()`.

here is the screen record:
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/59901734/85929833-cf2c7f00-b86c-11ea-971c-8ac4a9a81c9a.gif)

# versions:
"@react-navigation/native": "^5.6.1",
"react-native-screens": "^2.9.0"

**Comment by beqramo** [comment]
duplication of #111

**Comment by WoLewicki** [comment]
Yes, it is most probably as @beqramo says. I am closing it then. Feel free to comment if I am wrong.
