### ISSUE TITLE
Native Stack, React-nativation 5, white screen when navigating back

### ISSUE THREAD

**Issue by sa8ab** [software-mansion/react-native-screens#556]
When navigating forward and back using back button in the header, sometimes ( like after 3, 4 ) times of navigating the first screen becomes white ( as it appears ).

Happens on Android not tested on IOS

# how to reproduce
create a native stack navigator using react navigation and move forward and back by pressing the back button in the header.

![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/59901734/86592009-7aad9180-bf47-11ea-93a1-bd7d26edbbc4.gif)

**Comment by WoLewicki** [comment]
I cannot repro this. Can you provide a repo where this happens?

**Comment by sa8ab** [comment]
@WoLewicki here is the repo. I made it for Reanimated but I noticed this one as well, so don't mind the name.

[https://github.com/sa8ab/reproducing-reanimated-issue](https://github.com/sa8ab/reproducing-reanimated-issue)

**Comment by beqramo** [comment]
I face same issue on ``` "react-navigation": "^4.4.0"  ``` 

@WoLewicki

**Comment by WoLewicki** [comment]
Yes, I have managed to reproduce it.

**Comment by WoLewicki** [comment]
@beqramo did you manage to make this bug appear every time, not randomly? It would be very helpful for debugging.

**Comment by beqramo** [comment]
@WoLewicki  I have any clue when it happens sorry

**Comment by WoLewicki** [comment]
I am getting such an Error in Logcat of Android Studio when this bug happens: 
![image](https://user-images.githubusercontent.com/32481228/86606472-58982b80-bfa8-11ea-8222-90bd979f41f6.png)
Can someone spot the same thing? Looks like it is the source of the problem.

**Comment by sa8ab** [comment]
@WoLewicki It happens sometimes on navigating back for the second time, sometimes takes longer, as if you notice the screen recording it happened after 20 seconds or so.

**Comment by WoLewicki** [comment]
https://github.com/software-mansion/react-native-screens/issues/556#issuecomment-654283994
I debugged it more and this Error is not connected strictly to the bug. It just appears when you click on an empty `View`.

**Comment by WoLewicki** [comment]
Can you try and change https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java#L189 to `mCurrentTransaction.commitNowAllowingStateLoss();` and see if there are any regressions and if the bug does disappear? Also, could you provide a repo for the #309 since I cannot repro it in release build?

**Comment by sa8ab** [comment]
I changed the following line from node_modules and rebuilt the project as the result the bug seemed to be disappeared ( I couldn't face the white screen on navigating multiple times for 20 seconds or so ). plus the transition had changed a bit as well. here is the screen recording.
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/59901734/87037446-12f28300-c1a1-11ea-8fc4-4d89c39b87c9.gif)

should I test in release built as well? @WoLewicki 

Should I

**Comment by WoLewicki** [comment]
I would be grateful if you could.

**Comment by chismadalina** [comment]
It happens for me as well with React Navigation 5 and screens enabled.

**Comment by WoLewicki** [comment]
@chismadalina does it happen after applying this: https://github.com/software-mansion/react-native-screens/issues/556#issuecomment-656044339? And are there any other issues after doing so?

**Comment by chismadalina** [comment]
> @chismadalina does it happen after applying this: [#556 (comment)](https://github.com/software-mansion/react-native-screens/issues/556#issuecomment-656044339)? And are there any other issues after doing so?

@WoLewicki it does fix the issue when navigation back but then I have a white flicker when I enter the screen, only on some screens.

**Comment by WoLewicki** [comment]
Can you provide minimal code that shows the flickering after that change?

**Comment by chismadalina** [comment]
@WoLewicki I don't think the code of the screen will help as it happens in different screens

**Comment by sa8ab** [comment]
@chrisnojima does it happen only on the first screen?
I mean like you go from Screen1 to Screen2 and you see the white flicker, but when going from Screen2 to Screen3 there is no flicker.

**Comment by awinograd** [comment]
https://github.com/software-mansion/react-native-screens/issues/556#issuecomment-656044339 fixed a similar bug for me that was showing only in release builds. 

navigating from A -> push B -> goBack to A -> push B would sometimes cause B to show with opacity < 1.

**Comment by awinograd** [comment]
One of our testers reported a re-occurrence of this bug after the fix mentioned above. At least, the issue appears to be much less common

**Comment by awinograd** [comment]
One more note from me and sorry for the noise. It looks like my issue wasn't related to react-native-screens at all, but rather LayoutAnimation on android

**Comment by ahmed5605** [comment]
Can someone let me know what worked for them?

**Comment by WoLewicki** [comment]
@ahmed5605 you can try and change the line to `mCurrentTransaction.commitNowAllowingStateLoss();` here: https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java#L219

**Comment by gazedash** [comment]
> Native Stack, React-nativation 5, white screen when navigating back

in fact, in my case, it crashes with fatal exception about react-native-screens, but looks like a freeze with white background, exactly as described

**Comment by WoLewicki** [comment]
@gazedash can you provide a reproduction of this? It would help with debugging.

**Comment by ZeiRashed** [comment]
Still seeing repros of this issue. The line switch above didn't fix the issue for me - has anyone found a fix?

**Comment by iagormoraes** [comment]
The flickering is still happening with the components like fast-image and svg when we call `goBack()`.

https://user-images.githubusercontent.com/13892132/105480810-f9b8ac00-5c84-11eb-92c6-6b4e1462daa1.mov

**Comment by darron1217** [comment]
In my case, map becomes empty when calling `navigation.goBack()`.
But it's fine with touching back button on header.

**Comment by WoLewicki** [comment]
@darron1217 I think your problem is described in #773.

**Comment by darron1217** [comment]
@WoLewicki Sorry, it was map plugin's problem.
I appreciate for your help :)

**Comment by ZeiRashed** [comment]
@WoLewicki Do you happen to know if the issue with crashing/white screens when going back is being tracked?

**Comment by WoLewicki** [comment]
Unfortunately we didn't come up with a better solution than proposed yet, but we are open to suggestions.

**Comment by jslok** [comment]
Recent version 3.4.0 of react-native-screens seems to have solved this issue for me.

**Comment by jslok** [comment]
This seems to have fixed the white screen issue on goBack but the navigation animation is different now. It's more like a partial swoop in from the left.

**Comment by qara0001** [comment]
> I changed the following line from node_modules and rebuilt the project as the result the bug seemed to be disappeared ( I couldn't face the white screen on navigating multiple times for 20 seconds or so ). plus the transition had changed a bit as well. here is the screen recording. ![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/59901734/87037446-12f28300-c1a1-11ea-8fc4-4d89c39b87c9.gif) [ ![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/59901734/87037446-12f28300-c1a1-11ea-8fc4-4d89c39b87c9.gif) ](https://user-images.githubusercontent.com/59901734/87037446-12f28300-c1a1-11ea-8fc4-4d89c39b87c9.gif) [ ](https://user-images.githubusercontent.com/59901734/87037446-12f28300-c1a1-11ea-8fc4-4d89c39b87c9.gif)
> 
> Should I test in release build as well? [@WoLewicki](https://github.com/WoLewicki)

can you help this problem to fix ?
