### ISSUE TITLE
[!] The platform of the target `RNMacOS5-macOS` (macOS 10.14) is not compatible with `RNScreens (2.9.0)`, which does not support `macOS`.

### ISSUE THREAD

**Issue by Mustafax06** [software-mansion/react-native-screens#557]
Hello, I'm building a macOS app and I'm simply trying to open a new screen in my app. I've installed the necessary libraries like react-navigation, react-native-safe-area-context, react-native-gesture-handler etc. I need to install the pods but I'm constantly getting this error: `[!] The platform of the target 'RNMacOS5-macOS' (macOS 10.14) is not compatible with 'RNScreens (2.9.0)', which does not support 'macOS'.`. I also got a few errors too like this one from my other installed libraries. Does anyone would suggest me anything that helps to fix this issue.

Thanks a lot.

**Comment by WoLewicki** [comment]
`RNScreens` does not support macOS for now and neither does `react-navigation`. You can try and apply patches to `react-navigation` to eliminate the code including `RNScreens` because it is not a necessary component of that library, but it is not the scope of `RNScreens`. I think many other libraries are just not supporting this platform so there is no easy way to integrate it on this stage of work. Can I close this issue then?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Comment by cawfree** [comment]
Just to confirm this `react-native-screens` is now supported on MacOS via `@react-navigation/stack` as of [5.9.0](https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fstack%405.9.0).

It requires that you use `react-native-screens@2.10.1` as a dependency and not the latest version.

**Comment by tangten** [comment]
hi @cawfree , I can not see animation when navigate to other screens, are you sure rn-screens is working well with macOS?

**Comment by stanislav-sidorov-empeek** [comment]
all I need is to use @react-navigation/stack instead of @react-navigation/native-stack

import {createStackNavigator} from '@react-navigation/stack';
const NavigationStack = createStackNavigator();
