### ISSUE TITLE
[native-stack] stackPresentation not working on Android

### ISSUE THREAD

**Issue by ARDcode** [software-mansion/react-native-screens#558]
stackPresentation: 'modal' and etc not working on Android on RN 0.62.2.
react-navigation and rn-screen are last version
iOS is work perfect.
```
const Stack = createNativeStackNavigator();

export default () => {
  return (
    <Stack.Navigator
      screenOptions={{
        headerShown: false,
      }}
    >
      <Stack.Screen name={Screens.COURSE_LIST} component={CourseListScreen} />
      <Stack.Screen name={Screens.COURSE_PAGE} options={{ stackPresentation: 'modal' }} component={CoursePage} />
    </Stack.Navigator>
  );
};
```

**Comment by WoLewicki** [comment]
What do you mean by not working? What would you expect from it?

**Comment by ARDcode** [comment]
> What do you mean by not working? What would you expect from it? Android does not define anything similar to iOS modal views. Correct me if I am wrong.

Android modal is should not be fullscreen? 
All props are not work: stackPresentation, stackAnimation

**Comment by WoLewicki** [comment]
Maybe you are not using them correctly? Please create a repo/snack where it does not work so I can help you.

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Comment by AkshayAdiga1997** [comment]
The modal effect in android is different from IOS. In android, it's subtle faded modal. But when I set `stackPresentation:'modal'`. I do not see that effect. Pl reopen the issue. Thanks.

**Comment by AkshayAdiga1997** [comment]
> I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

The modal effect in android is different from IOS. In android, it's subtle faded modal. But when I set `stackPresentation:'modal'`. I do not see that effect. Pl reopen the issue. Thanks.

**Comment by WoLewicki** [comment]
On Android, the only different presentation than the `push` is `transparentModal`, which makes the previous screen stay behind the newly pushed screen. You can see it e.g. here: https://github.com/software-mansion/react-native-screens/pull/658#issuecomment-761223274
