### ISSUE TITLE
Jumpdown ScrollView with auto insets on BottomTab inside NativeStack

### ISSUE THREAD

**Issue by SDSLeon** [software-mansion/react-native-screens#564]
related issue in react-navigation was closed so I open it here

**Current Behavior**

ScrollView with contentInsetAdjustmentBehavior="automatic" initialy render under translucent header and after stack animation jumps down; 

GIF: [url](https://storage.de.cloud.ovh.net/v1/AUTH_b2cffe8f45324c2bba39e8db1aedb58f/cloudconvert-files/87d0b94d-9da2-417d-837a-5ad54414fe58/Запись%20экрана%202020-07-13%20в%2015.35.56.gif?temp_url_sig=0998bd7d02e92abf5590769b1d8ef8edcac63104&temp_url_expires=1594731587)

**Expected Behavior**

ScrollView with contentInsetAdjustmentBehavior="automatic" initialy render on bottom of header; 

**How to reproduce**
Example: https://github.com/SDSLeon/nativeStackPlusTabTranslucentScroll

after some time of investigation:
1. Problem is when bottomTabsNavigation uses react-native-screens to render tab content
![image](https://user-images.githubusercontent.com/6071034/87339550-72f57a80-c54f-11ea-9abf-ed44ae56660e.png)
 

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS                | all versions
| @react-navigation/native      | 5.7.0
| @react-navigation/bottom-tabs | 5.7.0
| react-native-screens          | 2.9.0
| react-native                  | 0.63.0
| expo                          |
| node                          | 13.11
| npm or yarn                   | yarn 1.22.4

**Comment by WoLewicki** [comment]
Can you check if #1029 resolves your issues and does not introduce new ones? It requires applying PR from `react-navigation` for it to work: https://github.com/react-navigation/react-navigation/pull/9772.
