### ISSUE TITLE
Is it possible to have a different backgroundColor for the collapsed header when using largeTitle on iOS?

### ISSUE THREAD

**Issue by davitykale** [software-mansion/react-native-screens#565]
I'm only aware of how to set `headerTranslucent` and the `backgroundColor` for the entire header (both the extended, large title version as well as the collapsed smaller title).

Is it possible to do something like this:
![RPReplay_Final1594693843](https://user-images.githubusercontent.com/4770980/87375362-3169cd00-c559-11ea-8c5f-b13aa9bcaa0a.gif)

Specifically where the largeTitle is translucent (or at least has a different background color) than the collapsed header?

**Comment by WoLewicki** [comment]
You can do something like this: 
```
         headerLargeStyle: {
            backgroundColor: 'red',
          },
          headerStyle: {
            backgroundColor: 'yellow',
          },
```
You can see more info about the transitions between colours in #524. Does it solve your issue?

**Comment by davitykale** [comment]
@WoLewicki ah, that does seem to work for the most part!

Is it possible to hide the border at the bottom of the large title header? I'm trying to style it from `headerLargeStyle` and not able to.

![Screen Shot 2020-07-14 at 8 08 31 PM](https://user-images.githubusercontent.com/4770980/87488239-db0a9600-c60d-11ea-9c72-8e7aa8597c31.png)

**Comment by WoLewicki** [comment]
You should use `headerLargeTitleHideShadow: true`.

**Comment by WoLewicki** [comment]
Is your issue solved, and if so, can I close it?

**Comment by davitykale** [comment]
Yes! Please close. Thank you so much!
Cosma Damiano Trimboli <notifications@github.com> wrote:
“Is your issue solved, and if so, can I close it?”

**Comment by Appkidd** [comment]
@WoLewicki Is there a recommended way of transitioning `largeHeaderStyle: { backgroundColor: 'transparent }` to `headerStyle: { backgroundColor: 'white' }`? In our case, we have a background rendered behind the scene container. We're display this when the large title is in view, but would like to make it opaque once the user begins scrolling. Currently, when the `headerStyle` background is set to white, it stops the `largeHeaderStyle` from being transparent and renders opaque instead. It works fine in the example above when the colours are both opaque.

**Comment by Appkidd** [comment]
Worked around this using `navigation.setOptions` and FlatList's `onScroll` to swap between opaque/transparent on scroll. Will just tidy this up with a fade using Reanimated.

**Comment by WoLewicki** [comment]
I cannot help much about it unfortunately, we are using native behaviors for setting those values, so they should work just like it would in a native `iOS` app.
