### ISSUE TITLE
initialRouteName behaving odd

### ISSUE THREAD

**Issue by dakkafex** [software-mansion/react-native-screens#567]
so for some reason with this setup, the app will always render the ``SignIn`` screen, no matter what i put in "initialRouteName".
Only when i change the screen name of ``SignIn``  ``initialRouteName`` starts behaving like normal again.

what is going on here? is ``SignIn`` somekind of reserved name?

```ts
const EntryStack = createNativeStackNavigator<PrimaryParamList>()

export function EntryStackNavigator() {
  return (
    <EntryStack.Navigator
      initialRouteName="Loading"
      screenOptions={{
        headerShown: false,
        gestureEnabled: true,
      }}
    >
      <EntryStack.Screen name="Loading" component={LoginLoadingScreen} />
      <EntryStack.Screen name="forgotPassword" component={ForgotPassScreen} />
      <EntryStack.Screen name="betaKey" component={VerifyCodeScreen} />
      <EntryStack.Screen name="SignIn" component={SignInScreen} />
    </EntryStack.Navigator>
  )
}
```

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue? I tried it with simple components and all works OK.

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
