### ISSUE TITLE
Native Stack Navigator push with NativeStackNavigationOptions for createNativeStackNavigator?

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-screens#569]
From what I can see, dynamic titles / options aren't really possible out of the box.

Is it the case that this is out of scope for this library? I can understand that you don't want to delve into being a navigation library, however if that's the case I guess I don't understand why createNativeStackNavigator exists.

I guess the main work around for this is to have a custom headerCenter that uses some state management?

Please let me know if I'm miss-understanding something.

Edit: turns out I can do the following and trigger state changes from wherever I like, is there any performance defecit by setting state within a Navigator?

```
   <Stack.Screen
                            name={routes.home.name}
                            options={{
                              ...routes.home.options,
                                title: this.state.name
                            }}
/>
```

**Comment by WoLewicki** [comment]
I am not sure what is your problem. Could you describe more strictly the behavior you would like to achieve? You can check https://reactnavigation.org/docs/screen-options/#navigationsetoptions-method if it is what you need.

**Comment by kyle-ssg** [comment]
Sure, two scenarios:

From screen A I want to Push to screen b but make the new title "Screen b dynamic title", is it that I can just do 
```
  React.useLayoutEffect(() => {
    navigation.setOptions({
      title: value === '' ? 'No title' : value,
    });
  }, [navigation, value]);
```

**Comment by kyle-ssg** [comment]
Sorry I didnt realise it was this simple, setOptions in the constructor works great!
