### ISSUE TITLE
[iOS] HeaderCenter positioned to the right on initial screen

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-screens#571]
![image](https://user-images.githubusercontent.com/8608314/87939022-50072100-ca8f-11ea-9c50-cc14de1bc529.png)

Rendering an unstyled text element for headerCenter shows it is miss-aligned but only if the screen has no back button.

```
 const options: Partial<NativeStackNavigationOptions> = {
              headerCenter: ()=>    <ReactNative.Text>Loading</ReactNative.Text>,
        }
```

<img src="http://g.recordit.co/BcWpAzT9rU.gif"/>

Replicated on iOS simulator SE 2nd Edition

**Comment by WoLewicki** [comment]
It is probably the same issue as #432. There are problems with aligning header buttons on iOS and it seems like it is not too easy to resolve it.

**Comment by kyle-ssg** [comment]
Hmm I'm not 100% sure @WoLewicki, happy to trust judgment but this seems a little less random than the one mentioned there. This seems to be literally the centre view being padded left by the exact width of the back button?

**Comment by WoLewicki** [comment]
Yeah, if you put a simple View in the `headerCenter`, it will misaligned too. It is mentioned in a comment https://github.com/software-mansion/react-native-screens/issues/432#issuecomment-644639697.

**Comment by kyle-ssg** [comment]
Ah. This is quite a big issue then, should I close in favour of #432?
