### ISSUE TITLE
[Android] Render content behind transparent navigation bar

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-screens#573]
on iOS, when you set the background of the navbar to transparent, the content is able to be rendered behind the navbar.  

![image](https://user-images.githubusercontent.com/8608314/88090030-dfdac700-cb84-11ea-8e88-d59a83af4893.png)

Ideally, I'd like to have the ability to render content behind the navigation bar in android.

**Comment by kylsYw** [comment]
I have the same problem
