### ISSUE TITLE
[Android] Pushing to a new independent stack on android shows the back button

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-screens#576]
Pushing to the following independent navigation container, I'd expect the back button to be hidden as it's at the start of the stack. I can work around it at the moment by forcing headerHideBackButton, however this is a bit of a hack.

```
        <NavigationContainer independent>
            <Navigator screenOptions={defaultNavigationOptions} initialRouteName={RouteUrls.home}>
                <Stack.Screen
                  name={RouteUrls.home}
                  options={{...routes[RouteUrls.home].options, headerHideBackButton: true}}
                  component={routes[RouteUrls.home].component}
        />
                <Stack.Screen
                  name={RouteUrls.generic}
                  options={routes[RouteUrls.generic].options}
                  component={routes[RouteUrls.generic].component}
        />
                <Stack.Screen
                  name={RouteUrls.stack}
                  options={routes[RouteUrls.stack].options}
                  component={routes[RouteUrls.stack].component}
        />
            </Navigator>
        </NavigationContainer>
```

**Comment by WoLewicki** [comment]
In https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java#L189 you can change that if to `return ((ScreenStack) container).getRootScreen() != getScreen();` and comment the code below it. I will look at why it is implemented like that.

**Comment by kyle-ssg** [comment]
Thanks for looking at this, by the way I have to say so far this is an outstanding package! Glad so far to be transitioning away from react-native-navigation to this.

**Comment by WoLewicki** [comment]
There are many things to be implemented still but thanks for the kind words 🙂

**Comment by WoLewicki** [comment]
This code is needed for displaying the back button in "modal" screens on Android and it should stay like that (suggested by @kmagiera). Disabling back button on the screen is the recommended way of doing it then to keep the consistency between iOS and Android. Can I close this issue then?

**Comment by WoLewicki** [comment]
I am closing this issue since there is nothing more I can help you with regarding it. Feel free to comment if I am wrong.

**Comment by kyle-ssg** [comment]
Sorry missed this - Yep, after reconsidering I think that independent NavigationContainers have almost 0 usecases.

**Comment by WoLewicki** [comment]
Some inconsistencies will always arise from the fact that these are 2 different platforms and we are using native behavior for each of them.
