### ISSUE TITLE
Modal bugs out and reveals view behind when dragging down with gesture

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-screens#577]
### Description

I'm sorry for the title, but I couldn't find better words to describe this.

When using the native stack navigator to present a screen modally, the screen slides up like a `pageSheet` or `formSheet` on iOS. A users reaction might be sliding it back down, which is native behaviour for action sheets in iOS. The problem is, that the screen moves up and shows what's beneath it. 

The weird this is, I cannot reproduce this issue on my iPhone 11 simulator, but it happens **every** time on my real iPhone 11 Pro device.

### Demo

Here's a demo:

![t](https://user-images.githubusercontent.com/15199031/88532559-1beaad80-d005-11ea-9d23-3b22fca3d041.gif)

### Additional Info

For my `NativeStackNavigationOptions` in the Parent Stack navigator I am using:

```js
stackPresentation: 'modal',
gestureEnabled: false,
```

, and the child stack navigator (the screens inside the modal) have the following `NativeStackNavigationOptions`:

```js
headerShown: true,
headerStyle: {
	backgroundColor: Colors.current.identity,
},
headerTintColor: Colors.current.white,
headerTitleStyle: {
	color: Colors.current.white,
	fontSize: 20,
},
```

### Versions

`package.json`
```json
...
"react": "16.13.1",
"react-native": "0.63.2",
"react-native-screens": "^2.9.0",
...
```

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by mrousavy** [comment]
@WoLewicki https://github.com/mrousavy/rnscreens577

**Comment by mrousavy** [comment]
It goes pretty far up. Kinda funny

<img src="https://user-images.githubusercontent.com/15199031/88546500-befaf180-d01c-11ea-8142-d947735082ec.png" width="50%" />

**Comment by mrousavy** [comment]
Also, here's another demo, seems related:

![RPReplay_Final1596031780 mov](https://user-images.githubusercontent.com/15199031/88811092-6eb79700-d1b6-11ea-806c-5b1a0c3fc1e9.gif)

I don't know why it flickers here and doesn't on the other demo, maybe because I'm using `SafeAreaView` here?

**Comment by WoLewicki** [comment]
Yeah, it may have something to do with `SafeAreaView`. Could you try if it can be reproduced without it?

**Comment by happyfloat** [comment]
I also run into this issue today. I did remove the immediate `SafeAreaView`, but it didn't help, it did just flicker less.

**Comment by Cal-um** [comment]
confirm I am also seeing the bottom jitter on iOS 14 modals when pulling the modal upwards.

**Comment by WoLewicki** [comment]
Can you check if the same happens in RN's `Modal` component? And does it happen only on phones with bottom notch?

**Comment by Cal-um** [comment]
I have presented the same component in the RN modal and the problem does not exist. 

Can repo it with createNativeStackNavigator on notch and non notch device running iOS 13 +.

The issue is most evident when pinning a component to the bottom={0} of the screen.

**Comment by Cal-um** [comment]
I think I have found the issue. RNScreen frames are set to the navigation controller frame when the parent is not UINavigationController. This forces the UIModalPresentationPageSheet modal to be the height of the modal (which extends below the screen since the height of the NavigationController does not equal the height of the modal on screen) on first frame and subsequent calls to viewDidLayout is called the frame is updated and then updated again by setBounds. This causes the jittering effect. 

Looking how to solve this now.

**Comment by WoLewicki** [comment]
@mrousavy @Cal-um can you check if #680 fixes this issue?

**Comment by Cal-um** [comment]
@WoLewicki  This does fix the wobbling issue, however the bottom of the view extends below the screen itself. Im not sure if is meant to do this.

**Comment by a-eid** [comment]
@WoLewicki the issue persists, 

I think when dragging views should persist height. ( so things wouldn't jump around esp absolutely positioned. )

**Comment by a-eid** [comment]
please keep in mind that the issue happens only when `gestureEnabled` is set to false. 

it behaves correctly when the gestures are enabled.

**Comment by WoLewicki** [comment]
Can you check if applying #712 fixes these issues?

**Comment by a-eid** [comment]
@WoLewicki I'm wondering if this is related to this issue. 

![Nov-16-2020 18-26-50](https://user-images.githubusercontent.com/19273413/99279833-550b8f80-2839-11eb-9ddb-7dfc4525e4e3.gif)

is there a way to keep the inner frame size as is when dragging the modal down ?

**Comment by a-eid** [comment]
@WoLewicki I'm also wondering if there is a way to completely disable dragging the modal down ?

**Comment by WoLewicki** [comment]
Is the bug from the GIF appearing after applying #712? If so, could you provide a reproduction of this? You can use `TestsExample` app for it: https://github.com/software-mansion/react-native-screens/tree/master/TestsExample. About the disabling of dragging, I am afraid it is not provided by the platform.

**Comment by a-eid** [comment]
@WoLewicki I can't reproduce it, I need to look more into it, 
is it possible however to maintain the screen frame  when dragging down the screen `gestureEnabled: false` ?

**Comment by Cal-um** [comment]
Confirm it fixes the wobble noted in #https://github.com/software-mansion/react-native-screens/pull/660
🙌

**Comment by kacperkapusciak** [comment]
It's been over a year since this issue was opened and it seems like it doesn't occur anymore. If it still occurs please let us now and we'll reopen this issue.

https://user-images.githubusercontent.com/39658211/132662799-8dbe5c3d-d5e2-4ac3-b16f-7a49da4e1286.MP4

Cheers
