### ISSUE TITLE
Which libs are required by react-native-screens

### ISSUE THREAD

**Issue by muhammadwafa** [software-mansion/react-native-screens#578]
I am using only and only `native-stack` **navigator**, and now I am confused which libraries are required by `react-native-screens/native-stack` ?? I am asking this because, in `react-navigation` there is multiple libs to be install like:

```
react-native-reanimated
react-native-gesture-handler
react-native-safe-area-context
@react-native-community/masked-view
```

So do I need the above 4 packages for only `react-native-screens/native-stack` ?

**Comment by muhammadwafa** [comment]
any help...

**Comment by WoLewicki** [comment]
For `native-stack`, you should only need `@react-navigation/native`. You can read it at https://github.com/software-mansion/react-native-screens/tree/master/native-stack#native-stack-navigator. Does it solve your issue?

**Comment by muhammadwafa** [comment]
And `reactnavigation.org`  says:

`To finalize installation of react-native-gesture-handler, add the following at the top (make sure it's at the top and there's nothing else before it) of your entry file, such as index.js or App.js`

So we do we have to only `react-native-gesture-handler` ?

**Comment by WoLewicki** [comment]
It is not needed for `native-stack`.

**Comment by muhammadwafa** [comment]
@WoLewicki thank you very much, could you please let me know when it is needed `react-native-gesture-handler` ?

And also please if you know let me know do we need `react-native-reanimated` ? for `native-stack` animation?

**Comment by WoLewicki** [comment]
It is needed when you want to use it in your project. As I said, `native-stack` does not require `react-native-gesture-handler` and `react-native-reanimated`. Animations are native there. You can check it by making a simple project without those libraries installed.

**Comment by muhammadwafa** [comment]
Thank you bro very much

**Comment by WoLewicki** [comment]
No problem. Have a good day 🙂 I am closing it then, feel free to comment if you have any questions.
