### ISSUE TITLE
InteractionManager.runAfterInteractions not running at all! (In Production/Release builds)

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-screens#579]
## Description

I am using a lot of `InteractionManager.runAfterInteractions(() => ...)` calls throughout my project.

For example, I have a **feed of multiple posts** in my HomeScreen (Tab Navigator) and each post has `useEffect` and `useFocusEffect` hooks which call `InteractionManager.runAfterInteractions` inside the hook to schedule loading extra post data after some animations have completed. _"Some animations"_ = mostly navigation transitions from [react-navigation](https://github.com/react-navigation/react-navigation), but since the post items specifically are inside a Tab Navigator, no navigation transitions/animations are run so this should fire almost immediately.

In development/debug build everything works fine, but once I build for production/release, the extra post data never gets loaded, a test `Alert.alert(...)` I've put in there never gets shown, and my animations will never start, causing my app to be fully stuck.

I have added a `GlobalErrorHandler` callback to my entry point (`App.tsx`) since I thought "hey, maybe some JS error is thrown and execution is stopped?":

```ts
const defaultErrorHandler = ErrorUtils.getGlobalHandler();
ErrorUtils.setGlobalHandler((error, isFatal) => {
	Alert.alert(`Unexpected ${isFatal ? 'fatal error' : 'error'}!`, `Unexpected error occured! ${JSON.stringify(error)}`);
	Logger.logError(isFatal ? 'A fatal, unhandled error occured!' : 'An unhandled error occured!', error);
	if (defaultErrorHandler) defaultErrorHandler(error, isFatal);
});
```

but this doesn't get called either.

Unfortunately, since this only happens on production/release builds, I'm having a hard time debugging this. I will happily provide any extra information needed.

---

## Extra Details

* I'm using react-navigation, so this might cause a problem I suppose. My root view is a `NavigationContainer`, and inside of it, I conditionally render the `LoginStackNavigator` or the `HomeStackNavigator` depending if the user is logged in or not.
* I'm using react-native-screens (because of react-navigation), but I call the `enableScreens()` function at the top of my entry point (`App.tsx`):
    ```ts
    import { enableScreens } from 'react-native-screens';
    enableScreens();
    ```
* I'm using react-native-gesture-handler (because of react-navigation), but I import the library at the top of my entry point (`App.tsx`):
    ```ts
    import 'react-native-gesture-handler';
    ```
* I'm using react-native-vector-icons, and somehow those Icons won't get shown either. Issue for this: https://github.com/oblador/react-native-vector-icons/issues/1208

---

### Current Behavior

Right now, the InteractionManager does not call the callback function at all, causing my app to be "broken". Data is never getting loaded, delayed animations are not getting started, etc.

### Expected Behavior

The InteractionManager should call the callback after animations have finished. (Which, on a Tab navigator, should be instantly.)

---

## Screenshots

<table>
<tr>
<th>Debug/Development Build</th>
<th>Release/Production Build</th>
</tr>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/15199031/87852514-d80bf000-c902-11ea-84e9-50eac6bdf5fa.jpeg" />
</td><td>
<img src="https://user-images.githubusercontent.com/15199031/87852233-7cd8fe00-c900-11ea-971c-ca1151fc1f25.png"   />
</td>
</tr>
<tr>
<td width="50%">
Everything working fine, all <code>InteractionManager.runAfterInteraction</code> callbacks inside my <code>useEffect</code> hooks are being called.
</td>
<td width="50%">
Everything is broken, <code>InteractionManager.runAfterInteraction</code> callbacks inside my <code>useEffect</code> hooks are not being called, the text for the post is not being loaded (which is inside an <code>InteractionManager.runAfterInteraction</code> callback), and weirdly the react-native-vector-icons are not being displayed. no idea why that's the case, since that has nothing to do with an <code>InteractionManager.runAfterInteraction</code> callback.
</td>
</table>

## How to reproduce

1. Create awesome app
2. Use `react-navigation` for navigation, create NavigationContainer, in my case a Stack Navigator containing a Tab Navigator (Home) and a "Post Details Screen".
3. Add `InteractionManager.runAfterInteractions(() => ...)` callbacks in your components (e.g. `useEffect()` hook)
4. Callbacks will be called in debug, but never in release

## Navigation Structure

Dumbed down, I have the following Navigation Structure:

* `NavigationContainer`
  - `Stack.Navigator` from `createNativeStackNavigator`
    * Some Screens like an Add Screen which are irrelevant here
    * A `Stack.Navigator` from `createStackNavigator` (not native, because I need [react-navigation-shared-element](https://github.com/IjzerenHein/react-navigation-shared-element))
      * Bottom Tabs with 4 Screens from `createBottomTabNavigator`
      * Post Details Screen which is just a simple Screen.

## My Environment

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS, 13.5.1
| @react-navigation/native       | 5.7.1
| react-native-screens | ^2.9.0
| react-native                   | 0.63.2
| react-native-gesture-handler | ^1.7.0
| @react-native-community/masked-view | ^0.1.10
| react-native-reanimated | ^1.10.1
| react-native-safe-area-context | ^3.0.7
| node                           | v14.4.0
| npm or yarn                    | npm, 6.14.6

## Conclusion

I would really appreciate some help with this. I am having an incredibly hard time finding the cause for this and cannot release my app for production.. I have already opened issues for this here:
* https://github.com/facebook/react-native/issues/29421
* https://github.com/react-navigation/react-navigation/issues/8606

I have tried rewriting my app to use [wix/react-native-navigation](https://github.com/wix/react-native-navigation), and noticed that all InteractionManagers work correctly there.

**Comment by hlandao** [comment]
Having the same issue here with react-native | 0.63.2 & rn-screens 2.9.0

**Comment by WoLewicki** [comment]
Can you check if disabling `react-native-screens` fixes the issue?

**Comment by mrousavy** [comment]
@WoLewicki I don't know how I should test this, since when I remove the `enableScreens()` call the app obviously won't work anymore since react-navigation depends on screens.

And I'm pretty sure if I remove screens, gesture handler, and react-navigation, the issue won't persist anymore since then it's just a simple single-page react native app. I could try this though if you need me to.

**Comment by WoLewicki** [comment]
`react-native-screens` is not obligatory for `react-navigation` to work despite the `native-stack`.

**Comment by mrousavy** [comment]
I've just tested removing `enableScreens()` and my app won't even start anymore..

**Comment by WoLewicki** [comment]
You have to convert `native-stack` to normal `stack` in order to make it work without `react-native-screens`. You can also explicitly use `enableScreens(false)` at the root of the project.

**Comment by mrousavy** [comment]
I've replaced all my navigators with non-native stack navigators and called `enableScreens(false)` at the top of my `App.tsx` and the issue still persists. If `enableScreens(false)` really disables the whole lib then it's not part of my problem, thanks for helping me eliminate that possiblity i guess :/

@hlandao do you have any idea? Are you using react-native-shared-element?

**Comment by WoLewicki** [comment]
`enableScreens(false)` disables the usage of `react-native-screens` in the project so if the issue persists, it is not the bug in this library. Can I close it then?

**Comment by mrousavy** [comment]
Yes, I tried eliminating all other causes and finally came to the root of the problem. It's because of the `react-navigation-shared-element` library, created an issue over there: https://github.com/IjzerenHein/react-navigation-shared-element/issues/94. Hopefully it will get resolved soon, don't want to rewrite everything in react-native-navigation :(

Thanks for your help @WoLewicki.

**Comment by haibert** [comment]
incase this helps someone.. requestAnimationFrame is a great alternative! Its also quicker since it waits until there are enough frames to fire the function. 

``` javascript 
 useEffect(() => {
        const task = requestAnimationFrame(() => {
            loadData() 
        })
        return () => cancelAnimationFrame(task)
}, [])
```
