### ISSUE TITLE
NativeStackNavigator - cannot call navigate in useEffect on iOS

### ISSUE THREAD

**Issue by sebqq** [software-mansion/react-native-screens#581]
Hello,

I'm trying to fetch data when app is started and based on response I would like to show Modal to the user.

My modal screen is presented in RootNavigator, which is defined as NativeStackNavigator (`import {createNativeStackNavigator} from 'react-native-screens/native-stack'`) and code looks like:

```tsx
import React from 'react';
...

const Stack = createNativeStackNavigator<RootStackParams>();

const MAIN_STACK_PROPS = {
  stackPresentation: 'modal' as const,
  headerShown: false,
  contentStyle: {
    backgroundColor: colors.background,
    zIndex: 50000,
  },
};

const ALERT_MODAL_OPTIONS = {
  stackPresentation: 'transparentModal' as const,
  stackAnimation: 'fade' as const,
  contentStyle: {
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
};

const RootStack = () => {
  return (
    <NavigationContainer ref={navigationRef}>
      <SafeAreaProvider>
        <ErrorBoundary>
          <Stack.Navigator
            initialRouteName="Main"
            screenOptions={MAIN_STACK_PROPS}>
            <Stack.Screen name="Main" component={TabNavigator} />
            <Stack.Screen
              name="DownloadModal"
              component={DownloadModal}
              options={ALERT_MODAL_OPTIONS}
            />
          </Stack.Navigator>
        </ErrorBoundary>
      </SafeAreaProvider>
    </NavigationContainer>
  );
};

export default RootStack;
```

My Home screen Inside `NativeStackNavigator (RootStack) -> BottomTabNavigator (TabNaigator) -> StackNavigator` then contains a custom react hook, which performs fetch action in it's useEffect and simplified example looks like:

```ts
React.useEffect(() => {
  const data = fetchData();
  if (data) {
    navigation.navigate('DownloadVideoModal', {
        data
      });
  }
}, [])
```

In this example, I'm getting `navigation` prop using `useNavigation()` from React Navigation.

### The problem is that new screen (DownloadModal) **is not VISIBLE**. I said visible on purpose, because at this point I cannot see a new screen is pushed but I'm also not able to trigger any other screen from RootStack using navigation.navigate() function. It looks like my whole RootStack is stucked at this point (However, nested navigators works just fine).

Navigate function is working even when I refresh the app (`CMD + R`). It is not working only after app is fresh-started.

However, if I tried to change my RootStack to use StackNavigator (from React Navigation lib) instead of NativeStackNavigator, then everything works correctly.

Do you have any suggestion how to overcome this problem? If you need repro, I will try to create one later.

BTW: I also tried to use navigationRef from [Navigating without the navigation prop](https://reactnavigation.org/docs/navigating-without-navigation-prop/#handling-initialization) guide and I've also tried to implement on `onReady` callback on `NavigationContainer` but without any success.

I'm able to overcome this issue using `setTimeout` with long enough delay but I think that it is an ugly hack. Hack that helped looks like:

```ts
React.useEffect(() => {
  const data = fetchData();
  if (data) {
    setTimeout(() => {
       navigation.navigate('DownloadVideoModal', {
          data
       });
    }, 3500);
  }
}, [])
```

Thank you for any help!

```
react-native: 0.62.2
react-navigation/bottom-tabs: 5.7.3
react-navigation/native: 5.7.2
react-navigation/stack: 5.8.0
react-native-screens: 2.9.0
```

**Comment by sebqq** [comment]
For everything that it is worth, this code was previously working correctly on some of older versions of _react-native-screens_ package

**Comment by sebqq** [comment]
Solved by upgrading react native to 0.63.2.

**Comment by sebqq** [comment]
Nope, the bug is still there.

**Comment by sebqq** [comment]
Basically, I cannot navigate to another screen even after onReady callback from NavigationContainer was fired. Whole NativeStack is stucked at this point and none of screens from NativeStack are responding.

**Comment by WoLewicki** [comment]
I cannot say much without having a repo to work on. Also, you can try and look in Xcode if the modal screen can be seen in the View Hierarchy.

**Comment by sebqq** [comment]
I've managed to make it work. The problem was in bootsplash package. I was previously hiding Boot screen using timeout. Everything is working correctly after I removed timeout. Thanks for response!

**Comment by Pat-Gekoski** [comment]
I am having the same problem. I don't use bootsplash. I use [react-native-splash-screen](https://www.npmjs.com/package/react-native-splash-screen).  I don't know if the problem is that related. I try to navigate like this: 

```
   useEffect(() => {
      if (!_.isEmpty(checkinData)){
			console.log("useEffect", checkinData)
			navigation.navigate('Checked In')
		} 
   }, [])
```
and the console.log is triggered but not navigation. If I call it like this: 

`	if (checkinData && checkinData.checkedIn) {
		navigation.navigate('Checked In')
	}`

it works no problem. I had no problem with the older version of my app. Is this a bug?

**Comment by WoLewicki** [comment]
I cannot say much without a reproduction of the problem unfortunately.

**Comment by Pat-Gekoski** [comment]
Here are my navigators: 

`const Stack = createStackNavigator()
const Drawer = createDrawerNavigator()
const AboutStack = createStackNavigator()
const FavStack = createStackNavigator()
const ProfileStack = createStackNavigator()
const IssuesStack = createStackNavigator()

// must be declared after styles are parsed or imported
const stackOptions = {
   headerTitleStyle: styles.headerTitle,
   headerStyle: styles.headerContainer,
   headerBackTitleVisible: false,
   headerTintColor: 'white',
   headerLeftContainerStyle: styles.headerIconContainerStyle,
   headerRightContainerStyle: styles.headerIconContainerStyle,
}

// make each drawer screen a stack navigator to use the header
const CheckIn = (props) => {
   return (
      <Stack.Navigator initialRouteName={"Check In"} screenOptions={stackOptions}>
         <Stack.Screen
            name="Check In"
            component={SearchLocationsScreen}
            options={{ headerTitle: 'BarberQue'}}
         />
         <Stack.Screen name="Check In Form" component={CheckInFormScreen}/>
         <Stack.Screen name="Checked In" component={CheckedInScreen} />
         <Stack.Screen name="Business Details" component={BusinessDetailsScreen} />
      </Stack.Navigator>
   )
}

const About = (props) => {
   return (
      <AboutStack.Navigator screenOptions={stackOptions}>
         <AboutStack.Screen name="About" component={AboutScreen} />
      </AboutStack.Navigator>
   )
}

const Favorites = (props) => {
	return (
      <FavStack.Navigator screenOptions={stackOptions}>
         <FavStack.Screen name="Favorites" component={FavoritesScreen} />
      </FavStack.Navigator>
   )
}

const Profile = (props) => {
	return (
      <ProfileStack.Navigator screenOptions={stackOptions}>
         <ProfileStack.Screen name="Profile" component={ProfileScreen} />
      </ProfileStack.Navigator>
   )
}

const Issues = (props) => {
	return (
      <IssuesStack.Navigator screenOptions={stackOptions}>
         <IssuesStack.Screen name="Report Issues" component={ReportIssuesScreen} />
      </IssuesStack.Navigator>
   )
}

// Main Navigation -------------------
const NavDrawer = ({route}) => {
   const [isLoading, setIsLoading] = useState(true)

   if (isLoading) {
      return <LoadingScreen setIsLoading={setIsLoading} />
   }

   return (
      <Drawer.Navigator
         initialRouteName="Search Locations"
         drawerStyle={styles.drawerStyle}
         backBehavior="firstRoute"
         drawerType="slide"
         drawerContent={(props) => <DrawerContent {...props} />}>
         <Drawer.Screen name="Search Locations" component={CheckIn} />
         <Drawer.Screen name="About" component={About} />
         <Drawer.Screen name='Favorites' component={Favorites} />
         <Drawer.Screen name='Profile' component={Profile} />
         <Drawer.Screen name='Report Issues' component={Issues} />
      </Drawer.Navigator>
   )
}

const NavContainer = () => (
   <SafeAreaProvider>
      <NavigationContainer>
         <UserLocationProvider>
            <BusinessLocationsProvider>
               <UserProfileProvider>
                  <CheckInProvider>
                     <FavoritesProvider>
                        <NavDrawer />
                     </FavoritesProvider>
                  </CheckInProvider>
               </UserProfileProvider>
            </BusinessLocationsProvider>
         </UserLocationProvider>
      </NavigationContainer>
   </SafeAreaProvider>
)

export default NavContainer`

and in my "Search Locations" screen i call a function that checks a Context for "checkinData"  and then if it exists It should navigate the user to the "Checked In" screen like this: 

`useEffect(() => {
      console.log('useEffect called')
      navigation.navigate('Checked In')
   }, [])`

I will try and see if I can get a snack up and running but because this has worked in the past, I'm not sure how easily I can replicate it.

**Comment by sobernaut** [comment]
Unfortunately, I am having the same problem as @Pat-Gekoski . navigate would not fire up inside useEffect.

**Comment by kacperkapusciak** [comment]
Hi @Pat-Gekoski
Developing with `react-navigation` differs a bit from what we used to do in "normal" React.
Screens in a `stack` are never really unmounted. So when a screen "mounts" once again it has no real effect on the navigation. React navigation team overcome that problem by introducing a `focus` event, which is called when the screen comes into focus.

```js
React.useEffect(() => {
  const unsubscribe = navigation.addListener('focus', () => {
    // Screen was focused
    // Do something
  });
    
  return unsubscribe;
}, [navigation]);
```

[This part of the documentation](https://reactnavigation.org/docs/navigation-lifecycle) explains the lifecycle of navigation in detail and I highly recommend checking it out. It'll save you a lot of time 😅 

Also, your code has nothing to do with `react-native-screens`.
We are the creators of `native-stack`. All of the other navigators are made by `react-navigation` team fyi 😄

**Comment by timoisalive** [comment]
The above listener seems to work, but how come the provided `useFocusEffect` hook doesn't:
```
  useFocusEffect(
    useCallback(() => {
      navigation.navigate(routeName);
    }, [])
  );
```
