### ISSUE TITLE
Status Bar Disable does not work on Android

### ISSUE THREAD

**Issue by Immortalin** [software-mansion/react-native-screens#585]
Unable to disable Status bar on Android with enableScreens()

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue? I am not quite sure I understand what you mean by `disable`.

**Comment by Immortalin** [comment]
Making the status bar invisible until swiped. I meant hidden, not disable https://reactnative.dev/docs/statusbar
