### ISSUE TITLE
How to enable/disable NativeStackNavigationOptions gestureEnabled with animated values ? 

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-screens#586]
I have been able to disable `gestureEnabled` with `PanGestureHandler` but I wasn't able to enable / disable either the stack props not `PanGestureHandler` `enable/disabled` props use `Animated.Value`

does any body have any idea ( possible hacky way ) to do that ?

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to understand the use case you are trying to achieve?

**Comment by a-eid** [comment]
@WoLewicki I'm trying to enable / disable `gestureEnabled` with an `Animated.Value` without causing any rerenders.

but yea I have make a minimal repro example, that is not a bug thou, more of a feature request.

**Comment by WoLewicki** [comment]
So please provide a repo that shows what you would like to achieve.

**Comment by a-eid** [comment]
@WoLewicki basically this 
https://github.com/a-eid/react-native-native-stack-global-loader/blob/475fb7d95003606551c29bacae547ec7c35a980f/App.tsx#L50

I wanna control the `gestureEnabled` via an animated value | sharedvalue so I can avoid the re-rendering of the stack. is that possible ?

**Comment by satya164** [comment]
Why is re-rendering Stack a problem?

**Comment by a-eid** [comment]
@satya164 TBH, I'm a little concerned about performance.

**Comment by WoLewicki** [comment]
I wouldn't be too concerned about performance, `react-navigation` already does a lot to prevent unnecessarily re-rendering your screens. Or can you spot a problem with this already?

**Comment by a-eid** [comment]
@WoLewicki  are u saying that rerender the stack wouldn't re-render the screens inside of it ? 

I thought it does, I never tried actually I'll try and see whether or not it does rerender the nested screens, thanks.

**Comment by a-eid** [comment]
@WoLewicki @satya164 that is the case indeed, it works great. thank you.
