### ISSUE TITLE
How to add headerLargeRight component when headerLargeTitle is enabled?

### ISSUE THREAD

**Issue by yareyaredesuyo** [software-mansion/react-native-screens#595]
I think there is no option to add headerLargeRight component, when headerLargeTitle is enabled.
This feature is common in iOS App.

Is there any way to achieve this?

The following image is a sample which has headerLargeRight component in app.

![UNADJUSTEDNONRAW_thumb_3](https://user-images.githubusercontent.com/31843888/89699532-97801f00-d962-11ea-8aae-35565b859a25.jpg)

**Comment by WoLewicki** [comment]
According to https://stackoverflow.com/questions/55539363/navigation-bar-with-large-titles-and-right-uibarbuttonitem, there is no such option in native iOS, it has to be handled manually. Can I help you more with this?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Comment by MoOx** [comment]
I am very interested by this, what is the best way to have a "custom" large title? I am also looking to have a "pre-title", like this 

![IMG_63F456C23D25-1](https://user-images.githubusercontent.com/157534/106334387-d1374000-628a-11eb-8c32-aae629e9dd04.jpeg)
![IMG_F60B75E4B92B-1](https://user-images.githubusercontent.com/157534/106334389-d3010380-628a-11eb-8bf0-58eb30c3a915.jpeg)

**Comment by WoLewicki** [comment]
I am afraid you need to hide the `header` provided by `native-stack` and create your own animated header in order to have this.
