### ISSUE TITLE
Change backgroundColor of the card behind a modal

### ISSUE THREAD

**Issue by Kinark** [software-mansion/react-native-screens#596]
When a modal pops up, the behind content dims (gets darker/less opacity), however, if we are working on a dark themed app (with a black bg), the background should turn to gray when a modal pops up (notice the grayish card in the back).
![image](https://user-images.githubusercontent.com/17537081/89715754-77f6ef80-d97e-11ea-9a92-2b13ee02d962.png)
when working with a black background and the modal pops up, the result is something like this:
![image](https://user-images.githubusercontent.com/17537081/89716104-a5449d00-d980-11ea-9e0f-b883508c7aae.png)
As you can see, the card in the back is completely gone.

Is it possible to do such thing with createNativeStackNavigator?

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue so I can work on it?

**Comment by WoLewicki** [comment]
Also, I am afraid that this grayish color comes from the usage of the system colors introduced in iOS 13. It is probably dynamic .systemBackground color for an elevated layer. (check 10:00 here https://developer.apple.com/videos/play/wwdc2019/808). In `react-native` you can use this color with `PlatformColor`. Applying https://github.com/facebook/react-native/blob/master/RNTester/js/examples/PlatformColor/PlatformColorExample.js#L60 to your headerStyle's `backgroundColor` will result in this effect in dark mode. Can I help you any more with this issue?

**Comment by Kinark** [comment]
> Also, I am afraid that this grayish color comes from the usage of the system colors introduced in iOS 13. It is probably dynamic .systemBackground color for an elevated layer. (check 10:00 here https://developer.apple.com/videos/play/wwdc2019/808). In `react-native` you can use this color with `PlatformColor`. Applying https://github.com/facebook/react-native/blob/master/RNTester/js/examples/PlatformColor/PlatformColorExample.js#L60 to your headerStyle's `backgroundColor` will result in this effect in dark mode. Can I help you any more with this issue?

But if I apply a fixed `backgroundColor` to my headerStyle, I'll get a static gray header even when it's in first plan. What I want to achieve is a 100% black background that turns gray when in second plan.  
  
Take a look at this native app:
[NativeApp.zip](https://github.com/software-mansion/react-native-screens/files/5097827/NativeApp.zip)

**Comment by Kinark** [comment]
Oh, nevermind. It worked just perfect :D

Thanks, @WoLewicki!!!

**Comment by waheedakhtar694** [comment]
@WoLewicki your link is not working for react-native example app.

> Also, I am afraid that this grayish color comes from the usage of the system colors introduced in iOS 13. It is probably dynamic .systemBackground color for an elevated layer. (check 10:00 here https://developer.apple.com/videos/play/wwdc2019/808). In `react-native` you can use this color with `PlatformColor`. Applying https://github.com/facebook/react-native/blob/master/RNTester/js/examples/PlatformColor/PlatformColorExample.js#L60 to your headerStyle's `backgroundColor` will result in this effect in dark mode. Can I help you any more with this issue?

**Comment by WoLewicki** [comment]
@waheedakhtar694 thanks for the updated link. I think it is even better to provide the code from a exact commit so if the `main` branch changes, it won't lead to a wrong code (like in my older link): https://github.com/facebook/react-native/blob/013232abefcb73548946699f54e98cc95b853bfa/packages/rn-tester/js/examples/PlatformColor/PlatformColorExample.js?rgh-link-date=2022-03-29T10%3A06%3A24Z

**Comment by waheedakhtar694** [comment]
@WoLewicki I think the [docs](https://reactnative.dev/docs/platformcolor) link will be fine it also has the above link at the bottom.

**Comment by waheedakhtar694** [comment]
@WoLewicki I have an issue with my native stack navigator, the header of the stack navigator becomes gray randomly in the dark mode, sometimes these work fine and sometimes these become gray while initializing the app, Can you please suggest some solution.
