### ISSUE TITLE
Is it possible to set headerTruncatedBackTitle?

### ISSUE THREAD

**Issue by JB1905** [software-mansion/react-native-screens#605]
Is it possible to set headerTruncatedBackTitle in `createNativeStackNavigator` like in [`createStackNavigator`](https://reactnavigation.org/docs/stack-navigator/#headertruncatedbacktitle)?

**Comment by WoLewicki** [comment]
According to https://stackoverflow.com/a/50148259/13006595, it is not possible to determine if the title will be truncated from the native side and I cannot see such an option too, so I am afraid it is not possible. Can I help you more with it?

**Comment by JB1905** [comment]
@WoLewicki thanks you for your answer 😃

**Comment by Rebsos** [comment]
So basically, if you have non english users, you have to
1. Disable BackTitle everywhere with headerBackTitleVisible​: false, or
2. Use createStackNavigator
Or am I missing something?
