### ISSUE TITLE
Feature request: ability to add an overlay component

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-screens#606]
Considering the scenarios I may encounter using this, I see a need to be able to define an overlay component that can sit above the navigation bar, this is a concept that react-native-navigation has https://wix.github.io/react-native-navigation/docs/overlay.

This would make adding drawer layouts or anything that needs to be above the navigation bar a lot easier.

**Comment by WoLewicki** [comment]
Cannot this behavior be achieved with `transparentModal`? You can see more discussion about it in #525.

**Comment by a-eid** [comment]
@WoLewicki I would like to reference wix's overlay docs here 
https://wix.github.io/react-native-navigation/docs/overlay 

using a `transparentModal` wouldn't work if you wanna display a toast on top of modal screen, users wouldn't be able to interact with the underlying view.

**Comment by a-eid** [comment]
@WoLewicki I'm wondering if you guys are still considering this feature.

**Comment by WoLewicki** [comment]
This is for sure something nice to be added and I would gladly accept a PR with it.

**Comment by a-eid** [comment]
@WoLewicki how do I add `pointerEvents` support for it ? 

I'm assuming `pointerEvents` works on android out of the box because it's just view.

**Comment by WoLewicki** [comment]
I think this issue is part of what can be achieved by using `OverlayView` (see https://github.com/software-mansion/react-native-screens/issues/525 and https://github.com/software-mansion/react-native-screens/pull/1096). I will close this issue then to keep the discussion in one place. Feel free to comment here if I am wrong and I'll reopen it.

**Comment by kyle-ssg** [comment]
So good, can't wait to use this!
