### ISSUE TITLE
android 5 Crash

### ISSUE THREAD

**Issue by luyouwei66** [software-mansion/react-native-screens#617]
implementation 'androidx.appcompat:appcompat:1.1.0' problem 
implementation 'androidx.appcompat:appcompat:1.2.0' is ok

**Comment by WoLewicki** [comment]
On which RN version does it happen? Can you provide a repo that shows this problem?

**Comment by luyouwei66** [comment]
> 它在哪个RN版本上发生？您可以提供显示此问题的存储库吗？

0.62.2

**Comment by WoLewicki** [comment]
I built a new project with `react-native-screens` with RN version 0.62.2 and on Android 5 phone and all works as expected. Can you provide a repository where I can recreate the crash?

**Comment by luyouwei66** [comment]
native-echarts or react-native-webview

**Comment by luyouwei66** [comment]
> 我`react-native-screens`使用RN版本0.62.2和Android 5手机构建了一个新项目，所有项目均按预期工作。您可以提供一个可以重新创建崩溃的存储库吗？
native-echarts或react-native-webview

**Comment by WoLewicki** [comment]
Problems with `react-native-webview` are already discussed in #105. Is it the same crash as reported there?

**Comment by luyouwei66** [comment]
> Problems with `react-native-webview` are already discussed in #105. Is it the same crash as reported there?
String resource ID #0x2040002

**Comment by WoLewicki** [comment]
I don't understand.

**Comment by WoLewicki** [comment]
Closing due to no reproduction provided in 30 days.
