### ISSUE TITLE
Feature Request: Add 'replace' to stack navigator actions

### ISSUE THREAD

**Issue by cjpete** [software-mansion/react-native-screens#623]
Per the react-navigation docs, there is a 'replace' function available for stack navigators, but this doesn't seem to be supported in the react-native-screens `stack-navigator`.

https://reactnavigation.org/docs/navigation-prop/#navigator-dependent-functions

**Comment by WoLewicki** [comment]
It should be available in `native-stack`. Can you provide an example where it does not work?

**Comment by WoLewicki** [comment]
I am closing it since I think this issue is invalid. Feel free to comment if I am wrong.

**Comment by sbalay** [comment]
@WoLewicki I think this issue meant that right now, to replace a screen we have to do

```
      navigation.dispatch(
        StackActions.replace('my screen', screenParams)
      )
```

And it would be nice to be able to do

```
navigation.replace('my screen', )
```

Correct me if Im wrong though. Im using the following types:

```
NativeStackNavigationProp<Params, 'my screen'>
```

**Comment by WoLewicki** [comment]
Oh I can see what is the problem now. Can you check if #695 fixes this?

**Comment by sbalay** [comment]
Yep, I think #695 should fix this

**Comment by punisher97** [comment]
#695 not working, you need add replace function, see:

```typescript

**Comment by WoLewicki** [comment]
`StackActionHelpers` does contain `replace` action in it. How did you test that this PR is not working @punisher97 ?

**Comment by punisher97** [comment]
@WoLewicki  I use:
```typescript 
import type { NativeStackNavigationProp } from 'react-native-screens/native-stack';
type Props = {
	navigation: NativeStackNavigationProp<any>;
};
```
How add ‘replace' in NativeStackNavigationProp or which I should use?

**Comment by sbalay** [comment]
@punisher97 note that this fix has not been released yet. Make sure that you are using the correct reference of react-native-screens when trying to test these changes.

@WoLewicki can we get this included in a release soon? 😇

**Comment by WoLewicki** [comment]
@sbalay 2.15.0 is out 🎉
