### ISSUE TITLE
How to disable shadow transition?

### ISSUE THREAD

**Issue by lakakoy** [software-mansion/react-native-screens#628]
This is how transitions work in **react-native-screens**:
![via-react-native-screens](https://media.giphy.com/media/KCqh3jPCQRMOM1vj23/giphy.gif)

Could you give me an idea how to do this:
![via-react-nativigation](https://media.giphy.com/media/SrzP8Tt3Fq5dOD6imT/giphy.gif)

There are several ways how to disable transition shadow in **react-navigation**.
None of these methods work in **react-native-screens**.

Thanks.

**Comment by SrBrahma** [comment]
There is also a strange shadow below the header in Android that gets stronger when it finishes transitioning.

**Comment by Appkidd** [comment]
Also seeing this issue. Any workarounds?

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by WoLewicki** [comment]
@SrBrahma if you mean the shadow under the header on Android, it can be hidden with this prop: https://github.com/software-mansion/react-native-screens/tree/master/native-stack#headerhideshadow. 
@vjjd the shadow in the iOS transition is provided by the `UIKit` and unfortunately it looks like it is not customizable. Can I help you any more with it?

**Comment by vjjd** [comment]
@WoLewicki sorry for my late response. Now I'm trying to find where the transition shadow parameters are set. Most likely, I'll be able to change the values with the [patch-package](https://github.com/ds300/patch-package). It would be fantastic if you could share information where these parameters might be located.

**Comment by WoLewicki** [comment]
I tried the solution presented in the SO thread, but it did not change the transition shadow. It changes the view that is not visible (attached screenshot), maybe it would work for the native iOS project or maybe I am doing something wrong. You can try it by applying the changes anywhere where the `navigationController` is used.

![image](https://user-images.githubusercontent.com/32481228/99407174-189a6b00-28ef-11eb-8c12-ed495b098957.png)

**Comment by vjjd** [comment]
@WoLewicki сould you post a stoke of code you're using? Thank you.

**Comment by WoLewicki** [comment]
I just added `navigationController.view.backgroundColor = [UIColor blueColor];` below this line: https://github.com/software-mansion/react-native-screens/blob/master/ios/RNSScreenStack.m#L120

**Comment by Appkidd** [comment]
Hey guys, did you manage to find a workaround at all? The shadow is particularly noticeable in our app based on our stack configuration so would be great to find a fix.

@WoLewicki would it be possible to add a custom transition we can use as [demonstrated here](https://stackoverflow.com/questions/30719916/uinavigationcontroller-remove-drop-shadow-when-transitioning-to-another-vc) so that we can remove the shadow? Would love to help where I can but my knowledge of Obj C is shocking.

**Comment by WoLewicki** [comment]
Can you check if #761 is what you need? @Appkidd @lakakoy

**Comment by lakakoy** [comment]
> Can you check if #761 is what you need? @Appkidd @lakakoy

Awesome! It's working. Thanks so much!

**Comment by lakakoy** [comment]
@WoLewicki
I still face problem when using swipe back gesture.
![swipe-back-gesture-shadow](https://media.giphy.com/media/xlSSC9T9eJgXQOA9Sg/giphy.gif)

**Comment by WoLewicki** [comment]
@lakakoy it happens because the swipe gesture does not use the specified transition, but rather the default one provided by the platform. The only solution I can think of is to disable going back with swipe by setting `gestureEnabled: false` on the navigator.

**Comment by WoLewicki** [comment]
@lakakoy #761 should be ready and should solve the problem with shadow in swipe transition. Can you check if it does not introduce any new problems?

**Comment by lakakoy** [comment]
@WoLewicki thank you! I'm still waiting for the merge and as a temporary solution I'm using the patch based on your code #761.
