### ISSUE TITLE
Blank screen on native stack push animation with nested navigator

### ISSUE THREAD

**Issue by savelichalex** [software-mansion/react-native-screens#629]
react-native-screens version: 2.10.1 (with patch, details below)
react-native: 0.62.2 (same for 0.63)
@react-navigation/native: ^5.6.1

I had a same problem as in https://github.com/software-mansion/react-native-screens/issues/432 , therefore I had to apply a patch https://github.com/software-mansion/react-native-screens/pull/600 . It fixed header buttons positions, but introduced a new bug. When you push a new screen with nested stack navigator in it, it will render nothing until transition animation is finished (persist even when `Slow animations` flag is turned on for a simulator).

<img width="200" alt="bug-1" src="https://user-images.githubusercontent.com/6286454/92722729-b104f400-f370-11ea-8b2d-c333e7a0a1e6.png" align="left">
<img width="200" alt="bug-2" src="https://user-images.githubusercontent.com/6286454/92722733-b2ceb780-f370-11ea-98c8-14ed340ea8aa.png">

In our project we use a custom navigator and I created [a branch in it](https://github.com/tonlabs/react-navigation-surf/blob/native-stack-bug/Example/App.js) to help you to reproduce the problem.

(You could apply a patch with `./apply-patch.sh` command in `Example` folder, also make sure that `Example/node_modules/react-navigation-surf/src/createSurfSplitNavigator.js` [use proper if statement](https://github.com/tonlabs/react-navigation-surf/blob/master/src/createSurfSplitNavigator.js#L187) (we had to turn off ios support until fix is found).

**Comment by WoLewicki** [comment]
Please apply also #613 and see if it fixes the issues.

**Comment by savelichalex** [comment]
@WoLewicki it helped, thanks!

**Comment by WoLewicki** [comment]
And there are no new issues with this setup?
