### ISSUE TITLE
How to use with the jest preset "react-native"?

### ISSUE THREAD

**Issue by bitttttten** [software-mansion/react-native-screens#631]
The jest preset from React Native [mocks the UIIManager.getViewManagerConfig method](https://github.com/facebook/react-native/blob/bdf3c7911007f547101d753903da11ea4ee095f9/jest/setup.js#L61):

```js
jest.mock('../Libraries/ReactNative/UIManager', () => ({
  getViewManagerConfig: jest.fn(name => {
    if (name === 'AndroidDrawerLayout') {
      return {
        Constants: {
          DrawerPosition: {
            Left: 10,
          }
        }
      }
    }
  })
})
```

And so this creates an error [when calling enableScreen](https://github.com/software-mansion/react-native-screens/blob/620d063d19eb27faea7b91a99c262ce203e23a06/src/index.native.js#L16), since `UIManager.getViewManagerConfig(name)` will fail like when name is `RNScreen`. If name is `RNScreen`, the method will return undefined and then an error will appear in the tests:

```js
console.error
    Screen native module hasn't been linked. Please check the react-native-screens README for more details
```

The tests do pass and work, although this error is not ideal. Is there a way to use the preset without this warning? I was imaging just patching the preset and extending it to be:

```js
getViewManagerConfig: jest.fn(name => {
  if (name === 'AndroidDrawerLayout') {
    return {
      Constants: {
        DrawerPosition: {
          Left: 10,
        }
      }
    }
  }
  if (name === 'RNScreen') {
    return {}
  }
})
```

Although I don't know if this is ideal!

**Comment by codecog** [comment]
@bitttttten You can remove the error by mocking the `enableScreens()` method.

```
// __mocks__/react-native-screens.js
export const enableScreens = jest.fn();
```

**Comment by bitttttten** [comment]
Oh okay great! I didn't know if it was safe to mock or not. Thanks @codecog !

**Comment by amwebexpert** [comment]
Another way, directly inside the unit test:

```
jest.mock('react-native-screens', () => ({
  ...jest.requireActual('react-native-screens'),
  enableScreens: jest.fn(),
}));
```
