### ISSUE TITLE
Add web support for native stack

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/react-native-screens#634]
It would be great to have web support for the native stack. It's difficult to fall back to react navigation's `createStackNavigator` on web, since there isn't parity between the two APIs and naming is different for similar props.

**Comment by WoLewicki** [comment]
`native-stack` depends on platform-specific options for all the exported features, so it is not designed to be applicable in the web environment. I think all the options for web would have to be copied code from `stack-navigator`. How would you see such support?

**Comment by nandorojo** [comment]
Got it, that makes sense. I ended up using a `stack.web.tsx` file that exports a regular stack for web from React navigation. It's a bit cumbersome to have 2 files like that, but it does the job, so I'll close this.

Thanks for your work on this library. It's a game changer to use.
