### ISSUE TITLE
Can't dismiss full screen modals on iOS after upgrade to 2.11.0

### ISSUE THREAD

**Issue by beetlebum** [software-mansion/react-native-screens#638]
After upgrading to 2.11.0, full screen modals on iOS cannot be dismissed.
`canGoBack` from react navigation returns true, but `goBack` does nothing. 
I've also tried `popToTop` to no avail.

The stack is configured as such:
```    
  mode="stack"
      screenOptions={{
        headerShown: false,
        stackPresentation: 'fullScreenModal',
      }}
```

Android works fine, and so does `'modal'` stack presentation.

Downgrading to 2.10 fixes the issue.

Thank you.

**Comment by kamui545** [comment]
I am experiencing the same and can confirm that it seems to be a regression from 2.10 -> 2.11.

`formSheet` works fine, but as soon as you try to dismiss a `fullScreenModal` the UI will "freeze" and you cannot interact with anything anymore.

**Comment by WoLewicki** [comment]
Looks like this regression was introduced by #600 + #613. For now, you can revert them with [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by WoLewicki** [comment]
Can you check if #643 fixes that bug and does not introduce new ones?

**Comment by beetlebum** [comment]
@WoLewicki I can't reproduce it anymore in #643 , seems to be fixed, thanks

**Comment by saeho** [comment]
I still have the same issue in both v2.11.0 and also the "fixed" commit.

May I have some assistance?

Using goBack() on a full screen modal seems to trigger this.
