### ISSUE TITLE
Issue with largeTitle and BottomTabNavigator without a header

### ISSUE THREAD

**Issue by juergengunz** [software-mansion/react-native-screens#645]
The first screen in the RootNavigator is a BottomTabNavigator without a header and I want to navigate to a Screen in the RootStackNavigator with largeTitles. If I navigate to the second Screen with headerLargeTitle:true - Initially the title is collapsed. 

Is there a way to force the large title to be not collapsed?

```
<RootStack.Screen options={{headerShown: false}} name="Home" component={TabScreen} />
<RootStack.Screen options={({ route }) => ({headerShown: true,title: route.params.name,headerLargeTitle: true})} name="Second" component={SecondScreen} />
```

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by giaset** [comment]
Having the same issue.

`<Tab.Navigator>
    <Tab.Screen name='LobbyStackNavigator' component={LobbyStackNavigator} />
</Tab.Navigator>`

and

```
<Stack.Navigator screenOptions={{ headerLargeTitle: true }}/>
    <Stack.Screen name='Lobby' component={LobbyScreen} />
</Stack.Navigator>
```

**Comment by ArekChr** [comment]
Have the same issue, every large title header is collapsed inside bottom tab on app mounted

**Comment by WoLewicki** [comment]
Does this behavior appear only if using `ScrollView` in the screen with large title?

**Comment by ArekChr** [comment]
@WoLewicki  I have manipulatet props a bit, If I set remove paddingBottom contentContainerStyle from scrollview (which is needed for bottom tab translucent) then this doesn't occur I hope that helps

**Comment by ArekChr** [comment]
@WoLewicki  This error doesn't occur if scrollview is empty and without props, hope that helps

**Comment by ArekChr** [comment]
@WoLewicki this error also occur with contentContainerStyle={{ paddingBottom: 10 }} **but with empty scrollView**

**Comment by WoLewicki** [comment]
It looks like the native iOS implementation of `RCTScrollView` is messing with the large header. It would require more debugging on the native side. Thanks for the information @ArekChr 🎉 .

**Comment by ArekChr** [comment]
Im not pretty sure that it is RCTScrollView, With wix react-native-navigation this issue doesn't occur with the same config

**Comment by WoLewicki** [comment]
That is interesting. I will try to look into it more. Please comment if you find some more clues about it!

**Comment by alexanderstrom** [comment]
If you delay the render of the scrollView the title is not collapsed. For example, delay it by setting a state showScrollview in useEffect. Maybe a little clue

**Comment by WoLewicki** [comment]
Can you check if #670 fixes the issue and does not introduce any new issues?

**Comment by johankasperi** [comment]
I've had the same issue and the solution proposed by @grahammendick [here](https://github.com/software-mansion/react-native-screens/issues/645#issuecomment-712199841) solves it for me. Thank you @grahammendick!

**Comment by grahammendick** [comment]
@johankasperi glad it works and thanks for letting me know

**Comment by WoLewicki** [comment]
I am closing this issue in favor of #649 in order to keep the discussion in one place. Please comment here if something is wrong with it.

**Comment by andrew09** [comment]
> If you delay the render of the scrollView the title is not collapsed. For example, delay it by setting a state `showScrollview` in `useEffect` with a `setTimeout` at 0. Maybe a little clue

This worked for me. Saved my life after so much searching!

**Comment by danielrhodes** [comment]
If anybody is still having trouble with this, the answer for me was I needed another stack navigator inside the tab.

I am also using a ScrollView (FlashList) with a refresh control, which appears to have caused problems for others. If `refreshing` is initially given a value of true, it animates in a funny way and becomes offset, so during the initial load `refreshing` cannot be true.

Here is my approximate view hierarchy:

```jsx
<NavigationContainer>
    <Stack.Navigator>
       <Stack.Screen component={tabBar} options={{headerShown: false}} />
    </Stack.Navigator />
</NavigationContainer>

// tabs

<Tab.Navigator>
   <Tab.Screen />
      <Tab.Screen  options={{headerShown: false}} component={tab} />
    </Tab.Navigator>
</Stack.Navigator>

// tab
<Stack.Navigator>
   <Stack.Screen component={tabBar} options={{headerShown: true, headerTranslucent: true, headerLargeTitle: true}} />
</Stack.Navigator />


```

**Comment by fabOnReact** [comment]
This issue can be solved by creating your own implementation of ScrollView based on react-native APIs. https://github.com/fabOnReact/react-native-improved
