### ISSUE TITLE
Android: android.view.ViewParent android.view.View.getParent()' on a null object reference

### ISSUE THREAD

**Issue by melkayam92** [software-mansion/react-native-screens#646]
Hi,

Since I upgraded from 2.5.0 to 2.10.* I'm getting a lot crashes in production saying:

"android.view.ViewParent android.view.View.getParent()' on a null object reference" - NullPointerExecption
"FragmentManager has been destroyed" - IllegalStateException

 "@react-navigation/native": "^5.7.3",
 "@react-navigation/native-stack": "^5.0.5",
 "@react-navigation/stack": "^5.9.0",
  "react-native": "0.63.2",

Now I downgraded to 2.5.0, will update here if the issue really stops.

ALSO - it's not related to the issue that the activity is killed in the background, I checked and it works fine there with the onCreate(null) solution.

**Comment by WoLewicki** [comment]
Are you using `"@react-navigation/native-stack": "^5.0.5",`? The supported version of native-stack is taken from `react-native-screens/native-stack`. Does this issue happen there? If so, please provide a reproduction of this crash so we can work on it.

**Comment by lampn9397** [comment]
This issue occur also with me on Android devices.
`"react-native-screens": "2.10.1"`
![image](https://user-images.githubusercontent.com/22604768/93751822-e5599980-fc27-11ea-894c-9f8ef5f21c32.png)

**Comment by WoLewicki** [comment]
@lampn9397 could you provide a repo with a reproduction of the issue then?

**Comment by melkayam92** [comment]
I can confirm that downgrade the library to 2.5.0 didn't help.

Looks like it's related to saveInstanceState..



![Screen Shot 2020-09-22 at 20 37 45](https://user-images.githubusercontent.com/8774744/93917398-9f79ff80-fd13-11ea-89d5-b53846d62c66.png)

**Comment by melkayam92** [comment]
Also, I forgot to say, I did use the "animationEnabled"  for my navigator in this version.

I will try to see what happens if I revert it to false.

**Comment by handipriyono** [comment]
sorry, i think the solution above still not resolved. 
i still getting crash 
_Android: android.view.ViewParent android.view.View.getParent()' on a null object reference_

**Comment by WoLewicki** [comment]
Can you try and change https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.java#L157 to `ViewParent screenStack = getView() != null ? getView().getParent() : null;` and see if it fixes the issue?

**Comment by handipriyono** [comment]
i'll try, @WoLewicki , but, btw, if i change / modif in node_modules react-native screens repo,   it means that, for the production-App, i have to clone that repo and use my repo instead of using from react-native-screen?

**Comment by WoLewicki** [comment]
You can use [patch-package](https://www.npmjs.com/package/patch-package) until the version with a fix is released to automatically apply the change to your code.

**Comment by handipriyono** [comment]
@WoLewicki , thank for the solution, 👍🏼 
unfortunatelly, this crash-case is random, so i can not make sure that that solution is working.,
but i still investigating into this issue,, and re-check my sentry if the crash still exist or not

**Comment by melkayam92** [comment]
I can confirm that disabling the animation "fixes" the issues.

**Comment by WoLewicki** [comment]
@melkayam92 can you check if having the animation and applying #671 fixes the bug?
