### ISSUE TITLE
Native stack fullScreenModal screens wont close on iOS with navigation.goBack()

### ISSUE THREAD

**Issue by Vissp18** [software-mansion/react-native-screens#657]
After updating from 2.10.1 to 2.11.0 our React navigation (native stack) screens with stackPresentation: 'fullScreenModal' screens wont close any more on iOS with navigation.goBack(). It seems the underlying screen does regain focus after navigation.goBack(), but it doesnt slide down.

**Comment by WoLewicki** [comment]
It seems to be duplicate of #638. I am closing it. Please comment if I am wrong or if you have any questions.
