### ISSUE TITLE
Enabling with react-navigation causes white flash

### ISSUE THREAD

**Issue by scottmas** [software-mansion/react-native-screens#661]
This bug has been well explained here https://github.com/react-navigation/react-navigation/issues/8242 and seems to be affecting all users of the latest react navigation, both react navigation 5 and the latest on 4. 

Is there anything that could be done to fix this inside this package? Thanks!

**Comment by WoLewicki** [comment]
Isn't it a duplicate of https://github.com/software-mansion/react-native-screens/issues/111? If not, could you be more descriptive of what the issue is exactly and provide some repo/snack/gifs that show buggy behavior?

**Comment by scottmas** [comment]
Hey sorry didn't a notification for your response for some reason. But yes, this is a duplicate of https://github.com/software-mansion/react-native-screens/issues/111. Closing. I think the underlying issue is that the view hasn't been remounted to the view hierarchy before react navigation wants to display it.

**Comment by WoLewicki** [comment]
Yeah, that is the reason. Hopefully, it will be fixed by #624, where you will be able to keep e.g. 2 screens mounted all the time.
