### ISSUE TITLE
Change header height in headerStyle

### ISSUE THREAD

**Issue by chengsokdara** [software-mansion/react-native-screens#665]
**Is your feature request related to a problem? Please describe.**
I would to be able to change header height. Is it considered in future version?

**Describe the solution you'd like**
I would like to be able to change it in headerStyle, currently I can only change the backgroundColor.

**Describe alternatives you've considered**
Alternatively let us use custom component to replace the whole header.

**Comment by WoLewicki** [comment]
`react-native-screens` uses native components for the header and does not provide a method to change its height. You can use `headerShown: false` option to hide the native header and provide your own, custom one. Can I help you any more with this?

**Comment by chengsokdara** [comment]
> `react-native-screens` uses native components for the header and does not provide a method to change its height. You can use `headerShown: false` option to hide the native header and provide your own, custom one. Can I help you any more with this?

Right now I'm going with that approach and just use FlatList ListHeaderComponent to render custom header. Thank you.

**Comment by WoLewicki** [comment]
I will close this issue then. Feel free to comment if you have any questions.
