### ISSUE TITLE
[ANDROID CRASH] with @react-navigation/material-top-tabs

### ISSUE THREAD

**Issue by HasanSahabGlobal** [software-mansion/react-native-screens#674]
when i try to navigate by "react-native-screens/native-stack" from "@react-navigation/material-top-tabs" top tabs, it is crashes.

> "dependencies": {
    "@dudigital/react-native-zoomable-view": "^1.0.15",
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/cameraroll": "^4.0.0",
    "@react-native-community/hooks": "^2.6.0",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-native-community/netinfo": "^5.9.2",
    "@react-native-community/push-notification-ios": "^1.3.0",
    "@react-native-firebase/analytics": "^7.6.8",
    "@react-native-firebase/app": "^8.4.6",
    "@react-native-firebase/auth": "^9.3.1",
    "@react-native-firebase/database": "^7.5.12",
    "@react-native-firebase/messaging": "^7.9.1",
    "@react-navigation/bottom-tabs": "^5.6.1",
    "@react-navigation/material-top-tabs": "^5.2.12",
    "@react-navigation/native": "^5.6.1",
    "axios": "^0.19.2",
    "clevertap-react-native": "^0.4.5",
    "i18next": "^19.4.3",
    "libphonenumber-js": "^1.7.51",
    "lodash": "^4.17.19",
    "lottie-ios": "^3.1.8",
    "lottie-react-native": "^3.4.0",
    "moment": "^2.27.0",
    "react": "16.11.0",
    "react-hook-form": "^5.3.1",
    "react-i18next": "^11.3.5",
    "react-native": "0.62.0",
    "react-native-adjust": "^4.22.0",
    "react-native-animatable": "^1.3.3",
    "react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera.git",
    "react-native-confirmation-code-field": "^6.0.0",
    "react-native-custom-actionsheet": "^0.1.1",
    "react-native-device-info": "^5.6.1",
    "react-native-drop-shadow": "^0.0.2",
    "react-native-easy-content-loader": "^0.3.2",
    "react-native-fast-image": "^8.3.2",
    "react-native-flags": "^1.0.0",
    "react-native-gallery-swiper": "^1.26.4",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-masked-text": "^1.13.0",
    "react-native-outlined-input": "https://hasan_1995@bitbucket.org/hasan_1995/react-native-material-outlined-input.git",
    "react-native-paper": "4.0.0-alpha.0",
    "react-native-permissions": "^2.2.2",
    "react-native-push-notification": "^4.0.0",
    "react-native-reanimated": "^1.7.1",
    "react-native-restart": "^0.0.17",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.11.0",
    "react-native-share": "^3.7.1",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.0",
    "react-native-svg-flagkit": "^0.9.5",
    "react-native-swiper": "^1.6.0",
    "react-native-tab-view": "^2.14.4",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^10.7.0",
    "yup": "^0.28.3"
  }

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by HasanSahabGlobal** [comment]
OK i will do that ASAS.
thank you

**Comment by rphlmr** [comment]
We have some crash with Android devices only (one plus, xiaomi).
It occurred when we swipe on left side (when we are on the first tab).
It seems to be an issue with index. But I have no clue.

To prevent that (can't repro on simulator) we change the pager.

```
import ViewPagerAdapter from "react-native-tab-view-viewpager-adapter";

 <TopTab.Navigator
        pager={(props) => <ViewPagerAdapter {...props} />}>
  ...

 </TopTab.Navigator>
```

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Comment by HasanSahabGlobal** [comment]
@WoLewicki thank you

**Comment by WoLewicki** [comment]
@HasanSahabGlobal did you manage to reproduce it?

**Comment by HasanSahabGlobal** [comment]
i will do it ASAS

**Comment by marcodiloreto** [comment]
what the fuck

**Comment by Pradeepd15594** [comment]
i am getting issue with 5 tabs sceeen and evey change input need to rerender tabs,

**Comment by tboba** [comment]
Hi @Pradeepd15594, this seems to be different situation from what the issue is about 👀 
If you feel this is a bug, feel free to create an issue with steps to reproduce (including minimal repro). I don't quite understand what `every change input` means in your case, but this could be the wrong usage of `useState` hook (or just a natural logic of React).
