### ISSUE TITLE
[iOS crash] with react-native-screens version 2.11.0 and ViewPager

### ISSUE THREAD

**Issue by yodaheis** [software-mansion/react-native-screens#676]
Package info:
* react-native-screens: 2.11.0
* @react-native-community/viewpager: 4.1.6
* expo: 39.0.3

On Android, ViewPager works fine.
But on iOS, it crashes with the following message:
Downgrading the library to previous version: 2.10.1 seems to work fine

![IMG_2063](https://user-images.githubusercontent.com/22661681/96747651-2939ed00-13e6-11eb-953f-11552d646fea.PNG)

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
