### ISSUE TITLE
BottomTabNavigator hide/show bug in Native Stack

### ISSUE THREAD

**Issue by VanDu97** [software-mansion/react-native-screens#678]
I had a problem with BottomTabNavigation have some Stack in there.
 "@react-navigation/stack": "^5.9.3"
"react-native-screens": "^2.11.0",

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by VanDu97** [comment]
The same issues was https://github.com/software-mansion/react-native-screens/issues/364

**Comment by WoLewicki** [comment]
So if it is a duplicate of #364, can I close it then? Unfortunately, I cannot help you more than what is mentioned there already.

**Comment by VanDu97** [comment]
but not solved. Please fix this!

**Comment by WoLewicki** [comment]
Can you check if #680 fixes your issue? It seems to fix the problem for the code given in #364.

**Comment by VanDu97** [comment]
> Can you check if #680 fixes your issue? It seems to fix the problem for the code given in #364.

Thank you for your help. It's fixed my problem.

**Comment by WoLewicki** [comment]
#680 was closed in favor of #712. It fixes the issue of #364 from what I tested and seems not to introduce new, wrong behavior.
