### ISSUE TITLE
tvOS RNScreens build errors

### ISSUE THREAD

**Issue by dktrvamp** [software-mansion/react-native-screens#686]
![Screen Shot 2020-10-28 at 6 04 25 pm](https://user-images.githubusercontent.com/8250990/97605289-13bf5700-19d4-11eb-832d-615fb41eeec1.png)
React Native For TVOS:
"react-native": "npm:react-native-tvos@0.63.1-1",

Breaks tvOS
"react-native-screens": "^2.12.0",

downgraded to and it works fine
"react-native-screens": "2.11.0",

**Comment by WoLewicki** [comment]
Can you check if applying #675 resolves all the issues with tvOS? I tried to add the checks in all places there.

**Comment by dktrvamp** [comment]
@WoLewicki I am a bit confused. #675 is part of the `2.11.0` version. This bug I reported was introduced in `2.12.0` 
Here is what I did.
I installed the following dependency:  `"react-native-screens": "software-mansion/react-native-screens#675/head", `
however my `yarn.lock` shows
```
react-native-screens@software-mansion/react-native-screens#675/head:
  version "2.11.0"
  resolved "https://codeload.github.com/software-mansion/react-native-screens/tar.gz/55f3ea54b1f7d988c7ad62512b15021e3e10c9ea"
```

Please Advise!

**Comment by WoLewicki** [comment]
#675 is not merged so it is not available in 2.11.0. Did you copy all the changes from the file on the screenshot? I added checks there: https://github.com/software-mansion/react-native-screens/pull/675/files#diff-c58852b1c4aee1faddadefe30184a27d6598427b60dcf335c889df3e03d55424R8 which I cannot see on your screenshot.

**Comment by WoLewicki** [comment]
The bugs were introduced in `2.12.0` because the other PR (#642), which is first available in `2.12.0`, introduced them.

**Comment by WoLewicki** [comment]
@dktrvamp can you check if #724 fixes all the problems with the compilation?

**Comment by csantos1113** [comment]
> @dktrvamp can you check if #724 fixes all the problems with the compilation?

Hi @WoLewicki - I tried this in my project:
```
"react-native-screens": "software-mansion/react-native-screens#724/head",
```

and now got the following errors:
<img width="1272" alt="Screen Shot 2020-12-15 at 6 37 05 PM" src="https://user-images.githubusercontent.com/9648559/102285642-b12f0580-3f04-11eb-8d1b-73fda47a0778.png">
