### ISSUE TITLE
RCTImageLoader.h not found error (IOS) RN0.60.6

### ISSUE THREAD

**Issue by joshua-augustinus** [software-mansion/react-native-screens#688]
Current Behavior

Build error in XCode. RCTImageLoader.h not found.
See image:
https://i.stack.imgur.com/49P3q.png

Expected Behavior
No build error.

How to reproduce

Create a react native project with v0.60.6
Add react-navigation v4
Add dependencies by following tutorial.
Add AppContainer and StackNavigator.
Build project in Xcode.

Example minimal repo: https://github.com/joshua-augustinus/react-navigation-training

Your Environment

software | version
-- | --
iOS or Android | IOS 14.1
react-navigation | 4.4.3
react-navigation-stack | 2.9.0
react-navigation-tabs | N/A
react-navigation-drawer | N/A
react-native-reanimated | 1.13.1
react-native-gesture-handler | 1.8.0
react-native-safe-area-context | 3.1.8
react-native-screens | 2.12.0
react-native | 0.60.6
node | 12.9.0
yarn | 1.22.10

**Comment by joshua-augustinus** [comment]
I have tested the solution from here:
https://github.com/software-mansion/react-native-screens/issues/281#issuecomment-585859427

but it doesn't seem to work with react native 0.60.6.

When I change the podfile with the solution I get the error:
```
[!] No podspec found for `React-CoreModules` in `../node_modules/react-native/React/CoreModules`
```

**Comment by fdwcomune** [comment]
A workaround that worked for me was to downgrade `react-native-screens` to `v2.11.0`. Seems like something in the latest version (`v2.12.0`) changed something that caused this issue.

---

My app environment:

- react-native: 0.60.2
- iOS: 14.1

**Comment by joshua-augustinus** [comment]
Thanks @fdwcomune it worked after I downgraded.

**Comment by eschos24** [comment]
Downgrading to 2.11.0 fixed it for me too. The docs need to be updated to reflect that `react native 0.60.x` does not work with `react-native-screens v 2.12.x`.
