### ISSUE TITLE
Modal doesn't close when navigating to another tab.

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/react-native-screens#691]
Hey there, I am using the `native-stack`.

I have a bit of an issue. I have stacks nested inside tabs. **I'm trying to close a modal when I jump to another tab. However, the modal stays open when I jump from one tab to another.**

## Current Behavior

`Tab1` opens a `modal`. User places an order. This needs to send the user to `Tab2` (where I can see my orders.)

```sh
- Tab1
  - Stack
      - Screen
      - Modal
- Tab 2 (Orders)
```

## Illustration

```tsx
// Modal inside of Tab1
import { TabActions, useNavigation } from '@react-navigation/native';

const { navigate, dispatch } = useNavigation()

const placeOrder = async () => {
  const success = await order()
  // ok, let's now close this modal and send the user to Tab2
  dispatch(TabActions.jumpTo('Orders')) // jumps tabs, but the modal stays open
}
```

I would expect this to do two things: **1)** close the modal, **2)** jump to tab 2. It does indeed jump to tab 2. However, the modal stays open. I'm not really sure what the proper behavior is, or how to handle this.

### I've also tried...

I tried using `popToTop()` before `jumpTo('Orders')`, but then it never changes tabs. Same goes for `goBack()`.

```tsx
// tab1 modal
import { StackActions, useNavigation } from '@react-navigation/native';

const { navigate, dispatch } = useNavigation()

const placeOrder = async () => {
  const success = await order()
  // ok, let's now send the user to tab2
  dispatch(StackActions.popToTop()) // pops to main tab screen
  dispatch(TabActions.jumpTo('Orders')) // this never happens
}
```

In this case, it does indeed pop to the main tab navigator, but it never goes to the `Orders` tab.

**Comment by WoLewicki** [comment]
The modal is not dismissed because the tab in which it is rendered is not unmounted on the JS side, so the modal is not dismissed, and unfortunately, the native iOS modal is rendered above almost anything else in the native view hierarchy and so it is not unmounted there too on the tab change.

One option I can think of is to use https://reactnavigation.org/docs/bottom-tab-navigator#unmountonblur on the screen with `Stack`, which should work ok but can have unwanted side effects since it unmounts the screen.

Second option is to use `navigation.reset()` in `placeOrder`, something like 
```js
navigation.reset({
              index: 1,
              routes: [
                {name: 'Tab1'},
                {name: 'Tab2'},
              ],
            })
```

Does applying one of those options fix your issue?

**Comment by nandorojo** [comment]
Hey thanks a lot for the response.

I don't know if unmount is what I'm looking for. Would this mess with other screens lower in the stack? All I want to do is close this modal in particular, although I'm willing to pop to the top of the stack.

Reset _may_ work, I can try that out. It seems a bit low-level; am I resetting my entire navigation? I'm a bit worried that if I change tabs around in the future or something, `reset` might break my app. Not sure if that's a realistic worry or not since I've ever used it before. I ideally wouldn't have to keep track of the global navigation state just to jump tabs. 

That said, I'll test out `reset`. If it's the best option and it works, I suppose I'll stick with that. Thanks again!

**Comment by WoLewicki** [comment]
Did you manage to make it work? Can I help you any more with this?

**Comment by nandorojo** [comment]
Hey thanks for following up. I haven't yet, but I can close this for now while I keep experimenting. I'll report back if I have new info. Thanks again your help, really appreciate it.

**Comment by miticous** [comment]
I solved this issue by adding a navigation event listener to control when modal show up or not with some flag to prevent modal shown on screen load at the first time... Example:

```
  React.useEffect(() => {
    const unsubscribe = navigation.addListener('blur', () => {
      setShowSuccessModal(false);
    });

    return unsubscribe;
  }, [navigation]);

  React.useEffect(() => {
    const unsubscribe = navigation.addListener('focus', () => {
      if (switcherScreenIndex === Screens.USER_DEFINE_PASSWORD) {
        setShowSuccessModal(true);
      }
    });

    return unsubscribe;
  }, [navigation, switcherScreenIndex]);
```

**Comment by nandorojo** [comment]
Could you show some more code? Not sure I'm getting the full context here. Does this go on the modal, or the child component?

**Comment by ilkerceng** [comment]
thanks so much @miticous. I use 'blur' event and it's much faster than [useFocusEffect](https://reactnavigation.org/docs/use-focus-effect/)

**Comment by sadewole** [comment]
Had the same issue with @nandorojo and I was able to solve it by adding an event listener and removing stack after blur.
For reusability, I created a hook for it.

```
import {useEffect} from 'react';
import {StackActions, useNavigation} from '@react-navigation/native';

export const useUnsubscribe = () => {
  const navigation = useNavigation();

  return useEffect(() => {
    const unsubscribe = navigation.addListener('blur', () => {
      navigation.dispatch(StackActions.pop());
    });

    return unsubscribe;
  }, [navigation]);
};

```

**Comment by ser-emejia** [comment]
Had similar issue, when my modal is open and try to navigate to other screen the modal keeps open, so, I don't know if this is a good solution, but solve my issue, what do you guys think?

I create a custom hook:

```
const useWaitForModalClose = () => {
  const navigation = useNavigation();

  return useCallback(
    (onClose: () => void, timeout: number = 500) => {
      navigation.goBack();
      setTimeout(onClose, timeout);
    },
    [navigation]
  );
};

export default useWaitForModalClose;
```

In my modal:

```
  function navigateToScreen() {

    waitForModalClose(() => {
      navigation.dispatch(
        StackActions.push('SomeScreen', {
          param:, someParam
        })
      );
    });
  }
```

**Comment by chr4ss12** [comment]
old thread however you can follow convention that any modal you have has 'Modal' in it, and then you can close all modals like this:

  closeModals() {
    navigationRef.dispatch(state => {
      const routes = state.routes.filter(route => !route.name.includes('Modal'));
      return CommonActions.reset({
        ...state,
        routes,
        index: routes.length - 1,
      });
    });
  }
