### ISSUE TITLE
Make header left/right insets configurable

### ISSUE THREAD

**Issue by martinandert** [software-mansion/react-native-screens#692]
Currently, the insets (paddings from the edge of the window) for custom `headerLeft` and `headerRight` views can not be adjusted. It always uses the default insets on iOS and Android (probably these values are provided by the system).

Pull request #350 proposed making the insets customizable, but it was dismissed, I suppose because of [this comment](https://github.com/software-mansion/react-native-screens/issues/332#issuecomment-591912481):

> [...] I'd like to avoid adding too many settings to header [...]

We have a use case where it would be nice if we were able to control the inset sizes:

We have a screen that renders a web view, so we added "go back" and "go forward" buttons to the header to control the navigation inside the web view. It looks like this:

<img src="https://user-images.githubusercontent.com/6715978/98085176-3db5c500-1e7d-11eb-811e-ee00656d63b7.png" width="500" />

As you can see, this doesn't look good, as the buttons -- due to the fixed insets -- appear too far away from the left and right window edges (reducing also the space available for the title). This is because we added padding around the small-ish chevron icons in order to increase the hit area of these buttons. Here's the same screenshot, but this time with outlines around the hit areas:

<img src="https://user-images.githubusercontent.com/6715978/98085839-36db8200-1e7e-11eb-95c4-d045f7738013.png" width="500" />

If there was a way to customize the insets, we could make it look like this instead:

<img src="https://user-images.githubusercontent.com/6715978/98086160-a2255400-1e7e-11eb-87e3-b86c9bd8114c.png" width="500" />

This is much better, isn't it?

Here's the same screenshot again, showing the hit areas:

<img src="https://user-images.githubusercontent.com/6715978/98086531-342d5c80-1e7f-11eb-8ffa-9a137b284dbf.png" width="500" />

So this is exactly what we need. 

As a workaround, we could style the buttons with negative margins in order to move them to the desired positions, but this affects the hit areas negatively:

<img src="https://user-images.githubusercontent.com/6715978/98087177-04328900-1e80-11eb-964c-3d3ed761865a.png" width="500" />

It's effectively reducing the chance the user is actually able to hit the button with their thumb / finger by half.

This isn't iOS specific. It also applies to Android.

To further prove my point, here are screenshots of the stock iOS and Android back buttons, with outlines added around their hit areas:

<img src="https://user-images.githubusercontent.com/6715978/98087583-9b97dc00-1e80-11eb-8b8d-682047e61a30.png" width="500" />

<img src="https://user-images.githubusercontent.com/6715978/98087687-c4b86c80-1e80-11eb-9f8c-1fbec227430c.png" width="500" />

As you can see, although the content of the back buttons appears inset from the left edge of the header / toolbar, their hit areas actually extend to the very edge.

Given all that, please consider adding `headerLeftInset` and `headerRightInset` options. In order to not break existing apps, these could be `undefined` by default, rendering the inset sizes as they currently are.

**Comment by alminde** [comment]
This is something we need as well. The hit areas are just too small. I‘ve tried all combinations of margins, paddings, hit slops, but to no avail.

Does anyone know how to do this with UIKit so we can PR or patch-package it?

@martinandert Did you find a suitable workaround for this?

**Comment by martinandert** [comment]
> Did you find a suitable workaround for this?

Unfortunately not. We're using managed expo, so our ability to patch native code is very limited.

**Comment by Jobeso** [comment]
The only way I found till now is using negative margin, e.g. `marginLeft: -8` for headerLeft.

**Comment by dancixx** [comment]
Is there any update on this topic?

**Comment by iBhavesh** [comment]
I am facing the same issue. I am using react-navigation-header-buttons I reduced the margin by using negative MarginRight on the item

```javsacript
useLayoutEffect(() => {
  navigation.setOptions({
    headerRight: () => (
      <HeaderButtons HeaderButtonComponent={FavouriteHeaderButton}>
        <Item
          title="Fav"
          iconName={iconName}
          onPress={toggleFavourite}
          style={{ marginRight: -15 }}
        />
      </HeaderButtons>
    ),
  });
}, [navigation, iconName]);
```

**Comment by chinieer** [comment]
> react-navigation-header-buttons

I had think about this solution,but the extra 15 space will not animate when u go back by gesture right,it looks so strangely

**Comment by chinieer** [comment]
> I am facing the same issue. I am using react-navigation-header-buttons I reduced the margin by using negative MarginRight on the item
> 
> ```
> useLayoutEffect(() => {
>   navigation.setOptions({
>     headerRight: () => (
>       <HeaderButtons HeaderButtonComponent={FavouriteHeaderButton}>
>         <Item
>           title="Fav"
>           iconName={iconName}
>           onPress={toggleFavourite}
>           style={{ marginRight: -15 }}
>         />
>       </HeaderButtons>
>     ),
>   });
> }, [navigation, iconName]);
> ```

I had think about this solution,but the extra 15 space will not animate when u go back by gesture right,it looks so strangely

**Comment by WoLewicki** [comment]
I made a PR that hopefully fixes the issue on `iOS`: #1157. Can you check if it works and does not introduce any new problems?

**Comment by SimpleCreations** [comment]
@WoLewicki I've tried the PR and it doesn't seem to work. I have a `TouchableOpacity` button in `headerRight` that is shifted closer to the right edge with negative margin. Pressing the right edge of the button still has no effect. `hitSlop` doesn't help either.
iOS 14.5, iOS 12.5.

**Comment by WoLewicki** [comment]
@SimpleCreations I changed the implementation a bit, can you check again? And if it still does not work correctly, can you provide a reproduction of the issue?

**Comment by SimpleCreations** [comment]
@WoLewicki seems to be working now, thank you!

**Comment by rumax** [comment]
Issue is closed but problem still exists in

> "react-native-screens": "^3.18.2"

![image](https://user-images.githubusercontent.com/2707180/204821572-ec6fd57b-fbfe-41d5-9798-9a7acb25d3aa.png)

What is the solution to render left and right buttons without extra spaces on left and right?

**Comment by WoLewicki** [comment]
Doesn't applying margin like in this comment: https://github.com/software-mansion/react-native-screens/issues/692#issuecomment-913808627 work?

**Comment by dFelinger** [comment]
Negative margin doesn't help. It still not pressable in that space.

> Doesn't applying margin like in this comment: [#692 (comment)](https://github.com/software-mansion/react-native-screens/issues/692#issuecomment-913808627) work?

**Comment by khunghang16** [comment]
+1

**Comment by DongGukMon** [comment]
I found something strange in the solution that gives minus margin. When I used the version @react-navigation/native-stack 6.9.10, I didn't have a problem with the hit area even if I gave a negative margin, but when I upgraded it to 6.9.17, the same problem occurred. In my experience, 6.9.10 only had a problem with narrowing the hit area when I gave the renderBackground option. Why did the problem get fixed and then relapsed?

**Comment by jetaggart** [comment]
Is there any progress on this? This bug has been around for a while and the negative margin workaround really affects hit areas.

**Comment by jetaggart** [comment]
For reference, this is a marginLeft of -16 which aligns it with the default back button if it's not configured. It's strange that it is so mis-aligned if we provide our own button but the default button is exactly where it should be. Notice the hitbox vs where the icon is rendered. I can't see any way of fixing this.

<img width="152" alt="Screenshot 2024-02-23 at 3 54 18 PM" src="https://github.com/software-mansion/react-native-screens/assets/161737/aa18ed5b-560e-42fd-a3fd-4afd2ed1ff2d">

**Comment by VariabileAleatoria** [comment]
This issue should be reopened as there is still not a solution. We need a reliable solution that does not affect negatively the hitbox (if we care about accessibility)

**Comment by kligarski** [comment]
Margin workaround should work on iOS after this PR is merged: https://github.com/software-mansion/react-native-screens/pull/3446. On iOS 26, you need to use `unstable_headerLeft/RightItems` with `hidesSharedBackground: true`.

https://github.com/user-attachments/assets/655e9097-6089-4851-abd4-202dc788a71b
