### ISSUE TITLE
How could I implement a toaster

### ISSUE THREAD

**Issue by timurridjanovic** [software-mansion/react-native-screens#693]
## Description

Is there a way that I could implement a toaster that could show up on top of the modals?
I could just move the <Toaster /> component inside the modal but then if I close the modal while the toaster is showing, the toaster will animate away alongside the modal.. Ideally it would be great if I could have some sort of global component that
could show on top of all screens (even modals).. Seems like perhaps this might not be possible while using native screens..
Has anybody run into this issue and found a solution?

**Comment by WoLewicki** [comment]
There is already a discussion about it in #525. I will close it to keep the discussion in one place. Feel free to comment if you have any questions.
