### ISSUE TITLE
Overriding onCreate causes compileDebugJavaWithJavac to fail.

### ISSUE THREAD

**Issue by yfunk** [software-mansion/react-native-screens#696]
I have started using _react-native-screens_  with _react-navigation_, but I'm facing an issue where compileDebugJavaWithJavac fails when I add the Override for onCreate [mentioned in the installation instructions](https://github.com/software-mansion/react-native-screens#android) to my `MainApplication.java`.

```
> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
61 actionable tasks: 2 executed, 59 up-to-date
C:\Users\...\MyApp\android\app\src\main\java\com\myapp\MainActivity.java:17: error: cannot find symbol
  protected void onCreate(Bundle savedInstanceState) {
                          ^
  symbol:   class Bundle
  location: class MainActivity
Note: C:\Users\yfunk\Desktop\MyApp\android\app\src\debug\java\com\myapp\ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.
```

Since I'm using a considerable amount packages and made a few changes to native code I set up a new React Native project based on the TypeScript template using `npx react-native init MyApp --template react-native-template-typescript` to see if the issue also occurs. After adding the Override to my `MainActivity.java` i was facing the same issue.

**MainActivity in test project:**
```java
package com.myapp;

import com.facebook.react.ReactActivity;

public class MainActivity extends ReactActivity 
{
  @Override
  protected String getMainComponentName() {
    return "MyApp";
  }

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(null);
  }   
}
```

**Dependencies in test project:**
```
"@react-native-community/masked-view": "^0.1.10",
"@react-navigation/native": "^5.8.7",
"@react-navigation/stack": "^5.12.4",
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-gesture-handler": "^1.8.0",
"react-native-reanimated": "^1.13.1",
"react-native-safe-area-context": "^3.1.8",
"react-native-screens": "^2.13.0"
```

**Comment by yfunk** [comment]
The solution turned out to be as simple as adding a missing `import android.os.Bundle` statement.
Since most people probably use something like VSCode as opposed to an IDE with auto imports for making small changes to native code I feel like this should be mentioned in the instructions.

**Comment by WoLewicki** [comment]
I made a PR with more information in README: #697. Does it solve the issue?
