### ISSUE TITLE
[Android] Enlarged AppBarLayout

### ISSUE THREAD

**Issue by m-ruhl** [software-mansion/react-native-screens#699]
Hello,

it seems that in Android the AppBarLayout is enlarged.

### Screenshots

![react_navigation_screens](https://user-images.githubusercontent.com/867772/98688361-0ce8fa80-236b-11eb-80cd-add5902638d2.png)

## Steps To Reproduce

Not sure how to reproduce it.. I checked out the sample and there it was fine

### Expected behavior

If I switch back to `createStackNavigator`it is rendered correctly

![react_native_navigation](https://user-images.githubusercontent.com/867772/98688416-1a9e8000-236b-11eb-80b3-623f17a6204c.png)

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Screens: 2.13.0

**Comment by WoLewicki** [comment]
If you mean the height of the header, please refer to release notes: https://github.com/software-mansion/react-native-screens/releases/tag/2.9.0, where it is explained. Can I help you more with it?

**Comment by m-ruhl** [comment]
yeah, I meant the header.. thanks 👍
