### ISSUE TITLE
Lottie animations do not show

### ISSUE THREAD

**Issue by slorber** [software-mansion/react-native-screens#70]
Hi,

I have some Lottie animations. 
They do play well inside Storybook, but once in my app, when I add `useScreens()`, the animations do not show.

I'm on Expo SDK 32 and react-navigation 2.x

Will report if this works when I migrate to newer versions

**Comment by WoLewicki** [comment]
Does the issue still exist or can I close it @slorber ?

**Comment by slorber** [comment]
I don't know, @xcarpentier could you check?

**Comment by xcarpentier** [comment]
@WoLewicki Yes, you can close it :)
