### ISSUE TITLE
src/index.js is missing a shouldUseActivityState export

### ISSUE THREAD

**Issue by TikiTDO** [software-mansion/react-native-screens#701]
## Description

As of 2.14 the `src/index.native.js` file exports a `shouldUseActivityState` value, while the `src/index.js` file does not. This triggers a warning when using `react-navigation` in conjunction with `react-native-web`. 

The fallback `index.js` should export some sort of value for this variable to align the APIs.

### Expected behavior

Expect no `react-native-screens` related warnings when running using above environment.

### Actual behavior

Receive build-time warning.

## Package versions

- React Native Screens: 2.14

**Comment by WoLewicki** [comment]
Does #709 resolve your issue?

**Comment by TikiTDO** [comment]
Yep, looks great, thanks. I'll close this issue.
