### ISSUE TITLE
Push animation between screens not working

### ISSUE THREAD

**Issue by longprao** [software-mansion/react-native-screens#702]
This is the version that was working for me:

```
    "@react-navigation/bottom-tabs": "^5.10.2",
    "@react-navigation/native": "^5.8.2",
    "@react-navigation/stack": "^5.11.1",
    "react": "17.0.1",
    "react-native": "0.63.3",
    "react-native-screens": "^2.12.0",
```

I recently updated to this version and on iOS, navigation no longer has any animation, it happens instantly:

```
    "@react-navigation/bottom-tabs": "^5.11.1",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.6",
    "react": "17.0.1",
    "react-native": "0.63.3",
    "react-native-screens": "^2.14.0",
```

I have deleted Podfile.lock and `npx pod-install ios`, still not work.

When I changed `createNativeStackNavigator()` to `createStackNavigator()`, it worked fine again with animation.

Please let me know if it's a bug or what config I need to use to have the slide (push) animation?

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by dylancom** [comment]
Same here since I updated from version 2.12. Going to a new screen doesn't show an animation anymore. Navigating back to a screen shows an animation though.

**Comment by WoLewicki** [comment]
@dylancom please provide a repo that shows this bug so I can work on it.

**Comment by longprao** [comment]
@dylancom hey thanks for that, I'm using exactly the same thing too.

**Comment by WoLewicki** [comment]
I tested the reproduction and I can spot this bug too. Until we find the solution, the workaround is to set `detachInactiveScreens` to `false` on iOS in the `stack` navigator.

**Comment by WoLewicki** [comment]
@longprao @dylancom can you check if #714 resolves the problem?
