### ISSUE TITLE
Enabling the status bar causes a crash for react-navigation navigator screens

### ISSUE THREAD

**Issue by hsavit1** [software-mansion/react-native-screens#708]
## Description

Turning on the UIViewController native status bars eliminates the possibility of using react navigation's status bar, which requires

```
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
```

This makes it extremely difficult for me to add createStackNavigator to my project that previous did not use createStackNavigator

**Comment by WoLewicki** [comment]
Yes, you should use only one of those options since they are mutually exclusive. Can I help you more with this?

**Comment by WoLewicki** [comment]
I check the `react-navigation` code and I can see that `drawer` navigator uses `StatusBar.setHidden()` with the `hideStatusBar` option. This method cannot be used on iOS with `native-stack`'s `StatusBar` management. You need to choose which of the options to use.

**Comment by WoLewicki** [comment]
I am closing this issue since I don't know if there is something at the side of `react-native-screens` that can be done. Please comment here if you have any questions.

**Comment by hsavit1** [comment]
I think the StatusBar section of the readme just needs to be updated a bit to reflect that it should not be added to projects that use createStackNavigator status bars

**Comment by WoLewicki** [comment]
Do you mean `createDrawerNavigator`? I couldn't find any usages of `StatusBar` in `createStackNavigator`.

**Comment by hsavit1** [comment]
no I meant createStackNavigator, why wouldnt `StatusBar` have use in createStackNavigator? It is something that comes from react native https://reactnative.dev/docs/statusbar

**Comment by WoLewicki** [comment]
But it is not directly used by `createStackNavigator`, so how is it connected directly to the `stack-navigator`? You can use `createStackNavigator` without using `StatusBar`. I am not sure if I understand you.
