### ISSUE TITLE
 stackPresentation: 'modal' not working in ios 11.x

### ISSUE THREAD

**Issue by VanDu97** [software-mansion/react-native-screens#715]
- React Native:0.63.3
- React Native Screens:2.11.0

**Comment by WoLewicki** [comment]
The description you gave is not enough for me to work on that issue. Is it the same problem as in #436? If not, can you be more descriptive?

**Comment by VanDu97** [comment]
In ios 11.x When I set screen stackPresentation ='modal'. It's not showing up modal.It's kind of full modal.

**Comment by WoLewicki** [comment]
On iOS < 13, using `modal` presentation resolves `fullScreen` modal (see https://github.com/software-mansion/react-native-screens/blob/master/ios/RNSScreen.m#L86). You can try and use other options, probably `formSheet` will give you what you want. Can I help you more with this?

**Comment by VanDu97** [comment]
> https://github.com/software-mansion/react-native-screens/blob/master/ios/RNSScreen.m#L86
I use formSheet not working the same modal.
how to use modal in ios < 13?

**Comment by WoLewicki** [comment]
You used `stackPresentation: 'formSheet'` and it still shows `fullScreen` modal?

**Comment by VanDu97** [comment]
> You used `stackPresentation: 'formSheet'` and it still shows `fullScreen` modal?

yes. It's stills fullcreen

**Comment by WoLewicki** [comment]
It looks like on iOS pre 13, the fullScreen modals were the only ones available for iPhone. You can read more about it e.g. here: https://hacknicity.medium.com/view-controller-presentation-changes-in-ios-13-ac8c901ebc4e. It also tackles what other options resolve to on different devices. Can I help you more with this?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
