### ISSUE TITLE
Pod install fails due to source pointing at tag on Github

### ISSUE THREAD

**Issue by brentvatne** [software-mansion/react-native-screens#72]
`warning: Could not find remote branch 1.0.0-alpha.22 to clone.` - the tag doesn't exist on this repo :)

**Comment by nkovacic** [comment]
Any chance of adding this tag? Would simplify a lot the linking and CI process.

**Comment by brentvatne** [comment]
I created a release tag for this so it should work: https://github.com/kmagiera/react-native-screens/releases/tag/1.0.0-alpha.22
We should change how the podspec works or be sure to tag releases in the future cc @kmagiera

**Comment by WoLewicki** [comment]
Does this issue still exist or can I close it?

**Comment by brentvatne** [comment]
not a problem anymore @WoLewicki!
