### ISSUE TITLE
Not able to use Animated to animate the transparency of the header.

### ISSUE THREAD

**Issue by wahiche** [software-mansion/react-native-screens#725]
## Description

I am trying to make the React Navigation header change it's transparency from 0 to .95 and back to 0 while scrolling up and down.  I have followed many different methods to get this working but it does not work with the **createNativeStackNavigator**, but it does work with **createStackNavigator**.

I surmise this is because the way it gets handled is adding the opacity to the **headerBackground**, which does not exist with the Native Stack.

I have also noticed that when scrolling I do not see the change in the **headerOpacity** value when I try log it in the useEffect hook.  It only does it once, and never calls it again.

## Code
```const yOffset = useRef(new Animated.Value(0)).current;
const headerOpacity = yOffset.interpolate({
  inputRange: [0, 200],
  outputRange: [0, 1],
  extrapolate: "clamp",
});

<Animated.ScrollView
  onScroll={Animated.event(
    [
      {
        nativeEvent: {
          contentOffset: {
            y: yOffset,
          },
        },
      },
    ],
    { useNativeDriver: true }
  )}
  scrollEventThrottle={16}
>

useEffect(() => {
  navigation.setOptions({
    headerStyle: {
      opacity: headerOpacity,
    },
    headerBackground: () => (
      <Animated.View
        style={{
          backgroundColor: "white",
          ...StyleSheet.absoluteFillObject,
          opacity: headerOpacity,
        }}
      />
    ),
    headerTransparent: true,
  });
}, [headerOpacity, navigation]);
```

### Package versions

- Expo: 38.0.0
- React: 16.11.0
- React Native: 0.63
- React Native Screens: 2.9.0

**Comment by WoLewicki** [comment]
`native-stack` exposes the `backgroundColor` prop on the `headerStyle` object, which is probably what you are looking for. You can check it here: https://github.com/software-mansion/react-native-screens/tree/master/native-stack#headerstyle. Remember that the component for the header in `native-stack` is not written in JS, but instead passes props to the native side, where the platform-specific component is used. Can I help you more with this?

**Comment by wahiche** [comment]
So I tried to update that background color by trying to chagne the rgba value like this

```
backgroundColor: `rgba(0,0,0, ${headerOpacity})`
```
The problem is that it never changed.  Just showed white.

I have no other way of explaining my issue, or how to actually get it to work.  If you have a working example of the React Navigator Native version changing the background opacity while scrolling up and down, in a snack, that would be ideal.

Thanks.

**Comment by xmflsct** [comment]
@wahiche I get a state to it and it works. But it is not smooth. Any suggestions?

**Comment by WoLewicki** [comment]
@xmflsct can you provide a reproduction of how you do it so we can work on it?

**Comment by xmflsct** [comment]
@WoLewicki Sure!

So my stack has one screen like this:
```
    const [opacity, setOpacity] = useState(0)

    <Stack.Screen
      name='name'
      options={({ navigation }) => {
        return {
          headerTranslucent: true,
          headerStyle: {
            backgroundColor: `rgba(255, 255, 255, ${opacity / 200})`
          },
          headerCenter: () => null,
          )
        }
      }}
    >
      {({
        route
      }: {
        route: {
          params: {
            id: string
          }
        }
      }) => <SomeComponent route={route} setOpacity={setOpacity} />}
    </Stack.Screen>
```

And then in my component:
```
    <ScrollView
      bounces={false}
      onScroll={({nativeEvent}) => setOpacity(nativeEvent.contentOffset.y)}
      scrollEventThrottle={10}
    >
      ......
    </ScrollView>
```

**Comment by wahiche** [comment]
I am on break from work for a couple of weeks but I will try this out and let you know if I was successful.  Thank you very much.

**Comment by wahiche** [comment]
I have used this solution, but there is still something that is not happening and I am not sure how to handle it. 

First thing is I want to go from transparent to black, at a gradual rate, which is what you have in your example, but the big difference is yours is going from to white, and I want mine to go to black.  When I do that I notice that the large title scrolls up and is transparent, but then the header with the title in the center is white and then goes from white to black, not from transparent.

It seems like there are two headers to handle this transition, but I am not sure how to stop this from happening.

**Comment by WoLewicki** [comment]
@wahiche there are two options, each of them controlling the [small](https://github.com/software-mansion/react-native-screens/tree/master/native-stack#headerlargestyle-ios-only) / [large](https://github.com/software-mansion/react-native-screens/tree/master/native-stack#headerstyle) header style. Maybe you should properly use each of them to aquire the behavior you need?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days and I am not sure if there is something more to be done here. Feel free to comment to reopen it.
