### ISSUE TITLE
Header shadow appearance on iOS

### ISSUE THREAD

**Issue by thomasgosse** [software-mansion/react-native-screens#728]
## Description

Hi, first, thanks to the maintainers of this nice library !

I just wanted to know if there was a way to set an appearance prop for the header shadow. The color changes automatically when phone is in dark or light theme. As I don't support dark theme in my app yet, the dark divider can appear almost transparent, I would like to know if there is some way to force the color divider to "light" ?

Ex:

"Light" mode
<img src="https://i.ibb.co/3v31T0W/Capture-d-e-cran-2020-12-01-a-16-18-45.png">

"Dark" mode
<img src="https://i.ibb.co/KWzdMMf/Capture-d-e-cran-2020-12-01-a-16-19-10.png">

Of course I could juste changed the background color of my header but I think it would be nice to have a control on this !

### Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Screens: 2.15.0

**Comment by WoLewicki** [comment]
You can remove header shadow by using: https://github.com/software-mansion/react-native-screens/blob/master/src/native-stack/types.tsx#L122 or https://github.com/software-mansion/react-native-screens/blob/master/src/native-stack/types.tsx#L144. Is it what you need?

**Comment by thomasgosse** [comment]
No, I would like something like a color setting !
I want the shadow to be shown, but I want to lock the color appearance to "light", because in the actual version, it seems it colors switch automatically when the color scheme of the phone changes 😕

**Comment by ocarreterom** [comment]
You can disable dark mode in your iOS app:
> The system automatically opts in any app linked against the iOS 13.0 or later SDK to both light and dark appearances. If you need extra time to work on your app's Dark Mode support, you can temporarily opt out by including the UIUserInterfaceStyle key (with a value of Light) in your app’s Info.plist file. Setting this key to Light causes the system to ignore the user's preference and always apply a light appearance to your app.

https://developer.apple.com/documentation/xcode/supporting_dark_mode_in_your_interface/choosing_a_specific_interface_style_for_your_ios_app

**Comment by thomasgosse** [comment]
Perfect, I didn't know about that. I will use this solution and close the issue.

Thank you for your time 😀

**Comment by wibb36** [comment]
@WoLewicki removing header shadow and create your own maybe, will not be the best solution.

@ocarreterom setting `UIUserInterfaceStyle` to 'Light' solves @thomasgosse issue. How about if one actually supports both modes (light and dark) and has a preference setting to change the appearance to override the system one?

Example: iPhone system appearance is set to 'Dark', App appearance is set to 'Light'. As of now, the shadow color change automatically still. I dug into the code; the only props for header shadow are `headerHideShadow` and `headerLargeTitleHideShadow`. It would be complementary to this library to be able to change the shadow color (dark || light) as is the case for `headerBlurEffect`. I hope I'm not missing anything.

**Comment by WoLewicki** [comment]
@wibb36 We are always open for PRs with new functionalities :tada:

**Comment by wibb36** [comment]
@WoLewicki I would but I'm not familiar with the native side's languages nor APIs. I will look into it when I have some free time

**Comment by happyfloat** [comment]
@wibb36 Did you find a solution for this by now?

**Comment by wibb36** [comment]
It's been some time, and I'm not quite up to date on the current state of React Native Screens.
