### ISSUE TITLE
[iPad] [14.2] setOptions headerRight headerLeft is not rendered

### ISSUE THREAD

**Issue by SDSLeon** [software-mansion/react-native-screens#733]
## Description

on ipad (ios 14.2) setOptions headerRight not working for stack in modals
for ios 12 all woking good
rootStack -> ModalStack as Modal -> Screen (workaround for header in modals)

### Screenshots
![image](https://user-images.githubusercontent.com/6071034/101024879-6c5ab480-357d-11eb-9209-f49a7cffd471.png)

## Steps To Reproduce
1. create root stack (createNativeStackNavigator) with screenOptions stackPresentation: 'modal'
![image](https://user-images.githubusercontent.com/6071034/101025268-04589e00-357e-11eb-9a0c-454ad2b9a151.png)
2. as component use another component with stack (createNativeStackNavigator) and one screen
3. use component here
4. inside component in componentDidMount call navigation 
![image](https://user-images.githubusercontent.com/6071034/101025433-3c5fe100-357e-11eb-8800-2e6211bd60cb.png)
5. bug present
6. i can fix it with setTimeout 100 for setOptions call
![image](https://user-images.githubusercontent.com/6071034/101025778-b728fc00-357e-11eb-917b-6d49a0501d23.png)

### Expected behavior
rightHeader render on screen for ipad os 14.2
### Actual behavior
rightHeader does not render on screen for ipad os 14.2

## Package versions
- React: 16.14
- React Native: 0.63.3
- React Native Screens: 2.15.0

**Comment by WoLewicki** [comment]
Can you provide a repo/snack with minimal configuration needed to reproduce the issue? It would be best if it could be added to `TestsExample` project to make the testing even easier.

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Comment by JB1905** [comment]
@WoLewicki I prepared [snack for the issue](https://snack.expo.io/@jbiesiada/ipad-rns-issue-demo). I have the same problem with `formSheet`.

**Comment by WoLewicki** [comment]
I tested your snack in [TestExample](https://github.com/software-mansion/react-native-screens/tree/master/TestsExample) project and cannot spot the issue there (see the screenshot). Do you use the newest `react-native-screens` version? If so, can you be more specific how to reproduce the issue? I tried going to page 2 and back multiple times and the `headerRight` is always there.
![image](https://user-images.githubusercontent.com/32481228/108706459-f37d5000-750e-11eb-9ce0-96881176b852.png)

**Comment by JB1905** [comment]
@WoLewicki I use `supportsTablet: true` in Expo `app.json`

**Comment by JB1905** [comment]
![7BFB9CB5-179E-4A28-A2EF-B4BD38B01867](https://user-images.githubusercontent.com/28870390/108724872-16ffc500-7526-11eb-844d-f171edd6b0e3.png)
![42ABED04-77A8-41C4-A174-9209F742349D](https://user-images.githubusercontent.com/28870390/108724891-1c5d0f80-7526-11eb-99d9-0bbb0c0038f9.png)

**Comment by WoLewicki** [comment]
So you are using Expo managed workflow? What SDK version are you using? Could you try and reproduce the issue in the bare RN project with the newest version of `react-native-screens`?

**Comment by JB1905** [comment]
I use managed workflow (SDK 40). I saw the issue in RNS supported (recommended) in SDK 40 and latest RNS version. I will check this in bare RN project.
