### ISSUE TITLE
[native-stack] Implement ability to set `isModalInPresentation`

### ISSUE THREAD

**Issue by iDuuck** [software-mansion/react-native-screens#736]
## Description

The implementation is fairly simple. I want a boolean toggle (preferably in the options of the screen) to toggle the screens `isModalInPresentation` for the transparent modals.

I will work on a PR, if I have the time to.

## Motivation

I think the motivation behind this one is pretty clear.

## Code example

N/A

**Comment by WoLewicki** [comment]
I think it is already available here: https://github.com/software-mansion/react-native-screens/blob/master/ios/RNSScreen.m#L154 by using `gestureEnabled` option in modals. Or do you mean something else?

**Comment by iDuuck** [comment]
No, sadly this is a difference. With `isModalInPresentation`, the modal can be dragged for about 20-30 pixels, and with `gestureEnabled` set to false, I am not able to drag at all.

**Comment by iDuuck** [comment]
@WoLewicki Have a look at this example: https://sarunw.com/posts/modality-changes-in-ios13/#a-simple-way

**Comment by WoLewicki** [comment]
I am not sure what you mean. Setting `gestureEnabled` to `false` in a screen that is a modal, resolves in setting `isModalInPresentation` to `true` on the native side. You can check an example here: https://github.com/software-mansion/react-native-screens/blob/master/TestsExample/src/Test577.js, it provides the same behavior as in the article you sent. What am I missing?

**Comment by iDuuck** [comment]
Super sorry, searched the repository for `isModalInPresentation`, but just found out that the Obj-C equiv is `modalInPresentation` and is set here: https://github.com/software-mansion/react-native-screens/blob/6d110d64356309ebac4d64e22d5b1f16b98c36bb/ios/RNSScreen.m#L153

Thanks!

**Comment by iDuuck** [comment]
Just a little heads up on this issue and a little RFC. I would *think* of `gestureEnabled` to disable all gestures (even the `modalInPresentation` thingy). And then I would think that an additional `modalInPresentation` prop should enable the `modalInPresentation` thingy. What do you think about this, @WoLewicki?

**Comment by WoLewicki** [comment]
I am not sure if I fully understand what you mean. The 'gesture' in this context means the ability to discard the screen with a gesture. The way to do this in normal presentation is swiping horizontally and for modal it is swiping vertically. What would be the benefit of adding another prop? You can specify the `gestureEnabled` prop per screen, so you can not add it in you modal screens if you don't want it there. Am I missing something?

**Comment by iDuuck** [comment]
You understood me correctly, but I don't know, if I am right. FWIW, the `gestureEnabled` prop (at least for the rest of the `react-navigation` family, is disabling the gestures *completely*).

My proposal:
- `gestureEnabled: true` → everything like normal
- `gestureEnabled: false` → Not even the small "peak" (currently, you have the ability to drag the screen 20px downwards, but not further)
- NEW: `modalInPresentation: true` → The functionality that is currently offered by `gestureEnabled: false`.

**Comment by WoLewicki** [comment]
For the second dot, I am afraid there is no possibility to disable the ability to do this small "peak" in the native implementation. If you find any code/thread, where people make it possible, please link it here.

**Comment by WoLewicki** [comment]
I am closing this issue since I believe there is nothing more we can do from the `react-native-screens` point of view. Feel free to comment if you find a solution or if something is wrong.

**Comment by WoLewicki** [comment]
@ypohrebennyk Unfortunately we did not come up with any better solutions. Please feel free to open a PR if you have an idea how could we manage that 🚀

**Comment by macalinao** [comment]
How could one add a PanResponder into a modal? It seems that when the modal jerks a bit, the PanResponder move events no longer get fired. Do you have any ideas? Thank you!
