### ISSUE TITLE
iphone 6 full screen video player gets hidden by transparentModal

### ISSUE THREAD

**Issue by Aryk** [software-mansion/react-native-screens#740]
## Description

On iphone 6, the full screen video starts playing (I can hear the audio), but it is behind the transparentModal. When I close the transparent modal, I see the full screen video that was playing underneath.

On iphone X, it works correctly.
 
## Package versions

- React: 16.13.1
- React Native Screens: ~2.10.1

**Comment by WoLewicki** [comment]
Can you provide a test example in TestsExample project (https://github.com/software-mansion/react-native-screens/tree/master/TestsExample) with minimal configuration needed to reproduce the issue? Also, what iOS version are you using on iPhone 6?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
