### ISSUE TITLE
Support for subtitle

### ISSUE THREAD

**Issue by hsavit1** [software-mansion/react-native-screens#741]
## Description
The iOS header has no support currently for a subtitle property. Can we get that added that to the roadmap?

**Comment by Hirbod** [comment]
You can add this by your own, since `headerCenter` accepts any view.

**Comment by WoLewicki** [comment]
Does @Hirbod answer solves your issue @hsavit1 ? If not, please provide some more information about the feature.

**Comment by hsavit1** [comment]
In some applications, like the GitHub iOS application, when the large header collapses on scroll, you see a regular sized header with a prominent centered title and a centered subtitle beneath it. I believe to achieve this with `headerCenter` you'd have to implement your own animation such that the view only appears on scroll?

**Comment by WoLewicki** [comment]
I cannot see anything else than small title in the GitHub iOS app, can you show a GIF/photo of what you mean exactly?

**Comment by Hirbod** [comment]
@hsavit1 yeah, with the current implementation, thats the way to go. So you want to have a single large header and a small header with subtitle after collapse, is that right?

**Comment by Hirbod** [comment]
I think he means this feature @WoLewicki 
https://streamable.com/jau5du

But this doesn't look like the default LargeHeader collapse. Its something custom.

**Comment by WoLewicki** [comment]
Oh this. I am afraid it is not a native iOS header at all, so I don't think there is anything I can do about it. It is probably some custom component with the animation coupled with the ScrollView's scrolling. Can I help you more regarding this?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Comment by Andarius** [comment]
Hey @WoLewicki, sorry for pinging you on this closed issue but I was wondering if it would be possible to add subtitle for the Android Toolbar https://developer.android.com/reference/android/widget/Toolbar#attr_android:subtitle.
I'm not sure if there is native way of doing it on iOS (React Native Navigation implemented their own: https://github.com/wix/react-native-navigation/blob/master/lib/ios/RNNTitleViewHelper.m).

**Comment by WoLewicki** [comment]
cc @kkafar do you think it is doable?

**Comment by kkafar** [comment]
I guess so, I'll add doing some more research & impl to my backlog.
