### ISSUE TITLE
[2.16.1] - Lazy loaded tabs renders stack headers without safe area insets.

### ISSUE THREAD

**Issue by owinter86** [software-mansion/react-native-screens#750]
## Description
The latest version (2.16.1) and more related to this merge https://github.com/software-mansion/react-native-screens/pull/712, has issues where the header insets are not applied if not using lazy loaded tabs from react navigation `lazy={false}`.

### Screenshots
<img src="https://user-images.githubusercontent.com/2920419/101982276-ff2cda80-3c72-11eb-878b-0390f9149199.png" width="300">

## Steps To Reproduce

1. Navigate to the last tab and then navigate to the next screen within that tab and you will see the header rendered with no top insets applied.

## Snack or minimal code example

```
import React from 'react';
import { View, Button } from 'react-native';
import { enableScreens } from 'react-native-screens';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from 'react-native-screens/native-stack';

enableScreens();

const Tab = createBottomTabNavigator();
export default function TabNav() {
  return (
    <NavigationContainer>
      <Tab.Navigator lazy={false}>
        <Tab.Screen name="Tab1" component={Tab1} />
        <Tab.Screen name="Tab2" component={StackNav} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}

const Stack = createNativeStackNavigator();
function StackNav() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="Screen1" component={Screen1} options={{ headerShown: false }} />
      <Stack.Screen name="Screen2" component={Screen2} />
    </Stack.Navigator>
  );
}

const Tab1 = () => <View style={{ flex: 1, backgroundColor: 'red' }} />;
const Screen1 = ({ navigation }) => (
  <View style={{ flex: 1, backgroundColor: 'green', justifyContent: 'center' }}>
    <Button title="navigate" onPress={() => navigation.navigate('Screen2')} />
  </View>
);
const Screen2 = () => <View style={{ flex: 1 }} />;
```

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Screens: 2.16.1

**Comment by hussainarthuna** [comment]
Experiencing the same issue.

**Comment by Cal-um** [comment]
Also have this issue

**Comment by hussainarthuna** [comment]
Any fixes or workaround??

**Comment by diegolmello** [comment]
I have a similar issue, but on the bottom inset and I was able to workaround by patching off #712

**Comment by Cal-um** [comment]
Can anyone confirm that the bug still happens when managing the status bar natively using https://github.com/software-mansion/react-native-screens/tree/master/native-stack#status-bar-and-orientation-managment

**Comment by WoLewicki** [comment]
Can you check if #772 fixes the issue and does not introduce any new bugs?

**Comment by Cal-um** [comment]
@WoLewicki Looks good to me. Not seen any obvious bugs.
