### ISSUE TITLE
Unresponsive interactions after navigating between screens on nested navigators.

### ISSUE THREAD

**Issue by limiaspasdaniel** [software-mansion/react-native-screens#774]
## Description

After switching to this library and specially after using `createNativeStackNavigator` on my app, I have noticed that touch events / interactions after navigating between screens are unresponsive or delayed in comparison to not using the library.

I have checked issue #95 , updated the library to the latest version, cleaned cache, rebuilt and I still notice the same issue.

## Steps To Reproduce

Navigation setup:

```
- Root  Stack Navigator
       |
       --------- Screen A (appears on top of bottom tab navigator when invoked, using "formSheet" stack presentation)
       --------- Screen B (appears on top of bottom tab navigator when invoked, using "formSheet" stack presentation)
       --------- Bottom Tab Navigator
                                                    |
                                                    |---- Tab A
                                                    |---- Tab B
                                                    |---- Tab C
                                                        
```
I have noticed the delay only happens when navigating from any of the Tab screens to Screen A or Screen B, going back and then trying to navigate again to one of those Screen A or Screen B.

### Expected behavior

There shouldn't be any frozen touch events when navigating between nested navigators

### Actual behavior

There is a delay or unresponsive interactions when navigating between nested navigators.
## Package versions

This is my setup: 

- React: 16.13.1
- React Native: 0.63.3
- React Native Screens: 2.16.1
- `"@react-navigation/bottom-tabs": "5.11.2"`
- `"@react-navigation/native": "5.8.10"`
- `"@react-navigation/stack": "5.12.8"`

**Comment by WoLewicki** [comment]
Please post this comment in #95 to avoid keeping the discussion in two places. I will close this issue and reopen #95. Feel free to comment here if something is wrong.

**Comment by limiaspasdaniel** [comment]
Thank you 👍
