### ISSUE TITLE
Backgrounding app automatically alters navigation state for native modals

### ISSUE THREAD

**Issue by smallfx** [software-mansion/react-native-screens#796]
## Description

I'm working on an app that uses React Navigation. We are aiming to use `react-native-screens` to increase the app's navigation performance.
We are seeing a show-stopping issue where the navigation state is automatically altered when the app is backgrounded. There is nowhere in our code that does this specifically (quintuple-checked, thoroughly) and this issue only appeared once we integrated `react-native-screens` to replace our stack navigators with native ones.

The issue is as described below.

## Steps To Reproduce

1. Configure a route that is a native modal which animates from the bottom of the screen.
2. Navigate to that previously mentioned route which summons the modal.
3. Background the app (swipe up on the "home bar" or press the home button on older devices).
4. Note that the modal was immediately dismissed.

### Expected behavior
It is expected that the navigation state should remain the same even if the app is backgrounded.

### Actual behavior
Instantly as the app is backgrounded, `react-native-screens`'s native modals are automatically dismissed.
I am not entirely clear whether this is the modal itself being dismissed first or a navigation event.

## Snack or minimal code example

The code, simplified, is roughly this:

```
import * as React from 'react';
import { Text, View, TouchableOpacity } from 'react-native';
import {createAppContainer} from 'react-navigation';
import {createNativeStackNavigator} from 'react-native-screens';

const Start = ({navigation}) => (
  <View>
    <TouchableOpacity onPress={() => navigation.navigate("Next")}>
      <Text>"Hello"</Text>
    </TouchableOpacity>
  </View>
);

const MainNav = createNativeStackNavigator({ Start: { screen: Start } });

const Next = ({navigation}) => (
  <View>
    <Text>"Modal"</Text>
  </View>
);


const AppNavigator = createNativeStackNavigator({
  Main: { screen: MainNav },
  Next: { screen: Next }
}, {
  mode: 'modal',
})

export default function App() {
  return <AppNavigator />;
}
```

## Package versions

- React: `^16.2.0`
- React Native: `0.63.3`
- React Native Screens: `^2.9.0`
- React Navigation: `^4.4.0`

**Comment by WoLewicki** [comment]
Does it still happen in the newest version or `React Native Screens`?

**Comment by WoLewicki** [comment]
I couldn't repro this on the example you provided in v. 2.18.1. Most probably it has been already resolved in one of the releases. I will close it then. Feel free to comment here if something is wrong.
