### ISSUE TITLE
add a changelog

### ISSUE THREAD

**Issue by sibelius** [software-mansion/react-native-screens#80]
it would be great to have a changelog to describe any feature or breaking changes

**Comment by slavikdenis** [comment]
Every release I try to look for one. This still would be much appreciated 👍 @kmagiera

**Comment by kmagiera** [comment]
Thank you for your input. We are currently focusing on stabilizing the library and there are still many moving parts. We pay a lot of attention to making commit messages provide valuable information about the changes. I'd be open to accepting community driven changelog if anyone feels like they'd like to invest their time into combining those messages into a more condensed message.

**Comment by WoLewicki** [comment]
All of the changes for the new version are now listed in https://github.com/software-mansion/react-native-screens/releases so I am closing this issue. Feel free to comment if you have any questions.
