### ISSUE TITLE
[ts] v5 native stack does not throw error when using unknown props on it

### ISSUE THREAD

**Issue by sbalay** [software-mansion/react-native-screens#809]
## Description

The type of `NativeStackNavigatorProps` is not narrowed down to only known props and does not generate a ts error when unknown props are specified to the Navigator component:

```
const RootStack = createNativeStackNavigator()

RootNavigator = () => {
  return (
    <RootStack.Navigator whatever unknownProp={3}>
      <RootStack.Screen
        name="Splash"
        component={SplashScreen}
      />
  </RootStack.Navigator>
``` 

The above code does not throw any ts error, even though `whatever` and `unknownProp` are not props of Navigator.

I believe this is caused by [NativeStackNavigationConfig](https://github.com/software-mansion/react-native-screens/blob/master/src/native-stack/types.tsx#L54) which is defined as `Record<string, unknown>` and then used to build the `NativeStackNavigatorProps` type.

`NativeStackNavigationConfig` does not seem to be used anywhere in the codebase, I was going to send a PR just deleting it but I'm not sure about the implications of doing so.

### Expected behavior

Navigator throws a ts error when unknown props are specified

### Actual behavior

Navigator does not throw a ts error when unknown props are specified

## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Screens: 2.16.1

**Comment by WoLewicki** [comment]
Can you check if #810 fixes it?

**Comment by sbalay** [comment]
> Can you check if #810 fixes it?

Yep!
