### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'void android.view.ViewRootImpl.semRemoveEditText(android.widget.EditText)' on a null object reference

### ISSUE THREAD

**Issue by NeronKesar** [software-mansion/react-native-screens#811]
Got this crash on Galaxy Tab S7 Android 11 only.
I'm using react-navigation v5 and react-native-screens 2.17.1.
Can anyone help me?

android.widget.EditText.onDetachedFromWindow (EditText.java:397)
com.facebook.react.views.textinput.ReactEditText.onDetachedFromWindow (ReactEditText.java:714)
android.view.View.dispatchDetachedFromWindow (View.java:22071)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.removeAllViewsInLayout (ViewGroup.java:6606)
android.view.ViewGroup.removeAllViews (ViewGroup.java:6552)
com.swmansion.rnscreens.ScreenContainer.onDetachedFromWindow (ScreenContainer.java:309)
android.view.View.dispatchDetachedFromWindow (View.java:22071)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4755)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.dispatchDetachedFromWindow (ViewGroup.java:4747)
android.view.ViewGroup.removeViewInternal (ViewGroup.java:6394)
android.view.ViewGroup.removeViewInternal (ViewGroup.java:6365)
android.view.ViewGroup.removeView (ViewGroup.java:6296)
com.swmansion.rnscreens.ScreenContainer.removeView (ScreenContainer.java:84)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1250)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1356)
androidx.fragment.app.FragmentManager.moveFragmentToExpectedState (FragmentManager.java:1434)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1504)
androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:2007)
androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:1953)
androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:1849)
androidx.fragment.app.FragmentManager$4.run (FragmentManager.java:413)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:246)
android.app.ActivityThread.main (ActivityThread.java:8506)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:596)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

**Comment by creambyemute** [comment]
@NeronKesar Weird! I just experienced the same error message/crash but with V2.15.0 and updated to V2.17.1 which fixed it for me.

**Comment by WoLewicki** [comment]
I am not sure if it is an issue with `react-native-screens`. The `ScreenContainer` just calls `onDetachedFromWindow` which is a normal behavior. If you think there is something that can be done on the side of `react-native-screens`, please provide a reproduction of the issue so we can work on it.

**Comment by creambyemute** [comment]
@WoLewicki I don't have a repro repo but In my case it was reproducable by:

* Device: Android 11 + OneUI 3.1
* Using RN-Screens V 2.15.0
* Calling `launchImageLibrary` from react-native-image-picker

As mentioned in the above comment, for me it works with RN-Screens V 2.17.1.

**Comment by creambyemute** [comment]
@WoLewicki This is still not a repro, sorry for that but:

I have experienced the same error (`void android.view.ViewRootImpl.semRemoveEditText(android.widget.EditText)' on a null object reference`) again on a different part of the app.  Samsung Android 11 again, but it also seems to happen on Android 8, 9 and 10 (at least according to the crash reports I got). Samsung only!

If I comment `enableScreens();` out, the error does not appear anymore.

I highly suspect the Samsung OneUI 3.0/3.1 update to be the root-cause at the moment.

**Comment by NeronKesar** [comment]
@creambyemute Thanks for your advice, commenting enableScreens() fixed the crash!

**Comment by WoLewicki** [comment]
@NeronKesar commenting `enableScreens()` removes the usage of `react-native-screens` in the project and disables all of the performance improvements, so I wouldn't treat it as a fix. 

Can you provide a whole stacktrace and a code snippet with an easy reproduction of the crash? Otherwise it is really hard to do something regarding the problem @creambyemute  @NeronKesar.

**Comment by creambyemute** [comment]
@WoLewicki I'll try to get a repro up for the weekend. Will let you know

**Comment by limaAniceto** [comment]
Hey there @NeronKesar, @WoLewicki and @creambyemute,
Sharing some information about this crash which hopefully helps (the stack trace seems exactly the same as @NeronKesar )

Device Model - Galaxy Tab S7
Device OS - Android 11
Orientation - Portrait
Rooted - No

Stack trace
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewRootImpl.semRemoveEditText(android.widget.EditText)' on a null object reference
       at android.widget.EditText.onDetachedFromWindow(EditText.java:397)
       at com.facebook.react.views.textinput.ReactEditText.onDetachedFromWindow(ReactEditText.java:714)
       at android.view.View.dispatchDetachedFromWindow(View.java:22071)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:6606)
       at android.view.ViewGroup.removeAllViews(ViewGroup.java:6552)
       at com.swmansion.rnscreens.ScreenContainer.onDetachedFromWindow(ScreenContainer.java:309)
       at android.view.View.dispatchDetachedFromWindow(View.java:22071)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4755)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:6394)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:6365)
       at android.view.ViewGroup.removeView(ViewGroup.java:6296)
       at com.swmansion.rnscreens.ScreenContainer.removeView(ScreenContainer.java:84)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1250)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1504)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2007)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8506)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
 ```

The crash doesn't happen on the simulator, probably it's a production build/specific device issue.

**Comment by luizdubas** [comment]
We are also having the same problem on a production app, we're using the version `2.18.1` of `react-native-screens` in there.

I was also able to simulate the same crash on a test project of mine using `react-native-screens` `2.17.1`: https://github.com/luizdubas/rn-screens-tablet-error
This project has a `BottomTabNavigator`, the first tab has a `TextInput` and every time I change to the next tab the app crashes.

Some important notes is that I was unable to simulate this on a simulator, I've used the [Samsung Remote Test Lab](https://developer.samsung.com/remote-test-lab) to test it. Also this seems to happen only on the Samsung Galaxy Tab S7 and S7+ using Android 11, the error doesn't seem to happen on Android 10.

**Comment by WoLewicki** [comment]
The crash appears in `ReactEditText` in calling `super.onDetachedFromWindow`, which fires this method on `android.widget.EditText`. It seems like a bug in the code of `android.widget.EditText` on Samsung Galaxy Tab S7 and S7+ with Android 11. Maybe you could submit an issue in `react-native` repository with this crash and reproduction? I am not sure if we can do anything about this unfortunately.

**Comment by luizdubas** [comment]
I think the only question that I would have is why this happens only when `react-native-screens` is enabled? 🤔 
Trying the same example but without enabling `react-native-screens` works without issues.

**Comment by WoLewicki** [comment]
Probably because of the specific order of lifecycle methods used by `react-native-screens`, but I cannot say much more.

**Comment by Nehal-Sanklecha** [comment]
+1

**Comment by hamzaouhssain1993** [comment]
Hello, everyone! Is there any update on the issue? Because we had the same one on galaxy tab 7 too with android 11. thanks a lot

**Comment by washimimizuku** [comment]
We are also having this problem, is anyone going to fix this? Would be really nice. Thanks

**Comment by it-hienvv** [comment]
The same issue, is anyone going to fix this ? Save my life. Thanks

**Comment by hamzaouhssain1993** [comment]
we used this patch to solve temporary the problem and waiting for a better one.
`diff --git a/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java b/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
index 3f53cc4..8b39847 100644
--- a/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
+++ b/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
@@ -306,7 +306,16 @@ public class ScreenContainer<T extends ScreenFragment> extends ViewGroup {
     // attept to re-attach it to with a misconfigured fragment. This would result in a crash. To
     // avoid it we clear all the children here as we attach all the child fragments when the container
     // is reattached anyways.
-    removeAllViews();
+    try {
+      removeAllViews();
+    } catch (NullPointerException e) {
+      // Workaround for Samsung Android bug:
+      // (android.widget.EditText.onDetachedFromWindow (EditText.java:397))
+      // Fatal Exception: java.lang.NullPointerException
+      // Attempt to invoke virtual method 'void android.view.ViewRootImpl.semRemoveEditText(android.widget.EditText)'
+      // on a null object reference
+      e.printStackTrace();
+    }
   }
 
   @Override
diff --git a/node_modules/react-native-screens/ios/RNSScreenContainer.m b/node_modules/react-native-screens/ios/RNSScreenContainer.m
index 2a00f28..03ab946 100644
--- a/node_modules/react-native-screens/ios/RNSScreenContainer.m
+++ b/node_modules/react-native-screens/ios/RNSScreenContainer.m
@@ -185,7 +185,7 @@ - (void)updateContainer
           // for screens that were already active we want to mimick the effect UINavigationController
           // has when willMoveToWindow:nil is triggered before the animation starts
           [self prepareDetach:screen];
-        } else if (![_activeScreens containsObject:screen]) {
+        } else if (![_activeScreens containsObject:screen] && screen.controller != nil) {
           [self attachScreen:screen atIndex:index];
         }
         index += 1;
`

**Comment by hamzaouhssain1993** [comment]
We used this patch to solve temporary the porblem.

CODE:


diff --git a/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java b/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
index 3f53cc4..8b39847 100644
--- a/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
+++ b/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java
@@ -306,7 +306,16 @@ public class ScreenContainer<T extends ScreenFragment> extends ViewGroup {
     // attept to re-attach it to with a misconfigured fragment. This would result in a crash. To
     // avoid it we clear all the children here as we attach all the child fragments when the container
     // is reattached anyways.
-    removeAllViews();
+    try {
+      removeAllViews();
+    } catch (NullPointerException e) {
+      // Workaround for Samsung Android bug:
+      // (android.widget.EditText.onDetachedFromWindow (EditText.java:397))
+      // Fatal Exception: java.lang.NullPointerException
+      // Attempt to invoke virtual method 'void android.view.ViewRootImpl.semRemoveEditText(android.widget.EditText)'
+      // on a null object reference
+      e.printStackTrace();
+    }
   }
 
   @Override
diff --git a/node_modules/react-native-screens/ios/RNSScreenContainer.m b/node_modules/react-native-screens/ios/RNSScreenContainer.m
index 2a00f28..03ab946 100644
--- a/node_modules/react-native-screens/ios/RNSScreenContainer.m
+++ b/node_modules/react-native-screens/ios/RNSScreenContainer.m
@@ -185,7 +185,7 @@ - (void)updateContainer
           // for screens that were already active we want to mimick the effect UINavigationController
           // has when willMoveToWindow:nil is triggered before the animation starts
           [self prepareDetach:screen];
-        } else if (![_activeScreens containsObject:screen]) {
+        } else if (![_activeScreens containsObject:screen] && screen.controller != nil) {
           [self attachScreen:screen atIndex:index];
         }
         index += 1;

**Comment by hamzaouhssain1993** [comment]
We used temporarily this patch to solve the problem and hopefully get a better one in the future: 

PATCH here
[patch.docx](https://github.com/software-mansion/react-native-screens/files/6614278/patch.docx)

**Comment by it-hienvv** [comment]
> We used temporarily this patch to solve the problem and hopefully get a better one in the future:
> 
> PATCH here
> [patch.docx](https://github.com/software-mansion/react-native-screens/files/6614278/patch.docx)

Thanks, You saved my life

**Comment by thaitd96** [comment]
> The same issue, is anyone going to fix this ? Save my life. Thanks



> We used temporarily this patch to solve the problem and hopefully get a better one in the future:
> 
> PATCH here
> [patch.docx](https://github.com/software-mansion/react-native-screens/files/6614278/patch.docx)



> We used temporarily this patch to solve the problem and hopefully get a better one in the future:
> 
> PATCH here
> [patch.docx](https://github.com/software-mansion/react-native-screens/files/6614278/patch.docx)

Thank you so much, bro

**Comment by thaitd96** [comment]
> We used temporarily this patch to solve the problem and hopefully get a better one in the future:
> 
> PATCH here
> [patch.docx](https://github.com/software-mansion/react-native-screens/files/6614278/patch.docx)

Thank you so much, bro

**Comment by truongducle94** [comment]
> We used temporarily this patch to solve the problem and hopefully get a better one in the future:
> 
> PATCH here
> [patch.docx](https://github.com/software-mansion/react-native-screens/files/6614278/patch.docx)

Many thanks, bro!!!!

**Comment by limaAniceto** [comment]
@hamzaouhssain1993 thank you for sharing that patch 🙏 

@WoLewicki Any chance you could review this patch and share your thoughts please?

**Comment by WoLewicki** [comment]
Based on the stacktrace, I think the root of the crash is the same as in https://github.com/software-mansion/react-native-screens/issues/913, where the `onDetachedFromWindow` is called more than once and the component is not ready for such a behavior. We will try and look for the solution of the problem and we are always open for PRs. The patch provided is for sure a good start, but it a workaround, not a solution, so I am afraid it is not enough.

**Comment by WoLewicki** [comment]
Can you check if #985 fixes the issue? It should address the problem of double detach.

**Comment by approached** [comment]
New version?
