### ISSUE TITLE
Header animation

### ISSUE THREAD

**Issue by Razorholt** [software-mansion/react-native-screens#812]
Since Expo doesn't accept version above 2.15.2, the headerCenter is very unstable. However, when I force the installation on the latest release, the headerCenter issue seems to be fixed but there is this header animation (left-to-right) of headerLeft and headerCenter. 
How can I disable that header animation or at least change the direction?

**Comment by WoLewicki** [comment]
What do you mean by forcing the installation on the latest release? In Expo managed workflow, it will only change JS implementation, which can lead to buggy/weird behavior. Also, can you post some GIFs/videos of this animation?

**Comment by Razorholt** [comment]
If I do `expo install react-native-screens` it installs version 2.15.2. So I tried `expo install react-native-screens@2.17.1` instead, which worked. 
However, that latest version brought a header animation while navigating from one screen to another that I would like to cancel. I should be able to get you a gif shortly. Thanks!

**Comment by WoLewicki** [comment]
It is not recommended to install the version of code which has a native part, different than the one provided by default in Expo SDK for the reasons mentioned in my previous comment.
