### ISSUE TITLE
native-stack doesn't play well with react-navigation initialState (on iOS at least)

### ISSUE THREAD

**Issue by MoOx** [software-mansion/react-native-screens#816]
## Description

In short, if you use react-navigation `initialState` (start the app with existing navigation history/state), some actions doesn't work and doesn't trigger error.
For example a formSheet with 2 items doesn't "initiate" correctly, so navigate() doesn't have any effect (and doesn't return to item 1 without formSheet layout). 
I first didn't found the reason of this weird problems I got (tap that navigation call  but didn't have any effect AND no error triggered) but [I tried to disable](https://github.com/MoOx/LifeTime/blob/6c7d455d325da136ce2b41be8f6eac104103f4ef/src/App.res#L123) some things and with "clean slate" on every app start, no issue.

## Steps To Reproduce

1. uncomment this initial state https://github.com/MoOx/LifeTime/blob/6c7d455d325da136ce2b41be8f6eac104103f4ef/src/App.res#L123
2. build the app
3. go to "Settings" tab, open "Welcome screen".
4. reload via react native "Reload" from debug menu.

### Expected behavior

Initial state should be correctly reloaded and navigation shouldn't be stuck

### Actual behavior

On iOS, Welcome Screen don't always reload, and if you tap "Welcome Screen" to have it opened, it doesn't work and triggers no error.

## Snack or minimal code example

https://github.com/MoOx/LifeTime/tree/6c7d455d325da136ce2b41be8f6eac104103f4ef

## Package versions

- React: 16.14.0
- React Native: 0.63.3
- React Native Screens:  b00a488
- "@react-navigation/native@^5.9.2":  version "5.9.2"

**Comment by WoLewicki** [comment]
Could you make a simple reproduction of the issue? I am afraid having such a big project, it has too much overhead to easily direct the source of the problem.

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
