### ISSUE TITLE
Drawer hideStatusBar breaks SafeAreaView on repeated navigation with screens enabled

### ISSUE THREAD

**Issue by somebody32** [software-mansion/react-native-screens#822]
## Description

When you have a Drawer navigation with `hideStatusBar` prop and screens enabled, repeated navigation to the same screen is setting SaveAreaView top inset to 0.

### Screenshots

 <img src="https://user-images.githubusercontent.com/25742/108512376-67c2b400-72c1-11eb-80f0-6a278f71b42b.gif" width="400" height="auto">

## Steps To Reproduce

1. open app, see that the green background does not cover status bar
2. go to Notifications, status bar is not covered
3. open drawer again and dismiss it or go to notifications again
4. status bar is covered with green

### Expected behavior
4. status bar should not be covered

## Snack or minimal code example

```jsx
import 'react-native-gesture-handler';
import {createDrawerNavigator} from '@react-navigation/drawer';
import {NavigationContainer} from '@react-navigation/native';
import {View, Text, Button} from 'react-native';
import React, {StrictMode} from 'react';
import {SafeAreaProvider, SafeAreaView} from 'react-native-safe-area-context';
import {enableScreens} from 'react-native-screens';

enableScreens();

const Drawer = createDrawerNavigator();

function Home({navigation}) {
  return (
    <SafeAreaView style={{flex: 1}}>
      <View
        style={{
          backgroundColor: 'green',
          flex: 1,
          alignItems: 'center',
          justifyContent: 'center',
        }}>
        <Text>Home</Text>
        <Button
          onPress={() => {
            navigation.openDrawer();
          }}
          title="open drawer"
        />
      </View>
    </SafeAreaView>
  );
}

function Notifications({navigation}) {
  return (
    <SafeAreaView style={{flex: 1}}>
      <View
        style={{
          backgroundColor: 'green',
          flex: 1,
          alignItems: 'center',
          justifyContent: 'center',
        }}>
        <Text>Notifications</Text>
        <Button
          onPress={() => {
            navigation.openDrawer();
          }}
          title="open drawer"
        />
      </View>
    </SafeAreaView>
  );
}

function App() {
  return (
    <StrictMode>
      <SafeAreaProvider>
        <NavigationContainer>
          <Drawer.Navigator initialRouteName="Home" hideStatusBar>
            <Drawer.Screen name="Home" component={Home} />
            <Drawer.Screen name="Notifications" component={Notifications} />
          </Drawer.Navigator>
        </NavigationContainer>
      </SafeAreaProvider>
    </StrictMode>
  );
}

export default App;

```

## Package versions

```
  "@react-navigation/drawer": "^5.12.3",
  "@react-navigation/native": "^5.9.2",
  "react": "16.13.1",
  "react-native": "0.63.4",
  "react-native-gesture-handler": "^1.10.1",
  "react-native-reanimated": "^1.13.2",
  "react-native-safe-area-context": "^3.1.9",
"react-native-screens": "^2.17.1"
```

**Comment by somebody32** [comment]
And looks like it happens only for devices without the notch (at least in simulators)

**Comment by WoLewicki** [comment]
Can you check if the issue is still there when you remove `SafeAreaView`? I tested it and looks like it is the problem and it does not play well with `react-native-screens`.

**Comment by somebody32** [comment]
@WoLewicki, sorry, I'm not following. The idea is to have `SafeAreaView`, so the content would not overlap Status Bar. In the example green background is just for visualization; in my real project text header + hamburger menu are moved up, so they could not be clicked anymore. Or have I misunderstood you?

**Comment by WoLewicki** [comment]
Sorry, I misunderstood what you were trying to achieve. I think the solution is to wrap every Screen of navigator with `SafeAreaProvider`, as suggested in https://github.com/th3rdwave/react-native-safe-area-context#safeareaprovider. Can I help you more with this?

**Comment by somebody32** [comment]
@WoLewicki, oh, thanks a lot! I've somehow missed this line: 
> You may need to add it in other places like the root of modals and routes when using react-native-screen.

But to understand, in my example, I'm wrapping `<NavigationContainer>` in `<SafeAreaProvider>`. According to the doc you've linked, I would assume that this is the root that should be wrapped and everything is done correctly.

But you're saying that I should do it for every screen, and this is really fixing the issue. But then the doc should be clarified, or there is an edge case that I'm missing? Thank you so much for your help!

**Comment by WoLewicki** [comment]
I am not too keen with the implementation of the library, but it may be related to usage of `ViewControllers` for each of the screens in the navigator, when using `react-native-screens`. Each screen perhaps requires the `SafeAreaProvider` to be under it. Maybe @janicduplessis could elaborate more on this. Can I help you any more regarding this issue or can we close it?

**Comment by somebody32** [comment]
Thanks a lot! Closing it then as soon as this is expected behavior
