### ISSUE TITLE
Input loose focus when an action is dispatched

### ISSUE THREAD

**Issue by KevinBrustolin** [software-mansion/react-native-screens#841]
## Description

When an action is dispatched, inputs seems to loose focus: cursor jump to end and keyboard close / open.

Don't know on which version this issue appear, but on 2.11.0 there is no problem. 

## Package versions

- React: 16.13.1
- React Native: 0.63.3
- React Native Screens: 2.18.1 (working if 2.11.0)
- Redux: 4.0.5
- Redux-thunk: 2.3.0
- React-redux: 7.2.2

**Comment by WoLewicki** [comment]
Can you provide a test example in TestsExample project (https://github.com/software-mansion/react-native-screens/tree/master/TestsExample) with minimal configuration needed to reproduce the issue?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.
