### ISSUE TITLE
native-stack animation does not fade in from the bottom on Android

### ISSUE THREAD

**Issue by 1natsu172** [software-mansion/react-native-screens#851]
## Description

When using `createNativeStackNavigator`, the animation is strange on Android.
Specifically, the animation scale from center(zoom-out-from-center), which is not a standard OS animation.

The official README for [createNativeStackNavigator](https://github.com/software-mansion/react-native-screens/tree/a46aaab4b594079cdce36ff0115f472f5249c506/createNativeStackNavigator)
 says to expect the standard OS animation of fading in from the bottom.
> By default the stack navigator is configured to have the familiar iOS and Android look & feel: new screens slide in from the right on iOS, fade in from the bottom on Android. On iOS, the stack navigator can also be configured to a modal style where screens slide in from the bottom.

The current animation is different from the expected behavior.

### Screenshots

<img src=https://user-images.githubusercontent.com/7282145/110764018-dfb74500-8295-11eb-9652-d029a4982464.gif width=320 />

## Steps To Reproduce

1. Build and run the Example in this repository on Android. https://github.com/software-mansion/react-native-screens/tree/a46aaab4b594079cdce36ff0115f472f5249c506/Example
2. Select menu the `Native stack bindings for RNN`
3. Select `PUSH` or `MODAL` to cause a navigation animation.

### Expected behavior

fade in animation from the bottom on Android

### Actual behavior

scale-from-center(zoom-out-from-center) animation on Android

## Snack or minimal code example

The Example of this repository.

https://github.com/software-mansion/react-native-screens/tree/a46aaab4b594079cdce36ff0115f472f5249c506/Example

## Package versions

- React: 16.13.1
- React Native: 0.63.0
- React Native Screens: 2.18.1

**Comment by kacperkapusciak** [comment]
Thank you for opening the issue. I'll investigate it and inform you if I find anything useful connected to this issue.

**Comment by kacperkapusciak** [comment]
Hi @1natsu172,
for adding a new screen onto the stack we use the default Android's `TRANSIT_FRAGMENT_OPEN`  - [see here](https://github.com/software-mansion/react-native-screens/blob/master/android/src/main/java/com/swmansion/rnscreens/ScreenStack.java#L178). What I want to say is we haven't change the default. To be sure that it hasn't changed from version to version I've checked every Android version from the newest up to 6.0 and the animation was exactly the same. I might be wrong tho and I'm open to discussion.

**Comment by 1natsu172** [comment]
@kacperkapusciak 
Thank you for your research. It is true that the value in the code looks like the default. I'm thinking that creating a new stack on top of the stack might result in this animation, but it's just a guess and I don't know the truth.

When I get some free time, I'll try to debug the Java code here as well. If I find out anything, I will reply again.

**Comment by AkshayAdiga1997** [comment]
Much needed. Any luck on this? @kacperkapusciak

**Comment by AkshayAdiga1997** [comment]
> Much needed. Any luck on this? @kacperkapusciak

Also, a prop to have customised height or height based on content inside would be really helpful. Thank you for such a great library and all your efforts!

**Comment by hehex9** [comment]
related discussion #770 , definitely need to use different animations depending on the device version 🤔️

**Comment by WoLewicki** [comment]
#848 `fade_from_bottom` animation should be what you need. Please comment here if something is wrong about it.
