### ISSUE TITLE
iOS Swipe Gesture Not Working Properly After 2.18.0

### ISSUE THREAD

**Issue by GoktuqCan** [software-mansion/react-native-screens#853]
## Description
We have two createNativeStackNavigator with one is in the other.
After updating to version 2.18.1 or 2.18.0, we're getting this weird behavior. When going back to previous screen with slow swipe gesture, screen releases itself from touch position. And if you want it to work, you have to do it really fast.

After I compare **2.18.0** with **2.17.1**, I found out this caused by the changes [here](https://github.com/software-mansion/react-native-screens/compare/2.17.1...2.18.0#diff-c27cca0a72136c4b43dbfb6319e61fef4204856916d56fc600d28ee798719291L389).
If I put this if check back to where it was in 2.17.1, problem is getting fixed.

### Screenshots
![RPReplay_Final1615887621 (1)](https://user-images.githubusercontent.com/15637944/111302829-e7476700-8664-11eb-9130-e6e9c5397c6c.gif)
## Steps To Reproduce

1. Put one of two createNativeStackNavigator into the other.

### Expected behavior
Works as in 2.17.1 .

### Actual behavior
Gesture not working with slow sliding.
## Package versions
- React: 16.13.1
- React Native: 0.63.4
- React Native Screens: 2.18.1
- @react-navigation/native: 5.9.3

**Comment by kacperkapusciak** [comment]
Hi @GoktuqCan,
I've tried nesting native-stack navigators in various ways and I've tested on both simulator and real device and I wasn't able to reproduce your issue. Could you provide a simple reproduction example eg. as [we have here](https://github.com/software-mansion/react-native-screens/blob/master/TestsExample/src/Test831.tsx)?

**Comment by kacperkapusciak** [comment]
Closing due to no response within 30 days.
