### ISSUE TITLE
docs issue activityState can't be 1?

### ISSUE THREAD

**Issue by wedelgaard** [software-mansion/react-native-screens#859]
According to the documentation the ```<Screen />``` component can have an activityState of 0, 1 or 2.

_"When activityState is set to 0, the parent container will detach its views from the native view hierarchy. When activityState is set to 1, the Screen will stay attached, but on iOS it will not respond to touches. We only want to set activityState to 1 for during the transition or e.g. for modal presentation, where the previous screen should be visible, but not interactive. When activityState is set to 2, the views will be attached and will respond to touches as long as the parent container is attached too."_

But when I look in the source code this is the style being applied to the parent ```<View />```

```
<View
        style={[
          style,
          ENABLE_SCREENS && enabled && activityState !== 2
            ? { display: 'none' }
            : null,
        ]}
        {...rest}
/>
```

So it seems like there's a mistake in the docs, or have I misunderstood something?

**Comment by WoLewicki** [comment]
`activityState` can take value of `1`. There should be a note in docs that the `activityState` of `1` is used when you need the previous `Screen` to be attached even after the transition, which takes place e.g. in `modal` presentation of `stack` navigator. The code you provided is from the `index.tsx`, which is meant for web only. IIRC, `react-native-screens` are currently not enabled on web in `react-navigation`, so this code is never used, but would probably be problematic for `modal` presentation mentioned earlier and for during the transition. I am open for PRs correctly managing this behavior.

**Comment by wedelgaard** [comment]
@WoLewicki thank you for your quick response. I'm not sure I follow. I've looked at this source code:

[master/src/index.tsx](https://github.com/software-mansion/react-native-screens/blob/master/src/index.tsx)

As far as I can tell it has nothing to do with web, and only react-native?

**Comment by WoLewicki** [comment]
There is also file `index.native.tsx`. For iOS and Android, this file will be taken.

**Comment by WoLewicki** [comment]
The code in `index.tsx` has been changed to properly behave with `activityState`. It will now only detach the screen if the `activityState === 0`. As I mentioned before, since there is `index.native.tsx`, the `index.tsx` was only used on web, but `react-navigation` had its own implementation there. Since `react-navigation` v6, this file will probably be used. Can I help you any more with this or can I close this issue @wedelgaard ?

**Comment by wedelgaard** [comment]
Thx I think can be closed :)
