### ISSUE TITLE
stackAnimation: 'slide_from_right' on Android uses the `slide_from_right` animation when calling navigation.reset

### ISSUE THREAD

**Issue by tomtargosz** [software-mansion/react-native-screens#865]
## Description
When using the 'slide_from_right' `stackAnimation` property on Android, pushing a routes makes the screen slide from the right side of the screen, whereas popping a route has the screen slide from the left side of the screen (as expected). However, if you call `navigaiton.reset` the new route is slid in from the right side of the screen instead of the left. On iOS, calling `navigation.reset` causes the screen to be slid in from the left side so I would believe this behavior should be consistent.

### Screenshots

**iOS:**

https://user-images.githubusercontent.com/7979579/112345439-06607d00-8c93-11eb-8fbc-41ca4a06faa9.mov

**Android:**

https://user-images.githubusercontent.com/7979579/112345460-0c565e00-8c93-11eb-8690-05d78b959a94.mov

## Steps To Reproduce

1. See code example (or https://github.com/tomtargosz/react-navigation-android-back-button/tree/slide_from_right-reset-issue)

### Expected behavior
- When calling `navigation.reset` on Android when `stackAnimation` is 'slide_from_right', the new screen should slide in from the left like calling `navigation.pop` does

### Actual behavior
- The new screen is sliding in from the right

## Snack or minimal code example
https://github.com/tomtargosz/react-navigation-android-back-button/tree/slide_from_right-reset-issue
```js
import React from "react";
import { View, Text, Button } from "react-native";

import { NavigationContainer } from "@react-navigation/native";
import { enableScreens } from "react-native-screens";
import { createNativeStackNavigator } from "react-native-screens/native-stack";

enableScreens();
const Stack = createNativeStackNavigator();

const App = () => {
  return (
    <NavigationContainer>
      <Stack.Navigator
        screenOptions={{
          stackAnimation: "slide_from_right",
        }}
      >
        <Stack.Screen
          name="Screen1"
          component={({ navigation }) => (
            <View style={{ flex: 1, justifyContent: "center" }}>
              <Text style={{ paddingBottom: 24, textAlign: "center" }}>
                Screen 1
              </Text>
              <Button
                title="PUSH TO SCREEN 2"
                onPress={() => navigation.push("Screen2")}
              />
            </View>
          )}
        />
        <Stack.Screen
          name="Screen2"
          component={({ navigation }) => (
            <View style={{ flex: 1, justifyContent: "center" }}>
              <Text style={{ paddingBottom: 24, textAlign: "center" }}>
                Screen 2
              </Text>
              <Button
                title="PUSH TO SCREEN 3"
                onPress={() => navigation.push("Screen3")}
              />
            </View>
          )}
        />
        <Stack.Screen
          name="Screen3"
          component={({ navigation }) => (
            <View style={{ flex: 1, justifyContent: "center" }}>
              <Text style={{ paddingBottom: 24, textAlign: "center" }}>
                Screen 3
              </Text>
              <Button
                title="RESET TO SCREEN 1 WITH INDEX OF 0"
                onPress={() =>
                  navigation.reset({
                    routes: [{ name: "Screen1" }],
                    index: 0,
                  })
                }
              />
            </View>
          )}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

export default App;

```

## Package versions

- React: 16.13.1
- React Native: 0.63.4
- React Native Screens: 2.18.1

**Comment by kacperkapusciak** [comment]
Hi @tomtargosz,
Thank you very much for this detailed description!🥇 
Could you check if changes made in (https://github.com/software-mansion/react-native-screens/pull/871) fixes your issue?

**Comment by tomtargosz** [comment]
@kacperkapusciak thank _you_ for the fast follow up on this! The fix works great! 😄
