### ISSUE TITLE
Example App fails to run

### ISSUE THREAD

**Issue by henrymoulton** [software-mansion/react-native-screens#870]
## Description

Cloning the repo and running the example fails to run.

`Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /Users/hmmoulto/Code/react-native-screens/src/native-stack/index.tsx: @babel/runtime/helpers/interopRequireDefault could not be found within the project.`

### Screenshots

![image](https://user-images.githubusercontent.com/30093692/112624830-047af300-8e26-11eb-8f08-b2e15e37fcb7.png)

## Steps To Reproduce

1. `git clone https://github.com/software-mansion/react-native-screens.git`
2. `cd react-native-screens/Example`
3. `yarn && npx pod-install`
4. `yarn ios`

### Expected behavior

Doesn't crash.

### Actual behavior

Crashes.

**Comment by WoLewicki** [comment]
Can you try and clear all of the cache and start it with `yarn start --reset-cache`? Also, did you `yarn` in the main folder of the project?

**Comment by kacperkapusciak** [comment]
As @WoLewicki stated above you probably forgot to run Metro bundler in a separate terminal window. Try these steps:

```bash
git clone https://github.com/software-mansion/react-native-screens.git
cd react-native-screens
yarn
cd Example
yarn && npx pod-install && yarn start # let it finish and leave it running
# open a new terminal window
cd react-native-screens/Example
yarn ios
```

I will close this issue. Feel free to comment here if these steps didn't solve your problem and I'll reopen it.
