### ISSUE TITLE
react-native-tab-view not pushing up header when headerLargeTitle is true

### ISSUE THREAD

**Issue by quachdev** [software-mansion/react-native-screens#880]
## Description

I am currently using `react-navigation` v5 with screens.

When scrolling through the content inside `TabView` from `react-native-tab-view` the header does not currently push up from scrolling the content. Scrolling on the TabView itself seems to be working.

I am not sure if this is how TabView is implemented. I have initially tried using [createMaterialTopTabNavigator](https://reactnavigation.org/docs/material-top-tab-navigator) as well but fell into the same result.

Any help is appreciated.

### Screenshots

Scrolling through content:

https://user-images.githubusercontent.com/11295669/113967272-a3c4c080-97fe-11eb-97ee-5b94f9593835.mov

Scrolling on the tab view:

https://user-images.githubusercontent.com/11295669/113966079-7545e600-97fc-11eb-96a1-68ddf3f4911e.mov

## Steps To Reproduce

1. Wrap TabView inside a ScrollView `<ScrollView contentContainerStyle={{ flex: 1 }}>`
2. TabView content has scrollable elements (FlatList, or ScrollView)
3. Scroll through TabView content

### Expected behavior
Scrolling inside the content should push up the header title

### Actual behavior
Header stays put

## Snack or minimal code example

`      <ScrollView contentContainerStyle={{ flex: 1 }}>
          <TabView
            ...
            renderScene={renderScene}
            renderTabBar={renderTabBar}
          />
      </ScrollView>
`

Eg content for TabView:

`      <ScrollView>
           <View style={{ backgroundColor: 'red', height: 1000, width: 375 }} />
      </ScrollView>
`
## Package versions
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-screens": "^3.1.0",
"@react-navigation/native": "^5.9.1",
"react-native-tab-view": "^3.0.0",

**Comment by kacperkapusciak** [comment]
Hi @quachdev,
Could you provide a full but minimal (with all necessary imports, components, variables etc.) code example that reproduces your issue? Try following [this guide](https://stackoverflow.com/help/minimal-reproducible-example). 
That would help us a lot. Thanks!

**Comment by kacperkapusciak** [comment]
Closing due to no response in 30 days.
