### ISSUE TITLE
[Native Stack Navigator] stackPresentation: 'modal' screen animation broken  with TextInput autoFocus and multiline set

### ISSUE THREAD

**Issue by KingAmo** [software-mansion/react-native-screens#899]
## Description
when navigate to a modal screen with TextInput autoFocus and multiline set, previous screen's animation broken  
### Screenshots

https://user-images.githubusercontent.com/29938227/116215768-8ee2a980-a77a-11eb-931d-2ec5c2f84ef0.mov

## Steps To Reproduce

1.

### Expected behavior
animation works
### Actual behavior
animation broken

## Snack or minimal code example
https://github.com/KingAmo/rnscreen-textinput-bug

## Package versions

- React: 17.0.1
- React Native:0.64.0
- React Native Screens:3.1.1

**Comment by KingAmo** [comment]
either set `autoFocus={false}` or `multiline={false}`,  the animation is ok

https://user-images.githubusercontent.com/29938227/116215433-43300000-a77a-11eb-84f3-c8f3f96a20ee.mov

**Comment by WoLewicki** [comment]
Can you check if the same happens in `react-native`'s `Modal` component and report back here? If so, I believe there is something wrong with implementation of `TextInput`.

**Comment by KingAmo** [comment]
> Can you check if the same happens in `react-native`'s `Modal` component and report back here? If so, I believe there is something wrong with implementation of `TextInput`.

@WoLewicki yes,  `react-native`'s `Modal` component also has this issue, i  have updated  the minimal reproduce example here https://github.com/KingAmo/rnscreen-textinput-bug

**Comment by WoLewicki** [comment]
Can you post that issue in the react-native's repo (https://github.com/facebook/react-native) then? I am not sure if we can do anything about it since it looks like not an issue with the `react-native-screens` implementation.

**Comment by Razorholt** [comment]
Here is how I solved that problem:

```
const InputFocus = useRef();

useLayoutEffect(() => {
   const unsubscribe = navigation.addListener("focus", () => {
      setTimeout(() => {
         InputFocus.current?.focus()
      }, 100)
   });
   return unsubscribe;
}, [navigation]);

<TextInput 
    ref={InputFocus} 
    autoFocus={false} 
    multiline 
    ... // rest of your props here
>
```

**Comment by WoLewicki** [comment]
I will close this issue since it looks like the issue of `TextInput` integration with modals, not something specific to `react-native-screens`. Feel free to comment here if you have any updates/comments.

**Comment by ferrannp** [comment]
@WoLewicki just tried this with `react-native-screens@3.20.0` and ` "@react-navigation/native-stack": "^6.9.13"` and yep, still broken. Same broken animation as OP.
