### ISSUE TITLE
When we use absolute positioned tab bar icon and I do enablesceens(true) in App.js then the tabbaricon gets cut off when using bottom tab navigator

### ISSUE THREAD

**Issue by IssueResolver-collab** [software-mansion/react-native-screens#911]
## Description
This issue is only present on android

## Steps To Reproduce

1.

## Package versions

- React:
- React Native:
- React Native Screens:

**Comment by kacperkapusciak** [comment]
Please fill in the issue template. Without this necessary information, we are unable to help you. 

After you fill in the template tag me in a comment and I'll reopen this issue.
