### ISSUE TITLE
After updating to version 3.0.0 (expo 41 SDK) dangerouslyGetParent always returns undefined

### ISSUE THREAD

**Issue by TomasSestak** [software-mansion/react-native-screens#936]
## Snack or minimal code example

https://snack.expo.io/@yolk/dangerouslygetparent

**Comment by WoLewicki** [comment]
You are not using anything related to `react-native-screens` in this snack, so I don't think it is an issue connected to this library. You also provide another `NavigationContainer` with `independent={true}` which makes the stack not treat the tab navigation as a parent navigator, which results in it not having a parent navigator. If you remove the nested `NavigationContainer`, you will get the parent navigator object. I will close this issue then. Feel free to comment here if something is wrong.
