### ISSUE TITLE
Building library with Screens

### ISSUE THREAD

**Issue by aleixo** [software-mansion/react-native-screens#94]
Hello

I am trying to build library with react-native-screens but i am having some troubles.

The docs say that if i pass `active={0}` to one screen, the container will detach if from the hierarchy.

It is not happening to me.

I have the following simple example:

```
export default class App extends Component {
  render() {
    return (
      <ScreenContainer>
        <Screen active={1}>
          <View><Text>Active</Text></View>
        </Screen>
        <Screen active={0}>
          <View><Text>Detached</Text></View>
        </Screen>
      </ScreenContainer >
    );
  }
}
```

The truth is that, on the screen after running `react-native run-android` i have the two text components on the screen.

Thank you

**Comment by gabrielbull** [comment]
Did you do `useScreens()`?

**Comment by aleixo** [comment]
Hi @gabrielbull yes i do.

Here is the example

````
import { useScreens, ScreenContainer, Screen } from 'react-native-screens';

useScreens();
export default function App() {
  return (
    <ScreenContainer>
      <Screen><Text>1</Text></Screen>
      <Screen active={1}>
        <Text>2</Text>
      </Screen>
      <Screen><Text>3</Text></Screen>
    </ScreenContainer>
  );
}
````

The three numbers appear on the screen. Wasn´t it supposed to appear only number "2"?

**Comment by WoLewicki** [comment]
I think this issue is outdated. Can I close it @aleixo ?

**Comment by aleixo** [comment]
Yes @WoLewicki.

Thank you.
