### ISSUE TITLE
Dismiss event doesn't fire on android hardware back press

### ISSUE THREAD

**Issue by petercarpenter-santander** [software-mansion/react-native-screens#942]
## Description

The documentation for `native-stack` states the following about the `dismiss` event:

> Event which fires when the current screen is dismissed by hardware back (on Android) or dismiss gesture (swipe back or down).

I'm attempting to use this event to update my app's state when the user navigates back, but observed that the dismiss event doesn't get fired when pressing the android hardware back button. It does however get fired on iOS when using the back/down swipe gesture.

## Steps To Reproduce

1. Add an event listener for the dismiss event on a screen
2. Navigate to that screen
3. Press the android hardware back button

### Expected behavior

The event listener should be called.

### Actual behavior

The event listener is not called.

## Snack or minimal code example

```typescript
// App.tsx

import {useNavigation} from '@react-navigation/core';
import {NavigationContainer} from '@react-navigation/native';
import React from 'react';
import {Button, SafeAreaView, Text, View} from 'react-native';
import {createNativeStackNavigator} from 'react-native-screens/native-stack';

const Stack = createNativeStackNavigator();

const Screen1 = () => {
  const nav = useNavigation();
  return (
    <View>
      <Text>Screen 1</Text>
      <Button title="Go to Screen 2" onPress={() => nav.navigate('Screen2')} />
    </View>
  );
};

const Screen2 = () => {
  return (
    <View>
      <Text>Screen 2</Text>
    </View>
  );
};

const App = () => {
  return (
    <SafeAreaView style={{flex: 1}}>
      <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen name="Screen1" component={Screen1} />
          <Stack.Screen
            name="Screen2"
            component={Screen2}
            listeners={{
              dismiss: () => {
                // This log should run when pressing the android hardware back button on screen 2
                console.log('DISMISSED');
                // it does not
              },
            }}
          />
        </Stack.Navigator>
      </NavigationContainer>
    </SafeAreaView>
  );
};

export default App;
```

## Package versions

I created a fresh RN project and installed the latest version of RN screens to test this out in isolation using the example above:

- React: 17.0.1
- React Native: 0.64.0
- React Native Screens: 3.2.0

But I originally observed the issue in another app which is using slightly older versions:

- React: 16.9.0
- React Native: 0.61.5
- React Native Screens: 2.15.2

**Comment by petercarpenter-santander** [comment]
I spent some time looking into this and I think I've found the problem, and have a temporary solution, but not sure about how we can address it properly.

The problem is as follows:

The function `setupBackHandlerIfNeeded` in `ScreenStack.java` is expecting to be handling the back button presses (with the whole "fake" fragment transaction thing), but actually the back button presses are being handled by `useBackButton` in `NavigationContainer.tsx`, which is part of  `@react-navigation/native` [here](https://github.com/react-navigation/react-navigation/blob/696aa7eb9b9d56ad51b62fee8fcb0c5846803044/packages/native/src/NavigationContainer.tsx#L56).

If I remove that line in `NavigationContainer.tsx`, instead of being handled by the fragment manager, the back presses now stop being handled at all, the app just exits instead. This is because before adding the fake transaction to the back stack, it checks `topScreen.isDismissable()`, which checks `mScreenView.isGestureEnabled();`, which is always false, due to [this line](https://github.com/software-mansion/react-native-screens/blob/a6ec0dc95c118fd731f4db8145d07bc7ba4c1ebc/src/native-stack/views/NativeStackView.tsx#L156).

If I change `gestureEnabled` to always be true on android, then the back presses get handled and the dismiss event emits correctly! The only problem is that I was seeing a strange glitchy animation when navigating back to the previous screen... I managed to fix that by changing the fragment transaction to first hide the screen, then show it, instead of just showing it (I think this was the intended behaviour).

So altogether it works perfectly with these two patches (generated with [patch-package](https://www.npmjs.com/package/patch-package))

```
diff --git a/node_modules/@react-navigation/native/src/NavigationContainer.tsx b/node_modules/@react-navigation/native/src/NavigationContainer.tsx
index 9e75f90..9097a77 100644
--- a/node_modules/@react-navigation/native/src/NavigationContainer.tsx
+++ b/node_modules/@react-navigation/native/src/NavigationContainer.tsx
@@ -10,7 +10,6 @@ import LinkingContext from './LinkingContext';
 import useThenable from './useThenable';
 import useLinking from './useLinking';
 import useDocumentTitle from './useDocumentTitle';
-import useBackButton from './useBackButton';
 import type { Theme, LinkingOptions, DocumentTitleOptions } from './types';
 
 type Props = NavigationContainerProps & {
@@ -50,7 +49,6 @@ const NavigationContainer = React.forwardRef(function NavigationContainer(
 
   const refContainer = React.useRef<NavigationContainerRef>(null);
 
-  useBackButton(refContainer);
   useDocumentTitle(refContainer, documentTitle);
 
   const { getInitialState } = useLinking(refContainer, {

```

```
diff --git a/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStack.java b/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
index 4e29b97..5a21fdc 100644
--- a/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
+++ b/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStack.java
@@ -311,6 +311,7 @@ public class ScreenStack extends ScreenContainer<ScreenStackFragment> {
     if (topScreen != firstScreen && topScreen.isDismissable()) {
       mFragmentManager
               .beginTransaction()
+              .hide(topScreen)
               .show(topScreen)
               .addToBackStack(BACK_STACK_TAG)
               .setPrimaryNavigationFragment(topScreen)
diff --git a/node_modules/react-native-screens/src/native-stack/views/NativeStackView.tsx b/node_modules/react-native-screens/src/native-stack/views/NativeStackView.tsx
index 30775c5..7be1827 100644
--- a/node_modules/react-native-screens/src/native-stack/views/NativeStackView.tsx
+++ b/node_modules/react-native-screens/src/native-stack/views/NativeStackView.tsx
@@ -81,7 +81,7 @@ export default function NativeStackView({
           <Screen
             key={route.key}
             style={StyleSheet.absoluteFill}
-            gestureEnabled={isAndroid ? false : gestureEnabled}
+            gestureEnabled={isAndroid ? true : gestureEnabled}
             replaceAnimation={replaceAnimation}
             stackPresentation={stackPresentation}
             stackAnimation={stackAnimation}

```

I'd like to create a PR with the fixes for this library, but not sure what to do about the conflict with `@react-navigation/native`. Obviously disabling the back button handling is not a good general solution, as you'll likely want that behaviour when using other navigators, so maybe it needs to have some awareness of when the native navigator is being used?

**Comment by WoLewicki** [comment]
All of your findings are right, but I intentionally removed the option for dismissing on the native side with hardware back button in this PR: https://github.com/software-mansion/react-native-screens/pull/496 due to problems with `ScreenStack`. The information in documentation is wrong since the `dismiss` event is fired only when the navigation action was dispatched on the native side and after it ended, we want to update JS navigation stack, so for now these moments are: default native header back button both on iOS and Android and dismiss swipe gesture on iOS. Hardware back button on Android and navigating from JS with e.g. `navigation.goBack()` changes the JS stack automatically so the `dismiss` event has no meaning there.
That being said, why do you want to listen to that event? Native-stack has `transitionStart/End` events for native navigation and you can also listen on `navigation` events concerning navigating from JS. Can I help you more with that?

**Comment by WoLewicki** [comment]
I think it is good to add that `dismiss` event is dispatched on the native side every time the screen is dismissed, either due to JS or native navigation. But since `react-navigation` library works in a way that it removes the screen from its stack the moment you dispatch the e.g. `pop` action, the screen being dismissed is already not present in the React DOM, so the events sent from the native side are not received on the JS side. We still "cache" the view of dismissed screen and animate it's popping if requested by the user in `stackAnimation`.

**Comment by petercarpenter-santander** [comment]
Okay I understand, thanks for the detailed explanation! The reason I was looking to use the `dismiss` event, rather than `transitionEnd`, is because I wanted the behaviour of only emitting specifically when swiping back or pressing the hardware back button, as it will effectively allow me to organise my code in a neater way. 

I'm managing state in my app using xstate and the aim is to have the navigation defined entirely declaratively, mapping all states to specific screens, then pushing/popping automatically when the state changes. This is working great so far, but I'll outline the situation in which `dismiss` is useful:

1. I'm in state A, which is mapped to screen 1, so I am currently on screen 1
2. the user presses something, we update the state to state B, which is mapped to screen 2, so screen 2 gets pushed
3. the user presses something, we update the state back to state A, so screen 2 gets popped
4. the user presses something, back to state B, screen 2 gets pushed
5. the user presses the hardware back button, screen 2 gets popped (by react-navigation, not my mapping logic), I have a dismiss event handler on screen 2 that updates the state back to state A

If I don't have that dismiss event, I have to handle the back presses myself instead of letting react-navigation handle them, which makes the code a lot more messy. Additionally I can use the same event to handle the equivalent case on iOS with a back swipe, I don't need two separate implementations.

My next question would then be, is there anywhere else (in the native or js side) we can emit that dismiss event so it works in the same way? If not then we'll have to at least update the documentation to state that event is iOS only.

**Comment by WoLewicki** [comment]
You should be able to specify your handler of back button: https://reactnavigation.org/docs/custom-android-back-button-handling. Isn't that enough to cover all cases? `dismiss` for swipe/header back button and this for hw back button.

**Comment by petercarpenter-santander** [comment]
I can definitely make it work using `BackHandler` directly, its just a much less elegant solution than doing it all in one place with the dismiss event. It seems I'm probably in quite a unique situation with my routing logic though, as nobody else has brought this up before...

**Comment by WoLewicki** [comment]
Yeah, `dismiss` event was treated rather as an internal option since `transitionStart/End` events were released. You can stil try and make back handler use only native option by disabling the `react-native` implementation of it and fixing the native behavior, but I am afraid it might be rather hard.

**Comment by WoLewicki** [comment]
I will close this issue since I think there is not much to be added here. Feel free to comment here if you have something to add and we can reopen it.
