### ISSUE TITLE
TvOS compiling issues

### ISSUE THREAD

**Issue by henninghall** [software-mansion/react-native-screens#950]
## Description

The package is not compiling on TvOS version 3.2.0 and 3.3.0
It successfully compiles on version 3.1.1

## Package versions

- React: 16.13.1
- React Native: npm:react-native-tvos@0.63.1-4
- React Native Screens: 3.2.0 or 3.3.0

**Comment by henninghall** [comment]
I have seen that this issue has been present in the past too. It would be nice to for instance have a github action running a tvOS build to prevent this issue to reoccur.

**Comment by surafelbm** [comment]
@henninghall , were you able to fix this?

**Comment by henninghall** [comment]
Nope, using version 3.1.1 meanwhile

**Comment by WoLewicki** [comment]
Can you provide the fragment of code that makes it not compile? Also, we are open to PRs adding such github action.

**Comment by Kazetsukai** [comment]
Took a stab at this with #984

**Comment by henninghall** [comment]
That's great!
