### ISSUE TITLE
How to set headertitle center in android like ios?

### ISSUE THREAD

**Issue by BooYeu** [software-mansion/react-native-screens#960]
Does it have any props to control header title align , I want to set headertitle center in android like ios~~~

**Comment by BooYeu** [comment]
native stack

**Comment by kacperkapusciak** [comment]
Hi @BooYeu,
There isn't a property to directly control title alignment but you could use `headerCenter` property to provide your own title in the center of the header and style it to your needs:
```Javascript
headerCenter: () => <Text>Title</Text>
```
https://github.com/software-mansion/react-native-screens/tree/master/native-stack#headercenter

**Comment by kacperkapusciak** [comment]
I'll move this to discussions because it's a question, not a bug report.
