### ISSUE TITLE
No need to run enableScreens()

### ISSUE THREAD

**Issue by xylini** [software-mansion/react-native-screens#973]
As of version 3.0.0 `You no longer need to call enableScreens() at the top of your application` ([click](https://github.com/software-mansion/react-native-screens/releases/tag/3.0.0))

https://github.com/software-mansion/react-native-screens/blob/b5171609cf8b0455aca0ad9710aff3f997cea1a6/Example/App.tsx#L30

**Comment by WoLewicki** [comment]
Thanks @xylini! We will update it ASAP. Or maybe you want to submit a PR with such a change?
