### ISSUE TITLE
[native-stack] Header randomly goes white, loses styles

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/react-native-screens#977]
## Description

I'm using `native-stack`. The header on one screen randomly goes white, even though it should be gray. The title font family also loses style.

### Screenshots

Watch when I open the `Account` screen. Notice how the header keeps going white (incorrectly). After multiple quits, it finally works and becomes the correct color. 🤷🏼‍♂️

https://www.loom.com/share/ed22f7fd56cd4a449dec47c9a59f068d

## Steps To Reproduce

Honestly, no idea. It's totally random when this happens. My best guess is the fact that this header has a `headerRight` set, since it's the only screen where this happens, and also the only screen with `headerRight`.

This is what my screen looks like:

```jsx
<Screen
  name="User"
  component={UserProfileScreen}
  options={{
    title: 'Account',
    headerRight: function HeaderRight() {
      return <SignoutLink />
    }
  }}
/>
```

And for reference, this is my navigator:

```jsx
<Navigator
      screenOptions={{
        contentStyle: {
          backgroundColor: colors.background,
        },
        headerStyle: {
          backgroundColor: colors.muted,
        },
        headerTitleStyle: {
          color: colors.text,
          fontFamily: font.bold, 
        },
        headerTintColor: colors.primary, 
      }}
      initialRouteName={initialRouteName}
    >
```

### Expected behavior

The header should always be styled correctly.

### Actual behavior

The header randomly flickers white on certain occasions, but not on others. See the video above.

## Snack or minimal code example

Sorry, I haven't been able to reproduce this yet. It's very inconsistent.

## Package versions

- React: `16.13.1`
- React Native: `0.63.4`
- React Native Screens: `~3.0.0`

**Comment by kacperkapusciak** [comment]
Hi @nandorojo 👋 
I'm pretty sure this issue [was fixed](https://github.com/software-mansion/react-native-screens/pull/847) in v3.1.0. You can check the original issue for this [here](https://github.com/software-mansion/react-native-screens/issues/844). Could you check if your issue persists in `react-native-screens` >=3.1.0?

**Comment by nandorojo** [comment]
Sure, I'll check!

**Comment by kacperkapusciak** [comment]
I'll close this as I previously stated I'm pretty sure it shouldn't occur in the newest version. If it still persists - let me know and I'll reopen the issue.

**Comment by nandorojo** [comment]
Sounds good. I've been slow to respond since my app keeps crashing at startup since updating, but I haven't been able to reproduce that it's due to Screens yet, so I'm still figuring that out.

**Comment by nandorojo** [comment]
I'm using 3.4.0 and it works well now! Thanks for the help.

**Comment by pe-johndpope** [comment]
I'm seeing this on ios 14.4 simulator - ios 15 works fine.

**Comment by waheedakhtar694** [comment]
@WoLewicki I still have the same issue I am using `3.13.1` of `react-native-screens` with IOS `14.1`, Can you please suggest some solution for this.

**Comment by pe-johndpope** [comment]
this will help ship app - but be sure to add comments in react that these values are being overridden.
It will be hard to work out what's going on.


android manifest

  <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      **android:theme="@style/AppTheme">**
styles.xml
```xml
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:forceDarkAllowed">false</item>
        <item name="colorPrimary">#0DCAD0</item>
        <item name="colorPrimaryDark">#0DCAD0</item>
        <!-- <item name="android:textColorPrimary">#FFFFFF</item> -->

        <!-- <item name="colorAccent">#0DCAD0</item>
        <item name="android:navigationBarColor">#0DCAD0</item>
        <item name="android:statusBarColor">#0DCAD0</item>
        <item name="android:colorPrimaryDark">#0DCAD0</item>
        <item name="android:colorAccent">#FFFFFF</item>
        <item name="android:colorPrimary">#0DCAD0</item> -->
    </style>

</resources>

```
ios / appdelegate.m
```objective-c

if (@available(iOS 15, *)) {
    // iOS 15 (or newer) ObjC code
} else {
   NSDictionary *settings = @{
    UITextAttributeTextColor            :  [UIColor whiteColor],
    UITextAttributeTextShadowColor      :  [UIColor clearColor],
    UITextAttributeTextShadowOffset     :  [NSValue valueWithUIOffset:UIOffsetZero]};


  [[UINavigationBar appearance] setTitleTextAttributes:settings];
  [[UINavigationBar appearance] setTintColor:[UIColor whiteColor]];
  [[UINavigationBar appearance] setBarTintColor:[UIColor colorFromHexString:@"#0DCAD0" ]];
}

```

these values fix the grey / white overlay for me.

**Comment by waheedakhtar694** [comment]
@pe-johndpope i am guessing this will make color static we cannot switch between dark and light mode.

**Comment by johndpope** [comment]
Check documentation.
For iOS there’s a way to say backgroundcolor as opposed to white.
For android maybe something similar.

**Comment by johndpope** [comment]
I’d search GitHub for those words with Darkmode - here’s offciial docs for apple https://developer.apple.com/documentation/uikit/appearance_customization/supporting_dark_mode_in_your_interface
