### ISSUE TITLE
[ios] large title on scroll & on orientation change weird behavior  ?

### ISSUE THREAD

**Issue by a-eid** [software-mansion/react-native-screens#990]
### Screenshots

![on scroll](https://user-images.githubusercontent.com/19273413/122591768-bad82800-d063-11eb-9309-2fe6a12f2080.gif)
![on orientation](https://user-images.githubusercontent.com/19273413/122591785-c1669f80-d063-11eb-8497-6553c1c6b332.gif)

## Package versions

- React: 17.0.1
- React Native: 0.64.2
- React Native Screens: ^3.4.0

**Comment by kacperkapusciak** [comment]
Can you please provide a minimal complete reproducible code sample?

**Comment by a-eid** [comment]
Will provide one, but I've literally done nothing other than adding the title

**Comment by a-eid** [comment]
will reopen with a reproducible example repo.

**Comment by a-eid** [comment]
this repo include a reproducible example of the issue(s)

https://github.com/a-eid/RNSBug

large title goes off screen when orientation change.

not sure how to describe the second issue but the large title should animate back to large since the scrollview is empty,

**Comment by WoLewicki** [comment]
About the second issue, see: https://github.com/software-mansion/react-native-screens/issues/320#issuecomment-670469660. About the 

> large title goes off screen when orientation change.

I am not sure what do you mean by it. In the repro, the header transitions normally landscape-portrait both on simulator and physical phone. I haven't been able to reproduce the behavior from the provided GIF.

**Comment by a-eid** [comment]
I will re test on a non m1 machine and a physical device

**Comment by a-eid** [comment]
@WoLewicki I am still seeing the first (gif) issue when using a tabbar, for the first tab the large header look to work fine, but for other tabs it does not.


https://user-images.githubusercontent.com/19273413/127714262-5da3de67-3f58-4ea3-95a3-59188fc242de.mp4

**Comment by WoLewicki** [comment]
@a-eid is it still the issue? Or did you close it on purpose?
