### ISSUE TITLE
Stacking multiple screens with "stackPresentation: 'modal'"

### ISSUE THREAD

**Issue by tizzle** [software-mansion/react-native-screens#997]
## Description

I'm opening a screen (ModalOne) with `stackPresentation: 'modal'` and i navigate to another screen (ModalTwo) with `stackPresentation: 'modal'`. When doing this the second modal opens with a broken animation and when the second modal is closed, the modal-screen-overlay-effect is dismissed, leaving the first modal with a broken status bar area where parts of the underlying screen are showing through.

### Screenshots

![IMG_0508](https://user-images.githubusercontent.com/2727786/123874946-2ad69000-d939-11eb-9031-9a2e717a48d3.jpg)

## Steps To Reproduce

1. See this Snack: https://snack.expo.io/4_T9ryjcL
2. Open the first modal by pressing the button
3. Open the second modal from the first modal

### Expected behaviour

The modal stack should allow to stack multiple modals on top of each other without any glitches.

### Actual behaviour

There are animation glitches and a persisting visual glitch in the status bar area.

## Snack or minimal code example

https://snack.expo.io/4_T9ryjcL

## Package versions

- React: "react": "16.13.1",
- React Native: "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
- React Native Screens: "react-native-screens": "~3.0.0",

**Comment by tizzle** [comment]
I just found out that in some cases this glitch does not appear. It seems to NOT happen when i scroll a bit in the first modal (like pulling it down a bit and letting it snap back). When i open the second modal after doing this, the stacking works as expected.

**Comment by WoLewicki** [comment]
I tested it in non-expo project and the glitch does not happen there. Also, could you test if the same issue exists when you use `Modal` components from `react-native` in Expo?

**Comment by tizzle** [comment]
Hey @WoLewicki,

thanks for looking into this.

I just set up a small expo snack using the react-native `Modal` components. It shows the same behaviour, i think. Take a look for yourself please: https://snack.expo.io/0Wv53mC9P

I fear this means you cannot help much, right? Underlying issue in react-native, huh?
Still, thanks so much for maintaining this library and big ups to the whole Software Mansion team.

Cheers,

Till

**Comment by WoLewicki** [comment]
Yeah, I am afraid it is not an issue of `react-native-screens` then so we cannot do much about it. I would recommend for you to submit an issue in Expo with the reproduction, maybe they will manage to resolve it. Also, thanks for the kind words, always great to hear them 😄 
I will close this issue then, feel free to comment if something is wrong or you have an update.
